style

diff --git a/misc/cmdboot b/misc/cmdboot
--- a/misc/cmdboot
+++ b/misc/cmdboot
@@ -156,6 +156,7 @@ touch \
 uname \
 tr \
 truncate \
+ulimit \
 umount \
 uuidgen \
 whoami \
@@ -168,6 +169,11 @@ wc \
 
 # check by FreeBSD version, since the misc/elf_tables may be absent on first init
 _version=$( sysctl -n kern.osreldate 2>/dev/null )
+
+if [ -z "${_version}" ]; then
+	echo "unable to get sysctl kern.osreldate"
+	exit 1
+fi
 
 if [ ${_version} -lt 1300131 ]; then
 	# https://svnweb.freebsd.org/base?view=revision&revision=r368045
diff --git a/sudoexec/initenv b/sudoexec/initenv
--- a/sudoexec/initenv
+++ b/sudoexec/initenv
@@ -268,6 +268,10 @@ phase1()
 
 	if [ "${initenv_modify_cbsd_homedir}" = "1" ]; then
 		# check for correct homedir
+		if [ ! -r /etc/master.passwd ]; then
+			echo "no such /etc/master.passwd file"
+			exit 1
+		fi
 		cbsd_home=$( grep ^cbsd /etc/master.passwd | cut -d : -f 9 )
 		[ "${cbsd_home}" != "${workdir}" ] && pw usermod ${cbsduser} -d ${workdir} >/dev/null 2>&1
 	else
@@ -284,7 +288,12 @@ phase1()
 	printf "${myversion}" > ${workdir}/ver
 
 	$ECHO "${N1_COLOR} * Check hier and permission..."
-	mtree -deU -f ${distdir}/etc/cbsd.mtree -p ${workdir}
+	MTREE_CMD=$( which mtree 2>/dev/null )
+	if [ ! -x "${MTREE_CMD}" ]; then
+		echo "initenv error: no such command: mtree"
+		exit 1
+	fi
+	${MTREE_CMD} -deU -f ${distdir}/etc/cbsd.mtree -p ${workdir}
 	env workdir=${workdir} ${distdir}/misc/cmdboot
 	_ret=$?
 	if [ ${_ret} -ne 0 ]; then
