cmdboot: work via temporary file

diff --git a/misc/cmdboot b/misc/cmdboot
--- a/misc/cmdboot
+++ b/misc/cmdboot
@@ -234,16 +234,16 @@ case "${platform}" in
 		;;
 esac
 
-truncate -s0 ${CMD_FILE}
+truncate -s0 ${CMD_FILE}.tmp
 
-cat > ${CMD_FILE} <<EOF
+cat > ${CMD_FILE}.tmp <<EOF
 if [ ! "\$_CBSD_CMD_SUBR" ]; then
 _CBSD_CMD_SUBR=1
 ###
 EOF
 	if [ $? -ne 0 ]; then
-		echo "cmdboot: append error: ${CMD_FILE}"
-		cat >> ${CMD_FILE} <<EOF
+		echo "cmdboot: append error: ${CMD_FILE}.tmp"
+		cat >> ${CMD_FILE}.tmp <<EOF
 ###
 fi
 EOF
@@ -259,7 +259,7 @@ for i in ${MAIN_CMD}; do
 
 	if [ -z "${mycmd}" -a ! -x "${mycmd}" ]; then
 		echo "cmdboot: no such executable, CBSD dependency/requirement: ${i}"
-		cat >> ${CMD_FILE} <<EOF
+		cat >> ${CMD_FILE}.tmp <<EOF
 ###
 fi
 EOF
@@ -268,7 +268,7 @@ EOF
 	MY_CMD=$( echo ${i} | tr '\-[:lower:]' '_[:upper:]' )
 	MY_CMD="${MY_CMD}_CMD"
 
-	echo "${MY_CMD}=\"${mycmd}\"" >> ${CMD_FILE}
+	echo "${MY_CMD}=\"${mycmd}\"" >> ${CMD_FILE}.tmp
 done
 
 for i in ${OPTIONAL_CMD}; do
@@ -291,7 +291,7 @@ for i in ${OPTIONAL_CMD}; do
 
 		if [ -n "${feature}" ]; then
 			if [ -h ${dbdir}/local.sqlite ]; then
-				echo "    cmdboot: no such optional executable: ${i}, ${feature} disabled"
+				echo "    cmdboot: no such optional executable: ${i}, ${feature} disabled" 1>&2
 				sqlite3 ${dbdir}/local.sqlite "UPDATE local SET ${feature}=\"0\""
 			fi
 		fi
@@ -300,11 +300,25 @@ for i in ${OPTIONAL_CMD}; do
 	MY_CMD=$( echo ${i} | tr '\-[:lower:]' '_[:upper:]' )
 	MY_CMD="${MY_CMD}_CMD"
 
-	echo "${MY_CMD}=\"${mycmd}\"" >> ${CMD_FILE}
-
+	echo "${MY_CMD}=\"${mycmd}\"" >> ${CMD_FILE}.tmp
 done
 
-cat >> ${CMD_FILE} <<EOF
+cat >> ${CMD_FILE}.tmp <<EOF
 ###
 fi
 EOF
+
+# test & compare & replace original file
+/bin/sh -n ${CMD_FILE}.tmp
+if [ $? -ne 0 ]; then
+	echo "cmdboot: sh -n error: ${CMD_FILE}.tmp"
+	exit 1
+fi
+is_diff=$( diff ${CMD_FILE} ${CMD_FILE}.tmp )
+if [ -n "${is_diff}" ]; then
+	mv ${CMD_FILE}.tmp ${CMD_FILE}
+else
+	rm -f ${CMD_FILE}.tmp
+fi
+
+exit 0
