crossplatform friendly

diff --git a/misc/cmdboot b/misc/cmdboot
--- a/misc/cmdboot
+++ b/misc/cmdboot
@@ -21,9 +21,11 @@ add_freebsd_cmd()
 {
 	MAIN_CMD="${MAIN_CMD} \
 acpidump \
+chflags \
 devfs \
 dpv \
 etcupdate \
+fetch \
 getent \
 zfs \
 zpool \
@@ -32,20 +34,32 @@ cpuset \
 geli \
 growfs \
 gpart \
+idprio \
 jexec \
+jot \
+kenv \
+kldload \
+kldstat \
 lockf \
 login \
 makefs \
+md5 \
 mdconfig \
 mkimg \
 mkuzip \
+mtree \
 newfs \
 newfs_msdos \
 ndp \
+pciconf \
+pw \
+sha256 \
 sockstat \
 rctl \
 setfib \
+sysrc \
 ulimit \
+uuencode \
 "
 }
 
@@ -53,10 +67,37 @@ ulimit \
 add_dragonfly_cmd()
 {
 	MAIN_CMD="${MAIN_CMD} \
+chflags \
+fetch \
 hammer2 \
-jexec
+idprio \
+jexec \
+jot \
+kenv \
+kldload \
+kldstat \
 lockf \
 login \
+mtree \
+newfs \
+pciconf \
+pw \
+sha256 \
+sysrc \
+uuencode \
+"
+}
+
+# Linux-specific CMD
+add_linux_cmd()
+{
+	MAIN_CMD="${MAIN_CMD} \
+chattr \
+wget \
+flock \
+md5sum \
+sha256sum \
+uuencode \
 "
 }
 
@@ -77,7 +118,6 @@ basename \
 cat \
 cc \
 chown \
-chflags \
 chmod \
 chroot \
 column \
@@ -92,7 +132,6 @@ du \
 dirname \
 egrep \
 env \
-fetch \
 find \
 file \
 grep \
@@ -102,33 +141,24 @@ head \
 hexdump \
 hostname \
 id \
-idprio \
 ifconfig \
 install \
-jot \
-kenv \
 kill \
 killall \
-kldload \
-kldstat \
 ldd \
 ln \
 ls \
 make \
-md5 \
 mkdir \
-mtree \
 mktemp \
 mount \
 mv \
 nc \
-newfs \
 nice \
+pkgconf \
 pax \
-pciconf \
 ps \
 ping \
-pw \
 pwd \
 readlink \
 realpath \
@@ -141,16 +171,13 @@ sed \
 seq \
 service \
 sort \
-sha256 \
 ssh \
 ssh-keygen \
 stat \
 strings \
-stty \
 su \
 sync \
 sysctl \
-sysrc \
 stty \
 sqlite3 \
 tail \
@@ -165,31 +192,41 @@ umount \
 uuidgen \
 whoami \
 xargs \
-uuencode \
 xz \
 xzcat \
 wc \
 "
 
 # check by FreeBSD version, since the misc/elf_tables may be absent on first init
-_version=$( sysctl -n kern.osreldate 2>/dev/null )
-
-if [ -z "${_version}" ]; then
-	echo "unable to get sysctl kern.osreldate"
-	exit 1
-fi
-
-if [ ${_version} -lt 1300131 ]; then
-	# https://svnweb.freebsd.org/base?view=revision&revision=r368045
-	MAIN_CMD="${MAIN_CMD} ping6"
-fi
+case "${platform}" in
+	Linux)
+		_version=$( sysctl -n kernel.osrelease 2>/dev/null | cut -d "-" -f 1  | tr '.' '0' )
+		;;
+	NetBSD)
+		_version=$( sysctl -n kern.osrevision 2>/dev/null )
+		;;
+	*)
+		_version=$( sysctl -n kern.osreldate 2>/dev/null )
+		if [ -z "${_version}" ]; then
+			echo "unable to get sysctl kern.osreldate"
+			exit 1
+		fi
+		;;
+esac
 
 case "${platform}" in
 	FreeBSD|HardenedBSD|TrueOS)
+		if [ ${_version} -lt 1300131 ]; then
+			# https://svnweb.freebsd.org/base?view=revision&revision=r368045
+			MAIN_CMD="${MAIN_CMD} ping6"
+		fi
 		add_freebsd_cmd
 		;;
 	DragonFly)
 		add_dragonfly_cmd
+		;;
+	Linux)
+		add_linux_cmd
 		;;
 esac
 
