cmdboot: fatal when append error

diff --git a/misc/cmdboot b/misc/cmdboot
--- a/misc/cmdboot
+++ b/misc/cmdboot
@@ -190,6 +190,14 @@ if [ ! "\$_CBSD_CMD_SUBR" ]; then
 _CBSD_CMD_SUBR=1
 ###
 EOF
+	if [ $? -ne 0 ]; then
+		echo "cmdboot: append error: ${CMD_FILE}"
+		cat >> ${CMD_FILE} <<EOF
+###
+fi
+EOF
+		exit 1
+	fi
 
 MAIN_CMD=$( echo ${MAIN_CMD} | sort )
 OPTIONAL_CMD=$( echo ${OPTIONAL_CMD} | sort )
