secondary ISO: WIP

diff --git a/sudoexec/bcreate b/sudoexec/bcreate
--- a/sudoexec/bcreate
+++ b/sudoexec/bcreate
@@ -336,7 +336,7 @@ if [ -n "${flavor}" ]; then
 
 	[ ${flavor_exist} -eq 0 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such flavor [${flavor}], available flavors: ${N2_COLOR}${flavors_available}${N0_COLOR}"
 
-	_res=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name=\"${flavor}\" LIMIT 1" 2>/dev/null )
+	_res=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name='${flavor}' LIMIT 1" 2>/dev/null )
  
 	[ -z "${_res}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get vm_cpus/vm_ram/imgsize for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
 	sqllistdelimer="|"
@@ -763,12 +763,12 @@ fi
 echo
 if [ "${vm_zfs_guid}" != "0" ]; then
 	[ -z "${NOINTER}" ] && ${ECHO} "${N1_COLOR}Global VM ZFS guid: ${N2_COLOR}${vm_zfs_guid}${N0_COLOR}"
-	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE settings SET vm_zfs_guid=\"${vm_zfs_guid}\"
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE settings SET vm_zfs_guid='${vm_zfs_guid}'"
 fi
 if [ "${uuid}" = "0" ]; then
 	uuid=$( ${UUIDGEN_CMD} )
 	#[ -z "${NOINTER}" ] && ${ECHO} "${N1_COLOR}Global VM UUID: ${N2_COLOR}${uuid}${N0_COLOR}"
-	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE settings SET uuid=\"${uuid}\"
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE settings SET uuid='${uuid}'"
 	/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} uuid="${uuid}" > /dev/null
 fi
 
@@ -833,7 +833,7 @@ case "${imgtype}" in
 		fi
 
 		# mark the first disk bootable
-		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET bootable='true' WHERE dsk_path=\"${defdsk}\""
+		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET bootable='true' WHERE dsk_path='${defdsk}'"
 		;;
 esac
 
@@ -865,7 +865,7 @@ fi
 #if [ "${bhyve_have_net_ratelimit}" = "1" ]; then
 #	if [ "${nic_ratelimit}" != "0" ]; then
 #		cbsdlogger NOTICE ${CBSD_APP}: bcreate for ${jname}: nic_ratelimit for nic id 1: ${nic_ratelimit}
-#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_ratelimit=\"${nic_ratelimit}\" WHERE id=\"1\""
+#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_ratelimit='${nic_ratelimit}' WHERE id='1'"
 #		/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} nic_ratelimit="${nic_ratelimit}" > /dev/null 2>&1
 #	fi
 #fi
@@ -876,12 +876,12 @@ fi
 #if [ "${bhyve_have_dsk_ratelimit}" = "1" ]; then
 #	if [ "${dsk_iops_limit}" != "0" ]; then
 #		cbsdlogger NOTICE ${CBSD_APP}: bcreate for ${jname}: dsk_iops_limit for dsk ${defdsk}: ${dsk_iops_limit}
-#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET dsk_iops_limit=\"${dsk_iops_limit}\" WHERE dsk_path=\"${defdsk}\""
+#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET dsk_iops_limit='${dsk_iops_limit}' WHERE dsk_path='${defdsk}'"
 #		/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} dsk_iops_limit="${dsk_iops_limit}" > /dev/null 2>&1
 #	fi
 #	if [ "${dsk_mbps_limit}" != "0" ]; then
 #		cbsdlogger NOTICE ${CBSD_APP}: bcreate for ${jname}: dsk_mbps_limit for dsk ${defdsk}: ${dsk_mbps_limit}
-#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET dsk_mbps_limit=\"${dsk_mbps_limit}\" WHERE dsk_path=\"${defdsk}\""
+#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET dsk_mbps_limit='${dsk_mbps_limit}' WHERE dsk_path='${defdsk}'"
 #		/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} dsk_mbps_limit="${dsk_mbps_limit}" > /dev/null 2>&1
 #	fi
 #fi
@@ -904,7 +904,7 @@ if [ -n "${register_iso_as}" -a -n "${register_iso_name}" ]; then
 	cd_name="${register_iso_as}"
 	cd_path="${srcdir}/iso/${register_iso_name}"
 
-	cd_rec_num=$( cbsdsqlro storage_media SELECT COUNT\(path\) FROM media WHERE name=\"${cd_name}\" AND path=\"${cd_path}\" AND type=\"iso\" AND jname=\"-\" )
+	cd_rec_num=$( cbsdsqlro storage_media "SELECT COUNT(path) FROM media WHERE name='${cd_name}' AND path='${cd_path}' AND type='iso' AND jname='-'" )
 
 	if [ "${cd_rec_num}" = "0" ]; then
 		# register new ISO with assignment to this VM
@@ -913,7 +913,24 @@ if [ -n "${register_iso_as}" -a -n "${register_iso_name}" ]; then
 		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}bcreate: media register error: ${_res}${N0_COLOR}"
 	else
 		# we have free/unassignent CD. link to this VM
-		cbsdsqlrw storage_media "UPDATE media SET jname=\"${jname}\" WHERE jname=\"-\" AND type=\"iso\" AND name=\"${cd_name}\" AND path=\"${cd_path}\""
+		cbsdsqlrw storage_media "UPDATE media SET jname='${jname}' WHERE jname='-' AND type='iso' AND name='${cd_name}' AND path='${cd_path}'"
+	fi
+fi
+
+if [ -n "${register_iso_as2}" -a -n "${register_iso_name2}" ]; then
+	cd_name="${register_iso_as2}"
+	cd_path="${srcdir}/iso/${register_iso_name2}"
+
+	cd_rec_num=$( cbsdsqlro storage_media "SELECT COUNT(path) FROM media WHERE name='${cd_name}' AND path='${cd_path}' AND type='iso' AND jname='-'" )
+
+	if [ "${cd_rec_num}" = "0" ]; then
+		# register new ISO with assignment to this VM
+		_res=$( media mode=register name="${register_iso_as2}" path="${srcdir}/iso/${register_iso_name2}" type=iso jname=${jname} 2>&1 )
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}bcreate: media register error: ${_res}${N0_COLOR}"
+	else
+		# we have free/unassignent CD. link to this VM
+		cbsdsqlrw storage_media "UPDATE media SET jname='${jname}' WHERE jname='-' AND type='iso' AND name='${cd_name}' AND path='${cd_path}'"
 	fi
 fi
 
@@ -1156,13 +1173,13 @@ if [ ${is_cloud} -eq 1 ]; then
 	[ -z "${ci_gw4}" ] && /usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} ci_gw4="${ci_gw4}" > /dev/null 2>&1
 
 	# GET MAC
-	nic_hwaddr0=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT nic_hwaddr FROM bhyvenic LIMIT 1 )
+	nic_hwaddr0=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT nic_hwaddr FROM bhyvenic LIMIT 1" )
 
 	if [ "${nic_hwaddr0}" = "0" ]; then
 		# gen MAC
 		nic_hwaddr0=$( mac_gen 00:a0:98 )
 		cbsdlogger NOTICE ${CBSD_APP}: bcreate for ${jname}: MAC address randomized and updated for nic id 1: ${nic_hwaddr0}
-		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_hwaddr=\"${nic_hwaddr0}\" WHERE id=\"1\""
+		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_hwaddr='${nic_hwaddr0}' WHERE id='1'"
 	fi
 
 	[ -z "${ci_nic_hwaddr0}" ] && /usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} ci_nic_hwaddr0="${nic_hwaddr0}" > /dev/null 2>&1
@@ -1197,6 +1214,11 @@ fi
 
 # unset vnc_password when vnc_password=0 (reserved)
 [ "${vnc_password}" = "0" ] && cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE settings SET vnc_password=''"
+
+# copy tpm settings
+tpm=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT lpcslot_value FROM lpc WHERE lpcslot_name='tpm'" )
+cbsdsqlrw local "UPDATE bhyve SET tpm='${tpm}' WHERE jname='${jname}'"
+cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE settings SET tpm='${tpm}'"
 
 # set default nice from rctl_nice
 [ -n "${rctl_nice}" ] && nice="${rctl_nice}"
