fix bset; style

diff --git a/sudoexec/bcreate b/sudoexec/bcreate
--- a/sudoexec/bcreate
+++ b/sudoexec/bcreate
@@ -712,6 +712,15 @@ vm_ram_validate
 defdsk="dsk1.vhd"
 defnic="nic1.vhd"
 
+[ ! -d ${jailfstabdir}  ] && ${MKDIR_CMD} -m 0770 -p ${jailfstabdir}
+# cached sqlite3
+if [ ! -r "${tmpdir}/bhyve-local.sqlite" ]; then
+	bsqlite-cache-create file=${tmpdir}/bhyve-local.sqlite
+	_ret=$?
+	[ ${_ret} -ne 0 ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N2_COLOR}bsqlite-cache-create file=${tmpdir}/bhyve-local.sqlite${N0_COLOR}"
+fi
+${CP_CMD} -a ${tmpdir}/bhyve-local.sqlite ${jailsysdir}/${jname}/local.sqlite
+
 if [ -z "${zfs_snapsrc}" ]; then
 	really_create_base
 	really_create_vm
@@ -724,15 +733,6 @@ else
 fi
 
 [ ! -d "${data}" ] && log_err 1 "Can't create datadir ${data}"
-[ ! -d ${jailfstabdir}  ] && ${MKDIR_CMD} -m 0770 -p ${jailfstabdir}
-
-# cached sqlite3
-if [ ! -r "${tmpdir}/bhyve-local.sqlite" ]; then
-	bsqlite-cache-create file=${tmpdir}/bhyve-local.sqlite
-	_ret=$?
-	[ ${_ret} -ne 0 ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N2_COLOR}bsqlite-cache-create file=${tmpdir}/bhyve-local.sqlite${N0_COLOR}"
-fi
-${CP_CMD} -a ${tmpdir}/bhyve-local.sqlite ${jailsysdir}/${jname}/local.sqlite
 
 if [ -n "${lpc_temp_sql}" ]; then
 	[ ! -r "${lpc_temp_sql}" ] && err 1 "${N1_COLOR}${CIX_APP}: lpc_temp_sql file not readable: ${N2_COLOR}${lpc_temp_sql}${N0_COLOR}"
