invert is_number: For the CBSD, is was historical behavior. Its time to fix it.

diff --git a/sudoexec/bcreate b/sudoexec/bcreate
--- a/sudoexec/bcreate
+++ b/sudoexec/bcreate
@@ -327,22 +327,20 @@ imgsize_validate()
 {
 	# imgsize validate
 	if [ -n "${imgsize_min}" -a -n "${imgsize}" ]; then
-		if ! is_number "${imgsize_min}"; then
-			# imgsize_min is number. assume value in bytes
+		if is_number "${imgsize_min}"; then
 			imgsize_min_bytes="${imgsize_min}"
 		else
-			imgsize_min_bytes=$( get_bytes ${imgsize_min} )
+			capture imgsize_min_bytes ${miscdir}/conv2human "${imgsize_min}"
 		fi
 
 		[ -z "${imgsize_min_bytes}" -o "${imgsize_min_bytes}" = "0" ] && err 1 "${N1_COLOR}${CIX_APP}: unable to convert imgsize to bytes: ${N2_COLOR}${imgsize_min}${N0_COLOR}"
 
 		imgsize_min_human_mb=$(( imgsize_min_bytes / 1024 / 1024 ))
 
-		if ! is_number "${imgsize}"; then
-			# imgsize is number. assume value in bytes
+		if is_number "${imgsize}"; then
 			imgsize_bytes="${imgsize}"
 		else
-			imgsize_bytes=$( get_bytes ${imgsize} )
+			capture imgsize_bytes ${miscdir}/conv2human "${imgsize}"
 		fi
 
 		imgsize_human_mb=$(( imgsize_bytes / 1024 / 1024 ))
@@ -362,20 +360,18 @@ imgsize_validate()
 vm_ram_validate()
 {
 	if [ -n "${vm_ram_min}" -a -n "${vm_ram}" ]; then
-		if ! is_number "${vm_ram_min}"; then
-			# vm_ram_min is number. assume value in bytes
+		if is_number "${vm_ram_min}"; then
 			vm_ram_min_bytes="${vm_ram_min}"
 		else
-			vm_ram_min_bytes=$( get_bytes ${vm_ram_min} )
+			capture vm_ram_min_bytes ${miscdir}/conv2human "${vm_ram_min}"
 		fi
 
 		vm_ram_min_human_mb=$(( vm_ram_min_bytes / 1024 / 1024 ))
 
-		if ! is_number "${vm_ram}"; then
-			# vm_ram is number. assume value in bytes
+		if is_number "${vm_ram}"; then
 			vm_ram_bytes="${vm_ram}"
 		else
-			vm_ram_bytes=$( get_bytes ${vm_ram} )
+			capture vm_ram_bytes ${miscdir}/conv2human "${vm_ram}"
 		fi
 
 		vm_ram_human_mb=$(( vm_ram_bytes / 1024 / 1024 ))
@@ -615,10 +611,10 @@ fi
 
 case "${platform}" in
 	Linux)
-		res=$( ${STAT_CMD} -c "%u %g" "${jconf_tmp}" )
+		capture res ${STAT_CMD} -c "%u %g" "${jconf_tmp}"
 		;;
 	*)
-		res=$( ${STAT_CMD} -f "%u %g" "${jconf_tmp}" )
+		capture res ${STAT_CMD} -f "%u %g" "${jconf_tmp}"
 		;;
 esac
 
@@ -830,7 +826,7 @@ case "${imgtype}" in
 
 		dsk_bsize=0
 
-		if is_number "${imgsize}"; then
+		if ! is_number "${imgsize}"; then
 			if conv2bytes ${imgsize}; then
 				dsk_bsize="${convval}"
 			else
@@ -916,13 +912,13 @@ fi
 # update state_time
 SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE settings SET state_time=(strftime('%s','now')); UPDATE settings SET created=(strftime('%s','now'))"
 
-# Check if SIZE if valid: can't be smaller then template
-if is_number ${vm_ram}; then
-	# not number, try to convert
-	if conv2bytes "${vm_ram}"; then
-		vm_ram="${convval}"
+# Check if SIZE is valid: convert to bytes if needed
+if ! is_number "${vm_ram}"; then
+	# not a number (e.g. "1g"), try to convert to bytes
+	if capture vm_ram_bytes ${miscdir}/conv2human "${vm_ram}"; then
+		vm_ram="${vm_ram_bytes}"
 	else
-		log_err 1 "${vm_ram} is not number and we can't convert int via conv2bytes"
+		log_err 1 "${vm_ram} is not a number and we can't convert via conv2human"
 	fi
 fi
 
@@ -1088,7 +1084,7 @@ if [ ${is_cloud} -eq 1 ]; then
 						_prefix="24"
 					else
 						_prefix="${_pureip#*/}"
-						if is_number "${_prefix}"; then
+						if ! is_number "${_prefix}"; then
 							err 1 "${N1_COLOR}${CIX_APP}: prefix not a number: ${_prefix}: ${N2_COLOR}${_pureip}${N1_COLOR}"
 						fi
 					fi
@@ -1099,7 +1095,7 @@ if [ ${is_cloud} -eq 1 ]; then
 						_prefix="64"
 					else
 						_prefix="${_pureip#*/}"
-						if is_number "${_prefix}"; then
+						if ! is_number "${_prefix}"; then
 							err 1 "${N1_COLOR}${CIX_APP}: prefix not a number: ${_prefix}: ${N2_COLOR}${_pureip}${N1_COLOR}"
 						fi
 					fi
