bhyvedsk

diff --git a/sudoexec/bcreate b/sudoexec/bcreate
--- a/sudoexec/bcreate
+++ b/sudoexec/bcreate
@@ -20,6 +20,7 @@ readconf buildworld.conf
 readconf jail.conf
 . ${workdir}/universe.subr
 . ${workdir}/freebsd_world.subr
+. ${workdir}/bhyve.subr
 
 init $*
 
@@ -145,16 +146,9 @@ if [ $? -eq 0 ]; then
 	sysrc -qf ${jconf} ver="${ver}" > /dev/null
 	mv /tmp/${jname}.$$.img ${data}/${defdsk}
     else
-	# test for human
-	if is_number ${freesize}; then
-	    conv2bytes ${freesize} || err 1 "${MAGENTA}conv2bytes from bcreate error for: ${GREEN}${freesize}${MAGENTA}"
-	    imgbytes="${convval}"
-	else
-	    imgbytes=$convval
+	if ! bhyve_create_dsk ${data}/${defdsk} ${freesize}; then
+		err 1 "Error: Couldn't create the image file. ${mdimage}"
 	fi
-	blockcount=$(( imgbytes  / 1048576 ))
-	touch "${data}/${defdsk}"
-	dd if="/dev/zero" of="${data}/${defdsk}" bs=1m count=0 seek=${blockcount} 1> /dev/null 2>&1 || err 1 "Error: Couldn't create the image file. ${mdimage}"
     fi
 
     if [ -n "${virtio_type}" ]; then
