bhyve: one global dataset per vm
when we work with bhyve virtual machines on ZFS pool, create personal
dataset for each vm and place all vm related stuff (zvol, system files)
inside. it adds management flexibility of VM data (e.g. atomic
recursive replication and so on). Use symlink for back-compatible from
old dirs

diff --git a/sudoexec/bremove b/sudoexec/bremove
--- a/sudoexec/bremove
+++ b/sudoexec/bremove
@@ -49,13 +49,17 @@ for jname in ${JLIST}; do
 	DST="${jaildatadir}/${jname}-${jaildatapref}"
 	JAILDIR="${jaildir}/${jname}"
 	JAILFSTAB="${jailfstabdir}/${jailfstabpref}${jname}"
-	JAILRCCONF="${jailsysdir}/${jname}/rc.conf_${jname}"
-
+	JAILSYSRCCONF="${jailsysdir}/${jname}/rc.conf_${jname}"
+	JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
 	unregister=0
 
 	. ${jrcconf}
 	if [ $? -eq 1 ]; then
-		if [ ! -f "${JAILRCCONF}" ]; then
+		if [ -r "${JAILRCCONF}" -o -r "${JAILSYSRCCONF}" ]; then
+			[ -r ${JAILSYSRCCONF} ] && . ${JAILSYSRCCONF}
+			[ -r ${JAILRCCONF} ] && . ${JAILRCCONF}
+			unregister=1
+		else
 			# remote?
 			if [ ${sqlreplica} -eq 0 ]; then
 				${ECHO} "${N1_COLOR}No such domain: ${N2_COLOR}${jname}${N0_COLOR}"
@@ -80,9 +84,6 @@ for jname in ${JLIST}; do
 			fi
 			done
 			continue
-		else
-			. ${JAILRCCONF}
-			unregister=1
 		fi
 	fi
 
@@ -214,6 +215,25 @@ for jname in ${JLIST}; do
 	for parent_snapshot in ${PARENT_SNAPSHOTS}; do
 		/sbin/zfs destroy ${parent_snapshot}
 	done
+
+	vmdir="${workdir}/vm/${jname}"
+
+	### xxx
+	if [ "${zfsfeat}" = "1" ]; then
+		readconf zfs.conf
+		. ${zfstool}
+		zfsmnt "${vmdir}"
+		_ret=$?
+		if [ ${_ret} -eq 1 -o ${_ret} -eq 2 ]; then
+			_msg=$( /sbin/zfs destroy ${ZPOOL} )
+			_ret=$?
+			if [ ${_ret} -ne 0 ]; then
+				${ECHO} "${N1_COLOR}bremove: zfs destroy error for: ${N2_COLOR}${ZPOOL}: ${N1_COLOR}${_msg}${N0_COLOR}"
+			fi
+		fi
+	fi
+
+	[ -d "${vmdir}" ] && /bin/rm -rf ${vmdir}
 
 	# detach ppt
 	cbsdsqlrw local "DELETE FROM bhyveppt WHERE jname=\"${jname}\""
