WIP: CPU topology
add vm_cpu_topology settings in global bhyve config

diff --git a/sudoexec/bstart b/sudoexec/bstart
--- a/sudoexec/bstart
+++ b/sudoexec/bstart
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v11.1.7
+#v11.1.17
 MYARG=""
 MYOPTARG="jname inter debug"
 MYDESC="Start jail"
@@ -197,7 +197,7 @@ start_bhyve()
 				init_iso
 				if [ $? -eq 1 ]; then
 					printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
-					for i in $( jot 5 ); do
+					for i in $( /usr/bin/jot 5 ); do
 						printf "."
 						sleep 1
 					done
@@ -249,6 +249,12 @@ start_bhyve()
 	#unset zero-value
 	[ "${bhyve_flags}" = "0" ] && unset bhyve_flags
 	[ "${vm_os_profile}" = "0" ] && unset vm_os_profile
+
+	# init bhyve_cpus
+	if ! compile_bhyve_cpus_args; then
+		${ECHO} "${MAGENTA}Unable to compile bhyve_cpus_args for VMs: ${GREEN}${jname}${NORMAL}"
+		bhyve_cpus="${vm_cpus}"
+	fi
 
 	# init hostbridge_args
 	if ! compile_hostbridge_args; then
@@ -360,7 +366,8 @@ tmuxcmd='${tmuxcmd}'
 jname='${jname}'
 
 bhyve_flags='${bhyve_flags}'
-vm_cpus='${vm_cpus}'
+# with topology
+vm_cpus='${bhyve_cpus}'
 vm_ram='${vm_ram}'
 vm_efi='${vm_efi}'
 vm_console='${vm_console}'
@@ -527,7 +534,7 @@ readconf ${default_profile}
 init_bhyve
 init_systap
 
-[ -z "$jname" ] && jname=$1
+[ -z "${jname}" ] && jname=$1
 
 readconf vnc.conf
 readconf bstart.conf
