bhyve: check bhyve_vnc_tcp_bind available

diff --git a/sudoexec/bstart b/sudoexec/bstart
--- a/sudoexec/bstart
+++ b/sudoexec/bstart
@@ -410,6 +410,19 @@ start_bhyve()
 	# init vnc_args
 	if ! compile_vnc_args; then
 		unset vnc_args
+	else
+		case "${bhyve_vnc_tcp_bind}" in
+			127.0.0.1|0.0.0.0)
+				;;
+			*)
+				getnics-by-ip ip=${bhyve_vnc_tcp_bind} mode=strict
+				_ret=$?
+				if [ ${_ret} -ne 0 ]; then
+					err 1 "${N1_COLOR}Unable to bind bhyve VNC, please check bhyve_vnc_tcp_bind settings: ${N2_COLOR}${bhyve_vnc_tcp_bind}${N0_COLOR}"
+				fi
+				;;
+		esac
+		# todo: check for port
 	fi
 
 	if [ "${lm}" = "1" -a -n "${lm_rnodename}"  ]; then
