Allow to show cbsd version even workdir is not set. Issue #173, Thanks to Vladislav V. Prodan aka click0; jail: add support for aarch64 aka ARMv8 and arm-64 via qemu-aarch64-static emulator type; update kmem patch for FreeBSD 12.0 and next-drm branch re-generate base filelists for FreeBSD 11,12 and upcoming 13 bumb CBSD version, 11.1.0-beta

diff --git a/sudoexec/bstart b/sudoexec/bstart
--- a/sudoexec/bstart
+++ b/sudoexec/bstart
@@ -29,6 +29,36 @@ init_grubcheck()
 	[ -z "${grubcmd}" ] && err 1 "${MAGENTA}Current version required for ${GREEN}grub-bhyve${MAGENTA}\nPlease ${GREEN}pkg install grub2-bhyve ${MAGENTA} or ${GREEN}make -C /usr/ports/sysutils/grub2-bhyve install${MAGENTA} it.${NORMAL}"
 }
 
+init_systap()
+{
+	local _i _iface _desc _mytap
+
+	_iface=$( /sbin/ifconfig -l )
+	_mytap=
+
+	for _i in ${_iface}; do
+		_desc=$( /sbin/ifconfig ${_i} 2>/dev/null | /usr/bin/awk '/description:/{print $2}' )
+		[ "${_desc}" = "CBSDSYSTEM0" ] && return 0
+	done
+
+	local _uplink_iface4=$( /sbin/route -n -4 get 0.0.0.0 2>/dev/null | /usr/bin/awk '/interface/{print $2}' )
+
+	. ${vimageconf}
+
+	if ! get_vm_uplink_interface auto; then
+		err 1 "${MAGENTA}bstart: error get_vm_uplink_interface auto${NORMAL}"
+	fi
+
+	if ! mybridge=$( get_my_device bridge ${interface} ); then
+		err 1 "errmsg=\"Error:get_my_device_bridge_for_${interface}: ${mybridge}\""
+	fi
+
+	_mytap=$( get_my_tap ${mybridge} )
+	[ $? -eq 1 ] && err 1 "errmsg=\"Error:get_my_tap_for_${mybridge}: ${mybridge}\""
+
+	/sbin/ifconfig ${_mytap} description CBSDSYSTEM0
+}
+
 create_from_jail()
 {
 	local passt_args=
@@ -505,6 +535,7 @@ fi
 . ${sharedir}/bhyve.conf		# only for for MYCOL variables: used in exports below
 
 init_bhyve
+init_systap
 
 [ -z "$jname" ] && jname=$1
 
