some improvements in bstop: soft timeout and noacpi
new args: noacpi=0,1 (force hard reset or not). By default - 0, dont force hard and send ACPI signal first
  hard_timeout= configurable soft timeout for ACPI shutdown before hard poweroff
add bstop.conf config for global overwriting of these values

diff --git a/sudoexec/bstop b/sudoexec/bstop
--- a/sudoexec/bstop
+++ b/sudoexec/bstop
@@ -1,16 +1,16 @@
 #!/usr/local/bin/cbsd
-#v11.0.10
+#v11.1.19
 globalconf="${workdir}/cbsd.conf";
 MYARG=""
-MYOPTARG="jname inter cbsd_queue_name"
+MYOPTARG="jname inter cbsd_queue_name noacpi hard_timeout"
 MYDESC="Stop jail"
 CBSDMODULE="bhyve"
 EXTHELP="wf_jstop_jstart.html"
-ADDHELP="cbsd_queue_name - realtime queue, can be: none\n"
-
-set -e
-. ${globalconf}
-set +e
+ADDHELP="cbsd_queue_name - realtime queue, can be: none\n\
+noacpi= 1 - force hard poweroff immediately or 0 - send ACPI signal first\n\
+    can be overwriten by bstop.conf\n\
+hard_timeout=N, how many seconds wait after ACPI signal before hard poweroff,\n\
+    default is: 30. Can be overwriten by bstop.conf\n"
 
 . ${subr}
 . ${system}
@@ -19,6 +19,12 @@ set +e
 . ${tools}
 
 [ -z "${1}" ] && select_jail_by_list -s "List of online VMs" -a "On" -e bls -r ${sqlreplica}
+
+noacpi=0		# soft shutdown by default
+hard_timeout=30		# default soft timeout: 30 seconds
+
+readconf bstop.conf
+
 init $*
 
 [ -n "${inter}" ] && shift
@@ -32,18 +38,31 @@ init $*
 emulator="bhyve" # for jname_is_multiple
 jname_is_multiple
 
-if [ $# -gt 1 -o -n "${jail_list}" ]; then
-#	recursive stop
+if [ -n "${jail_list}" ]; then
+	TMP_JLIST="${jail_list}"
+else
+	TMP_JLIST=$*
+fi
 
-	if [ -n "${jail_list}" ]; then
-		JLIST="${jail_list}"
-	else
-		JLIST=$*
+JLIST=
+
+# check for actual vm list in arg list
+jail_num=0
+for i in ${TMP_JLIST}; do
+	exist=$( cbsdsql local SELECT jname FROM jails WHERE jname=\"${i}\" AND emulator=\"${emulator}\" LIMIT 1 )
+	if [ -n "${exist}" ]; then
+		JLIST="${exist} ${JLIST}"
+		jail_num=$(( jail_num + 1 ))
 	fi
+done
 
+# this is multiple list, split it by parallel bstop execution
+if [ ${jail_num} -gt 1 ]; then
+	st_time=$( /bin/date +%s )
+	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple stopping: ${JLIST}
 	for jname in ${JLIST}; do
 		[ "${jname}" = "cbsd_queue_name=none" ] && continue						#TODO << substr
-		/usr/sbin/daemon -p ${ftmpdir}/bstop.${jname}.$$ /usr/local/bin/cbsd bstop jname=${jname}
+		/usr/sbin/daemon -p ${ftmpdir}/bstop.${jname}.$$ /usr/local/bin/cbsd bstop jname=${jname} noacpi=${noacpi} hard_timeout=${hard_timeout}
 		#lets save .pid file
 		sleep 1
 		[ -f "${ftmpdir}/bstop.${jname}.$$" ] && cbsd_pwait --pid=$( /bin/cat ${ftmpdir}/bstop.${jname}.$$ ) --timeout=${parallel}
@@ -51,10 +70,14 @@ if [ $# -gt 1 -o -n "${jail_list}" ]; then
 
 	wait_for_fpid stop
 
+	end_time=$( /bin/date +%s )
+	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple done in $(( end_time - st_time ))s: ${JLIST}
 	err 0 "${MAGENTA}Multiple stop: ${GREEN}done${NORMAL}"
 fi
 
-[ -z "${jname}" ] && jname=$1
+st_time=$( /bin/date +%s )
+
+[ -z "${jname}" ] && jname=$( echo ${JLIST} | /usr/bin/awk '{printf $1}' )
 . ${sharedir}/bhyve.conf		# only for for MYCOL variables: used in exports below
 
 . ${jrcconf}
@@ -69,10 +92,10 @@ fi
 
 pid=
 
-pid=$( /bin/ps axopid,ucomm,command|while read pid comm cmd; do
+pid=$( /bin/ps axopid,ucomm,command | while read pid comm cmd; do
 	case "${comm}" in
 		bhyve|grub-bhyve)
-			_res=$( echo $cmd|/usr/bin/grep " ${jname}" 2>/dev/null)
+			_res=$( echo ${cmd} | /usr/bin/grep " ${jname}" 2>/dev/null)
 			[ -n "${_res}" ] && echo "${pid}" && exit 0
 			;;
 	esac
@@ -90,26 +113,41 @@ trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 
 jswmode jname=${jname} mode=maintenance comment='Stopping_VM'
 
-if [ -n "${pid}" ]; then
-	# soft stop, send SIGTERM
-	printf "${MAGENTA}Send SIGTERM to VM: ${GREEN}${jname}${NORMAL}"
-	kill -15 ${pid} > /dev/null 2>&1
-	for i in $( /usr/bin/seq 1 30 ); do
-		cbsd_pwait --pid=${pid} --timeout=1 > /dev/null 2>&1
-		printf "${MAGENTA}."
-	done
-	printf "${NORMAL}\n"
+if [ ${noacpi} -eq 0 ]; then
+	if [ -n "${pid}" ]; then
+		# soft stop, send SIGTERM
+		tleft=$(( hard_timeout - 1 ))
+		kill -15 ${pid} > /dev/null 2>&1
+		for i in $( /usr/bin/seq 1 ${hard_timeout} ); do
+			printf "${CLRLINE}"
+			printf "${CURSORRST}"
+			printf "${MAGENTA}Send SIGTERM to ${GREEN}${jname}${MAGENTA}. Soft timeout is ${GREEN}${hard_timeout}${MAGENTA} sec. ${LRED}${tleft}${MAGENTA} seconds left [${NORMAL}"
+			for x in $( /usr/bin/seq 1 ${i} ); do
+				printf "${MAGENTA}."
+			done
+			cbsd_pwait --pid=${pid} --timeout=1 > /dev/null 2>&1
+			tleft=$(( tleft - 1 ))
+		done
+		printf "]${NORMAL}\n"
+		/bin/ps -p ${pid} > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			# still live
+			cbsdlogger NOTICE ${CBSD_APP}: bhyve domain ${jname} does not want to die via ACPI, soft timeout ${hart_timeout} exceeded. Kill him
+			kill -9 ${pid} > /dev/null 2>&1 || true
+		fi
+	else
+		${ECHO} "${MAGENTA}Warning: unable to determine bhyve pid for: ${GREEN}${jname}${NORMAL}"
+	fi
 else
-	${ECHO} "${MAGENTA}Warning: unable to determine bhyve pid for: ${GREEN}${jname}${NORMAL}"
+	kill -9 ${pid} > /dev/null 2>&1 || true
 fi
 
-[ -f ${jailsysdir}/${jname}/vnc_port ] && /bin/rm -f ${jailsysdir}/${jname}/vnc_port
+[ -r ${jailsysdir}/${jname}/vnc_port ] && /bin/rm -f ${jailsysdir}/${jname}/vnc_port
 
 _res=$( /usr/sbin/bhyvectl --destroy --vm="${jname}" 2>&1 )
-[ $? -ne 0 ] && ${ECHO} "${MAGENTA}byvectl --destroy: ${_res}${NORMAL}"
 
 # extra check for no any cbsd process related to this VM is active
-epid=$( /bin/ps axopid,ucomm,command | /usr/bin/grep "/tmp/bhyveload.${jname}.lock" |/usr/bin/grep -v grep |/usr/bin/awk '{printf $1" "}' )
+epid=$( /bin/ps axopid,ucomm,command | /usr/bin/grep "/tmp/bhyveload.${jname}.lock" | /usr/bin/grep -v grep | /usr/bin/awk '{printf $1" "}' )
 [ -n "${epid}" ] && kill -9 ${epid} > /dev/null 2>&1
 epid=$( /bin/ps axopid,ucomm,command | /usr/bin/grep "${sharedir}/bhyverun.sh -c ${workdir}/jails-system/${jname}/bhyve.conf" | /usr/bin/grep -v grep | /usr/bin/awk '{printf $1" "}' )
 [ -n "${epid}" ] && kill -9 ${epid} > /dev/null 2>&1
@@ -144,4 +182,6 @@ if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
 	[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} id=${jname} cmd=bstop status=2 data_status=0
 fi
 
+end_time=$( /bin/date +%s )
+cbsdlogger NOTICE ${CBSD_APP}: bhyve domain ${jname} stopped in $(( end_time - st_time ))s
 exit 0
