style

diff --git a/sudoexec/initenv b/sudoexec/initenv
--- a/sudoexec/initenv
+++ b/sudoexec/initenv
@@ -1012,8 +1012,9 @@ phase5()
 		[ $? -eq 0 ] && _myfs="hammer"
 	fi
 
-	_uncfg=$( ${miscdir}/sqlcli ${dbdir}/local.sqlite "SELECT items FROM unconfigured" )
-	[ $? -ne 0 ] && err 1 "Error for unconfigured query"
+	_uncfg=$( ${miscdir}/sqlcli ${dbdir}/local.sqlite "SELECT items FROM unconfigured" 2>&1 )
+	_ret=$?
+	[ ${_ret} -ne 0 ] && err 1 "Error for unconfigured query: err:${_ret}: ${_uncfg}"
 
 	if [ -n "${INITCFG}" ]; then
 		onodename="${nodename}"
