style

diff --git a/sudoexec/initenv b/sudoexec/initenv
--- a/sudoexec/initenv
+++ b/sudoexec/initenv
@@ -274,7 +274,13 @@ phase1()
 		initenv_modify_cbsd_homedir=0
 	fi
 
-	[ ! -d "${workdir}" ] && /bin/mkdir -m 755 ${workdir}
+	if [ ! -d "${workdir}" ]; then
+		/bin/mkdir -m 755 ${workdir}
+		if [ $? -ne 0 ]; then
+			echo "mkdir error: ${workdir}"
+			exit 1
+		fi
+	fi
 	printf "${myversion}" > ${workdir}/ver
 
 	$ECHO "${N1_COLOR} * Check hier and permission..."
