fix for SQLite3 double_quoted_string_literals_are_accepted
https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted

diff --git a/sudoexec/initenv b/sudoexec/initenv
--- a/sudoexec/initenv
+++ b/sudoexec/initenv
@@ -690,7 +690,16 @@ phase5()
 		env workdir=${workdir} /usr/local/bin/cbsd ${miscdir}/updatesql ${dbdir}/inv.${nodename}.sqlite ${distdir}/share/local-local.schema local
 		env workdir=${workdir} /usr/local/bin/cbsd ${miscdir}/updatesql ${dbdir}/inv.${nodename}.sqlite ${distdir}/share/local-jails.schema jails
 		$ECHO "${N1_COLOR}Empty inventory database created: ${N2_COLOR}${dbdir}/inv.${nodename}.sqlite${N0_COLOR}"
-		${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite "INSERT INTO local ( nodename ) VALUES ( \"${nodename}\" )"
+		${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite "INSERT INTO local ( nodename ) VALUES ( '${nodename}' )"
+	fi
+
+	# extra re-check for empty values
+	_tmp_nodename=$( ${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite "SELECT nodename FROM local" 2>/dev/null )
+	[ -z "${_tmp_nodename}" ] && ${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite "INSERT INTO local ( nodename ) VALUES ( '${nodename}' )"
+	_tmp_nodename=$( ${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite "SELECT nodename FROM local" 2>/dev/null )
+	if [ -z "${_tmp_nodename}" ]; then
+		echo "error query: ${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite \"INSERT INTO local ( nodename ) VALUES ( '${nodename}' )\""
+		exit 1
 	fi
 
 	/bin/chmod 0660 ${dbdir}/inv.${nodename}.sqlite && /usr/sbin/chown ${cbsduser}:${cbsduser} ${dbdir}/inv.${nodename}.sqlite
@@ -731,7 +740,7 @@ phase5()
 	env workdir=${workdir} /usr/local/bin/cbsd ${miscdir}/updatesql ${dbdir}/storage_media.sqlite ${distdir}/share/local-storage_media_map.schema media
 	env workdir=${workdir} /usr/local/bin/cbsd ${miscdir}/updatesql ${dbdir}/images.sqlite ${distdir}/share/local-images.schema images
 	env workdir=${workdir} /usr/local/bin/cbsd ${miscdir}/updatesql ${dbdir}/inv.${nodename}.sqlite ${distdir}/share/local-storage_pools.schema storage_pools
-	_tmpval=$( ${miscdir}/sqlcli ${dbdir}/local.sqlite SELECT id FROM storage_pools LIMIT 1 )
+	_tmpval=$( ${miscdir}/sqlcli ${dbdir}/local.sqlite "SELECT id FROM storage_pools LIMIT 1" )
 	if [ -z "${_tmpval}" ]; then
 		${miscdir}/sqlcli ${dbdir}/inv.${nodename}.sqlite "INSERT INTO storage_pools (id,name,driver,description,poolpath,state) VALUES(1,'default','dir','','jails-data',1); )"
 	fi
@@ -751,7 +760,7 @@ phase5()
 			zfsfeat=1
 		else
 			zfsfeat=0
-			${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET zfsfeat=\"0\"
+			${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET zfsfeat='0'"
 		fi
 	fi
 
@@ -760,8 +769,7 @@ phase5()
 		[ $? -eq 0 ] && _myfs="hammer"
 	fi
 
-	_uncfg=$( ${miscdir}/sqlcli ${dbdir}/local.sqlite SELECT items FROM unconfigured )
-
+	_uncfg=$( ${miscdir}/sqlcli ${dbdir}/local.sqlite "SELECT items FROM unconfigured" )
 	[ $? -ne 0 ] && err 1 "Error for unconfigured query"
 
 	if [ -n "${INITCFG}" ]; then
@@ -777,11 +785,11 @@ phase5()
 			[ "${_uninit}" = "mdtmp" ] && continue
 			if [ "${_uninit}" = "${_checkme}" ]; then
 				if [ "${_checkme}" = "zfsfeat" -a ${_myfs} != "zfs" ]; then
-					${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET zfsfeat=\"0\"
+					${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET zfsfeat='0'"
 					continue
 				fi
 				if [ "${_checkme}" = "hammerfeat" -a ${_myfs} != "hammer" ]; then
-					${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET hammer=\"0\"
+					${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET hammer='0'"
 					continue
 				fi
 
@@ -796,7 +804,7 @@ phase5()
 				[ "${_checkme}" = "mdtmp" -a "$answ" = "1" ] && answ="8"
 				[ "${_checkme}" = "mdtmp" -a "$answ" = "2" ] && answ="0"
 				if [ -n "${answ}" ]; then
-					${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET ${_uninit}=\"${answ}\"
+					${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET ${_uninit}='${answ}'"
 					eval "${_uninit}=\"${answ}\"" 2>/dev/null
 				fi
 				if [ "${_checkme}" = "nat_enable" -a  "${nat_enable}" != "0" ]; then
@@ -812,10 +820,10 @@ phase5()
 		done
 	done
 	# flush unconfigured marker
-	${miscdir}/sqlcli ${dbdir}/local.sqlite DELETE FROM unconfigured
+	${miscdir}/sqlcli ${dbdir}/local.sqlite "DELETE FROM unconfigured"
 	# constants and static param. FIX ME
-	${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET repo=\"https://bsdstore.ru\"
-	${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET workdir=\"${workdir}\"
+	${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET repo='https://bsdstore.ru'"
+	${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET workdir='${workdir}'"
 
 	oipfw_enable="${ipfw_enable}"
 
@@ -840,7 +848,7 @@ phase5()
 	for i in ipfw_enable fs jail_interface nodedescr nodename hostname vnet racct platform node_ip4_active node_ip6_active nodeip natip; do
 		T=
 		eval T="\$$i"
-		${miscdir}/sqlcli ${dbdir}/local.sqlite UPDATE local SET ${i}="${T}"
+		${miscdir}/sqlcli ${dbdir}/local.sqlite "UPDATE local SET ${i}='${T}'"
 	done
 
 	if [ -n "${INITCFG_PRESEED}" -a -r "${INITCFG_PRESEED}" ]; then
@@ -868,7 +876,7 @@ phase5()
 		eval myval=\$${i}
 		tmpval=$( /usr/local/bin/sqlite3 ${_formfile} "SELECT cur FROM forms WHERE param=\"${i}\" LIMIT 1" )
 		if [ -z "${tmpval}" ]; then
-			/usr/local/bin/sqlite3 ${_formfile} "UPDATE forms SET cur=\"${myval}\" WHERE param=\"${i}\""
+			/usr/local/bin/sqlite3 ${_formfile} "UPDATE forms SET cur='${myval}' WHERE param='${i}'"
 		fi
 	done
 }
