fix SC2181

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -230,8 +230,8 @@ fi
 # todo: there is a lot of duplicate code (for example, create_fs/from_zfssnap): cleaning required.
 if [ -n "${from}" ]; then
 	. "${temprcconf}"
-	jstatus jname="${jname}" > /dev/null 2>&1
-	[ $? -ne 0 ] && stderr 1 "${N1_COLOR}${CBSD_APP}: jail already exist: ${N2_COLOR}${jname}${N0_COLOR}"
+	jstatus jname="${jname}" > /dev/null 2>&1 \
+	|| stderr 1 "${N1_COLOR}${CBSD_APP}: jail already exist: ${N2_COLOR}${jname}${N0_COLOR}"
 
 	[ ! -r "${dbdir}"/images.sqlite ] && "${miscdir}"/updatesql "${dbdir}"/images.sqlite "${distdir}"/share/local-images.schema images
 
@@ -384,9 +384,8 @@ fi
 
 init_kerneldir
 
-jstatus jname="${jname}" > /dev/null 2>&1
-
-if [ $? -ne 0 ]; then
+if ! jstatus jname="${jname}" > /dev/null 2>&1;
+then
 	# Redis
 	if [ "${mod_cbsd_redis_enabled}" = "YES" ] && [ -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
 		cbsdredis publish cbsd_events '{"cmd":"jcreate", "node":"'"${nodename}"'", "jail":"'"${jname}"'", "status":2, "ip4_addr":"'"${ip4_addr}"'"}'
@@ -441,11 +440,9 @@ if [ "${mnt_start}" != "0" ]; then
 	if [ ${_ret} -ne 0 ]; then
 		err 1 "${W1_COLOR}error: ${N1_COLOR}mnt_start script failed: ${N2_COLOR}${mnt_start} -d ${data} -f ${jailfstabdir} -j ${jname} -r ${jailrcconfdir} -s ${jailsysdir}/${jname}${N0_COLOR}"
 	fi
-	create_fs "${data}"
-	[ $? -ne 0 ] && err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
+	create_fs "${data}" || err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
 else
-	create_fs "${data}"
-	[ $? -ne 0 ] && err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
+	create_fs "${data}" || err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
 fi
 
 [ ! -d "${data}" ] && err 1 "Can't create datadir ${data}"
@@ -495,8 +492,8 @@ if [ "${mdsize}" != "0" ]; then
 	${TOUCH_CMD} "${mdimage}"
 	${DD_CMD} if="/dev/zero" of="${mdimage}" bs=1m count=0 seek=${blockcount} 1> /dev/null 2>&1 || err 1 "jcreate error: couldn't create the image file. ${mdimage}"
 	# Attach the .img file as a memory disk.
-	mdimagedevice=$( ${MDCONFIG_CMD} -a -t vnode -f "${mdimage}" )
-	[ $? -eq 0 ] || err 1 "Error: Failed to mdconfig on ${mdimage}"
+	mdimagedevice=$( ${MDCONFIG_CMD} -a -t vnode -f "${mdimage}" ) \
+	|| err 1 "Error: Failed to mdconfig on ${mdimage}"
 	${NEWFS_CMD} -j -n -U "/dev/${mdimagedevice}" 1> /dev/null 2>&1 || ${MDCONFIG_CMD} -d -u "${mdimagedevice}" || err 1 "Error: Couldn't newfs the memory disk. ${mdimagedevice}"
 	${MDCONFIG_CMD} -d -u "${mdimagedevice}"
 	# mount here
@@ -674,8 +671,7 @@ if [ -n "${ci_user_pubkey}" ]; then
 		fi
 	else
 		# its relative path or pubkey string itself.
-		strpos --str="${ci_user_pubkey}" --search=" "
-		if [ $? -ne 0 ]; then
+		if ! strpos --str="${ci_user_pubkey}" --search=" "; then
 			# not path, check syntax
 			if ! is_valid_ssh_key "${ci_user_pubkey}"; then
 				jdestroy jname="${jname}" || true
