jail vnet: config eth0 when ip4_addr=DHCP/REALDHCP

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -814,6 +814,65 @@ fi
 
 # ci_gw4?
 if [ "${vnet}" = "1" -a "${ver}" != "empty" ]; then
+	_check_ip=0
+	case "${ip4_addr}" in
+		[Rr][Ee][Aa][Ll][Dd][Hh][Cc][Pp])
+			${SYSRC_CMD} -qf ${data}/etc/rc.conf ifconfig_eth0="DHCP" > /dev/null 2>&1
+			;;
+		[Dd][Hh][Cc][Pp])
+			_check_ip=1
+			ip4_addr=$( dhcpd )
+			_ret=$?
+			case "${_ret}" in
+				0)
+					true
+					;;
+				1)
+					${ECHO} "${W1_COLOR}${CBSD_APP} dhcp error, please check: ${N2_COLOR}cbsd dhcpd${N0_COLOR}"
+					;;
+				2)
+					${ECHO} "${W1_COLOR}${CBSD_APP} dhcp error: pools are exhausted (no free IPs in 'nodeippool'?, please check: ${N2_COLOR}cbsd dhcpd${N0_COLOR}"
+					;;
+			esac
+			;;
+		[Dd][Hh][Cc][Pp][vV]6)
+			_check_ip=1
+			ip4_addr=$( dhcpdv6 )
+			_ret=$?
+			case "${_ret}" in
+				0)
+					true
+					;;
+				1)
+					${ECHO} "${W1_COLOR}${CBSD_APP} dhcp error, please check: ${N2_COLOR}cbsd dhcpd${N0_COLOR}"
+					;;
+				2)
+					${ECHO} "${W1_COLOR}${CBSD_APP} dhcp error: pools are exhausted (no free IPs in 'nodeippool'?, please check: ${N2_COLOR}cbsd dhcpd${N0_COLOR}"
+					;;
+			esac
+			;;
+		*)
+			;;
+	esac
+
+	if [ ${_check_ip} -eq 1 ]; then
+		iptype ${ip4_addr}
+			_ret=$?
+			case "${_ret}" in
+				0)
+					${ECHO} "${W1_COLOR}${CBSD_APP} dhcp error, unknown IP type: ${N2_COLOR}cbsd dhcpd${N0_COLOR}"
+					;;
+				1)
+					${SYSRC_CMD} -qf ${data}/etc/rc.conf ifconfig_eth0="inet ${ip4_addr} up" > /dev/null 2>&1
+					jset jname=${jname} ip4_addr="${ip4_addr}"
+					;;
+				2)
+					${SYSRC_CMD} -qf ${data}/etc/rc.conf ifconfig_eth0="inet6 ${ip4_addr} up" > /dev/null 2>&1
+					jset jname=${jname} ip4_addr="${ip4_addr}"
+					;;
+			esac
+	fi
+
 	if [ -n "${ci_gw4}" ]; then
 		if [ "${ci_gw4}" != "0" ]; then
 			${SYSRC_CMD} -qf ${data}/etc/rc.conf defaultrouter="${ci_gw4}" > /dev/null 2>&1
