jcreate highlight the fatality of the error when the pool is exhausted.

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -529,7 +529,7 @@ mkfstab
 case "${ip4_addr}" in
 	[Dd][Hh][Cc][Pp])
 		ip4_addr=$( dhcpd )
-		[ $? -eq 2 ] && err 1 "${N1_COLOR}No free IP address for DHCP in nodeippool${N0_COLOR}"
+		[ $? -eq 2 ] && log_err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}${jname}: no free IP address for DHCP in 'nodeippool', please check: ${N2_COLOR}cbsd initenv-tui${N0_COLOR}"
 		${SYSRC_CMD} -qf ${temprcconf} ip4_addr="${ip4_addr}" > /dev/null
 		# CBSD QUEUE
 		if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
@@ -538,7 +538,7 @@ case "${ip4_addr}" in
 		;;
 	[Dd][Hh][Cc][Pp][vV]6)
 		ip4_addr=$( dhcpdv6 )
-		[ $? -eq 2 ] && err 1 "${N1_COLOR}No free IP address for DHCPv6 in nodeippool${N0_COLOR}"
+		[ $? -eq 2 ] && log_err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}${jname}: no free IP address for DHCPv6 in 'nodeip6pool', please check: ${N2_COLOR}cbsd initenv-tui${N0_COLOR}"
 		${SYSRC_CMD} -qf ${temprcconf} ip4_addr="${ip4_addr}" > /dev/null
 		# CBSD QUEUE
 		if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
