mountpoint: C implementation of dir=mount point
C implementation of checking that a directory is a mount point.
While here, better control when mount point already mounted

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -862,21 +862,21 @@ if [ ${res} -eq 0 ]; then
 		fi
 	fi
 
-	[ ${quiet} -ne 1 ] && echo
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd jconfig jname=${jname}${N0_COLOR}"
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd jstart ${jname}${N0_COLOR}"
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd jstop ${jname}${N0_COLOR}"
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd jremove ${jname}${N0_COLOR}"
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd jlogin ${jname}${N0_COLOR}"
-	[ ${quiet} -ne 1 ] && echo
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
+	[ ${quiet} -ne 1 ] && echo 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd jconfig jname=${jname}${N0_COLOR}" 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd jstart ${jname}${N0_COLOR}" 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd jstop ${jname}${N0_COLOR}" 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd jremove ${jname}${N0_COLOR}" 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd jlogin ${jname}${N0_COLOR}" 1>&2
+	[ ${quiet} -ne 1 ] && echo 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}" 1>&2
 
 	${RM_CMD} -f ${rcconf}
 	[ "${mdsize}" != "0" ] && unmountmd jroot=${data}
 else
-	[ ${quiet} -ne 1 ] && ${ECHO}
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Creating ${jname} failed: ${N2_COLOR}cbsd jregister${N0_COLOR}"
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Please review bad config file: ${N2_COLOR}/tmp/rc.conf_${jname}${N0_COLOR}"
+	[ ${quiet} -ne 1 ] && ${ECHO} 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Creating ${jname} failed: ${N2_COLOR}cbsd jregister${N0_COLOR}" 1>&2
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Please review bad config file: ${N2_COLOR}/tmp/rc.conf_${jname}${N0_COLOR}" 1>&2
 	${MV_CMD} ${rcconf} /tmp
 	#cleanup
 	[ -f "${mount_fstab}" ] && ${RM_CMD} -f ${mount_fstab}
@@ -1119,7 +1119,6 @@ if [ -n "${with_img_helpers}" ]; then
 		fi
 	done
 fi
-
 
 [ -n "${orunasap}" ] && runasap="${orunasap}"
 # autostart asap upon jail created
