skel for LUA init that i plan to use in some helpers. fix for updating jid in sqlite for local jails. Start of transfer rctl from ascii conf to sqlite. Colorized header in jrctl and jls. Jrctl without arguments out is jail list with their limits

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -1,11 +1,14 @@
 #!/bin/sh
-#v10.0.1
+#v10.0.2
 globalconf="${workdir}/cbsd.conf";
 MYARG="jconf"
-MYOPTARG="inter ver arch"
+MYOPTARG="inter ver arch customskel fstablocal delpkglist"
 MYDESC="Create jail from config file"
-ADDHELP="inter=0 to prevent any questions and to accept answers by default\n"
+ADDHELP="inter=0 to prevent any questions and to accept answers by default\n\
+customskel = additional skel directory applyed above jail structrure\n\
+fstablocal = additional fstab file stored as fstab.local\n"
 CBSDMODULE="jail"
+EXTHELP="html/wf_jcreate_en.html"
 
 [ -f ${globalconf} ] || err 1 "no such conf file";
 . ${globalconf}
@@ -16,6 +19,8 @@ CBSDMODULE="jail"
 . ${mdtools}
 . ${jfs}
 . ${color}
+. ${etcdir}/buildworld.conf
+. ${workdir}/universe.subr
 
 init $*
 
@@ -42,6 +47,12 @@ over="${ver}"
 oarch="${arch}"
 jconf=`realpath $jconf`
 
+if [ -z "${delpkglist}" ]; then
+    delpkglist=0
+else
+    delpkglist=1
+fi
+
 temprcconf="${ftmpdir}/jcreate_jconf.$$"
 
 cp ${jconf} ${temprcconf}
@@ -51,6 +62,10 @@ trap "rm -f ${temprcconf} ${jconf}" HUP INT ABRT BUS TERM  EXIT
 . ${temprcconf}
 . ${buildconf}
 . ${temprcconf}
+
+init_target_arch
+init_basedir
+init_kerneldir
 
 cbsd jstatus jname=${jname} > /dev/null 2>&1
 [ $? -eq 0 ] || err 1 "${MAGENTA}Jail with $jname already exist${NORMAL}"
@@ -116,23 +131,23 @@ fi
 ### COPY FROM BASE
 if [ "${ver}" != "empty" ]; then
     if [ "$baserw" = "1" ]; then
-#basepath variable from get_base
-	if ! populate_cdir ${basepath} ${data}; then
+#BASE_DIR variable from get_base
+	if ! populate_cdir ${BASE_DIR} ${data}; then
 	    [ "${mdsize}" != "0" ] && cbsd unmountmd jroot=${data}
-	    err 1 "Can't populate $data from $basepath"
+	    err 1 "Can't populate $data from $BASE_DIR"
 	fi
     else
-	cp -rP ${basepath}/etc ${data}/
-	cp -rP ${basepath}/root ${data}/
-	[ -f "${basepath}/etc/mtree/BSD.root.dist" ] && mtree -deU -f ${basepath}/etc/mtree/BSD.root.dist -p ${data} >/dev/null
-	[ -f "${basepath}/etc/mtree/BSD.usr.dist" ] && mtree -deU -f ${basepath}/etc/mtree/BSD.usr.dist -p ${data}/usr >/dev/null
-	[ -f "${basepath}/etc/mtree/BSD.var.dist" ] && mtree -deU -f ${basepath}/etc/mtree/BSD.var.dist -p ${data}/var >/dev/null
+	cp -rP ${BASE_DIR}/etc ${data}/
+	cp -rP ${BASE_DIR}/root ${data}/
+	[ -f "${BASE_DIR}/etc/mtree/BSD.root.dist" ] && mtree -deU -f ${BASE_DIR}/etc/mtree/BSD.root.dist -p ${data} >/dev/null
+	[ -f "${BASE_DIR}/etc/mtree/BSD.usr.dist" ] && mtree -deU -f ${BASE_DIR}/etc/mtree/BSD.usr.dist -p ${data}/usr >/dev/null
+	[ -f "${BASE_DIR}/etc/mtree/BSD.var.dist" ] && mtree -deU -f ${BASE_DIR}/etc/mtree/BSD.var.dist -p ${data}/var >/dev/null
 	# in FreeBSD10 BIND is go away
-	if [ -f "${basepath}/etc/mtree/BIND.chroot.dist" ]; then
+	if [ -f "${BASE_DIR}/etc/mtree/BIND.chroot.dist" ]; then
 	    [ ! -d "${data}/var/named" ] && mkdir ${data}/var/named
-	    mtree -deU -f ${basepath}/etc/mtree/BIND.chroot.dist -p ${data}/var/named >/dev/null
+	    mtree -deU -f ${BASE_DIR}/etc/mtree/BIND.chroot.dist -p ${data}/var/named >/dev/null
 	fi
-	[ -f "${basepath}/etc/mtree/BSD.sendmail.dist" ] && mtree -deU -f ${basepath}/etc/mtree/BSD.sendmail.dist -p ${data} >/dev/null
+	[ -f "${BASE_DIR}/etc/mtree/BSD.sendmail.dist" ] && mtree -deU -f ${BASE_DIR}/etc/mtree/BSD.sendmail.dist -p ${data} >/dev/null
 	if [ -n "${emulator}" -a "${emulator}" != "0" ]; then
 	    . ${workdir}/emulator.subr
 	    init_usermode_emul
@@ -151,9 +166,12 @@ if [ "${ver}" != "empty" ]; then
 
     if [ ${applytpl} -eq 1 ]; then
 
+	touch ${data}/etc/src.conf
+
 	if [ -d "${jailskeldir}" ]; then
 	    cd ${jailskeldir} && find -E ${jailskeldir} \( -type f -or -type d -or -type l \) -print |sed s:${jailskeldir}:./:g |cpio -pdmu ${data} > /dev/null 2>&1
 	fi
+
 	
 	if [ -f ${data}/master.passwd ]; then
 	    /usr/sbin/pwd_mkdb -d ${data}/etc ${data}/etc/master.passwd
@@ -162,41 +180,52 @@ if [ "${ver}" != "empty" ]; then
 	[ ! -f ${data}/etc/localtime ] && cp /etc/localtime ${data}/etc
 
     fi
+
+    if [ -n "${customskel}" -a -d "${customskel}" ]; then
+	$ECHO "${MAGENTA}Apply custom skeldir from: ${GREEN}${customskel}${NORMAL}"
+	cd ${customskel} && find -E ${customskel} \( -type f -or -type d -or -type l \) -print |sed s:${customskel}:./:g |cpio -pdmu ${data} > /dev/null 2>&1
+    fi
+
 fi  # if ver = empty
 
 mkfstab
 cp $temprcconf $rcconf
 
-[ ${applytpl} -eq 1 ] && ${miscdir}/config_pkgrepo -t ${etcdir}/pkg.conf -v ${ver} -a ${arch} ${data}
+[ -n "${fstablocal}" -a -f "${fstablocal}" ] && cp ${fstablocal} ${jailfstabdir}/${jailfstabpref}${jname}.local
 
+
+#[ ${applytpl} -eq 1 ] && ${miscdir}/config_pkgrepo -t ${etcdir}/pkg.conf -v ${ver} -a ${arch} ${data}
 # pkg area
-if [ "${pkglist}" != "NO" -a "${ver}" != "empty" -a -f "${pkglist}" ]; then
-    ${ECHO} "${MAGENTA}Populate jail from pkglist: ${GREEN}${pkglist}${NORMAL}"
-    mountbase
-    cbsd mountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
-    mount -t devfs devfs $path/dev
-
-    [ ! -d "${path}/usr/local/etc" ] && mkdir ${path}/usr/local/etc
-
-    printf "${MAGENTA}pkg: [${GREEN}bootstrap... "
-    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg > /dev/null 2>&1
-    # remove default pkg.conf
-    #[ -f "${path}/usr/local/etc/pkg.conf" ] && rm -f ${path}/usr/local/etc/pkg.conf
-    printf "looking for new version... "
-    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg update -f > /dev/null 2>&1
-    #lets upgrade pkg if new version available
-    printf "upgrading... "
-#need for pkg upgrade twice for reinstalling pkg with "needed shared library changed"
-    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg upgrade -f > /dev/null 2>&1
-#need for pkg upgrade twice for reinstalling pkg with "needed shared library changed"
-    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg upgrade -f > /dev/null 2>&1
-    PKGLIST=`cat ${pkglist} |xargs`
-    printf "install for ${PKGLIST}...${MAGENTA}]${NORMAL}\n"
-    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg install ${PKGLIST}
-    cbsd unmountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
-    umount -f ${path}/dev
-    unmountbase
-    rm -f ${pkglist}
+if [ "${pkglist}" != "NO" -a "${ver}" != "empty" ]; then
+    if [ ! -f "${pkglist}" ]; then
+	${ECHO} "${MAGENTA}pkglist specified but not exist: ${GREEN}${pkglist}${NORMAL}"
+    else
+	${ECHO} "${MAGENTA}Populate jail from pkglist: ${GREEN}${pkglist}${NORMAL}"
+	mountbase
+	[ -f "${mount_fstab}" ] && cbsd mountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
+	[ -f "${mount_fstab}.local" ] && cbsd mountfstab jroot=${path} fstab=${mount_fstab}.local > /dev/null 2>&1
+	mount -t devfs devfs $path/dev
+	[ ! -d "${path}/usr/local/etc" ] && mkdir ${path}/usr/local/etc
+	printf "${MAGENTA}pkg: [${GREEN}bootstrap... "
+	chroot ${path} env ASSUME_ALWAYS_YES=yes pkg > /dev/null 2>&1
+	# remove default pkg.conf
+	#[ -f "${path}/usr/local/etc/pkg.conf" ] && rm -f ${path}/usr/local/etc/pkg.conf
+	printf "looking for new version... "
+	chroot ${path} env ASSUME_ALWAYS_YES=yes pkg update -f > /dev/null 2>&1
+	#lets upgrade pkg if new version available
+	printf "upgrading... "
+	#need for pkg upgrade twice for reinstalling pkg with "needed shared library changed"
+	chroot ${path} env ASSUME_ALWAYS_YES=yes pkg upgrade -f > /dev/null 2>&1
+	#need for pkg upgrade twice for reinstalling pkg with "needed shared library changed"
+	chroot ${path} env ASSUME_ALWAYS_YES=yes pkg upgrade -f > /dev/null 2>&1
+	PKGLIST=`cat ${pkglist} |xargs`
+	printf "install for ${PKGLIST}...${MAGENTA}]${NORMAL}\n"
+	chroot ${path} env ASSUME_ALWAYS_YES=yes pkg install ${PKGLIST}
+	cbsd unmountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
+	umount -f ${path}/dev
+	unmountbase
+	[ $delpkglist -eq 1 ] && rm -f ${pkglist}
+    fi
 fi
 
 [ "${mdsize}" != "0" ] && cbsd unmountmd jroot=${data}
diff --git a/tools/repo b/tools/repo
--- a/tools/repo
+++ b/tools/repo
@@ -1,10 +1,10 @@
 #!/bin/sh
-#v10.0.0
+#v10.0.2
 globalconf="${workdir}/cbsd.conf";
 MYARG="action"
 # action=list,get,put
 # source=src,obj,base,kernel,img
-MYOPTARG="mode arch ver sources name basename stable inter"
+MYOPTARG="mode arch targer_arch ver sources name basename stable inter"
 #mode=check,update,upgrade
 MYDESC="Working with CBSD Repository"
 ADDHELP="action can be: list, get, put
@@ -28,6 +28,9 @@ origver="${ver}"
 # prefered for ver in arg
 [ "${ver}" != "${origver}" -a -n "${origver}" ] && ver=$origver
 
+. ${etcdir}/buildworld.conf
+. ${workdir}/universe.subr
+
 fetchme()
 {
     cbsd cfetch -u $1 -o ${TF}
@@ -49,14 +52,14 @@ checkmd5()
 	fi
     done
 
-return ${_GOOD}
+    return ${_GOOD}
 }
 
 
 
 checkrepo()
 {
-local _i
+    local _i
 
     for _i in ${REPO}; do
 	[ -z $1 ] && printf "${MAGENTA}Check for repository${NORMAL}: ${GREEN}${_i}${NORMAL} ..."
@@ -73,6 +76,7 @@ local _i
 
 getsrc()
 {
+    init_srcdir
 
     if [ -d "${srcdir}/${DIR}" ]; then
 	[ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
@@ -105,7 +109,9 @@ getsrc()
 
     ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
     cd $workdir/tmp
+    set -e
     tar xfz ${MYDIR}/src.txz
+    set +e
     rm -f ${MYDIR}/src.txz
     mkdir -p ${srcdir}/src_${ver}
     mv ${workdir}/tmp/src_${ver} ${srcdir}/
@@ -123,13 +129,13 @@ getbase()
 	BDIR="${basejailpref}_${basename}_${arch}_${ver}"
     fi
 
-    DST="${basejaildir}/${BDIR}"
     MIRROR="http://ftp.freebsd.org"
-    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/base.txz"
+    FHIER="${arch}/${target_arch}/${ver}"
+    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${FHIER}-RELEASE/base.txz"
 
-    if [ -d "${DST}" ]; then
+    if [ -d "${BASE_DIR}" ]; then
 	[ $UPGRADE -eq 1 ] || err 1 "${MAGENTA}You already have ${ver}. Use mode=upgrade for upgrade${NORMAL}"
-	chflags -R noschg ${DST}
+	chflags -R noschg ${BASE_DIR}
     fi
 
     if [ "$fbsdrepo" = "1" -a -z "${basename}" ]; then
@@ -139,22 +145,26 @@ getbase()
 	cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
 	if [ $? -eq 0 ]; then
 	    printf "\n${MAGENTA}Extracting base...${NORMAL}\n"
-	    mkdir $DST
-	    cd $DST
+	    mkdir $BASE_DIR
+	    cd $BASE_DIR
+	    set -e
 	    tar xfz ${ARCHIVE}
+	    set +e
 	    rm -f ${ARCHIVE}
-	    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/lib32.txz"
+	    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${FHIER}-RELEASE/lib32.txz"
 	    ARCHIVE="$MYDIR/lib32.txz"
 	    cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
 		if [ $? -eq 0 ]; then
 		    printf "\n${MAGENTA}Extracting lib32...${NORMAL}\n"
-		    cd $DST
+		    cd $BASE_DIR
+		    set -e
 		    tar xfz ${ARCHIVE}
+		    set +e
 		    rm -f ${ARCHIVE}
 		else
 		    printf "${GREEN} Lib32 not found${NORMAL}\n"
 		fi
-	    cbsd preparebase dst=${DST}
+	    cbsd preparebase dst=${BASE_DIR}
 	    ${ECHO} "${MAGENTA}Done...${NORMAL}"
 	    return 0
 	fi
@@ -162,17 +172,12 @@ getbase()
     ### Official fbsd repo end ###
     fi
 
-    _srcmd5_found=0
+#    _srcmd5_found=0
     _src_found=0
 
     for MYREPO in $REPO; do
 	${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
-	if [ -z "${basename}" ]; then
-	    MIRROR="${MYREPO}/base_${arch}_${ver}/mirror.html";
-	else	
-	    MIRROR="${MYREPO}/base_${basename}_${arch}_${ver}/mirror.html";
-	fi
-
+	MIRROR="${MYREPO}/releases/${FHIER}/mirror.html";
 	cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 	if [ $? -eq 0 ]; then
@@ -181,72 +186,78 @@ getbase()
 	fi
 
 	if [ -z "${basename}" ]; then
-	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz${NORMAL}"
-	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz
+	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/base.txz${NORMAL}"
+	    cbsd cfetch -o ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/base.txz
 
 	    if [ $? -ne 0 ]; then
-		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz${NORMAL}"
+		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${FHIER}/base.txz${NORMAL}"
 		continue
 	    else
 		_src_found=1
 	    fi
 
-	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+#	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
 
-	    if [ $? -ne 0 ]; then
-		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
-		continue
-	    else
+#	    if [ $? -ne 0 ]; then
+#		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
+#		continue
+#	    else
 		_srcmd5_found=1
-	    fi
+#	    fi
 	else
-	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz${NORMAL}"
-	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz
+	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/base_${basename}.txz${NORMAL}"
+	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/base_${basename}.txz
 
 	    if [ $? -ne 0 ]; then
-		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz${NORMAL}"
+		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${FHIER}/base_${basename}.txz${NORMAL}"
 		continue
 	    else
 		_src_found=1
 	    fi
 
-	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+#	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
 
-	    if [ $? -ne 0 ]; then
-		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
-		continue
-	    else
+#	    if [ $? -ne 0 ]; then
+#		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
+#		continue
+#	    else
 		_srcmd5_found=1
-	    fi
+#	    fi
 	fi
 
-    [ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
+	[ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
     done
 
-    if checkmd5 ${MYDIR}; then
-	${ECHO} "${MAGENTA}MD5 sum:${GREEN} correct${NORMAL}"
-    else
-	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
-    fi
+#    if checkmd5 ${MYDIR}; then
+#	${ECHO} "${MAGENTA}MD5 sum:${GREEN} correct${NORMAL}"
+#    else
+#	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
+#    fi
 
-    if [ -z "${basename}" ]; then
-	rm -f  ${MYDIR}/base_${arch}_${ver}.txz.md5
-    else
-	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
-    fi
+#    if [ -z "${basename}" ]; then
+#	rm -f  ${MYDIR}/base_${arch}_${ver}.txz.md5
+#    else
+#	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
+#    fi
+
+    [ ${_src_found} -ne 1 ] && err 1 "${MAGENTA}Not found data${NORMAL}"
 
     ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
-    [ -d "$basejaildir" ] | mkdir -p ${basejaildir}
+    [ ! -d "${BASE_DIR}" ] && mkdir -p ${BASE_DIR}
     #/base_${arch}_${ver}
-    cd $basejaildir
+    cd $BASE_DIR
     #/base_${arch}_${ver}
 
     if [ -z "${basename}" ]; then
-	tar xfz ${MYDIR}/base_${arch}_${ver}.txz
-	rm -f ${MYDIR}/base_${arch}_${ver}.txz.md5
+	set -e
+	tar xfz ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz
+	set +e
+#	rm -f ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz.md5
     else
-	tar xfz ${MYDIR}/base_${basename}_${arch}_${ver}.txz
-	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
+	set -e
+	tar xfz ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz
+	set +e
+#	rm -f ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz.md5
     fi
 
     ${ECHO} "${MAGENTA}Done...${NORMAL}"
@@ -312,7 +323,9 @@ rm -f ${MYDIR}/obj_${arch}_${ver}.txz.md5
 
 ${ECHO} "Extracting..."
 cd $srcdir
+set -e
 tar xfz ${MYDIR}/obj_${arch}_${ver}.txz
+set +e
 rm -f ${MYDIR}/obj_${arch}_${ver}.txz
 ${ECHO} "Done..."
 }
@@ -320,17 +333,26 @@ ${ECHO} "Done..."
 
 getkernel()
 {
-    [ -z "${name}" ] && name="GENERIC"
-    DST="${basejaildir}/kernel_${name}_${arch}_${ver}"
+    local name KERNNAME
 
-    if [ -d "${DST}" ]; then
-	[ $UPGRADE -eq 1 ] || err 1 "${MAGENTA}You already have kernel ${name} for ${ver}${NORMAL}"
+#    [ -z "${name}" ] && name="GENERIC"
+#    KERNNAME="_${name}_"
+    if [ -n "${name}" -a "${name}" != "GENERIC" ]; then
+	KERNNAME="_${name}_"
+    else
+	KERNNAME=""
+    fi
+
+    FHIER="${arch}/${target_arch}/${ver}"
+
+    if [ -d "${KERNEL_DIR}" ]; then
+	[ $UPGRADE -ne 1 ] && err 1 "${MAGENTA}You already have kernel ${name} for ${ver}${NORMAL}"
 	cbsd removekernel ver=${ver} arch=${arch} name=${name}
     fi
 
     for MYREPO in $REPO; do
 	${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
-	MIRROR="${MYREPO}/kernel_${name}_${arch}_${ver}/mirror.html"
+	MIRROR="${MYREPO}/releases/${FHIER}/mirror.html"
 	cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 	if [ $? -eq 0 ]; then
@@ -338,27 +360,30 @@ getkernel()
 	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
 	fi
 
-	${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz${NORMAL}"
-	cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz
+	${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/kernel${KERNNAME}.txz${NORMAL}"
+	cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/kernel${KERNNAME}.txz
 	[ $? -eq 0 ] || continue
-	cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
-	[ $? -eq 0 ] || continue
+#	cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+#	[ $? -eq 0 ] || continue
     done
 
-    [ -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz" -a -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5" ] || err 1 "${MAGENTA}No such sources:${GREEN}${MYDIR}/kernel_${name}_${arch}_${ver}.txz and/or ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5${NORMAL}"
+    [ ! -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz" ] && err 1 "${MAGENTA}No such sources:${GREEN}${MYDIR}/kernel_${name}_${arch}_${ver}.txz${NORMAL}"
 
-    if checkmd5 ${MYDIR}; then
-	${ECHO} "${MAGENTA}MD5 sum: ${GREEN}correct${NORMAL}"
-    else
-	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
-	exit 1
-    fi
+#    if checkmd5 ${MYDIR}; then
+#	${ECHO} "${MAGENTA}MD5 sum: ${GREEN}correct${NORMAL}"
+#    else
+#	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
+#	exit 1
+#    fi
 
-    rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5
+#    rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5
 
     ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
-    cd $basejaildir
+    [ ! -d "${KERNEL_DIR}" ] && mkdir -p ${KERNEL_DIR}
+    cd $KERNEL_DIR
+    set -e
     tar xfz ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
+    set +e
     rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
     ${ECHO} "${MAGENTA}Done...${NORMAL}"
 }
@@ -366,35 +391,36 @@ getkernel()
 
 getimg()
 {
-DST="${importdir}/${name}.img"
+    local DST="${importdir}/${name}.img"
+    FHIER="${arch}/${target_arch}/${ver}"
 
-if [ -f "${DST}" ]; then
-    if ! getyesno "${MAGENTA}You already have ${DST}. Remove them?${NORMAL}"; then
-	err 1 "${MAGENTA}You already have: ${GREEN}${DST}${NORMAL}"
-    else
-	rm -f ${DST}
-    fi
-fi
-
-cbsd jstatus jname=${name} > /dev/null 2>&1
-[ $? -ne 0 ] && err 1 "${MAGENTA}You already have installed jail:${GREEN}${name}${NORMAL}"
-
-for MYREPO in $REPO; do
-    ${ECHO} "${MAGENTA}REPO:${GREEN} ${MYREPO}"
-    MIRROR="${MYREPO}/img_${arch}_${ver}_${name}/mirror.html"
-    cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
-
-    if [ $? -eq 0 ]; then
-	MYREPO=`cat ${TF}`
-	${ECHO} "${MAGENTA}Found new mirror for ${name} ${NORMAL}: ${MYREPO}"
+    if [ -f "${DST}" ]; then
+	if ! getyesno "${MAGENTA}You already have ${DST}. Remove them?${NORMAL}"; then
+	    err 1 "${MAGENTA}You already have: ${GREEN}${DST}${NORMAL}"
+	else
+	    rm -f ${DST}
+	fi
     fi
 
-    ${ECHO} "${MAGENTA}Fetching ${name} jail: ${GREEN}${MYREPO}/${DIR}${MAGENTA}${NORMAL}"
-    cbsd cfetch -o ${DST} -u ${MYREPO}${DIR}
-    [ $? -eq 0 ] || continue
-done
+    cbsd jstatus jname=${name} > /dev/null 2>&1
+    [ $? -ne 0 ] && err 1 "${MAGENTA}You already have installed jail:${GREEN}${name}${NORMAL}"
 
-[ -f "${DST}" ] || err 1 "No such remote file or network problem"
+    for MYREPO in $REPO; do
+	${ECHO} "${MAGENTA}REPO:${GREEN} ${MYREPO}"
+	MIRROR="${MYREPO}/img/${FHIER}/${name}/mirror.html"
+	cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
+
+	if [ $? -eq 0 ]; then
+	    MYREPO=`cat ${TF}`
+	    ${ECHO} "${MAGENTA}Found new mirror for ${name} ${NORMAL}: ${MYREPO}"
+	fi
+
+	${ECHO} "${MAGENTA}Fetching ${name} jail: ${GREEN}${MYREPO}/${DIR}${MAGENTA}${NORMAL}"
+	cbsd cfetch -o ${DST} -u ${MYREPO}/img/${FHIER}/${name}.img
+	[ $? -eq 0 ] || continue
+    done
+
+    [ ! -f "${DST}" ] && err 1 "No such remote file or network problem"
 }
 
 gethelpers()
@@ -432,7 +458,9 @@ DST="${sharedir}/helpers"
 		err 1 "${MAGENTA}Helpers already exist: ${GREEN}${name}${MAGENTA}. Use mode=upgrade for upgrading.${NORMAL}"
 	    fi
 	    mkdir ${DST}/${name}
+	    set -e
 	    tar xfz ${tmpdir}/helpers/helpers_${name}.$$.tgz -C ${DST}/${name}
+	    set +e
 	    rm -f ${tmpdir}/helpers/helpers_${name}.$$.tgz
     fi
 
@@ -453,6 +481,11 @@ case "${mode}" in
     "upgrade") UPGRADE=1;;
     "quiet") QUIET=1;;
 esac
+
+init_target_arch
+init_supported_arch
+init_basedir
+init_kerneldir
 
 case "${action}" in
 "ping")
@@ -482,64 +515,58 @@ for i in ${REPO}; do
 done
 ;;
 "get")
-[ -z "${sources}" ] && err 1 "Give me sources"
-
-case "${sources}" in
-"src")
-    DIR="src_${ver}"; 
-    DST="${srcdir}/src_${ver}"
-    LOCKFILE=${DST}.lock
-    makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}" safe
-    mkdir -p ${MYDIR}
-    getsrc ;;
-"base")
-    if [ -z "${basename}" ]; then
-	DIR="base_${arch}_${ver}"; 
-    else
-	DIR="base_${basename}_${arch}_${ver}"; 
-    fi
-    SRC="${srcdir}/src_${ver}"
-    LOCKFILE=${SRC}.lock
-    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
-    mkdir -p ${MYDIR}
-    getbase ;;
-"obj")
-    if [ -z "${basename}" ]; then
-	DIR="obj_${arch}_${ver}";
-    else
-	DIR="obj_${basename}_${arch}_${ver}";
-    fi
-    SRC="${srcdir}/src_${ver}"
-    LOCKFILE=${SRC}.lock
-    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
-    mkdir -p ${MYDIR}
-    getobj ;;
-"kernel")
-    [ -z "${name}" ] && name="GENERIC"
-    DIR="kernel_${name}_${arch}_${ver}"
-    SRC="${srcdir}/src_${ver}"
-    LOCKFILE=${SRC}.lock
-    makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
-    mkdir -p ${MYDIR}
-    getkernel ;;
-"img")
-    [ -z "${name}" ] && err 1 "Give me name"
-    DIR="img_${arch}_${ver}_${name}/${name}.img"
-    LOCKFILE="${jaildir}/${name}.lock"
-    makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}"
-    mkdir -p ${MYDIR}
-    getimg
-    [ "${usehelpers}" = "1" ] && gethelpers ${name} ${name}
-    ${ECHO} "${MAGENTA}Done... Importing...${NORMAL}"
-    cbsd jimport jname=${name}
-    [ "${usehelpers}" = "1" ] && cbsd jconfig jname=${name} ${name}cfg
-    cbsd jsetup-tui jname=${name} ip4_addr interface astart host_hostname
-    cbsd jconfig mode=list jname=${name}
-    ;;
-"helpers")
-    gethelpers
-    ;;
-
-esac ## END of source case
-
+    [ -z "${sources}" ] && err 1 "Give me sources"
+    case "${sources}" in
+    "src")
+	DIR="src_${ver}"; 
+	DST="${srcdir}/src_${ver}"
+	LOCKFILE=${DST}.lock
+	makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}" safe
+	mkdir -p ${MYDIR}
+	getsrc
+	;;
+    "base")
+#	LOCKFILE=${SRC}.lock
+#	makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
+	trap "rm -f ${TF}; rm -rf ${MYDIR}"
+	mkdir -p ${MYDIR}
+	getbase
+	;;
+    "obj")
+	if [ -z "${basename}" ]; then
+	    DIR="obj_${arch}_${ver}";
+	else
+	    DIR="obj_${basename}_${arch}_${ver}";
+	fi
+	SRC="${srcdir}/src_${ver}"
+	LOCKFILE=${SRC}.lock
+	makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
+	mkdir -p ${MYDIR}
+	getobj
+	;;
+    "kernel")
+#	[ -z "${name}" ] && name="GENERIC"
+#	LOCKFILE=${SRC}.lock
+#	makelock $LOCKFILE "rm -f ${TF}; rm -rf ${MYDIR}" safe
+	trap "rm -f ${TF}; rm -rf ${MYDIR}"
+	mkdir -p ${MYDIR}
+	getkernel
+	;;
+    "img")
+	[ -z "${name}" ] && err 1 "Give me name"
+	LOCKFILE="${jaildir}/${name}.lock"
+	makelock ${LOCKFILE} "rm -f ${TF}; rm -rf ${MYDIR}"
+	mkdir -p ${MYDIR}
+	getimg
+	[ "${usehelpers}" = "1" ] && gethelpers ${name} ${name}
+	${ECHO} "${MAGENTA}Done... Importing...${NORMAL}"
+	cbsd jimport jname=${name}
+	[ "${usehelpers}" = "1" ] && cbsd jconfig jname=${name} ${name}cfg
+	cbsd jsetup-tui jname=${name} ip4_addr interface astart host_hostname
+	cbsd jconfig mode=list jname=${name}
+	;;
+    "helpers")
+	gethelpers
+	;;
+    esac ## END of source case
 esac ## END of action case
