rewrote some lines for better portability

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -577,7 +577,14 @@ if [ "${mdsize}" != "0" ]; then
 	mdimage="${jailsysdir}/${jname}/image.dat"
 	${TOUCH_CMD} "${mdimage}"
 	# Linux does not support postfix in bs=, e.g. bs=1m
-	${DD_CMD} if="/dev/zero" of="${mdimage}" bs=1000000 count=0 seek=${blockcount} 1> /dev/null 2>&1 || err 1 "jcreate error: couldn't create the image file. ${mdimage}"
+	case "${platform}" in
+		Linux)
+			${DD_CMD} if="/dev/zero" of="${mdimage}" bs=1000000 count=0 seek=${blockcount} 1> /dev/null 2>&1 || err 1 "jcreate error: couldn't create the image file. ${mdimage}"
+			;;
+		*)
+			${DD_CMD} if="/dev/zero" of="${mdimage}" bs=1m count=0 seek=${blockcount} 1> /dev/null 2>&1 || err 1 "jcreate error: couldn't create the image file. ${mdimage}"
+			;;
+	esac
 	# Attach the .img file as a memory disk.
 	mdimagedevice=$( ${MDCONFIG_CMD} -a -t vnode -f "${mdimage}" ) \
 	|| err 1 "Error: Failed to mdconfig on ${mdimage}"
