shellcheck sudoexec/jlogin

diff --git a/sudoexec/jlogin b/sudoexec/jlogin
--- a/sudoexec/jlogin
+++ b/sudoexec/jlogin
@@ -1,5 +1,7 @@
 #!/usr/local/bin/cbsd
-#v13.0.1
+# shellcheck shell=sh disable=2086,1090,2154,2166,3043,1091,2034
+# v13.0.1
+
 MYARG=""
 MYOPTARG="jname remote src_session user"
 MYDESC="Exec login into jail"
@@ -106,7 +108,7 @@ login_internal()
 			if [ -f "${data}/bin/bash" ]; then
 				LOGIN_STR="/bin/bash"
 			elif [ -f "${data}/bin/sh" ]; then
-				LOGIN_STR="/bin/sh" ];
+				LOGIN_STR="/bin/sh"
 			else
 				err 1 "${N1_COLOR}Unknown environment, unable to login${N0_COLOR}"
 			fi
@@ -115,8 +117,8 @@ login_internal()
 			[ -n "${ouser}" ] && user="${ouser}"
 			if [ "${user}" != "root" ]; then
 				# additional check for user existance
-				_res=$( ${PW_CMD} -R ${path} usershow ${user} 2>&1 )
-				[ $? -ne 0 ] && err 1 "${N1_COLOR}Unable to find user: ${_res}${N0_COLOR}"
+				_res=$( ${PW_CMD} -R ${path} usershow ${user} 2>&1 ) \
+				|| err 1 "${N1_COLOR}Unable to find user: ${_res}${N0_COLOR}"
 			fi
 
 			if [ "${emulator}" != "jail" -a -n "${emulator}" ]; then
@@ -131,6 +133,7 @@ login_internal()
 	esac
 
 	if [ "${platform}" = "DragonFly" ]; then
+		# shellcheck disable=2153
 		jexec="/usr/bin/nice -n ${nice} ${JEXEC_CMD} ${jid} ${LOGIN_STR}"
 	else
 		jexec="/usr/bin/nice -n ${nice} ${SETFIB} ${CPUSET} ${JEXEC_CMD} ${jid} ${LOGIN_STR}"
@@ -162,8 +165,6 @@ login_custom()
 	readconf jlogin.conf
 	${ECHO} "${N1_COLOR}Custom login command: ${N2_COLOR}${login_cmd}${N0_COLOR}"
 	exec /bin/sh -c "${login_cmd}"
-	# restore CBSD PATH
-	export PATH="${CBSDPATH}"
 }
 
 # jname must be set
