sync last modification for jsnapshot

diff --git a/sudoexec/jsnapshot b/sudoexec/jsnapshot
--- a/sudoexec/jsnapshot
+++ b/sudoexec/jsnapshot
@@ -1,55 +1,118 @@
 #!/bin/sh
-#v9.2.0
+#v10.0.3
 globalconf="${workdir}/cbsd.conf";
 MYARG="mode"
-MYOPTARG="jname snapname snapfs"
+MYOPTARG="jname snapname snapfs header display"
 MYDESC="Jail snapshot management"
-ADDHELP="mode can: list, create, destroy, destroyall, clone, rollback\n
-snapfs can be: rsync\n
-snapname can be: gettimeofday\n"
+ADDHELP="mode can: list, create, destroy, destroyall, clone, rollback\n\
+snapfs can be: rsync\n\
+snapname can be: \"gettimeofday\" or any arbitrary word\n\
+header=0 don't print header\n\
+display= list by comma for column. Default: snapname,jname,creation\n"
 CBSDMODULE="jail"
 
 [ -f ${globalconf} ] || err 1 "no such conf file";
 . ${globalconf}
 . ${subr}
 . ${inventory}
+. ${color}
+. ${strings}
 init $*
 
-
-zfssnapshot_list()
+show_header()
 {
-    if [ -n "${jname}" ]; then
-	if zfsroot ${jname}; then
-	    /sbin/zfs list -H -r -t snapshot -o name,creation ${ZPOOL}/${jname}|sed s:${ZPOOL}\/${jname}@::g
-	fi
-    else
-	/sbin/zfs list -H -r -t snapshot -o name,creation
-    fi
+    local _header="${BOLD}${myheader}${NORMAL}"
+    [ ${header} -ne 0 ] && $ECHO ${_header}
 }
 
 
-zfssnapshot_destroyall()
+check_jname()
 {
-    if [ -n "${jname}" ]; then
-	if zfsroot ${jname}; then
-	    /sbin/zfs list -H -r -t snapshot -o name ${ZPOOL}/${jname}|sed s:${ZPOOL}\/${jname}@::g| while read _snap; do
-		[ -n "${_snap}" ] && zfssnapshot_destroy ${_snap}
-	    done
-	fi
-    else
-	err 1 "jname is necessary"
-    fi
+    [ -z "${jname}" ] && err 1 "${MAGENTA}Please set ${GREEN}jname=${NORMAL}"
+    . ${jrcconf}
+    [ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
 }
 
-rsyncsnapshot_list()
+zfs_snapshot_list()
 {
-    err 1 "Rsync Not implemented"
+    local _mod _fs _p1 _jname _createtime _status _snaptime _snapname
+    [ -n "${jname}" ] && _mod="${ZPOOL}/${jname}"
+
+    show_header
+
+    for _fs in $(/sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null); do
+	_status=""
+	_jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}")
+	[ -z "${_jname}" ] && continue
+	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
+	_snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}")
+	[ -z "${_snapname}" ] && continue
+	#populate values for in output string
+	for _i in ${mydisplay}; do
+	    case "${_i}" in
+		"snapname")
+		    _status="${_status}${_snapname} "
+		    ;;
+		"jname")
+		    _status="${_status}${_jname} "
+		    ;;
+		"creation")
+		    _createtime=$(zfs get -H -o value creation "${_fs}")
+		    _snaptime=$( date -j -f "%a %b %d %T %Y" "${_createtime}" "+%Y-%m-%d__%H:%M" )
+		    _status="${_status}${_snaptime} "
+		    ;;
+	    esac
+	done
+	${ECHO} "${NORMAL}${_status}"
+    done
+}
+
+zfs_snapshot_destroyall()
+{
+    local _fs _jname _mod _snapname
+
+    [ -n "${jname}" ] && _mod="${ZPOOL}/${jname}"
+
+    for _fs in $(/sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null); do
+	_jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}")
+	[ -z "${_jname}" ] && continue
+	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
+	_snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}")
+	[ -z "${_snapname}" ] && continue
+	zfs_snapshot_destroy ${_fs} && ${ECHO} "${MAGENTA}zfs snapshot for ${jname} destoyed: ${GREEN}${_snapname}${NORMAL}"
+    done
 }
 
 
-ufssnapshot_list()
+zfs_snapshot_destroy_by_snapname()
 {
-    err 1 "UFS Not implemented"
+    local _fs _jname _mod _snapname _chkloop=0
+
+    [ -z "${snapname}" ] && err 1 "${MAGENTA}Please set ${GREEN}snapname=${MAGENTA} or use ${GREEN}mode=destroyall ${MAGENTA}to destroy all snapshots for this jail${NORMAL}"
+    [ -n "${jname}" ] && _mod="${ZPOOL}/${jname}@${snapname}"
+
+    for _fs in $(/sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null); do
+	_chkloop=$(( _chkloop + 1 ))
+	# normally we never got _chkloop greater than 1
+	[ ${_chkloop} -gt 10 ] && err 1 "${MAGENTA}Error for parsing snapname in zfs_snapshot_destroy_by_snapname${NORMAL}"
+	_jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}")
+	[ -z "${_jname}" ] && continue
+	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
+	_snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}")
+	[ -z "${_snapname}" -o "${_snapname}" != "${snapname}" ] && continue
+	zfs_snapshot_destroy ${_fs} && ${ECHO} "${MAGENTA}zfs snapshot for ${jname} destoyed: ${GREEN}${_snapname}${NORMAL}"
+	# if cycle is not end than something wrong with parsing of snapname
+    done
+}
+
+rsync_snapshot_list()
+{
+    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+}
+
+ufs_snapshot_list()
+{
+    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
     fs_type="ufs"
 
     for snap in `snapinfo $fs_dir 2>/dev/null`; do
@@ -87,84 +150,114 @@ ufssnapshot_list()
     done
 }
 
-zfssnapshot_create()
+zfs_snapshot_create()
 {
-    [ -z "${jname}" ] && err 1 "Empty jname"
+    local _tst _createtime
+
+    [ -z "${snapname}" ] && err 1 "${MAGENTA}Empty ${GREEN}snapname=${NORMAL}"
+
+    _createtime=$(date "+%Y%m%d%H%M%S")
+    [ "${snapname}" = "gettimeofday" ] && snapname=${_createtime}
+
+    _tst=$(zfs snapshot ${ZPOOL}/${jname}@${snapname} 2>&1)
+    [ $? -ne 0 ] && err 1 "${MAGENTA}zfs snapshot error: ${NORMAL}${_tst}"
+    zfs set cbsdsnap:jname=${jname} ${ZPOOL}/${jname}@${snapname}
+    zfs set cbsdsnap:snapname=${snapname} ${ZPOOL}/${jname}@${snapname}
+}
+
+ufs_snapshot_create()
+{
+    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+}
+
+rsync_snapshot_create()
+{
+    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+}
+
+zfs_snapshot_destroy()
+{
+    [ -z "${1}" ] && return 1
+    zfs destroy ${1}
+}
+
+ufs_snapshot_destroy()
+{
+    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+}
+
+ufs_snapshot_destroyall()
+{
+    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+}
+
+ufs_snapshot_destroy_by_snapname()
+{
+    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+}
+
+rsync_snapshot_destroy()
+{
+    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+}
+
+
+zfs_snapshot_rollback()
+{
     [ -z "${snapname}" ] && err 1 "Empty snapname"
-
-    [ "$snapname" = "gettimeofday" ] && snapname=`date "+%Y%m%d%H%M%S"`
-
-    A=`cbsd jstatus jname=${jname}`
-    [ $? -eq 0 ] && err 1 "No such jail ${jname}"
-    zfs snapshot ${ZPOOL}/${jname}@${snapname}
-}
-
-ufssnapshot_create()
-{
-    err 1 "UFS Not implemented"
-}
-
-rsyncsnapshot_create()
-{
-    err 1 "Rsync Not implemented"
-}
-
-zfssnapshot_destroy()
-{
-    [ -n "${1}" ] && snapname=$1
-    [ -z "${jname}" ] && err 1 "Empty jname"
-    [ -z "${snapname}" ] && err 1 "Empty snapname"
-    A=`cbsd jstatus jname=${jname}`
-    [ $? -eq 0 ] && err 1 "No such jail ${jname}"
-    zfs destroy ${ZPOOL}/${jname}@${snapname}
-}
-
-ufssnapshot_destroy()
-{
-    err 1 "UFS Not implemented"
-}
-
-rsyncsnapshot_destroy()
-{
-    err 1 "Rsync Not implemented"
-}
-
-
-zfssnapshot_rollback()
-{
-    [ -z "${jname}" ] && err 1 "Empty jname"
-    [ -z "${snapname}" ] && err 1 "Empty snapname"
-    A=`cbsd jstatus jname=${jname}`
-    [ $? -eq 0 ] && err 1 "No such jail ${jname}"
     zfs rollback -r ${ZPOOL}/${jname}@${snapname}
 }
 
-ufssnapshot_rollback()
+ufs_snapshot_rollback()
 {
-    err 1 "UFS Not implemented"
+    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
 }
 
-rsyncsnapshot_rollback()
+rsync_snapshot_rollback()
 {
-    err 1 "Rsync Not implemented"
+    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
 }
 
+#MAIN
 if [ -z "${snapfs}" ]; then
     if [ "$zfsfeat" = "1" ]; then
 	snapfs="zfs"
 	. $zfstool
-	ZPOOL=`/sbin/zfs get -Ho value name ${jaildatadir}`
-	[ -z "${ZPOOL}" ] && err 1 "Cant find working ZFS pool"
+	ZPOOL=$( /sbin/zfs get -Ho value name ${jaildatadir} 2>/dev/null)
+	[ -z "${ZPOOL}" ] && err 1 "${MAGENTA}Can't find ZFS pool on ${GREEN}${jaildatadir}${NORMAL}"
     else
 	snapfs="ufs"
     fi
 fi
 
-case "${mode}" in
-    "list") ${snapfs}snapshot_list ;;
-    "create") ${snapfs}snapshot_create ;;
-    "destroy") ${snapfs}snapshot_destroy ;;
-    "destroyall") ${snapfs}snapshot_destroyall ;;
-    "rollback") ${snapfs}snapshot_rollback ;;
-esac
+[ -z "${display}" ] && display="jname,snapname,creation"
 
+#remove commas for loop action on header
+mydisplay=$(echo ${display} |tr ',' '  ')
+
+# upper for header
+myheader=$(echo ${mydisplay} |tr '[:lower:]' '[:upper:]')
+
+[ -z "${header}" ] && header=1
+
+case "${mode}" in
+    "list")
+	${snapfs}_snapshot_list |column -t
+	;;
+    "create")
+	check_jname
+	${snapfs}_snapshot_create
+	;;
+    "destroy")
+	check_jname
+	${snapfs}_snapshot_destroy_by_snapname
+	;;
+    "destroyall")
+	check_jname
+	${snapfs}_snapshot_destroyall
+	;;
+    "rollback")
+	check_jname
+	${snapfs}_snapshot_rollback
+	;;
+esac
