tabs

diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -314,8 +314,8 @@ fi
 
 # Update Redis
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-        cbsdredis hset "jail:${jname}" node "${nodename}" status 1 || echo "WARNING: failed to update Redis!"
-        cbsdredis publish cbsd_events '{"cmd":"jstart", "node":"'${nodename}'", "jail":"'${jname}'", "status":1}'
+	cbsdredis hset "jail:${jname}" node "${nodename}" status 1 || echo "WARNING: failed to update Redis!"
+	cbsdredis publish cbsd_events '{"cmd":"jstart", "node":"'${nodename}'", "jail":"'${jname}'", "status":1}'
 fi
 
 # CBSD QUEUE
@@ -610,6 +610,12 @@ if [ ${ret} -ne 0 ]; then
 	exit 0
 fi
 
+# TODO/NOTES:
+# when path have no /var and/or /tmp (e.g empty fstab file), after jail start we have
+# undesirable/undesirable tmpfs! bug/issue ?
+# tmpfs on /usr/jails/jails/jail2/var (tmpfs, local)
+# tmpfs on /usr/jails/jails/jail2/tmp (tmpfs, local)
+
 ${DAEMON_CMD} -p ${ftmpdir}/jstart.${jname}.$$ /usr/bin/nice -n ${nice} /usr/sbin/jail -f ${ftmpdir}/${jname}.conf -c ${jname}
 trap "" HUP INT ABRT BUS TERM EXIT
 
@@ -713,7 +719,6 @@ if [ -x "${distmoduledir}/vncterm.d/cbsdvnc" ]; then
 	${ECHO} "${N1_COLOR}vncterm is installed, launch vncterm session...${N0_COLOR}"
 	${DAEMON_CMD} -f /usr/local/bin/cbsd vncterm jname=${jname} mode=run addr=127.0.0.1 >/dev/null 2>&1
 fi
-
 
 
 # CBSD QUEUE
