missed these files

diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -25,6 +25,8 @@ readconf jail-freebsd-default.conf
 # for external_exec-related command
 . ${distdir}/jcreate.subr
 
+my_name="jstart"
+
 # check environment scripts from tests dir
 # when error code != 0 - exit
 # $1 - is source dir name ( tests )
@@ -312,7 +314,8 @@ fi
 
 # Update Redis
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-        hset "jail:${jname}" node "${HOST}" state starting
+        cbsdredis hset "jail:${jname}" node "${nodename}" status 1 || echo "WARNING: failed to update Redis!"
+        cbsdredis publish cbsd_events '{"cmd":"jstart", "node":"'${nodename}'", "jail":"'${jname}'", "status":1}'
 fi
 
 # CBSD QUEUE
@@ -690,6 +693,13 @@ else
 	external_exec_master_script "master_poststop.d"
 	exec_poststop
 	jcleanup jname=${jname}
+
+	# redis
+	if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
+		cbasredis hset "jail:${jname}" status -1 || echo "WARNING: Failed to update Redis"
+		cbasredis hdel "jail:${jname}" jid || echo "WARNING: Failed to update Redis"
+        	cbsdredis publish cbsd_events '{"cmd":"jstart", "node":"'${nodename}'", "jail":"'${jname}'", "status":-1}'
+	fi
 fi
 
 cbsdsqlrw local UPDATE jails SET jid=${myjid},status=${status} where jname=\"${jname}\"
@@ -705,10 +715,6 @@ if [ -x "${distmoduledir}/vncterm.d/cbsdvnc" ]; then
 fi
 
 
-# redis
-if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-	hset "jail:${jname}" state running jid ${myjid} started ${st_time}
-fi
 
 # CBSD QUEUE
 if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
@@ -717,6 +723,11 @@ fi
 
 end_time=$( ${DATE_CMD} +%s )
 diff_time=$(( end_time - st_time ))
+# redis
+if [ ${myjid} -gt 0 -a "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
+	cbsdredis hset "jail:${jname}" status 2 jid ${myjid} started ${st_time} echo "WARNING: Failed to update Redis"
+        cbsdredis publish cbsd_events '{"cmd":"jstart", "node":"'${nodename}'", "jail":"'${jname}'", "status":0, "duration":'${diff_time}'}'
+fi
 diff_time=$( displaytime ${diff_time} )
 ${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
 cbsdlogger NOTICE ${CBSD_APP}: jail ${jname} started in ${diff_time}
diff --git a/sudoexec/jstop b/sudoexec/jstop
--- a/sudoexec/jstop
+++ b/sudoexec/jstop
@@ -34,7 +34,7 @@ else
 fi
 
 JLIST=
-
+my_name="jstop"
 # check for actual vm list in arg list
 jail_num=0
 for i in ${TMP_JLIST}; do
@@ -99,7 +99,8 @@ init_basedir
 
 # Update Redis
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-	hset "jail:${jname}" state stopping
+	cbsdredis hset "jail:${jname}" status 2 || echo "WARNING: failed to update Redis!"
+	cbsdredis publish cbsd_events '{"cmd":"jstop", "node":"'${nodename}'", "jail":"'${jname}'", "status":1}'
 fi
 
 
@@ -297,11 +298,6 @@ FID="/var/run/jail_${UNDhost_hostname}.id"
 /bin/rm -f ${ftmpdir}/${jname}.conf
 
 
-# Update Redis
-if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-	hset "jail:${jname}" state offline stopped ${st_time}
-	hdel "jail:${jname}" jid
-fi
 
 # CBSD QUEUE
 if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
@@ -310,6 +306,12 @@ fi
 
 end_time=$( ${DATE_CMD} +%s )
 diff_time=$(( end_time - st_time ))
+# Update Redis
+if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
+	cbsdredis hdel "jail:${jname}" jid
+	cbsdredis hset "jail:${jname}" status 0 || echo "WARNING: failed to update Redis!"
+	cbsdredis publish cbsd_events '{"cmd":"jstop", "node":"'${nodename}'", "jail":"'${jname}'", "status":0, "duration":'${diff_time}'}'
+fi
 diff_time=$( displaytime ${diff_time} )
 ${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
 cbsdlogger NOTICE ${CBSD_APP}: jail ${jname} stopped in ${diff_time}
