add kfreebsd profile

diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -59,6 +59,33 @@ external_exec_master_script()
 	done
 }
 
+# check environment scripts from tests dir
+# when error code != 0 - exit
+# $1 - is source dir name ( tests )
+check_environment_script()
+{
+	local _res
+	local _dir="${1}"
+	local _testfiles
+
+	[ -z "${_dir}" ] && return 1
+
+	local _srcdir="${jailsysdir}/${jname}/${_dir}"
+
+	[ ! -d "${_srcdir}" ] && return 0
+	[ -z "$( /bin/ls ${_srcdir}/ )" ] && return 0
+
+	_testfiles=$( /usr/bin/find "${_srcdir}" -type f -depth 1 -maxdepth 1 -exec /usr/bin/basename {} \; )
+
+	for _file in ${_testfiles}; do
+		${ECHO} "${MAGENTA}Check environment script: ${GREEN}${_file}${NORMAL}"
+		env jname=${jname} ${_srcdir}/${_file}
+		[ $? -ne 0 ] && err 1 "${MAGENTA}Error: ${GREEN}${_file}${NORMAL}"
+	done
+}
+
+
+
 exec_master_poststart()
 {
 	eval CMD=\${exec_master_poststart}
@@ -91,7 +118,6 @@ exec_master_prestart()
 	${ECHO} "${MAGENTA}${jname} master exec prestart: ${GREEN}${CMD}${NORMAL}"
 	${CMD}
 }
-
 
 exec_prestart()
 {
@@ -303,14 +329,14 @@ if [ -f "${jaillock}" ]; then
 		rm -f ${jaillock}
 	else
 		cur_time=$( /bin/date +%s )
-		eval $( stat -s ${jaillock} )
+		eval $( /usr/bin/stat -s ${jaillock} )
 		difftime=$(( ( cur_time - st_mtime ) / 60 ))
 
 		# 30 minutes outdated lock
 		if [ ${difftime} -gt 30 ]; then
 			${ECHO} "${MAGENTA}Jail ${GREEN}${jname}${MAGENTA} locked by ${GREEN}${masterhost}${MAGENTA} node${NORMAL}"
 			${ECHO} "${MAGENTA}But lock age is too old: ${difftime} min. Removing!!!${NORMAL}"
-			rm -f ${jaillock}
+			/bin/rm -f ${jaillock}
 		else
 			# still fresh
 			$ECHO "${MAGENTA}Jail ${GREEN}${jname}${MAGENTA} locked by ${GREEN}${masterhost}${MAGENTA} node, lock age: ${difftime} min.${NORMAL}"
@@ -334,8 +360,9 @@ init_target_arch
 init_basedir
 
 jcleanup jname=${jname}
-[ ! -d "${path}" ] && mkdir ${path}
+[ ! -d "${path}" ] && /bin/mkdir ${path}
 
+check_environment_script "tests"
 geniplist ${ip4_addr}
 
 if [ -n "${interface}" -a "${interface}" != "0" -a "${vnet}" -eq "0" ]; then
@@ -490,7 +517,7 @@ unset_changes_20140930
 set_changes_20140930
 
 ${ECHO} "${MAGENTA}Starting jail: ${GREEN}${jname}, parallel timeout=${parallel}${NORMAL}"
-TRAP="${TRAP} rm -f ${ftmpdir}/jstart.${jname}.$$;"
+TRAP="${TRAP} /bin/rm -f ${ftmpdir}/jstart.${jname}.$$;"
 trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 
 # check that the emulator is able to execute commands
@@ -516,7 +543,6 @@ sync
 exec_cbsdjail_first_boot
 
 external_exec_script "start.d"
-
 exec_master_poststart
 external_exec_master_script "master_poststart.d"
 exec_poststart
