vpc wip

diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -454,7 +454,7 @@ if [ "${vnet}" = "1" ]; then
 	done ) || err 1 "${N1_COLOR}jstart: error get interfaces name for vnet nic map${N0_COLOR}"
 
 	eth_seq=0
-	printf "${N1_COLOR}Create epair: "
+	printf "${N1_COLOR}create epair: "
 
 	for i in ${interfaces}; do
 
@@ -467,6 +467,27 @@ if [ "${vnet}" = "1" ]; then
 		[ "${nic_parent}" = "0" -o "${nic_parent}" = "auto" ] && nic_parent=$( getnics-by-ip ip=0.0.0.0 skip=bridge )
 
 		case "${nic_parent}" in
+			vpc-*)
+				VPC_ROOT_DIR="${dbdir}/vpc"
+				_arg_len=$( strlen ${nic_parent} )
+				vpc_name=$( substr --pos=5 --len=${_arg_len} --str="${nic_parent}" )
+				_dbpath="${VPC_ROOT_DIR}/${vpc_name}.sqlite"
+				[ ! -r ${_dbpath} ] && err 1 "${N1_COLOR}VPC not exist: ${N2_COLOR}${_dbpath}${N0_COLOR}"
+
+				mybridge=
+				if ! mybridge=$( get_my_device vpc vpc-${vpc_name} ); then
+					err 1 "${N1_COLOR}${CBSD_APP} failed to get VPC bridge: ${mybridge}${N0_COLOR}"
+				fi
+
+				${IFCONFIG_CMD} ${mybridge} > /dev/null 2>&1
+				_ret=$?
+				if [ ${_ret} -ne 0 ]; then
+					err 1 "${N1_COLOR}no such bridge interface: ${N2_COLOR}${mybridge}${N0_COLOR}"
+				fi
+				;;
+			bridge*)
+				mybridge="${nic_parent}"
+				;;
 			cbsdvale*)
 				mybridge="${nic_parent}"
 				;;
@@ -505,7 +526,6 @@ if [ "${vnet}" = "1" ]; then
 				${distdir}/tools/vale-ctl -h vale${valeid}:${myepair}a
 		esac
 
-
 		printf "${H3_COLOR}${myepair}:${N2_COLOR}${nic_parent} "
 		${IFCONFIG_CMD} ${myepair}a description ${jname}-eth${eth_seq} up
 		eth_seq=$(( eth_seq + 1 ))
@@ -525,7 +545,6 @@ if [ "${vnet}" = "1" ]; then
 	done
 
 	${ECHO} "${N0_COLOR}"
-
 fi	# vnet -eq 1
 
 #test for zfs mounted & mount if not
