when mount_ports=1 mount ports tree in RO and personal distfiles from jail tmp dir in RW above: Pointed: k at free.de; Unlink BFS patches due to maintainer no longer supports/use it; allow.mount.fdescfs added; update kmem patches according to https://svnweb.freebsd.org/base?view=revision&revision=r277855

diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -273,10 +273,10 @@ if [ $# -gt 1 -a -z "${jname}" ]; then
 		/usr/sbin/daemon -p ${ftmpdir}/jstart.${jname}.$$ /usr/local/bin/cbsd jstart inter=0 jname=${jname}
 		#lets save .pid file
 		sleep 1
-		[ -f "${ftmpdir}/jstart.${jname}.$$" ] && cbsd_pwait --pid=$( cat ${ftmpdir}/jstart.${jname}.$$ ) --timeout=${parallel}
+		[ -f "${ftmpdir}/jstart.${jname}.$$" ] && cbsd_pwait --pid=$( /bin/cat ${ftmpdir}/jstart.${jname}.$$ ) --timeout=${parallel}
 	done
 
-	wait_for_jstart ${parallel}
+	wait_for_fpid start ${parallel}
 
 	err 0 "${MAGENTA}Multiple jstart: ${GREEN}done${NORMAL}"
 fi
@@ -311,7 +311,7 @@ TRAP=""
 #Check for shared lock
 jaillock="${jailsysdir}/${jname}/locked"
 if [ -f "${jaillock}" ]; then
-	masterhost=$( cat ${jaillock} )
+	masterhost=$( /bin/cat ${jaillock} )
 	if [ "${masterhost}" = "${nodename}" ]; then
 		${ECHO} "${MAGENTA}Remove my stale lock file: ${GREEN}${jaillock}${NORMAL}"
 		rm -f ${jaillock}
@@ -355,11 +355,11 @@ geniplist ${ip4_addr}
 if [ -n "${interface}" -a "${interface}" != "0" -a "${vnet}" -eq "0" ]; then
 	### CHECK FOR IP ####
 	for ips in ${IPS}; do
-		ipwmask "${ips}"
+		iptype "${ips}" ||true
 		[ -z "${IWM}" ] && continue
 		#prevent to use nodeip
 		[ "${IWM}" = "${nodeip}" ] && err 1 "${MAGENTA}Error: Jail can not take nodeip when interface is not equal 0: ${GREEN}${nodeip}${NORMAL}"
-		cbsd checkip ip=${IWM} check=1
+		checkip ip=${IWM} check=1
 		IPUSE=$?
 		case ${IPUSE} in
 			0)
@@ -381,7 +381,7 @@ if [ "$vnet" = "1" ]; then
 	[ "${interface}" = "0" -o "${interface}" = "auto" ] && interface=$( cbsd getnics-by-ip ip=0.0.0.0 )
 
 	if ! mybridge=$( get_my_device bridge ${interface} ); then
-	    err 1 "${MAGENTA}Error: Cant get_my_device for ${interface}: ${mybridge}${NORMAL}"
+		err 1 "${MAGENTA}Error: Cant get_my_device for ${interface}: ${mybridge}${NORMAL}"
 	fi
 	myepair=$( get_my_epair ${mybridge} )
 	[ $? -eq 1 ] && err 1 "${MAGENTA}Error: Cant get_my_epair by: ${GREEN}${mybridge}${NORMAL}"
@@ -396,14 +396,14 @@ case $zfsfeat in
 	1)
 		. $zfstool
 		zfsmnt ${data}
-		[ $? -eq 2 ] && zfs mount "${ZPOOL}"
+		[ $? -eq 2 ] && /sbin/zfs mount "${ZPOOL}"
 	;;
 esac
 
 if [ $baserw -eq 1 ]; then
 	path=$data
 	[ ! -f "${path}/bin/sh" ] && switch_baserw ${path} 1
-	[ -f ${mount_fstab} ] && rm -f ${mount_fstab}
+	[ -f ${mount_fstab} ] && /bin/rm -f ${mount_fstab}
 fi
 
 if [ $baserw -eq 0 -a ! -f "${mount_fstab}" ]; then
@@ -446,8 +446,7 @@ if [ "$mount_kernel" = "1" ]; then
 fi
 
 if [ "$mount_ports" = "1" ]; then
-	SRCDIR="/usr/ports"
-	MOUNTOPT="${MOUNTOPT} -p ${SRCDIR}"
+	MOUNTOPT="${MOUNTOPT} -p /usr/ports -d ${data}/tmp/distfiles"
 fi
 
 [ "${ver}" != "empty" ] && mountbase -v ${ver} -a ${arch} ${MOUNTOPT}
@@ -477,7 +476,7 @@ fi
 
 [ "${osname}" = "freebsd" ] && is_freebsd=1
 
-    # check for freshed version of the base via elf from /bin/sh
+# check for freshed version of the base via elf from /bin/sh
 if [ ${is_freebsd} -eq 1 -a ${baserw} -eq 1 ]; then
 	if [ -n ${BASE_DIR} -a -f "${BASE_DIR}/bin/sh" ]; then
 		baseelf=$( ${miscdir}/elf_tables --ver ${BASE_DIR}/bin/sh 2>/dev/null )
@@ -503,7 +502,6 @@ jrctl jname=$jname mode=set
 unset_changes_20140930
 set_changes_20140930
 
-
 ${ECHO} "${MAGENTA}Starting jail: ${GREEN}${jname}, parallel timeout=${parallel}${NORMAL}"
 TRAP="${TRAP} rm -f ${ftmpdir}/jstart.${jname}.$$;"
 trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
@@ -520,7 +518,7 @@ fi
 /usr/sbin/daemon -p ${ftmpdir}/jstart.${jname}.$$ /usr/bin/nice -n ${nice} /usr/sbin/jail -f ${ftmpdir}/${jname}.conf -c ${jname}
 
 trap "" HUP INT ABRT BUS TERM EXIT
-[ -f "${ftmpdir}/jstart.${jname}.$$" ] && cbsd_pwait --pid=$( cat ${ftmpdir}/jstart.${jname}.$$ ) --timeout=${parallel}
+[ -f "${ftmpdir}/jstart.${jname}.$$" ] && cbsd_pwait --pid=$( /bin/cat ${ftmpdir}/jstart.${jname}.$$ ) --timeout=${parallel}
 
 # make id file
 UNDHOSTNAME=$( echo ${hostname} |tr  "." "_" )
diff --git a/tools/detachzfs b/tools/detachzfs
--- a/tools/detachzfs
+++ b/tools/detachzfs
@@ -20,59 +20,58 @@ init $*
 
 zfs_check_and_deattach()
 {
-    local _err
-    zfsfs ${1}
+	local _err
+	zfsfs ${1}
 
-    _err=$?
+	_err=$?
 
-    case "${_err}" in
-	0)
-	    return 0
-	    ;;
-	1)
-	    zfs unmount -f ${1}
-	    ;;
-	2)
-	    ;;
-	*)
-	    return 0
-    esac
+	case "${_err}" in
+		0)
+			return 0
+			;;
+		1)
+			/sbin/zfs unmount -f ${1}
+			;;
+		2)
+			;;
+		*)
+			return 0
+	esac
 
-    # no we ready for dettaching $zfs from $jname
-    zfs set jailed=off ${1}
-    zfs unjail ${jname} ${1}
+	# no we ready for dettaching $zfs from $jname
+	/sbin/zfs set jailed=off ${1}
+	/sbin/zfs unjail ${jname} ${1}
 
-    return 2
+	return 2
 }
 
 
 mount_via_fstab()
 {
-    cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
-	    case ":${_device}" in
-        	:#* | :)
-                continue
-                ;;
-    	    esac
+	/bin/cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
+		case ":${_device}" in
+			:#* | :)
+				continue
+				;;
+		esac
 
-	[ "${_fs}" != "zfs" -o -z "${_device}" ] && continue
-	zfs_check_and_deattach ${_device}
-	case $? in
-	    0)
-    		${ECHO} "${MAGENTA}attachzfs: ${_device} is not valid ZFS filesystem${NORMAL}"
-		return 0
-    		;;
-	    2)
-    		;;
-	    *)
-    		${ECHO} "${MAGENTA}attachzfs: Unknown error while test for zfsfs ${_device}. Skip${NORMAL}"
-		return 0
-    		;;
-	esac
-    done
+		[ "${_fs}" != "zfs" -o -z "${_device}" ] && continue
+		zfs_check_and_deattach ${_device}
+		case $? in
+			0)
+				${ECHO} "${MAGENTA}attachzfs: ${_device} is not valid ZFS filesystem${NORMAL}"
+				return 0
+				;;
+			2)
+				;;
+			*)
+				${ECHO} "${MAGENTA}attachzfs: Unknown error while test for zfsfs ${_device}. Skip${NORMAL}"
+				return 0
+				;;
+		esac
+	done
 
-    #exit now
-    exit
+	exit 0
 }
 
 . ${jrcconf}
@@ -84,12 +83,12 @@ mount_via_fstab()
 
 zfs_check_and_deattach ${zfs}
 case $? in
-    0)	
-	err 1 "${MAGENTA}attachzfs: $zfs is not valid ZFS filesystem${NORMAL}"
-	;;
-    2)	
-	;;
-    *)	
-	err 1 "${MAGENTA}attachzfs: Unknown error while test for zfsfs ${zfs}. Skip${NORMAL}"
-	;;
+	0)
+		err 1 "${MAGENTA}attachzfs: $zfs is not valid ZFS filesystem${NORMAL}"
+		;;
+	2)
+		;;
+	*)	
+		err 1 "${MAGENTA}attachzfs: Unknown error while test for zfsfs ${zfs}. Skip${NORMAL}"
+		;;
 esac
diff --git a/tools/makejconf b/tools/makejconf
--- a/tools/makejconf
+++ b/tools/makejconf
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v10.1.0
+#v10.1.4
 globalconf="${workdir}/cbsd.conf";
 MYARG="jname out"
 MYOPTARG="ip6wa epair fbsd"
@@ -27,14 +27,32 @@ mkjhosts()
 	for i in $( /usr/bin/egrep "[:blank:]*${host_hostname}" ${JHOST} |/usr/bin/awk '/^;/{print $1"\n"}' ); do
 		if [ "$i" != "${IP}" ]; then
 			TMPH="${ftmpdir}/hosts.$$"
-			cp ${JHOST} ${TMPH}
-			grep -v "[:blank:]*${host_hostname}" ${TMPH} > ${JHOST}
-			rm -f ${TMPH}
+			/bin/cp ${JHOST} ${TMPH}
+			/usr/bin/grep -v "[:blank:]*${host_hostname}" ${TMPH} > ${JHOST}
+			/bin/rm -f ${TMPH}
 		fi
 	done
 
-	[ $( grep -c ^${IP} ${JHOST} ) = "0" ] && echo ${IP} ${host_hostname} >> ${JHOST}
+	[ $( /usr/bin/grep -c ^${IP} ${JHOST} ) = "0" ] && echo ${IP} ${host_hostname} >> ${JHOST}
 }
+
+# fill $interface variable by physical NIC
+get_iface_by_ip()
+{
+	local ip
+
+	if [ -n "${1}" ]; then
+		ip="${1}"
+	else
+		ip="0.0.0.0"
+	fi
+
+	# autodetect correct interface
+	if [ "${interface}" = "auto" ]; then
+		interface=$( getnics-by-ip ip=${ip} )
+	fi
+}
+
 
 # MAIN
 readconf jail-freebsd-default.conf
@@ -43,11 +61,9 @@ JAILRCCONF="${ftmpdir}/rc.conf_${jname}"
 jmkrcconf jname=${jname} > ${JAILRCCONF}
 . ${JAILRCCONF}
 init_jail_path
-rm -f ${JAILRCCONF}
+/bin/rm -f ${JAILRCCONF}
 
 [ ${vnet} -eq 1 -a -z "${epair}" ] && err 1 "${MAGENTA}Error: Jail is ${GREEN}vnet${NORMAL}-feature enabled, but epair is not set.${NORMAL}"
-
-eval multiips4=\"\$ip4_addr\"
 
 [ $baserw -eq 1 ] && path=$data
 
@@ -119,51 +135,56 @@ EOF
 
 ALIAS4=""
 ALIAS6=""
-ips=$( echo ${multiips4}|tr "," " " )
 
-# autodetect correct interface
-if [ -n "${interface}" ]; then
-	if [ "${interface}" = "auto" ]; then
-		if [ -n "${ip4_addr}" ]; then
-			ip=$( echo ${ip4_addr}|/usr/bin/awk '{printf $1}' )
-			interface=$( getnics-by-ip ip=${ip} )
-		else
-			interface=$( getnics-by-ip ip=0.0.0.0 )
-		fi
-	fi
-	echo "interface=\"${interface}\";" >> $out
-fi
-
+# gen ipX.addr params
 if [ ${vnet} -eq 0 ]; then
 	# when vnet we not need ipX.addr
-	for a in ${ips}; do
+	OLDIFS="${IFS}"
+	IFS=","
+	for a in ${ip4_addr}; do
+		unset IWM VHID
 		iptype $a
 		_inet=$?
 		[ ${_inet} -eq 0 ] && continue
 
-		ipwmask ${a}
+		# this is carp records
+		if [ -n "${VHID}" ]; then
+#			a=$( carpcfg inter=0 mode=show vhid=${VHID} ip=${IPWVHID} )
+			a=$( carpcfg inter=0 mode=show vhid=${VHID} ip=${IWM} )
+			_res=$?
+			if [ ${_res} -ne 0 ]; then
+				err 1 "${MAGENTA}Error in CARP area from makejconf: ${a}${NORMAL}"
+				continue
+			fi
+		else
+			if [ -n "${interface}" ]; then
+				get_iface_by_ip ${IWM}
+				a="${interface}|${a}"
+			fi
+		fi
 
 		case ${_inet} in
-		1)
-			if [ -z "$ALIAS4" ]; then
-				echo "ip4.addr = ${a};" >> ${out}
-				[ "${mkhostsfile}" != "0" ] && mkjhosts ${IWM} ${data}/etc/hosts
-				ALIAS4="1"
-			else
-				[ "${mkhostsfile}" != "0" ] && mkjhosts ${IWM} ${data}/etc/hosts
-				echo "ip4.addr += ${a};" >> ${out}
-			fi
-		;;
-		2)
-			if [ -z "$ALIAS6" ]; then
-				echo "ip6.addr = ${a};" >> ${out}
-				ALIAS6="1"
-			else
-				echo "ip6.addr += ${a};" >> ${out}
-			fi
-		;;
+			1)
+				if [ -z "$ALIAS4" ]; then
+					echo "ip4.addr = \"${a}\";" >> ${out}
+					[ "${mkhostsfile}" != "0" ] && mkjhosts ${IWM} ${data}/etc/hosts
+					ALIAS4="1"
+				else
+					[ "${mkhostsfile}" != "0" ] && mkjhosts ${IWM} ${data}/etc/hosts
+					echo "ip4.addr += \"${a}\";" >> ${out}
+				fi
+				;;
+			2)
+				if [ -z "$ALIAS6" ]; then
+					echo "ip6.addr = \"${a}\";" >> ${out}
+					ALIAS6="1"
+				else
+					echo "ip6.addr += \"${a}\";" >> ${out}
+				fi
+				;;
 		esac
 	done
+	IFS="${OLDIFS}"
 else
 	# vnet
 	cat >> ${out} <<EOF
@@ -188,6 +209,14 @@ fi
 
 if [ "${allow_nullfs}" = "1" ]; then
 	echo "allow.mount.nullfs = \"true\";" >> ${out}
+fi
+
+# this feature available for FreeBSD 10.2+
+_res=$( /sbin/sysctl -q security.jail.mount_fdescfs_allowed >/dev/null 2>&1 )
+if [ $? -ne 1 ]; then
+	if [ "${allow_fdescfs}" = "1" ]; then
+		echo "allow.mount.fdescfs = \"true\";" >> ${out}
+	fi
 fi
 
 if [ "${allow_devfs}" = "1" ]; then
