initial native ZFS encryption support: passphrase method
method 1: per jail entirely dataset with passphrase (interactive)
todo:
  - partial per-mount point encryption + passhrase
+ keyfile ( PXE, sshfs, NFS )
  - geli-like method to encrypt keyfile datasets

feature request: #583

diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -433,7 +433,7 @@ done
 IFS="${OIFS}"
 
 if [ ${_mod} -eq 1 ]; then
-	jset jname=${jname} ip4_addr="${_tmp_ip4_addr}"
+	jset ip4_addr="${_tmp_ip4_addr}"
 	ip4_addr="${_tmp_ip4_addr}"
 fi
 
@@ -579,7 +579,25 @@ case ${zfsfeat} in
 	1)
 		. ${zfstool}
 		zfsmnt ${data}
-		[ $? -eq 2 ] && ${ZFS_CMD} mount "${ZPOOL}"
+		if [ $? -eq 2 ]; then
+			# ZFS encryption?
+			zfs_encryption_val=$( ${ZFS_CMD} get -Ho value encryption ${ZPOOL} 2>/dev/null )
+			if [ -n "${zfs_encryption_val}" -a "${zfs_encryption_val}" != "off" ]; then
+				${ECHO} "${N1_COLOR}${CBSD_APP}: encrypted dataset: ${N2_COLOR}${zfs_encryption_val}${N0_COLOR}"
+				zfs_encryption_keyformat=$( ${ZFS_CMD} get -Ho value keyformat ${ZPOOL} 2>/dev/null )
+				${ECHO} "${N1_COLOR}${CBSD_APP}: encryption keyformat: ${N2_COLOR}${zfs_encryption_keyformat}${N0_COLOR}"
+				if [ "${zfs_encryption_keyformat}" = "passphrase" ]; then
+					if [ -n "${NOINTER}" -o "${inter}" = "1" ]; then
+						err 0 "${N1_COLOR}${CBSD_APP} keyformat is passphrase, skipp for non-interactive mode${N0_COLOR}"
+					else
+						${ZFS_CMD} load-key ${ZPOOL}
+						# 255 code valid here, already loaded
+					fi
+				fi
+			fi
+			${ZFS_CMD} mount "${ZPOOL}"
+			is_mounted ${data} || err 1 "${N1_COLOR}${CBSD_APP}: unable to mount zfs pool: ${N2_COLOR}${ZPOOL} -> ${data}${N0_COLOR}"
+		fi
 	;;
 esac
 
@@ -862,7 +880,7 @@ fi
 cbsdsqlrw local UPDATE jails SET jid=${myjid},status=${status} where jname=\"${jname}\"
 ${RM_CMD} -f ${ftmpdir}/${jname}.conf
 fwcounter
-expose jname=${jname} mode=apply
+expose mode=apply
 [ ${myjid} -gt 0 -a ${cpuset} != "0" ] && ${CPUSET_CMD} -c -l ${cpuset} -j ${myjid}
 
 # VNC auto start
diff --git a/tools/geli b/tools/geli
--- a/tools/geli
+++ b/tools/geli
@@ -1,13 +1,15 @@
 #!/usr/local/bin/cbsd
 #v11.1.12
 MYARG="mode"
-MYOPTARG="key backupfile device file"
+MYOPTARG="backupfile device file key"
 MYDESC="cbsd geli helper"
-ADDHELP="key= path to master key file\n\
-device= path to device\n\
-file= path to image\n\
-mode= initmaster, init, attach, detach, info\n\
-backupfile= alternative path to backup for init for storing backup\n"
+ADDHELP="\
+ backupfile= alternative path to backup for init for storing backup\n\
+ device= path to device\n\
+ file= path to image\n\
+ key= path to master key file\n\
+ mode= initmaster, init, attach, detach, info\n\
+"
 EXTHELP="wf_geli"
 
 . ${subr}
@@ -25,7 +27,7 @@ TRAP=""
 change_passphrase()
 {
 	local _passfile _dev _pw="1" _npw
-	local oldmodes=$( /bin/stty -g )
+	local oldmodes=$( ${STTY_CMD} -g )
 
 	[ -z "${1}" -o -z "${2}" ] && err 1 "${N1_COLOR}change_passphrase need for arguments${N0_COLOR}"
 	_dev="${1}"
@@ -35,7 +37,7 @@ change_passphrase()
 
 	while [ "${_pw}" != "${_npw}" ]; do
 		printf "${BOLD}New Password: ${N0_COLOR}"
-		/bin/stty -echo
+		${STTY_CMD} -echo
 		read _pw
 		printf "\n${BOLD}Retype New Password: ${N0_COLOR}"
 		read _npw
@@ -43,8 +45,8 @@ change_passphrase()
 	done
 
 	echo "${_pw}" > ${_passfile}
-	/bin/stty $oldmodes
-	/sbin/geli init -J ${_passfile} ${_dev}
+	${STTY_CMD} $oldmodes
+	${GELI_CMD} init -J ${_passfile} ${_dev}
 }
 
 # $1 - path to dev/file
@@ -54,7 +56,7 @@ get_key()
 	local _res _md5
 	[ -z "${1}" ] && err 1 "${N1_COLOR}get_key need for arguments${N0_COLOR}"
 	_res=$( echo $1 | ${SED_CMD} s:^${workdir}/::g )
-	_md5=$( /sbin/md5 -qs "${_res}" )
+	_md5=$( ${MD5_SUM} -qs "${_res}" )
 	printf "${gelidir}/${_md5}"
 }
 
@@ -73,16 +75,16 @@ create_key()
 		if [ -n "${_res}" ]; then
 			_md="${_res}"
 		else
-			_md=$( /sbin/mdconfig -a -t vnode -f ${file} )
-			[ $? -ne 0 ] && err 1 "${N1_COLOR}Error for: ${N2_COLOR}mdconfig -a -t vnode -f ${file}${N0_COLOR}"
-			TRAP="${TRAP} /sbin/mdconfig -d -u ${_md};"
+			_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${file} )
+			[ $? -ne 0 ] && err 1 "${N1_COLOR}Error for: ${N2_COLOR}${MDCONFIG_CMD} -a -t vnode -f ${file}${N0_COLOR}"
+			TRAP="${TRAP} ${MDCONFIG_CMD} -d -u ${_md};"
 			trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 		fi
 		_dev="/dev/${_md}"
 		#remove workdir part in path if exist
-		_keypath=$(get_key "${1}")
+		_keypath=$( get_key "${1}" )
 	else
-		_keypath=$(get_key "${_dev}")
+		_keypath=$( get_key "${_dev}" )
 	fi
 
 	if [ ! -r "${_keypath}" ]; then
@@ -113,10 +115,10 @@ init_device()
 	if [ -n "${backupfile}" ]; then
 		_arg="${_arg} -B ${backupfile}"
 		_tst=$( dirname ${backupfile} )
-		[ ! -d "${_tst}" ] && mkdir -p ${_tst}
+		[ ! -d "${_tst}" ] && ${MKDIR_CMD} -p ${_tst}
 	fi
 
-	_res=$( /sbin/geli init ${_arg} ${_device} 2>&1)
+	_res=$( ${GELI_CMD} init ${_arg} ${_device} 2>&1)
 
 	printf "${N0_COLOR}"
 	[ $? -ne 0 ] && err 1 "${N1_COLOR}error: ${N0_COLOR}${_res}"
@@ -134,7 +136,7 @@ attach_file()
 		if [ -n "${_res}" ]; then
 			_md="${_res}"
 		else
-			_md=$( mdconfig -a -t vnode -f ${file} )
+			_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${file} )
 		fi
 	fi
 
@@ -156,8 +158,8 @@ info_file()
 	if [ -n "${_res}" ]; then
 		_md="${_res}"
 	else
-		_md=$( mdconfig -a -t vnode -f ${file} )
-		trap "/sbin/mdconfig -d -u ${_md}" HUP INT ABRT BUS TERM EXIT
+		_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${file} )
+		trap "${MDCONFIG_CMD} -d -u ${_md}" HUP INT ABRT BUS TERM EXIT
 	fi
 
 	info_device /dev/${_md}
@@ -181,8 +183,8 @@ init_file()
 	if [ -n "${_res}" ]; then
 		_md="${_res}"
 	else
-		_md=$( /sbin/mdconfig -a -t vnode -f ${_file} )
-		trap "/sbin/mdconfig -d -u ${_md}" HUP INT ABRT BUS TERM EXIT
+		_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${_file} )
+		trap "${MDCONFIG_CMD} -d -u ${_md}" HUP INT ABRT BUS TERM EXIT
 	fi
 
 	if [ -c "${_md}.eli" ]; then
@@ -209,7 +211,7 @@ mdattach_file()
 	if [ -n "${_res}" ]; then
 		_md="${_res}"
 	else
-		_md=$( /sbin/mdconfig -a -t vnode -f ${_file} )
+		_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${_file} )
 	fi
 
 	echo ${_md}
@@ -227,7 +229,7 @@ detach_file()
 	if [ -n "${_res}" ]; then
 		_md="${_res}"
 	else
-		_md=$( /sbin/mdconfig -a -t vnode -f ${file} )
+		_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${file} )
 	fi
 
 	detach_device /dev/${_md}
@@ -248,7 +250,7 @@ attach_device()
 		err 0 "${N2_COLOR}${_device}.eli${N0_COLOR}"
 	fi
 	printf "${BOLD}"
-	_res=$( /sbin/geli attach -j ${_keyfile} ${_device} 2>&1)
+	_res=$( ${GELI_CMD} attach -j ${_keyfile} ${_device} 2>&1)
 	[ $? -ne 0 ] && err 1 "${N1_COLOR}error: ${N0_COLOR}${_res}"
 	printf "${N0_COLOR}"
 	[ -c "${device}.eli" ] && err 0 "${device}.eli"
@@ -280,7 +282,7 @@ detach_device()
 		_device="${device}"
 	fi
 	[ ! -c "${_device}.eli" ] && err 0 "${N1_COLOR}geli: ${N1_COLOR}Device not attached: ${N2_COLOR}${_device}.eli${N0_COLOR}"
-	_res=$( /sbin/geli detach ${_device}.eli 2>&1)
+	_res=$( ${GELI_CMD} detach ${_device}.eli 2>&1)
 	[ $? -ne 0 ] && err 1 "${N1_COLOR}error: ${N0_COLOR}${_res}"
 }
 
@@ -300,7 +302,7 @@ initmaster_attach_file()
 	[ -z "${1}" ] && return 1
 
 	${ECHO} "${N1_COLOR}Attaching geli base image. Please use master password.${N0_COLOR}"
-	_res=$( /sbin/geli attach ${1} 2>&1 )
+	_res=$( ${GELI_CMD} attach ${1} 2>&1 )
 	[ ! -c "${1}.eli" ] && err 1 "${N1_COLOR}Not attached: ${_res}${N0_COLOR}"
 }
 
@@ -310,27 +312,27 @@ initmaster_file()
 	local _md _res
 
 	[ -f "${MASTER_FILE}" ] && return 0
-	TRAP="rm -f ${MASTER_FILE};"
+	TRAP="${RM_CMD} -f ${MASTER_FILE};"
 	trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
-	truncate -s ${master_size} ${MASTER_FILE}
+	${TRUNCATE_CMD} -s ${master_size} ${MASTER_FILE}
 	chmod 0600 ${MASTER_FILE}
-	_md=$( mdconfig -a -t vnode -f ${MASTER_FILE} )
-	TRAP="mdconfig -d -u ${_md}; ${TRAP}"
+	_md=$( ${MDCONFIG_CMD} -a -t vnode -f ${MASTER_FILE} )
+	TRAP="${MDCONFIG_CMD} -d -u ${_md}; ${TRAP}"
 	trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 	$ECHO "${BOLD}Initialization. Please set master password for geli base image${N0_COLOR}"
-	_res=$( /sbin/geli init -s 4096 /dev/${_md} 2>&1 )
+	_res=$( ${GELI_CMD} init -s 4096 /dev/${_md} 2>&1 )
 
 	initmaster_attach_file /dev/${_md}
 
-	TRAP="/sbin/geli detach /dev/${_md}.eli; ${TRAP}"
+	TRAP="${GELI_CMD} detach /dev/${_md}.eli; ${TRAP}"
 	trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 	# now create filesystem on the image
-	dd if=/dev/random of=/dev/${_md}.eli bs=128k >/dev/null 2>&1 || true  ## << short write on character device exit with 1 err
-	/sbin/newfs -U -m0 -n /dev/${_md}.eli >/dev/null 2>&1
+	${DD_CMD} if=/dev/random of=/dev/${_md}.eli bs=128k >/dev/null 2>&1 || true  ## << short write on character device exit with 1 err
+	${NEWFS_CMD} -U -m0 -n /dev/${_md}.eli >/dev/null 2>&1
 	trap "" HUP INT ABRT BUS TERM EXIT
 	#    # detach
-	#    /sbin/geli detach /dev/${_md}.eli
-	#    mdconfig -d -u ${_md}
+	#    ${GELI_CMD} detach /dev/${_md}.eli
+	#    ${MDCONFIG_CMD} -d -u ${_md}
 	${ECHO} "${N1_COLOR}Init complete: ${N2_COLOR}${MASTER_FILE}${N0_COLOR}"
 }
 
@@ -356,29 +358,28 @@ mountmaster_file()
 		_res=$( ${MKTEMP_CMD} -q ${gelidir}/XXXXX )
 		if [ $? -eq 0 ]; then
 			_mounted="rw"
-			/bin/rm -f ${_res}
+			${RM_CMD} -f ${_res}
 		else
 			_mounted="ro"
 		fi
 		[ "${_mounted}" = "${_mode}" ] && return 0
 		# we need for re-mount in new mode
-		umount ${gelidir}
+		${UMOUNT_CMD} ${gelidir}
 	fi
 
 	[ ! -c "/dev/${_md}.eli" ] &&  initmaster_attach_file /dev/${_md}
 
 	if [ ! -c "/dev/${_md}.eli" ]; then
-		/sbin/mdconfig -d -u ${_md}
+		${MDCONFIG_CMD} -d -u ${_md}
 		err 1 "${N1_COLOR}No eli initialized for ${N2_COLOR}${MASTER_FILE}${N0_COLOR}"
 	fi
 
-	mount -o${_mode} /dev/${_md}.eli ${gelidir}
+	${MOUNT} -o${_mode} /dev/${_md}.eli ${gelidir}
 }
 
 
-
 # MAIN
-[ ! -d "${gelidir}" ] && mkdir -m 0600 ${gelidir}
+[ ! -d "${gelidir}" ] && ${MKDIR_CMD} -m 0600 ${gelidir}
 
 case "${mode}" in
 	"init")
@@ -434,3 +435,5 @@ case "${mode}" in
 		err 1 "${N1_COLOR}Unknown mode${N0_COLOR}"
 		;;
 esac
+
+exit 0
