migrate to cixinit, style

diff --git a/sudoexec/junregister b/sudoexec/junregister
--- a/sudoexec/junregister
+++ b/sudoexec/junregister
@@ -1,7 +1,7 @@
 #!/usr/local/bin/cbsd
 #v12.0.6
-MYARG="jname"
-MYOPTARG="dbfile rcfile"
+CIXARG="jname"
+CIXOPTARG="dbfile destroy rcfile"
 MYDESC="Unregister environments and dump settings from DB to ASCII/text config file"
 CBSDMODULE="jail"
 ADDHELP="
@@ -33,10 +33,10 @@ ${H3_COLOR}See also${N0_COLOR}:
 "
 
 . ${subrdir}/nc.subr
-
-. ${cbsdinit}
-
+. ${tools}
+cixinit
 . ${subrdir}/env_register.subr
+[ -z "${destroy}" ] && destroy=0
 
 emulator="jail" # for jname_is_multiple
 jail_list=
@@ -46,7 +46,7 @@ jname_is_multiple
 # -o uniq_name_of_the_task (one world)
 junregister_multi_init()
 {
-	local _jname
+	local _jname=
 
 	while getopts "c:n:o:" opt; do
 		case "${opt}" in
@@ -88,10 +88,7 @@ if [ -n "${jail_list}" ]; then
 	_args=
 
 	# trim for jname= in "$*"
-	for i in $*; do
-		prefix=
-		prefix6=$( substr --pos=0 --len=6 --str="${i}" )
-		[ "${prefix6}" = "jname=" ] && continue
+	for i in ${CIX_OTHER_ARGS}; do
 		if [ -n "${_args}" ]; then
 			_args="${_args} ${i}"
 		else
@@ -103,7 +100,6 @@ if [ -n "${jail_list}" ]; then
 	junregister_multi_init -c "${_args}" -o ${task_owner} -n "junregister"
 	err 0 "${N1_COLOR}Multiple junregister: ${N2_COLOR}done${N0_COLOR}"
 fi
-
 
 ret=0
 . ${subrdir}/rcconf.subr
@@ -135,29 +131,31 @@ else
 	JAILRCCONF="${rcfile}"
 fi
 
-CONF_DIR=$( ${DIRNAME_CMD} ${JAILRCCONF} )
-[ ! -d "${CONF_DIR}" ] && ${MKDIR_CMD} -m 0755 -p ${CONF_DIR}
-[ ! -d "${CONF_DIR}" ] && err 1 "${N1_COLOR}no such dir: ${N2_COLOR}${CONF_DIR}${N0_COLOR}"
+if [ ${destroy} -ne 1 ]; then
+	CONF_DIR=$( ${DIRNAME_CMD} ${JAILRCCONF} )
+	[ ! -d "${CONF_DIR}" ] && ${MKDIR_CMD} -m 0755 -p ${CONF_DIR}
+	[ ! -d "${CONF_DIR}" ] && err 1 "${N1_COLOR}no such dir: ${N2_COLOR}${CONF_DIR}${N0_COLOR}"
 
-jmkrcconf jname=${jname} > ${JAILRCCONF}
-res=$( replacewdir file0="${JAILRCCONF}" old=${workdir} new="CBSDROOT" )
-_ret=$?
-
-if [ ${_ret} -ne 0 ]; then
-	${RM_CMD} -f ${JAILRCCONF}
-	err 1 "${N1_COLOR}Error replacewdir for ${JAILRCCONF}: ${res}${N0_COLOR}"
-fi
-
-if [ -r ${mount_fstab} ]; then
-	res=$( replacewdir file0="${mount_fstab}" old=${workdir} new="CBSDROOT" )
+	jmkrcconf jname=${jname} > ${JAILRCCONF}
+	res=$( replacewdir file0="${JAILRCCONF}" old=${workdir} new="CBSDROOT" )
 	_ret=$?
-	[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error replacewdir for ${mount_fstab}: ${res}${N0_COLOR}"
-fi
 
-if [ -r {mount_fstab}.local ]; then
-	res=$( replacewdir file0="{mount_fstab}.local" old=${workdir} new="CBSDROOT" )
-	_ret=$?
-	[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error replacewdir for ${mount_fstab}.local: ${res}${N0_COLOR}"
+	if [ ${_ret} -ne 0 ]; then
+		${RM_CMD} -f ${JAILRCCONF}
+		err 1 "${N1_COLOR}Error replacewdir for ${JAILRCCONF}: ${res}${N0_COLOR}"
+	fi
+
+	if [ -r ${mount_fstab} ]; then
+		res=$( replacewdir file0="${mount_fstab}" old=${workdir} new="CBSDROOT" )
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error replacewdir for ${mount_fstab}: ${res}${N0_COLOR}"
+	fi
+
+	if [ -r {mount_fstab}.local ]; then
+		res=$( replacewdir file0="{mount_fstab}.local" old=${workdir} new="CBSDROOT" )
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error replacewdir for ${mount_fstab}.local: ${res}${N0_COLOR}"
+	fi
 fi
 
 register_delete_full
