started working on qemu (+nvmm accel) support, WIP

diff --git a/sudoexec/qdestroy b/sudoexec/qdestroy
--- a/sudoexec/qdestroy
+++ b/sudoexec/qdestroy
@@ -4,7 +4,27 @@ MYARG=""
 MYOPTARG="jname"
 MYDESC="Destroy QEMU domain"
 CBSDMODULE="qemu"
-EXTHELP="wf_xremove"
+EXTHELP="wf_qremove"
+ADDHELP="
+${H3_COLOR}Description${N0_COLOR}:
+
+Destroy qemu domain and all related data.
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}jname=${N0_COLOR} - target env name.
+
+${H3_COLOR}Examples${N0_COLOR}:
+
+ # cbsd qdestroy
+ # cbsd qdestroy <env>
+ # cbsd qdestroy jname=<env>
+
+${H3_COLOR}See also${N0_COLOR}:
+
+ cbsd destroy --help
+
+"
 
 . ${subrdir}/nc.subr
 . ${tools}	# for select_jail_by_list
@@ -23,8 +43,7 @@ fi
 . ${jfs}
 
 if [ -n "${jname}" ]; then
-
-	emulator="bhyve" # for jname_is_multiple
+	emulator="qemu" # for jname_is_multiple
 	jname_is_multiple
 
 	if [ -n "${jail_list}" ]; then
@@ -54,10 +73,12 @@ for jname in ${JLIST}; do
 	JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
 	unregister=0
 
+	# get is_cloud settings (used for detect ZVOL_PARENT below)
+	[ -r ${JAILSYSRCCONF} ] && . ${JAILSYSRCCONF}
+
 	. ${subrdir}/rcconf.subr
 	if [ $? -eq 1 ]; then
-		if [ -r "${JAILRCCONF}" -o -r "${JAILSYSRCCONF}" ]; then
-			[ -r ${JAILSYSRCCONF} ] && . ${JAILSYSRCCONF}
+		if [ -r "${JAILRCCONF}" ]; then
 			[ -r ${JAILRCCONF} ] && . ${JAILRCCONF}
 			unregister=1
 		else
@@ -66,58 +87,65 @@ for jname in ${JLIST}; do
 				${ECHO} "${N1_COLOR}No such domain: ${N2_COLOR}${jname}${N0_COLOR}"
 				continue
 			fi
-			remotenode=$( bwhereis ${jname} )
+			remotenode=$( qwhereis ${jname} )
 			if [ -z "${remotenode}" ]; then
 				${ECHO} "${N1_COLOR}No such domain: ${N2_COLOR}${jname}${N0_COLOR}"
 				continue
 			fi
 			for i in ${remotenode}; do
 				if [ "${i}" = "${nodename}" ]; then
-					${ECHO} "${N1_COLOR}Remote xremove: found on nodename ${N2_COLOR}${nodename}${N1_COLOR}. Skipped${N0_COLOR}"
+					${ECHO} "${N1_COLOR}Remote qdestroy: found on nodename ${N2_COLOR}${nodename}${N1_COLOR}. Skipped${N0_COLOR}"
 					continue
-			fi
-			${ECHO} "${N1_COLOR}Remote xremove: ${N2_COLOR}${jname} ${N1_COLOR}on${N2_COLOR} ${i}${N0_COLOR}"
-			rexe node=${i} cbsd xremove jname=${jname}
-			if [ $? -eq 0 ]; then
-				# updating state and put task for retrinv inventory
-				${ECHO} "${N1_COLOR}Updating inventory...${N0_COLOR}"
-				task autoflush=2 mode=new retrinv node=${i} tryoffline=1 data=db > /dev/null 2>&1
-			fi
+				fi
+				${ECHO} "${N1_COLOR}Remote qdestroy: ${N2_COLOR}${jname} ${N1_COLOR}on${N2_COLOR} ${i}${N0_COLOR}"
+				rexe node=${i} cbsd qdestroy jname=${jname}
+				if [ $? -eq 0 ]; then
+					# updating state and put task for retrinv inventory
+					${ECHO} "${N1_COLOR}Updating inventory...${N0_COLOR}"
+					task autoflush=2 mode=new retrinv node=${i} tryoffline=1 data=db > /dev/null 2>&1
+				fi
 			done
 			continue
 		fi
 	fi
 
 	if [ "${protected}" = "1" ]; then
-		${ECHO} "${N1_COLOR}Protected/locked jail. Skip for remove: ${N2_COLOR}${jname}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}Protected/locked env. Skip for remove: ${N2_COLOR}${jname}${N0_COLOR}"
 		continue
 	fi
 
+	# remove port expose
+	[ -n "${ip4_addr}" ] && expose jname=${jname} mode=flush
+
 	# CBSD QUEUE
 	if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
-		[ -n "${cbsd_qemu_queue_name}" ] && ${cbsd_queue_backend} cbsd_qemu_queue_name=${cbsd_qemu_queue_name} id=${jname} cmd=xremove status=1
+		[ -n "${cbsd_qemu_queue_name}" ] && ${cbsd_queue_backend} cbsd_queue_name=${cbsd_qemu_queue_name} id=${jname} cmd=bremove status=1
 	fi
 
 	. ${subrdir}/jcreate.subr
-	export_bhyve_data_for_external_hook
+	export_qemu_data_for_external_hook
 	external_exec_master_script "remove.d"
-
 	PARENT_SNAPSHOTS=
 	DEPENDENT_VMS=
 	PARENT_ZVOL=
-
 	if [ ${unregister} -eq 0 ] ; then
 		if [  ${jid} -ne 0 ]; then
 			case "${emulator}" in
-				"qemu")
-					xstop jname=${jname} noacpi=1
+				bhyve)
+					bstop jname=${jname} noacpi=1
 					;;
-				"virtualbox")
+				qemu)
+					qstop jname=${jname} noacpi=1
+					;;
+				virtualbox)
 					. ${subrdir}/virtualbox.subr
 					vstop jname=${jname}
 					;;
+				xen)
+					xstop jname=${jname} noacpi=1
+					;;
 				*)
-					jstop jname=${jname}
+					jstop jname=${jname} fast=1
 					;;
 			esac
 		fi
@@ -166,7 +194,7 @@ for jname in ${JLIST}; do
 			fi
 
 		fi
-		jcleanup jname=${jname}
+		qcleanup jname=${jname}
 		${UMOUNT_CMD} ${path} 2>/dev/null
 	fi
 
@@ -191,20 +219,31 @@ for jname in ${JLIST}; do
 		done
 	fi
 
+	# jailed process?
+	# if we are not inside jail then check for jailed qemu and remove hoster jail
+	_jailed="0"	# no hoster jail
+	pjailed=$( ${SYSCTL_CMD} -qn security.jail.jailed 2>/dev/null )
+	[ -z "${pjailed}" ] && pjailed=0
+
+	if [ "${pjailed}" = "0" ]; then
+		# we a not jailed
+		# qemu is jailed and has jail?
+		[ -r ${jailsysdir}/${jname}/local.sqlite ] && _jailed=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT jailed FROM settings LIMIT 1" )
+
+		[ -z "${_jailed}" ] && _jailed="0"
+		# when _jailed != 0 use this variable to jremove at the end of the scenatio
+	fi
 	[ -d "${DST}" ] && remove_data_dir ${DST}
 	[ ${zfsfeat} -eq 1 ] && jsnapshot mode=destroyall_original jname=${jname}
 	[ ${unregister} -eq 0 ] && junregister jname=${jname} rcfile=${JAILRCCONF}
-	[ -f "${JAILFSTAB}" ] && ${RM_CMD} -f ${JAILFSTAB}
-	[ -f "${JAILFSTAB}.local" ] && ${RM_CMD} -f "${JAILFSTAB}.local"
+	[ -d "${JAILFSTAB_DIR}" ] && removedir ${JAILFSTAB_DIR}
 	[ -f "${JAILRCCONF}" ] && ${RM_CMD} -f ${JAILRCCONF}
 	[ -f "${jailrcconfdir}/rc.conf_${jname}" ] && ${RM_CMD} -f "${jailrcconfdir}/rc.conf_${jname}"
-	if [ -d "${jailsysdir}/${jname}" ]; then
-		${RM_CMD} -rf "${jailsysdir}/${jname}"
-	elif [ -h "${jailsysdir}/${jname}" ]; then
-		${RM_CMD} -f "${jailsysdir}/${jname}"
-	fi
+	[ -d "${jailsysdir}/${jname}" ] && removedir "${jailsysdir}/${jname}"
+	[ -h "${jailsysdir}/${jname}" ] && ${RM_CMD} -f "${jailsysdir}/${jname}"
 	[ -f "${logdir}/${jname}.log" ] && ${RM_CMD} -f "${logdir}/${jname}.log"
-	[ -d "${jaildir}/${jname}" ] && ${RMDIR_CMD} "${jaildir}/${jname}"
+	[ -d "${jaildir}/${jname}" ] && ${FIND_CMD} ${jaildir}/${jname}/ -type d -exec ${RMDIR_CMD} {} \; > /dev/null 2>&1
+	[ -d "${jaildir}/${jname}" ] && ${RMDIR_CMD} ${jaildir}/${jname}
 	for parent_snapshot in ${PARENT_SNAPSHOTS}; do
 		${ZFS_CMD} destroy ${parent_snapshot}
 	done
@@ -226,12 +265,15 @@ for jname in ${JLIST}; do
 			_msg=$( ${ZFS_CMD} destroy ${ZPOOL} )
 			_ret=$?
 			if [ ${_ret} -ne 0 ]; then
-				${ECHO} "${N1_COLOR}bremove: zfs destroy error for: ${N2_COLOR}${ZPOOL}: ${N1_COLOR}${_msg}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}qdestroy: zfs destroy error for: ${N2_COLOR}${ZPOOL}: ${N1_COLOR}${_msg}${N0_COLOR}"
 			fi
 		fi
 	fi
 
 	[ -d "${vmdir}" ] && ${RM_CMD} -rf ${vmdir}
+
+	# detach ppt
+	cbsdsqlrw local "DELETE FROM qemuppt WHERE jname=\"${jname}\""
 
 	if [ "${emulator}" != "jail" ]; then
 		# TODO: cbsd media unregister mode=removeall jname=jname
@@ -248,17 +290,17 @@ for jname in ${JLIST}; do
 		fi
 	fi
 
-	if [ "${emulator}" = "virtualbox" ]; then
-		. ${subrdir}/virtualbox.subr
-		${VBOX_MGMT_CMD} unregistervm ${jname}
-		[ -d "/root/VirtualBox VMs/${jname}" ] && ${RM_CMD} -rf "/root/VirtualBox VMs/${jname}"
-	fi
-
 	# CBSD QUEUE
 	if [ "${mod_cbsd_queue_enabled}" = "YES" -a -z "${MOD_CBSD_QUEUE_DISABLED}" ]; then
-		[ -n "${cbsd_qemu_queue_name}" ] && ${cbsd_queue_backend} cbsd_qemu_queue_name=${cbsd_qemu_queue_name} id=${jname} cmd=xremove status=2
+		[ -n "${cbsd_qemu_queue_name}" ] && ${cbsd_queue_backend} cbsd_queue_name=${cbsd_qemu_queue_name} id=${jname} cmd=qdestroy status=2
 	fi
 
+	if [ "${_jailed}" != "0" ]; then
+		${ECHO} "${N1_COLOR}remove hoster jail: ${N2_COLOR}${_jailed}${N0_COLOR}"
+		cbsdlogger NOTICE ${CBSD_APP}: remove qemu [${jname}] hoster jail: ${_jailed}
+		jset protected=0 jname=${_jailed}
+		jremove jname="${_jailed}"
+	fi
 done
 
 end_time=$( ${DATE_CMD} +%s )
