wip: jail rc.conf is deprecated now

diff --git a/sudoexec/upgrade b/sudoexec/upgrade
--- a/sudoexec/upgrade
+++ b/sudoexec/upgrade
@@ -109,94 +109,126 @@ create_hierdiff()
 # in ${BASEDIR}
 fetch_inspect_system()
 {
-        # No errors yet...
-        rm -f ${tmpdir}/.err.$$
-        # Tell the user why his disk is suddenly making lots of noise
-        printf "  ${GREEN}*${MAGENTA} Inspecting system [${GREEN}${BASEDIR}${MAGENTA}]... ${NORMAL}"
+	# No errors yet...
+	rm -f ${tmpdir}/.err.$$
+	# Tell the user why his disk is suddenly making lots of noise
+	printf "  ${GREEN}*${MAGENTA} Inspecting system [${GREEN}${BASEDIR}${MAGENTA}]... ${NORMAL}"
 
 	truncate -s0 ${tmpdir}/filelist.$$
 
-        # Generate list of files to inspect
-        cat $1 |
-            cut -f 1 -d '|' |
-            sort -u > ${tmpdir}/filelist.tmp.$$
+	# Generate list of files to inspect
+	cat $1 |
+	    cut -f 1 -d '|' |
+	    sort -u > ${tmpdir}/filelist.tmp.$$
 
 	sort -u ${tmpdir}/filelist.tmp.$$ > ${tmpdir}/filelist.$$
 
 	rm -f ${tmpdir}/filelist.tmp.$$
 
-        # Examine each file and output lines of the form
-        # /path/to/file|type|device-inum|user|group|perm|flags|value
-        # sorted by device and inode number.
-        while read F; do
-                # If the symlink/file/directory does not exist, record this.
-                if ! [ -e ${BASEDIR}/${F} ]; then
-                        echo "${F}|-||||||"
-                        continue
-                fi
+	# Examine each file and output lines of the form
+	# /path/to/file|type|device-inum|user|group|perm|flags|value
+	# sorted by device and inode number.
+	while read F; do
+	    # If the symlink/file/directory does not exist, record this.
+	    if ! [ -e ${BASEDIR}/${F} ]; then
+		echo "${F}|-||||||"
+		continue
+	    fi
 
-                if ! [ -r ${BASEDIR}/${F} ]; then
-                        echo "Cannot read file: ${BASEDIR}/${F}"        \
-                            >/dev/stderr
-                        touch ${tmpdir}/.err.$$
-                        return 1
-                fi
+	    if ! [ -r ${BASEDIR}/${F} ]; then
+		echo "Cannot read file: ${BASEDIR}/${F}" >/dev/stderr
+		touch ${tmpdir}/.err.$$
+		return 1
+	    fi
 
-                # Otherwise, output an index line.
-                if [ -L ${BASEDIR}/${F} ]; then
-                        echo -n "${F}|L|"
-                        stat -n -f '%d-%i|%u|%g|%Mp%Lp|%Of|' ${BASEDIR}/${F};
-                        readlink ${BASEDIR}/${F};
-                elif [ -f ${BASEDIR}/${F} ]; then
-                        echo -n "${F}|f|"
-                        stat -n -f '%d-%i|%u|%g|%Mp%Lp|%Of|' ${BASEDIR}/${F};
-                        sha256 -q ${BASEDIR}/${F};
-                elif [ -d ${BASEDIR}/${F} ]; then
-                        echo -n "${F}|d|"
-                        stat -f '%d-%i|%u|%g|%Mp%Lp|%Of|' ${BASEDIR}/${F};
-                else
-                        echo "Unknown file type: ${BASEDIR}/${F}"       \
-                            >/dev/stderr
-                        touch ${tmpdir}/.err.$$
-                        return 1
-                fi
-        done < ${tmpdir}/filelist.$$ |
-            sort -k 3,3 -t '|' > $2.tmp.$$
-        rm -f ${tmpdir}/filelist.$$
+	    # Otherwise, output an index line.
+	    if [ -L ${BASEDIR}/${F} ]; then
+		echo -n "${F}|L|"
+		stat -n -f '%d-%i|%u|%g|%Mp%Lp|%Of|' ${BASEDIR}/${F};
+		readlink ${BASEDIR}/${F};
+	    elif [ -f ${BASEDIR}/${F} ]; then
+		echo -n "${F}|f|"
+		stat -n -f '%d-%i|%u|%g|%Mp%Lp|%Of|' ${BASEDIR}/${F};
+		sha256 -q ${BASEDIR}/${F};
+	    elif [ -d ${BASEDIR}/${F} ]; then
+		echo -n "${F}|d|"
+		stat -f '%d-%i|%u|%g|%Mp%Lp|%Of|' ${BASEDIR}/${F};
+	    else
+		echo "Unknown file type: ${BASEDIR}/${F}" >/dev/stderr
+		touch ${tmpdir}/.err.$$
+		return 1
+	    fi
+	done < ${tmpdir}/filelist.$$ |
 
-        # Check if an error occurred during system inspection
-        if [ -f ${tmpdir}/.err.$$ ]; then
-                return 1
-        fi
-       # Convert to the form
-        # /path/to/file|type|user|group|perm|flags|value|hlink
-        # by resolving identical device and inode numbers into hard links.
-        cut -f 1,3 -d '|' $2.tmp.$$ |
-            sort -k 1,1 -t '|' |
-            sort -s -u -k 2,2 -t '|' |
-            join -1 2 -2 3 -t '|' - $2.tmp.$$ |
-            awk -F \| -v OFS=\|         \
-                '{
-                    if (($2 == $3) || ($4 == "-"))
-                        print $3,$4,$5,$6,$7,$8,$9,""
-                    else
-                        print $3,$4,$5,$6,$7,$8,$9,$2
-                }' |
-            sort > $2
-        rm $2.tmp.$$
+	sort -k 3,3 -t '|' > $2.tmp.$$
+	rm -f ${tmpdir}/filelist.$$
 
-        # We're finished looking around
-        ${ECHO} "${MAGENTA}done.${NORMAL}"
+	# Check if an error occurred during system inspection
+	[ -f ${tmpdir}/.err.$$ ] && return 1
+
+	# Convert to the form
+	# /path/to/file|type|user|group|perm|flags|value|hlink
+	# by resolving identical device and inode numbers into hard links.
+	cut -f 1,3 -d '|' $2.tmp.$$ |
+	    sort -k 1,1 -t '|' |
+	    sort -s -u -k 2,2 -t '|' |
+	    join -1 2 -2 3 -t '|' - $2.tmp.$$ |
+	    awk -F \| -v OFS=\|         \
+	    '{
+		if (($2 == $3) || ($4 == "-"))
+		    print $3,$4,$5,$6,$7,$8,$9,""
+		else
+		print $3,$4,$5,$6,$7,$8,$9,$2
+	    }' |
+	    sort > $2
+	    rm $2.tmp.$$
+
+	# We're finished looking around
+	${ECHO} "${MAGENTA}done.${NORMAL}"
 }
 
-# Compare INDEX-ALL and INDEX-PRESENT and print warnings about differences.
-IDS_compare ()
+# Remove files which we want to delete
+install_delete()
+{
+	# Generate list of new files
+	cut -f 1 -d '|' < $2 | sort > newfiles
+
+	# Generate subindex of old files we want to nuke
+	sort -k 1,1 -t '|' $1 |
+	    join -t '|' -v 1 - newfiles |
+	    sort -r -k 1,1 -t '|' |
+	    cut -f 1,2 -d '|' |
+	    tr '|' ' ' > killfiles
+
+	# Remove the offending bits
+	while read FPATH TYPE; do
+	    case ${TYPE} in
+		d)
+		    rmdir ${BASEDIR}/${FPATH}
+		    ;;
+		f)
+		    rm ${BASEDIR}/${FPATH}
+		    ;;
+		L)
+		    rm ${BASEDIR}/${FPATH}
+		    ;;
+	    esac
+	done < killfiles
+
+	# Clean up
+	rm newfiles killfiles
+}
+
+
+#Install new files, delete old files, and update linker.hints
+prepare_joblist()
 {
         # Get all the lines which mismatch in something other than file
         # flags.  We ignore file flags because sysinstall doesn't seem to
         # set them when it installs FreeBSD; warning about these adds a
         # very large amount of noise.
 #        cut -f 1-5,7-8 -d '|' $1 > $1.noflags
+
         sort -k 1,1 -t '|' $1 > $1.sorted
 
         cat $2 |
@@ -212,27 +244,11 @@ IDS_compare ()
             sort -u |
             comm -13 - ${tmpdir}/INDEX-NOTMATCHING > ${tmpdir}/INDEX-NOTMATCHING.tmp
         mv ${tmpdir}/INDEX-NOTMATCHING.tmp ${tmpdir}/INDEX-NOTMATCHING
-                  
+
         # Go through the lines and print warnings.
         while read LINE; do
-#echo "D: ${LINE}"
-#                FPATH=`echo "${LINE}" | cut -f 1 -d '|'`
-#                TYPE=`echo "${LINE}" | cut -f 2 -d '|'`
-#                OWNER=`echo "${LINE}" | cut -f 3 -d '|'`
-#                GROUP=`echo "${LINE}" | cut -f 4 -d '|'`
-#                PERM=`echo "${LINE}" | cut -f 5 -d '|'`
-#                FLAGS=`echo "${LINE}" | cut -f 6 -d '|'`
-#                HASH=`echo "${LINE}" | cut -f 7 -d '|'`
-#                LINK=`echo "${LINE}" | cut -f 8 -d '|'`
-#                P_TYPE=`echo "${LINE}" | cut -f 9 -d '|'`
-#                P_OWNER=`echo "${LINE}" | cut -f 10 -d '|'`
-#                P_GROUP=`echo "${LINE}" | cut -f 11 -d '|'`
-#                P_PERM=`echo "${LINE}" | cut -f 12 -d '|'`
-#                P_FLAGS=`echo "${LINE}" | cut -f 13 -d '|'`
-#                P_HASH=`echo "${LINE}" | cut -f 14 -d '|'`
-#                P_LINK=`echo "${LINE}" | cut -f 15 -d '|'`
-	sqllist ${LINE} FPATH TYPE OWNER GROUP PERM FLAGS HASH LINK P_TYPE P_OWNER P_GROUP P_PERM P_FLAGS P_HASH P_LINK
 
+		sqllist ${LINE} FPATH TYPE OWNER GROUP PERM FLAGS HASH LINK P_TYPE P_OWNER P_GROUP P_PERM P_FLAGS P_HASH P_LINK
 
                 # Warn about different object types.
                 if ! [ "${TYPE}" = "${P_TYPE}" ]; then
@@ -319,9 +335,9 @@ IDS_compare ()
                 # underlying data is correct they really don't matter.
         done < ${tmpdir}/INDEX-NOTMATCHING
 
+cp ${tmpdir}/INDEX-NOTMATCHING /
         # Clean up
-        rm $1 $1.sorted $2 ${tmpdir}/INDEX-NOTMATCHING
-
+        rm $1.sorted ${tmpdir}/INDEX-NOTMATCHING
 }
 
 # Install new files
@@ -332,6 +348,12 @@ install_from_index()
         sort -k 1,1 -t '|' $1 |
             tr '|' ' ' |
             while read FPATH TYPE OWNER GROUP PERM FLAGS HASH LINK; do
+
+                OLDFLAGS=`stat -f "%Of" ${DSTDIR}${FPATH} 2>/dev/null`
+                NEWFLAGS=`stat -f "%Of" ${SRCDIR}${FPATH} 2>/dev/null`
+
+		[ "$OLDFLAGS" != "0" ] && chflags 0 ${DSTDIR}${FPATH}
+
                 case ${TYPE} in
                 d)
                         # Create a directory
@@ -342,8 +364,11 @@ install_from_index()
                                 # Create a file, without setting flags.
                                 install -S -o ${OWNER} -g ${GROUP} -m ${PERM} ${SRCDIR}${FPATH} ${DSTDIR}${FPATH}
                         else
+                                install -S -o ${OWNER} -g ${GROUP} -m ${PERM} ${SRCDIR}${FPATH} ${DSTDIR}${FPATH}
                                 # Create a hard link.
-                                ln -f ${DSTDIR}${LINK} ${DSTDIR}${FPATH}
+#                                ln -f ${DSTDIR}${LINK} ${DSTDIR}${FPATH}
+				ln -f ${DSTDIR}${FPATH} ${DSTDIR}${LINK}
+				[ "${OLDFLAGS}" != "0" ] && chflags ${OLDFLAGS} ${DSTDIR}${FPATH}
                         fi
                         ;;
                 L)
@@ -351,6 +376,7 @@ install_from_index()
 			ln -sfh ${HASH} ${DSTDIR}${FPATH}
                         ;;
                 esac
+		[ "$NEWFLAGS" != "0" ] && chflags $NEWFLAGS ${DSTDIR}${FPATH} 
             done
 
         # Perform a second pass, adding file flags.
@@ -365,7 +391,6 @@ install_from_index()
 
 
 ### Cumulative. func
-
 stage1()
 {
 	${ECHO} "${GREEN}* ${MAGENTA}Create hier${NORMAL}"
@@ -397,34 +422,39 @@ stage1()
 
 stage2()
 {
-    ${ECHO} "${GREEN}* ${MAGENTA}Compare hier${NORMAL}"
-    create_hierdiff ${tmpdir}/${DSTNAME}.hier.$$ ${tmpdir}/${SRCNAME}.hier.$$
+	${ECHO} "${GREEN}* ${MAGENTA}Compare hier${NORMAL}"
+	create_hierdiff ${tmpdir}/${DSTNAME}.hier.$$ ${tmpdir}/${SRCNAME}.hier.$$
 }
 
 stage3()
 {
-    ${ECHO} "${GREEN}* ${MAGENTA}Create IDS${NORMAL}"
-    for BASEDIR in ${SRCDIR} ${DSTDIR}; do
-	name=`md5 -qs ${BASEDIR}`
-	# For all paths appearing in INDEX-OLD or INDEX-NEW, inspect the
-	# system and generate an INDEX-PRESENT file.
-	fetch_inspect_system ${tmpdir}/${name}.hier.$$ ${tmpdir}/${name}.ids.$$ || return 1
-    done
+	${ECHO} "${GREEN}* ${MAGENTA}Create IDS${NORMAL}"
+	for BASEDIR in ${SRCDIR} ${DSTDIR}; do
+	    name=`md5 -qs ${BASEDIR}`
+	    # For all paths appearing in INDEX-OLD or INDEX-NEW, inspect the
+	    # system and generate an INDEX-PRESENT file.
+	    fetch_inspect_system ${tmpdir}/${name}.hier.$$ ${tmpdir}/${name}.ids.$$ || return 1
+	done
 }
 
 stage4()
 {
-    ${ECHO} "${GREEN}* ${MAGENTA}Compare IDS${NORMAL}"
-    truncate -s0 ${WORK_IDS}
-    IDS_compare ${tmpdir}/${SRCNAME}.ids.$$ ${tmpdir}/${DSTNAME}.ids.$$
+	${ECHO} "${GREEN}* ${MAGENTA}Create file list from IDS${NORMAL}"
+	truncate -s0 ${WORK_IDS}
+	prepare_joblist ${tmpdir}/${SRCNAME}.ids.$$ ${tmpdir}/${DSTNAME}.ids.$$
 }
 
 stage5()
 {
-    while read F; do
-	fgrep "${F}|" ${tmpdir}/${SRCNAME}.hier.$$ >> ${WORK_IDS}
-##	grep "^${F}|" ${SRCNAME}.hier >> ${WORK_IDS}
-    done < ${tmpdir}/files.added.$$
+	while read F; do
+	    fgrep "${F}|" ${tmpdir}/${SRCNAME}.hier.$$ >> ${WORK_IDS}
+	done < ${tmpdir}/files.added.$$
+}
+
+stage7()
+{
+	${ECHO} "${GREEN}* ${MAGENTA}Prune old files and directory from IDS${NORMAL}"
+	install_delete ${tmpdir}/${SRCNAME}.ids.$$ ${tmpdir}/${DSTNAME}.ids.$$
 }
 
 #stage5()
@@ -440,18 +470,18 @@ stage5()
 
 stage6()
 {
-    ${ECHO} "${GREEN}* ${MAGENTA}Installing${NORMAL}"
-    install_from_index ${WORK_IDS}
+	${ECHO} "${GREEN}* ${MAGENTA}Installing${NORMAL}"
+	install_from_index ${WORK_IDS}
 #    install_from_index /usr/jails/tmp/job.ids.16793
 }
 
-stage7()
+stage8()
 {
-    ${ECHO} "${GREEN}* ${MAGENTA}Cleanup${NORMAL}"
-    #store src hier as dst hier in gzip
-    mv ${tmpdir}/${SRCNAME}.hier.$$  ${tmpdir}/${DSTNAME}.hier
-    gzip -9c ${tmpdir}/${DSTNAME}.hier > ${dbdir}/nodehier.${DSTNAME}.gz
-    rm -f ${tmpdir}/${SRCNAME}.hier.$$ ${tmpdir}/${DSTNAME}.hier.$$ ${tmpdir}/${DSTNAME}.hier ${tmpdir}/files.removed.$$ ${tmpdir}/files.added.$$ ${tmpdir}/files.updated.$$ ${tmpdir}/cmp.ids.$$ ${tmpdir}/job.ids.$$
+	${ECHO} "${GREEN}* ${MAGENTA}Cleanup${NORMAL}"
+	#store src hier as dst hier in gzip
+	mv ${tmpdir}/${SRCNAME}.hier.$$  ${tmpdir}/${DSTNAME}.hier
+	gzip -9c ${tmpdir}/${DSTNAME}.hier > ${dbdir}/nodehier.${DSTNAME}.gz
+	rm -f ${tmpdir}/${SRCNAME}.ids.$$ ${tmpdir}/${DSTNAME}.ids.$$ ${tmpdir}/${SRCNAME}.hier.$$ ${tmpdir}/${DSTNAME}.hier.$$ ${tmpdir}/${DSTNAME}.hier ${tmpdir}/files.removed.$$ ${tmpdir}/files.added.$$ ${tmpdir}/files.updated.$$ ${tmpdir}/cmp.ids.$$ ${tmpdir}/job.ids.$$
 }
 
 init_world()
@@ -484,7 +514,8 @@ upgrade_world()
 	stage4
 	stage5
 	stage6
-	stage7
+#	stage7
+	stage8
 }
 
 ###MAIN
@@ -498,7 +529,7 @@ case "${target}" in
     "kernel")
 	init_kernel
 	upgrade_kernel "${KERNELSOURCE}"
-        ;;
+	;;
     "node")
 	init_kernel
 	init_world
@@ -509,4 +540,3 @@ case "${target}" in
 	${ECHO} "Unsupported target"
 	;;
 esac
-
