test for IP address

diff --git a/sudoexec/vpc b/sudoexec/vpc
--- a/sudoexec/vpc
+++ b/sudoexec/vpc
@@ -19,6 +19,7 @@ node_member in mode=create can be 'all'\n\
 header=0 don't print header\n\
 display= list by comma for column. Default: name,pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk\n\
 dryrun=1 - print command only, dont apply\n"
+EXTHELP="wf_vpc"
 
 . ${subr}
 dryrun=0
@@ -168,12 +169,31 @@ init_vxlan()
 		iptype ${_node_ip} > /dev/null 2>&1
 		case $? in
 			0)
-				[ -z "${_node_ip}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to determine ip type for: ${N2_COLOR}${_node_ip}${N0_COLOR}"
+				err 1 "${N1_COLOR}${CBSD_APP}: unable to determine ip type for: ${N2_COLOR}${_node_ip}${N0_COLOR}"
 				;;
 			1)
+				iptype ${nodeip} > /dev/null 2>&1
+				case $? in
+					0)
+						${ECHO} "${N1_COLOR}${CBSD_APP}: unable to determine ip type for nodeip: ${N2_COLOR}${nodeip}${N0_COLOR}"
+						err 1 "${N1_COLOR}${CBSD_APP}: please set it via: ${N2_COLOR}cbsd initenv-tui${N0_COLOR}"
+						;;
+					*)
+						;;
+				esac
+
 				_myip="${nodeip}"
 				;;
 			2)
+				iptype ${nodeip6} > /dev/null 2>&1
+				case $? in
+					0)
+						${ECHO} "${N1_COLOR}${CBSD_APP}: unable to determine ip type for nodeip6: ${N2_COLOR}${nodeip6}${N0_COLOR}"
+						err 1 "${N1_COLOR}${CBSD_APP}: please set it via: ${N2_COLOR}cbsd initenv-tui${N0_COLOR}"
+						;;
+					*)
+						;;
+				esac
 				_myip="${nodeip6}"
 				;;
 		esac
@@ -184,6 +204,7 @@ init_vxlan()
 			continue
 		fi
 
+		echo "${IFCONFIG_CMD} vxlan${vxlan_id} create vxlanid ${vxlan_id} vxlanlocal ${_myip} vxlanremote ${_node_ip} inet ${peer_ip} mtu 1450 up"
 		_res="${IFCONFIG_CMD} vxlan${vxlan_id} create vxlanid ${vxlan_id} vxlanlocal ${_myip} vxlanremote ${_node_ip} inet ${peer_ip} mtu 1450 up"
 		if [ ${dryrun} -eq 1 ]; then
 			echo "${_res}"
@@ -266,9 +287,26 @@ init_bridge()
 				[ -z "${_node_ip}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to determine ip type for: ${N2_COLOR}${_node_ip}${N0_COLOR}"
 				;;
 			1)
+				iptype ${nodeip} > /dev/null 2>&1
+				case $? in
+					0)
+						${ECHO} "${N1_COLOR}${CBSD_APP}: unable to determine ip type for nodeip: ${N2_COLOR}${nodeip}${N0_COLOR}"
+						err 1 "${N1_COLOR}${CBSD_APP}: please set it via: ${N2_COLOR}cbsd initenv-tui${N0_COLOR}"
+						;;
+					*)
+						;;
+				esac
 				_myip="${nodeip}"
 				;;
 			2)
+				case $? in
+					0)
+						${ECHO} "${N1_COLOR}${CBSD_APP}: unable to determine ip type for nodeip6: ${N2_COLOR}${nodeip6}${N0_COLOR}"
+						err 1 "${N1_COLOR}${CBSD_APP}: please set it via: ${N2_COLOR}cbsd initenv-tui${N0_COLOR}"
+						;;
+					*)
+						;;
+				esac
 				_myip="${nodeip6}"
 				;;
 		esac
