cloudinit: check for empty ci_pubkey

diff --git a/modules/bsdconf.d/cloudinit b/modules/bsdconf.d/cloudinit
--- a/modules/bsdconf.d/cloudinit
+++ b/modules/bsdconf.d/cloudinit
@@ -15,7 +15,7 @@ cloudengine - 'cloud-init' (default) or 'cloudinit-base'\n"
 [ -z "${cloudengine}" ] && cloudengine="cloud-init"
 
 _MYDIR="${distdir}/modules/bsdconf.d"
-SERVICE="adduser"
+SERVICE="cloudinit"
 
 case "${cloudengine}" in
 	cloud-init)
@@ -60,23 +60,25 @@ show()
 		shift $(($OPTIND - 1))
 	done
 
-	# ci_pubkey test
-	. ${distdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
-	if [ -r "${workdir}/${ci_pubkey}" ]; then
-		_keytest=$( /usr/bin/grep -v '#' ${workdir}/${ci_pubkey} | /usr/bin/grep . | /usr/bin/head -n1 )
-		if ! is_valid_ssh_key "${_keytest}"; then
-			err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${workdir}/${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+	if [ -n "${ci_pubkey}" ]; then
+		# ci_pubkey test
+		. ${distdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
+		if [ -r "${workdir}/${ci_pubkey}" ]; then
+			_keytest=$( /usr/bin/grep -v '#' ${workdir}/${ci_pubkey} | /usr/bin/grep . | /usr/bin/head -n1 )
+			if ! is_valid_ssh_key "${_keytest}"; then
+				err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${workdir}/${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+			fi
+		elif [ -r "${ci_pubkey}" ]; then
+			_keytest=$( /usr/bin/grep -v '#' ${ci_pubkey} | /usr/bin/grep . | /usr/bin/head -n1 )
+			if ! is_valid_ssh_key "${_keytest}"; then
+				err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+			fi
+		else
+			if ! is_valid_ssh_key "${ci_pubkey}"; then
+				err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${mtag}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+			fi
+			_keytest="${ci_pubkey}"
 		fi
-	elif [ -r "${ci_pubkey}" ]; then
-		_keytest=$( /usr/bin/grep -v '#' ${ci_pubkey} | /usr/bin/grep . | /usr/bin/head -n1 )
-		if ! is_valid_ssh_key "${_keytest}"; then
-			err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
-		fi
-	else
-		if ! is_valid_ssh_key "${ci_pubkey}"; then
-			err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${mtag}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
-		fi
-		_keytest="${ci_pubkey}"
 	fi
 
 	ci_user_pw_user_lock="false"
@@ -181,9 +183,10 @@ show()
 	esac
 }
 
-
 # MAIN
-if [ -r "${fromfile}" ]; then
+if [ -n "${fromfile}" ]; then
+
+	[ ! -r "${fromfile}" ] && err 1 "${N1_COLOR}cloudinit: no such fromfile: ${N2_COLOR}${fromfile}${N0_COLOR}"
 
 	unset ci_template ci_user_pw_root ci_user_add ci_ip4_addr ci_gw4 ci_nameserver_address ci_nameserver_search
 	unset ci_jname ci_fqdn ci_interface ci_ip4_addr ci_gw4 ci_nameserver_address ci_user_pw_user ci_user_pw_root
