return 1 when no valid key detected

diff --git a/modules/bsdconf.d/cloudinit b/modules/bsdconf.d/cloudinit
--- a/modules/bsdconf.d/cloudinit
+++ b/modules/bsdconf.d/cloudinit
@@ -74,16 +74,19 @@ show()
 		if [ -r "${workdir}/${ci_pubkey}" ]; then
 			_keytest=$( ${GREP_CMD} -v '#' ${workdir}/${ci_pubkey} | ${GREP_CMD} . | /usr/bin/head -n1 )
 			if ! is_valid_ssh_key "${_keytest}"; then
-				err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${workdir}/${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+				echo "cloudinit: invalid ssh key in ${workdir}/${ci_pubkey} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+				return 1
 			fi
 		elif [ -r "${ci_pubkey}" ]; then
 			_keytest=$( ${GREP_CMD} -v '#' ${ci_pubkey} | ${GREP_CMD} . | /usr/bin/head -n1 )
 			if ! is_valid_ssh_key "${_keytest}"; then
-				err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+				echo "cloudinit: invalid ssh key in ${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+				return 1
 			fi
 		else
 			if ! is_valid_ssh_key "${ci_pubkey}"; then
-				err 1 "${N1_COLOR}cloudinit: invalid ssh key in ${mtag}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${N0_COLOR}"
+				echo "cloudinit: invalid ssh key: ${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+				return 1
 			fi
 			_keytest="${ci_pubkey}"
 		fi
@@ -202,6 +205,8 @@ if [ -n "${fromfile}" ]; then
 
 	. ${fromfile}
 
+	#cp -a ${fromfile} /tmp/1.txt
+
 	[ -z "${ci_template}" ] && err 1 "${N1_COLOR}No ci_template${N0_COLOR}"
 
 	for i in ${ci_user_add}; do
@@ -220,20 +225,28 @@ if [ -n "${fromfile}" ]; then
 		# global pubkey
 		if [ -n "${ci_user_pubkey}" ]; then
 			ci_pubkey="${ci_user_pubkey}"
-			ci_user_pubkey_${i}="${ci_user_pubkey}"
+			echo "LOL: [$ci_pubkey]"
+			exit 1
+			eval ci_user_pubkey_${i}="${ci_user_pubkey}"
 		fi
 
 		case "${mode}" in
 			show)
 				for i in ${cloud_data_files}; do
 					show -s ${i}
+					ret=$?
+					[ ${ret} -ne 0 ] && err ${ret} "cloudinit error"
 				done
-				ret=$?
 				;;
 			gen)
 				[ ! -d "${cloud_init_dir}" ] && /bin/mkdir -p ${cloud_init_dir}
 				for i in ${cloud_data_files}; do
 					show -s ${i} > ${cloud_init_dir}/${i}
+					ret=$?
+					if [ ${ret} -ne 0 ]; then
+						${CAT_CMD} ${cloud_init_dir}/${i}
+						err ${ret} "cloudinit error"
+					fi
 				done
 
 				if [ "${ci_adjust_inteface_helper}" = "1" ]; then
@@ -247,7 +260,7 @@ if [ -n "${fromfile}" ]; then
 		esac
 
 	done
-	exit 0
+	exit ${ret}
 fi
 
 case "${mode}" in
