bhyve cloud-init: ci_pubkey can be file
when .ssh/authorized_key, use node key as custom login_cmd via blogin.conf

diff --git a/modules/bsdconf.d/cloudinit b/modules/bsdconf.d/cloudinit
--- a/modules/bsdconf.d/cloudinit
+++ b/modules/bsdconf.d/cloudinit
@@ -37,6 +37,7 @@ show()
 {
 	local _source=
 	local _tpldir="${_MYDIR}/cloud-tpl/${ci_template}"
+	local _keytest
 
 	[ ! -d ${_tpldir} ] && err 1 "${MAGENTA}cloudinit: no template dir: ${GREEN}${_tpldir}${NORMAL}"
 
@@ -46,6 +47,25 @@ show()
 		esac
 		shift $(($OPTIND - 1))
 	done
+
+	# ci_pubkey test
+	. ${distdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
+	if [ -r "${workdir}/${ci_pubkey}" ]; then
+		_keytest=$( /usr/bin/grep -v '#' ${workdir}/${ci_pubkey} | /usr/bin/grep . | /usr/bin/head -n1 )
+		if ! is_valid_ssh_key "${_keytest}"; then
+			err 1 "${MAGENTA}cloudinit: invalid ssh key in ${workdir}/${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${NORMAL}"
+		fi
+	elif [ -r "${ci_pubkey}" ]; then
+		_keytest=$( /usr/bin/grep -v '#' ${ci_pubkey} | /usr/bin/grep . | /usr/bin/head -n1 )
+		if ! is_valid_ssh_key "${_keytest}"; then
+			err 1 "${MAGENTA}cloudinit: invalid ssh key in ${ci_pubkey}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${NORMAL}"
+		fi
+	else
+		if ! is_valid_ssh_key "${ci_pubkey}"; then
+			err 1 "${MAGENTA}cloudinit: invalid ssh key in ${mtag}. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa${NORMAL}"
+		fi
+		_keytest="${ci_pubkey}"
+	fi
 
 	case "${_source}" in
 		meta-data)
@@ -64,7 +84,7 @@ show()
 		user-data)
 			/usr/bin/sed -e "s:%%ci_login%%:${ci_login}:g" \
 			-e "s:%%ci_shell%%:${ci_shell}:g" \
-			-e "s:%%ci_pubkey%%:${ci_pubkey}:g" \
+			-e "s:%%ci_pubkey%%:${_keytest}:g" \
 			${_tpldir}/${_source}
 			;;
 	esac
