added tiny-cloud engine: WIP

diff --git a/modules/bsdconf.d/cloudinit b/modules/bsdconf.d/cloudinit
--- a/modules/bsdconf.d/cloudinit
+++ b/modules/bsdconf.d/cloudinit
@@ -38,6 +38,11 @@ _MYDIR="${distdir}/modules/bsdconf.d"
 SERVICE="cloudinit"
 
 case "${cloudengine}" in
+	tiny-cloud)
+		# build-in
+		cloud_init_dir="${jailsysdir}/${jname}/cloud-init"
+		cloud_data_files="meta-data user-data"
+		;;
 	cloud-init)
 		cloud_init_dir="${jailsysdir}/${jname}/cloud-init"
 		cloud_data_files="meta-data network-config user-data"
@@ -107,8 +112,76 @@ show()
 	# todo: test for empty values
 	case "${_source}" in
 		meta-data)
+			if [ "${cloudengine}" = "tiny-cloud" ]; then
+				# olevole comment: /usr/local/cbsd/modules/bsdconf.d/cloud-tpl/tiny-cloud/README.md
+				unset ci_pubkey ci_pubkey2
+
+				# global pubkey
+				if [ -z "${ci_pubkey}" ]; then
+					ci_pubkey="${ci_user_pubkey}"
+				fi
+
+				if [ -n "${ci_user_pubkey2}" ]; then
+					ci_pubkey2="${ci_user_pubkey2}"
+				fi
+
+				if [ -n "${ci_pubkey}" ]; then
+					# ci_pubkey test
+					. ${subrdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
+					if [ -r "${workdir}/${ci_pubkey}" ]; then
+						_keytest=$( ${GREP_CMD} -v '#' ${workdir}/${ci_pubkey} | ${GREP_CMD} . | ${HEAD_CMD} -n1 )
+						if ! is_valid_ssh_key "${_keytest}"; then
+							echo "cloudinit: invalid ssh key from ${workdir}/${ci_pubkey} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							echo "found: [${_keytest}]"
+							return 1
+						fi
+					elif [ -r "${ci_pubkey}" ]; then
+						_keytest=$( ${GREP_CMD} -v '#' ${ci_pubkey} | ${GREP_CMD} . | ${HEAD_CMD} -n1 )
+						if ! is_valid_ssh_key "${_keytest}"; then
+							echo "cloudinit: invalid ssh key from ${ci_pubkey} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							echo "found: [${_keytest}]"
+							return 1
+						fi
+					else
+						if ! is_valid_ssh_key "${ci_pubkey}"; then
+							echo "cloudinit: invalid ssh key: [${ci_pubkey}]. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							return 1
+						fi
+						_keytest="${ci_pubkey}"
+					fi
+				fi
+
+				if [ -n "${ci_pubkey2}" ]; then
+					# ci_pubkey2 test
+					. ${subrdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
+					if [ -r "${workdir}/${ci_pubkey2}" ]; then
+						_keytest2=$( ${GREP_CMD} -v '#' ${workdir}/${ci_pubkey2} | ${GREP_CMD} . | ${HEAD_CMD} -n1 )
+						if ! is_valid_ssh_key "${_keytest2}"; then
+							echo "cloudinit: invalid ssh key from ${workdir}/${ci_pubkey2} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							echo "found: [${_keytest2}]"
+							return 1
+						fi
+					elif [ -r "${ci_pubkey2}" ]; then
+						_keytest2=$( ${GREP_CMD} -v '#' ${ci_pubkey2} | ${GREP_CMD} . | ${HEAD_CMD} -n1 )
+						if ! is_valid_ssh_key "${_keytest2}"; then
+							echo "cloudinit: invalid ssh key from ${ci_pubkey2} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							echo "found: [${_keytest2}]"
+							return 1
+						fi
+					else
+						if ! is_valid_ssh_key "${ci_pubkey2}"; then
+							echo "cloudinit: invalid ssh key: [${ci_pubkey2}]. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							return 1
+						fi
+						_keytest2="${ci_pubkey2}"
+					fi
+				fi
+			fi
+
 			[ -r ${_tpldir}/${_source} ] && ${SED_CMD} -e "s:%%ci_jname%%:${ci_jname}:g" \
 			-e "s:%%ci_fqdn%%:${ci_fqdn}:g" \
+			-e "s:%%ci_pubkey%%:${_keytest}:g" \
+			-e "s:%%ci_pubkey2%%:${_keytest2}:g" \
 			${_tpldir}/${_source}
 			;;
 		meta_data.json)
@@ -416,6 +489,15 @@ show()
 
 			# change root password needed?
 			need_root_chpasswd=0
+
+			if [ "${cloudengine}" = "tiny-cloud" ]; then
+				# olevole comment: /usr/local/cbsd/modules/bsdconf.d/cloud-tpl/tiny-cloud/README.md
+				${SED_CMD} -e "s:%%ci_interface%%:${ci_interface}:g" \
+				-e "s:%%ci_ip4_addr%%:${ci_ip4_addr}:g" \
+				-e "s:%%ci_gw4%%:${ci_gw4}:g" \
+				${_tpldir}/user-data-static
+				return 0
+			fi
 
 			[ -r ${_tpldir}/10-user-data ] && ${CAT_CMD} ${_tpldir}/10-user-data		# header
 
