cloud-init: support for secondary pubkey via ci_user_pubkey2

diff --git a/modules/bsdconf.d/cloudinit b/modules/bsdconf.d/cloudinit
--- a/modules/bsdconf.d/cloudinit
+++ b/modules/bsdconf.d/cloudinit
@@ -80,7 +80,7 @@ show()
 {
 	local _source=
 	local _tpldir="${_MYDIR}/cloud-tpl/${ci_template}"
-	local _keytest
+	local _keytest= _keytest2=
 	local _nomask=1
 
 	[ ! -d ${_tpldir} ] && err 1 "${N1_COLOR}cloudinit: no template dir: ${N2_COLOR}${_tpldir}${N0_COLOR}"
@@ -424,7 +424,7 @@ show()
 				need_user_chpasswd=0
 
 				unset login epw ci_pw ci_fullname ci_secgroup ci_group ci_shell res err
-				unset ci_pubkey
+				unset ci_pubkey ci_pubkey2
 				ci_login="${i}"
 
 				f_getvar ci_user_pw_${i} ci_pw
@@ -469,6 +469,10 @@ show()
 					ci_pubkey="${ci_user_pubkey}"
 				fi
 
+				if [ -n "${ci_user_pubkey2}" ]; then
+					ci_pubkey2="${ci_user_pubkey2}"
+				fi
+
 				if [ -n "${ci_pubkey}" ]; then
 					# ci_pubkey test
 					. ${subrdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
@@ -495,6 +499,32 @@ show()
 					fi
 				fi
 
+				if [ -n "${ci_pubkey2}" ]; then
+					# ci_pubkey2 test
+					. ${subrdir}/settings-tui-virtual.subr	# for is_valid_ssh_key
+					if [ -r "${workdir}/${ci_pubkey2}" ]; then
+						_keytest2=$( ${GREP_CMD} -v '#' ${workdir}/${ci_pubkey2} | ${GREP_CMD} . | ${HEAD_CMD} -n1 )
+						if ! is_valid_ssh_key "${_keytest2}"; then
+							echo "cloudinit: invalid ssh key from ${workdir}/${ci_pubkey2} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							echo "found: [${_keytest2}]"
+							return 1
+						fi
+					elif [ -r "${ci_pubkey2}" ]; then
+						_keytest2=$( ${GREP_CMD} -v '#' ${ci_pubkey2} | ${GREP_CMD} . | ${HEAD_CMD} -n1 )
+						if ! is_valid_ssh_key "${_keytest2}"; then
+							echo "cloudinit: invalid ssh key from ${ci_pubkey2} file. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							echo "found: [${_keytest2}]"
+							return 1
+						fi
+					else
+						if ! is_valid_ssh_key "${ci_pubkey2}"; then
+							echo "cloudinit: invalid ssh key: [${ci_pubkey2}]. valid key: ssh-rsa,ssh-ed25519,ecdsa-*,ssh-dsa"
+							return 1
+						fi
+						_keytest2="${ci_pubkey2}"
+					fi
+				fi
+
 				prefix=$( substr --pos=0 --len=1 --str=${ci_user_pw_user} )
 				if [ "${prefix}" = "*" ]; then
 					ci_user_pw_user_lock="true"
@@ -507,12 +537,14 @@ show()
 					[ -r ${_tpldir}/20-user-data-user-password ] && ${SED_CMD} -e "s:%%ci_login%%:${ci_login}:g" \
 					-e "s:%%ci_shell%%:${ci_shell}:g" \
 					-e "s:%%ci_pubkey%%:${_keytest}:g" \
+					-e "s:%%ci_pubkey2%%:${_keytest2}:g" \
 					-e "s:%%ci_user_pw_user%%:${ci_user_pw_user}:g" \
 					${_tpldir}/20-user-data-user-password
 				else
 					[ -r ${_tpldir}/20-user-data-user-lockpassword ] && ${SED_CMD} -e "s:%%ci_login%%:${ci_login}:g" \
 					-e "s:%%ci_shell%%:${ci_shell}:g" \
 					-e "s:%%ci_pubkey%%:${_keytest}:g" \
+					-e "s:%%ci_pubkey2%%:${_keytest2}:g" \
 					${_tpldir}/20-user-data-user-lockpassword
 				fi
 			done
@@ -556,7 +588,7 @@ if [ -n "${fromfile}" ]; then
 
 	unset ci_template ci_user_pw_root ci_user_add ci_ip4_addr ci_gw4 ci_nameserver_address ci_nameserver_search
 	unset ci_jname ci_fqdn ci_interface ci_ip4_addr ci_gw4 ci_nameserver_address ci_user_pw_user ci_user_pw_root
-	unset ci_nic_hwaddr0 ci_user_pubkey ci_interface_mtu default_ci_interface_mtu
+	unset ci_nic_hwaddr0 ci_user_pubkey ci_user_pubkey2 ci_interface_mtu default_ci_interface_mtu
 
 	. ${fromfile}
 
