jexport: ability to add custom header data

diff --git a/modules/bsdconf.d/sysrc b/modules/bsdconf.d/sysrc
--- a/modules/bsdconf.d/sysrc
+++ b/modules/bsdconf.d/sysrc
@@ -13,7 +13,7 @@ EXTHELP="modules/bsdconf.d"
 . ${system}
 
 #defines
-_MYDIR=$( /usr/bin/dirname `${REALPATH_CMD} $0` )
+_MYDIR=$( ${DIRNAME_CMD} `${REALPATH_CMD} $0` )
 
 emulator="jail" # for jname_is_multiple
 jail_list=
@@ -81,16 +81,50 @@ if [ -n "${jail_list}" ]; then
 	err 0 "${N1_COLOR}Multiple sysrc: ${N2_COLOR}done${N0_COLOR}"
 fi
 
-[ -n "${jname}" ] && shift # skip for jname
+ARGS=
 
+# exclude jname= and mode= params from args str
+INIT_IFS="${IFS}"
+IFS="~"
+cmd="$@"
+IFS="${INIT_IFS}"
+ARGS=$( while [ -n "${1}" ]; do
+	IFS="~"
+	strpos --str="${1}" --search="="
+	_pos=$?
+	if [ ${_pos} -eq 0 ]; then
+		# not params=value form
+		#printf "${1} "         # (printf handles -args (with dashes)
+		echo -n "${1} "
+		shift
+		continue
+	fi
+
+	_arg_len=$( strlen ${1} )
+	_pref=$(( _arg_len - _pos ))
+	ARG=$( substr --pos=0 --len=${_pos} --str="${1}" )
+	VAL=$( substr --pos=$(( ${_pos} +2 )) --len=${_pref} --str="${1}" )
+
+	case ${ARG} in
+		fromfile|jname)
+			shift
+			continue
+			;;
+	esac
+
+	printf "${ARG}=${VAL} "
+	shift
+done )
 
 if [ -n "${fromfile}" ]; then
-	shift
-	[ -r "${fromfile}" ] && . ${fromfile}
+	if [ -r "${fromfile}" ]; then
+		. ${fromfile}
+	else
+		err 1 "${N1_COLOR}${CBSD_APP}: unable to open fromfile: ${N2_COLOR}${fromfile}${N0_COLOR}"
+	fi
 fi
 
-cmd="$@"
-[ -z "${cmd}" -a -z "${fromfile}" ] && err 1 "${N1_COLOR}Empty command${N0_COLOR}"
+[ -z "${ARGS}" -a -z "${fromfile}" ] && err 1 "${N1_COLOR}Empty command${N0_COLOR}"
 
 ## MAIN ##
 if [ -n "${jname}" ]; then
@@ -111,7 +145,7 @@ if [ -n "${jname}" ]; then
 		init_kerneldir
 		prepare_jail
 	fi
-	exec_cmd="/usr/sbin/chroot ${path} ${SYSRC_CMD} -f /etc/rc.conf"
+	exec_cmd="${CHROOT_CMD} ${path} ${SYSRC_CMD} -f /etc/rc.conf"
 else
 	data=
 	exec_cmd="${SYSRC_CMD}"
@@ -119,7 +153,7 @@ fi
 
 [ ! -f "${data}/etc/rc.conf" ] && ${TOUCH_CMD} ${data}/etc/rc.conf
 if [ -z "${fromfile}" ];then
-	${exec_cmd} "${cmd}"
+	${exec_cmd} ${ARGS}
 fi
 
 for i in ${sysrc_enable}; do
