WIP: re-work boot order

diff --git a/bhyvectl/bhyve-efivar b/bhyvectl/bhyve-efivar
--- a/bhyvectl/bhyve-efivar
+++ b/bhyvectl/bhyve-efivar
@@ -6,7 +6,7 @@
 CBSDMODULE="bhyve"
 MYDESC="Dialog-based text user interface for manage bhyve UEFI boot order"
 MYARG="jname"
-MYOPTARG="display header human"
+MYOPTARG="display header human quiet"
 ADDHELP="
 ${H3_COLOR}Description${N0_COLOR}:
 
@@ -35,6 +35,7 @@ ${H3_COLOR}See also${N0_COLOR}:
 "
 
 human=1
+quiet=0
 . ${cbsdinit}
 . ${strings}
 
@@ -104,7 +105,13 @@ eval $( ${GREP_CMD} -E -v '(^BootCurrent:)|(^BootOrder:)|(Unreferenced)' ${temp}
 	echo "${_name}=\"${_other}\""
 done )
 
-[ -z "${name_list}" ] && err 1 "${N1_COLOR}${CBSD_APP}: VARS not found: ${N2_COLOR}${VM_VARS}${N0_COLOR}"
+if [ -z "${name_list}" ]; then
+	if [ "${quiet}" = "1" ]; then
+		exit 1
+	else
+		err 1 "${N1_COLOR}${CBSD_APP}: VARS not found: ${N2_COLOR}${VM_VARS}${N0_COLOR}"
+	fi
+fi
 [ -z "${header}" ] && header=1
 sqldelimer=" "
 if [ ${human} -eq 1 ]; then
