switch to cixinit

diff --git a/bhyvectl/bscp b/bhyvectl/bscp
--- a/bhyvectl/bscp
+++ b/bhyvectl/bscp
@@ -1,8 +1,8 @@
 #!/usr/local/bin/cbsd
 #v12.1.3
 CBSDMODULE="bhyve"
-MYARG=""
-MYOPTARG="scp_max_retry verbose"
+CIXARG=""
+CIXOPTARG="scp_max_retry:int verbose:int"
 MYDESC="Copy files from/to VM via scp(1)"
 ADDHELP="
 ${H3_COLOR}Description${N0_COLOR}:
@@ -22,7 +22,6 @@ ${H3_COLOR}Examples${N0_COLOR}:
   # cbsd bscp vm1:install.sh /tmp/install.sh
 
 "
-EXTHELP="wf_jailscp"
 
 # ToDo:
 # Instead of this need one jailscp daemon/services with one lock and which will work on AMQP queue
@@ -36,7 +35,7 @@ EXTHELP="wf_jailscp"
 cloud_api=0
 scp_max_retry=
 oscp_max_retry=
-. ${cbsdinit}
+cixinit
 
 [ -n "${scp_max_retry}" ] && oscp_max_retry="${scp_max_retry}"
 
@@ -83,18 +82,21 @@ bscp()
 			log_err 1 "${N1_COLOR}${CIX_APP}: only one remote path${N0_COLOR}"
 		fi
 		if [ -n "${rfile}" ]; then
-			dst=$( ${BASENAME_CMD} ${rfile} )
+			# basename
+			dst="${rfile##*/}"
 		else
-			dst=$( ${BASENAME_CMD} ${2} )
+			# basename
+			dst="${2##*/}"
 		fi
 		rarg=1
 	else
 		if getjname ${2}; then
 			rarg=2
 			if [ -n "${rfile}" ]; then
-				dst=$( ${BASENAME_CMD} ${rfile} )
+				dst="${rfile##*/}"
 			else
-				dst=$( ${BASENAME_CMD} ${1} )
+				# basename
+				dst="${1##*/}"
 			fi
 		fi
 	fi
@@ -196,83 +198,44 @@ bscp()
 			done
 		done
 		exit 0
-fi
-
-. ${subrdir}/rcconf.subr
-[ $? -eq 1 ] && err 1 "${N1_COLOR}${CIX_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
-[ ${jid} -eq 0 ] && log_err 1 "${N1_COLOR}${CIX_APP}: bhyve not active: ${jname}${N0_COLOR}"
-
-if [ ${rarg} -eq 1 ]; then
-	readconf blogin.conf
-
-	# get first IP
-	# todo: where ipv4_first facts?
-	# todo: v6 ssh/ip
-	OIFS="${IFS}"
-	IFS=","
-	for i in ${ip4_addr}; do
-		first_ip4_addr="${i}"
-		break
-	done
-	IFS="${OIFS}"
-
-	echo "${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${first_ip4_addr}:${rfile} ${2}"
-	dstfile=$( ${BASENAME_CMD} ${2} )
-
-	pass=0
-	ret=0
-	retry=0
-	[ -z "${scp_max_retry}" ] && scp_max_retry="5"
-	while [ ${pass} -ne 1 ]; do
-		${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${first_ip4_addr}:${rfile} ${CIX_PWD}/${dstfile}
-		ret=$?
-		if [ ${ret} -eq 0 ]; then
-			pass=1
-			break
-		else
-			retry=$(( retry + 1 ))
-			[ ${retry} -gt ${scp_max_retry} ] && break
-			echo "[debug] error code: ${ret}, retry ${retry}/${scp_max_retry}: ${scp_exec}" 1>&2
-			sleep 1
-		fi
-	done
-	unset first_ip4_addr
-else
-	# to VM
-	DIR=$( ${DIRNAME_CMD} ${path}${dst} )
-	readconf blogin.conf
-	ret=0
-	prefix=$( substr --pos=0 --len=1 --str="${1}" )
-	if [ "${prefix}" = "/" ]; then
-		# full_path?
-		_source=$( ${REALPATH_CMD} "${1}" 2>/dev/null )
-		ret=$?
-		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such file: ${N2_COLOR}${1}${N0_COLOR}"
-	else
-		_source=$( ${REALPATH_CMD} "${CIX_PWD}/${1}" 2>/dev/null )
-		ret=$?
-		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such file: ${N2_COLOR}${CIX_PWD}/${1}${N0_COLOR}"
 	fi
 
-	# get first IP
-	# todo: where ipv4_first facts?
-	# todo: v6 ssh/ip
-	OIFS="${IFS}"
-	IFS=","
-	for i in ${ip4_addr}; do
-		first_ip4_addr="${i}"
-		break
-	done
-	IFS="${OIFS}"
+	. ${subrdir}/rcconf.subr
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}${CIX_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
+	[ ${jid} -eq 0 ] && log_err 1 "${N1_COLOR}${CIX_APP}: bhyve not active: ${jname}${N0_COLOR}"
 
-	if [ -f ${_source} ]; then
-		echo "${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${first_ip4_addr}:${dst}"
+	if [ ${rarg} -eq 1 ]; then
+		# from VM
+		readconf blogin.conf
+		# get first IP
+		# todo: where ipv4_first facts?
+		# todo: v6 ssh/ip
+		OIFS="${IFS}"
+		IFS=","
+		for i in ${ip4_addr}; do
+			first_ip4_addr="${i}"
+			break
+		done
+		IFS="${OIFS}"
+
+		echo "${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${first_ip4_addr}:${rfile} ${2}"
+
+		prefix=$( substr --pos=0 --len=1 --str=${2} )
+		if [ "${prefix}" = "/" ]; then
+			# real/full path
+			dstfile="${2}"
+		else
+			# basename
+			_res="${2##*/}"
+			dstfile="${CIX_PWD}/${_res}"
+		fi
+
 		pass=0
 		ret=0
 		retry=0
 		[ -z "${scp_max_retry}" ] && scp_max_retry="5"
 		while [ ${pass} -ne 1 ]; do
-			${SCP_CMD} ${quiet} ${bscp_args}  -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${first_ip4_addr}:${dst}
+			${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${first_ip4_addr}:${rfile} ${dstfile}
 			ret=$?
 			if [ ${ret} -eq 0 ]; then
 				pass=1
@@ -284,18 +247,64 @@ else
 				sleep 1
 			fi
 		done
-		ret=$?
-	elif [ -d "${_source}" ]; then
-		echo "DIR"
+		unset first_ip4_addr
+	else
+		# to VM
+		DIR=$( ${DIRNAME_CMD} ${path}${dst} )
+		readconf blogin.conf
+		ret=0
+		prefix=$( substr --pos=0 --len=1 --str="${1}" )
+		if [ "${prefix}" = "/" ]; then
+			# full_path?
+			_source=$( ${REALPATH_CMD} "${1}" 2>/dev/null )
+			ret=$?
+			[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such file: ${N2_COLOR}${1}${N0_COLOR}"
+		else
+			_source=$( ${REALPATH_CMD} "${CIX_PWD}/${1}" 2>/dev/null )
+			ret=$?
+			[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such file: ${N2_COLOR}${CIX_PWD}/${1}${N0_COLOR}"
+		fi
+
+		# get first IP
+		# todo: where ipv4_first facts?
+		# todo: v6 ssh/ip
+		OIFS="${IFS}"
+		IFS=","
+		for i in ${ip4_addr}; do
+			first_ip4_addr="${i}"
+			break
+		done
+		IFS="${OIFS}"
+
+		if [ -f ${_source} ]; then
+			echo "${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${first_ip4_addr}:${dst}"
+			pass=0
+			ret=0
+			retry=0
+			[ -z "${scp_max_retry}" ] && scp_max_retry="5"
+			while [ ${pass} -ne 1 ]; do
+				${SCP_CMD} ${quiet} ${bscp_args}  -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${first_ip4_addr}:${dst}
+				ret=$?
+				if [ ${ret} -eq 0 ]; then
+					pass=1
+					break
+				else
+					retry=$(( retry + 1 ))
+					[ ${retry} -gt ${scp_max_retry} ] && break
+					echo "[debug] error code: ${ret}, retry ${retry}/${scp_max_retry}: ${scp_exec}" 1>&2
+					sleep 1
+				fi
+			done
+			ret=$?
+		elif [ -d "${_source}" ]; then
+			echo "DIR"
+		fi
+
+		unset first_ip4_addr
 	fi
 
-	unset first_ip4_addr
-fi
-
-exit ${ret}
-
+	exit ${ret}
 }
-
 
 ### MAIN ###
 # change current dir
@@ -310,13 +319,7 @@ fi
 [ -z "${*}" ] && err 1 "${N1_COLOR}${CIX_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ]${N0_COLOR}"
 
 ARGS=
-for i in $*; do
-	prefix8=$( substr --pos=0 --len=8 --str="${i}" )
-	prefix14=$( substr --pos=0 --len=14 --str="${i}" )
-
-	[ "${prefix8}" = "verbose=" ] && shift && continue
-	[ "${prefix14}" = "scp_max_retry=" ] && shift && continue
-
+for i in ${CIX_OTHER_ARGS}; do
 	if [ -z "${ARGS}" ]; then
 		ARGS="${i}"
 	else
