migrate to dash, WIP

diff --git a/bhyvectl/bscp b/bhyvectl/bscp
--- a/bhyvectl/bscp
+++ b/bhyvectl/bscp
@@ -58,20 +58,20 @@ try_remote()
 
 	node=$( jwhereis ${jname} )
 
-	[ -z "${node}" ] && log_err 1 "${CBSD_APP}: node not found for jail ${jname}"
+	[ -z "${node}" ] && log_err 1 "${CIX_APP}: node not found for jail ${jname}"
 
-	cbsdlogger NOTICE ${CBSD_APP}: try to get remote jstatus for ${jname} on ${node}
+	cbsdlogger NOTICE ${CIX_APP}: try to get remote jstatus for ${jname} on ${node}
 	status=$( rexe node=${node} cbsd jstatus ${jname} )
-	[ "${status}" = "0" ] && log_err 1 "${CBSD_APP}: jail ${jname} not running on ${node}"
+	[ "${status}" = "0" ] && log_err 1 "${CIX_APP}: jail ${jname} not running on ${node}"
 	sqlfile="${node}"
 	. ${subrdir}/rcconf.subr
 	[ "${baserw}" = "1" ] && path=${data}
-	[ -z "${path}" ] && log_err 1 "${CBSD_APP}: path not found"
+	[ -z "${path}" ] && log_err 1 "${CIX_APP}: path not found"
 }
 
 bscp()
 {
-	[ $# -ne 2 ] && err 1 "${N1_COLOR}${CBSD_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ] ( $ARGS) ${N0_COLOR}"
+	[ $# -ne 2 ] && err 1 "${N1_COLOR}${CIX_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ] ( $ARGS) ${N0_COLOR}"
 
 	jname=
 	rfile=
@@ -80,7 +80,7 @@ bscp()
 
 	if getjname ${1}; then
 		if getjname ${2}; then
-			log_err 1 "${N1_COLOR}${CBSD_APP}: only one remote path${N0_COLOR}"
+			log_err 1 "${N1_COLOR}${CIX_APP}: only one remote path${N0_COLOR}"
 		fi
 		if [ -n "${rfile}" ]; then
 			dst=$( ${BASENAME_CMD} ${rfile} )
@@ -99,11 +99,11 @@ bscp()
 		fi
 	fi
 
-	[ -z "${jname}" -o -z "${dst}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: jail path via jail: path records not determine${N0_COLOR}"
+	[ -z "${jname}" -o -z "${dst}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: jail path via jail: path records not determine${N0_COLOR}"
 
-	validate_jname "${jname}" || log_err 1 "${N1_COLOR}${CBSD_APP}: bad jname: ${jname}${N0_COLOR}"
+	validate_jname "${jname}" || log_err 1 "${N1_COLOR}${CIX_APP}: bad jname: ${jname}${N0_COLOR}"
 
-	Makefile="${CBSD_PWD}/CBSDfile"
+	Makefile="${CIX_PWD}/CBSDfile"
 	if [ -r "${Makefile}" ]; then
 		[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 		. ${Makefile}
@@ -130,13 +130,13 @@ bscp()
 				break
 			fi
 		done
-		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such bhyve: ${N2_COLOR}${jname}${N0_COLOR}"
+		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such bhyve: ${N2_COLOR}${jname}${N0_COLOR}"
 
 		for _jname in ${all_bhyve_list}; do
 			_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${_jname} 2>&1 )
 			_ret=$?
 			if [ ${_ret} -ne 0 ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
 				${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
 				continue
 			fi
@@ -145,7 +145,7 @@ bscp()
 			_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh_string}" )
 
 			if [ "${_ssh_pref}" != "ssh" ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
 				${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
 				continue
 			fi
@@ -199,8 +199,8 @@ bscp()
 fi
 
 . ${subrdir}/rcconf.subr
-[ $? -eq 1 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
-[ ${jid} -eq 0 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: bhyve not active: ${jname}${N0_COLOR}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}${CIX_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
+[ ${jid} -eq 0 ] && log_err 1 "${N1_COLOR}${CIX_APP}: bhyve not active: ${jname}${N0_COLOR}"
 
 if [ ${rarg} -eq 1 ]; then
 	readconf blogin.conf
@@ -224,7 +224,7 @@ if [ ${rarg} -eq 1 ]; then
 	retry=0
 	[ -z "${scp_max_retry}" ] && scp_max_retry="5"
 	while [ ${pass} -ne 1 ]; do
-		${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${first_ip4_addr}:${rfile} ${CBSD_PWD}/${dstfile}
+		${SCP_CMD} ${quiet} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${first_ip4_addr}:${rfile} ${CIX_PWD}/${dstfile}
 		ret=$?
 		if [ ${ret} -eq 0 ]; then
 			pass=1
@@ -247,11 +247,11 @@ else
 		# full_path?
 		_source=$( ${REALPATH_CMD} "${1}" 2>/dev/null )
 		ret=$?
-		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such file: ${N2_COLOR}${1}${N0_COLOR}"
+		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such file: ${N2_COLOR}${1}${N0_COLOR}"
 	else
-		_source=$( ${REALPATH_CMD} "${CBSD_PWD}/${1}" 2>/dev/null )
+		_source=$( ${REALPATH_CMD} "${CIX_PWD}/${1}" 2>/dev/null )
 		ret=$?
-		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such file: ${N2_COLOR}${CBSD_PWD}/${1}${N0_COLOR}"
+		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such file: ${N2_COLOR}${CIX_PWD}/${1}${N0_COLOR}"
 	fi
 
 	# get first IP
@@ -299,7 +299,7 @@ exit ${ret}
 
 ### MAIN ###
 # change current dir
-cd ${CBSD_PWD}
+cd ${CIX_PWD}
 
 if [ "${verbose}" = "0" ]; then
 	quiet="-q"
@@ -307,7 +307,7 @@ else
 	quiet=
 fi
 
-[ -z "${*}" ] && err 1 "${N1_COLOR}${CBSD_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ]${N0_COLOR}"
+[ -z "${*}" ] && err 1 "${N1_COLOR}${CIX_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ]${N0_COLOR}"
 
 ARGS=
 for i in $*; do
@@ -326,7 +326,7 @@ for i in $*; do
 	args_num=$(( args_num + 1 ))
 done
 
-[ ${args_num} -ne 2 ] && err 1 "${N1_COLOR}${CBSD_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ] ( $ARGS) ${N0_COLOR}"
+[ ${args_num} -ne 2 ] && err 1 "${N1_COLOR}${CIX_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ] ( $ARGS) ${N0_COLOR}"
 
 bscp ${ARGS}
 
diff --git a/jailctl/j2prepare b/jailctl/j2prepare
--- a/jailctl/j2prepare
+++ b/jailctl/j2prepare
@@ -115,12 +115,12 @@ REMOTE_JAIL_FSTAB_DIR="jails-fstab/${jname}"
 
 # Update Redis
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-	cbsdredis publish cbsd_events '{"cmd":"'${CBSD_APP}'", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":1}'
+	cbsdredis publish cbsd_events '{"cmd":"'${CIX_APP}'", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":1}'
 fi
 
 not_sharedfs_action()
 {
-	cbsdlogger NOTICE ${CBSD_APP}: generate secrets for ${jname}
+	cbsdlogger NOTICE ${CIX_APP}: generate secrets for ${jname}
 	jgensecrets jname=${jname} mode=force > ${DEBLOG} 2>&1
 	dot "jgensecrets"
 
@@ -133,10 +133,10 @@ not_sharedfs_action()
 
 	SSHOP="-oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=5 -q -oPort=${myport} -i ${mykey} ${myip}"
 
-	cbsdlogger NOTICE ${CBSD_APP}: register secrets for ${jname} on remote node: ${node}
+	cbsdlogger NOTICE ${CIX_APP}: register secrets for ${jname} on remote node: ${node}
 	rexe node=${node} tryoffline=${tryoffline} /usr/local/bin/cbsd secretsfile jname=${jname} mode=off > ${DEBLOG} 2>&1
 	dot "rexe_1"
-	cbsdlogger NOTICE ${CBSD_APP}: copy secrets for ${jname} to remote node: ${node}
+	cbsdlogger NOTICE ${CIX_APP}: copy secrets for ${jname} to remote node: ${node}
 	nodescp tryoffline=${tryoffline} ${SECFILE} ${node}:etc > ${DEBLOG} 2>&1
 	dot "scp_secfile"
 
@@ -150,7 +150,7 @@ not_sharedfs_action()
 		${DU_CMD} -sh ${tmpdir}/${jname}-sysdata.tgz
 	fi
 
-	cbsdlogger NOTICE ${CBSD_APP}: copy sysdata for ${jname} to ${node}
+	cbsdlogger NOTICE ${CIX_APP}: copy sysdata for ${jname} to ${node}
 	nodescp tryoffline=${tryoffline} ${tmpdir}/${jname}-sysdata.tgz ${node}:jails-system > ${DEBLOG} 2>&1
 	dot "scp_sysdata"
 	# sysdata
@@ -166,7 +166,7 @@ not_sharedfs_action()
 			${DU_CMD} -sh ${tmpdir}/${jname}-data.tgz
 		fi
 
-		cbsdlogger NOTICE ${CBSD_APP}: copy data for ${jname} to ${node}
+		cbsdlogger NOTICE ${CIX_APP}: copy data for ${jname} to ${node}
 		nodescp tryoffline=${tryoffline} ${tmpdir}/${jname}-data.tgz ${node}:jails-system > ${DEBLOG} 2>&1
 		dot "scp_data"
 	fi
@@ -176,54 +176,54 @@ not_sharedfs_action()
 	dot "rexe_2"
 	RDIR="${jname}-data"
 	if [ "${mkdatadir}" = "1" ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: create datadir for ${jname} on ${node}
+		cbsdlogger NOTICE ${CIX_APP}: create datadir for ${jname} on ${node}
 		rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd mkdatadir jname=${jname} > ${DEBLOG} 2>&1
 		dot "rexe_mkdatadir"
 	fi
 
 	# Legacy/old fstab location, < CBSD 12.1.5
 	if [ -r ${JAIL_FSTAB_LEGACY} ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: copy fstabs for ${jname} to ${node}
+		cbsdlogger NOTICE ${CIX_APP}: copy fstabs for ${jname} to ${node}
 		nodescp tryoffline=${tryoffline} ${JAIL_FSTAB_LEGACY} ${node}:${REMOTE_FSTAB_LEGACY} > ${DEBLOG} 2>&1
 		dot "scp legacy fstab"
 
-		cbsdlogger NOTICE ${CBSD_APP}: replacewdir for ${jname} fstab on ${node}
+		cbsdlogger NOTICE ${CIX_APP}: replacewdir for ${jname} fstab on ${node}
 		rexe tryoffline=${tryoffline} node=${node} cbsd replacewdir old=${workdir} file0=${REMOTE_FSTAB_LEGACY} > ${DEBLOG} 2>&1
 		dot "rexe_fstab_legacy"
 	fi
 	# Legacy/old fstab.local location, < CBSD 12.1.5
 	if [ -r ${JAIL_FSTAB_LEGACY}.local ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: copy local fstabs for ${jname} to ${node}
+		cbsdlogger NOTICE ${CIX_APP}: copy local fstabs for ${jname} to ${node}
 		nodescp tryoffline=${tryoffline} ${JAIL_FSTAB_LEGACY}.local ${node}:${REMOTE_FSTAB_LEGACY}.local > ${DEBLOG} 2>&1
 		dot "scp legacy local fstab"
 
-		cbsdlogger NOTICE ${CBSD_APP}: replacewdir for ${jname} fstab.local on ${node}
+		cbsdlogger NOTICE ${CIX_APP}: replacewdir for ${jname} fstab.local on ${node}
 		rexe tryoffline=${tryoffline} node=${node} cbsd replacewdir old=${workdir} file0=${REMOTE_FSTAB_LEGACY}.local > ${DEBLOG} 2>&1
 		dot "rexe_fstab_legacy_local"
 	fi
 
 	# New fstab location, > CBSD 12.1.5
 	if [ -r ${JAIL_FSTAB_DIR}/fstab ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: copy fstabs for ${jname} to ${node}
+		cbsdlogger NOTICE ${CIX_APP}: copy fstabs for ${jname} to ${node}
 		nodescp tryoffline=${tryoffline} ${JAIL_FSTAB_DIR}/fstab ${node}:${REMOTE_JAIL_FSTAB_DIR}/fstab > ${DEBLOG} 2>&1
 		dot "scp fstab"
 
-		cbsdlogger NOTICE ${CBSD_APP}: replacewdir for ${jname} fstab on ${node}
+		cbsdlogger NOTICE ${CIX_APP}: replacewdir for ${jname} fstab on ${node}
 		rexe tryoffline=${tryoffline} node=${node} cbsd replacewdir old=${workdir} file0=${REMOTE_JAIL_FSTAB_DIR}/fstab > ${DEBLOG} 2>&1
 		dot "rexe_fstab"
 	fi
 	# New fstab location, > CBSD 12.1.5
 	if [ -r ${JAIL_FSTAB_DIR}.local ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: copy local fstabs for ${jname} to ${node}
+		cbsdlogger NOTICE ${CIX_APP}: copy local fstabs for ${jname} to ${node}
 		nodescp tryoffline=${tryoffline} ${JAIL_FSTAB_DIR}.local ${node}:${JAIL_FSTAB_DIR}.local > ${DEBLOG} 2>&1
 		dot "scp fstab"
 
-		cbsdlogger NOTICE ${CBSD_APP}: replacewdir for ${jname} fstab.local on ${node}
+		cbsdlogger NOTICE ${CIX_APP}: replacewdir for ${jname} fstab.local on ${node}
 		rexe tryoffline=${tryoffline} node=${node} cbsd replacewdir old=${workdir} file0=${JAIL_FSTAB_DIR}.local > ${DEBLOG} 2>&1
 		dot "rexe_fstab_local"
 	fi
 
-	cbsdlogger NOTICE ${CBSD_APP}: extract sysdata for ${jname} on ${node}
+	cbsdlogger NOTICE ${CIX_APP}: extract sysdata for ${jname} on ${node}
 	rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd imgpart mode=extract jname=jails-system/${jname}-sysdata.tgz part=sysdata out=jails-system > ${DEBLOG} 2>&1
 	dot "rexe_img_extract_sysdata"
 
@@ -231,7 +231,7 @@ not_sharedfs_action()
 	dot "rexe_rm-f-sysdata"
 
 	if [ "${scpdata}" = "1" ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: extract data for ${jname} on ${node}
+		cbsdlogger NOTICE ${CIX_APP}: extract data for ${jname} on ${node}
 		rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd imgpart mode=extract jname=jails-system/${jname}-data.tgz part=data out=jails-data > ${DEBLOG} 2>&1
 		dot "rexe_img_extract_data"
 
@@ -242,31 +242,31 @@ not_sharedfs_action()
 
 printf "   ${H5_COLOR}* ${N1_COLOR}check for remote CBSD version: ${N0_COLOR}"
 # todo: we can get this version from the nodes database (from retrinv task)
-d_cbsd_ver=$( rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version 2>/dev/null | ${TR_CMD} -d \\r | ${AWK_CMD} '/./{print $1}' )
-[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: failed: tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version${N0_COLOR}"
-[ -z "${d_cbsd_ver}" ] && err 1 "${N1_COLOR}${CBSD_APP}: failed: cbsd rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version${N0_COLOR}"
+d_cbsd_ver=$( rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd version 2>/dev/null | ${TR_CMD} -d \\r | ${AWK_CMD} '/./{print $1}' )
+[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: failed: tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd version${N0_COLOR}"
+[ -z "${d_cbsd_ver}" ] && err 1 "${N1_COLOR}${CIX_APP}: failed: cbsd rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd version${N0_COLOR}"
 printf "${H3_COLOR}${d_cbsd_ver}${N0_COLOR}"
 echo
 s_cbsd_ver=$( version | ${AWK_CMD} '/./{print $1}' )
 
-[ "${s_cbsd_ver}" != "${d_cbsd_ver}" ] && err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}local CBSD version not equal: ${s_cbsd_ver} != ${d_cbsd_ver}${N0_COLOR}"
+[ "${s_cbsd_ver}" != "${d_cbsd_ver}" ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}local CBSD version not equal: ${s_cbsd_ver} != ${d_cbsd_ver}${N0_COLOR}"
 
 if [ ${sharedfs} -eq 0 ]; then
-	cbsdlogger NOTICE ${CBSD_APP}: not shared fs with ${node}, perform not_sharedfs_action
+	cbsdlogger NOTICE ${CIX_APP}: not shared fs with ${node}, perform not_sharedfs_action
 	not_sharedfs_action
 fi
 
 jmkrcconf jname=${jname} > ${JAIL_RCCONF}
-cbsdlogger NOTICE ${CBSD_APP}: copy rcconf for ${jname} to ${node}
+cbsdlogger NOTICE ${CIX_APP}: copy rcconf for ${jname} to ${node}
 nodescp tryoffline=${tryoffline} ${JAIL_RCCONF} ${node}:${REMOTE_JAIL_RCCONF} > ${DEBLOG} 2>&1
 dot "scp rcconf"
 ${RM_CMD} -f ${JAIL_RCCONF}
 
-cbsdlogger NOTICE ${CBSD_APP}: jrsyncconf for ${jname} on ${node}
+cbsdlogger NOTICE ${CIX_APP}: jrsyncconf for ${jname} on ${node}
 rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd jrsyncconf jname=${jname} > ${DEBLOG} 2>&1
 dot "rexe_jrsyncconf"
 
-cbsdlogger NOTICE ${CBSD_APP}: replacewdir for ${jname} on ${node}
+cbsdlogger NOTICE ${CIX_APP}: replacewdir for ${jname} on ${node}
 rexe tryoffline=${tryoffline} node=${node} cbsd replacewdir old=${workdir} file0=jails-rcconf/rc.conf_${jname} > ${DEBLOG} 2>&1
 dot "rexe_4"
 
@@ -274,7 +274,7 @@ dot "rexe_4"
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
 	end_time=$( ${DATE_CMD} +%s )
 	diff_time=$(( end_time - st_time ))
-	cbsdredis publish cbsd_events '{"cmd":"'${CBSD_APP}'", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":0, "duration":'${diff_time}'}'
+	cbsdredis publish cbsd_events '{"cmd":"'${CIX_APP}'", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":0, "duration":'${diff_time}'}'
 fi
 
 err 0 "${N2_COLOR}ok${N0_COLOR}"
diff --git a/modules/bsdconf.d/sysrc b/modules/bsdconf.d/sysrc
--- a/modules/bsdconf.d/sysrc
+++ b/modules/bsdconf.d/sysrc
@@ -89,13 +89,13 @@ if [ -z "${jname}" -a -n "${ojname}" ]; then
 fi
 
 # check for cloud function when CBSDfile exist
-Makefile="${CBSD_PWD}/CBSDfile"
+Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" ]; then
 	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 	. ${Makefile}
 
 	all_jail_list=$( ${GREP_CMD} -E '^jail_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#jail_##g )
-	[ -z "${all_jail_list}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no jail found${N0_COLOR}"
+	[ -z "${all_jail_list}" ] && err 1 "${N1_COLOR}${CIX_APP}: no jail found${N0_COLOR}"
 
 	if [ -n "${jname}" ]; then
 		found=0
@@ -105,7 +105,7 @@ if [ -r "${Makefile}" ]; then
 				break
 			fi
 		done
-		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 		all_jail_list="${jname}"
 	fi
 
@@ -194,13 +194,13 @@ if [ ${cbsd_api} -eq 1 ]; then
 		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${jname} 2>&1 )
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
 			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			continue
 		fi
 		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh}" )
 		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
 			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			continue
 		fi
@@ -218,7 +218,7 @@ if [ ${cbsd_api} -eq 1 ]; then
 			fi
 		fi
 		jexec_cmd="${SSH_CMD} -tt -oStrictHostKeyChecking=no -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_post}"
-		exec_cmd="/usr/local/cbsd/misc/cbsdsysrc ${ARGS}"
+		exec_cmd="${CIX_DISTDIR}/misc/cbsdsysrc ${ARGS}"
 		echo "[debug] exec $jname: $jexec_cmd ${exec_cmd}"
 		${jexec_cmd} ${exec_cmd}
 	done
@@ -229,7 +229,7 @@ if [ -n "${fromfile}" ]; then
 	if [ -r "${fromfile}" ]; then
 		. ${fromfile}
 	else
-		err 1 "${N1_COLOR}${CBSD_APP}: unable to open fromfile: ${N2_COLOR}${fromfile}${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP}: unable to open fromfile: ${N2_COLOR}${fromfile}${N0_COLOR}"
 	fi
 fi
 
@@ -238,13 +238,13 @@ fi
 ## MAIN ##
 if [ -n "${jname}" ]; then
 	. ${subrdir}/rcconf.subr
-	[ $? -eq 1 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}${CIX_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
-	[ ! -d ${data}/etc ] && err 1 "${N1_COLOR}${CBSD_APP}: no such /etc directory in jail: ${N2_COLOR}${jname}${N0_COLOR}"
-	exec_cmd="/usr/local/cbsd/misc/cbsdsysrc -qf ${data}/etc/rc.conf"
+	[ ! -d ${data}/etc ] && err 1 "${N1_COLOR}${CIX_APP}: no such /etc directory in jail: ${N2_COLOR}${jname}${N0_COLOR}"
+	exec_cmd="${CIX_DISTDIR}/misc/cbsdsysrc -qf ${data}/etc/rc.conf"
 else
 	data=
-	exec_cmd="/usr/local/cbsd/misc/cbsdsysrc"
+	exec_cmd="${CIX_DISTDIR}/misc/cbsdsysrc"
 fi
 
 [ ! -f "${data}/etc/rc.conf" ] && ${TOUCH_CMD} ${data}/etc/rc.conf
diff --git a/sudoexec/bstart b/sudoexec/bstart
--- a/sudoexec/bstart
+++ b/sudoexec/bstart
@@ -71,7 +71,7 @@ readconf bhyve-default-default.conf
 jname=
 
 # check for cloud function when CBSDfile exist
-Makefile="${CBSD_PWD}/CBSDfile"
+Makefile="${CIX_PWD}/CBSDfile"
 if [ ! -r "${Makefile}" ]; then
 	[ -z "${1}" ] && select_jail_by_list -s "List of offline VMs" -a "Off" -e bls -r ${sqlreplica}
 fi
@@ -127,7 +127,7 @@ if [ -r "${Makefile}" ]; then
 						ojname="${ojname} ${i}"
 					fi
 				else
-					${ECHO} "${N1_COLOR}${CBSD_APP}: env absent in CBSDfile: ${N2_COLOR}${i}${N0_COLOR}" 1>&2
+					${ECHO} "${N1_COLOR}${CIX_APP}: env absent in CBSDfile: ${N2_COLOR}${i}${N0_COLOR}" 1>&2
 				fi
 			fi
 		done
@@ -140,7 +140,7 @@ if [ -r "${Makefile}" ]; then
 
 	unset ojname jname
 
-	[ -z "${bhyve_list}" ] && err 1 "${N1_COLOR}${CBSD_APP}: give me jname${N0_COLOR}"
+	[ -z "${bhyve_list}" ] && err 1 "${N1_COLOR}${CIX_APP}: give me jname${N0_COLOR}"
 
 	# multiple?
 	strpos --str="${jname}" --search=" "
@@ -233,7 +233,7 @@ start_bhyve()
 
 	if [ -n "${extra_profile_dir}" ]; then
 		if [ ! -d "${extra_profile_dir}" ]; then
-			[ ${quiet} -ne 1 ] && ${ECHO} "${W1_COLOR}${CBSD_APP} warning: ${N1_COLOR}no such extra_profile_dir: ${N2_COLOR}${extra_profile_dir}${N0_COLOR}" >&2
+			[ ${quiet} -ne 1 ] && ${ECHO} "${W1_COLOR}${CIX_APP} warning: ${N1_COLOR}no such extra_profile_dir: ${N2_COLOR}${extra_profile_dir}${N0_COLOR}" >&2
 		else
 			[ -r ${extra_profile_dir}/vm-${vm_os_type}-${vm_os_profile}.conf ] && . ${extra_profile_dir}/vm-${vm_os_type}-${vm_os_profile}.conf
 		fi
@@ -341,7 +341,7 @@ start_bhyve()
 							${ZFS_CMD} destroy ${_dsk_source_zvol}
 							#${ZFS_CMD} clone ${_cloud_source_zvol}@boot-${jname} ${_dsk_source_zvol}
 							${ZFS_CMD} clone -o volsize=${_dsk_ebytes} ${_cloud_source_zvol}@boot-${jname} ${_dsk_source_zvol}
-							cbsdlogger NOTICE ${CBSD_APP}: zfs clone method cloud image: gpart commit zvol/${_dsk_source_zvol}
+							cbsdlogger NOTICE ${CIX_APP}: zfs clone method cloud image: gpart commit zvol/${_dsk_source_zvol}
 							${GPART_CMD} commit zvol/${_dsk_source_zvol}
 							# restore original size
 							# ${ZFS_CMD} set volsize=${_dsk_ebytes} ${_dsk_source_zvol}
@@ -426,7 +426,7 @@ start_bhyve()
 							${ZFS_CMD} destroy ${_dsk_source_zvol}
 							#${ZFS_CMD} clone ${_cloud_source_zvol}@boot-${jname} ${_dsk_source_zvol}
 							${ZFS_CMD} clone -o volsize=${_dsk_ebytes} ${_cloud_source_zvol}@boot-${jname} ${_dsk_source_zvol}
-							cbsdlogger NOTICE ${CBSD_APP}: zfs clone method cloud image: gpart commit zvol/${_dsk_source_zvol}
+							cbsdlogger NOTICE ${CIX_APP}: zfs clone method cloud image: gpart commit zvol/${_dsk_source_zvol}
 							${GPART_CMD} commit zvol/${_dsk_source_zvol}
 							# restore original size
 							# ${ZFS_CMD} set volsize=${_dsk_ebytes} ${_dsk_source_zvol}
@@ -713,7 +713,7 @@ start_bhyve()
 	if [ -n "${_res}" ]; then
 		cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT pcislot_name,pcislot_desc FROM pcibus WHERE modified=false 2>/dev/null | while read _name _desc; do
 			# debug: echo "Prune for: [${_name} ${_desc}]"
-			cbsdlogger NOTICE ${CBSD_APP}: pcibus map: purge for old/orphaned devices for ${jname}: [${_name} ${_desc}]
+			cbsdlogger NOTICE ${CIX_APP}: pcibus map: purge for old/orphaned devices for ${jname}: [${_name} ${_desc}]
 		done
 		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite DELETE FROM pcibus WHERE modified=false
 	fi
@@ -827,8 +827,8 @@ nic_address_cmd='${nic_address_cmd}'
 bhyverun_wrapper='${bhyverun_wrapper}'
 EOF
 
-	[ -z "${bhyverun_wrapper}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: empty mandatory param: ${N2_COLOR}bhyverun_wrapper${N0_COLOR}"
-	[ ! -r "${bhyverun_wrapper}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such bhyverun_wrapper script: ${N2_COLOR}${bhyverun_wrapper}${N0_COLOR}"
+	[ -z "${bhyverun_wrapper}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: empty mandatory param: ${N2_COLOR}bhyverun_wrapper${N0_COLOR}"
+	[ ! -r "${bhyverun_wrapper}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: no such bhyverun_wrapper script: ${N2_COLOR}${bhyverun_wrapper}${N0_COLOR}"
 
 	# export all tap bridges
 	for i in ${mytap}; do
@@ -839,20 +839,20 @@ EOF
 		# mytap_vale1:files3_members: name contains characters not allowed in shell
 		# cast ':' to '_' ?
 		i=$( echo ${i} | ${TR_CMD} ":" "_" )
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/bhyve.conf mytap_${i}_members="${T}" >/dev/null
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/bhyve.conf mytap_${i}_members="${T}" >/dev/null
 	done
 
 	# export all dsk path as dsk_X_path
 	_dsk_id=0
 	for i in ${mydsk}; do
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/bhyve.conf dsk_${_dsk_id}_path="${i}" >/dev/null
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/bhyve.conf dsk_${_dsk_id}_path="${i}" >/dev/null
 		_dsk_id=$(( _dsk_id + 1 ))
 	done
 
 	# export all cd path as cd_X_path
 	_dsk_id=0
 	for i in ${mycd}; do
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/bhyve.conf cd_${_dsk_id}_path="${i}" >/dev/null
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${jailsysdir}/${jname}/bhyve.conf cd_${_dsk_id}_path="${i}" >/dev/null
 		_dsk_id=$(( _dsk_id + 1 ))
 	done
 
@@ -909,7 +909,7 @@ EOF
 					zvol_dsk0_dev=$( ${MDCONFIG_CMD} -a -t vnode -f ${data}/dsk1.vhd )
 					_ret=$?
 					if [ ${_ret} -ne 0 ]; then
-						err 1 "${N1_COLOR}${CBSD_APP}: homeass cloud-init: error: ${N2_COLOR}${MDCONFIG_CMD} -a -t vnode -f ${data}/dsk1.vhd${N0_COLOR}"
+						err 1 "${N1_COLOR}${CIX_APP}: homeass cloud-init: error: ${N2_COLOR}${MDCONFIG_CMD} -a -t vnode -f ${data}/dsk1.vhd${N0_COLOR}"
 					fi
 					${GPART_CMD} recover ${zvol_dsk0_dev}
 					zvol_dsk0_dev="/dev/${zvol_dsk0_dev}"
@@ -919,7 +919,7 @@ EOF
 				${MOUNT_CMD} -t msdosfs -o rw ${zvol_dsk0_dev}p1 ${mount_dir}
 				_ret=$?
 				if [ ${_ret} -ne 0 ]; then
-					err 1 "${N1_COLOR}${CBSD_APP}: homeass cloud-init: error: ${N2_COLOR}${MOUNT_CMD} -t msdosfs -o rw ${zvol_dsk0_dev}p1 ${mount_dir}${N0_COLOR}"
+					err 1 "${N1_COLOR}${CIX_APP}: homeass cloud-init: error: ${N2_COLOR}${MOUNT_CMD} -t msdosfs -o rw ${zvol_dsk0_dev}p1 ${mount_dir}${N0_COLOR}"
 				fi
 				${MKDIR_CMD} -p ${mount_dir}/CONFIG/network
 				${CP_CMD} -a ${jailsysdir}/${jname}/cloud-init/* ${mount_dir}/CONFIG/network/
@@ -947,7 +947,7 @@ EOF
 					else
 						GENISOIMAGE_CMD=$( which makefs )
 					fi
-					[ ! -x "${GENISOIMAGE_CMD}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no such makefs${N0_COLOR}"
+					[ ! -x "${GENISOIMAGE_CMD}" ] && err 1 "${N1_COLOR}${CIX_APP}: no such makefs${N0_COLOR}"
 
 					case "${ci_template}" in
 						*)
@@ -1101,7 +1101,7 @@ done
 
 # this is multiple list, split it by parallel jstart execution
 if [ ${jail_num} -gt 1 ]; then
-	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple starting: ${JLIST}
+	cbsdlogger NOTICE ${CIX_APP}: executing for multiple starting: ${JLIST}
 	# multiple astart always non interactive
 	export inter=0
 
@@ -1156,8 +1156,8 @@ if [ ${jail_num} -gt 1 ]; then
 	end_time=$( ${DATE_CMD} +%s )
 	diff_time=$(( end_time - st_time ))
 	diff_time=$( displaytime ${diff_time} )
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
-	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple done in ${diff_time}: ${JLIST}
+	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CIX_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
+	cbsdlogger NOTICE ${CIX_APP}: executing for multiple done in ${diff_time}: ${JLIST}
 	err 0 "${N1_COLOR}Multiple bstart: ${N2_COLOR}done${N0_COLOR}"
 fi
 
@@ -1194,7 +1194,7 @@ if [ "${lm}" = "0" ]; then
 	# mainly to smooth mass start in astart.
 	[ -n "${odelay}" ] && delay="${odelay}"
 	if [ ${delay} -ne 0 ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: delayed boot for ${jname} via delay= params: ${delay} sec.
+		cbsdlogger NOTICE ${CIX_APP}: delayed boot for ${jname} via delay= params: ${delay} sec.
 		sleep ${delay}
 	fi
 
@@ -1288,7 +1288,7 @@ fi
 _secured=
 _jailed=0
 _chrooted=0
-#[ "${_jailed}" = "${_chrooted}" -a "${_jailed}" = "1" ] && err 1 "${N1_COLOR}${CBSD_APP}: chrooted=1 and jailed=1 is mutually exclusive. There can be only one${N2_COLOR}"
+#[ "${_jailed}" = "${_chrooted}" -a "${_jailed}" = "1" ] && err 1 "${N1_COLOR}${CIX_APP}: chrooted=1 and jailed=1 is mutually exclusive. There can be only one${N2_COLOR}"
 
 #[ "${_jailed}" != "0" ] && _secured="jail"
 #[ "${_chrooted}" != "0" ] && _secured="chroot"
@@ -1298,7 +1298,7 @@ if [ -n "${_secured}" ]; then
 	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${_secured}ed bhyve. create temporary jail: ${N2_COLOR}${_jname}${N0_COLOR}"
 	${SED_CMD} -e "s:%%jname%%:${_jname}:g" \
 	-e "s:%%workdir%%:${workdir}:g" \
-	-e "s:%%domain%%#:my.domain:g" ${distdir}/share/jail.jconf > ${tmpdir}/jail.$$
+	-e "s:%%domain%%#:my.domain:g" ${CIX_DISTDIR}/share/jail.jconf > ${tmpdir}/jail.$$
 	jcreate jconf=${tmpdir}/jail.$$
 	${RM_CMD} -f ${tmpdir}/jail.$$
 	exec b${_secured} jname=${_jname} bname=${jname}
@@ -1404,7 +1404,7 @@ if [ "${lm}" = "0" ]; then
 fi
 
 if [ "${tpm}" = "new" ]; then
-	[ -z "${SWTPM_CMD}" ] && err 1 "${N1_COLOR}${CBSD_APP}tpm=new requires swtpm package, please install it and re-run cbsd initenv: ${N2_COLOR}pkg install -y swtpm; cbsd initenv${N0_COLOR}"
+	[ -z "${SWTPM_CMD}" ] && err 1 "${N1_COLOR}${CIX_APP}tpm=new requires swtpm package, please install it and re-run cbsd initenv: ${N2_COLOR}pkg install -y swtpm; cbsd initenv${N0_COLOR}"
 	[ "${quiet}" != "1" ] && ${ECHO} "${N1_COLOR}TPM2: launch swtpm daemon: ${N2_COLOR}${jailsysdir}/${jname}/tpm${N0_COLOR}"
 	/usr/local/cbsd/misc/swtpm -a start -b ${SWTPM_CMD} -d ${jailsysdir}/${jname}/tpm -e error -p swtpm.pid -l tpm.log -v 20 -u swtpm-sock -s mystate
 fi
@@ -1419,12 +1419,12 @@ diff_time=$(( end_time - st_time ))
 diff_time=$( displaytime ${diff_time} )
 
 if [ "${lm}" = "0" ]; then
-	cbsdlogger NOTICE ${CBSD_APP}: bhyve domain ${jname} started in ${diff_time}
+	cbsdlogger NOTICE ${CIX_APP}: bhyve domain ${jname} started in ${diff_time}
 else
-	cbsdlogger NOTICE ${CBSD_APP}: bhyve domain ${jname} started for live migration for source node ${lm_rnodename} in ${diff_time}
+	cbsdlogger NOTICE ${CIX_APP}: bhyve domain ${jname} started for live migration for source node ${lm_rnodename} in ${diff_time}
 fi
 
-[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
+[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CIX_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
 
 if [ -n "${start_post_message}" -a ${quiet} -ne 1 ]; then
 	${ECHO} "${N1_COLOR}post-start message for ${N2_COLOR}${jname}${N2_COLOR}"
diff --git a/sudoexec/jlogin b/sudoexec/jlogin
--- a/sudoexec/jlogin
+++ b/sudoexec/jlogin
@@ -193,7 +193,7 @@ login_internal()
 	fi
 	init_tmux
 
-	cbsdlogger NOTICE ${CBSD_APP}: executing jexec string for login: ${jexec}
+	cbsdlogger NOTICE ${CIX_APP}: executing jexec string for login: ${jexec}
 
 	if [ ${tmux_login} -eq 1 ]; then
 		${tmuxcmd} list-sessions | ${GREP_CMD} -qwF "${session_name}:"
@@ -208,7 +208,7 @@ login_internal()
 		eval ${jexec}
 		ret=$?
 		if [ ${ret} -ne 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP} jexec errcode: ${ret}: ${jexec}${N0_COLOR}" 1>&2
+			${ECHO} "${N1_COLOR}${CIX_APP} jexec errcode: ${ret}: ${jexec}${N0_COLOR}" 1>&2
 		fi
 	fi
 
@@ -239,7 +239,7 @@ jname_jlogin()
 
 	readconf jlogin.conf
 
-	cbsdlogger NOTICE ${CBSD_APP}: login into ${jname}
+	cbsdlogger NOTICE ${CIX_APP}: login into ${jname}
 
 	case "${login_cmd}" in
 		internal)
@@ -260,13 +260,13 @@ fi
 emulator="jail"		# for jname_is_multiple
 
 # check for cloud function when CBSDfile exist
-Makefile="${CBSD_PWD}/CBSDfile"
+Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" ]; then
 	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 	. ${Makefile}
 
 	all_jail_list=$( ${GREP_CMD} -E '^jail_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#jail_##g )
-	[ -z "${all_jail_list}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no jail found${N0_COLOR}"
+	[ -z "${all_jail_list}" ] && err 1 "${N1_COLOR}${CIX_APP}: no jail found${N0_COLOR}"
 	[ -z "${jname}" ] && jname="${1}"
 
 	if [ -n "${jname}" ]; then
@@ -277,7 +277,7 @@ if [ -r "${Makefile}" ]; then
 				break
 			fi
 		done
-		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 		all_jail_list="${jname}"
 	fi
 
@@ -322,14 +322,14 @@ if [ ${cbsd_api} -eq 1 ]; then
 		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${jname} 2>&1 )
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error1: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error1: ${N2_COLOR}${_ssh}${N0_COLOR}"
 			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			continue
 		fi
 		_ssh_string=$( echo "${_ssh}" | ${JQ_CMD} '.ssh_string' | ${TR_CMD} -d '"' )
 		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh_string}" )
 		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error2, no ssh_string:\n${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error2, no ssh_string:\n${N2_COLOR}${_ssh}${N0_COLOR}"
 			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			continue
 		fi
diff --git a/sudoexec/jstart b/sudoexec/jstart
--- a/sudoexec/jstart
+++ b/sudoexec/jstart
@@ -52,7 +52,7 @@ else
 fi
 
 # check for cloud function when CBSDfile exist
-Makefile="${CBSD_PWD}/CBSDfile"
+Makefile="${CIX_PWD}/CBSDfile"
 if [ ! -r "${Makefile}" ]; then
 		[ -z "${1}" ] && select_jail_by_list -s "List of offline jail" -a "Off" -r ${sqlreplica}
 fi
@@ -103,7 +103,7 @@ if [ -r "${Makefile}" ]; then
 						ojname="${ojname} ${i}"
 					fi
 				else
-					${ECHO} "${N1_COLOR}${CBSD_APP}: env absent in CBSDfile: ${N2_COLOR}${i}${N0_COLOR}" 1>&2
+					${ECHO} "${N1_COLOR}${CIX_APP}: env absent in CBSDfile: ${N2_COLOR}${i}${N0_COLOR}" 1>&2
 				fi
 			fi
 		done
@@ -116,7 +116,7 @@ if [ -r "${Makefile}" ]; then
 
 	unset ojname jname
 
-	[ -z "${jail_list}" ] && err 1 "${N1_COLOR}${CBSD_APP}: give me jname${N0_COLOR}"
+	[ -z "${jail_list}" ] && err 1 "${N1_COLOR}${CIX_APP}: give me jname${N0_COLOR}"
 
 	# multiple?
 	strpos --str="${jail_list}" --search=" "
@@ -226,7 +226,7 @@ done
 
 # this is multiple list, split it by parallel jstart execution
 if [ ${jail_num} -gt 1 ]; then
-	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple starting: ${JLIST}
+	cbsdlogger NOTICE ${CIX_APP}: executing for multiple starting: ${JLIST}
 	# multiple astart always non interactive
 	export inter=0
 
@@ -276,8 +276,8 @@ if [ ${jail_num} -gt 1 ]; then
 	end_time=$( ${DATE_CMD} +%s )
 	diff_time=$(( end_time - st_time ))
 	diff_time=$( displaytime ${diff_time} )
-	${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
-	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple done in ${diff_time}: ${JLIST}
+	${ECHO} "${N1_COLOR}${CIX_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
+	cbsdlogger NOTICE ${CIX_APP}: executing for multiple done in ${diff_time}: ${JLIST}
 	err 0 "${N1_COLOR}Multiple start: ${N2_COLOR}done${N0_COLOR}"
 fi
 
@@ -312,7 +312,7 @@ fi
 # mainly to smooth mass start in astart.
 [ -n "${odelay}" ] && delay="${odelay}"
 if [ ${delay} -ne 0 ]; then
-	cbsdlogger NOTICE ${CBSD_APP}: delayed boot for ${jname} via delay= params: ${delay} sec.
+	cbsdlogger NOTICE ${CIX_APP}: delayed boot for ${jname} via delay= params: ${delay} sec.
 	sleep ${delay}
 fi
 
@@ -373,7 +373,7 @@ jaillock="${jailsysdir}/${jname}/locked"
 if [ -f "${jaillock}" ]; then
 	masterhost=$( ${CAT_CMD} ${jaillock} )
 	if [ "${masterhost}" = "${nodename}" -o -z "${masterhost}" ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: jail ${jname}: remove my stale lock file: ${jaillock}
+		cbsdlogger NOTICE ${CIX_APP}: jail ${jname}: remove my stale lock file: ${jaillock}
 		[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Remove my stale lock file: ${N2_COLOR}${jaillock}${N0_COLOR}"
 		${RM_CMD} -f ${jaillock}
 	else
@@ -383,13 +383,13 @@ if [ -f "${jaillock}" ]; then
 
 		# 30 minutes outdated lock
 		if [ ${difftime} -gt 30 ]; then
-			cbsdlogger NOTICE ${CBSD_APP}: jail ${jname}: locked by ${masterhost} node via ${jaillock} file but lock file age is too old: ${difftime}. Removing!
+			cbsdlogger NOTICE ${CIX_APP}: jail ${jname}: locked by ${masterhost} node via ${jaillock} file but lock file age is too old: ${difftime}. Removing!
 			[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Jail ${N2_COLOR}${jname}${N1_COLOR} locked by ${N2_COLOR}${masterhost}${N1_COLOR} node${N0_COLOR}"
 			[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}But lock age is too old: ${difftime} min. Removing!!!${N0_COLOR}"
 			${RM_CMD} -f ${jaillock}
 		else
 			# still fresh
-			cbsdlogger NOTICE ${CBSD_APP}: jail ${jname}: locked by ${masterhost} node via ${jaillock} file and lock file age time is fresh: ${difftime}.
+			cbsdlogger NOTICE ${CIX_APP}: jail ${jname}: locked by ${masterhost} node via ${jaillock} file and lock file age time is fresh: ${difftime}.
 			[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Jail ${N2_COLOR}${jname}${N1_COLOR} locked by ${N2_COLOR}${masterhost}${N1_COLOR} node, lock age: ${difftime} min.${N0_COLOR}"
 			log_err 1 "${N1_COLOR}You may remove the lockfile if you believe that jail is not running on this node: ${N2_COLOR}rm -f ${jaillock}${N0_COLOR}"
 		fi
@@ -403,7 +403,7 @@ trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 if [ -n "${mdsize}" -a "${mdsize}" != "0" ]; then
 	MDFILE="${jailsysdir}/${jname}/image.dat"
 	if [ ! -f "${MDFILE}" -a ! -h "${MDFILE}" ]; then
-		cbsdlogger NOTICE ${CBSD_APP}: jail: ${jname}: no such ${MDFILE} but mdsize flags is not null, skip
+		cbsdlogger NOTICE ${CIX_APP}: jail: ${jname}: no such ${MDFILE} but mdsize flags is not null, skip
 		[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}No such ${MDFILE} but mdsize flags is not null. Skip${N0_COLOR}" && continue
 	fi
 fi
@@ -463,7 +463,7 @@ fi
 
 check_environment_script "tests"
 
-[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && /usr/local/bin/cbsd ${miscdir}/updatesql ${jailsysdir}/${jname}/local.sqlite ${distdir}/share/local-jailnic.schema jailnic
+[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && /usr/local/bin/cbsd ${miscdir}/updatesql ${jailsysdir}/${jname}/local.sqlite ${CIX_DISTDIR}/share/local-jailnic.schema jailnic
 
 # check for DHCP in ip4_addr string and replace them by ip
 OIFS="${IFS}"
@@ -476,13 +476,13 @@ for _tmp in ${ip4_addr}; do
 		[Dd][Hh][Cc][PP])
 			_tmp=$( dhcpd )
 			[ $? -eq 2 ] && log_err 1 "${N1_COLOR}No free IP address for DHCP in nodeippool${N0_COLOR}"
-			cbsdlogger NOTICE ${CBSD_APP}: set ip4_addr for ${jname} via DHCP: ${_tmp}
+			cbsdlogger NOTICE ${CIX_APP}: set ip4_addr for ${jname} via DHCP: ${_tmp}
 			_mod=1
 			;;
 		[Dd][Hh][Cc][PP][vV]6)
 			_tmp=$( dhcpdv6 )
 			[ $? -eq 2 ] && log_err 1 "${N1_COLOR}No free IP6 address for DHCP in nodeip6pool${N0_COLOR}"
-			cbsdlogger NOTICE ${CBSD_APP}: set ip4_addr for ${jname} via DHCPv6: ${_tmp}
+			cbsdlogger NOTICE ${CIX_APP}: set ip4_addr for ${jname} via DHCPv6: ${_tmp}
 			_mod=1
 			;;
 		*)
@@ -522,7 +522,7 @@ if [ -n "${interface}" -a "${interface}" != "0" -a "${vnet}" -eq "0" ]; then
 
 		if [ ${_ret} -ne 0 ]; then
 			${ECHO} "${W1_COLOR}Warning: ${N1_COLOR}interface not exist for jail ${jname}: ${N2_COLOR}${interface}${N0_COLOR}"
-			cbsdlogger NOTICE ${CBSD_APP}: Warning: interface not exist for jail ${jname}: ${interface}
+			cbsdlogger NOTICE ${CIX_APP}: Warning: interface not exist for jail ${jname}: ${interface}
 		fi
 	fi
 
@@ -603,7 +603,7 @@ if [ "${vnet}" = "1" ]; then
 
 				mybridge=
 				if ! mybridge=$( get_my_device vpc vpc-${vpc_name} ); then
-					err 1 "${N1_COLOR}${CBSD_APP} failed to get VPC bridge: ${mybridge}${N0_COLOR}"
+					err 1 "${N1_COLOR}${CIX_APP} failed to get VPC bridge: ${mybridge}${N0_COLOR}"
 				fi
 
 				${IFCONFIG_CMD} ${mybridge} > /dev/null 2>&1
@@ -655,7 +655,7 @@ if [ "${vnet}" = "1" ]; then
 				_pos=$?
 				if [ ${_pos} -eq 0 ]; then
 					# not vale_XXX form
-					err 1 "${N1_COLOR}${CBSD_APP}: vale switch not vale_XXX form: ${N2_COLOR}${nic_parent}${N0_COLOR}"
+					err 1 "${N1_COLOR}${CIX_APP}: vale switch not vale_XXX form: ${N2_COLOR}${nic_parent}${N0_COLOR}"
 				else
 					_arg_len=$( strlen ${nic_parent} )
 					_pref=$(( _arg_len - _pos ))
@@ -663,11 +663,11 @@ if [ "${vnet}" = "1" ]; then
 					_sw=$( substr --pos=$(( ${_pos} +2 )) --len=${_pref} --str="${nic_parent}" )
 				fi
 				valeid=$( cbsdsqlro local "SELECT idx FROM vale WHERE name='${_sw}'"  )
-				[ -z "${valeid}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: can't determine vale nic for: ${nic_parent}, sw: ${_sw}${N0_COLOR}"
+				[ -z "${valeid}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: can't determine vale nic for: ${nic_parent}, sw: ${_sw}${N0_COLOR}"
 				#mytap="vale${valeid}:${jname}"
-				cbsdlogger NOTICE "${CBSD_APP}: vale switch id: ${valeid} (vale${valeid})"
-				[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP}: attach to vale switch id: ${valeid} (${N2_COLOR}vale${valeid}${N1_COLOR})${N0_COLOR}"
-				${distdir}/tools/vale-ctl -h vale${valeid}:${myepair}a
+				cbsdlogger NOTICE "${CIX_APP}: vale switch id: ${valeid} (vale${valeid})"
+				[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CIX_APP}: attach to vale switch id: ${valeid} (${N2_COLOR}vale${valeid}${N1_COLOR})${N0_COLOR}"
+				${CIX_DISTDIR}/tools/vale-ctl -h vale${valeid}:${myepair}a
 		esac
 
 		printf "${H3_COLOR}${myepair}(type:${nic_type}):${N2_COLOR}${nic_parent} "
@@ -706,11 +706,11 @@ if [ "${vnet}" = "1" ]; then
 
 		case "${nic_type}" in
 			ppt)
-				cbsdlogger NOTICE ${CBSD_APP}: jail ${jname}: set hwaddr for vnet interface ${myepair}: ${nic_hwaddr}
+				cbsdlogger NOTICE ${CIX_APP}: jail ${jname}: set hwaddr for vnet interface ${myepair}: ${nic_hwaddr}
 				${IFCONFIG_CMD} ${myepair} ether ${nic_hwaddr}
 				;;
 			*)
-				cbsdlogger NOTICE ${CBSD_APP}: jail ${jname}: set hwaddr for vnet interface ${myepair}b: ${nic_hwaddr}
+				cbsdlogger NOTICE ${CIX_APP}: jail ${jname}: set hwaddr for vnet interface ${myepair}b: ${nic_hwaddr}
 				_iface_rename=1
 				${IFCONFIG_CMD} ${myepair}b ether ${nic_hwaddr}
 				if [ "${nic_address}" != "0" ]; then
@@ -731,12 +731,12 @@ case ${zfsfeat} in
 			# ZFS encryption?
 			zfs_encryption_val=$( ${ZFS_CMD} get -Ho value encryption ${ZPOOL} 2>/dev/null )
 			if [ -n "${zfs_encryption_val}" -a "${zfs_encryption_val}" != "off" ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: encrypted dataset: ${N2_COLOR}${zfs_encryption_val}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP}: encrypted dataset: ${N2_COLOR}${zfs_encryption_val}${N0_COLOR}"
 				zfs_encryption_keyformat=$( ${ZFS_CMD} get -Ho value keyformat ${ZPOOL} 2>/dev/null )
-				${ECHO} "${N1_COLOR}${CBSD_APP}: encryption keyformat: ${N2_COLOR}${zfs_encryption_keyformat}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP}: encryption keyformat: ${N2_COLOR}${zfs_encryption_keyformat}${N0_COLOR}"
 				if [ "${zfs_encryption_keyformat}" = "passphrase" ]; then
 					if [ -n "${NOINTER}" -o "${inter}" = "1" ]; then
-						err 0 "${N1_COLOR}${CBSD_APP} keyformat is passphrase, skipp for non-interactive mode${N0_COLOR}"
+						err 0 "${N1_COLOR}${CIX_APP} keyformat is passphrase, skipp for non-interactive mode${N0_COLOR}"
 					else
 						${ZFS_CMD} load-key ${ZPOOL}
 						# 255 code valid here, already loaded
@@ -744,7 +744,7 @@ case ${zfsfeat} in
 				fi
 			fi
 			${ZFS_CMD} mount "${ZPOOL}"
-			is_mounted ${data} || err 1 "${N1_COLOR}${CBSD_APP}: unable to mount zfs pool: ${N2_COLOR}${ZPOOL} -> ${data}${N0_COLOR}"
+			is_mounted ${data} || err 1 "${N1_COLOR}${CIX_APP}: unable to mount zfs pool: ${N2_COLOR}${ZPOOL} -> ${data}${N0_COLOR}"
 		fi
 	;;
 esac
@@ -906,8 +906,8 @@ case "${platform}" in
 		ret=$?
 		;;
 	*)
-		#cbsdlogger NOTICE ${CBSD_APP}: ${CPUSET} /usr/local/cbsd/misc/daemonize -e ${ftmpdir}/jstart.${jname}.err -p ${ftmpdir}/jstart.${jname}.$$ ${NICE_CMD} -n ${nice} ${JAIL_CMD} -f ${ftmpdir}/${jname}.conf -c ${jname}
-		cbsdlogger NOTICE ${CBSD_APP}: ${CPUSET} /usr/local/cbsd/misc/daemonize -e ${ftmpdir}/jstart.${jname}.err -p ${ftmpdir}/jstart.${jname}.$$ ${NICE_CMD} -n ${nice} ${miscdir}/jail_env ${jname} ${ftmpdir}/${jname}.conf
+		#cbsdlogger NOTICE ${CIX_APP}: ${CPUSET} /usr/local/cbsd/misc/daemonize -e ${ftmpdir}/jstart.${jname}.err -p ${ftmpdir}/jstart.${jname}.$$ ${NICE_CMD} -n ${nice} ${JAIL_CMD} -f ${ftmpdir}/${jname}.conf -c ${jname}
+		cbsdlogger NOTICE ${CIX_APP}: ${CPUSET} /usr/local/cbsd/misc/daemonize -e ${ftmpdir}/jstart.${jname}.err -p ${ftmpdir}/jstart.${jname}.$$ ${NICE_CMD} -n ${nice} ${miscdir}/jail_env ${jname} ${ftmpdir}/${jname}.conf
 		#echo "${JAIL_CMD} -f ${ftmpdir}/${jname}.conf -c ${jname}"
 
 		case "${quiet}" in
@@ -932,7 +932,7 @@ if [ ${ret} -ne 0 ]; then
 		${RM_CMD} ${ftmpdir}/jstart.${jname}.err
 	fi
 	jcleanup jname=${jname}
-	log_err 1 "${N1_COLOR}${CBSD_APP}: daemonize error${N0_COLOR}"
+	log_err 1 "${N1_COLOR}${CIX_APP}: daemonize error${N0_COLOR}"
 fi
 
 trap "" HUP INT ABRT BUS TERM EXIT
@@ -950,7 +950,7 @@ for i in 1 2 3 4 5 6; do
 	if [ "${quiet}" != "1" ]; then
 		printf "${CLRLINE}"
 		printf "${CURSORRST}"
-		printf "${N1_COLOR}${CBSD_APP}: waiting for ${jname} JID: ${N2_COLOR}${i}/6 ... ${N0_COLOR}"
+		printf "${N1_COLOR}${CIX_APP}: waiting for ${jname} JID: ${N2_COLOR}${i}/6 ... ${N0_COLOR}"
 		jstart_slow=1
 	fi
 	sleep 1
@@ -963,7 +963,7 @@ if [ ${ret} -eq 0 ]; then
 		${RM_CMD} ${ftmpdir}/jstart.${jname}.err
 	fi
 	jcleanup jname=${jname}
-	log_err 1 "${N1_COLOR}${CBSD_APP}: jail failed${N0_COLOR}"
+	log_err 1 "${N1_COLOR}${CIX_APP}: jail failed${N0_COLOR}"
 fi
 
 [ ${jstart_slow} -eq 1 -a "${quiet}" != "1" ] && ${ECHO} "${H1_COLOR}${myjid}${N0_COLOR}"
@@ -1025,7 +1025,7 @@ if [ ${vnet} -eq 1 ]; then
 					_res=$( ${CAT_CMD} ${tmpdir}/eth${eth_seq}.locked )
 					jstop jname=${jname} fast=1
 					${IFCONFIG_CMD} ${i} destroy
-					log_err 1 "${N1_COLOR}${CBSD_APP}: waiting for unlock: still locked by [${_res}]: ${N2_COLOR}${tmpdir}/eth${eth_seq}.locked${N0_COLOR}"
+					log_err 1 "${N1_COLOR}${CIX_APP}: waiting for unlock: still locked by [${_res}]: ${N2_COLOR}${tmpdir}/eth${eth_seq}.locked${N0_COLOR}"
 				fi
 
 				sleep 1
@@ -1090,7 +1090,7 @@ if [ ${vnet} -eq 1 ]; then
 									. ${path}/etc/os-release
 									case "${ID}" in
 										debian)
-											${ECHO} "${N1_COLOR}${CBSD_APP} use debian helper for config_${int_iface}${N1_COLOR}"
+											${ECHO} "${N1_COLOR}${CIX_APP} use debian helper for config_${int_iface}${N1_COLOR}"
 											# just test, netlink/BSD wIP
 											# mgmt for first boot only? ! -r ${data}/etc/network/interfaces.d/* ?
 #											${CAT_CMD} > ${data}/etc/network/interfaces.d/lo <<EOF
@@ -1189,7 +1189,7 @@ if [ ${vnet} -eq 1 ]; then
 								fi
 							done
 						fi
-						/usr/local/cbsd/misc/cbsdsysrc -qf ${data}/etc/rc.conf ${find_ifconfig}="${new_ifconfig_eth0}" > /dev/null 2>&1
+						${CIX_DISTDIR}/misc/cbsdsysrc -qf ${data}/etc/rc.conf ${find_ifconfig}="${new_ifconfig_eth0}" > /dev/null 2>&1
 					fi
 			esac
 		done
@@ -1220,14 +1220,14 @@ if [ ${vnet} -eq 1 ]; then
 					nic_address=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT nic_address FROM jailnic LIMIT 1 )
 					# is ip?
 					if [ -n "${nic_address}" -a "${nic_address}" != "0" ]; then
-						echo "${N1_COLOR}${CBSD_APP}: set defaultrouter to nic_address: ${N2_COLOR}[${nic_address}]${N0_COLOR}"
-						/usr/local/cbsd/misc/cbsdsysrc -qf ${data}/etc/rc.conf defaultrouter="${nic_address}" > /dev/null 2>&1
+						echo "${N1_COLOR}${CIX_APP}: set defaultrouter to nic_address: ${N2_COLOR}[${nic_address}]${N0_COLOR}"
+						${CIX_DISTDIR}/misc/cbsdsysrc -qf ${data}/etc/rc.conf defaultrouter="${nic_address}" > /dev/null 2>&1
 					elif [ -n "${oci_gw4}" ];then
 						nic_address="${oci_gw4}"
-						echo "${N1_COLOR}${CBSD_APP}: set defaultrouter to by config file: ${N2_COLOR}[${nic_address}]${N0_COLOR}"
-						/usr/local/cbsd/misc/cbsdsysrc -qf ${data}/etc/rc.conf defaultrouter="${nic_address}" > /dev/null 2>&1
+						echo "${N1_COLOR}${CIX_APP}: set defaultrouter to by config file: ${N2_COLOR}[${nic_address}]${N0_COLOR}"
+						${CIX_DISTDIR}/misc/cbsdsysrc -qf ${data}/etc/rc.conf defaultrouter="${nic_address}" > /dev/null 2>&1
 					else
-						echo "${N1_COLOR}${CBSD_APP}: ci_gw4 sets to auto, but nic_address is empty${N0_COLOR}"
+						echo "${N1_COLOR}${CIX_APP}: ci_gw4 sets to auto, but nic_address is empty${N0_COLOR}"
 					fi
 					;;
 				*)
@@ -1238,10 +1238,10 @@ if [ ${vnet} -eq 1 ]; then
 					# * - unknown
 					case ${myip_type} in
 						1)
-							/usr/local/cbsd/misc/cbsdsysrc -qf ${data}/etc/rc.conf defaultrouter="${_pureip}" > /dev/null 2>&1
+							${CIX_DISTDIR}/misc/cbsdsysrc -qf ${data}/etc/rc.conf defaultrouter="${_pureip}" > /dev/null 2>&1
 							;;
 						2)
-							/usr/local/cbsd/misc/cbsdsysrc -qf ${data}/etc/rc.conf ipv6_defaultrouter="${_pureip}" > /dev/null 2>&1
+							${CIX_DISTDIR}/misc/cbsdsysrc -qf ${data}/etc/rc.conf ipv6_defaultrouter="${_pureip}" > /dev/null 2>&1
 							;;
 						*)
 							;;
@@ -1352,7 +1352,7 @@ if [ -f "${jailsysdir}/${jname}/jail-message" -a ${quiet} -ne 1 ]; then
 	${ECHO} "${N1_COLOR}---- ${N2_COLOR}jail messages ${N1_COLOR}----${N0_COLOR}" 1>&2
 fi
 
-[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
-cbsdlogger NOTICE ${CBSD_APP}: jail ${jname} started in ${diff_time}
+[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CIX_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
+cbsdlogger NOTICE ${CIX_APP}: jail ${jname} started in ${diff_time}
 
 exit 0
diff --git a/system/delete-old-libs b/system/delete-old-libs
--- a/system/delete-old-libs
+++ b/system/delete-old-libs
@@ -45,8 +45,8 @@ oarch="${arch}"
 
 if [ -n "${jname}" ]; then
 	. ${subrdir}/rcconf.subr
-	[ $? -eq 1 ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
-	[ "${baserw}" != "1" ] && err 1 "${N1_COLOR}${CBSD_APP} error: jail is baserw=0: ${N2_COLOR}${jname}${N0_COLOR}"
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}${CIX_APP} error: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+	[ "${baserw}" != "1" ] && err 1 "${N1_COLOR}${CIX_APP} error: jail is baserw=0: ${N2_COLOR}${jname}${N0_COLOR}"
 	BASE_DIR="${data}"
 fi
 
@@ -57,7 +57,7 @@ fi
 init_target_arch
 init_srcdir
 
-[ ! -r ${SRC_DIR}/Makefile ] && log_err 1 "${N1_COLOR}${CBSD_APP}: source directory must exist, no such src dir: ${N2_COLOR}${SRC_DIR}${N0_COLOR}"
+[ ! -r ${SRC_DIR}/Makefile ] && log_err 1 "${N1_COLOR}${CIX_APP}: source directory must exist, no such src dir: ${N2_COLOR}${SRC_DIR}${N0_COLOR}"
 
 if [ -z "${jname}" ]; then
 	if [ -z "${destdir}" ]; then
@@ -68,8 +68,8 @@ if [ -z "${jname}" ]; then
 	fi
 fi
 
-[ ! -d "${BASE_DIR}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: No such dir: ${N2_COLOR}${BASE_DIR}${N0_COLOR}"
-cbsdlogger NOTICE ${CBSD_APP}: make -C ${SRC_DIR} DESTDIR="${BASE_DIR}" delete-old delete-old-libs
+[ ! -d "${BASE_DIR}" ] && err 1 "${N1_COLOR}${CIX_APP} error: No such dir: ${N2_COLOR}${BASE_DIR}${N0_COLOR}"
+cbsdlogger NOTICE ${CIX_APP}: make -C ${SRC_DIR} DESTDIR="${BASE_DIR}" delete-old delete-old-libs
 yes | make -C ${SRC_DIR} DESTDIR="${BASE_DIR}" delete-old delete-old-libs
 
 exit 0
diff --git a/system/etcupdate b/system/etcupdate
--- a/system/etcupdate
+++ b/system/etcupdate
@@ -86,10 +86,10 @@ readconf buildworld.conf
 
 etcupdate_base_extract()
 {
-	local _etcupdate_dir _index_ver _index_file
+	local _etcupdate_dir= _index_ver= _index_file=
 
 	# todo: generate from ~cbsd/basejail/* ? gen from etcupdate required for source tree!
-	[ -z "${etcupdate_ver}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}ver=${N0_COLOR}"
+	[ -z "${etcupdate_ver}" ] && err 1 "${N1_COLOR}${CIX_APP} error: no such ${N2_COLOR}ver=${N0_COLOR}"
 	ver="${etcupdate_ver}"
 
 	init_target_arch
@@ -99,7 +99,7 @@ etcupdate_base_extract()
 
 	if [ -d ${_etcupdate_dir}/current ]; then
 		if [ ${force} -eq 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: already exist: ${N2_COLOR}${_etcupdate_dir}/current${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: already exist: ${N2_COLOR}${_etcupdate_dir}/current${N0_COLOR}"
 			return 0
 		fi
 		${RM_CMD} -rf ${_etcupdate_dir}/current
@@ -107,11 +107,11 @@ etcupdate_base_extract()
 
 	case "${default_obtain_etcupdate_method}" in
 		build)
-			[ ! -r ${SRC_DIR}/Makefile ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such src hier in ${SRC_DIR}. Please run: ${N2_COLOR}cbsd srcup ver=${ver}${N1_COLOR} first${N0_COLOR}"
-			${ECHO} "${N1_COLOR}${CBSD_APP}: extract to: ${N2_COLOR}${_etcupdate_dir}/current${N0_COLOR}"
+			[ ! -r ${SRC_DIR}/Makefile ] && err 1 "${N1_COLOR}${CIX_APP} error: no such src hier in ${SRC_DIR}. Please run: ${N2_COLOR}cbsd srcup ver=${ver}${N1_COLOR} first${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: extract to: ${N2_COLOR}${_etcupdate_dir}/current${N0_COLOR}"
 			${ETCUPDATE_CMD} extract -d ${_etcupdate_dir} -s ${SRC_DIR}
-			[ ! -d ${_etcupdate_dir}/current ] && err 1 "${N1_COLOR}${CBSD_APP} failed to extract: ${N1_COLOR}${_etcupdate_dir}${N0_COLOR}"
-			${ECHO} "${N1_COLOR}${CBSD_APP} updated: ${N2_COLOR}${_etcupdate_dir}${N0_COLOR}"
+			[ ! -d ${_etcupdate_dir}/current ] && err 1 "${N1_COLOR}${CIX_APP} failed to extract: ${N1_COLOR}${_etcupdate_dir}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} updated: ${N2_COLOR}${_etcupdate_dir}${N0_COLOR}"
 			;;
 		index)
 			_index_ver="${ver}"
@@ -121,23 +121,23 @@ etcupdate_base_extract()
 				_index_ver=${ver%%.*}
 				_index_file="${distsharedir}/etcupdate_${_index_ver}.txt.xz"
 			fi
-			[ ! -r "${_index_file}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no index for default_obtain_etcupdate_method=index method: ${N2_COLOR}${_index_file}${N0_COLOR}"
+			[ ! -r "${_index_file}" ] && err 1 "${N1_COLOR}${CIX_APP}: no index for default_obtain_etcupdate_method=index method: ${N2_COLOR}${_index_file}${N0_COLOR}"
 			over="${ver}"
 			. ${subrdir}/build.subr
 			init_target_arch
 			init_basedir
 
 			if [ ! -x "${BASE_DIR}/bin/sh" ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: no such base for default_obtain_etcupdate_method=index method: ${N2_COLOR}${BASE_DIR}${N0_COLOR}"
-				err 1 "${N1_COLOR}${CBSD_APP}: please use: ${N2_COLOR}cbsd repo action=get sources=base ver=${ver}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP}: no such base for default_obtain_etcupdate_method=index method: ${N2_COLOR}${BASE_DIR}${N0_COLOR}"
+				err 1 "${N1_COLOR}${CIX_APP}: please use: ${N2_COLOR}cbsd repo action=get sources=base ver=${ver}${N0_COLOR}"
 			fi
 
 			[ -d ${_etcupdate_dir}/current ] && ${RM_CMD} -rf ${_etcupdate_dir}/current
-			${ECHO} "${N1_COLOR}${CBSD_APP}: extract to: ${N2_COLOR}${_etcupdate_dir}/current${N1_COLOR} (by: ${N2_COLOR}${_index_file} <- ${BASE_DIR}${N1_COLOR})${N0_COLOR}" 1>&2
+			${ECHO} "${N1_COLOR}${CIX_APP}: extract to: ${N2_COLOR}${_etcupdate_dir}/current${N1_COLOR} (by: ${N2_COLOR}${_index_file} <- ${BASE_DIR}${N1_COLOR})${N0_COLOR}" 1>&2
 			copy-binlib filelist=${_index_file} dstdir=${_etcupdate_dir}/current basedir=${BASE_DIR} 2>/dev/null
 			;;
 		*)
-			err 1 "${N1_COLOR}${CBSD_APP}: unknown default_obtain_etcupdate_method: ${N2_COLOR}${default_obtain_etcupdate_method}${N0_COLOR}"
+			err 1 "${N1_COLOR}${CIX_APP}: unknown default_obtain_etcupdate_method: ${N2_COLOR}${default_obtain_etcupdate_method}${N0_COLOR}"
 			;;
 	esac
 
@@ -146,15 +146,15 @@ etcupdate_base_extract()
 
 etcupdate_jail_extract()
 {
-	local _etcupdate_dir _etcupdate_from_dir
+	local _etcupdate_dir= _etcupdate_from_dir=
 
-	[ -z "${jail_ver}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}ver=${N0_COLOR}"
+	[ -z "${jail_ver}" ] && err 1 "${N1_COLOR}${CIX_APP} error: no such ${N2_COLOR}ver=${N0_COLOR}"
 	[ -z "${jname}" ] && log_err 1 "${N1_COLOR}Please set jset: ${N2_COLOR}jname${N0_COLOR}"
 
 	_etcupdate_from_dir="${srcdir}/src_${ver}/etcupdate"
 	if [ ! -d ${_etcupdate_from_dir}/current ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
-		err 1 "${N1_COLOR}${CBSD_APP}: please run for init: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP} error: no such ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP}: please run for init: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
 	fi
 
 	[ ! -d ${etcupdate_jail_root} ] && ${MKDIR_CMD} -p ${etcupdate_jail_root}
@@ -168,7 +168,7 @@ etcupdate_jail_extract()
 
 	# store original version
 	[ ! -r ${etcupdate_jail_root}/ver ] && ${TOUCH_CMD} ${etcupdate_jail_root}/ver
-	/usr/local/cbsd/misc/cbsdsysrc -qf ${etcupdate_jail_root}/ver etcupdate_current_ver="${ver}" > /dev/null 2>&1
+	${CIX_DISTDIR}/misc/cbsdsysrc -qf ${etcupdate_jail_root}/ver etcupdate_current_ver="${ver}" > /dev/null 2>&1
 
 	return 0
 }
@@ -178,7 +178,7 @@ etcupdate_base_build()
 	local _etcupdate_dir=
 
 	# todo: generate from ~cbsd/basejail/* ? gen from etcupdate required for source tree!
-	[ -z "${etcupdate_ver}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}ver=${N0_COLOR}"
+	[ -z "${etcupdate_ver}" ] && err 1 "${N1_COLOR}${CIX_APP} error: no such ${N2_COLOR}ver=${N0_COLOR}"
 	ver="${etcupdate_ver}"
 
 	init_target_arch
@@ -188,7 +188,7 @@ etcupdate_base_build()
 
 	if [ -r ${_etcupdate_dir}/etcupdate.tgz ]; then
 		if [ ${force} -eq 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: already exist: ${N2_COLOR}${_etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: already exist: ${N2_COLOR}${_etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
 			return 0
 		fi
 		${RM_CMD} -f ${_etcupdate_dir}/etcupdate.tgz
@@ -196,22 +196,18 @@ etcupdate_base_build()
 
 	case "${default_obtain_etcupdate_method}" in
 		build)
-			[ ! -r ${SRC_DIR}/Makefile ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such src hier in ${SRC_DIR}. Please run: ${N2_COLOR}cbsd srcup ver=${ver}${N1_COLOR} first${N0_COLOR}"
-			${ECHO} "${N1_COLOR}${CBSD_APP}: ${N2_COLOR}build...${N0_COLOR}"
+			[ ! -r ${SRC_DIR}/Makefile ] && err 1 "${N1_COLOR}${CIX_APP} error: no such src hier in ${SRC_DIR}. Please run: ${N2_COLOR}cbsd srcup ver=${ver}${N1_COLOR} first${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: ${N2_COLOR}build...${N0_COLOR}"
 			${ETCUPDATE_CMD} build -s ${SRC_DIR} ${_etcupdate_dir}/etcupdate.tgz
-			if [ -r ${_etcupdate_dir}/etcupdate.tgz ]; then
-				# done
-			else
-				err 1 "${N1_COLOR}${CBSD_APP} failed: no ${N2_COLOR}${_etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
-			fi
+			[ ! -r ${_etcupdate_dir}/etcupdate.tgz ] && err 1 "${N1_COLOR}${CIX_APP} failed: no ${N2_COLOR}${_etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
 			;;
 		index)
 			[ ! -d ${_etcupdate_dir}/current ] && etcupdate mode=extract ver=${ver}
-			[ ! -d ${_etcupdate_dir}/current ] && err 1 "${N1_COLOR}${CBSD_APP} no dir: ${N1_COLOR}${_etcupdate_dir}/current${N1_COLOR}. please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
-			${ECHO} "${N1_COLOR}${CBSD_APP}: build to: ${N2_COLOR}${_etcupdate_dir}/etcupdate.tgz${N1_COLOR} (from: ${N2_COLOR}${_etcupdate_dir}/current${N1_COLOR})${N0_COLOR}"
+			[ ! -d ${_etcupdate_dir}/current ] && err 1 "${N1_COLOR}${CIX_APP} no dir: ${N1_COLOR}${_etcupdate_dir}/current${N1_COLOR}. please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: build to: ${N2_COLOR}${_etcupdate_dir}/etcupdate.tgz${N1_COLOR} (from: ${N2_COLOR}${_etcupdate_dir}/current${N1_COLOR})${N0_COLOR}"
 			cd ${_etcupdate_dir}/current
 			${TAR_CMD} cfz ${_etcupdate_dir}/etcupdate.tgz .
-			[ ! -r ${_etcupdate_dir}/etcupdate.tgz ] && err 1 "${N1_COLOR}${CBSD_APP} failed to build: ${N1_COLOR}${_etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
+			[ ! -r ${_etcupdate_dir}/etcupdate.tgz ] && err 1 "${N1_COLOR}${CIX_APP} failed to build: ${N1_COLOR}${_etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
 			;;
 	esac
 
@@ -220,11 +216,11 @@ etcupdate_base_build()
 
 etcupdate_update()
 {
-	local _exclude_args= i _ret _etcupdate_to_current_dir
-	local _files _etcupdate_to_dir _etcupdate_from_dir
-	local _to_remove _file_num _file_list
+	local _exclude_args= i= _ret= _etcupdate_to_current_dir=
+	local _files= _etcupdate_to_dir= _etcupdate_from_dir=
+	local _to_remove= _file_num= _file_list=
 
-	[ -z "${jname}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: please set jset: ${N2_COLOR}jname${N0_COLOR}"
+	[ -z "${jname}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: please set jset: ${N2_COLOR}jname${N0_COLOR}"
 
 	if [ -z "${from}" ]; then
 		if [ -r ${etcupdate_jail_root}/ver ]; then
@@ -232,14 +228,14 @@ etcupdate_update()
 			. ${etcupdate_jail_root}/ver
 			if [ -n "${etcupdate_current_ver}" ]; then
 				from="${etcupdate_current_ver}"
-				${ECHO} "${N1_COLOR}${CBSD_APP} ${N2_COLOR}from=${N1_COLOR} not specified, assume jail version: ${N2_COLOR}${from}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP} ${N2_COLOR}from=${N1_COLOR} not specified, assume jail version: ${N2_COLOR}${from}${N0_COLOR}"
 			fi
 		fi
 	fi
-	[ -z "${from}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}from=${N0_COLOR}"
+	[ -z "${from}" ] && err 1 "${N1_COLOR}${CIX_APP} error: no such ${N2_COLOR}from=${N0_COLOR}"
 
 	if [ -z "${to}" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP} ${N2_COLOR}to=${N1_COLOR} not specified, assume jail version: ${N2_COLOR}${jail_ver}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP} ${N2_COLOR}to=${N1_COLOR} not specified, assume jail version: ${N2_COLOR}${jail_ver}${N0_COLOR}"
 		to="${jail_ver}"
 	fi
 
@@ -250,10 +246,10 @@ etcupdate_update()
 	_etcupdate_from_dir="${srcdir}/src_${ver}/etcupdate"
 
 	if [ ! -d ${_etcupdate_from_dir}/current ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
-		err 1 "${N1_COLOR}${CBSD_APP}: please run for init: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP} error: no such ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP}: please run for init: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
 	fi
-	${ECHO} "${N1_COLOR}${CBSD_APP} source hier: ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP} source hier: ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
 
 	ver="${to}"
 	init_target_arch
@@ -261,14 +257,14 @@ etcupdate_update()
 	_etcupdate_to_dir="${srcdir}/src_${ver}/etcupdate"
 	_etcupdate_to_current_dir="${srcdir}/src_${ver}/etcupdate/current"
 
-	[ ! -d ${_etcupdate_to_current_dir} ] && err 1 "${N1_COLOR}${CBSD_APP} no dir: ${N1_COLOR}${_etcupdate_to_current_dir}${N1_COLOR}. please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
+	[ ! -d ${_etcupdate_to_current_dir} ] && err 1 "${N1_COLOR}${CIX_APP} no dir: ${N1_COLOR}${_etcupdate_to_current_dir}${N1_COLOR}. please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
 
 	if [ ! -r ${_etcupdate_to_dir}/etcupdate.tgz ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP} failed: no ${N2_COLOR}${_etcupdate_to_dir}/etcupdate.tgz${N0_COLOR}"
-		err 1 "${N1_COLOR}${CBSD_APP}: please run for init: ${N2_COLOR}cbsd etcupdate mode=build ver=${ver}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP} failed: no ${N2_COLOR}${_etcupdate_to_dir}/etcupdate.tgz${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP}: please run for init: ${N2_COLOR}cbsd etcupdate mode=build ver=${ver}${N0_COLOR}"
 
 	fi
-	${ECHO} "${N1_COLOR}${CBSD_APP} destination hier: ${N2_COLOR}${_etcupdate_to_dir}/etcupdate.tgz${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP} destination hier: ${N2_COLOR}${_etcupdate_to_dir}/etcupdate.tgz${N0_COLOR}"
 
 	[ ! -d ${etcupdate_jail_root} ] && ${MKDIR_CMD} -p ${etcupdate_jail_root}
 	# we need RW place for log? redefine log path and use nullfs in RO?
@@ -302,7 +298,7 @@ etcupdate_update()
 		${RM_CMD} ${_tmp_filelist}.xz
 		cd ${etcupdate_jail_root}/backup
 		nice -n 19 ${IDLE_IONICE} ${TAR_CMD} cfz ${_back_time}.tgz ${_back_time}
-		${ECHO} "${N1_COLOR}${CBSD_APP}: created backup: ${N2_COLOR}${_back_dir}.tgz${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP}: created backup: ${N2_COLOR}${_back_dir}.tgz${N0_COLOR}"
 		# rotate
 		_file_list=$( ${FIND_CMD} ${etcupdate_jail_root}/backup -mindepth 1 -maxdepth 1 -name \*.tgz -type f -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} -n | ${XARGS_CMD} )
 		_file_num=$( echo ${_file_list} | ${WC_CMD} -w | ${AWK_CMD} '{printf $1}' )
@@ -310,7 +306,7 @@ etcupdate_update()
 		if [ ${_file_num} -gt ${etcupdate_create_backup} ]; then
 			_to_remove=$(( _file_num - etcupdate_create_backup ))
 			for i in ${_file_list}; do
-				${ECHO} "  ${N1_COLOR}${CBSD_APP}: prune old backup (max ${etcupdate_create_backup}): ${N2_COLOR}${i}${N0_COLOR}"
+				${ECHO} "  ${N1_COLOR}${CIX_APP}: prune old backup (max ${etcupdate_create_backup}): ${N2_COLOR}${i}${N0_COLOR}"
 				${RM_CMD} ${etcupdate_jail_root}/backup/${i}
 				_to_remove=$(( _to_remove - 1 ))
 				[ ${_to_remove} -eq 0 ] && break
@@ -333,10 +329,10 @@ EOF
 				[ -z "${p2}" ] && continue
 				echo "  * ${p2}"
 			done )
-			${ECHO} "${W1_COLOR}${CBSD_APP} warning${N1_COLOR}: confict files:${N0_COLOR}"
+			${ECHO} "${W1_COLOR}${CIX_APP} warning${N1_COLOR}: confict files:${N0_COLOR}"
 			echo "${_files}"
-			${ECHO} "${N1_COLOR}${CBSD_APP} please run: ${N2_COLOR}cbsd etcupdate mode=resolve jname=${jname}${N1_COLOR} to run etcupdate resolve${N0_COLOR}"
-			${ECHO} "${N1_COLOR}${CBSD_APP}: use ${N2_COLOR}EDITOR=${N1_COLOR} environment variable to use favorite editor${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} please run: ${N2_COLOR}cbsd etcupdate mode=resolve jname=${jname}${N1_COLOR} to run etcupdate resolve${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: use ${N2_COLOR}EDITOR=${N1_COLOR} environment variable to use favorite editor${N0_COLOR}"
 		fi
 	fi
 
@@ -345,14 +341,15 @@ EOF
 
 etcupdate_diff()
 {
-	local _ret
+	local _ret=
+
 	[ -z "${jname}" ] && log_err 1 "${N1_COLOR}Please set jset: ${N2_COLOR}jname${N0_COLOR}"
 
 	_etcupdate_from_dir="${srcdir}/src_${ver}/etcupdate"
 	if [ ! -d ${_etcupdate_from_dir}/current ]; then
 		err 1 "${N1_COLOR}no such etcupdate hier, please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
 	fi
-	${ECHO} "${N1_COLOR}${CBSD_APP} source hier: ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP} source hier: ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
 
 	${ETCUPDATE_CMD} diff -d ${etcupdate_jail_root} -D ${path}
 	_ret=$?
@@ -361,14 +358,15 @@ etcupdate_diff()
 
 etcupdate_resolve()
 {
-	local _ret
+	local _ret=
+
 	[ -z "${jname}" ] && log_err 1 "${N1_COLOR}Please set jset: ${N2_COLOR}jname${N0_COLOR}"
 
 	_etcupdate_from_dir="${srcdir}/src_${ver}/etcupdate"
 	if [ ! -d ${_etcupdate_from_dir}/current ]; then
 		err 1 "${N1_COLOR}no such etcupdate hier, please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
 	fi
-	${ECHO} "${N1_COLOR}${CBSD_APP} source hier: ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP} source hier: ${N2_COLOR}${_etcupdate_from_dir}/current${N0_COLOR}"
 
 	${ETCUPDATE_CMD} resolve -d ${etcupdate_jail_root} -D ${path}
 	_ret=$?
@@ -403,8 +401,8 @@ is_prepare_offline_jail=0
 
 if [ -n "${jname}" ]; then
 	. ${subrdir}/rcconf.subr
-	[ $? -eq 1 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
-	[ "${emulator}" != "jail" ] && err 1 "${N1_COLOR}${CBSD_APP}: for 'jail' type emulator only: ${N2_COLOR}${emulator}${N0_COLOR}"
+	[ $? -eq 1 ] && log_err 1 "${N1_COLOR}${CIX_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+	[ "${emulator}" != "jail" ] && err 1 "${N1_COLOR}${CIX_APP}: for 'jail' type emulator only: ${N2_COLOR}${emulator}${N0_COLOR}"
 
 	[ ${baserw} -eq 1 ] && path=${data}
 
@@ -445,10 +443,10 @@ case "${mode}" in
 		ret=$?
 
 		if [ ${ret} -eq 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: update successfull, bootstrap for: ${N1_COLOR}${ver}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: update successfull, bootstrap for: ${N1_COLOR}${ver}${N0_COLOR}"
 			etcupdate jname=${jname} mode=extract default_obtain_etcupdate_method=index ver=${to} force=1
 		else
-			${ECHO} "${N1_COLOR}${CBSD_APP}: update failed${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: update failed${N0_COLOR}"
 		fi
 		;;
 	purge)
@@ -458,14 +456,14 @@ case "${mode}" in
 		etcupdate_resolve
 		ret=$?
 		if [ ${ret} -eq 0 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: update successfull, bootstrap for: ${N1_COLOR}${ver}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: update successfull, bootstrap for: ${N1_COLOR}${ver}${N0_COLOR}"
 			etcupdate jname=${jname} mode=extract default_obtain_etcupdate_method=index ver=${to} force=1
 		else
-			${ECHO} "${N1_COLOR}${CBSD_APP}: update failed${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: update failed${N0_COLOR}"
 		fi
 		;;
 	*)
-		err 1 "${N1_COLOR}${CBSD_APP} error: unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP} error: unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
 		;;
 esac
 
diff --git a/system/module b/system/module
--- a/system/module
+++ b/system/module
@@ -47,7 +47,7 @@ install_module()
 	local CBSDPATH
 
 	if [ -z "${data}" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: no such data variable${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: no such data variable${N0_COLOR}" 1>&2
 		return 1
 	fi
 
@@ -58,7 +58,7 @@ install_module()
 	_ret=$?
 
 	if [ ${_ret} -ne 0 ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: unable to fetch metadata via: /usr/local/cbsd/bin/cfetch -u ${N2_COLOR}${_gh_raw_content_prefix}-${data}/${version}/metadata.conf${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: unable to fetch metadata via: /usr/local/cbsd/bin/cfetch -u ${N2_COLOR}${_gh_raw_content_prefix}-${data}/${version}/metadata.conf${N0_COLOR}" 1>&2
 		[ -r ${_metadata_tmp} ] && ${RM_CMD} ${_metadata_tmp}
 		return 1
 	fi
@@ -68,7 +68,7 @@ install_module()
 	_ret=$?
 
 	if [ ${_ret} -ne 0 -o -z "${MODULE_DIR}" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: unable to extract MODULE_DIR= variable from manifest: ${N2_COLOR}${_gh_raw_content_prefix}-${data}/${version}/metadata.conf${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: unable to extract MODULE_DIR= variable from manifest: ${N2_COLOR}${_gh_raw_content_prefix}-${data}/${version}/metadata.conf${N0_COLOR}" 1>&2
 		return 1
 	fi
 
@@ -77,7 +77,7 @@ install_module()
 	# we do not accept content in places other than CBSD, test it
 	_prefix23=$( substr --pos=0 --len=23 --str="${MODULE_DIR}" )
 	if [ "${_prefix23}" != "/usr/local/cbsd/modules" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: MODULE_DIR != /usr/local/cbsd/modules in manifest: ${N2_COLOR}${MODULE_DIR}${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: MODULE_DIR != /usr/local/cbsd/modules in manifest: ${N2_COLOR}${MODULE_DIR}${N0_COLOR}" 1>&2
 		return 1
 	fi
 
@@ -88,13 +88,13 @@ install_module()
 				${RMDIR_CMD} ${MODULE_DIR} >/dev/null 2>&1 || true
 				# still exist ?
 				[ ! -d "${MODULE_DIR}" ] && return 0
-				${ECHO} "${N1_COLOR}${CBSD_APP}: MODULE_DIR already exist: ${N2_COLOR}${MODULE_DIR}${N1_COLOR}. Maybe you want to upgrade: ${N2_COLOR}cbsd module mode=upgrade ${data}${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}${CIX_APP}: MODULE_DIR already exist: ${N2_COLOR}${MODULE_DIR}${N1_COLOR}. Maybe you want to upgrade: ${N2_COLOR}cbsd module mode=upgrade ${data}${N0_COLOR}" 1>&2
 				return 1
 			fi
 			;;
 		upgrade)
 			if [ ! -d "${MODULE_DIR}" ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: MODULE_DIR doesn't exist: ${N2_COLOR}${MODULE_DIR}${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}${CIX_APP}: MODULE_DIR doesn't exist: ${N2_COLOR}${MODULE_DIR}${N0_COLOR}" 1>&2
 				return 1
 			fi
 			cd ${MODULE_DIR}
@@ -107,14 +107,14 @@ install_module()
 			# restore CBSD PATH
 			export PATH="${CBSDPATH}"
 			if [ ${_ret} -ne 0 ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: git pull error${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}${CIX_APP}: git pull error${N0_COLOR}" 1>&2
 				return 1
 			fi
 			return 0
 			;;
 	esac
 
-	${ECHO} "${N1_COLOR}${CBSD_APP}: clonning: ${N2_COLOR}${GIT_CMD} clone --depth=1 --single-branch ${_gh_remote_url} ${MODULE_DIR}${N0_COLOR}" 1>&2
+	${ECHO} "${N1_COLOR}${CIX_APP}: clonning: ${N2_COLOR}${GIT_CMD} clone --depth=1 --single-branch ${_gh_remote_url} ${MODULE_DIR}${N0_COLOR}" 1>&2
 	CBSDPATH="${PATH}"
 	# reset CBSD PATH
 	# it is necessary due to git used external command with conflict with CBSD path
@@ -124,14 +124,14 @@ install_module()
 	# restore CBSD PATH
 	export PATH="${CBSDPATH}"
 	if [ ${_ret} -ne 0 ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: clone error${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: clone error${N0_COLOR}" 1>&2
 		return 1
 	fi
 
-	${ECHO} "${N1_COLOR}${CBSD_APP}: module installed: ${N2_COLOR}${data}${N0_COLOR}" 1>&2
+	${ECHO} "${N1_COLOR}${CIX_APP}: module installed: ${N2_COLOR}${data}${N0_COLOR}" 1>&2
 
 	if [ -r "${MODULE_DIR}/message.txt" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: module post-install message:${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: module post-install message:${N0_COLOR}" 1>&2
 		${CAT_CMD} ${MODULE_DIR}/message.txt
 	fi
 
@@ -143,9 +143,9 @@ list_module()
 {
 	printf "${H1_COLOR}${BOLD}%-18s  %-3s${N0_COLOR}\n" "MODULE" "STATUS"
 
-	${FIND_CMD} ${distdir}/modules/ -mindepth 1 -maxdepth 1 -name \*.d -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | ${SED_CMD} 's/\.d//g' | while read _dir; do
+	${FIND_CMD} ${CIX_DISTDIR}/modules/ -mindepth 1 -maxdepth 1 -name \*.d -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | ${SED_CMD} 's/\.d//g' | while read _dir; do
 		# check for CBSD module signature: metadata.conf
-		[ ! -r ${distdir}/modules/${_dir}.d/metadata.conf ] && continue
+		[ ! -r ${CIX_DISTDIR}/modules/${_dir}.d/metadata.conf ] && continue
 
 		# check if module enabled (todo: via nc.inventory facts?)
 		if [ -r ${workdir}/etc/modules.conf ]; then
@@ -165,12 +165,12 @@ list_module()
 	done
 
 	# sub-modules for forms.d
-	if [ -d ${distdir}/modules/forms.d ]; then
+	if [ -d ${CIX_DISTDIR}/modules/forms.d ]; then
 
-		${FIND_CMD} ${distdir}/modules/forms.d/ -mindepth 1 -maxdepth 1 -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | while read _dir; do
+		${FIND_CMD} ${CIX_DISTDIR}/modules/forms.d/ -mindepth 1 -maxdepth 1 -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | while read _dir; do
 			# check for CBSD module signature: metadata.conf
 
-			[ ! -r ${distdir}/modules/forms.d/${_dir}/metadata.conf ] && continue
+			[ ! -r ${CIX_DISTDIR}/modules/forms.d/${_dir}/metadata.conf ] && continue
 
 			# forms always available
 			_status="on"
@@ -183,7 +183,7 @@ list_module()
 ## MAIN
 export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 [ -z "${GIT_CMD}" ] && GIT_CMD=$( which git )
-[ -z "${GIT_CMD}" -o ! -x "${GIT_CMD}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no such git, please install first: ${N2_COLOR}pkg install -y devel/git${N0_COLOR}"
+[ -z "${GIT_CMD}" -o ! -x "${GIT_CMD}" ] && err 1 "${N1_COLOR}${CIX_APP}: no such git, please install first: ${N2_COLOR}pkg install -y devel/git${N0_COLOR}"
 
 # parse args
 for i in $*; do
@@ -200,9 +200,9 @@ case "${mode}" in
 	install|upgrade)
 		[ -z "${version}" ] && version="main"
 		if [ -z "${data}" ]; then
-			${FIND_CMD} ${distdir}/modules/ -mindepth 1 -maxdepth 1 -name \*.d -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | ${SED_CMD} 's/\.d//g' | while read data; do
+			${FIND_CMD} ${CIX_DISTDIR}/modules/ -mindepth 1 -maxdepth 1 -name \*.d -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | ${SED_CMD} 's/\.d//g' | while read data; do
 				# check for CBSD module signature: metadata.conf
-				[ ! -r ${distdir}/modules/${data}.d/metadata.conf ] && continue
+				[ ! -r ${CIX_DISTDIR}/modules/${data}.d/metadata.conf ] && continue
 				# skip base/contrib mods
 				case "${data}" in
 					bsdconf|cbsd_queue|pkg|forms-brctl|forms-jrctl)
@@ -212,7 +212,7 @@ case "${mode}" in
 				echo "* upgrade for: ${data}" 1>&2
 				install_module
 			done
-			${FIND_CMD} ${distdir}/modules/forms.d/ -mindepth 1 -maxdepth 1 -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | while read _tmp; do
+			${FIND_CMD} ${CIX_DISTDIR}/modules/forms.d/ -mindepth 1 -maxdepth 1 -type d -exec ${BASENAME_CMD} {} \; | ${SORT_CMD} | while read _tmp; do
 				data="forms-${_tmp}"
 				echo "* upgrade for: ${data}" 1>&2
 				install_module
@@ -225,7 +225,7 @@ case "${mode}" in
 		list_module
 		;;
 	*)
-		err 1 "${N1_COLOR}${CBSD_APP}: unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP}: unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
 		;;
 esac
 
diff --git a/system/srcup b/system/srcup
--- a/system/srcup
+++ b/system/srcup
@@ -123,9 +123,9 @@ init_git()
 
 	[ -n "${ogit_flags}" ] && git_flags="${ogit_flags}"
 	if [ -n "${git_flags}" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: git_flags set to: ${N2_COLOR}${git_flags}${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: git_flags set to: ${N2_COLOR}${git_flags}${N0_COLOR}" 1>&2
 	fi
-	${ECHO} "${N1_COLOR}${CBSD_APP} hint: you can adjust the git_flags= through configs: ${N2_COLOR}~cbsd/etc/srcup.conf ${N1_COLOR}or${N2_COLOR} ~cbsd/etc/srcup-${platform}.conf${N0_COLOR}" 1>&2
+	${ECHO} "${N1_COLOR}${CIX_APP} hint: you can adjust the git_flags= through configs: ${N2_COLOR}~cbsd/etc/srcup.conf ${N1_COLOR}or${N2_COLOR} ~cbsd/etc/srcup-${platform}.conf${N0_COLOR}" 1>&2
 
 	set -o xtrace
 	cd ${dst} && ${SCM} init
@@ -156,7 +156,7 @@ svn_checkout()
 	fi
 	${ECHO} "${N1_COLOR}Processing svn update...${N0_COLOR}"
 	[ -z "${rev}" ] && rev="head"
-	cbsdlogger NOTICE ${CBSD_APP}: processing svn update: ${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}
+	cbsdlogger NOTICE ${CIX_APP}: processing svn update: ${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}
 	echo "${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}"
 	nice -n 19 ${IDLE_IONICE} ${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}
 	_ret=$?
@@ -175,7 +175,7 @@ git_checkout()
 
 	if [ -d "${dst}/.git" ]; then
 		echo "cd ${dst} && ${SCM} ${git_flags} branch ${SCM_GIT_BRANCH}"
-		cbsdlogger NOTICE ${CBSD_APP}: processing git checkout: ${SCM_GIT_BRANCH} in ${dst}
+		cbsdlogger NOTICE ${CIX_APP}: processing git checkout: ${SCM_GIT_BRANCH} in ${dst}
 
 		local CBSDPATH="${PATH}"
 		# reset CBSD PATH
@@ -194,8 +194,8 @@ git_checkout()
 		_p2=${SCM_GIT_BRANCH##*${_remotes}}
 		_branch=${_p2##*${_origin}}
 
-		[ -z "${_branch}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: empty branch var SCM_GIT_BRANCH${N0_COLOR}"
-		${ECHO} "${N1_COLOR}${CBSD_APP} swith to branch: ${N2_COLOR}${_branch}${N0_COLOR}"
+		[ -z "${_branch}" ] && err 1 "${N1_COLOR}${CIX_APP} error: empty branch var SCM_GIT_BRANCH${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP} swith to branch: ${N2_COLOR}${_branch}${N0_COLOR}"
 
 		nice -n 19 ${IDLE_IONICE} ${SCM} pull ${git_pull_flags}
 		_ret=$?
@@ -211,7 +211,7 @@ git_checkout()
 		# restore CBSD PATH
 		export PATH="${CBSDPATH}"
 	else
-		${ECHO} "${N1_COLOR}${CBSD_APP}: clone error: no ${N2_COLOR}.git${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP}: clone error: no ${N2_COLOR}.git${N0_COLOR}"
 		_ret=1
 	fi
 
@@ -339,7 +339,7 @@ case "${checkout_method}" in
 		diff_time=$(( end_time - st_time ))
 		diff_time=$( displaytime ${diff_time} )
 		${ECHO} "${N1_COLOR}svn_checkout src done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
-		cbsdlogger NOTICE ${CBSD_APP}: svn_checkout src done in ${diff_time}. with errcode: ${_ret}
+		cbsdlogger NOTICE ${CIX_APP}: svn_checkout src done in ${diff_time}. with errcode: ${_ret}
 		;;
 	git*)
 		st_time=$( ${DATE_CMD} +%s )
@@ -362,7 +362,7 @@ case "${checkout_method}" in
 		diff_time=$(( end_time - st_time ))
 		diff_time=$( displaytime ${diff_time} )
 		${ECHO} "${N1_COLOR}git_checkout src done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
-		cbsdlogger NOTICE ${CBSD_APP}: svn_checkout src done in ${diff_time}. with errcode: ${_ret}
+		cbsdlogger NOTICE ${CIX_APP}: svn_checkout src done in ${diff_time}. with errcode: ${_ret}
 		;;
 	*)
 		err 1 "${ECHO}unknown checkout method, please specify it via: ${N2_COLOR}srcup.conf${N0_COLOR}"
@@ -371,7 +371,7 @@ esac
 [ -n "${opatch}" ] && patch="${opatch}"
 # todo: apply_cbsd_patch should be x11, not sign for global patch
 if [ "${apply_cbsd_patch}" = "1" ]; then
-	${ECHO} "${N1_COLOR}${CBSD_APP}: apply patch: ${N2_COLOR}apply_cbsd_patch=1${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP}: apply patch: ${N2_COLOR}apply_cbsd_patch=1${N0_COLOR}"
 fi
 
 register_src
diff --git a/tools/apply b/tools/apply
--- a/tools/apply
+++ b/tools/apply
@@ -42,7 +42,7 @@ EXTHELP="wf_cbsdfile"
 . "${subrdir}"/strings.subr
 
 # push original location: we need restore it before exit
-OCBSD_PWD="${CBSD_PWD}"
+OCIX_PWD="${CIX_PWD}"
 
 cwd=
 jname=
@@ -64,12 +64,12 @@ export CBSDFILE_RECURSIVE=1
 
 # init CBSDfile data
 if [ -n "${cwd}" ]; then
-	[ ! -r "${cwd}"/CBSDfile ] && err 1 "${N1_COLOR}${CBSD_APP}: no such CBSDfile: ${N2_COLOR}${cwd}/CBSDfile${N0_COLOR}"
+	[ ! -r "${cwd}"/CBSDfile ] && err 1 "${N1_COLOR}${CIX_APP}: no such CBSDfile: ${N2_COLOR}${cwd}/CBSDfile${N0_COLOR}"
 	cbsdfile="${cwd}/CBSDfile"
 	cd "${cwd}" || err 1 "Can not cd to cwd"
 fi
 
-# exported OCBSD_PWD as original PWD path: we neet to restore it on exit
+# exported OCIX_PWD as original PWD path: we neet to restore it on exit
 . "${subrdir}"/cbsdfile.subr
 
 . "${subrdir}"/time.subr
@@ -82,7 +82,7 @@ apply_jail()
 	local _runscript=$( ${MKTEMP_CMD} )
 	local _ret
 
-	${ECHO} "${N1_COLOR}${CBSD_APP}: apply jail-forms class: ${N2_COLOR}${jname}::${applyforms}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP}: apply jail-forms class: ${N2_COLOR}${jname}::${applyforms}${N0_COLOR}"
 
 	# generate runscript
 	printf "env " > ${_runscript}
@@ -91,7 +91,7 @@ apply_jail()
 	/bin/sh ${_runscript}
 	_ret=$?
 	if [ ${_ret} -ne 0 ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP} ${W1_COLOR}apply failed, runscript:${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP} ${W1_COLOR}apply failed, runscript:${N0_COLOR}"
 		${CAT_CMD} ${_runscript}
 		echo
 	fi
@@ -180,8 +180,8 @@ if [ "${num_env}" -eq 1 ]; then
 	diff_time=$(( end_time - st_time ))
 	diff_time=$( displaytime ${diff_time} )
 
-	${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}" 1>&2
-	cd ${OCBSD_PWD}
+	${ECHO} "${N1_COLOR}${CIX_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}" 1>&2
+	cd ${OCIX_PWD}
 	exit 0
 fi
 
@@ -205,9 +205,9 @@ cur_env=1
 # todo:
 # SUDO_USER for DOAS?
 for jname in ${jail_list} ${bhyve_list}; do
-	# we must inherit CBSD_PWD via cwd= for cbsd-related function in postcreate_ action
+	# we must inherit CIX_PWD via cwd= for cbsd-related function in postcreate_ action
 	# shellcheck disable=2086
-	task_id_cur=$( task mode=new logfile=${tmpdir}/${task_owner}.${jname}.log.$$ client_id=${jname} autoflush=0 owner=${task_owner} ${ENV_CMD} SUDO_USER="${SUDO_USER}" NOCOLOR=${NOCOLOR} /usr/local/bin/cbsd apply multiple=${max_env} cur_env=${cur_env} cbsdfile=${Makefile} jname=${jname} cwd=${CBSD_PWD} )
+	task_id_cur=$( task mode=new logfile=${tmpdir}/${task_owner}.${jname}.log.$$ client_id=${jname} autoflush=0 owner=${task_owner} ${ENV_CMD} SUDO_USER="${SUDO_USER}" NOCOLOR=${NOCOLOR} /usr/local/bin/cbsd apply multiple=${max_env} cur_env=${cur_env} cbsdfile=${Makefile} jname=${jname} cwd=${CIX_PWD} )
 	if [ -z "${task_id}" ]; then
 		task_id="${task_id_cur}"
 	else
@@ -225,8 +225,8 @@ multiple_processing_spawn -o ${task_owner} -n "apply"
 end_time=$( ${DATE_CMD} +%s )
 diff_time=$(( end_time - st_time ))
 diff_time=$( displaytime ${diff_time} )
-${ECHO} "${N1_COLOR}${CBSD_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
+${ECHO} "${N1_COLOR}${CIX_APP} done ${N2_COLOR}in ${diff_time}${N0_COLOR}"
 
-cd ${OCBSD_PWD}
+cd ${OCIX_PWD}
 
 exit 0
diff --git a/tools/expose b/tools/expose
--- a/tools/expose
+++ b/tools/expose
@@ -82,7 +82,7 @@ if [ -z "${jname}" -a -n "${ojname}" ]; then
 fi
 
 # check for cloud function when CBSDfile exist
-Makefile="${CBSD_PWD}/CBSDfile"
+Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" ]; then
 	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}" 1>&2
 	. ${Makefile}
@@ -103,7 +103,7 @@ if [ -r "${Makefile}" ]; then
 			break
 		fi
 		done
-		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
+		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
 	fi
 else
 	#jname="${all_jail_list}"
@@ -111,7 +111,7 @@ else
 fi
 
 if [ ${cbsd_api} -eq 1 ]; then
-	err 0 "${N1_COLOR}${CBSD_APP}: expose for API/remote not supported yet, skip for expose rule: ${N2_COLOR}mode=${mode} in=${in}${N0_COLOR}"
+	err 0 "${N1_COLOR}${CIX_APP}: expose for API/remote not supported yet, skip for expose rule: ${N2_COLOR}mode=${mode} in=${in}${N0_COLOR}"
 fi
 
 # "$1" - check values
@@ -122,11 +122,11 @@ is_valid_port()
 	_port="${1}"
 
 	if is_number "${_port}"; then
-		err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}wrong port values: ${N2_COLOR}${_port}${N0_COLOR}"
+		err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}wrong port values: ${N2_COLOR}${_port}${N0_COLOR}"
 	fi
 
 	if [ ${_port} -lt 1 -o ${_port} -gt 65535 ]; then
-		err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}wrong port range (1-65535): ${N2_COLOR}${_port}${N0_COLOR}"
+		err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}wrong port range (1-65535): ${N2_COLOR}${_port}${N0_COLOR}"
 	fi
 
 	return 0
@@ -206,7 +206,7 @@ fw_expose_add()
 	[ "${inaddr}" = "nodeip" ] && inaddr="0"
 
 	if [ -z "${inaddr}" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: inaddr not IPv4 address, skip: ${N2_COLOR}${inaddr}${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: inaddr not IPv4 address, skip: ${N2_COLOR}${inaddr}${N0_COLOR}" 1>&2
 		return 1
 	fi
 
@@ -218,7 +218,7 @@ fw_expose_add()
 		_ret=$?
 
 		if [ ${_ret} -ne 1 ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: inaddr not IPv4 address, skip: ${N2_COLOR}${_inaddr}${N0_COLOR}" 1>&2
+			${ECHO} "${N1_COLOR}${CIX_APP}: inaddr not IPv4 address, skip: ${N2_COLOR}${_inaddr}${N0_COLOR}" 1>&2
 			return 1
 		fi
 		_inaddr="${IWM}"
@@ -227,7 +227,7 @@ fw_expose_add()
 	fi
 
 	if [ -z "${jip}" -o "${jip}" = "0" ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: outaddr not IPv4 address, skip: ${N2_COLOR}${jip}${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: outaddr not IPv4 address, skip: ${N2_COLOR}${jip}${N0_COLOR}" 1>&2
 		return 1
 	fi
 
@@ -236,7 +236,7 @@ fw_expose_add()
 	_ret=$?
 
 	if [ ${_ret} -ne 1 ]; then
-		${ECHO} "${N1_COLOR}${CBSD_APP}: outaddr not IPv4 address, skip: ${N2_COLOR}${jip}${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: outaddr not IPv4 address, skip: ${N2_COLOR}${jip}${N0_COLOR}" 1>&2
 		return 1
 	fi
 
@@ -253,7 +253,7 @@ fw_expose_add()
 	_ret=$?
 
 	if [ ${_ret} -eq 0 ]; then
-		${ECHO} "${W1_COLOR}${CBSD_APP} warning: ${N1_COLOR}port already in use on ${_inaddr}?: ${N2_COLOR}${proto}/${in}${N0_COLOR}"
+		${ECHO} "${W1_COLOR}${CIX_APP} warning: ${N1_COLOR}port already in use on ${_inaddr}?: ${N2_COLOR}${proto}/${in}${N0_COLOR}"
 		case "${proto}" in
 			tcp)
 				${ECHO} "${N1_COLOR}Test string: '${N2_COLOR}${_test}${N1_COLOR}' (check errcode)${N0_COLOR}"
@@ -276,11 +276,11 @@ fw_expose_add()
 	case "${in}" in
 		0)
 			${ECHO} "${N1_COLOR}CBSD Expose for ${jname}: ${N2_COLOR}ALL via ${_inaddr} -> ${jip}${N0_COLOR}"
-			cbsdlogger NOTICE ${CBSD_APP}: ${jname}: ALL ${_inaddr}:${jip}
+			cbsdlogger NOTICE ${CIX_APP}: ${jname}: ALL ${_inaddr}:${jip}
 			;;
 		*)
 			${ECHO} "${N1_COLOR}CBSD Expose for ${jname}: ${N2_COLOR}${in} -> ${out} (${proto})${N0_COLOR} from IPs (${fromips})${N0_COLOR}"
-			cbsdlogger NOTICE ${CBSD_APP}: ${jname}: proto: ${proto}: ${in}:${out} from IPs: ${fromips}
+			cbsdlogger NOTICE ${CIX_APP}: ${jname}: proto: ${proto}: ${in}:${out} from IPs: ${fromips}
 			;;
 	esac
 
@@ -324,21 +324,21 @@ fw_expose_add()
 					done
 
 					if [ -z "${_pass_iface}" ]; then
-						${ECHO} "${N1_COLOR}${CBSD_APP}: unable to determine pass interface for: ${N2_COLOR}${_inaddr}${N0_COLOR}" 1>&2
+						${ECHO} "${N1_COLOR}${CIX_APP}: unable to determine pass interface for: ${N2_COLOR}${_inaddr}${N0_COLOR}" 1>&2
 						return 1
 					fi
 
 # + iface
-#					cbsdlogger NOTICE "${CBSD_APP}: rdr pass on ${_pass_iface} proto {tcp, udp} from any to ${_inaddr}/32 -> ${jip}/32"
-#					cbsdlogger NOTICE "${CBSD_APP}: nat pass on ${_pass_iface} from ${jip}/32 to !${rfcnet} -> ${_inaddr}"
+#					cbsdlogger NOTICE "${CIX_APP}: rdr pass on ${_pass_iface} proto {tcp, udp} from any to ${_inaddr}/32 -> ${jip}/32"
+#					cbsdlogger NOTICE "${CIX_APP}: nat pass on ${_pass_iface} from ${jip}/32 to !${rfcnet} -> ${_inaddr}"
 
 #					${CAT_CMD} >> ${etcdir}/pfnat.conf <<EOF
 #rdr pass on ${_pass_iface} proto {tcp, udp} from any to ${_inaddr}/32 -> ${jip}/32 # ${COMMENT}
 #nat pass on ${_pass_iface} from ${jip}/32 to !${rfcnet} -> ${_inaddr} # ${COMMENT}
 #EOF
 
-					cbsdlogger NOTICE "${CBSD_APP}: rdr pass proto {tcp, udp} from ${fromips} to ${_inaddr}/32 -> ${jip}/32"
-					cbsdlogger NOTICE "${CBSD_APP}: nat pass from ${jip}/32 to !${rfcnet} -> ${_inaddr}"
+					cbsdlogger NOTICE "${CIX_APP}: rdr pass proto {tcp, udp} from ${fromips} to ${_inaddr}/32 -> ${jip}/32"
+					cbsdlogger NOTICE "${CIX_APP}: nat pass from ${jip}/32 to !${rfcnet} -> ${_inaddr}"
 
 					# RDR
 					${CAT_CMD} >> ${etcdir}/pfrdr.conf <<EOF
@@ -360,14 +360,14 @@ EOF
 			naton
 			;;
 		nft)
-			cbsdlogger NOTICE "${CBSD_APP}: nft: add table ip nat${jname}"
+			cbsdlogger NOTICE "${CIX_APP}: nft: add table ip nat${jname}"
 			${NFT_CMD} add table ip nat${jname}
-			cbsdlogger NOTICE "${CBSD_APP}: nft: add prerouring/postrouting chain for: nat${jname}"
+			cbsdlogger NOTICE "${CIX_APP}: nft: add prerouring/postrouting chain for: nat${jname}"
 			${NFT_CMD} -- add chain ip nat${jname} prerouting { type nat hook prerouting priority -100 \; }
 			${NFT_CMD} add chain ip nat${jname} postrouting { type nat hook postrouting priority 100 \; }
-			cbsdlogger NOTICE "${CBSD_APP}: nft: ${NFT_CMD} add rule ip nat${jname} prerouting tcp dport ${in} dnat to ${jip}:${out}"
+			cbsdlogger NOTICE "${CIX_APP}: nft: ${NFT_CMD} add rule ip nat${jname} prerouting tcp dport ${in} dnat to ${jip}:${out}"
 			${NFT_CMD} add rule ip nat${jname} prerouting tcp dport ${in} dnat to ${jip}:${out}
-			cbsdlogger NOTICE "${CBSD_APP}: nft: ${NFT_CMD} add rule ip nat${jname} postrouting ip daddr ${jip} masquerade"
+			cbsdlogger NOTICE "${CIX_APP}: nft: ${NFT_CMD} add rule ip nat${jname} postrouting ip daddr ${jip} masquerade"
 			${NFT_CMD} add rule ip nat${jname} postrouting ip daddr ${jip} masquerade
 			# not needed?
 			# sysctl "net.ipv4.ip_forward=1"
@@ -436,7 +436,7 @@ fw_expose_clear()
 					#if ${GREP_CMD} -E "([tcp][udp])-([[:digit:]]){1,5}-${jname}"$ ${etcdir}/${i} 2>&1; then
 					if ${GREP_CMD} -E "([tcp][udp])-([[:digit:]]){1,5}-${jname} " ${etcdir}/${i} 2>&1; then
 						${CP_CMD} -a ${etcdir}/${i} ${tmpdir}/${i}
-						cbsdlogger NOTICE ${CBSD_APP}: fw_expose_clear for ${jname}: via ${i}
+						cbsdlogger NOTICE ${CIX_APP}: fw_expose_clear for ${jname}: via ${i}
 						#${GREP_CMD} -E -v "([tcp][udp])-([[:digit:]]{1,5})-${jname}"$ ${tmpdir}/${i} | ${GREP_CMD} "." > ${etcdir}/${i}
 						${GREP_CMD} -E -v "([tcp][udp])-([[:digit:]]{1,5})-${jname} " ${tmpdir}/${i} | ${GREP_CMD} "." > ${etcdir}/${i}
 						_need_naton=1
@@ -453,14 +453,14 @@ fw_expose_clear()
 			else
 				fwnum=$( ${CAT_CMD} ${ftmpdir}/${jname}-expose_fwnum )
 			fi
-			cbsdlogger NOTICE ${CBSD_APP}: fw_expose_clear for ${jname}: delete ipfw rule ${fwnum}
+			cbsdlogger NOTICE ${CIX_APP}: fw_expose_clear for ${jname}: delete ipfw rule ${fwnum}
 			${IPFW_CMD} delete ${fwnum}
 			;;
 		nft)
 			${NFT_CMD} list table ip nat${jname} >/dev/null 2>&1
 			_ret=$?
 			if [ ${_ret} -eq 0 ]; then
-				cbsdlogger NOTICE ${CBSD_APP}: nft_expose_clear for ${jname}: ${NFT_CMD} delete table ip nat${jname}
+				cbsdlogger NOTICE ${CIX_APP}: nft_expose_clear for ${jname}: ${NFT_CMD} delete table ip nat${jname}
 				${NFT_CMD} delete table ip nat${jname}
 			fi
 	esac
@@ -482,7 +482,7 @@ fw_expose_delete()
 	else
 		cbsdsqlrw ${exposefile} "DELETE FROM expose WHERE pin=${in} AND pout=${out} AND proto=\"${proto}\" AND inaddr=\"${inaddr}\" AND outaddr=\"${outaddr}\" AND fromips=\"${fromips}\""
 	fi
-	cbsdlogger NOTICE ${CBSD_APP}: fw_expose_delete: delete config for: ${jname}
+	cbsdlogger NOTICE ${CIX_APP}: fw_expose_delete: delete config for: ${jname}
 
 	case "${nat_enable}" in
 		pf)
@@ -510,7 +510,7 @@ if [ -z "$1" ]; then
 	exit 0
 fi
 
-[ -z "${jname}" ] && err 1 "${N1_COLOR}${CBSD_APP}: give me jname${N0_COLOR}"
+[ -z "${jname}" ] && err 1 "${N1_COLOR}${CIX_APP}: give me jname${N0_COLOR}"
 
 . ${subrdir}/rcconf.subr
 [ $? -eq 1 ] && err 1 "${N1_COLOR}no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
@@ -533,11 +533,11 @@ else
 	jip="${outaddr}"
 fi
 
-[ -z "${jip}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to determine jail ip: ${N2_COLOR}${jname}${N0_COLOR}"
+[ -z "${jip}" ] && err 1 "${N1_COLOR}${CIX_APP}: unable to determine jail ip: ${N2_COLOR}${jname}${N0_COLOR}"
 
 exposefile="${jailsysdir}/${jname}/expose.sqlite"
 
-[ ! -r "${exposefile}" ] && /usr/local/bin/cbsd ${miscdir}/updatesql ${exposefile} ${distdir}/share/system-expose.schema expose
+[ ! -r "${exposefile}" ] && /usr/local/bin/cbsd ${miscdir}/updatesql ${exposefile} ${CIX_DISTDIR}/share/system-expose.schema expose
 
 [ -z "${in}" -a -n "${out}" ] && in="${out}"
 [ -z "${out}" -a -n "${in}" ] && out="${in}"
@@ -571,14 +571,14 @@ if [ -z "${in}" ]; then
 	[ -z "${inaddr}" ] && err 1 "${N1_COLOR}Empty ${N2_COLOR}in${N0_COLOR}"
 	case "${inaddr}" in
 		[Nn][Oo][Dd][Ee]*)
-			err 1 "${N1_COLOR}${CBSD_APP}: Please use any IPv4 when 'in' args empty: ${N2_COLOR}inaddr=${N0_COLOR}"
+			err 1 "${N1_COLOR}${CIX_APP}: Please use any IPv4 when 'in' args empty: ${N2_COLOR}inaddr=${N0_COLOR}"
 			;;
 	esac
 
 	if [ "${inaddr}" != "0" -a "${inaddr}" != "nodeip" ]; then
 		iptype ${inaddr}
 		ret=$?
-		[ ${ret} -ne 1 ] && err 1 "${N1_COLOR}${CBSD_APP}: not valid IPv4 for 'inaddr': ${N2_COLOR}${inaddr}${N0_COLOR}"
+		[ ${ret} -ne 1 ] && err 1 "${N1_COLOR}${CIX_APP}: not valid IPv4 for 'inaddr': ${N2_COLOR}${inaddr}${N0_COLOR}"
 	fi
 	in="0"		# 'all'
 fi
@@ -598,10 +598,10 @@ case "${mode}" in
 		if [ ${ret} -eq 0 ]; then
 			# check for dup
 			_res=$( cbsdsqlro ${exposefile} "SELECT pin FROM expose WHERE pin=${pin} AND pout=${pout} AND proto=\"${proto}\" AND inaddr=\"${inaddr}\" AND outaddr=\"${outaddr}\" AND fromips=\"${fromips}\"" | ${HEAD_CMD} -n 1 )
-			[ -n "${_res}" ] && err 1 "${N1_COLOR}${CBSD_APP}: already exist in DB: pin=${pin} AND pout=${pout} AND proto=\"${proto}\" AND inaddr=\"${inaddr}\" AND outaddr=\"${outaddr}\" AND fromips=\"${fromips}\""
+			[ -n "${_res}" ] && err 1 "${N1_COLOR}${CIX_APP}: already exist in DB: pin=${pin} AND pout=${pout} AND proto=\"${proto}\" AND inaddr=\"${inaddr}\" AND outaddr=\"${outaddr}\" AND fromips=\"${fromips}\""
 			cbsdsqlrw ${exposefile} "INSERT INTO expose ( pin, pout, proto, inaddr, outaddr, fromips ) VALUES ( ${in}, ${out}, \"${proto}\", \"${inaddr}\", \"${outaddr}\", \"${fromips}\" )"
 		else
-			err 1 "${N1_COLOR}${CBSD_APP}: fw_expose_add error: ${ret}${N0_COLOR}"
+			err 1 "${N1_COLOR}${CIX_APP}: fw_expose_add error: ${ret}${N0_COLOR}"
 		fi
 		;;
 	delete)
diff --git a/tools/forms b/tools/forms
--- a/tools/forms
+++ b/tools/forms
@@ -75,7 +75,7 @@ if [ "${1}" != "--help" -a "${1}" != "--args" ]; then
 		formfile="${1}"
 		[ ! -f "${1}" ] && err 1 "${N1_COLOR}No such form file: ${N2_COLOR}${formfile}${N0_COLOR}"
 		shift
-		param=$( cbsdsqlro ${formfile} SELECT param FROM forms ORDER BY CAST\(order_id AS int\) | ${XARGS_CMD} )
+		param=$( cbsdsqlro ${formfile} "SELECT param FROM forms ORDER BY CAST(order_id AS int)" | ${XARGS_CMD} )
 		MYOPTARG="${MYOPTARG} ${param}"
 	fi
 fi
@@ -117,7 +117,7 @@ selected_defaultitem=
 
 dialog_menu_main()
 {
-	local _par VAL
+	local _par= VAL=
 	local btitle="$DIALOG_BACKTITLE"
 	local prompt="Use menu to select and edit items"
 	local hline=
@@ -129,10 +129,10 @@ dialog_menu_main()
 	[ -n "${selected_defaultitem}" ] && defaultitem="${selected_defaultitem}"
 	[ -n "${jname}" ] && mytargets="for ${jname} "
 
-	local title
-	local _mydesc
+	local title=
+	local _mydesc=
 	local menu_list=
-	local _id=0 _delimer_check
+	local _id=0 _delimer_check=
 
 	if [ -n "${forms_title}" ]; then
 		title="${forms_title}"
@@ -201,26 +201,26 @@ dialog_menu_main()
 	f_dialog_menutag_store "$menu_choice"
 	f_dialog_default_store "$menu_choice"
 
-	return $retval
+	return ${retval}
 }
 
 
 # $1 table
 get_radio()
 {
-	local param
+	local param=
 	local table="${1}"
 
 	[ -z "${table}" ] && return 1
 
-	param_list=$( cbsdsqlro ${formfile} SELECT text FROM ${table} ORDER BY CAST\(order_id AS int\) | ${XARGS_CMD} )
+	param_list=$( cbsdsqlro ${formfile} "SELECT text FROM ${table} ORDER BY CAST(order_id AS int)" | ${XARGS_CMD} )
 	local menu_list=
 	local x=0
-	local _par VAL
-	local btitle="$DIALOG_BACKTITLE"
+	local _par= VAL
+	local btitle="$DIALOG_BACKTITLE"=
 	local prompt="Use menu for select"
 	local hline=
-	local defaultitem
+	local defaultitem=
 	defaultitem="yes"
 
 	local title=" ${table} "
@@ -235,32 +235,32 @@ get_radio()
 	cbsd_menubox
 	retval=$?
 
-	mtag=$( cbsdsqlro ${formfile} SELECT text FROM ${table} WHERE text=\"${menu_choice}\" )
+	mtag=$( cbsdsqlro ${formfile} "SELECT text FROM ${table} WHERE text='${menu_choice}'" )
 	f_dialog_data_sanitize menu_choice
 
-	return $retval
+	return ${retval}
 }
 
 
 # $1 table
 get_checkbox()
 {
-	local param
+	local param=
 	local table="${1}"
 
 	[ -z "${table}" ] && return 1
 
-	param_list=$( cbsdsqlro ${formfile} SELECT text FROM ${table} ORDER BY CAST\(order_id AS int\) | ${XARGS_CMD} )
+	param_list=$( cbsdsqlro ${formfile} "SELECT text FROM ${table} ORDER BY CAST(order_id AS int)" | ${XARGS_CMD} )
 	local menu_list=
 	local x=0
-	local _par VAL
+	local _par= VAL=
 	local btitle="$DIALOG_BACKTITLE"
 	local prompt="Use menu for select"
 	local hline=
-	local defaultitem
+	local defaultitem=
 
 	local title=" syslog "
-	local _mydesc
+	local _mydesc=
 
 	local menu_list=
 
@@ -326,15 +326,15 @@ get_checkbox()
 		esac
 	done
 
-	mtag=$( cbsdsqlro ${formfile} SELECT id FROM ${table} WHERE text=\"${menu_choice}\" )
+	mtag=$( cbsdsqlro ${formfile} "SELECT id FROM ${table} WHERE text='{menu_choice}'" )
 
 	return ${retval}
 }
 
 reload_forms_full()
 {
-	local sql_part="SELECT param FROM ${table} WHERE type != \"subtable\" ORDER BY CAST(order_id AS int)"
-	param=$( cbsdsqlro ${formfile} ${sql_part} )
+	local sql_part="SELECT param FROM ${table} WHERE type != 'subtable' ORDER BY CAST(order_id AS int)"
+	param=$( cbsdsqlro ${formfile} "${sql_part}" )
 	load_forms
 	load_new
 }
@@ -343,7 +343,7 @@ reload_forms_full()
 # INDEX (namespace)
 get_group_id()
 {
-	local _new _group_id _new_group_id
+	local _new= _group_id= _new_group_id=
 
 	while getopts "a:g:" opt; do
 		case "${opt}" in
@@ -391,7 +391,7 @@ get_group_id()
 
 get_order_id()
 {
-	local _new _order_id _new_order_id
+	local _new= _order_id= _new_order_id=
 
 	while getopts "a:g:" opt; do
 		case "${opt}" in
@@ -454,14 +454,14 @@ group_add()
 	if [ -z "${_group_id}" ]; then
 		_res=$( get_group_id -a add -g ${_config} 2>&1 )
 		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP} error: ${_res}${N0_COLOR}"
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP} error: ${_res}${N0_COLOR}"
 		_group_id="${_res}"
 	fi
 
 	if [ -z "${_order_id}" ]; then
 		_res=$( get_order_id -a add -g ${_config} 2>&1 )
 		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP} error: ${_res}${N0_COLOR}"
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP} error: ${_res}${N0_COLOR}"
 		_order_id="${_res}"
 	fi
 
@@ -472,7 +472,7 @@ group_add()
 	_res=$( ${_file} -a add -i ${_group_id} -o ${_order_id} -f ${formfile} 2>&1 )
 	_ret=$?
 	if [ ${_ret} -ne 0 ]; then
-		err 1 "${N1_COLOR}${CBSD_APP} error: group_add: ${_res}${N0_COLOR}"
+		err 1 "${N1_COLOR}${CIX_APP} error: group_add: ${_res}${N0_COLOR}"
 	fi
 
 	return 0
@@ -481,7 +481,7 @@ group_add()
 # $1 - overvrite index
 group_del()
 {
-	local _config _file _order_id
+	local _config= _file= _order_id=
 
 	while getopts "c:o:" opt; do
 		case "${opt}" in
@@ -501,7 +501,8 @@ group_del()
 # inputform
 get_helper_value()
 {
-	local _input _retval _xattr _type _link _mtag _group_id _delete=0
+	local _input= _retval= _xattr= _type=
+	local _link= _mtag= _group_id= _delete=0
 
 	[ "${1}" = "delete" ] && _delete=1
 
@@ -591,15 +592,15 @@ EOF
 
 export_vars()
 {
-	local param _id type idx
-	local _tmp _res param
+	local param= _id= type= idx=
+	local _tmp= _res= param=
 
 	[ ! -f ${formfile} ] && err 1 "${N1_COLOR}formfile not found: ${N2_COLOR}${formfile}${N0_COLOR}"
 	[ -z "${table}" ] && table="forms"
 
 	idx=0
 
-	_param="$( cbsdsqlro ${formfile} "SELECT param FROM ${table}" ORDER BY CAST\(order_id AS int\) | ${XARGS_CMD} )"
+	_param="$( cbsdsqlro ${formfile} "SELECT param FROM ${table} ORDER BY CAST(order_id AS int)" | ${XARGS_CMD} )"
 
 	helpername=$( cbsdsqlro ${formfile} "SELECT helpername FROM system" )
 	# First SQL sequence is 1
@@ -607,18 +608,17 @@ export_vars()
 	_seq_ind=0
 	# H_<env> prefered, we need to pop/push it before/after config env file
 
-
 	for param in ${_param}; do
 		_seq_ind=$(( _seq_ind + 1 ))
-		_id="$( cbsdsqlro ${formfile} "SELECT idx FROM ${table} WHERE param=\"${param}\" LIMIT 1" )"
-		type="$( cbsdsqlro ${formfile} "SELECT type FROM ${table} WHERE idx=\"${_id}\"" )"
+		_id="$( cbsdsqlro ${formfile} \"SELECT idx FROM ${table} WHERE param='${param}' LIMIT 1\" )"
+		type="$( cbsdsqlro ${formfile} \"SELECT type FROM ${table} WHERE idx='${_id}'\" )"
 		case "${type}" in
 			hiddendelim|subtable|delimer)
 				continue
 				;;
 		esac
 
-		_res="$( cbsdsqlro ${formfile} "SELECT cur FROM ${table} WHERE idx=\"${_id}\"" )"
+		_res="$( cbsdsqlro ${formfile} \"SELECT cur FROM ${table} WHERE idx='${_id}'\" )"
 		[ -z "${_res}" ] && continue
 
 		readconf forms_export_vars.conf
@@ -632,8 +632,8 @@ export_vars()
 
 show_vars()
 {
-	local param _id type idx
-	local _tmp _res param _all_vars
+	local param= _id= type= idx=
+	local _tmp= _res= param= _all_vars=
 
 	[ -z "${formfile}" ] && err 1 "${N1_COLOR}empty formfile:${N0_COLOR}"
 	if [ ! -r ${formfile} ]; then
@@ -645,7 +645,7 @@ show_vars()
 	[ -z "${table}" ] && table="forms"
 
 	idx=0
-	_param="$( cbsdsqlro ${formfile} "SELECT param FROM ${table}" ORDER BY CAST\(order_id AS int\) | ${XARGS_CMD} )"
+	_param="$( cbsdsqlro ${formfile} \"SELECT param FROM ${table} ORDER BY CAST\(order_id AS int\)\" | ${XARGS_CMD} )"
 
 	helpername=$( cbsdsqlro ${formfile} "SELECT helpername FROM system" )
 	# First SQL sequence is 1
@@ -656,8 +656,8 @@ show_vars()
 
 	for param in ${_param}; do
 		_seq_ind=$(( _seq_ind + 1 ))
-		_id="$( cbsdsqlro ${formfile} "SELECT idx FROM ${table} WHERE param=\"${param}\" LIMIT 1" )"
-		type="$( cbsdsqlro ${formfile} "SELECT type FROM ${table} WHERE idx=\"${_id}\"" )"
+		_id="$( cbsdsqlro ${formfile} \"SELECT idx FROM ${table} WHERE param='${param}' LIMIT 1\" )"
+		type="$( cbsdsqlro ${formfile} \"SELECT type FROM ${table} WHERE idx='${_id}'\" )"
 		case "${type}" in
 			hiddendelim|subtable|delimer)
 				continue
@@ -685,8 +685,9 @@ show_vars()
 #
 # Check for cbsd_puppet_jname jail exist
 if [ "${jname}" != "CBSDSYS" ]; then
-#	jstatus jname=${cbsd_helper_jname} >/dev/null 2>&1
-#	[ $? -ne 1 ] && err 1 "${N1_COLOR}No such ${N2_COLOR}${cbsd_helper_jname}${N1_COLOR} for helper ${N2_COLOR}${helper_module}${N1_COLOR}. Please fetch it via repo command or create from template${N0_COLOR}"
+	# jstatus jname=${cbsd_helper_jname} >/dev/null 2>&1
+	# [ $? -ne 1 ] && err 1 "${N1_COLOR}No such ${N2_COLOR}${cbsd_helper_jname}${N1_COLOR} for helper ${N2_COLOR}${helper_module}${N1_COLOR}. Please fetch it via repo command or create from template${N0_COLOR}"
+	true
 else
 	with_bootstrap=1
 fi
diff --git a/tools/images b/tools/images
--- a/tools/images
+++ b/tools/images
@@ -84,7 +84,7 @@ get_zfs_image_snap()
 		${ZFS_CMD} list -t snapshot ${_zfssrc}@start > /dev/null 2>&1
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			err 1 "${CBSD_APP}: no such snapshot ${_zfssrc}@start"
+			err 1 "${CIX_APP}: no such snapshot ${_zfssrc}@start"
 		else
 			_zfssrc_snap="${_zfssrc}@start"
 		fi
@@ -103,7 +103,7 @@ images_register()
 	local _tmpfile= _remove_source=0
 	local _imgname= _imgpath= _buildah_platform=
 
-	[ ! -r ${dbdir}/images.sqlite ] && ${miscdir}/updatesql ${dbdir}/images.sqlite ${distdir}/share/local-images.schema images
+	[ ! -r ${dbdir}/images.sqlite ] && ${miscdir}/updatesql ${dbdir}/images.sqlite ${CIX_DISTDIR}/share/local-images.schema images
 
 	# can process multiple several cases:
 	# a) name ( lookup in ~cbsd/import/<name>.img
@@ -112,9 +112,9 @@ images_register()
 
 	if [ -n "${name}" -a -z "${path}" ]; then
 		path="${importdir}/${name}.img"
-		[ ! -r ${path} ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: file not found ${N2_COLOR}${path}${N0_COLOR}"
+		[ ! -r ${path} ] && stderr 1 "${N1_COLOR}${CIX_APP} error: file not found ${N2_COLOR}${path}${N0_COLOR}"
 	else
-		[ -z "${path}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}path= or name=${N1_COLOR} is mandatory${N0_COLOR}"
+		[ -z "${path}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}path= or name=${N1_COLOR} is mandatory${N0_COLOR}"
 		_res=$( ${BASENAME_CMD} "${path}" )
 		_ret=0
 		_md5=$( ${miscdir}/cbsd_md5 "${path}" )
@@ -127,12 +127,12 @@ images_register()
 			# fetch from remote
 			if [ "${prefix4}" = "http" ]; then
 				_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5='${_md5}'" 2>/dev/null )
-				[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist, source: ${N2_COLOR}${source}${N0_COLOR}"
-				${ECHO} "${N1_COLOR}${CBSD_APP}: remote resource: ${N2_COLOR}${path}${N0_COLOR}" 1>&2
+				[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist, source: ${N2_COLOR}${source}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP}: remote resource: ${N2_COLOR}${path}${N0_COLOR}" 1>&2
 				_tmpfile="${importdir}/${_md5}.img"
-				${ECHO} "${N1_COLOR}${CBSD_APP}: ${FETCH_CMD} -o \"${_tmpfile}\" \"${path}\"${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}${CIX_APP}: ${FETCH_CMD} -o \"${_tmpfile}\" \"${path}\"${N0_COLOR}" 1>&2
 				${FETCH_CMD} -o "${_tmpfile}" "${path}"
-				[ ! -r ${_tmpfile} ] && err 1 "${N1_COLOR}${CBSD_APP} error: unable to fetch: ${N2_COLOR}${path} -> ${_tmpfile}${N0_COLOR}"
+				[ ! -r ${_tmpfile} ] && err 1 "${N1_COLOR}${CIX_APP} error: unable to fetch: ${N2_COLOR}${path} -> ${_tmpfile}${N0_COLOR}"
 				opath="${path}"
 				_file=$( ${BASENAME_CMD} ${path} )
 				name=$( echo ${_file} | ${SED_CMD} 's:\.img::g' )
@@ -143,10 +143,10 @@ images_register()
 			fi
 		else
 			if [ -z "${BUILDAH_CMD}" ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: buildah command not found. If ${path} is a registry resource,"
+				${ECHO} "${N1_COLOR}${CIX_APP}: buildah command not found. If ${path} is a registry resource,"
 				${ECHO} "please install package then re-run 'cbsd initenv': ${N2_COLOR}buildah${N0_COLOR}"
 			else
-				${ECHO} "${N1_COLOR}${CBSD_APP}: let's try using the ${BUILDAH_CMD} utility...${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CIX_APP}: let's try using the ${BUILDAH_CMD} utility...${N0_COLOR}"
 
 				# doesn't work? for some reason ignored
 				export XDG_CONFIG_HOME="${workdir}/.config"
@@ -161,7 +161,7 @@ images_register()
 				_imgname=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah pull --platform ${_buildah_platform} ${path} 2>/tmp/images.$$ )
 				_ret=$?
 				if [ ${_ret} -ne 0 -o -z "${_imgname}" ]; then
-					${ECHO} "${N1_COLOR}${CBSD_APP}: unable to pull${N0_COLOR}"
+					${ECHO} "${N1_COLOR}${CIX_APP}: unable to pull${N0_COLOR}"
 					if [ -r /tmp/images.$$ ]; then
 						${CAT_CMD} /tmp/images.$$
 						${RM_CMD} -f /tmp/images.$$
@@ -180,13 +180,13 @@ images_register()
 				fi
 
 				if [ ${_ret} -ne 0 ]; then
-					err 1 "${N1_COLOR}${CBSD_APP}: buildah image not found: ${N2_COLOR}${path}${N0_COLOR}"
+					err 1 "${N1_COLOR}${CIX_APP}: buildah image not found: ${N2_COLOR}${path}${N0_COLOR}"
 				fi
 
 				_image_sha256=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah inspect "${_imgname}" | ${JQ_CMD} -r '.OCIv1.rootfs.diff_ids[-1]' )
 				_ret=$?
 				if [ ${_ret} -ne 0 -o -z "${_image_sha256}" ]; then
-					${ECHO} "${N1_COLOR}${CBSD_APP}: unable to create find tom layer in image ${_imgname}${N0_COLOR}"
+					${ECHO} "${N1_COLOR}${CIX_APP}: unable to create find tom layer in image ${_imgname}${N0_COLOR}"
 					exit 1
 				fi
                 echo "image sha256: ${_image_sha256}"
@@ -209,7 +209,7 @@ images_register()
                     _zvol=$(${ZFS_CMD} get -Ho value name ${workdir}/basejail/buildah)
                     _ret=$?
                     if [ -z "${_zvol}" -o ${_ret} -ne 0 ]; then
-                        ${ECHO} "${N1_COLOR}${CBSD_APP}: cannot find zfs volume for ${workdir}/basejail/buildah${N0_COLOR}"
+                        ${ECHO} "${N1_COLOR}${CIX_APP}: cannot find zfs volume for ${workdir}/basejail/buildah${N0_COLOR}"
                         exit 1
                     fi
                     _image_volume="${_zvol}/${_image_volume_id}"
@@ -220,7 +220,7 @@ images_register()
                         ${ZFS_CMD} snapshot ${_image_volume}@${_md5}
                         _ret=$?
                         if [ ${_ret} -ne 0 ]; then
-                            ${ECHO} "${N1_COLOR}${CBSD_APP}: unable to create ZFS snapshot for image volume ${_image_volume} ${N0_COLOR}"
+                            ${ECHO} "${N1_COLOR}${CIX_APP}: unable to create ZFS snapshot for image volume ${_image_volume} ${N0_COLOR}"
                             exit 1
                         fi
                         _image_snapshot="${_image_volume}@${_md5}"
@@ -229,9 +229,9 @@ images_register()
 					jcreate jname="${_md5}" host_hostname=${_md5}.my.domain zfs_snapsrc="${_image_snapshot}"\
 						ver=empty baserw=1 pkg_bootstrap=0 floatresolv=0 applytpl=0 etcupdate_init=0
 					_ret=$?
-					[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}unable to create jail: ${N2_COLOR}jcreate jname="${_md5}" host_hostname=${_md5}.my.domain${N0_COLOR}"
+					[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}unable to create jail: ${N2_COLOR}jcreate jname="${_md5}" host_hostname=${_md5}.my.domain${N0_COLOR}"
 					_rootfs="${workdir}/jails-data/${_md5}-data"
-					[ ! -d "${_rootfs}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no data dir for: ${_md5}: ${N2_COLOR}${_rootfs}${N0_COLOR}"
+					[ ! -d "${_rootfs}" ] && err 1 "${N1_COLOR}${CIX_APP}: no data dir for: ${_md5}: ${N2_COLOR}${_rootfs}${N0_COLOR}"
 					junregister jname="${_md5}"
 					${RM_CMD} -f ${jailrcconfdir}/rc.conf_${_md5}
 					# whats about systemdir stuff?
@@ -253,7 +253,7 @@ images_register()
                     _res=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah from --name ${_md5} ${_imgname} 2>/tmp/images.$$ )
                     _ret=$?
                     if [ ${_ret} -ne 0 -o -z "${_res}" ]; then
-                        ${ECHO} "${N1_COLOR}${CBSD_APP}: unable to create buildah container from ${_imgname}${N0_COLOR}"
+                        ${ECHO} "${N1_COLOR}${CIX_APP}: unable to create buildah container from ${_imgname}${N0_COLOR}"
                         if [ -r /tmp/images.$$ ]; then
                             ${CAT_CMD} /tmp/images.$$
                             ${RM_CMD} -f /tmp/images.$$
@@ -265,7 +265,7 @@ images_register()
                     _imgpath=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah mount ${_res} 2>/tmp/images.$$ )
                     _ret=$?
                     if [ ${_ret} -ne 0 -o -z "${_res}" ]; then
-                        ${ECHO} "${N1_COLOR}${CBSD_APP}: unable to mount buildah container from ${_res}${N0_COLOR}"
+                        ${ECHO} "${N1_COLOR}${CIX_APP}: unable to mount buildah container from ${_res}${N0_COLOR}"
                         if [ -r /tmp/images.$$ ]; then
                             ${CAT_CMD} /tmp/images.$$
                             ${RM_CMD} -f /tmp/images.$$
@@ -304,7 +304,7 @@ images_register()
 				stderr 0 "${N1_COLOR}registered: ${N2_COLOR}${_md5}${N0_COLOR}"
 			fi
 		fi
-		[ ! -r "${path}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: resource not found ${N2_COLOR}${path}${N0_COLOR}"
+		[ ! -r "${path}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: resource not found ${N2_COLOR}${path}${N0_COLOR}"
 		path=$( ${REALPATH_CMD} ${path} )
 
 		if [ -z "${name}" ]; then
@@ -317,24 +317,24 @@ images_register()
 	_md5=$( ${miscdir}/cbsd_md5 "${source}" )
 
 	_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5='${_md5}'" 2>/dev/null )
-	[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist: source: ${N2_COLOR}${source}${N0_COLOR}"
+	[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist: source: ${N2_COLOR}${source}${N0_COLOR}"
 
 	# detect image emulator
 	imgpart out=${tmpdir}/hdr.$$ jname=${path} part=header mode=extract
 	_ret=$?
 	if [ ${_ret} -ne 0 ]; then
 		[ -r ${tmpdir}/hdr.$$ ] && ${RM_CMD} -f ${tmpdir}/hdr.$$
-		stderr 1 "${N1_COLOR}${CBSD_APP} error: imgpart failed, not CBSD image?: ${N2_COLOR}imgpart out=${tmpdir}/hdr.$$ jname=${imgpath} part=header mode=extract${N0_COLOR}"
+		stderr 1 "${N1_COLOR}${CIX_APP} error: imgpart failed, not CBSD image?: ${N2_COLOR}imgpart out=${tmpdir}/hdr.$$ jname=${imgpath} part=header mode=extract${N0_COLOR}"
 	fi
 	. ${tmpdir}/hdr.$$
 	${RM_CMD} ${tmpdir}/hdr.$$
-	[ -z "${emulator}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: unable to determine emulator for: ${N2_COLOR}${path}${N0_COLOR}"
+	[ -z "${emulator}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: unable to determine emulator for: ${N2_COLOR}${path}${N0_COLOR}"
 
 	# import jail
 	if [ ${zfsfeat} -eq 1 ]; then
 		jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain
 		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}unable to import image: ${N2_COLOR}jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain${N0_COLOR}"
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}unable to import image: ${N2_COLOR}jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain${N0_COLOR}"
 		junregister jname=${_md5}
 		${RM_CMD} -f ${jailrcconfdir}/rc.conf_${_md5}
 		# whats about systemdir stuff?
@@ -352,9 +352,9 @@ images_register()
 	else
 		jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain
 		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to import image: ${N2_COLOR}jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain${N0_COLOR}"
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: unable to import image: ${N2_COLOR}jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain${N0_COLOR}"
 		if [ ! -d "${workdir}/jails-data/${_md5}-data" ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: no data dir: ${N2_COLOR}${workdir}/jails-data/${_md5}-data${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: no data dir: ${N2_COLOR}${workdir}/jails-data/${_md5}-data${N0_COLOR}"
 			jremove jname=${_md5} || true
 			exit 1
 		fi
@@ -363,8 +363,8 @@ images_register()
 		# whats about systemdir stuff?
 		${RM_CMD} -rf ${jailsysdir}/${_md5}
 		[ ! -d "${workdir}/basejail/${_md5}" ] && ${MKDIR_CMD} -p "${workdir}/basejail/${_md5}"
-		[ ! -d "${workdir}/basejail/${_md5}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to create basejail dir: ${workdir}/basejail/${_md5}${N0_COLOR}"
-		${ECHO} "${N1_COLOR}${CBSD_APP}: convert image ${_md5} data as basedir: ${N2_COLOR}${workdir}/basejail/${_md5}${N0_COLOR}"
+		[ ! -d "${workdir}/basejail/${_md5}" ] && err 1 "${N1_COLOR}${CIX_APP}: unable to create basejail dir: ${workdir}/basejail/${_md5}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CIX_APP}: convert image ${_md5} data as basedir: ${N2_COLOR}${workdir}/basejail/${_md5}${N0_COLOR}"
 		${RSYNC_CMD} -a --hard-links --links --acls --xattrs --numeric-ids --recursive --partial --delete ${workdir}/jails-data/${_md5}-data/ ${workdir}/basejail/${_md5}/
 		${CHFLAGS_CMD} noschg ${workdir}/jails-data/${_md5}-data
 		${RM_CMD} -rf noschg ${workdir}/jails-data/${_md5}-data ${workdir}/jails-fstab/${_md5}
@@ -395,7 +395,7 @@ images_delete()
 	local _data= _data_root= _jaildatadir_root=
 
 	_res=$( cbsdsqlro images "SELECT md5 FROM images WHERE md5='${md5}'" 2>/dev/null )
-	[ -z "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: not exist in DB: ${N2_COLOR}${md5}${N0_COLOR}"
+	[ -z "${_res}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: not exist in DB: ${N2_COLOR}${md5}${N0_COLOR}"
 
 	# try to remove ZFS first
 	###
@@ -412,24 +412,24 @@ images_delete()
 			${ZFS_CMD} list -t snapshot ${_zfssrc_snap} > /dev/null 2>&1
 			_ret=$?
 			if [ ${_ret} -eq 0 ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: snap exist, destroy: ${N2_COLOR}${_zfssrc_snap}${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}${CIX_APP}: snap exist, destroy: ${N2_COLOR}${_zfssrc_snap}${N0_COLOR}" 1>&2
 				${ZFS_CMD} destroy ${_zfssrc_snap}
 				_ret=$?
-				[ ${_ret} -ne 0 ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: unable to destroy snapshot: ${N2_COLOR}${ZFS_CMD} destroy ${_zfssrc_snap}${N0_COLOR}"
+				[ ${_ret} -ne 0 ] && stderr 1 "${N1_COLOR}${CIX_APP} error: unable to destroy snapshot: ${N2_COLOR}${ZFS_CMD} destroy ${_zfssrc_snap}${N0_COLOR}"
 			fi
 
 			if [ "${_data}" != "${_data_root}" ]; then
-				${ECHO} "${N1_COLOR}${CBSD_APP}: destroy image dataset: ${N2_COLOR}${_data}${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}${CIX_APP}: destroy image dataset: ${N2_COLOR}${_data}${N0_COLOR}" 1>&2
 				${ZFS_CMD} destroy ${_data}
 				_ret=$?
-				[ ${_ret} -ne 0 ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: unable to destroy image dataset: ${N2_COLOR}${ZFS_CMD} destroy ${_data}${N0_COLOR}"
+				[ ${_ret} -ne 0 ] && stderr 1 "${N1_COLOR}${CIX_APP} error: unable to destroy image dataset: ${N2_COLOR}${ZFS_CMD} destroy ${_data}${N0_COLOR}"
 			fi
 		else
-			${ECHO} "${N1_COLOR}${CBSD_APP}: dataset not exist: ${N2_COLOR}${ZFS_CMD} get -Ho value name ${_jaildatadir}${N0_COLOR}" 1>&2
+			${ECHO} "${N1_COLOR}${CIX_APP}: dataset not exist: ${N2_COLOR}${ZFS_CMD} get -Ho value name ${_jaildatadir}${N0_COLOR}" 1>&2
 		fi
 	else
 		if [ ! -d "${workdir}/basejail/${md5}" ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: no such directory: ${N2_COLOR}${workdir}/basejail/${md5}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: no such directory: ${N2_COLOR}${workdir}/basejail/${md5}${N0_COLOR}"
 		else
 			${CHFLAGS_CMD} noschg ${workdir}/basejail/${md5}
 			${RM_CMD} -rf ${workdir}/basejail/${md5}
@@ -449,7 +449,7 @@ case "${mode}" in
 		exit $?
 		;;
 	delete|remove|destroy)
-		[ -z "${md5}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}md5= ${N1_COLOR}is mandatory${N0_COLOR}"
+		[ -z "${md5}" ] && stderr 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}md5= ${N1_COLOR}is mandatory${N0_COLOR}"
 		images_delete
 		;;
 	list)
diff --git a/tools/jail2iso b/tools/jail2iso
--- a/tools/jail2iso
+++ b/tools/jail2iso
@@ -173,13 +173,13 @@ if [ ${baserw} -ne 1 ]; then
 	init_basedir
 else
 	nobase=1
-	${ECHO} "${N1_COLOR}${CBSD_APP}: baserw=1, skip init_basedir: ${N2_COLOR}${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP}: baserw=1, skip init_basedir: ${N2_COLOR}${jname}${N0_COLOR}"
 fi
 
 [ -n "${oname}" ] && name="${oname}"
 
 init_kerneldir
-${ECHO} "${N1_COLOR}${CBSD_APP}: KERNEL_DIR: ${N2_COLOR}${KERNEL_DIR}${N0_COLOR}"
+${ECHO} "${N1_COLOR}${CIX_APP}: KERNEL_DIR: ${N2_COLOR}${KERNEL_DIR}${N0_COLOR}"
 
 [ -n "${label}" ] && LABEL="${label}"
 [ -n "${product}" ] && PRODUCT="${product}"
@@ -305,10 +305,10 @@ epilogue_img()
 	# for ISO too?
 	[ "${media}" = "memstick" ] && return 0
 
-	/usr/local/cbsd/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf fsck_y_enable="YES" >/dev/null
+	${CIX_DISTDIR}/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf fsck_y_enable="YES" >/dev/null
 
 	# MFS override?
-	[ -n "${host_hostname}" ] && /usr/local/cbsd/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf hostname="${host_hostname}" >/dev/null
+	[ -n "${host_hostname}" ] && ${CIX_DISTDIR}/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf hostname="${host_hostname}" >/dev/null
 	[ -n "${oip4_addr}" ] && ip4_addr="${oip4_addr}"
 	[ -n "${ogw4}" ] && gw4="${ogw4}"
 	[ -z "${nic}" ] && nic="DEFAULT"
@@ -320,16 +320,16 @@ epilogue_img()
 			if [ -n "${ip4_addr}" -a "${ip4_addr}" != "0" ]; then
 				case "${ip4_addr}" in
 					[Dd][Hh][Cc][Pp])
-						/usr/local/cbsd/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf ifconfig_${nic}="DHCP" >/dev/null
+						${CIX_DISTDIR}/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf ifconfig_${nic}="DHCP" >/dev/null
 						;;
 					*)
-						/usr/local/cbsd/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf ifconfig_${nic}="inet ${ip4_addr}" >/dev/null
+						${CIX_DISTDIR}/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf ifconfig_${nic}="inet ${ip4_addr}" >/dev/null
 						;;
 				esac
 			fi
 		fi
 	else
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf mfsbsd_enable="YES"
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf mfsbsd_enable="YES"
 
 	fi
 
@@ -349,7 +349,7 @@ epilogue_img()
 #	fi
 
 	if [ -z "${mfsbsd_defaultrouter}" ]; then
-		[ -n "${gw4}" ] && /usr/local/cbsd/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf defaultrouter="${gw4}" >/dev/null
+		[ -n "${gw4}" ] && ${CIX_DISTDIR}/misc/cbsdsysrc -qf ${_rootfs}/etc/rc.conf defaultrouter="${gw4}" >/dev/null
 	fi
 
 	if [ -z "${mfsbsd_nameservers}" ]; then
@@ -366,7 +366,7 @@ epilogue_img()
 		[ -f "/usr/share/zoneinfo/${timezone}" ] && ${CP_CMD} /usr/share/zoneinfo/${timezone} ${_rootfs}/etc/localtime
 	fi
 
-	${ECHO} "${N1_COLOR}${CBSD_APP}: epilogue ${N2_COLOR}/etc/rc.conf:${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP}: epilogue ${N2_COLOR}/etc/rc.conf:${N0_COLOR}"
 	${CAT_CMD} ${_rootfs}/etc/rc.conf
 }
 
@@ -412,7 +412,7 @@ EOF
 
 	_filelist="${distsharedir}/${platform}-filemin_${_ver}.txt.xz"
 
-	[ ! -r ${_filelist} ] && err 1 "${N1_COLOR}${CBSD_APP}: no such index file: ${N2_COLOR}${_filelist}${N0_COLOR}"
+	[ ! -r ${_filelist} ] && err 1 "${N1_COLOR}${CIX_APP}: no such index file: ${N2_COLOR}${_filelist}${N0_COLOR}"
 
 	${ECHO} "${N1_COLOR}mfsroot index: ${N2_COLOR}${_filelist}${N0_COLOR}"
 
@@ -422,7 +422,7 @@ EOF
 		init_basedir
 	fi
 
-	[ -z "${BASE_DIR}" ] && err 1 "${N1_COLOR}${CBSD_APP} empty BASE_DIR${N0_COLOR}"
+	[ -z "${BASE_DIR}" ] && err 1 "${N1_COLOR}${CIX_APP} empty BASE_DIR${N0_COLOR}"
 
 	#echo "copy-binlib filelist=${_filelist} dstdir=${_tmpdir} basedir=${BASE_DIR} chaselibs=1 mtree=1"
 	copy-binlib filelist=${_filelist} dstdir=${_tmpdir} basedir=${BASE_DIR} chaselibs=1 mtree=1
@@ -472,7 +472,7 @@ EOF
 	${UMOUNT_CMD} -f ${DST_DIR} && ${RMDIR_CMD} ${DST_DIR}
 	${MDCONFIG_CMD} -d -u ${DEV}
 
-	${ECHO} "${N1_COLOR}${CBSD_APP} mfsroot done, temp md: ${N2_COLOR}${DEV}${N0_COLOR}" 1>&2
+	${ECHO} "${N1_COLOR}${CIX_APP} mfsroot done, temp md: ${N2_COLOR}${DEV}${N0_COLOR}" 1>&2
 }
 
 
@@ -729,7 +729,7 @@ make_ufs()
 
 	#echo "[debug] cd ${path} && nice -n 19 ${IDPRIO_CMD} 29 ${PAX_CMD} -p eme -rw . ${TMP_DIR}"
 
-	${ECHO} "${N1_COLOR}${CBSD_APP}: make_ufs: media: ${N2_COLOR}${media}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}${CIX_APP}: make_ufs: media: ${N2_COLOR}${media}${N0_COLOR}"
 
 	if [ "${media}" != "mfs" ]; then
 		echo "[debug]cd ${path} && nice -n 19 ${IDPRIO_CMD} 29 ${PAX_CMD} -p eme -rw . ${TMP_DIR}" 1>&2
@@ -785,10 +785,10 @@ make_ufs()
 		fi
 
 		if [ -r "${jailsysdir}/${jname}/loader.conf" ]; then
-			${ECHO} "${N1_COLOR}${CBSD_APP}: custom loader.conf found: ${N2_COLOR}${jailsysdir}/${jname}/loader.conf${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: custom loader.conf found: ${N2_COLOR}${jailsysdir}/${jname}/loader.conf${N0_COLOR}"
 			${CP_CMD} ${jailsysdir}/${jname}/loader.conf ${TMP_DIR}/boot/loader.conf
 		else
-			${ECHO} "${N1_COLOR}${CBSD_APP}: custom loader.conf absent in ${jailsysdir}/${jname}/loader.conf${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: custom loader.conf absent in ${jailsysdir}/${jname}/loader.conf${N0_COLOR}"
 		fi
 	fi
 
@@ -931,7 +931,7 @@ EOF
 		nice -n 19 ${IDPRIO_CMD} 29 ${XZ_CMD} -T${_ncpu} -v -c rw.tar > root.txz
 		_ret=$?
 		${RM_CMD} -f rw.tar
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: make_ufs error for mfs: ${N2_COLOR}${XZ_CMD} -T${_ncpu} -v -c rw.tar > root.txz${N0_COLOR}"
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: make_ufs error for mfs: ${N2_COLOR}${XZ_CMD} -T${_ncpu} -v -c rw.tar > root.txz${N0_COLOR}"
 		${RM_CMD} -rf ${TMP_DIR}
 		TMP_DIR="${OTMP_DIR}"
 
@@ -1012,8 +1012,8 @@ EOF
 		${CP_CMD} -a ${KERNEL_DIR}/boot/kernel/tmpfs.ko ${TMP_DIR}/mfsroot1/boot/modules/
 
 		# ROOTHACK
-		${CP_CMD} -a ${distdir}/modules/roothack.d/init ${TMP_DIR}/mfsroot1/sbin/init
-		${ECHO} "${N1_COLOR}${CBSD_APP}: MFS: * ${N2_COLOR}Create first layer${N0_COLOR}"
+		${CP_CMD} -a ${CIX_DISTDIR}/modules/roothack.d/init ${TMP_DIR}/mfsroot1/sbin/init
+		${ECHO} "${N1_COLOR}${CIX_APP}: MFS: * ${N2_COLOR}Create first layer${N0_COLOR}"
 		echo "${MAKEFS_CMD} -t ffs -f ${MFSROOT_FREE_INODES} -b ${MFSROOT_FREE_BLOCKS} mfsroot ${TMP_DIR}/mfsroot1"
 		#pwd
 
@@ -1306,9 +1306,9 @@ post_module_action()
 
 	if [ -r "${fromfile}" ]; then
 		${CP_CMD} -a ${fromfile} ${TMPFILE}
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${TMPFILE} -x jname
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${TMPFILE} path="${rootpath}"
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${TMPFILE} data="${rootpath}"
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${TMPFILE} -x jname
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${TMPFILE} path="${rootpath}"
+		${CIX_DISTDIR}/misc/cbsdsysrc -qf ${TMPFILE} data="${rootpath}"
 	else
 
 		# additional area
@@ -1359,7 +1359,7 @@ case "${media}" in
 		${cmd}
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			err 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}${cmd}${N0_COLOR}"
+			err 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}${cmd}${N0_COLOR}"
 		fi
 		echo "mkisoimages done"
 		;;
@@ -1367,7 +1367,7 @@ case "${media}" in
 		make_ufs
 
 		${MAKEFS_CMD} -B little -o version=2 -o softupdates=1 -o label=${LABEL} ${dstdir}/${dstname}.part ${TMP_DIR}
-		[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}makefs failed${N0_COLOR}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}makefs failed${N0_COLOR}"
 
 		if [ ${efi} -eq 1 ]; then
 			# efifat was deprecated in 12.2-RELEASE
@@ -1378,7 +1378,7 @@ case "${media}" in
 				_efi_part=$( ${MKTEMP_CMD} )
 				${TRUNCATE_CMD} -s64M ${_efi_part}
 				unit=$( ${MDCONFIG_CMD} -a -t vnode -f ${_efi_part} 2>&1 )
-				[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
 				echo "stamp loader.efi: ${_efi_part}"
 				tmp_mp=$( ${MKTEMP_CMD} -d )
 				/sbin/newfs_msdos -F 32 -c 1 -L EFISYS /dev/${unit}
@@ -1399,7 +1399,7 @@ case "${media}" in
 				${MKIMG_CMD} -s gpt -b ${TMP_DIR}/boot/pmbr -p efi:=${_efi_part} -p freebsd-boot:=${TMP_DIR}/boot/gptboot -p freebsd-ufs:=${dstdir}/${dstname}.part -p freebsd-swap::1M -o ${dstdir}/${dstname}
 				${RM_CMD} -f ${_efi_part}
 			else
-				err 1 "${N1_COLOR}${CBSD_APP}: no such boot1.efi or loader.efi: ${N2_COLOR}${TMP_DIR}/boot/${N0_COLOR}"
+				err 1 "${N1_COLOR}${CIX_APP}: no such boot1.efi or loader.efi: ${N2_COLOR}${TMP_DIR}/boot/${N0_COLOR}"
 			fi
 		else
 			# gptboot not for aarch64: jail2iso: no such boot/gptboot in hier: /usr/jails/tmp/cloud-iso.56237/boot/gptboot
@@ -1412,7 +1412,7 @@ case "${media}" in
 		${ECHO} "${N1_COLOR}Now you can burn image to USB memstick via\n ${N2_COLOR}dd if=${dstdir}/${dstname} of=/dev/da${W2_COLOR}X${N2_COLOR} bs=1m conv=\"sync\"${N0_COLOR}"
 		;;
 	mfs)
-		if [ ! -x ${distdir}/modules/roothack.d/init ]; then
+		if [ ! -x ${CIX_DISTDIR}/modules/roothack.d/init ]; then
 			${ECHO} "${N1_COLOR}MFS media requires an extra 'init' (roothack) file that is not included in the default CBSD distribution${N0_COLOR}"
 			${ECHO} "${N1_COLOR}Please get this file via 'roothack' module:${N0_COLOR}"
 			${ECHO} "${N2_COLOR}  cbsd module mode=install roothack${N0_COLOR}"
@@ -1424,14 +1424,15 @@ case "${media}" in
 		OTMP_DIR="${TMP_DIR}"
 		TMP_DIR="${TMP_DIR}/root"
 		if [ "${mfs_struct_only}" = "1" ]; then
-			[ ! -d "${dstdir}" ] && ${MKDIR_CMD} -p ${dstdir}/
-			${MV_CMD} ${TMP_DIR}/* ${dstdir}/
-			#${RMDIR_CMD} ${TMP_DIR} ${OTMP_DIR}
-			${ECHO} "${N1_COLOR}${CBSD_APP} mfs_struct_only struct: ${N2_COLOR}${dstdir}${N0_COLOR}"
+			[ ! -d "${dstdir}" ] && ${MKDIR_CMD} -p ${dstdir}
+			echo "${RSYNC_CMD} -avz ${TMP_DIR}/ ${dstdir}/"
+			${RSYNC_CMD} -avz ${TMP_DIR}/ ${dstdir}/
+			${RM_CMD} -rf ${TMP_DIR}
+			${ECHO} "${N1_COLOR}${CIX_APP} mfs_struct_only struct: ${N2_COLOR}${dstdir}${N0_COLOR}"
 			exit 0
 		fi
 		${MAKEFS_CMD} -B little -o version=2 -o softupdates=1 -o label=${LABEL} ${dstdir}/${dstname}.part ${TMP_DIR}
-		[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}makefs failed${N0_COLOR}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP} error: ${N2_COLOR}makefs failed${N0_COLOR}"
 
 		if [ -n "${extra_part}" ]; then
 			[ -z "${extra_part_label}" ] && extra_part_label="cbsdextra"
@@ -1447,7 +1448,7 @@ case "${media}" in
 				_efi_part=$( ${MKTEMP_CMD} )
 				${TRUNCATE_CMD} -s64M ${_efi_part}
 				unit=$( ${MDCONFIG_CMD} -a -t vnode -f ${_efi_part} 2>&1 )
-				[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
 				echo "stamp loader.efi: ${_efi_part}"
 				tmp_mp=$( ${MKTEMP_CMD} -d )
 				/sbin/newfs_msdos -F 32 -c 1 -L EFISYS /dev/${unit}
@@ -1483,7 +1484,7 @@ case "${media}" in
 				fi
 				${RM_CMD} -f ${_efi_part}
 			else
-				err 1 "${N1_COLOR}${CBSD_APP}: no such boot1.efi or loader.efi: ${N2_COLOR}${TMP_DIR}/boot/${N0_COLOR}"
+				err 1 "${N1_COLOR}${CIX_APP}: no such boot1.efi or loader.efi: ${N2_COLOR}${TMP_DIR}/boot/${N0_COLOR}"
 			fi
 		else
 			# swap?
@@ -1536,11 +1537,11 @@ case "${media}" in
 						${MKIMG_CMD} -s gpt -b ${TMP_DIR}/boot/pmbr -p efi:=${TMP_DIR}/boot/boot1.efifat -p freebsd-boot:=${TMP_DIR}/boot/gptboot ${_swap_args} -p freebsd-ufs:=${dstdir}/${dstname}.part -o ${dstdir}/${dstname}
 					elif [ -r ${TMP_DIR}/boot/boot1.efi ]; then
 						# gptboot not for aarch64: jail2iso: no such boot/gptboot in hier: /usr/jails/tmp/cloud-iso.56237/boot/gptboot
-						[ ! -r ${TMP_DIR}/boot/gptboot ] && err 1 "${N1_COLOR}${CBSD_APP}: no such boot/gptboot in hier: ${N2_COLOR}${TMP_DIR}/boot/gptboot${N0_COLOR}"
+						[ ! -r ${TMP_DIR}/boot/gptboot ] && err 1 "${N1_COLOR}${CIX_APP}: no such boot/gptboot in hier: ${N2_COLOR}${TMP_DIR}/boot/gptboot${N0_COLOR}"
 						_efi_part=$( ${MKTEMP_CMD} )
 						${TRUNCATE_CMD} -s64M ${_efi_part}
 						unit=$( ${MDCONFIG_CMD} -a -t vnode -f ${_efi_part} 2>&1 )
-						[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
+						[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
 						echo "stamp loader.efi: ${_efi_part}"
 						tmp_mp=$( ${MKTEMP_CMD} -d )
 						/sbin/newfs_msdos -F 32 -c 1 -L EFISYS /dev/${unit}
@@ -1564,7 +1565,7 @@ case "${media}" in
 						${RM_CMD} ${_efi_part}
 					else
 						[ -r ${dstdir}/${dstname}.part ] && ${RM_CMD} -f ${dstdir}/${dstname}.part
-						err 1 "${N1_COLOR}${CBSD_APP}: no such boot1.efi or loader.efi: ${N2_COLOR}${TMP_DIR}${N0_COLOR}"
+						err 1 "${N1_COLOR}${CIX_APP}: no such boot1.efi or loader.efi: ${N2_COLOR}${TMP_DIR}${N0_COLOR}"
 					fi
 				else
 					# gptboot not for aarch64: jail2iso: no such boot/gptboot in hier: /usr/jails/tmp/cloud-iso.56237/boot/gptboot
@@ -1597,7 +1598,7 @@ case "${media}" in
 				# deprecated, rewrite:
 				create_img_for_dir ${data} ${dstdir}/${dstname}
 				unit=$( ${MDCONFIG_CMD} -a -t vnode -f ${dstdir}/${dstname} 2>&1 )
-				[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}${CIX_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
 				bhyve_zfs_install
 				;;
 		esac
