Add domain field in jail schema; add cbsd_dot and modified version of daemon as temporary solution of event notification between nodes; increase sqlite3_busy_timeout; set system dir writable for cbsd group;

diff --git a/bin/rexe b/bin/rexe
--- a/bin/rexe
+++ b/bin/rexe
@@ -42,9 +42,9 @@ ssh_connect() {
 		TTYOP="-tt"
 	fi
 
-	#    echo "$THESCRIPT" | ssh -l ${cbsduser} $SSH_ARGS ${TTYOP} "${REMOTE_SHELL}" | \
-	#    ssh -l ${cbsduser} $SSH_ARGS ${TTYOP} "${THESCRIPT}"| \
-	ssh -oControlPath=${sshdir}/sockets/%r@%h:%p $SSH_ARGS ${TTYOP} "/usr/local/bin/cbsd -c \"update_idle ${nodename}\"; ${THESCRIPT}"| \
+	#    echo "$THESCRIPT" | /usr/bin/ssh -l ${cbsduser} $SSH_ARGS ${TTYOP} "${REMOTE_SHELL}" | \
+	#    /usr/bin/ssh -l ${cbsduser} $SSH_ARGS ${TTYOP} "${THESCRIPT}"| \
+	/usr/bin/ssh -oControlPath=${sshdir}/sockets/%r@%h:%p $SSH_ARGS ${TTYOP} "/usr/local/bin/cbsd -c \"update_idle ${nodename}\"; ${THESCRIPT}"| \
 		while read SSH_LINE ; do
 			[ "$QUIET" -lt 1 -a "$SSH_LINE" != "" -a "$MULTIHOST" = "0" ] && echo "$SSH_LINE"
 #			[ "$QUIET" -lt 1 -a "$SSH_LINE" != "" -a "$MULTIHOST" = "1" ] && echo "$SSH_LINE" | sed -e "s/^/$HOST: /"
@@ -59,7 +59,7 @@ ssh_connect() {
 set_hostlist() {
 	# Create a hostlist file.
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG: BUILDING HOST LIST FILE $TEMP_DIR/hostlist" 1>&2
-	rm -f $TEMP_DIR/hostlist || exit 1
+	/bin/rm -f $TEMP_DIR/hostlist || exit 1
 	for HOST in $HOSTLIST ; do
 		echo $HOST >> "$TEMP_DIR/hostlist" || exit 1
 	done
@@ -80,23 +80,25 @@ get_next_host() {
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG[#$CHILDNUM]: Locked hostfile." 1>&2
 
 	# get next host
-	NEXT_HOST=$(head -1 $TEMP_DIR/hostlist)
-	HOSTFILE_LEN=$(wc -l $TEMP_DIR/hostlist | awk '{print $1}')
+	NEXT_HOST=$( /usr/bin/head -1 $TEMP_DIR/hostlist)
+	HOSTFILE_LEN=$( /usr/bin/wc -l $TEMP_DIR/hostlist | /usr/bin/awk '{print $1}')
+
 	if [ -z "$HOSTFILE_LEN" -o "$HOSTFILE_LEN" = 0 ] ; then
-		rm -f "$TEMP_DIR/hostlist.lock"
+		/bin/rm -f "$TEMP_DIR/hostlist.lock"
 		return
 	fi
+
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG[#$CHILDNUM]: Next host: $NEXT_HOST" 1>&2
 
 	# re-write file removing new host
-	rm -f "$TEMP_DIR/hostlist.new"
-	tail -$(( $HOSTFILE_LEN - 1 )) $TEMP_DIR/hostlist > $TEMP_DIR/hostlist.new || exit 1
-	rm -f "$TEMP_DIR/hostlist"
-	mv "$TEMP_DIR/hostlist.new" "$TEMP_DIR/hostlist"
+	/bin/rm -f "$TEMP_DIR/hostlist.new"
+	/usr/bin/tail -$(( $HOSTFILE_LEN - 1 )) $TEMP_DIR/hostlist > $TEMP_DIR/hostlist.new || exit 1
+	/bin/rm -f "$TEMP_DIR/hostlist"
+	/bin/mv "$TEMP_DIR/hostlist.new" "$TEMP_DIR/hostlist"
 
 	# unlock file
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG[#$CHILDNUM]: Removing hostfile lock." 1>&2
-	rm -f "$TEMP_DIR/hostlist.lock"
+	/bin/rm -f "$TEMP_DIR/hostlist.lock"
 
 	# return hostname
 	echo $NEXT_HOST
@@ -110,15 +112,17 @@ run_child() {
 	while [ 1 ] ; do
 		# issue:  Cannot call get_next_host inside $() or `` because our trap won't be able to kill that.
 		#     solution: avoid subshell here by directing to a file.
-		rm -f $TEMP_DIR/$CHILDNUM.next_host
+		/bin/rm -f $TEMP_DIR/$CHILDNUM.next_host
 		get_next_host >$TEMP_DIR/$CHILDNUM.next_host
 		HOST=$( cat $TEMP_DIR/$CHILDNUM.next_host )
+
 		if [ -z "$HOST" ] ; then
-			rm -f "$TEMP_DIR/$CHILDNUM.pid"
+			/bin/rm -f "$TEMP_DIR/$CHILDNUM.pid"
 			break
 		fi
+
 		[ "$DEBUG" -ge 1 ] && echo "DEBUG[#$CHILDNUM]: CONNECT $HOST" 1>&2
-		rm -f "$TEMP_DIR/$CHILDNUM.active"
+		/bin/rm -f "$TEMP_DIR/$CHILDNUM.active"
 		echo "$HOST" > "$TEMP_DIR/$CHILDNUM.active"
 		#	cbsdsql nodes select ip,port,keyfile from nodelist where nodename=\"${HOST}\"
 		NODEDATA=$( cbsdsql nodes select ip,port,keyfile from nodelist where nodename=\"${HOST}\" )
@@ -151,11 +155,11 @@ run_child() {
 
 
 create_temp() {
-	TEMP_DIR=$(mktemp -d $TEMP_BASE/$(basename $0).XXXXXX) || err 1 "Error mktemp"
+	TEMP_DIR=$( /usr/bin/mktemp -d $TEMP_BASE/$(basename $0).XXXXXX) || err 1 "Error mktemp"
 }
 
 destroy_temp() {
-	[ -d "$TEMP_DIR" ] && rm -rf "$TEMP_DIR" 2>/dev/null
+	[ -d "$TEMP_DIR" ] && /bin/rm -rf "$TEMP_DIR" 2>/dev/null
 }
 
 ########################################
@@ -163,23 +167,27 @@ destroy_temp() {
 ########################################
 shutdown() {
 	[ "$DEBUG" -ge 1 ] && echo "DEBUG: shutting down children." 1>&2
-	CPIDS=$(cat $TEMP_DIR/*.pid 2>/dev/null)
+	CPIDS=$( /bin/cat $TEMP_DIR/*.pid 2>/dev/null)
+
 	for CPID in $CPIDS ; do 
 		[ "$DEBUG" -ge 2 ] && echo "DEBUG: Killing pid: $CPID" 1>&2
 		kill -HUP $CPID
 	done
+
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG: shutting down ssh-agent" 1>&2
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG: removing temp dir" 1>&2
+
 	destroy_temp
+
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG: done shutting down." 1>&2
-        exit 1
+	exit 1
 }
 
 spew_hostlist() {
 	echo "HOSTS RUNNING:"  1>&2
-	cat $TEMP_DIR/*.active 2>/dev/null | sed 's/^/    /'  1>&2
+	/bin/cat $TEMP_DIR/*.active 2>/dev/null | sed 's/^/    /'  1>&2
 	echo "HOSTS REMAINING:"  1>&2
-	cat $TEMP_DIR/hostlist 2>/dev/null | sed 's/^/    /'  1>&2
+	/bin/cat $TEMP_DIR/hostlist 2>/dev/null | sed 's/^/    /'  1>&2
 	return
 }
 
@@ -214,14 +222,14 @@ fi
 
 if [ -n "${nodelist}" ]; then
 	[ ! -f "${nodelist}" ] && err 1 "${nodelist} file doesn't exist"
-	HOSTLIST="$(cat $nodelist | sed -e 's/#.*//' | egrep -v "^ *$" )"
+	HOSTLIST="$( /bin/cat $nodelist | /usr/bin/sed -e 's/#.*//' | /usr/bin/egrep -v "^ *$" )"
 	shift
 fi
 
 if [ -n "${netgroup}" ]; then
 	# Negtgoup
 	NETGROUP=$2
-	NETGROUP_LIST="$(getent netgroup $NETGROUP | xargs -n 1 echo | sed -n '/^(.*,$/s/[,(]//gp')"
+	NETGROUP_LIST="$( /usr/bin/getent netgroup $NETGROUP | /usr/bin/xargs -n 1 echo | /usr/bin/sed -n '/^(.*,$/s/[,(]//gp')"
 	[ -z "${NETGROUP_LIST}" ] && err 1 "Failed to get netgroup: $NETGROUP"
 	HOSTLIST="$NETGROUP_LIST $HOSTLIST"
 	shift
@@ -229,14 +237,14 @@ fi
 
 if [ -n "${cmdfile}" ]; then
 	[ ! -e "$cmdfile" ] && err 1 "myssh: Script File '$SCRIPTFILE' does not exist!"
-	THESCRIPT="$THESCRIPT $(cat $cmdfile )"
+	THESCRIPT="$THESCRIPT $( /bin/cat $cmdfile )"
 	shift
 fi
 
-HOSTLIST=$(echo "$HOSTLIST" | sed -e 's/#.*//' | egrep -v "^ *$" )
+HOSTLIST=$(echo "$HOSTLIST" | /usr/bin/sed -e 's/#.*//' | /usr/bin/egrep -v "^ *$" )
 [ -z "${HOSTLIST}" ] && err 1 "host list is empty"
 
-COUNT_HOSTS=$(echo "$HOSTLIST" | wc -w|awk '{printf $1}')
+COUNT_HOSTS=$(echo "$HOSTLIST" |/usr/bin/wc -w|/usr/bin/awk '{printf $1}')
 CONCURRENT=$COUNT_HOSTS
 [ "$COUNT_HOSTS" = "1" ] && MULTIHOST=0
 [ -z "${cmd}" -a -z "${cmdfile}" ] && THESCRIPT=$@
@@ -265,8 +273,8 @@ if [ "${COUNT_HOSTS}" = "1" ]; then
 	SSH_ARGS="-l ${cbsduser} -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=5 -q -oPort=${myport} -i ${mykey} ${myip}"
 	SSHMUX="${sshdir}/sockets/${cbsduser}@${myip}:${myport}"
 	#    [ ! -S "${SSHMUX}" ] && err 1 "No such socket ${SSHMUX}. Please run nodepinger service"
-	ssh -oControlPath=${sshdir}/sockets/%r@%h:%p -t ${SSH_ARGS} ${TTOP} -C "/usr/local/bin/cbsd -c \"update_idle ${nodename}\"; ${THESCRIPT}"
-#	ssh -oControlPath=${sshdir}/sockets/%r@%h:%p -t ${SSH_ARGS} ${TTOP} -C <<CBSD_EOF
+	/usr/bin/ssh -oControlPath=${sshdir}/sockets/%r@%h:%p -t ${SSH_ARGS} ${TTOP} -C "/usr/local/bin/cbsd -c \"update_idle ${nodename}\"; ${THESCRIPT}"
+#	/usr/bin/ssh -oControlPath=${sshdir}/sockets/%r@%h:%p -t ${SSH_ARGS} ${TTOP} -C <<CBSD_EOF
 #${THESCRIPT}
 #CBSD_EOF
 
@@ -284,7 +292,7 @@ CHILDNUM=1
 while [ $CHILDNUM -le $CONCURRENT ] ; do 
 	run_child $CHILDNUM &
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG: FORKED CHILD #$CHILDNUM with pid $!" 1>&2
-	rm -f "$TEMP_DIR/$CHILDNUM.pid"
+	/bin/rm -f "$TEMP_DIR/$CHILDNUM.pid"
 	echo $! > "$TEMP_DIR/$CHILDNUM.pid"
 	CHILDNUM=$((CHILDNUM+1))
 done
@@ -295,12 +303,12 @@ RETVAL=$?
 while [ "$RETVAL" -gt 128 ] ; do
 	[ "$DEBUG" -ge 2 ] && echo "DEBUG: wait returned with a value of $RETVAL" 1>&2
 	DO_WAIT=0
-	    for CPID in $(cat $TEMP_DIR/*.pid 2>/dev/null) ; do
-		    if [ -d "/proc/$CPID" ] ; then 
+	for CPID in $( /bin/cat $TEMP_DIR/*.pid 2>/dev/null) ; do
+		if [ -d "/proc/$CPID" ] ; then 
 			DO_WAIT=1
 			[ "$DEBUG" -ge 2 ] && echo "DEBUG: $CPID is still running." 1>&2
-		    fi
-	    done
+		fi
+	done
 	[ "$DO_WAIT" = 0 ] && break
 	wait
 done
diff --git a/misc/updatesql b/misc/updatesql
--- a/misc/updatesql
+++ b/misc/updatesql
@@ -41,18 +41,18 @@ if [ $# -ne 2 ]; then
 	exit 0
 fi
 
-MYFILE=$1
+MYFILE=${1}
+SCHEMA=${2}
 
-if [ ! -f ${MYFILE} ]; then
-	/usr/bin/touch ${MYFILE} && /bin/chmod 0640 ${MYFILE} && /usr/sbin/chown ${cbsduser}:${cbsduser} ${MYFILE}
+[ ! -f ${MYFILE} ] && /usr/bin/touch ${MYFILE}
+/bin/chmod 0660 ${MYFILE} && /usr/sbin/chown ${cbsduser}:${cbsduser} ${MYFILE}
+
+if [ ! -f ${SCHEMA} ]; then
+	echo "File ${SCHEMA} not found"
+	exit 1
 fi
 
-if [ ! -f ${2} ]; then
-	echo "File $1 not found"
-	exit
-fi
-
-. ${2}
+. ${SCHEMA}
 
 create_table
 update_table
diff --git a/tools/jconstruct b/tools/jconstruct
--- a/tools/jconstruct
+++ b/tools/jconstruct
@@ -15,47 +15,49 @@ init $*
 # $jname
 get_jname()
 {
-    freejname
-    local _default _input
+	freejname
+	local _default _input
 
-    _default="${freejname}"
-    _input=""
-    while [ x${_input} = x ]; do
-	$ECHO "${BOLD}${GET_JNAME_MSG} e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-	if validate_jname ${_input}; then
-	    _input=""
-	fi
+	_default="${freejname}"
+	_input=""
+	while [ x${_input} = x ]; do
+		$ECHO "${BOLD}${jname_msg} e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+		if validate_jname ${_input}; then
+			_input=""
+		fi
 
-	jstatus jname=${_input}
-	if [ $? -ne 0 ]; then
-	    ${ECHO} "${MAGENTA}ERROR: Jail ${GREEN}${_input}${MAGENTA} already exist. Try again${NORMAL}"
-	    _input=""
-	fi
-    done
-    export jname=${_input}
+		jstatus jname=${_input}
+		if [ $? -ne 0 ]; then
+			${ECHO} "${MAGENTA}ERROR: Jail ${GREEN}${_input}${MAGENTA} already exist. Try again${NORMAL}"
+			_input=""
+		fi
+	done
+
+	export jname=${_input}
+	merge_apply_profiles ${etcdir}/defaults/${zero_profile} ${global_profile_file}
 }
 
 # $host_hostname
 get_jail_host_hostname()
 {
-    local _default _input _defdomain
+	local _default _input _defdomain
 
-    if [ -n "${default_domain}" ]; then
-	_defdomain="${default_domain}"
-    else
-	_defdomain="my.domain"
-    fi
+	if [ -n "${default_domain}" ]; then
+		_defdomain="${default_domain}"
+	else
+		_defdomain="my.domain"
+	fi
 
-    _default="${jname}.${_defdomain}"
+	_default="${jname}.${_defdomain}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_HOST_HOSTNAME_MSG} e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
-    export host_hostname=${_input}
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${host_hostname_msg} e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
+	export host_hostname=${_input}
 }
 
 
@@ -63,197 +65,196 @@ get_jail_host_hostname()
 # $ips
 get_jail_ips()
 {
-    local _input _default
-    _default=$( dhcpd 2>/dev/null )
+	local _input _default
+	_default=$( dhcpd 2>/dev/null )
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_IPS_MSG} e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
-    export ip4_addr="${_input}"
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${ip4_addr_msg} e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
+	export ip4_addr="${_input}"
 }
 
-# $oninterface
-get_jail_oninterface()
+# $interface
+get_jail_interface()
 {
-    local _default _input
+	local _default _input
 
-    _default="${interface}"
+	_default="${interface}"
 
-    while [ x${_input} = x ]; do
-	$ECHO "${BOLD}${GET_ONINTERFACE_MSG} e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		$ECHO "${BOLD}${ip4_addr_msg} e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export interface=${_input}
+	export interface=${_input}
 }
 
-# $base
-get_jail_base()
+# $ver
+get_jail_ver()
 {
-    local _input _default
+	local _input _default
 
-    _default="${ver}"
+	_default="${ver}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_BASE_MSG} e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${ver_msg} e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export ver=${_input}
+	export ver=${_input}
 }
 
 # $base
 get_jail_arch()
 {
-    local _default _input
+	local _default _input
 
-    _default="${arch}"
+	_default="${arch}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_ARCH_MSG} e.g: ${GREEN}${arch}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${arch_msg} e.g: ${GREEN}${arch}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export arch=${_input}
+	export arch=${_input}
 }
 
 
 # $baserw
 get_jail_baserw()
 {
-    local _default _input
+	local _default _input
 
-    _default="${baserw}"
+	_default="${baserw}"
 
-    while [ x${_input} = x ]; do
-	$ECHO "${BOLD}${GET_BASERW_MSG} ( 0 - nullfs base mount in RO, 1 - no nullfs, RW ) e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		$ECHO "${BOLD}${baserw_msg} ( 0 - nullfs base mount in RO, 1 - no nullfs, RW ) e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export baserw=${_input}
+	export baserw=${_input}
 }
 
 # $mount_src
 get_jail_mount_src()
 {
-    local _default _input
+	local _default _input
 
-    _default="${mount_src}"
+	_default="${mount_src}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_SRCMOUNT_MSG} (0 - no, 1 - yes): e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${mount_src_msg} (0 - no, 1 - yes): e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export mount_src=${_input}
+	export mount_src=${_input}
 }
 
 # $mount_obj
 get_jail_mount_obj()
 {
-    local _default _input
+	local _default _input
 
-    _default="${mount_obj}"
+	_default="${mount_obj}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_OBJMOUNT_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${mount_obj_msg} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export mount_obj=${_input}
+	export mount_obj=${_input}
 }
 
 # $mount_ports
 get_jail_mount_ports()
 {
-    local _default _input
+	local _default _input
 
-    _default="${mount_ports}"
+	_default="${mount_ports}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_PORTSMOUNT_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${mount_ports_msg} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export mount_ports=${_input}
+	export mount_ports=${_input}
 }
 
 
 # $applytpl
 get_jail_applytpl()
 {
-    local _default _input
+	local _default _input
 
-    _default="${applytpl}"
+	_default="${applytpl}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_APPLYTPL_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${applytpl_msg} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export applytpl=${_input}
+	export applytpl=${_input}
 }
 
 # $applytpl
 get_jail_floatresolv()
 {
-    local _default _input
+	local _default _input
 
-    _default="${floatresolv}"
+	_default="${floatresolv}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_FLOATRESOLV_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${floatresolv_msg} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export floatresolv=${_input}
+	export floatresolv=${_input}
 }
 
 
 # $astart
 get_jail_astart()
 {
-    local _default _input
+	local _default _input
 
-    _default="${astart}"
+	_default="${astart}"
 
-    while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_ASTART_MSG} ( 0 - no, 1 -yes) e.g: ${GREEN}${_default}${NORMAL} "
-	read _input
-	[ -z "${_input}" ] && _input="${_default}"
-    done
+	while [ x${_input} = x ]; do
+		${ECHO} "${BOLD}${astart_msg} ( 0 - no, 1 -yes) e.g: ${GREEN}${_default}${NORMAL} "
+		read _input
+		[ -z "${_input}" ] && _input="${_default}"
+	done
 
-    export astart=${_input}
+	export astart=${_input}
 }
 
 
 
 gen_newjail_conf()
 {
+	local _i _mytest _ret
 
-    local _i _mytest _ret
+	pkglist=""
+	vnet="0"
+	mdsize="0"
 
-    pkglist=""
-    vnet="0"
-    mdsize="0"
+	# vnet=${vimage}
 
-#    vnet=${vimage}
-
-    # init emulator by arch
-    init_target_arch
-    gen_jconf
-    [ $? -eq 0 ] || err 1 "${MAGENTA}Bad conf${NORMAL}"
+	# init emulator by arch
+	init_target_arch
+	gen_jconf
+	[ $? -eq 0 ] || err 1 "${MAGENTA}Bad conf${NORMAL}"
 }
 
 more << EOF_HEADER
@@ -266,37 +267,39 @@ EOF_HEADER
 
 agreed=
 while [ x$agreed = x ]; do
-        ${ECHO} "${BOLD}Proceed to construct? ${GREEN}[yes or no]${NORMAL}"
-        read reply leftover
-        case $reply in
-                y* | Y*)
-                        agreed=1
-                        ;;
-                n* | n*)
-                        echo
-                        exit 1
-                        ;;
-        esac
+	${ECHO} "${BOLD}Proceed to construct? ${GREEN}[yes or no]${NORMAL}"
+	read reply leftover
+	case $reply in
+		y* | Y*)
+			agreed=1
+			;;
+		n* | n*)
+			echo
+			exit 1
+			;;
+	esac
 done
 
-default_profile="jail-freebsd-default.conf"
-#defaults
 . ${buildconf}
-readconf ${default_profile}
+
+zero_profile="jail-freebsd-default.conf"
+readconf ${zero_profile}
+# re-read profile for init global_profile_file variable
+get_construct_profile ${default_profile}
+[ -z "${profile}" -a -n "${jail_profile}" ] && profile="${jail_profile}"
 
 . ${workdir}/universe.subr
 
 get_jname &&  \
 get_jail_host_hostname && \
 get_jail_ips && \
-get_jail_base && \
+get_jail_ver && \
 get_jail_arch && \
 get_jail_baserw && \
 get_jail_mount_src && \
-get_jail_mount_obj && \
 get_jail_mount_ports && \
 get_jail_astart && \
-get_jail_oninterface && \
+get_jail_interface && \
 get_jail_applytpl && \
 get_jail_floatresolv && \
 gen_newjail_conf
diff --git a/tools/retrinv b/tools/retrinv
--- a/tools/retrinv
+++ b/tools/retrinv
@@ -9,8 +9,10 @@ data can be - jdescr,nodedescr,db,rctl,fwcnt. If not specify - retrieive all of 
 jname - fetch data only for specified jail\n\
 tryoffline=1 - try to fetch inventory when node is offline\n"
 
-[ -f ${globalconf} ] || err 1 "no such conf file";
+set -e
 . ${globalconf}
+set +e
+
 . ${subr}
 . ${tools}
 . ${inventory}
@@ -26,10 +28,10 @@ retr_db()
 
 	nodescp ${checkforonline} ${_rnode}:var/db/inv.${_rnode}.sqlite ${dbdir}/${_rnode}.sqlite && chmod 0640 "${dbdir}/${_rnode}.sqlite" && chown ${cbsduser} "${dbdir}/${_rnode}.sqlite"
 	if [ $? -eq 0 ]; then
-		$ECHO "${MAGENTA}Fetching inventory done: ${GREEN}${_rnode}${NORMAL}"
+		$ECHO "${MAGENTA}CBSD: Fetching inventory done: ${GREEN}${_rnode}${NORMAL}"
 		idle_update ${_rnode}
 	else
-		$ECHO "${MAGENTA}Fetching inventory failed: ${GREEN}${_rnode}${NORMAL}"
+		$ECHO "${MAGENTA}CBSD: Fetching inventory failed: ${GREEN}${_rnode}${NORMAL}"
 	fi
 }
 
