bhyve: manage storage controller
WIP! Currently only AHCI controller supported

diff --git a/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller b/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller
--- a/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller
+++ b/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller
@@ -17,30 +17,27 @@ dialog_menu_main()
 
 	local btitle="$DIALOG_BACKTITLE"
 
-	local title=" Image Properties ${jname}:${dsk_path} "
+	local title=" Controller Properties ${jname}:${ctr} "
 	hline=
 
 	local prompt="${_desc}"
 	local sqldelimer=" "
 
-	eval $( cbsdsql ${jailsysdir}/${jname}/local.sqlite SELECT dsk_controller,dsk_slot,dsk_type,controller_id FROM bhyvedsk WHERE jname=\"${jname}\" AND dsk_path=\"${dsk_path}\" | while read dsk_controller dsk_slot dsk_type controller_id; do
-		echo "export dsk_controller=\"${dsk_controller}\""
-		echo "export dsk_slot=\"${dsk_slot}\""
-		echo "export dsk_type=\"${dsk_type}\""
-		echo "export new_controller_id=\"${controller_id}\""
-	done ) || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
-
-	# get $dsk_size
-	populate_dsk_size
+	eval $( cbsdsql ${jailsysdir}/${jname}/local.sqlite SELECT id,name,type,count,cache FROM bhyve_dskcontroller WHERE name=\"${ctr}\" | while read id name type count cache; do
+		echo "export ctr_id=\"${id}\""
+		echo "export new_ctr_name=\"${name}\""
+		echo "export new_ctr_type=\"${type}\""
+		echo "export new_ctr_count=\"${count}\""
+		echo "export new_ctr_cache=\"${cache}\""
+	done ) || err 1 "${MAGENTA}Error while create controller map${NORMAL}"
 
 	local menu_list="
-		'size'		'${dsk_size}'		'Current disk image size. Resize currently is not supported'
-		'controller'	'${dsk_controller}'	'Select controller type'
-		'slot'		'${dsk_slot}'		'Bus slot. 0 - auto'
-		'dsk_type'	'${dsk_type}'		'Disk type ( vhd, vmdk, vdi, qcow )'
-		'controller_id'	'${new_controller_id}'	'Attach to controller, not to BUS directly'
+		'type'		'${new_ctr_type}'	'Select controller type'
+		'name'		'${new_ctr_name}'	'Name of controller'
+		'count'		'${new_ctr_count}'	'Max Port Count'
+		'cache'		'${new_ctr_cache}'	'Use Host I/O Cache'
 		'-'		'-'			''
-		'remove'	'remove'		'Detach and remove image'
+		'remove'	'remove'	'Remove controller'
 	" # END-QUOTE
 
 	local height width rows
@@ -84,7 +81,7 @@ dialog_menu_main()
 ############################################################ MAIN
 export NOCOLOR=1
 
-MYARG="jname dsk"
+MYARG="jname ctr"
 MYOPTARG=""
 MYDESC="Edit properties for vitual image of VM"
 CBSDMODULE="bhyve"
@@ -103,14 +100,14 @@ init $*
 . ${dialog}
 
 . ${workdir}/bsdconfig.subr
-f_include_lang $BSDCFG_LIBE/$APP_DIR/include/messages-bhyvedsk.subr
+f_include_lang $BSDCFG_LIBE/$APP_DIR/include/messages-bhyve-dskcontroller.subr
 
 . ${jrcconf}
 [ $? -eq 1 ] && err 1 "${MAGENTA}No such VM: ${GREEN}${jname}${NORMAL}"
 [ "${emulator}" != "bhyve" ] && err 1 "${MAGENTA}Not in bhyve mode${NORMAL}"
 
-. $BSDCFG_LIBE/$APP_DIR/include/bhyvedsk.subr
 . ${workdir}/bhyve.subr
+. $BSDCFG_LIBE/$APP_DIR/include/bhyve-dskcontroller.subr
 
 # Incorporate rc-file if it exists
 [ -f "$HOME/.bsdconfigrc" ] && f_include "$HOME/.bsdconfigrc"
@@ -128,13 +125,9 @@ shift $(( $OPTIND - 1 ))
 #
 # Initialize
 #
-f_dialog_title " $msg_add_bhyvedsk "
+f_dialog_title " $msg_add_bhyvectr "
 f_dialog_backtitle "${ipgm:+bsdconfig }$pgm"
 f_mustberoot_init
-
-
-# Select from SQL by dsk_path. Also this variable used in populate_dsk_size func
-dsk_path="${dsk}.vhd"
 
 . ${workdir}/bhyve.subr
 
@@ -153,26 +146,36 @@ while :; do
 				?" $msg_exit")
 					break
 					;;
-				"-"|slot|dsk_type|size)
+				"-")
 					continue
 					;;
-				"controller")
-					get_dsk_controller
-					if [ -n "${new_dsk_controller}" ]; then
-						cbsdsql ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_controller=\"${new_dsk_controller}\" WHERE dsk_path=\"${dsk}.vhd\" AND jname=\"${jname}\"
+				cache)
+					get_ctr_cache
+					if [ -n "${new_ctr_cache}" ]; then
+						cbsdsql ${jailsysdir}/${jname}/local.sqlite UPDATE bhyve_dskcontroller SET cache=\"${new_ctr_cache}\" WHERE name=\"${ctr}\"
 					fi
 					;;
-				controller_id)
-					get_controller_id
-					if [ -n "${new_controller_id}" ]; then
-						cbsdsql ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET controller_id=\"${new_controller_id}\" WHERE dsk_path=\"${dsk}.vhd\" AND jname=\"${jname}\"
+				count)
+					get_ctr_count
+					if [ -n "${new_ctr_count}" ]; then
+						cbsdsql ${jailsysdir}/${jname}/local.sqlite UPDATE bhyve_dskcontroller SET count=\"${new_ctr_count}\" WHERE name=\"${ctr}\"
 					fi
 					;;
-				"remove")
-					if getyesno "Detach and remove ${dsk_path} from ${jname} VM?"; then
-						real_dsk_name="hdd-${dsk_path}"
-						real_dsk_path=$( cbsdsql storage_media SELECT path FROM media WHERE name=\"${real_dsk_name}\" AND jname=\"${jname}\" AND type=\"hdd\" )
-						media mode=remove name=${real_dsk_name} path=${real_dsk_path} jname=${jname} type="hdd"
+				name)
+					get_ctr_name
+					if [ -n "${new_ctr_name}" ]; then
+						cbsdsql ${jailsysdir}/${jname}/local.sqlite UPDATE bhyve_dskcontroller SET name=\"${new_ctr_name}\" WHERE name=\"${ctr}\"
+					fi
+					;;
+				type)
+					get_ctr_type
+					if [ -n "${new_ctr_type}" ]; then
+						cbsdsql ${jailsysdir}/${jname}/local.sqlite UPDATE bhyve_dskcontroller SET type=\"${new_ctr_type}\" WHERE name=\"${ctr}\"
+					fi
+					;;
+				remove)
+					if getyesno "Detach and remove ${ctr} from ${jname} VM?"; then
+						cbsdsql ${jailsysdir}/${jname}/local.sqlite DELETE FROM bhyve_dskcontroller WHERE name=\"${ctr}\"
 						f_die
 					fi
 					;;
