convert to builtin; reduce diff between bhyve/XEN/qemu; moving away from the bsdconfig

diff --git a/share/bsdconfig/cbsd/qemudsk-cfgdsk b/share/bsdconfig/cbsd/qemudsk-cfgdsk
--- a/share/bsdconfig/cbsd/qemudsk-cfgdsk
+++ b/share/bsdconfig/cbsd/qemudsk-cfgdsk
@@ -19,27 +19,21 @@ readconf qemu-default-default.conf		# qemu_have_dsk_ratelimit?
 dialog_menu_main()
 {
 	local _input _retval _controller_desc _dsk_controller_type
-	local _checkbox="bootable" i _mytest
+	local _checkbox="bootable" _i _mytest
 
-	local btitle="$DIALOG_BACKTITLE"
+	local _btitle="$DIALOG_BACKTITLE"
 
-	local title=" disk properties ${jname}:${dsk_path} "
-	hline=
+	local _title=" disk properties ${jname}:${dsk_path} "
+	local _hline=
 
-	local prompt="${_desc}"
-	local sqldelimer=" "
+	local _prompt="${_desc}"
 
-	eval $( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_controller,dsk_slot,dsk_type,bootable FROM qemudsk WHERE dsk_path=\"${dsk_path}\" | while read dsk_controller dsk_slot dsk_type bootable; do
-		echo "export dsk_controller=\"${dsk_controller}\""
-		echo "export dsk_slot=\"${dsk_slot}\""
-		echo "export dsk_type=\"${dsk_type}\""
-		echo "export bootable=\"${bootable}\""
-	done ) || err 1 "${N1_COLOR}Error while create disk map${N0_COLOR}"
+	cbsdsqlro_vars dsk_controller dsk_slot dsk_type bootable ${jailsysdir}/${jname}/local.sqlite SELECT dsk_controller,dsk_slot,dsk_type,bootable FROM qemudsk WHERE dsk_path='${dsk_path}' || err 1 "${N1_COLOR}Error while create disk map${N0_COLOR}"
 
 	# get ${dsk_size}
 	populate_dsk_size
 
-	_dsk_controller_type=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT type FROM qemu_dskcontroller WHERE name=\"${dsk_controller}\" )
+	capture _dsk_controller_type cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT type FROM qemu_dskcontroller WHERE name='${dsk_controller}'
 
 	# if no controller with specific name, than set controller type as controller name - probable direct connect via virtio-blk/ahci-hd
 	[ -z "${_dsk_controller_type}" ] && _dsk_controller_type="${dsk_controller}"
@@ -60,78 +54,78 @@ dialog_menu_main()
 	esac
 
 	# checkbox mark
-	for i in ${_checkbox}; do
-		#eval _new_mytest=\$new_$i
-		#[ -n "${_new_mytest}" ] && eval "${i}=${_new_mytest}"
-		eval _mytest=\$$i
+	for _i in ${_checkbox}; do
+		#eval _new_mytest=\$new_$_i
+		#[ -n "${_new_mytest}" ] && eval "${_i}=${_new_mytest}"
+		eval _mytest=\$$_i
 		if [ "${_mytest}" = "1" -o "${_mytest}" = "true" ]; then
-			export ${i}_mark="X"
+			export ${_i}_mark="X"
 		else
-			export ${i}_mark=" "
+			export ${_i}_mark=" "
 		fi
 	done
 
-	local menu_list="
+	local _menu_list="
 		'size'			'${dsk_size}'		'Current disk image size. Resize currently is not supported'
 		'controller'		'${dsk_controller}'	'Select controller. current: ${_controller_desc}'
 		'slot'			'${dsk_slot}'		'Bus slot. 0 - auto'
 	" # END-QUOTE
 
 	if [ "${qemu_have_dsk_ratelimit}" = "1" ]; then
-		menu_list="${menu_list}	'dsk_iops_limit'	'${dsk_iops_limit}'	'Disk IOPS limit'"
-		menu_list="${menu_list}	'dsk_mbps_limit'	'${dsk_mbps_limit}'	'Disk Mbit/s limit'"
+		_menu_list="${_menu_list}	'dsk_iops_limit'	'${dsk_iops_limit}'	'Disk IOPS limit'"
+		_menu_list="${_menu_list}	'dsk_mbps_limit'	'${dsk_mbps_limit}'	'Disk Mbit/s limit'"
 	fi
 
 	#checkbox area
-	for i in ${_checkbox}; do
-		eval _mytest=\$${i}_mark
+	for _i in ${_checkbox}; do
+		eval _mytest=\$${_i}_mark
 		[ -z "${_mytest}" ] && _mytest=" "
 		#inc_menu_index item_let
-		menu_list="${menu_list}	'${i}'	'[${_mytest}]'	'${_mydesc}'"
+		_menu_list="${_menu_list}	'${_i}'	'[${_mytest}]'	'${_mydesc}'"
 	done
 
-	menu_list="${menu_list}
+	_menu_list="${_menu_list}
 		'-'		'-'			''
 		'remove'	'remove'		'Detach and remove image'
 	" # END-QUOTE
 
 	local height width rows
 	eval f_dialog_menu_with_help_size height width rows \
-		\"\$title\"  \
-		\"\$btitle\" \
-		\"\$prompt\" \
-		\"\$hline\"  \
-		${menu_list}
+		\"\$_title\"  \
+		\"\$_btitle\" \
+		\"\$_prompt\" \
+		\"\$_hline\"  \
+		${_menu_list}
 
 	height=$(( height + 1 ))
 
 	# Obtain default-item from previously stored selection
-	f_dialog_default_fetch defaultitem
+	f_dialog_default_fetch _defaultitem
 
-	local menu_choice
-	menu_choice=$( eval $DIALOG \
+	local _menu_choice
+	_menu_choice=$( eval $DIALOG \
 		--clear                                 \
-		--title \"\$title\"                     \
-		--backtitle \"\$btitle\"                \
-		--hline \"\$hline\"                     \
+		--title \"\$_title\"                     \
+		--backtitle \"\$_btitle\"                \
+		--hline \"\$_hline\"                     \
 		--item-help                             \
 		--ok-label \"\$msg_ok\"                 \
 		--cancel-label \"Exit\"                 \
 		${USE_XDIALOG:+--help \"\"}             \
-		--default-item \"\$defaultitem\"        \
-		--menu \" \$prompt \"                   \
+		--default-item \"\$_defaultitem\"        \
+		--menu \" \$_prompt \"                   \
 		$height $width $rows                    \
-		$menu_list                              \
+		$_menu_list                              \
 		2>&1 >&$DIALOG_TERMINAL_PASSTHRU_FD
 	)
 
-	local retval=$?
-	f_dialog_data_sanitize menu_choice
-	f_dialog_menutag_store "$menu_choice"
+	local _retval=$?
+	f_dialog_data_sanitize _menu_choice
+	f_dialog_menutag_store "$_menu_choice"
 
 	# Only update default-item on success
-	[ $retval -eq $DIALOG_OK ] && f_dialog_default_store "$menu_choice"
-	return $retval
+	[ $_retval -eq $DIALOG_OK ] && f_dialog_default_store "$_menu_choice"
+	return $_retval
 }
 
 
@@ -180,7 +174,7 @@ while getopts h$GETOPTS_STDARGS flag; do
 	h|\?) f_usage $BSDCFG_LIBE/$APP_DIR/USAGE "PROGRAM_NAME" "$pgm" ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 #
 # Initialize
@@ -201,16 +195,16 @@ new_checkbox=
 #
 while :; do
 	dialog_menu_main
-	ret=$?
+	_ret=$?
 
 	#index=${mtag%% *}
 	#mychoice=${mtag##* }
 
-	command=
-	case ${ret} in
+	_command=
+	case ${_ret} in
 		${DIALOG_OK})
-			f_dialog_menutag_fetch mtag
-			case "$mtag" in
+			f_dialog_menutag_fetch _mtag
+			case "$_mtag" in
 				?" $msg_exit")
 					break
 					;;
@@ -220,13 +214,13 @@ while :; do
 				"controller")
 					get_dsk_controller
 					if [ -n "${new_dsk_controller}" ]; then
-						cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE qemudsk SET dsk_controller=\"${new_dsk_controller}\" WHERE dsk_path=\"${dsk}.vhd\"
+						cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE qemudsk SET dsk_controller='${new_dsk_controller}' WHERE dsk_path='${dsk}.vhd'
 					fi
 					;;
 				"remove")
 					if getyesno "Detach and remove ${dsk_path} from ${jname} VM?"; then
 						real_dsk_name="hdd-${dsk_path}"
-						real_dsk_path=$( cbsdsqlro storage_media SELECT path FROM media WHERE name=\"${real_dsk_name}\" AND type=\"hdd\" )
+						capture real_dsk_path cbsdsqlro storage_media SELECT path FROM media WHERE name='${real_dsk_name}' AND type='hdd'
 						media mode=remove name=${real_dsk_name} path=${real_dsk_path} jname=${jname} type="hdd"
 						f_die
 					fi
@@ -241,11 +235,11 @@ e.g: 512 or 4096 or 512/4096" "${dsk_sectorsize}" "${_message}" || return $?
 					if [ -n "${_input}" ]; then
 						dsk_sectorsize="${_input}"
 						new_dsk_sectorsize="${_input}"
-						cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE qemudsk SET dsk_sectorsize=\"${new_dsk_sectorsize}\" WHERE dsk_path=\"${dsk}.vhd\"
+						cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE qemudsk SET dsk_sectorsize='${new_dsk_sectorsize}' WHERE dsk_path='${dsk}.vhd'
 					fi
 					;;
 				"bootable")
-					invert_checkbox ${mtag}
+					invert_checkbox ${_mtag}
 					#new_bootable="${bootable}"
 					qemu-dsk mode=modify bootable=${bootable} jname=${jname} controller="${dsk_controller}" dsk="${dsk}.vhd" > /dev/null 2>&1
 					continue
diff --git a/share/bsdconfig/cbsd/qemunic-cfgnic b/share/bsdconfig/cbsd/qemunic-cfgnic
--- a/share/bsdconfig/cbsd/qemunic-cfgnic
+++ b/share/bsdconfig/cbsd/qemunic-cfgnic
@@ -11,43 +11,30 @@
 #
 dialog_menu_main()
 {
-	local _input _retval _pref
-	local _checkbox="nic_persistent" i _mytest
+	local _retval
+	local _checkbox="nic_persistent" _i _mytest
 
-	local btitle="$DIALOG_BACKTITLE"
-	local title=" Nic properties ${jname}:${nic_path} "
-	hline=
+	local _btitle="$DIALOG_BACKTITLE"
+	local _title=" Nic properties ${jname}:${nic_path} "
+	local _hline=
 
-	local prompt="${_desc}"
-	local sqldelimer=" "
+	local _prompt="${_desc}"
 
-	eval $( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT id,nic_driver,nic_slot,nic_type,nic_parent,nic_hwaddr,nic_address,nic_mtu,nic_persistent,nic_ratelimit,nic_flags FROM qemunic WHERE id=\"${nic}\" AND jname=\"${jname}\" | while read nic_id nic_driver nic_slot nic_type nic_parent nic_hwaddr nic_address nic_mtu nic_persistent nic_ratelimit nic_flags; do
-		echo "export nic_id=\"${nic_id}\""
-		echo "export nic_driver=\"${nic_driver}\""
-		echo "export nic_slot=\"${nic_slot}\""
-		echo "export nic_type=\"${nic_type}\""
-		echo "export nic_parent=\"${nic_parent}\""
-		echo "export nic_hwaddr=\"${nic_hwaddr}\""
-		echo "export nic_address=\"${nic_address}\""
-		echo "export nic_mtu=\"${nic_mtu}\""
-		echo "export nic_persistent=\"${nic_persistent}\""
-		echo "export nic_ratelimit=\"${nic_ratelimit}\""
-		echo "export nic_flags=\"${nic_flags}\""
-	done ) || err 1 "${N1_COLOR}Error while create NIC map${N0_COLOR}"
+	cbsdsqlro_vars nic_id nic_driver nic_slot nic_type nic_parent nic_hwaddr nic_address nic_mtu nic_persistent nic_ratelimit nic_flags ${jailsysdir}/${jname}/local.sqlite SELECT id,nic_driver,nic_slot,nic_type,nic_parent,nic_hwaddr,nic_address,nic_mtu,nic_persistent,nic_ratelimit,nic_flags FROM qemunic WHERE id='${nic}' AND jname='${jname}' || err 1 "${N1_COLOR}Error while create NIC map${N0_COLOR}"
 
 	# checkbox mark
-	for i in ${_checkbox}; do
-		#eval _new_mytest=\$new_$i
-		#[ -n "${_new_mytest}" ] && eval "${i}=${_new_mytest}"
-		eval _mytest=\$$i
+	for _i in ${_checkbox}; do
+		#eval _new_mytest=\$new_$_i
+		#[ -n "${_new_mytest}" ] && eval "${_i}=${_new_mytest}"
+		eval _mytest=\$$_i
 		if [ "${_mytest}" = "1" -o "${_mytest}" = "true" ]; then
-			export ${i}_mark="X"
+			export ${_i}_mark="X"
 		else
-			export ${i}_mark=" "
+			export ${_i}_mark=" "
 		fi
 	done
 
-	local menu_list="
+	local _menu_list="
 		'nic_driver'	'${nic_driver}'		'NIC driver'
 		'nic_parent'	'${nic_parent}'		'NIC parent interface. 0 - auto'
 		'nic_hwaddr'	'${nic_hwaddr}'		'NIC Mac address. 0 - auto'
@@ -58,65 +45,65 @@ dialog_menu_main()
 	" # END-QUOTE
 
 	if [ "${qemu_have_net_ratelimit}" = "1" ]; then
-		menu_list="${menu_list} 'nic_ratelimit'	'${nic_ratelimit}'	'NIC bandwith ratelimit'"
+		_menu_list="${_menu_list} 'nic_ratelimit'	'${nic_ratelimit}'	'NIC bandwith ratelimit'"
 	fi
 
 	# persistent checkbox for tap interface only
-	_pref3=$( substr --pos=0 --len=3 --str=${nic_parent} )
+	capture _pref3 substr --pos=0 --len=3 --str=${nic_parent}
 	if [ "${_pref3}" = "tap" ]; then
 		#checkbox area
-		for i in ${_checkbox}; do
-			eval _mytest=\$${i}_mark
+		for _i in ${_checkbox}; do
+			eval _mytest=\$${_i}_mark
 			[ -z "${_mytest}" ] && _mytest=" "
 			#inc_menu_index item_let
-			menu_list="${menu_list}	'${i}'	'[${_mytest}]'	'${_mydesc}'"
+			_menu_list="${_menu_list}	'${_i}'	'[${_mytest}]'	'${_mydesc}'"
 		done
 	else
 		nic_persistent=0
 	fi
 
-	menu_list="${menu_list}
+	_menu_list="${_menu_list}
 		'-'		'-'			''
 		'remove'	'remove'		'Detach and remove NIC'
 	" # END-QUOTE
 
 	local height width rows
 	eval f_dialog_menu_with_help_size height width rows \
-		\"\$title\"  \
-		\"\$btitle\" \
-		\"\$prompt\" \
-		\"\$hline\"  \
-		$menu_list
+		\"\$_title\"  \
+		\"\$_btitle\" \
+		\"\$_prompt\" \
+		\"\$_hline\"  \
+		$_menu_list
 
 	height=$(( height + 1 ))
 
 	# Obtain default-item from previously stored selection
-	f_dialog_default_fetch defaultitem
+	f_dialog_default_fetch _defaultitem
 
-	local menu_choice
-	menu_choice=$( eval $DIALOG \
+	local _menu_choice
+	_menu_choice=$( eval $DIALOG \
 		--clear                                 \
-		--title \"\$title\"                     \
-		--backtitle \"\$btitle\"                \
-		--hline \"\$hline\"                     \
+		--title \"\$_title\"                     \
+		--backtitle \"\$_btitle\"                \
+		--hline \"\$_hline\"                     \
 		--item-help                             \
 		--ok-label \"\$msg_ok\"                 \
 		--cancel-label \"Exit\"                 \
 		${USE_XDIALOG:+--help \"\"}             \
-		--default-item \"\$defaultitem\"        \
-		--menu \" \$prompt \"                   \
+		--default-item \"\$_defaultitem\"        \
+		--menu \" \$_prompt \"                   \
 		$height $width $rows                    \
-		$menu_list                              \
+		$_menu_list                              \
 		2>&1 >&$DIALOG_TERMINAL_PASSTHRU_FD
 	)
 
-	local retval=$?
-	f_dialog_data_sanitize menu_choice
-	f_dialog_menutag_store "$menu_choice"
+	local _retval=$?
+	f_dialog_data_sanitize _menu_choice
+	f_dialog_menutag_store "$_menu_choice"
 
 	# Only update default-item on success
-	[ $retval -eq $DIALOG_OK ] && f_dialog_default_store "$menu_choice"
-	return $retval
+	[ $_retval -eq $DIALOG_OK ] && f_dialog_default_store "$_menu_choice"
+	return $_retval
 }
 
 
@@ -161,7 +148,7 @@ while getopts h$GETOPTS_STDARGS flag; do
 	h|\?) f_usage $BSDCFG_LIBE/$APP_DIR/USAGE "PROGRAM_NAME" "$pgm" ;;
 	esac
 done
-shift $(( $OPTIND - 1 ))
+shift $(( OPTIND - 1 ))
 
 #
 # Initialize
@@ -179,13 +166,13 @@ readconf qemu-default-default.conf		# qemu_have_net_ratelimit?
 #
 while :; do
 	dialog_menu_main
-	ret=$?
+	_ret=$?
 
-	command=
-	case $ret in
+	_command=
+	case $_ret in
 		${DIALOG_OK})
-			f_dialog_menutag_fetch mtag
-			case "$mtag" in
+			f_dialog_menutag_fetch _mtag
+			case "$_mtag" in
 				?" $msg_exit")
 					break
 					;;
@@ -225,7 +212,7 @@ while :; do
 					fi
 					;;
 				"nic_persistent")
-					invert_checkbox ${mtag} && update_nic_persistent ${nic_id}
+					invert_checkbox ${_mtag} && update_nic_persistent ${nic_id}
 					;;
 				"nic_ratelimit")
 					get_construct_nic_ratelimit && update_nic_ratelimit ${nic_id}
diff --git a/sudoexec/xstart b/sudoexec/xstart
--- a/sudoexec/xstart
+++ b/sudoexec/xstart
@@ -92,7 +92,7 @@ make_freebsd_part()
 {
 ${CAT_CMD} >> $1 << EOF
 # $vm_os_type specific:
-builder = "hvm"
+type = "hvm"
 serial="pty"
 EOF
 }
@@ -102,7 +102,7 @@ make_linux_part()
 ${CAT_CMD} >> $1 << EOF
 
 # $vm_os_type specific:
-builder = "hvm"
+type = "hvm"
 #kernel = "/mnt/iso/isolinux/vmlinuz"
 #ramdisk = "/mnt/iso/isolinux/initrd.img"
 #extra = "debian-installer/exit/always_halt=true -- console=hvc0"
@@ -116,7 +116,7 @@ make_windows_part()
 ${CAT_CMD} >> $1 << EOF
 
 # $vm_os_type specific:
-builder='hvm'
+type='pvh'
 acpi = 1
 EOF
 }
@@ -126,7 +126,7 @@ make_other_part()
 ${CAT_CMD} >> $1 << EOF
 
 # $vm_os_type specific:
-builder='hvm'
+type='pvh'
 EOF
 }
 
@@ -347,30 +347,17 @@ name = "${jname}"
 memory = ${xvm_ram}
 vcpus = ${vm_cpus}
 
-# Network devices
-#vif = [ "bridge=${mybridge}" ]
-#vif = [ 
-#    'bridge=xenbr0, mac=00:16:3e:00:00:01, type=vif',
-#    'bridge=xenbr1, mac=00:16:3e:00:00:02, type=vif' 
-#]
-
-# vif = [ 'bridge=xenbr0, vifname=guest1-eth0, mac=00:16:3e:0a:11:01' ]
-
 # Boot args
 ${boot_arg}
 
-#vnc = 1
-#vnclisten = "${xen_vnc_tcp_bind}"
-#vncpasswd="${vnc_password}"
-#vncdisplay="${vncdisplay}"
+# slowoooooowww
+#vga = "stdvga"
+#videoram=32
 
-# larger resolution
-#vga="stdvga"
-# virtio, stdvga, qxl, cirrus
-vga = "stdvga"
-videoram=32
+# valid
+vga = "cirrus"
+videoram = 8
 
-#vm_vnc_port='${vm_vnc_port}'
 vncunused=0
 
 on_poweroff="${on_poweroff}";
@@ -379,33 +366,13 @@ on_crash="${on_crash}";
 
 usbdevice = 'tablet'
 
-# SPICE
-#vnc=0
-#on_crash="destroy"
-#spice=1
-#spicehost='0.0.0.0'
-#spiceport=6000
-# spicedisable_ticketing enabled is for no spice password, instead use spicepasswd
-#spicedisable_ticketing=1
-#spicepasswd="test"
-#spicevdagent=1
-#spice_clipboard_sharing=1
-# this will automatically redirect up to 4 usb devices from spice client to domUs
-#spiceusbredirection=4
-# This adds intel hd audio emulated card used for spice audio
-#soundhw="hda"
-#localtime=1
-
 hap="${xen_hap}"
 nestedhvm="${xen_nestedhvm}"
 # L1
 #cpuid = ['0x1:ecx=0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx']
 
-#nographics = 1
-
 # UEFI
 bios = "ovmf"
-#bios_override = "/usr/local/share/edk2-xen/XEN_X64_EFI.fd"
 
 apic=1
 acpi=1
@@ -451,7 +418,7 @@ soundhw="${soundhw}"
 EOF
 	fi
 
-#builder = "hvm"
+#type = "hvm"
 #name = "current0"
 #disk = [
 #'/dev/zvol/zroot/current0,raw,xvda,w'
@@ -532,6 +499,13 @@ EOF
 		fi
 	else
 		xl_cmd="${XL_CMD} -vvv create -c ${XENCFG}"
+	fi
+
+	${XL_CMD} create -n -p /usr/jails/jails-system/freebsd1/xen.cfg > /var/log/xen/qemu-dm-${jname}.log 2>&1
+	_ret=$?
+	if [ ${_ret} -ne 0 ]; then
+		${ECHO} "syntax check failed: ${XL_CMD} create -n -p /usr/jails/jails-system/freebsd1/xen.cfg"
+		err ${_ret} "see: /var/log/xen/qemu-dm-${jname}.log"
 	fi
 
 	echo "[debug]: $xl_cmd"
