fixes for jrclone; playing with new cmd: trafstat - traffic stats; add service/sysrc scripts to bsdconf modules; fullpath for real sysrc and services due to confict with bsdconf modules;

diff --git a/modules/pkg/pkg b/modules/pkg/pkg
--- a/modules/pkg/pkg
+++ b/modules/pkg/pkg
@@ -27,57 +27,58 @@ _MYDIR=$(dirname `realpath $0`)
 
 ### MAIN Route ###
 set -e
-    . ${_MYDIR}/pkg.subr
+	. ${_MYDIR}/pkg.subr
 set +e
 
 if [ -n "${name}" ]; then
-    pkgtarget="${name}"
+	pkgtarget="${name}"
 elif [ -n "$pkglist" ]; then
-    [ ! -f "${pkglist}" ] && err 1 "${MAGENTA}No such file: ${GREEN}${pkglist}${NORMAL}"
-    pkgtarget=$( cat ${pkglist}|xargs )
+	[ ! -f "${pkglist}" ] && err 1 "${MAGENTA}No such file: ${GREEN}${pkglist}${NORMAL}"
+	pkgtarget=$( cat ${pkglist}|xargs )
 else
-    [ "${mode}" != "bootstrap" ] && err 1 "${MAGENTA}Error: ${GREEN}name ${MAGENTA}or ${GREEN}pkglist${MAGENTA} arg is mandatory${NORMAL}"
+	[ "${mode}" != "bootstrap" ] && err 1 "${MAGENTA}Error: ${GREEN}name ${MAGENTA}or ${GREEN}pkglist${MAGENTA} arg is mandatory${NORMAL}"
 fi
 
 PKGARGS=""
 TRAP=""
 
 if [ -n "${jname}" ]; then
-    . ${jrcconf}
-    [ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
-    [ $baserw -eq 1 ] && path=$data
+	. ${jrcconf}
+	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+	[ $baserw -eq 1 ] && path=$data
 
-    . ${workdir}/universe.subr
-    readconf buildworld.conf
-    init_target_arch
-    init_srcdir
-    init_basedir
-    init_kerneldir
+	. ${workdir}/universe.subr
+	readconf buildworld.conf
+	init_target_arch
+	init_srcdir
+	init_basedir
+	init_kerneldir
 
-    [ ${jid} -eq 0 ] && prepare_jail
-    PKGARGS="${PKGARGS} -c ${path}"
+	[ ${jid} -eq 0 ] && prepare_jail
+	PKGARGS="${PKGARGS} -c ${path}"
 fi
 
 [ -n "${repodir}" ] && PKGARGS="${PKGARGS} -R ${repodir}"
 [ -n "${chroot}" ] && PKGARGS="${PKGARGS} -c ${chroot}"
 
 case "${mode}" in
-    bootstrap)
-	[ -z "${jname}" ] && err 1 "${MAGENTA}bootstrap for jail only${NORMAL}"
-	pkg_bootstrap
-	;;
-    install|add)
-	pkg_install "$pkgtarget"
-	;;
-    "remove")
-	pkg_remove "$pkgtarget"
-	;;
-    "info")
-	pkg_info "$pkgtarget"
-	;;
-    "query")
-	pkg_query "$pkgtarget"
-	;;
-    *)
-	err 1 "${MAGENTA}Unknown mode${NORMAL}"
+	bootstrap)
+		[ -z "${jname}" ] && err 1 "${MAGENTA}bootstrap for jail only${NORMAL}"
+		pkg_bootstrap
+		;;
+	install|add)
+		pkg_install "$pkgtarget"
+		;;
+	"remove")
+		pkg_remove "$pkgtarget"
+		;;
+	"info")
+		pkg_info "$pkgtarget"
+		;;
+	"query")
+		pkg_query "$pkgtarget"
+		;;
+	*)
+		err 1 "${MAGENTA}Unknown mode${NORMAL}"
 esac
+
diff --git a/tools/retrinv b/tools/retrinv
--- a/tools/retrinv
+++ b/tools/retrinv
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v10.0.6
+#v10.1.1
 globalconf="${workdir}/cbsd.conf";
 MYARG=""
 MYOPTARG="node data jname tryoffline"
@@ -20,155 +20,152 @@ init $*
 
 retr_db()
 {
-    local _rnode=$1
+	local _rnode=$1
 
-    [ -z "${_rnode}" ] && return 0
+	[ -z "${_rnode}" ] && return 0
 
-    nodescp ${checkforonline} ${_rnode}:var/db/inv.${_rnode}.sqlite ${dbdir}/${_rnode}.sqlite && chmod 0600 "${dbdir}/${_rnode}.sqlite" && chown ${cbsduser} "${dbdir}/${_rnode}.sqlite"
-    if [ $? -eq 0 ]; then
-	$ECHO "${MAGENTA}Fetching inventory done: ${GREEN}${_rnode}${NORMAL}"
-	idle_update ${_rnode}
-    else
-	$ECHO "${MAGENTA}Fetching inventory failed: ${GREEN}${_rnode}${NORMAL}"
-    fi
+	nodescp ${checkforonline} ${_rnode}:var/db/inv.${_rnode}.sqlite ${dbdir}/${_rnode}.sqlite && chmod 0640 "${dbdir}/${_rnode}.sqlite" && chown ${cbsduser} "${dbdir}/${_rnode}.sqlite"
+	if [ $? -eq 0 ]; then
+		$ECHO "${MAGENTA}Fetching inventory done: ${GREEN}${_rnode}${NORMAL}"
+		idle_update ${_rnode}
+	else
+		$ECHO "${MAGENTA}Fetching inventory failed: ${GREEN}${_rnode}${NORMAL}"
+	fi
 }
 
 retr_nodedescr()
 {
-    local _rnode=$1 _files _i
+	local _rnode=$1 _files _i
 
-    [ -z "${_rnode}" ] && return 0
+	[ -z "${_rnode}" ] && return 0
 
-    [ ! -d "${dbdir}/nodedescr" ] && mkdir -m 0700 -p "${dbdir}/nodedescr" && chmod 0600 "${dbdir}/nodedescr" && ${cbsduser} "${dbdir}/nodedescr"
+	[ ! -d "${dbdir}/nodedescr" ] && mkdir -m 0700 -p "${dbdir}/nodedescr" && chmod 0640 "${dbdir}/nodedescr" && ${cbsduser} "${dbdir}/nodedescr"
 
-    _files="descr role domain notes location"
+	_files="descr role domain notes location"
 
-    for _i in ${_files}; do
-	nodescp ${checkforonline} ${_rnode}:node.${_i} ${dbdir}/nodedescr/${_rnode}.${_i} 2>/dev/null && chmod 0600 "${dbdir}/nodedescr/${_rnode}.${_i}" && chown ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}" 2>/dev/null
-    done
+	for _i in ${_files}; do
+		nodescp ${checkforonline} ${_rnode}:node.${_i} ${dbdir}/nodedescr/${_rnode}.${_i} 2>/dev/null && chmod 0640 "${dbdir}/nodedescr/${_rnode}.${_i}" && chown ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}" 2>/dev/null
+	done
 }
 
 
 retr_jdescr()
 {
-    local _rnode=$1 _jname
+	local _rnode=$1 _jname
 
-    [ -z "${_rnode}" ] && return 0
+	[ -z "${_rnode}" ] && return 0
 
-    [ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
-    [ ! -d "${dbdir}/nodedescr" ] && mkdir -p "${dbdir}/nodedescr"
+	[ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
+	[ ! -d "${dbdir}/nodedescr" ] && mkdir -p "${dbdir}/nodedescr"
 
-    if [ -z "$jname" ]; then
-        _jname=$( cbsd -c "cbsdsql ${_rnode} SELECT jname FROM jails WHERE status\<2" )
-    else
-        _jname=${jname}
-    fi
+	if [ -z "$jname" ]; then
+		_jname=$( cbsd -c "cbsdsql ${_rnode} SELECT jname FROM jails WHERE status\<2" )
+	else
+		_jname=${jname}
+	fi
 
-    [ -z "${_jname}" ] && return 0
+	[ -z "${_jname}" ] && return 0
 
-
-    for _i in ${_jname}; do
-	nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/descr ${dbdir}/nodedescr/${_rnode}.${_i}.descr 2>/dev/null && chmod 0600 "${dbdir}/nodedescr/${_rnode}.${_i}.descr" && chown ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}.descr" 2>/dev/null
-    done
+	for _i in ${_jname}; do
+		nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/descr ${dbdir}/nodedescr/${_rnode}.${_i}.descr 2>/dev/null && chmod 0640 "${dbdir}/nodedescr/${_rnode}.${_i}.descr" && chown ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}.descr" 2>/dev/null
+	done
 }
 
 retr_rctl()
 {
-    local _rnode=$1 _jname
+	local _rnode=$1 _jname
 
-    [ -z "${_rnode}" ] && return 0
+	[ -z "${_rnode}" ] && return 0
 
-    [ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
+	[ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
 
+	if [ -z "$jname" ]; then
+		_jname=$( cbsd -c "cbsdsql ${_rnode} SELECT jname FROM jails WHERE status\<2" )
+	else
+		_jname=${jname}
+	fi
 
-    if [ -z "$jname" ]; then
-        _jname=$( cbsd -c "cbsdsql ${_rnode} SELECT jname FROM jails WHERE status\<2" )
-    else
-        _jname=${jname}
-    fi
+	[ -z "${_jname}" ] && return 0
 
-    [ -z "${_jname}" ] && return 0
-
-    for _i in ${_jname}; do
-	[ ! -d "${dbdir}/rctl/${_rnode}-${_i}" ] && mkdir -p "${dbdir}/rctl/${_rnode}-${_i}"
-	nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/rctl/* ${dbdir}/rctl/${_rnode}.${_i}.descr 2>/dev/null && chmod 0600 ${dbdir}/rctl/${_rnode}-${_i}/* && chown ${cbsduser} ${dbdir}/rctl/${_rnode}-${_i}/* 2>/dev/null
-    done
+	for _i in ${_jname}; do
+		[ ! -d "${dbdir}/rctl/${_rnode}-${_i}" ] && mkdir -p "${dbdir}/rctl/${_rnode}-${_i}"
+		nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/rctl/* ${dbdir}/rctl/${_rnode}.${_i}.descr 2>/dev/null && chmod 0640 ${dbdir}/rctl/${_rnode}-${_i}/* && chown ${cbsduser} ${dbdir}/rctl/${_rnode}-${_i}/* 2>/dev/null
+	done
 }
 
 retr_fwcnt()
 {
-    local _rnode=$1 _jname
+	local _rnode=$1 _jname
 
-    [ -z "${_rnode}" ] && return 0
+	[ -z "${_rnode}" ] && return 0
 
-    [ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
+	[ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
 
-    if [ -z "$jname" ]; then
-	_jname=$( cbsd -c "cbsdsql ${_rnode} SELECT jname FROM jails WHERE status\<2" )
-    else
-	_jname=${jname}
-    fi
+	if [ -z "$jname" ]; then
+		_jname=$( cbsd -c "cbsdsql ${_rnode} SELECT jname FROM jails WHERE status\<2" )
+	else
+		_jname=${jname}
+	fi
 
-    [ -z "${_jname}" ] && return 0
+	[ -z "${_jname}" ] && return 0
 
-    for _i in ${_jname}; do
-	[ ! -d "${dbdir}/fwcnt/${_rnode}-${_i}" ] && mkdir -p "${dbdir}/fwcnt/${_rnode}-${_i}"
-	nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/traffic/* ${dbdir}/fwcnt/${_rnode}-${_i}/ 2>/dev/null && chmod 0600 ${dbdir}/fwcnt/${_rnode}-${_i}/* && chown ${cbsduser} ${dbdir}/fwcnt/${_rnode}-${_i}/* 2>/dev/null
-    done
+	for _i in ${_jname}; do
+		[ ! -d "${dbdir}/fwcnt/${_rnode}-${_i}" ] && mkdir -p "${dbdir}/fwcnt/${_rnode}-${_i}"
+		nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/traffic/* ${dbdir}/fwcnt/${_rnode}-${_i}/ 2>/dev/null && chmod 0640 ${dbdir}/fwcnt/${_rnode}-${_i}/* && chown ${cbsduser} ${dbdir}/fwcnt/${_rnode}-${_i}/* 2>/dev/null
+	done
 }
 
 
 # MAIN #
 [ -z "${data}" ] && data="db jdescr nodedescr rctl fwcnt"
 if [ -z "${tryoffline}" ]; then
-    tryoffline=0
-    checkforonline="tryoffline=0"
+	tryoffline=0
+	checkforonline="tryoffline=0"
 else
-    checkforonline="tryoffline=${tryoffline}"
+	checkforonline="tryoffline=${tryoffline}"
 fi
 
-
 if [ -z "${node}" ]; then
-    sqldelimer=" "
-    node=$( cbsdsql nodes select nodename from nodelist 2>/dev/null )
-    unset sqldelimer
+	sqldelimer=" "
+	node=$( cbsdsql nodes select nodename from nodelist 2>/dev/null )
+	unset sqldelimer
 fi
 
 # check node online and repopulate array of online nodes if needed
 if [ ${sqlreplica} -eq 1 -a ${tryoffline} -eq 0 ]; then
-    testnode="${node}"
-    node=""
-    for i in ${testnode}; do
-	NODEDATA=$( cbsdsql nodes select ip,port,keyfile from nodelist where nodename=\"${i}\" )
-        sqllist "$NODEDATA" myip myport mykey
+	testnode="${node}"
+	node=""
+	for i in ${testnode}; do
+		NODEDATA=$( cbsdsql nodes select ip,port,keyfile from nodelist where nodename=\"${i}\" )
+		sqllist "$NODEDATA" myip myport mykey
 
-	if ! check_locktime ${ftmpdir}/shmux_${myip}.lock >/dev/null 2>&1; then
-	    ${ECHO} "${MAGENTA}Node is offline: ${GREEN}${i}${NORMAL}"
-	    continue
-	fi
-	node="${node} ${i}"
-    done
+		if ! check_locktime ${ftmpdir}/shmux_${myip}.lock >/dev/null 2>&1; then
+			${ECHO} "${MAGENTA}Node is offline: ${GREEN}${i}${NORMAL}"
+			continue
+		fi
+		node="${node} ${i}"
+	done
 fi
 
 
 for i in ${node}; do
-    for items in ${data}; do
-	case "${items}" in
-	    db)
-		retr_db ${i}
-		;;
-	    nodedescr)
-		retr_nodedescr ${i}
-		;;
-	    jdescr)
-		retr_jdescr ${i}
-		;;
-#	    rctl)
-#		retr_rctl ${i}
-#		;;
-	    fwcnt)
-		retr_fwcnt ${i}
-#		;;
-	esac
-    done
+	for items in ${data}; do
+		case "${items}" in
+			db)
+				retr_db ${i}
+				;;
+			nodedescr)
+				retr_nodedescr ${i}
+				;;
+			jdescr)
+				retr_jdescr ${i}
+				;;
+			# rctl)
+			# retr_rctl ${i}
+			# ;;
+			fwcnt)
+				retr_fwcnt ${i}
+				;;
+		esac
+	done
 done
