jail2iso rewrite; some scenes rework; ddns initial support; sqlite library added; cbsdsar script;

diff --git a/9.1.0/tools/mountfstab b/9.1.0/tools/mountfstab
--- a/9.1.0/tools/mountfstab
+++ b/9.1.0/tools/mountfstab
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v9.0.0
+#v9.1.0
 globalconf="${workdir}/cbsd.conf";
 MYARG="jroot fstab"
 MYOPTARG=""
@@ -21,22 +21,23 @@ case ":${_device}" in
 continue
 ;;
 *)
-A=`echo ${_device} |grep ^/`
-if [ ! -z "${A}" ]; then
-	if [ ! -d "${_device}" ]; then
-	echo "No source dir ${_device} in fstab" > "${fstab}.err"
-	fi
-fi
+[ -z "${_device}" ] && continue
+echo ${_device} |grep -sq ^/
+[ $? -eq 0 -a ! -d "${_device}" ] && {
+TMPLOG=`mktemp ${ftmpdir}/fstab.XXX`
+trap "rm -f ${TMPLOG}" 0 1 2 3 4 5
+echo "Source dir ${_device} doesn't exist" > ${TMPLOG}
+}
 ;;
 esac
-
 done
 
-if [ -f "${fstab}.err" ]; then
-A=`cat ${fstab}.err`
-rm -f "${fstab}.err"
-err 1 "${A}"
-fi
+[ -f "${TMPLOG}" ] && {
+	ERRORLOG=`cat $TMPLOG`
+	rm -f ${TMPLOG}
+	err 1 "$ERRORLOG"
+}
+
 
 cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 case ":${_device}" in
