switch to svn; replace base to ver and change X_y form to X.y; update for scenes

diff --git a/9.1.0/tools/repo b/9.1.0/tools/repo
--- a/9.1.0/tools/repo
+++ b/9.1.0/tools/repo
@@ -4,13 +4,15 @@ globalconf="${workdir}/cbsd.conf";
 MYARG="action"
 # action=list,get,put
 # source=src,obj,base,kernel,img
-MYOPTARG="mode arch ver sources name stable"
+MYOPTARG="mode arch ver sources name basename stable"
 #mode=check,update,upgrade
 MYDESC="Working with CBSD Repository"
 ADDHELP="action can be: list, get, put
 sources can be: src, obj, base, kernel, img\n
 mode can be: check, update, upgrade, quiet\n\
-stable=1 for RELENG_X\n"
+stable=1 for RELENG_X\n\
+ver=any for mode=list for show all version (no for cur. version only\n\
+arch=any for mode=list for show all arch (no for cur. arch only\n"
 
 [ -f ${globalconf} ] || err 1 "no such conf file";
 . ${globalconf}
@@ -69,21 +71,17 @@ fi
 
 MIRROR="${REPO}/src_${ver}/mirror.html"
 
-fetch -o ${TF} ${MIRROR} > /dev/null 2>&1
+cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 if [ $? -eq 0 ]; then
     REPO=`cat ${TF}`
     echo "Found new mirror for ${ver}: ${REPO}"
 fi
 
-if fetchme "${REPO}/${DIR}/cbsd.index"; then
-    echo "Fetching source for ${ver}..."
-else
-    err 1 "No such index"
-fi
-
 cbsd cfetch -o ${MYDIR}/src.txz -u ${REPO}/${DIR}/src.txz
+[ $? -eq 0 ] || err 1 "No such files in repo"
 cbsd cfetch -o ${MYDIR}/src.txz.md5 -u ${REPO}/${DIR}/src.txz.md5 >/dev/null 2>&1
+[ $? -eq 0 ] || err 1 "No such md5 files in repo"
 
 [ -d "${MYDIR}" ] || err 1 "No source dir"
 
@@ -95,8 +93,6 @@ fi
 
 ARCHIVE="${workdir}/tmp/src_${ver}.txz"
 [ ! -f "${ARCHIVE}" ] || rm -f ${ARCHIVE}
-
-rm -f ${MYDIR}/cbsd.index
 
 echo "Extracting..."
 cd $workdir/tmp
@@ -113,84 +109,75 @@ DT=`/bin/date "+%Y%m%d"`
 
 getbase()
 {
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
     BDIR="${basejailpref}_${arch}_${ver}"
 else
-    BDIR="${basejailpref}_${name}_${arch}_${ver}"
+    BDIR="${basejailpref}_${basename}_${arch}_${ver}"
 fi
 
 DST="${basejaildir}/${BDIR}"
 MIRROR="http://ftp.freebsd.org"
-Bver=`echo ${ver} |tr "_" "."`
-BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${Bver}-RELEASE/base.txz"
+BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/base.txz"
 
 if [ -d "${DST}" ]; then
     [ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
     cbsd removebase ver=${ver} arch=${arch}
 fi
 
-if [ "$fbsdrepo" = "1" -a -z "${name}" ]; then
-## Official fbsd repo
-printf "Looking for official FreeBSD mirror.."
-ARCHIVE="$MYDIR/base.txz"
-cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
-if [ $? -eq 0 ]; then
-printf "\nExtracting base...\n"
-mkdir $DST
-cd $DST
-tar xfz ${ARCHIVE}
-rm -f ${ARCHIVE}
+if [ "$fbsdrepo" = "1" -a -z "${basename}" ]; then
+    ## Official fbsd repo
+    printf "Looking for official FreeBSD mirror.."
+    ARCHIVE="$MYDIR/base.txz"
+    cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
+    if [ $? -eq 0 ]; then
+	printf "\nExtracting base...\n"
+	mkdir $DST
+	cd $DST
+	tar xfz ${ARCHIVE}
+	rm -f ${ARCHIVE}
+	BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${ver}-RELEASE/lib32.txz"
+	ARCHIVE="$MYDIR/lib32.txz"
+	cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
+	    if [ $? -eq 0 ]; then
+		printf "\nExtracting lib32...\n"
+		cd $DST
+		tar xfz ${ARCHIVE}
+		rm -f ${ARCHIVE}
+	    else
+		printf "Lib32 not found\n"
+	    fi
+	cbsd preparebase dst=${DST}
+	echo "Done..."
+	return 0
+    fi
 
-BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${arch}/${arch}/${Bver}-RELEASE/lib32.txz"
-ARCHIVE="$MYDIR/lib32.txz"
-cbsd cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
-if [ $? -eq 0 ]; then
-    printf "\nExtracting lib32...\n"
-    cd $DST
-    tar xfz ${ARCHIVE}
-    rm -f ${ARCHIVE}
-else
-    printf "Lib32 not found\n"
+    printf "Not found\n"
+    ### Official fbsd repo end ###
 fi
 
-cbsd preparebase dst=${DST}
-
-echo "Done..."
-return 0
-fi
-
-printf "Not found\n"
-
-### Official fbsd repo end ###
-fi
-
-
-
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
         MIRROR="${REPO}/base_${arch}_${ver}/mirror.html";
     else
-        MIRROR="${REPO}/base_${name}_${arch}_${ver}/mirror.html";
+        MIRROR="${REPO}/base_${basename}_${arch}_${ver}/mirror.html";
 fi
 
-fetch -o ${TF} ${MIRROR} > /dev/null 2>&1
+cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 if [ $? -eq 0 ]; then
     REPO=`cat ${TF}`
-    echo "Found new mirror for ${name}: ${REPO}"
+    echo "Found new mirror for ${basename}: ${REPO}"
 fi
 
-if fetchme "${REPO}/${DIR}/cbsd.index" >/dev/null 2>&1; then
-    echo "Fetching base for ${arch} ${ver}..."
-else
-    err 1 "No cbsd index..."
-fi
-
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
     cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz -u ${REPO}/${DIR}/base_${arch}_${ver}.txz
+    [ $? -eq 0 ] || err 1 "No such files in repo"
     cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+    [ $? -eq 0 ] || err 1 "No such md5 files in repo"
 else
-    cbsd cfetch -o ${MYDIR}/base_${name}_${arch}_${ver}.txz -u ${REPO}/${DIR}/base_${name}_${arch}_${ver}.txz
-    cbsd cfetch -o ${MYDIR}/base_${name}_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/base_${name}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz -u ${REPO}/${DIR}/base_${basename}_${arch}_${ver}.txz
+    [ $? -eq 0 ] || err 1 "No such files in repo"
+    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+    [ $? -eq 0 ] || err 1 "No such md5 files in repo"
 fi
 
 if checkmd5 ${MYDIR}; then
@@ -199,11 +186,10 @@ echo "MD5sum correct."
 err 1 "MD5sum incorrect."
 fi
 
-rm -f ${MYDIR}/cbsd.index 
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
     rm -f  ${MYDIR}/base_${arch}_${ver}.txz.md5
 else
-    rm -f ${MYDIR}/base_${name}_${arch}_${ver}.txz.md5
+    rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
 fi
 
 echo "Extracting..."
@@ -212,12 +198,12 @@ echo "Extracting..."
 cd $basejaildir
 #/base_${arch}_${ver}
 
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
     tar xfz ${MYDIR}/base_${arch}_${ver}.txz
     rm -f ${MYDIR}/base_${arch}_${ver}.txz.md5
 else
-    tar xfz ${MYDIR}/base_${name}_${arch}_${ver}.txz
-    rm -f ${MYDIR}/base_${name}_${arch}_${ver}.txz.md5
+    tar xfz ${MYDIR}/base_${basename}_${arch}_${ver}.txz
+    rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
 fi
 
 echo "Done..."
@@ -227,17 +213,17 @@ return 0
 
 getobj()
 {
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
     DST="${srcdir}/obj_${arch}_${ver}"
 else
-    DST="${srcdir}/obj_${name}_${arch}_${ver}"
+    DST="${srcdir}/obj_${basename}_${arch}_${ver}"
 fi
 
 
-if [ -z "${name}" ]; then
+if [ -z "${basename}" ]; then
         MIRROR="${REPO}/obj_${arch}_${ver}";
     else
-        MIRROR="${REPO}/obj_${name}_${arch}_${ver}";
+        MIRROR="${REPO}/obj_${basename}_${arch}_${ver}";
 fi
 
 if [ -d "${DST}" ]; then
@@ -245,24 +231,17 @@ if [ -d "${DST}" ]; then
     cbsd removeobj ver=${ver} arch=${arch}
 fi
 
-
-fetch -o ${TF} ${MIRROR} > /dev/null 2>&1
+cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 if [ $? -eq 0 ]; then
     REPO=`cat ${TF}`
-    echo "Found new mirror for ${name}: ${REPO}"
-fi
-
-
-
-if fetchme "${REPO}/${DIR}/cbsd.index" > /dev/null 2>&1; then
-    echo "Fetching obj for ${arch} ${ver}..."
-else
-    err 1 "No such index..."
+    echo "Found new mirror for ${basename}: ${REPO}"
 fi
 
 cbsd cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz -u ${REPO}/${DIR}/obj_${arch}_${ver}.txz
+[ $? -eq 0 ] || err 1 "No such files in repo"
 cbsd cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/obj_${arch}_${ver}.md5 >/dev/null 2>&1
+[ $? -eq 0 ] || err 1 "No such md5 files in repo"
 
 if checkmd5 ${MYDIR}; then
 echo "MD5sum correct."
@@ -271,7 +250,7 @@ err 1 "MD5sum incorrect."
 exit
 fi
 
-rm -f ${MYDIR}/cbsd.index ${MYDIR}/obj_${arch}_${ver}.txz.md5
+rm -f ${MYDIR}/obj_${arch}_${ver}.txz.md5
 
 echo "Extracting..."
 cd $srcdir
@@ -297,21 +276,17 @@ fi
 
 MIRROR="${REPO}/kernel_${name}_${arch}_${ver}/mirror.html"
 
-fetch -o ${TF} ${MIRROR} > /dev/null 2>&1
+cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 if [ $? -eq 0 ]; then
     REPO=`cat ${TF}`
     echo "Found new mirror for ${name}: ${REPO}"
 fi
 
-if fetchme "${REPO}/${DIR}/cbsd.index" > /dev/null 2>&1; then
-    echo "Fetching kernel for ${arch} ${ver}..."
-else
-    err 1 "No such index..."
-fi
-
 cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz -u ${REPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz
+[ $? -eq 0 ] || err 1 "No such files in repo"
 cbsd cfetch -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5 -u ${REPO}/${DIR}/kernel_${name}_${arch}_${ver}.md5 >/dev/null 2>&1
+[ $? -eq 0 ] || err 1 "No such md5 files in repo"
 
 if checkmd5 ${MYDIR}; then
 echo "MD5sum correct."
@@ -320,7 +295,7 @@ err 1 "MD5sum incorrect."
 exit
 fi
 
-rm -f ${MYDIR}/cbsd.index ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5
+rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5
 
 echo "Extracting..."
 cd $basejaildir
@@ -340,7 +315,7 @@ JAILRCCONF="${jailrcconfdir}/rc.conf_${name}"
 
 MIRROR="${REPO}/img_${arch}_${ver}_${name}/mirror.html"
 
-fetch -o ${TF} ${MIRROR} > /dev/null 2>&1
+cbsd cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
 if [ $? -eq 0 ]; then
     REPO=`cat ${TF}`
@@ -357,7 +332,7 @@ cbsd jimport jname=${name}
 #### MAIN ####
 UPGRADE=0
 QUIET=0
-TF="/tmp/test.$$"
+TF="${ftmpdir}/test.$$"
 MYDIR="${workdir}/tmp/src.$$"
 
 [ -z "${action}" ] && err 1 "Give me action"
@@ -378,14 +353,25 @@ case "${action}" in
 "list")
 if fetchme "${REPO}/${sources}ls" >/dev/null 2>&1; then
 	echo "Available sources:"
-	cat ${TF}
+	if [ "${ver}" = "any" ]; then
+	    ver="[[:alnum:]]"
+	else 
+	    [ -z "${ver}" ] && ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1 |tr "." "_"`
+	fi
+	if [ "${arch}" = "any" ]; then
+	    arch="[[:alnum:]]"
+	else
+	    [ -z "${arch}" ] && arch=`/sbin/sysctl -n hw.machine_arch`
+	fi
+
+#	    echo grep -E ${arch}_${ver} ${TF}
+	    grep -E ${arch}_${ver} ${TF}
+#rm -f ${TF}
 fi
 ;;
 "get")
+. $buildconf
 [ -z "${sources}" ] && err 1 "Give me sources"
-[ -n "${ver}" ] || ver=`/sbin/sysctl -n kern.osrelease|cut -d "-" -f1 |tr "." "_"`
-[ "${stable}" = "1" ] && ver=${ver%%_*}
-[ -n "${arch}" ] || arch=`/sbin/sysctl -n hw.machine_arch`
 
 case "${sources}" in
 "src")
@@ -396,10 +382,10 @@ case "${sources}" in
     mkdir -p ${MYDIR}
     getsrc ;;
 "base")
-    if [ -z "${name}" ]; then
+    if [ -z "${basename}" ]; then
 	DIR="base_${arch}_${ver}"; 
     else
-	DIR="base_${name}_${arch}_${ver}"; 
+	DIR="base_${basename}_${arch}_${ver}"; 
     fi
     SRC="${srcdir}/src_${ver}"
     LOCKFILE=${SRC}.lock
@@ -407,10 +393,10 @@ case "${sources}" in
     mkdir -p ${MYDIR}
     getbase ;;
 "obj")
-    if [ -z "${name}" ]; then
+    if [ -z "${basename}" ]; then
 	DIR="obj_${arch}_${ver}";
     else
-	DIR="obj_${name}_${arch}_${ver}";
+	DIR="obj_${basename}_${arch}_${ver}";
     fi
 
     SRC="${srcdir}/src_${ver}"
