update/bump dynamic data

diff --git a/tests/runall b/tests/runall
--- a/tests/runall
+++ b/tests/runall
@@ -6,7 +6,10 @@ for i in ${ALL_TESTS}; do
 	echo "--- ${i} ---"
 	${i}
 	ret=$?
-	[ ${ret} -ne 0 ] && exit ${ret}
+	if [ ${ret} -ne 0 ]; then
+		echo "FAILED: ${i}"
+		exit ${ret}
+	fi
 done
 
 exit 0
