Sync with my svn

diff --git a/9.1.0/jailctl/jcreate b/9.1.0/jailctl/jcreate
--- a/9.1.0/jailctl/jcreate
+++ b/9.1.0/jailctl/jcreate
@@ -9,14 +9,15 @@ ADDHELP="inter=0 to prevent any questions and to accept answers by default\n"
 [ -f ${globalconf} ] || err 1 "no such conf file";
 . ${globalconf}
 . ${subr}
+. ${system}
 . ${inventory}
 init $*
 
 mkfstab() {
-if [ $baserw -eq 1 ]; then
+    if [ $baserw -eq 1 ]; then
 cat > ${mount_fstab} << EOF
 EOF
-else
+    else
 cat > ${mount_fstab} << EOF
 ${data}/etc /etc nullfs rw 0 0
 ${data}/root /root nullfs rw 0 0
@@ -27,20 +28,21 @@ ${data}/var /var nullfs rw 0 0
 /var/cache/pkg /var/cache/pkg nullfs rw 0 0
 #
 EOF
-fi
+    fi
 
-if [ $srcmount -eq 1 ]; then
-SOURCE="$srcdir/src_${ver}"
+    if [ $srcmount -eq 1 ]; then
+	SOURCE="$srcdir/src_${ver}"
 cat >> ${mount_fstab} << EOF
 ${SOURCE}/src /usr/src nullfs rw 0 0
 EOF
-fi
 
-if [ $portsmount -eq 1 ]; then
-cat >> ${mount_fstab} << EOF
+    fi
+
+    if [ $portsmount -eq 1 ]; then
+	cat >> ${mount_fstab} << EOF
 /usr/ports /usr/ports nullfs rw 0 0
 EOF
-fi
+    fi
 }
 
 
@@ -48,21 +50,14 @@ mkrcconf() {
     cp $jconf $rcconf
 }
 
+### MAIN
 [ -f "$jconf" ] || err 1 "no such jconf file";
 . ${jconf}
 
 cbsd jstatus jname=${jname} > /dev/null 2>&1
 [ $? -eq 0 ] || err 1 "Jail with $jname already exist"
-
-if [ -z "${arch}" -o "${arch}" = "native" ]; then
-    arch=`uname -m`
-fi
-
-if [ -z "${ver}" -o "${ver}" = "native" ]; then
-    ver=`sysctl -n kern.osrelease|cut -d - -f 1`
-fi
-
-
+[ -z "${arch}" -o "${arch}" = "native" ] && arch=`uname -m`
+[ -z "${ver}" -o "${ver}" = "native" ] && ver=`sysctl -n kern.osrelease|cut -d - -f 1`
 
 ### CURRENT
 src="${basejaildir}/${basejailpref}_${arch}_${ver}"
@@ -95,70 +90,70 @@ usr/share"
 
 if [ ! -d "${src}" ]; then
     [ "${ver}" = "empty" ] || {
-#    echo "No data at ${src}"
-    getyesno "No base in ${src}. Try to fetch from remote repository?"
-    [ $? -eq 1 -o $? -eq 3 ] && err 1 "No data at ${src}"
-    cbsd repo action=get sources=base arch=${arch} ver=${ver}
-    [ $? -eq 1 ] && err 1 "No data at ${src}"
+	#    echo "No data at ${src}"
+	getyesno "No base in ${src}. Try to fetch from remote repository?"
+	[ $? -eq 1 -o $? -eq 3 ] && err 1 "No data at ${src}"
+	cbsd repo action=get sources=base arch=${arch} ver=${ver}
+	[ $? -eq 1 ] && err 1 "No data at ${src}"
     }
 fi
 
+
 if [ -n "${interface}" -a "${inteface}" != "0" ]; then
-### CHECK FOR IP ( 1 - check for interfaces) ####
-cbsd checkip ip=${ips} check=1 > /dev/null 2>&1
-case $? in
-0)
-err 1 "Ip not in pool range";;
-1)
-;;
-2)
-echo "Warning: Ip already exists in LAN";;
-default)
-exit;;
-esac
-#####################
+	### CHECK FOR IP ( 1 - check for interfaces) ####
+	cbsd checkip ip=${ips} check=1 > /dev/null 2>&1
+	case $? in
+	    0) err 1 "Ip not in pool range"
+		;;
+	    1)	;;
+	    2) echo "Warning: Ip already exists in LAN"
+		;;
+	    default) exit
+        	;;
+	esac
+	#####################
 fi
 
+echo "Please wait: it will take some time..."
+
 [ -d "${data}" ] && {
-
-case $zfsfeat in
-0)
-    chflags -R noschg ${data}
-    rm -rf "${data}"
-;;
-1)
-    . $zfstool
-    zfsmnt ${data}
-    case $? in
-	0) break ;;
-	[12]) echo "Remove stale zfs"
-	    /sbin/zfs unmount ${ZPOOL} && zfs destroy ${ZPOOL}
-	;;
-	*) err 1 "Unknown result from zfsmnt" ;;
-    esac
-;;
-esac
-
+	case $zfsfeat in
+	    0) chflags -R noschg ${data}
+		rm -rf "${data}"
+		;;
+	    1)  . $zfstool
+		zfsmnt ${data}
+		case $? in
+		    0) break 
+			;;
+		    [12]) echo "Remove stale zfs"
+		    /sbin/zfs unmount ${ZPOOL} && zfs destroy ${ZPOOL}
+			;;
+		    *) err 1 "Unknown result from zfsmnt" 
+		        ;;
+		esac
+		;;
+	esac
 }
 
 case $zfsfeat in
-"0") [ -d ${data} ] || mkdir -p ${data} ;;
-"1")
-. $zfstool
-ZPOOL=`zfs get -Ho value name ${jaildatadir}`
+	"0") [ -d ${data} ] || mkdir -p ${data} 
+	    ;;
+	"1") . $zfstool
+	    ZPOOL=`zfs get -Ho value name ${jaildatadir}`
 
-if zfsroot $jname; then
-    err 1 "$ZPOOL/$jname already in use"
-fi
+	    if zfsroot $jname; then
+		err 1 "$ZPOOL/$jname already in use"
+	    fi
 
-zfs create -o atime=off -o mountpoint=${data} ${ZPOOL}/$jname ;;
+	    zfs create -o atime=off -o mountpoint=${data} ${ZPOOL}/$jname 
+	    ;;
 esac
 
-[ -d "${data}" ] || err 1 "Can't create datadir"
-[ -d ${path} ] || mkdir -p ${path}
-[ -d ${jailfstabdir}  ] || mkdir -p ${jailfstabdir}
-[ -d ${jailrcconfdir}  ] || mkdir -p ${jailrcconfdir}
-
+    [ -d "${data}" ] || err 1 "Can't create datadir"
+    [ -d ${path} ] || mkdir -p ${path}
+    [ -d ${jailfstabdir}  ] || mkdir -p ${jailfstabdir}
+    [ -d ${jailrcconfdir}  ] || mkdir -p ${jailrcconfdir}
 
 ### COPY FROM BASE
 if [ "${ver}" != "empty" ]; then
@@ -178,7 +173,7 @@ if [ "${ver}" != "empty" ]; then
 	    fi
 	fi
 	done
-    fi
+fi
 
 touch "${data}/etc/fstab"
 
@@ -205,3 +200,30 @@ fi  # if ver = empty
 
 mkfstab
 mkrcconf
+
+if [ "${pkglist}" != "NO" -a "${ver}" != "empty" -a -f "${pkglist}" ]; then
+    echo "Populate jail data by pkg from repository via pkglist..."
+    mountbase
+    cbsd mountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
+    mount -t devfs devfs $path/dev
+    #
+    [ ! -d "${path}/usr/local/etc" ] && mkdir ${path}/usr/local/etc
+    cp /usr/local/etc/pkg.conf ${path}/usr/local/etc/
+    printf "pkg: [boostrap... "
+    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg > /dev/null 2>&1
+    printf "looking for new version... "
+    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg update -f > /dev/null 2>&1
+    #lets upgrade pkg if new version available
+    printf "upgrading... "
+    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg upgrade > /dev/null 2>&1
+    PKGLIST=`cat ${pkglist} |xargs`
+    printf "install for ${PKGLIST}...]\n"
+    chroot ${path} env ASSUME_ALWAYS_YES=yes pkg install ${PKGLIST}
+    cbsd unmountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
+    umount -f ${path}/dev
+    unmountbase
+    rm -f ${pkglist}
+fi
+
+echo
+echo "Creating ${jname} complete: Enjoy!"
diff --git a/9.1.0/nodectl/node b/9.1.0/nodectl/node
--- a/9.1.0/nodectl/node
+++ b/9.1.0/nodectl/node
@@ -1,12 +1,13 @@
 #!/bin/sh
-#v9.0.0
+#v9.1.0
 globalconf="${workdir}/cbsd.conf";
 MYARG="mode"
-MYOPTARG="node port pw"
+MYOPTARG="node port rootkeyfile pw"
 MYDESC="Manipulate with remote nodes"
-ADDHELP="mode = add , del , list\n\
+ADDHELP="mode = add , remove , list\n\
 node = remote node ip or fqdn\n\
 port = ssh port of remote node\n\
+rootkeyfile = path to id_rsa for root access\n\
 pw = password of cbsd user from remote node\n"
 
 [ -f ${globalconf} ] || err 1 "no such conf file";
@@ -17,82 +18,92 @@ init $*
 
 nodeadd()
 {
-[ -n "${node}" ] || err 1 "Empty node"
-[ -z "${port}" ] && port=22222
-[ -z "${pw}" ] && err 1 "Empty pw"
+    [ -n "${node}" ] || err 1 "Empty node"
+    [ -z "${port}" ] && port=22222
+    [ -z "${pw}" ] && err 1 "Empty pw"
+    [ -z "${rootkeyfile}" ] && rootkeyfile="/root/.ssh/id_rsa"
 
-if iptype $node; then
-    resolvhost ${node}
-    node=$HST
-fi
+    if iptype $node; then
+	resolvhost ${node}
+	node=$HST
+    fi
 
-NODENAME=`cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename`
+    NODENAME=`cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename`
 
-case $? in
-0)
-[ -z "$NODENAME" ] && err 1 "No nodename found. Check remote cbsd settings"
-echo "$node has nodename ${NODENAME}"
-;;
-1)
-err 1 "Connection problem with $node"
-;;
-2)
-err 1 "Bad password or system user"
-;;
-esac
+    case $? in
+	0)
+	    [ -z "$NODENAME" ] && err 1 "No nodename found. Check remote cbsd settings"
+	    echo "$node has nodename ${NODENAME}"
+	;;
+	1)
+	    err 1 "Connection problem with $node"
+	;;
+	2)
+	    err 1 "Bad password or system user"
+	;;
+    esac
 
-MD5NAME=`md5 -qs ${NODENAME}`
-cbsd nodeaddkey md5name=${MD5NAME} ip=${node} port=${port} pw=${pw} > $DEBLOG 2>&1
+    MD5NAME=`md5 -qs ${NODENAME}`
+    cbsd nodeaddkey md5name=${MD5NAME} ip=${node} port=${port} pw=${pw} > $DEBLOG 2>&1
 
-case $? in
-0)
-echo "${node} Added successfull"
-
-LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
-modconf ${rsshdir}/${NODENAME}.node SSHKEY $LOCALKEY
-modconf ${rsshdir}/${NODENAME}.node IP $node
-modconf ${rsshdir}/${NODENAME}.node PORT $port
-cbsd nodesql ${dbdir}/nodes.db insert ${NODENAME} ${node} ${port} ${LOCALKEY}
-;;
-1)
-    cat ${DEBLOG}
-    err 1 "Error: Bad password" ;;
-2)
-    cat ${DEBLOG}
-    err 1 "Error: No key found or wrong hostname. Make initenv on remote machine" ;;
-*)
-    cat ${DEBLOG}
-    err 1 "Error: Unkown error" ;;
-esac
+    case $? in
+	0)
+	    echo "${node} Added successfull"
+	    LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
+	    modconf ${rsshdir}/${NODENAME}.node SSHKEY $LOCALKEY
+	    modconf ${rsshdir}/${NODENAME}.node IP $node
+	    modconf ${rsshdir}/${NODENAME}.node PORT $port
+	    A=`cbsd nodesql --dbfile=${dbdir}/nodes.db --action=select --nodename=${NODENAME} --param=ip`
+	    if [ -z "${A}" ]; then
+		cbsd nodesql --dbfile=${dbdir}/nodes.db --action=insert --nodename=${NODENAME} --ip=${node} --port=${port} --keyfile=${LOCALKEY} --rootkeyfile=$rootkeyfile
+	    else
+		echo "${node} Already exist in database, updating..."
+		cbsd nodesql --dbfile=${dbdir}/nodes.db --action=delete --nodename=${NODENAME}
+		cbsd nodesql --dbfile=${dbdir}/nodes.db --action=insert --nodename=${NODENAME} --ip=${node} --port=${port} --keyfile=${LOCALKEY} --rootkeyfile=$rootkeyfile
+	    fi
+	;;
+	1)
+	    cat ${DEBLOG}
+	    err 1 "Error: Bad password"
+	;;
+	2)
+	    cat ${DEBLOG}
+	    err 1 "Error: No key found or wrong hostname. Make initenv on remote machine"
+	;;
+	*)
+	    cat ${DEBLOG}
+	    err 1 "Error: Unkown error"
+	;;
+    esac
 }
 
 nodedel()
 {
-[ -n "${node}" ] || err 1 "Empty node"
+    [ -n "${node}" ] || err 1 "Empty node"
+    NODECONF="${rsshdir}/${node}.node"
 
-NODECONF="${rsshdir}/${node}.node"
+    [ -f "${NODECONF}" ] || err 1 "No such node config"
+    . ${NODECONF}
 
-[ -f "${NODECONF}" ] || err 1 "No such node config"
-. ${NODECONF}
-
-[ -f ${SSHKEY} ] && rm -f ${SSHKEY}
-rm -f ${NODECONF}
-cbsd nodesql ${dbdir}/nodes.db delete ${node}
-echo "Removed"
+    [ -f ${SSHKEY} ] && rm -f ${SSHKEY}
+    rm -f ${NODECONF}
+    cbsd nodesql --dbfile=${dbdir}/nodes.db --action=delete --nodename=${node}
+    echo "Removed"
 }
 
+
 case "${mode}" in
-"add")
-    nodeadd
-;;
-"del")
-    nodedel
-;;
-"list")
+    "add")
+	nodeadd
+    ;;
+    "remove")
+	nodedel
+    ;;
+    "list")
 #    ls -1 ${rsshdir} |grep \.node$ |sed 's/\.node//g'
-    cbsd nodesql ${dbdir}/nodes.db list
-;;
-*)
-err 1 "Unknown mode"
-;;
+	cbsd nodesql --dbfile=${dbdir}/nodes.db --action=list
+    ;;
+    *)
+	err 1 "Unknown mode"
+    ;;
 esac
