qexec/bexec fixes; style

diff --git a/qemuctl/qlogin b/qemuctl/qlogin
--- a/qemuctl/qlogin
+++ b/qemuctl/qlogin
@@ -3,8 +3,39 @@
 CIXARG=""
 CIXOPTARG="jname remote inter"
 MYDESC="Exec login into QEMU domain"
-ADDHELP="\
-  If you are in the CBSDfile directory, these environments will always have priority\n\
+ADDHELP="
+${H3_COLOR}Description${N0_COLOR}:
+
+ Login into QEMU domain console via tmux or custom login command.
+ The login method is configured via readconf qlogin.conf.
+ If login_cmd is set to 'internal', the script attaches to the
+ QEMU tmux session. Otherwise, login_custom() is called with
+ the configured command.
+
+ If the QEMU domain has vm_efi set and VNC port file exists,
+ a notice about VNC mode is displayed before connecting.
+
+ If you are in the CBSDfile directory, these environments will
+ always have priority.
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}jname=${N0_COLOR}    - target QEMU domain name;
+ ${N2_COLOR}remote=${N0_COLOR}  - '1' prevent searching in remote node base.
+                  For avoid the looping.
+ ${N2_COLOR}inter=${N0_COLOR}   - interactive mode flag;
+
+${H3_COLOR}Examples${N0_COLOR}:
+
+ # cbsd qlogin
+ # cbsd qlogin jname=myvm
+
+${H3_COLOR}See also${N0_COLOR}:
+
+   cbsd qset --help
+   cbsd qstart --help
+   cbsd qexec --help
+
 "
 EXTHELP="wf_qlogin"
 CBSDMODULE="qemu"
@@ -23,7 +54,8 @@ try_remote()
 	export_qemu_data_for_external_hook
 
 	[ "${remote}" = "1" ] && err 1 "${N1_COLOR}No such domain${N0_COLOR}"
-	RHST=$( bwhereis ${jname} | ${HEAD_CMD} -n1 )
+	capture _bwhereis_out bwhereis ${jname}
+	read -r RHST _ <<< "${_bwhereis_out}"
 	[ -z "${RHST}" ] && err 1 "No such domain for login"
 
 	# we don't need for interactive when come with remote=2 from select_jail_by_list
@@ -34,7 +66,7 @@ try_remote()
 
 	case "${login_cmd}" in
 		internal)
-			echo "${N1_COLOR}Exec qlogin internal on remote node: ${N2_COLOR}${RHST}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}Exec qlogin internal on remote node: ${N2_COLOR}${RHST}${N0_COLOR}"
 			cbsdlogger NOTICE ${CIX_APP}: executing internal qlogin: rexe node=${RHST} /usr/local/bin/cbsd qlogin src_session=${nodename} jname=${jname} remote=1
 			rexe node=${RHST} /usr/local/bin/cbsd qlogin src_session=${nodename} jname=${jname} remote=1
 			;;
@@ -54,20 +86,20 @@ login_internal()
 
 	# reset CBSD PATH
 	export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
-	local TMUX_CMD=$( which tmux )
+	capture TMUX_CMD which tmux
 
 	[ -z "${TMUX_CMD}" ] && err 1 "${N1_COLOR}no such tmux${N0_COLOR}"
 
 	if [ "${vm_efi}" != "none" ]; then
 		if [ -f "${jailsysdir}/${jname}/vnc_port" ]; then
-			echo " *** VM booted in VNC mode. ***"
-			echo "${N1_COLOR}For attach VM console, use: ${N2_COLOR}vncviewer ${qemu_vnc_tcp_ipconnect}:${vm_port}${N0_COLOR}"
+			${ECHO} " *** VM booted in VNC mode. ***"
+			${ECHO} "${N1_COLOR}For attach VM console, use: ${N2_COLOR}vncviewer ${qemu_vnc_tcp_ipconnect}:${vm_port}${N0_COLOR}"
 			if ! getyesno "Do you want to attach into UEFI console anyway?"; then
 				exit 0
 			fi
 		else
-			echo " *** VM booted in VNC mode. ***"
-			echo "But no ${jailsysdir}/${jname}/vnc_port file"
+			${ECHO} " *** VM booted in VNC mode. ***"
+			${ECHO} "But no ${jailsysdir}/${jname}/vnc_port file"
 			if ! getyesno "Do you want to attach into UEFI console anyway?"; then
 				exit 0
 			fi
@@ -89,7 +121,7 @@ login_custom()
 	# re-read custom
 	readconf qlogin.conf > /dev/null 2>&1
 
-	echo "${N1_COLOR}Custom login command: ${N2_COLOR}${login_cmd}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}Custom login command: ${N2_COLOR}${login_cmd}${N0_COLOR}"
 	exec /bin/sh -c "${login_cmd}"
 	# restore CBSD PATH
 	export PATH="${CBSDPATH}"
@@ -107,12 +139,12 @@ jname_qlogin()
 
 	readconf qlogin.conf
 
-	vm_efi=$( cbsdsqlro local "SELECT vm_efi FROM qemu WHERE jname=\"${jname}\"" )
-	vnc_bind=$( cbsdsqlro local "SELECT qemu_vnc_tcp_bind FROM qemu WHERE jname=\"${jname}\"" )
+	capture vm_efi cbsdsqlro local "SELECT vm_efi FROM qemu WHERE jname='${jname}'"
+	capture vnc_bind cbsdsqlro local "SELECT qemu_vnc_tcp_bind FROM qemu WHERE jname='${jname}'"
 
 	if [ "${vm_efi}" != "none" ]; then
 		if [ -f "${jailsysdir}/${jname}/vnc_port" ]; then
-			vm_port=$( ${CAT_CMD} ${jailsysdir}/${jname}/vnc_port )
+			capture vm_port ${CAT_CMD} ${jailsysdir}/${jname}/vnc_port
 		else
 			vm_port="0"
 		fi
@@ -134,7 +166,7 @@ jname_qlogin()
 # check for cloud function when CBSDfile exist
 Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" ]; then
-	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
+	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 	. ${Makefile}
 
 	all_qemu_list=$( ${GREP_CMD} -E '^qemu_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#qemu_##g )
@@ -167,12 +199,12 @@ if [ -r "${Makefile}" ]; then
 			jname=
 			select_jail_by_list -s "List of online jails limited by CBSDfile scope [${all_qemu_list}]:" -l "${all_qemu_list}" -r 0 -e qls
 			if [ -n "${jname}" ]; then
-				echo "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+				${ECHO} "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
 				jname_qlogin
 			fi
 		else
 			jname="${all_qemu_list}"
-			echo "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+			${ECHO} "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
 			jname_qlogin
 		fi
 		exit 0
@@ -184,31 +216,32 @@ fi
 if [ ${cbsd_api} -eq 1 ]; then
 	capture CURL_CMD which curl
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
-	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
+	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
 	capture _cid ${miscdir}/cbsd_md5 "${CLOUD_KEY}"
 
 	for jname in ${all_qemu_list}; do
 		[ -z "${jname}" ] && continue
-		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${jname} 2>&1 )
+		capture _ssh ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${jname} 2>&1
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			echo "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			continue
 		fi
-		_ssh_string=$( echo "${_ssh}" | ${JQ_CMD} '.ssh_string' | ${TR_CMD} -d '"' )
+
+		capture _jq_out jq '.ssh_string' <<< "${_ssh}"
+		capture _ssh_string strstrip --str="${_jq_out}" --chars='"'
+
 		case "${_ssh_string}" in
 			ssh\ *)
 				_ssh_post=${_ssh_string#ssh }
 				;;
 			*)
-				echo "${N1_COLOR}${CIX_APP} error: curl error2: ${N2_COLOR}${_ssh}${N0_COLOR}"
-				echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
+				${ECHO} "${N1_COLOR}${CIX_APP} error: curl error2: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 				continue
 				;;
 		esac
-		_ssh_ip=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $1}' )
-		_ssh_port=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $2}' | ${TR_CMD} -d '\-p' )
 
 		if [ -n "${SUDO_USER}" ]; then
 			if [ -r /home/${SUDO_USER}/.ssh/id_ed25519 ]; then
@@ -227,9 +260,9 @@ emulator="qemu"
 jname_is_multiple
 
 if [ -n "${jail_list}" ]; then
-	echo "${N1_COLOR}Found domains by mask: ${N2_COLOR}${jail_list}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}Found domains by mask: ${N2_COLOR}${jail_list}${N0_COLOR}"
 	for jname in ${jail_list}; do
-		echo "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}"
 		qlogin jname=${jname}
 	done
 	exit 0
diff --git a/sudoexec/bexec b/sudoexec/bexec
--- a/sudoexec/bexec
+++ b/sudoexec/bexec
@@ -3,9 +3,8 @@
 #v12.1.2
 CIXARG=""
 CIXOPTARG="cmd jname script"
-MYDESC="Execute command inside cloud-based vm"
+MYDESC="Execute command inside bhyve domain"
 ADDHELP="
-
 ${H3_COLOR}Description${N0_COLOR}:
 
  Run the command in the cloud-init-based bhyve VM from the master environment.
@@ -15,9 +14,9 @@ ${H3_COLOR}Description${N0_COLOR}:
 
 ${H3_COLOR}Options${N0_COLOR}:
 
+ ${N2_COLOR}jname=${N0_COLOR}  - target environment. If '*' or 'vm*' then execute on all
+              bhyve VM or whose names begin with 'vm';
  ${N2_COLOR}cmd=${N0_COLOR}    - command to execute inside VM, e.g. \"pwd\".
- ${N2_COLOR}jname=${N0_COLOR}  - target bhyve. If bhyve='*' or bhyve='vm*' then execute command on all
-              bhyve VM or in VM whose names begin with 'vm', e.g. 'vm1', 'vmX'...
  ${N2_COLOR}script=${N0_COLOR} - path to script instead of command.
 
 ${H3_COLOR}Examples${N0_COLOR}:
@@ -29,6 +28,11 @@ hostname
 ls -la
 sudo whoami
 EOF
+
+${H3_COLOR}See also${N0_COLOR}:
+
+ cbsd blogin --help
+ cbsd bset --help
 
 "
 
@@ -91,35 +95,31 @@ fi
 #######################################
 
 if [ -z "${cmd}" ] && [ -z "${script}" ]; then
-	# Pass '"' as ' in cmd
 	INIT_IFS="${IFS}"
 	IFS="~"
 #	cmd="$@"
 	IFS="${INIT_IFS}"
 	cmd=$( while [ -n "${1}" ]; do
-		#IFS="~"
 		strpos --str="${1}" --search="="
 		_pos=$?
 		if [ ${_pos} -eq 0 ]; then
 			# not params=value form
-			#printf "${1} "		# -x args trouble
 			# shellcheck disable=3037
 			echo -n "${1} "
 			shift
 			continue
 		fi
 
-		_arg_len=$( strlen "${1}" )
+		capture _arg_len strlen "${1}"
 		_pref=$(( _arg_len - _pos ))
-		ARG=$( substr --pos=0 --len=${_pos} --str="${1}" )
-		VAL=$( substr --pos=$(( _pos +2 )) --len=${_pref} --str="${1}" )
+		capture ARG substr --pos=0 --len=${_pos} --str="${1}"
 
 		if [ "${ARG}" = "jname" ]; then
 			shift
 			continue
 		fi
 
-		#printf "${ARG}=\"${VAL}\" "
+		capture VAL substr --pos=$(( _pos + 2 )) --len=${_pref} --str="${1}"
 		# shellcheck disable=3037
 		echo -n "${ARG}=\"${VAL}\" "
 		shift
@@ -134,7 +134,7 @@ fi
 if [ -z "${cmd}" ] && [ -z "${script}" ]; then
 	capture batchfile ${MKTEMP_CMD}
 	capture script_name ${BASENAME_CMD} "${batchfile}"
-	# todo: test/chec for stdin/blocked
+	# todo: test/check for stdin/blocked
 	while read -r _line; do
 		echo "${_line}" >> "${batchfile}"
 	done
@@ -142,7 +142,6 @@ if [ -z "${cmd}" ] && [ -z "${script}" ]; then
 	bexec jname="${jname}" /bin/sh ./"${script_name}"
 	ret=$?
 	${RM_CMD} -f "${batchfile}"
-	#err 1 "${N1_COLOR}${CIX_APP}: empty command${N0_COLOR}"
 	exit ${ret}
 fi
 
@@ -214,17 +213,19 @@ else # we use API
 			continue
 		fi
 
-		capture _ssh_string jq -r '.ssh_string' <<< "${_ssh}"
+		capture _jq_out jq '.ssh_string' <<< "${_ssh}"
+		capture _ssh_string strstrip --str="${_jq_out}" --chars='"'
 		capture _ssh_pref substr --pos=0 --len=3 --str="${_ssh_string}"
 
 		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error2, no ssh_string: ${N2_COLOR}${_ssh}${N0_COLOR}"
 			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			_global_ret=$(( _global_ret + 1 ))
 			continue
 		fi
 
-		_ssh_post="${_ssh_string#?????}"
+		capture _ssh_len strlen "${_ssh_string}"
+		capture _ssh_post substr --pos=5 --len=${_ssh_len} --str="${_ssh_string}"
 
 		# rewrite
 		if [ -n "${SUDO_USER}" ]; then
@@ -232,13 +233,11 @@ else # we use API
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_ed25519"
 			elif [ -r /home/"${SUDO_USER}"/.ssh/id_rsa ]; then
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_rsa"
-			else
-				date
 			fi
 		fi
 		bexec_cmd="${SSH_CMD} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_post}"
 
-		echo "[debug]: ${bexec_cmd}" 1>&2
+		${ECHO} "[debug]: ${bexec_cmd}" 1>&2
 		${bexec_cmd} <<CBSD_EOF
 ${cmd}
 CBSD_EOF
@@ -260,7 +259,7 @@ elif [ -n "${script}" ]; then # script
 	capture scr_name ${BASENAME_CMD} "${script}"
 	capture orig_path ${REALPATH_CMD} "${script}"
 	[ ! -x "${orig_path}" ] && err 1 "${N1_COLOR}not executable: ${N2_COLOR}${orig_path}${N0_COLOR}"
-	echo "bscp ${orig_path} ${jname}:${scr_name}"
+	${ECHO} "bscp ${orig_path} ${jname}:${scr_name}"
 	bscp "${orig_path}" "${jname}":"${scr_name}"
 	bexec jname="${jname}" ./"${scr_name}"
 fi
diff --git a/sudoexec/qexec b/sudoexec/qexec
--- a/sudoexec/qexec
+++ b/sudoexec/qexec
@@ -3,21 +3,20 @@
 #v12.1.2
 CIXARG=""
 CIXOPTARG="cmd jname script"
-MYDESC="Execute command inside cloud-based vm"
-ADDHELP="\
-
+MYDESC="Execute command inside QEMU domain"
+ADDHELP="
 ${H3_COLOR}Description${N0_COLOR}:
 
- Run the command in the cloud-init-based qemu VM from the master environment.
+ Run the command in the cloud-init-based QEMU VM from the master environment.
  If you are in the CBSDfile directory, these environments will always have priority.
  Keep in mind that by default the login is performed by an unprivileged user,
  which is specified in the configuration file.
 
 ${H3_COLOR}Options${N0_COLOR}:
 
+ ${N2_COLOR}jname=${N0_COLOR}  - target environment. If '*' or 'vm*' then execute on all
+              QEMU VM or whose names begin with 'vm';
  ${N2_COLOR}cmd=${N0_COLOR}    - command to execute inside VM, e.g. \"pwd\".
- ${N2_COLOR}jname=${N0_COLOR}  - target qemu. If qemu='*' or qemu='vm*' then execute command on all
-              qemu VM or in VM whose names begin with 'vm', e.g. 'vm1', 'vmX'...
  ${N2_COLOR}script=${N0_COLOR} - path to script instead of command.
 
 ${H3_COLOR}Examples${N0_COLOR}:
@@ -30,12 +29,16 @@ ls -la
 sudo whoami
 EOF
 
+${H3_COLOR}See also${N0_COLOR}:
+
+ cbsd qlogin --help
+ cbsd qset --help
+
 "
 
 CBSDMODULE="qemu"
 
 . "${subrdir}"/nc.subr
-cixinit
 script=
 cbsd_api=0
 jname=
@@ -93,35 +96,31 @@ fi
 #######################################
 
 if [ -z "${cmd}" ] && [ -z "${script}" ]; then
-	# Pass '"' as ' in cmd
 	INIT_IFS="${IFS}"
 	IFS="~"
 #	cmd="$@"
 	IFS="${INIT_IFS}"
 	cmd=$( while [ -n "${1}" ]; do
-		#IFS="~"
 		strpos --str="${1}" --search="="
 		_pos=$?
 		if [ ${_pos} -eq 0 ]; then
 			# not params=value form
-			#printf "${1} "		# -x args trouble
 			# shellcheck disable=3037
 			echo -n "${1} "
 			shift
 			continue
 		fi
 
-		_arg_len=$( strlen "${1}" )
+		capture _arg_len strlen "${1}"
 		_pref=$(( _arg_len - _pos ))
-		ARG=$( substr --pos=0 --len=${_pos} --str="${1}" )
-		VAL=$( substr --pos=$(( _pos +2 )) --len=${_pref} --str="${1}" )
+		capture ARG substr --pos=0 --len=${_pos} --str="${1}"
 
 		if [ "${ARG}" = "jname" ]; then
 			shift
 			continue
 		fi
 
-		#printf "${ARG}=\"${VAL}\" "
+		capture VAL substr --pos=$(( _pos + 2 )) --len=${_pref} --str="${1}"
 		# shellcheck disable=3037
 		echo -n "${ARG}=\"${VAL}\" "
 		shift
@@ -134,17 +133,16 @@ fi
 #######################################
 
 if [ -z "${cmd}" ] && [ -z "${script}" ]; then
-	batchfile=$( ${MKTEMP_CMD} )
-	script_name=$( ${BASENAME_CMD} "${batchfile}" )
-	# todo: test/chec for stdin/blocked
+	capture batchfile ${MKTEMP_CMD}
+	capture script_name ${BASENAME_CMD} "${batchfile}"
+	# todo: test/check for stdin/blocked
 	while read -r _line; do
 		echo "${_line}" >> "${batchfile}"
 	done
-	bscp "${batchfile}" "${jname}":"${script_name}" 1>&2
+	qscp "${batchfile}" "${jname}":"${script_name}" 1>&2
 	qexec jname="${jname}" /bin/sh ./"${script_name}"
 	ret=$?
 	${RM_CMD} -f "${batchfile}"
-	#err 1 "${N1_COLOR}${CIX_APP}: empty command${N0_COLOR}"
 	exit ${ret}
 fi
 
@@ -179,7 +177,7 @@ if [ -n "${jail_list}" ]; then
 		task_id="${task_id} ${task_id_cur}"
 	done
 
-	multiple_task_id_all=$( echo "${task_id}" | ${TR_CMD} " " "," )
+	capture multiple_task_id_all ${TR_CMD} " " "," <<< "${task_id}"
 	sleep 1
 	multiple_processing_spawn -o ${task_owner} -n "qexec"
 	echo
@@ -207,7 +205,7 @@ else # we use API
 	_global_ret=0
 
 	for jname in ${all_jail_list}; do
-		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" "${CLOUD_URL}"/api/v1/status/"${jname}" 2>&1 )
+		capture _ssh ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" "${CLOUD_URL}"/api/v1/status/"${jname}" 2>&1
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
 			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
@@ -216,23 +214,19 @@ else # we use API
 			continue
 		fi
 
-		_ssh_string=$( echo "${_ssh}" | ${JQ_CMD} '.ssh_string' | ${TR_CMD} -d '"' )
-		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh_string}" )
+		capture _jq_out jq '.ssh_string' <<< "${_ssh}"
+		capture _ssh_string strstrip --str="${_jq_out}" --chars='"'
+		capture _ssh_pref substr --pos=0 --len=3 --str="${_ssh_string}"
 
 		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error2, no ssh_string: ${N2_COLOR}${_ssh}${N0_COLOR}"
 			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			_global_ret=$(( _global_ret + 1 ))
 			continue
 		fi
 
-		_ssh_len=$( strlen "${_ssh_string}" )
-		_ssh_post=$( substr --pos=5 --len="${_ssh_len}" --str="${_ssh_string}" )
-		#echo "${SSH_CMD} ${_ssh_post}"
-		# shellcheck disable=2016
-		_ssh_ip=$( echo "${_ssh_post}" | ${AWK_CMD} '{printf $1}' )
-		# shellcheck disable=2016
-		_ssh_port=$( echo "${_ssh_post}" | ${AWK_CMD} '{printf $2}' | ${TR_CMD} -d '\-p' )
+		capture _ssh_len strlen "${_ssh_string}"
+		capture _ssh_post substr --pos=5 --len=${_ssh_len} --str="${_ssh_string}"
 
 		# rewrite
 		if [ -n "${SUDO_USER}" ]; then
@@ -240,13 +234,11 @@ else # we use API
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_ed25519"
 			elif [ -r /home/"${SUDO_USER}"/.ssh/id_rsa ]; then
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_rsa"
-			else
-				date
 			fi
 		fi
 		qexec_cmd="${SSH_CMD} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_post}"
 
-		echo "[debug]: ${qexec_cmd}" 1>&2
+		${ECHO} "[debug]: ${qexec_cmd}" 1>&2
 		${qexec_cmd} <<CBSD_EOF
 ${cmd}
 CBSD_EOF
@@ -265,11 +257,11 @@ if [ -n "${cmd}" ]; then # cmd
 
 elif [ -n "${script}" ]; then # script
 	[ ! -r "${script}" ] && err 1 "${N1_COLOR}No such script: ${N2_COLOR}${script}${N0_COLOR}"
-	scr_name=$( ${BASENAME_CMD} "${script}" )
-	orig_path=$( ${REALPATH_CMD} "${script}" )
+	capture scr_name ${BASENAME_CMD} "${script}"
+	capture orig_path ${REALPATH_CMD} "${script}"
 	[ ! -x "${orig_path}" ] && err 1 "${N1_COLOR}not executable: ${N2_COLOR}${orig_path}${N0_COLOR}"
-	echo "bscp ${orig_path} ${jname}:${scr_name}"
-	bscp "${orig_path}" "${jname}":"${scr_name}"
+	${ECHO} "qscp ${orig_path} ${jname}:${scr_name}"
+	qscp "${orig_path}" "${jname}":"${scr_name}"
 	qexec jname="${jname}" ./"${scr_name}"
 fi
 
