10.0.6a

diff --git a/jailctl/bcreate b/jailctl/bcreate
--- a/jailctl/bcreate
+++ b/jailctl/bcreate
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v10.0.4
+#v10.0.6
 MYARG="jconf"
 MYOPTARG="inter ver arch customskel fstablocal delpkglist removejconf pkglist"
 MYDESC="Create jail from config file"
@@ -28,7 +28,7 @@ init $*
 [ -f "$jconf" ] || err 1 "${MAGENTA}no such jconf file${NORMAL}";
 over="${ver}"
 oarch="${arch}"
-jconf=`realpath $jconf`
+jconf=$( realpath $jconf )
 
 if [ -z "${delpkglist}" ]; then
     delpkglist=0
@@ -84,13 +84,13 @@ case $zfsfeat in
 	"0") [ -d ${data} ] || mkdir -p ${data}
 	    ;;
 	"1") . $zfstool
-	    ZPOOL=`zfs get -Ho value name ${jaildatadir}`
+	    ZPOOL=$( /sbin/zfs get -Ho value name ${jaildatadir} )
 
 	    if zfsroot $jname; then
 		err 1 "$ZPOOL/$jname already in use"
 	    fi
 
-	    zfs create -o atime=off -o mountpoint=${data} ${ZPOOL}/$jname
+	    /sbin/zfs create -o atime=off -o mountpoint=${data} ${ZPOOL}/$jname
 	    ;;
 esac
 
@@ -108,51 +108,52 @@ cp $temprcconf $rcconf
 jregister jname=${jname} mode=new
 
 if [ $? -eq 0 ]; then
-    ${ECHO}
-    ${ECHO} "${MAGENTA}Creating ${jname} complete: ${GREEN}Enjoy!${NORMAL}"
-    rm -f $rcconf
+	${ECHO}
+	${ECHO} "${MAGENTA}Creating ${jname} complete: ${GREEN}Enjoy!${NORMAL}"
+	rm -f $rcconf
 
-    [ "${mdsize}" != "0" ] && unmountmd jroot=${data}
-    #timezone
+	[ "${mdsize}" != "0" ] && unmountmd jroot=${data}
+	#timezone
 
-    defdsk="dsk1.vhd"
+	defdsk="dsk1.vhd"
 
-    if [ "${vm_os_type}" = "freebsd" ]; then
-	jail2iso jname=${jname} nameserver=${jnameserver} ip4_addr=${ip4_addr} gw4=${gw4} dstname=${jname}.$$.img freesize=${freesize} dstdir=/tmp host_hostname="${host_hostname}" media=bhyve quiet=1 prunelist=0
-	jremove ${jname}
-	sysrc -qf ${jconf} ver="empty" > /dev/null
-	jcreate jconf=${jconf}
+	if [ "${vm_os_type}" = "freebsd" ]; then
+		jail2iso jname=${jname} nameserver=${jnameserver} ip4_addr=${ip4_addr} gw4=${gw4} dstname=${jname}.$$.img freesize=${freesize} dstdir=/tmp host_hostname="${host_hostname}" media=bhyve quiet=1 prunelist=0
+		jremove ${jname}
+		sysrc -qf ${jconf} ver="empty" > /dev/null
+		jcreate jconf=${jconf}
 
-	#test for zfs mounted & mount if not
-	case $zfsfeat in
-	    1) . $zfstool
-		zfsmnt ${data}
-		[ $? -eq 2 ] && zfs mount "${ZPOOL}"
-		;;
-	esac
+		#test for zfs mounted & mount if not
+		case $zfsfeat in
+			1)
+				. $zfstool
+				zfsmnt ${data}
+				[ $? -eq 2 ] && /sbin/zfs mount "${ZPOOL}"
+			;;
+		esac
 
-	sysrc -qf ${jconf} ver="${ver}" > /dev/null
-	mv /tmp/${jname}.$$.img ${data}/${defdsk}
-    else
-	if ! bhyve_create_dsk ${data}/${defdsk} ${freesize}; then
-		err 1 "Error: Couldn't create the image file. ${mdimage}"
+		sysrc -qf ${jconf} ver="${ver}" > /dev/null
+		mv /tmp/${jname}.$$.img ${data}/${defdsk}
+	else
+		if ! bhyve_create_dsk ${data}/${defdsk} ${freesize}; then
+			err 1 "Error: Couldn't create the image file. ${mdimage}"
+		fi
 	fi
-    fi
 
-    if [ -n "${virtio_type}" ]; then
-	${miscdir}/sqlcli ${dbdir}/local.sqlite "INSERT INTO bhyvedsk ( jname,dsk_controller,dsk_path,dsk_slot  ) VALUES ( \"${jname}\",\"${virtio_type}\",\"${defdsk}\","0" )"
-    else
-	${miscdir}/sqlcli ${dbdir}/local.sqlite "INSERT INTO bhyvedsk ( jname,dsk_path,dsk_slot  ) VALUES ( \"${jname}\",\"${defdsk}\","0" )"
-    fi
+	if [ -n "${virtio_type}" ]; then
+		${miscdir}/sqlcli ${dbdir}/local.sqlite "INSERT INTO bhyvedsk ( jname,dsk_controller,dsk_path,dsk_slot  ) VALUES ( \"${jname}\",\"${virtio_type}\",\"${defdsk}\","0" )"
+	else
+		${miscdir}/sqlcli ${dbdir}/local.sqlite "INSERT INTO bhyvedsk ( jname,dsk_path,dsk_slot  ) VALUES ( \"${jname}\",\"${defdsk}\","0" )"
+	fi
 
-    exit 0
+	exit 0
 else
-    ${ECHO}
-    ${ECHO} "${MAGENTA}Creating ${jname} failed: ${GREEN}cbsd jregister${NORMAL}"
-    ${ECHO} "${MAGENTA}Please review bad config file: ${GREEN}/tmp/rc.conf_${jname}${NORMAL}"
-    mv $rcconf /tmp
-    #cleanup
-    [ -f "${mount_fstab}" ] && rm -f ${mount_fstab}
-    removedata ${data}
-    exit 1
+	${ECHO}
+	${ECHO} "${MAGENTA}Creating ${jname} failed: ${GREEN}cbsd jregister${NORMAL}"
+	${ECHO} "${MAGENTA}Please review bad config file: ${GREEN}/tmp/rc.conf_${jname}${NORMAL}"
+	mv $rcconf /tmp
+	#cleanup
+	[ -f "${mount_fstab}" ] && rm -f ${mount_fstab}
+	removedata ${data}
+	exit 1
 fi
diff --git a/tools/repo b/tools/repo
--- a/tools/repo
+++ b/tools/repo
@@ -32,26 +32,26 @@ readconf buildworld.conf
 
 fetchme()
 {
-    cfetch -u $1 -o ${TF}
-    return $?
+	cfetch -u $1 -o ${TF}
+	return $?
 }
 
 checkmd5()
 {
-    local _GOOD _OMD5 _RMD5 _i _FILE
-    DIR=$1
-    _GOOD=0
+	local _GOOD _OMD5 _RMD5 _i _FILE
+	DIR=$1
+	_GOOD=0
 
-    for _i in $( find ${DIR} -type f -depth 1 -name *.md5 -print); do
-	_FILE=$( ${ECHO} ${_i} |sed 's/\.md5//g' )
-	_OMD5=$( cat ${_FILE}.md5 )
-	_RMD5=$( md5 -q ${_FILE} )
-	if [ "${_RMD5}" != "${_OMD5}" ]; then
-	    _GOOD=$((_GOOD + 1))
-	fi
-    done
+	for _i in $( find ${DIR} -type f -depth 1 -name *.md5 -print); do
+		_FILE=$( ${ECHO} ${_i} |sed 's/\.md5//g' )
+		_OMD5=$( cat ${_FILE}.md5 )
+		_RMD5=$( md5 -q ${_FILE} )
+		if [ "${_RMD5}" != "${_OMD5}" ]; then
+			_GOOD=$((_GOOD + 1))
+		fi
+	done
 
-    return ${_GOOD}
+	return ${_GOOD}
 }
 
 
@@ -75,126 +75,126 @@ checkrepo()
 
 getsrc()
 {
-    init_srcdir
+	init_srcdir
 
-    [ -d "${srcdir}/${DIR}" -a $UPGRADE -ne 1 ] && err 1 "You already have ${ver}"
+	[ -d "${srcdir}/${DIR}" -a $UPGRADE -ne 1 ] && err 1 "You already have ${ver}"
 
-    for MYREPO in ${REPO}; do
-	${ECHO} "${MAGENTA}REPO${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
-	MIRROR="${MYREPO}/src_${ver}/mirror.html"
-	cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-	    MYREPO=$( cat ${TF} )
-	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
+	for MYREPO in ${REPO}; do
+		${ECHO} "${MAGENTA}REPO${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
+		MIRROR="${MYREPO}/src_${ver}/mirror.html"
+		cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			MYREPO=$( cat ${TF} )
+			${ECHO} "${MAGENTA}Found new mirror for ${ver}${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
+		fi
+		cfetch -o ${MYDIR}/src.txz -u ${MYREPO}/${DIR}/src.txz
+		[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz${NORMAL}" && icontinue
+		cfetch -o ${MYDIR}/src.txz.md5 -u ${MYREPO}/${DIR}/src.txz.md5 >/dev/null 2>&1
+		[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz.md5${NORMAL}" && continue
+	done
+
+	[ -f "${MYDIR}/src.txz" -a -f "${MYDIR}/src.txz.md5" ] || err 1 "No sources found"
+
+	if checkmd5 ${MYDIR}; then
+		${ECHO} "${MAGENTA}MD5sum correct.${NORMAL}"
+	else
+		err 1 "${MAGENTA}MD5sum incorrect.${NORMAL}"
 	fi
-	cfetch -o ${MYDIR}/src.txz -u ${MYREPO}/${DIR}/src.txz
-	[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz${NORMAL}" && icontinue
-	cfetch -o ${MYDIR}/src.txz.md5 -u ${MYREPO}/${DIR}/src.txz.md5 >/dev/null 2>&1
-	[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz.md5${NORMAL}" && continue
-    done
 
-    [ -f "${MYDIR}/src.txz" -a -f "${MYDIR}/src.txz.md5" ] || err 1 "No sources found"
+	ARCHIVE="${workdir}/tmp/src_${ver}.txz"
+	[ ! -f "${ARCHIVE}" ] || rm -f ${ARCHIVE}
 
-    if checkmd5 ${MYDIR}; then
-	${ECHO} "${MAGENTA}MD5sum correct.${NORMAL}"
-	    else
-	err 1 "${MAGENTA}MD5sum incorrect.${NORMAL}"
-    fi
-
-    ARCHIVE="${workdir}/tmp/src_${ver}.txz"
-    [ ! -f "${ARCHIVE}" ] || rm -f ${ARCHIVE}
-
-    ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
-    cd $workdir/tmp
-    set -e
-    tar xfz ${MYDIR}/src.txz
-    set +e
-    rm -f ${MYDIR}/src.txz
-    mkdir -p ${srcdir}/src_${ver}
-    mv ${workdir}/tmp/src_${ver} ${srcdir}/
-    ${ECHO} "${MAGENTA}Done...${NORMAL}"
-    DT=$( /bin/date "+%Y%m%d" )
+	${ECHO} "${MAGENTA}Extracting...${NORMAL}"
+	cd $workdir/tmp
+	set -e
+	tar xfz ${MYDIR}/src.txz
+	set +e
+	rm -f ${MYDIR}/src.txz
+	mkdir -p ${srcdir}/src_${ver}
+	mv ${workdir}/tmp/src_${ver} ${srcdir}/
+	${ECHO} "${MAGENTA}Done...${NORMAL}"
+	DT=$( /bin/date "+%Y%m%d" )
 }
 
 getbase()
 {
-    local _srcmd5_found _src_found
+	local _srcmd5_found _src_found
 
-    if [ -z "${basename}" ]; then
-	BDIR="${basejailpref}_${arch}_${ver}"
-    else
-	BDIR="${basejailpref}_${basename}_${arch}_${ver}"
-    fi
+	if [ -z "${basename}" ]; then
+		BDIR="${basejailpref}_${arch}_${ver}"
+	else
+		BDIR="${basejailpref}_${basename}_${arch}_${ver}"
+	fi
 
-    MIRROR="http://ftp.freebsd.org"
-    FHIER="${arch}/${target_arch}/${ver}"
-    BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${FHIER}-RELEASE/base.txz"
+	MIRROR="http://ftp.freebsd.org"
+	FHIER="${arch}/${target_arch}/${ver}"
+	BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${FHIER}-RELEASE/base.txz"
 
-    if [ -d "${BASE_DIR}" ]; then
-	[ $UPGRADE -eq 1 ] || err 1 "${MAGENTA}You already have ${ver}. Use mode=upgrade for upgrade${NORMAL}"
-	chflags -R noschg ${BASE_DIR}
-    fi
+	if [ -d "${BASE_DIR}" ]; then
+		[ $UPGRADE -eq 1 ] || err 1 "${MAGENTA}You already have ${ver}. Use mode=upgrade for upgrade${NORMAL}"
+		chflags -R noschg ${BASE_DIR}
+	fi
 
-    if [ "$fbsdrepo" = "1" -a -z "${basename}" ]; then
-	## Official fbsd repo
-	printf "${MAGENTA}Looking for official FreeBSD mirror:${NORMAL}"
-	ARCHIVE="$MYDIR/base.txz"
-	cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
-	if [ $? -eq 0 ]; then
-	    printf "\n${MAGENTA}Extracting base...${NORMAL}\n"
-	    [ ! -d "${BASE_DIR}" ] && mkdir -p $BASE_DIR
-	    cd $BASE_DIR
-	    set -e
-	    tar xfz ${ARCHIVE}
-	    set +e
-	    rm -f ${ARCHIVE}
-	    # fetch lib32 only for amd64
-	    if [ "${arch}" = "amd64" ]; then
-		BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${FHIER}-RELEASE/lib32.txz"
-		ARCHIVE="$MYDIR/lib32.txz"
+	if [ "$fbsdrepo" = "1" -a -z "${basename}" ]; then
+		## Official fbsd repo
+		printf "${MAGENTA}Looking for official FreeBSD mirror:${NORMAL}"
+		ARCHIVE="$MYDIR/base.txz"
 		cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
-		    if [ $? -eq 0 ]; then
-			printf "\n${MAGENTA}Extracting lib32...${NORMAL}\n"
+		if [ $? -eq 0 ]; then
+			printf "\n${MAGENTA}Extracting base...${NORMAL}\n"
+			[ ! -d "${BASE_DIR}" ] && mkdir -p $BASE_DIR
 			cd $BASE_DIR
 			set -e
 			tar xfz ${ARCHIVE}
 			set +e
 			rm -f ${ARCHIVE}
-		    else
-			printf "${GREEN} Lib32 not found${NORMAL}\n"
-		    fi
-	    fi
-	    preparebase dst=${BASE_DIR}
-	    ${ECHO} "${MAGENTA}Done...${NORMAL}"
-	    return 0
+			# fetch lib32 only for amd64
+			if [ "${arch}" = "amd64" ]; then
+				BSDBASE_DISTSITE="$MIRROR/pub/FreeBSD/releases/${FHIER}-RELEASE/lib32.txz"
+				ARCHIVE="$MYDIR/lib32.txz"
+				cfetch -u ${BSDBASE_DISTSITE} -o ${ARCHIVE}
+				if [ $? -eq 0 ]; then
+					printf "\n${MAGENTA}Extracting lib32...${NORMAL}\n"
+					cd $BASE_DIR
+					set -e
+					tar xfz ${ARCHIVE}
+					set +e
+					rm -f ${ARCHIVE}
+				else
+					printf "${GREEN} Lib32 not found${NORMAL}\n"
+				fi
+			fi
+			preparebase dst=${BASE_DIR}
+			${ECHO} "${MAGENTA}Done...${NORMAL}"
+			return 0
+		fi
+		printf "${GREEN} Not found${NORMAL}\n"
+		### Official fbsd repo end ###
 	fi
-    printf "${GREEN} Not found${NORMAL}\n"
-    ### Official fbsd repo end ###
-    fi
 
 #    _srcmd5_found=0
-    _src_found=0
+	_src_found=0
 
-    for MYREPO in $REPO; do
-	${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
-	MIRROR="${MYREPO}/releases/${FHIER}/mirror.html";
-	cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
+	for MYREPO in $REPO; do
+		${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
+		MIRROR="${MYREPO}/releases/${FHIER}/mirror.html";
+		cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
 
-	if [ $? -eq 0 ]; then
-	    MYREPO=$( cat ${TF} )
-	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
-	fi
+		if [ $? -eq 0 ]; then
+			MYREPO=$( cat ${TF} )
+			${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
+		fi
 
-	if [ -z "${basename}" ]; then
-	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/base.txz${NORMAL}"
-	    cfetch -o ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/base.txz
+		if [ -z "${basename}" ]; then
+			${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/base.txz${NORMAL}"
+			cfetch -o ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/base.txz
 
-	    if [ $? -ne 0 ]; then
-		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${FHIER}/base.txz${NORMAL}"
-		continue
-	    else
-		_src_found=1
-	    fi
+		if [ $? -ne 0 ]; then
+			${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${FHIER}/base.txz${NORMAL}"
+			continue
+		else
+			_src_found=1
+		fi
 
 #	    cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
 
@@ -204,16 +204,16 @@ getbase()
 #	    else
 		_srcmd5_found=1
 #	    fi
-	else
-	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/base_${basename}.txz${NORMAL}"
-	    cfetch -o ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/base_${basename}.txz
-
-	    if [ $? -ne 0 ]; then
-		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${FHIER}/base_${basename}.txz${NORMAL}"
-		continue
 	    else
-		_src_found=1
-	    fi
+		${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${FHIER}/base_${basename}.txz${NORMAL}"
+		cfetch -o ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${FHIER}/base_${basename}.txz
+
+		if [ $? -ne 0 ]; then
+			${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${FHIER}/base_${basename}.txz${NORMAL}"
+			continue
+		else
+			_src_found=1
+		fi
 
 #	    cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
 
@@ -223,10 +223,10 @@ getbase()
 #	    else
 		_srcmd5_found=1
 #	    fi
-	fi
+		fi
 
-	[ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
-    done
+		[ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
+	done
 
 #    if checkmd5 ${MYDIR}; then
 #	${ECHO} "${MAGENTA}MD5 sum:${GREEN} correct${NORMAL}"
@@ -240,101 +240,100 @@ getbase()
 #	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
 #    fi
 
-    [ ${_src_found} -ne 1 ] && err 1 "${MAGENTA}Not found data${NORMAL}"
+	[ ${_src_found} -ne 1 ] && err 1 "${MAGENTA}Not found data${NORMAL}"
 
-    ${ECHO} "${MAGENTA}Extracting...${NORMAL}"
-    [ ! -d "${BASE_DIR}" ] && mkdir -p ${BASE_DIR}
-    #/base_${arch}_${ver}
-    cd $BASE_DIR
-    #/base_${arch}_${ver}
+	${ECHO} "${MAGENTA}Extracting...${NORMAL}"
+	[ ! -d "${BASE_DIR}" ] && mkdir -p ${BASE_DIR}
+	#/base_${arch}_${ver}
+	cd $BASE_DIR
+	#/base_${arch}_${ver}
 
-    if [ -z "${basename}" ]; then
-	set -e
-	tar xfz ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz
-	set +e
-#	rm -f ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz.md5
-    else
-	set -e
-	tar xfz ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz
-	set +e
-#	rm -f ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz.md5
-    fi
+	if [ -z "${basename}" ]; then
+		set -e
+		tar xfz ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz
+		set +e
+#		rm -f ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz.md5
+	else
+		set -e
+		tar xfz ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz
+		set +e
+#		rm -f ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz.md5
+	fi
 
-    ${ECHO} "${MAGENTA}Done...${NORMAL}"
+	${ECHO} "${MAGENTA}Done...${NORMAL}"
 
-return 0
+	return 0
 }
 
 
 getobj()
 {
-    if [ -z "${basename}" ]; then
-	DST="${srcdir}/obj_${arch}_${ver}"
-    else
-	DST="${srcdir}/obj_${basename}_${arch}_${ver}"
-    fi
-
-    for MYREPO in ${REPO}; do
-	${ECHO} "${MAGENTA}REPO:${GREEN}${MYREPO}${NORMAL}"
 	if [ -z "${basename}" ]; then
-    	    MIRROR="${MYREPO}/obj_${arch}_${ver}/mirror.html";
+		DST="${srcdir}/obj_${arch}_${ver}"
 	else
-	    MIRROR="${MYREPO}/obj_${basename}_${arch}_${ver}/mirror.html";
+		DST="${srcdir}/obj_${basename}_${arch}_${ver}"
 	fi
 
-	if [ -d "${DST}" ]; then
-	    [ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
-	    removeobj ver=${ver} arch=${arch}
-	fi
+	for MYREPO in ${REPO}; do
+		${ECHO} "${MAGENTA}REPO:${GREEN}${MYREPO}${NORMAL}"
+		if [ -z "${basename}" ]; then
+			MIRROR="${MYREPO}/obj_${arch}_${ver}/mirror.html";
+		else
+			MIRROR="${MYREPO}/obj_${basename}_${arch}_${ver}/mirror.html";
+		fi
 
-	cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
+		if [ -d "${DST}" ]; then
+			[ $UPGRADE -eq 1 ] || err 1 "You already have ${ver}"
+			removeobj ver=${ver} arch=${arch}
+		fi
 
-	if [ $? -eq 0 ]; then
-	    MYREPO=$( cat ${TF} )
-	    ${ECHO} "Found new mirror for ${basename}: ${MYREPO}"
-	fi
+		cfetch -u ${MIRROR} -o ${TF} > /dev/null 2>&1
+
+		if [ $? -eq 0 ]; then
+			MYREPO=$( cat ${TF} )
+			${ECHO} "Found new mirror for ${basename}: ${MYREPO}"
+		fi
+
+		if [ -z "${basename}" ]; then
+			cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/obj_${arch}_${ver}.txz
+			[ $? -eq 0 ] || continue
+			cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/obj_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+			[ $? -eq 0 ] || continue
+		else
+			cfetch -o ${MYDIR}/obj_${basename}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/obj_${basename}_${arch}_${ver}.txz
+			[ $? -eq 0 ] || continue
+			cfetch -o ${MYDIR}/obj_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/obj_${basename}_${arch}_${ver}.md5 >/dev/null 2>&1
+			[ $? -eq 0 ] || continue
+		fi
+	done
 
 	if [ -z "${basename}" ]; then
-	    cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/obj_${arch}_${ver}.txz
-	    [ $? -eq 0 ] || continue
-	    cfetch -o ${MYDIR}/obj_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/obj_${arch}_${ver}.txz.md5 >/dev/null 2>&1
-	    [ $? -eq 0 ] || continue
+		[ -f "${MYDIR}/obj_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/obj_${arch}_${ver}.txz" ] || err 1 "No sources found"
 	else
-	    cfetch -o ${MYDIR}/obj_${basename}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/obj_${basename}_${arch}_${ver}.txz
-	    [ $? -eq 0 ] || continue
-	    cfetch -o ${MYDIR}/obj_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/obj_${basename}_${arch}_${ver}.md5 >/dev/null 2>&1
-	    [ $? -eq 0 ] || continue
+		[ -f "${MYDIR}/obj_${basename}_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/obj_${basename}_${arch}_${ver}.txz" ] || err 1 "No sources found"
 	fi
-    done
 
-    if [ -z "${basename}" ]; then
-	[ -f "${MYDIR}/obj_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/obj_${arch}_${ver}.txz" ] || err 1 "No sources found"
-    else
-	[ -f "${MYDIR}/obj_${basename}_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/obj_${basename}_${arch}_${ver}.txz" ] || err 1 "No sources found"
-    fi
+	if checkmd5 ${MYDIR}; then
+		${ECHO} "MD5sum correct."
+	else
+		err 1 "MD5sum incorrect."
+	fi
 
-    if checkmd5 ${MYDIR}; then
-	${ECHO} "MD5sum correct."
-    else
-	err 1 "MD5sum incorrect."
-    exit
-    fi
+	rm -f ${MYDIR}/obj_${arch}_${ver}.txz.md5
 
-    rm -f ${MYDIR}/obj_${arch}_${ver}.txz.md5
-
-    ${ECHO} "Extracting..."
-    cd $srcdir
-    set -e
-    tar xfz ${MYDIR}/obj_${arch}_${ver}.txz
-    set +e
-    rm -f ${MYDIR}/obj_${arch}_${ver}.txz
-    ${ECHO} "Done..."
+	${ECHO} "Extracting..."
+	cd $srcdir
+	set -e
+	tar xfz ${MYDIR}/obj_${arch}_${ver}.txz
+	set +e
+	rm -f ${MYDIR}/obj_${arch}_${ver}.txz
+	${ECHO} "Done..."
 }
 
 
 getkernel()
 {
-    local name KERNNAME
+	local name KERNNAME
 
 #    [ -z "${name}" ] && name="GENERIC"
 #    KERNNAME="_${name}_"
@@ -592,6 +591,9 @@ done
 	;;
     "helpers")
 	gethelpers
+	;;
+    *)
+	err 1 "${MAGENTA}Unknown sources: ${GREEN}${sources}${NORMAL}"
 	;;
     esac ## END of source case
 esac ## END of action case
