Update UEFI-CSM firmware
This should fix boot Linux kernels >= 4.15
- More logging;

diff --git a/jailctl/bcreate b/jailctl/bcreate
--- a/jailctl/bcreate
+++ b/jailctl/bcreate
@@ -72,7 +72,7 @@ really_create_vm()
 			1)
 				;;
 			*)
-				force switch imgtype to md when no zfsfeat
+				# force switch imgtype to md when no zfsfeat
 				imgtype="md"
 	esac
 
@@ -103,14 +103,14 @@ really_create_vm()
 		_res=$?
 		if [ ${_res} -ne 0 ]; then
 			bremove ${jname}
-			err 1 "bcreate error: Couldn't create the image file. ${_msg}"
+			log_err 1 "bcreate error: Couldn't create the image file. ${_msg}"
 		fi
 	fi
 }
 
 
 ### MAIN
-[ ! -f "${jconf}" ] && err 1 "${MAGENTA}no such jconf file${NORMAL}";
+[ ! -f "${jconf}" ] && log_err 1 "${MAGENTA}no such jconf file${NORMAL}";
 st_time=$( /bin/date +%s )
 over="${ver}"
 oarch="${arch}"
@@ -131,7 +131,7 @@ temprcconf="${ftmpdir}/jcreate_jconf.$$"
 . ${temprcconf}
 
 # profile
-[ -z "${vm_os_profile}" ] && err 1 "${MAGENTA}No such profile: ${GREEN}vm-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+[ -z "${vm_os_profile}" ] && log_err 1 "${MAGENTA}No such profile: ${GREEN}vm-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
 
 template_profile=
 
@@ -163,7 +163,7 @@ else
 	trap "/bin/rm -f ${temprcconf}" HUP INT ABRT BUS TERM  EXIT
 fi
 
-[ -z "${jname}" ] && err 1 "${MAGENTA}No such jname variable${NORMAL}"
+[ -z "${jname}" ] && log_err 1 "${MAGENTA}No such jname variable${NORMAL}"
 
 if [ "${vm_os_type}" = "freebsd" -a "${from_jail}" = "1" ]; then
 	# change emulator type for jcreate
@@ -190,7 +190,7 @@ fi
 [ -n "${tpl_pkglist}" ] && ${SYSRC_CMD} -qf ${jconf} pkglist="${tpl_pkglist}" > /dev/null 2>&1
 
 jstatus jname=${jname} > /dev/null 2>&1
-[ $? -eq 0 ] || err 1 "${MAGENTA}Jail with $jname already exist${NORMAL}"
+[ $? -eq 0 ] || log_err 1 "${MAGENTA}Jail with ${jname} already exist${NORMAL}"
 
 # CBSD QUEUE
 if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
@@ -203,14 +203,14 @@ if [ -n "${interface}" -a "${inteface}" != "0" ]; then
 	checkip ip=${ips} check=1 > /dev/null 2>&1
 	case $? in
 		0)
-			err 1 "${MAGENTA}Ip not in pool range${NORMAL}"
+			log_err 1 "${MAGENTA}Ip not in pool range${NORMAL}"
 			;;
 		1)	;;
 		2)
 			${ECHO} "${MAGENTA}Warning:${GREEN} Ip already exists in LAN${NORMAL}"
 			;;
 		*)
-			err 1 "Unknown code from checkip"
+			log_err 1 "Unknown code from checkip"
 			;;
 	esac
 fi
@@ -230,7 +230,7 @@ else
 	create_fs ${data}
 fi
 
-[ ! -d "${data}" ] && err 1 "Can't create datadir ${data}"
+[ ! -d "${data}" ] && log_err 1 "Can't create datadir ${data}"
 [ ! -d ${path} -a "${baserw}" -eq 0 ] && /bin/mkdir -p ${path}
 [ ! -d ${jailfstabdir}  ] && /bin/mkdir -p ${jailfstabdir}
 [ ! -d "${jailsysdir}/${jname}" ] && /bin/mkdir -p ${jailsysdir}/${jname}
@@ -293,7 +293,7 @@ if is_number ${vm_ram}; then
 	if conv2bytes "${vm_ram}"; then
 		vm_ram="${convval}"
 	else
-		err 1 "${vm_ram} is not number and we can't convert int via conv2bytes"
+		log_err 1 "${vm_ram} is not number and we can't convert int via conv2bytes"
 	fi
 fi
 
diff --git a/jailctl/jailscp b/jailctl/jailscp
--- a/jailctl/jailscp
+++ b/jailctl/jailscp
@@ -24,7 +24,7 @@ getjname()
 {
 	local _t
 
-	_t=$(echo ${1} |grep ":")
+	_t=$( echo ${1} | /usr/bin/grep ":")
 
 	[ $? -ne 0 ] && return 1
 
@@ -36,16 +36,17 @@ try_remote()
 {
 	# this is only wrapper for compile correct arguments for cbsd nodescp
 
-	node=$( jwhereis $jname )
+	node=$( jwhereis ${jname} )
 
-	[ -z "${node}" ] && err 1 "Node not found for jail $jname"
+	[ -z "${node}" ] && log_err 1 "Node not found for jail ${jname}"
 
-	status=$( rexe node=$node cbsd jstatus $jname )
-	[ "${status}" = "0" ] && err 1 "Jail not running"
+	cbsdlogger NOTICE ${CBSD_APP}: try to get remote jstatus for ${jname} on ${node}
+	status=$( rexe node=${node} cbsd jstatus ${jname} )
+	[ "${status}" = "0" ] && log_err 1 "jail ${jname} not running on ${node}"
 	sqlfile="${node}"
 	. ${jrcconf}
 	[ "${baserw}" = "1" ] && path=${data}
-	[ -z "${path}" ] && err 1 "path not found"
+	[ -z "${path}" ] && log_err 1 "path not found"
 }
 
 
@@ -69,7 +70,7 @@ rarg=0
 
 if getjname $1; then
 	if getjname $2; then
-		err 1 "${MAGENTA}Only one remote path${NORMAL}"
+		log_err 1 "${MAGENTA}Only one remote path${NORMAL}"
 	fi
 	rarg=1
 else
@@ -78,59 +79,66 @@ else
 	fi
 fi
 
-[ -z "${jname}" -o -z "${rfile}" ] && err 1 "${MAGENTA}jail path via jail:path records not determine${NORMAL}"
+[ -z "${jname}" -o -z "${rfile}" ] && log_err 1 "${MAGENTA}jail path via jail:path records not determine${NORMAL}"
 
 validate_jname ${jname}
-[ $? -ne 1 ] && err 1 "${MAGENTA}Bad jname${NORMAL}"
+[ $? -ne 1 ] && log_err 1 "${MAGENTA}Bad jname: ${jname}${NORMAL}"
 
-RSYNC=$(which rsync)
+RSYNC=$( which rsync )
+
 . ${jrcconf}
 if [ $? -eq 1 ]; then
 	try_remote
 
-	if [ $rarg -eq 1 ]; then
+	if [ ${rarg} -eq 1 ]; then
+		cbsdlogger NOTICE ${CBSD_APP}: nodescp for ${2} from ${node}:${path}${rfile}
 		nodescp root=1 ${node}:${path}${rfile} ${2}
 		err=$?
 	else
+		cbsdlogger NOTICE ${CBSD_APP}: nodescp for ${1} to ${node}:${path}${rfile}
 		nodescp root=1 $1 ${node}:${path}${rfile}
 		err=$?
 	fi
 	exit $err
 fi
 
-[ $jid -eq 0 ] && err 1 "${MAGENTA}Jail not active${NORMAL}"
+[ ${jid} -eq 0 ] && log_err 1 "${MAGENTA}jail not active: ${jname}${NORMAL}"
 
-[ $baserw -eq 1 ] && path="${data}"
+[ ${baserw} -eq 1 ] && path="${data}"
 
-if [ $rarg -eq 1 ]; then
-	DIR=$(dirname ${2})
-	[ ! -d "${DIR}" ] && mkdir -p ${DIR}
+if [ ${rarg} -eq 1 ]; then
+	DIR=$( dirname ${2} )
+	[ ! -d "${DIR}" ] && /bin/mkdir -p ${DIR}
 
 	if [ -n "${RSYNC}" ]; then
 		#we have rsync for that
 		[ ${verbose} -eq 1 ] && set -o xtrace
+		cbsdlogger NOTICE ${CBSD_APP}: rsync ${path}${rfile} ${2}
 		${RSYNC} -azzlH ${path}${rfile} ${2}
 		[ ${verbose} -eq 1 ] && set +o xtrace
 	else
 		#no rsync, just scp
 		[ ${verbose} -eq 1 ] && set -o xtrace
-		cp -a ${path}${rfile} ${2}
+		cbsdlogger NOTICE ${CBSD_APP}: cp for ${path}${rfile} to ${2}
+		/bin/cp -a ${path}${rfile} ${2}
 		[ ${verbose} -eq 1 ] && set +o xtrace
 	fi
 else
-	DIR=$(dirname ${path}${rfile})
+	DIR=$( dirname ${path}${rfile} )
 	[ ${verbose} -eq 1 ] && set -o xtrace
-	[ ! -d "${DIR}" ] && mkdir -p "${DIR}"
+	[ ! -d "${DIR}" ] && /bin/mkdir -p "${DIR}"
 	[ ${verbose} -eq 1 ] && set +o xtrace
 	if [ -n "${RSYNC}" ]; then
 		#we have rsync for that
 		[ ${verbose} -eq 1 ] && set -o xtrace
+		cbsdlogger NOTICE ${CBSD_APP}: rsync for ${1} to ${path}${rfile}
 		${RSYNC} -azzlH ${1} ${path}${rfile}
 		[ ${verbose} -eq 1 ] && set +o xtrace
 	else
 		#no rsync, just scp
 		[ ${verbose} -eq 1 ] && set -o xtrace
-		cp -a ${1} ${path}${rfile}
+		cbsdlogger NOTICE ${CBSD_APP}: cp for ${1} to ${path}${rfile}
+		/bin/cp -a ${1} ${path}${rfile}
 		[ ${verbose} -eq 1 ] && set +o xtrace
 	fi
 fi
