ability to customize colors
~cbsd/etc/colors.conf - for those who are tired of magenta and green

diff --git a/jailctl/bcreate b/jailctl/bcreate
--- a/jailctl/bcreate
+++ b/jailctl/bcreate
@@ -46,7 +46,7 @@ if [ -z "${jconf}" ]; then
 	unset CBSD_INIT_SAVE2FILE
 fi
 
-[ -z "${jconf}" -a -z "${jname}" ] && err 1 "${MAGENTA}Please set for bcreate: ${GREEN}${jconf}${NORMAL}"
+[ -z "${jconf}" -a -z "${jname}" ] && err 1 "${N1_COLOR}Please set for bcreate: ${N2_COLOR}${jconf}${N0_COLOR}"
 [ -n "${removejconf}" ] && oremovejconf="${removejconf}"
 
 really_create_base()
@@ -67,7 +67,7 @@ really_create_base()
 				init_kerneldir
 				get_base -v ${ver}
 				get_kernel
-				${ECHO} "${MAGENTA}Stage1: ${GREEN}jcreate...${NORMAL}"
+				${ECHO} "${N1_COLOR}Stage1: ${N2_COLOR}jcreate...${N0_COLOR}"
 				echo "jcreate jconf=${temprcconf} pkg_bootstrap=0"
 				jcreate jconf=${temprcconf} pkg_bootstrap=0
 
@@ -93,7 +93,7 @@ really_create_vm()
 	esac
 
 	if [ "${from_jail}" ]; then
-		${ECHO} "${MAGENTA}Stage2: ${GREEN}jail2iso...${NORMAL}"
+		${ECHO} "${N1_COLOR}Stage2: ${N2_COLOR}jail2iso...${N0_COLOR}"
 		[ -z "${swapsize}" ] && swapsize="0"
 
 		mountbase -o "" -p "" -d "" -c "" -s ""
@@ -126,7 +126,7 @@ really_create_vm()
 
 
 ### MAIN
-[ ! -f "${jconf}" ] && log_err 1 "${MAGENTA}no such jconf file${NORMAL}";
+[ ! -f "${jconf}" ] && log_err 1 "${N1_COLOR}no such jconf file${N0_COLOR}";
 st_time=$( /bin/date +%s )
 over="${ver}"
 oarch="${arch}"
@@ -186,7 +186,7 @@ done
 . ${temprcconf}
 
 # profile
-[ -z "${vm_os_profile}" ] && log_err 1 "${MAGENTA}No such vm profile: ${GREEN}vm-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+[ -z "${vm_os_profile}" ] && log_err 1 "${N1_COLOR}No such vm profile: ${N2_COLOR}vm-${vm_os_type}-${vm_os_profile}.conf${N0_COLOR}"
 
 template_profile=
 
@@ -226,7 +226,7 @@ else
 	trap "/bin/rm -f ${temprcconf} ${jconf_tmp}" HUP INT ABRT BUS TERM  EXIT
 fi
 
-[ -z "${jname}" ] && log_err 1 "${MAGENTA}No such jname variable${NORMAL}"
+[ -z "${jname}" ] && log_err 1 "${N1_COLOR}No such jname variable${N0_COLOR}"
 
 if [ "${vm_os_type}" = "freebsd" -a "${from_jail}" = "1" ]; then
 	# change emulator type for jcreate
@@ -235,10 +235,10 @@ if [ "${vm_os_type}" = "freebsd" -a "${from_jail}" = "1" ]; then
 	if [ -n "${jprofile}" ]; then
 		. ${settingstui}
 		if [ -r "${etcdir}/jail-freebsd-${jprofile}.conf" ]; then
-			${ECHO} "${MAGENTA}Use profile: ${GREEN}${etcdir}/jail-freebsd-${jprofile}.conf${NORMAL}"
+			${ECHO} "${N1_COLOR}Use profile: ${N2_COLOR}${etcdir}/jail-freebsd-${jprofile}.conf${N0_COLOR}"
 			merge_apply_profiles ${etcdir}/jail-freebsd-${jprofile}.conf ${jconf_tmp}
 		elif [ -r "${etcdir}/defaults/jail-freebsd-${jprofile}.conf" ]; then
-			${ECHO} "${MAGENTA}Use profile: ${GREEN}${etcdir}/defaults/jail-freebsd-${jprofile}.conf${NORMAL}"
+			${ECHO} "${N1_COLOR}Use profile: ${N2_COLOR}${etcdir}/defaults/jail-freebsd-${jprofile}.conf${N0_COLOR}"
 			merge_apply_profiles ${etcdir}/defaults/jail-freebsd-${jprofile}.conf ${jconf_tmp}
 		fi
 	fi
@@ -277,7 +277,7 @@ fi
 [ -n "${tpl_pkglist}" ] && ${SYSRC_CMD} -qf ${jconf_tmp} pkglist="${tpl_pkglist}" > /dev/null 2>&1
 
 jstatus jname=${jname} > /dev/null 2>&1
-[ $? -eq 0 ] || log_err 1 "${MAGENTA}Jail with ${jname} already exist${NORMAL}"
+[ $? -eq 0 ] || log_err 1 "${N1_COLOR}Jail with ${jname} already exist${N0_COLOR}"
 
 # CBSD QUEUE
 if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
@@ -290,11 +290,11 @@ if [ -n "${interface}" -a "${inteface}" != "0" ]; then
 	checkip ip=${ips} check=1 > /dev/null 2>&1
 	case $? in
 		0)
-			log_err 1 "${MAGENTA}Ip not in pool range${NORMAL}"
+			log_err 1 "${N1_COLOR}Ip not in pool range${N0_COLOR}"
 			;;
 		1)	;;
 		2)
-			${ECHO} "${MAGENTA}Warning:${GREEN} Ip already exists in LAN${NORMAL}"
+			${ECHO} "${N1_COLOR}Warning:${N2_COLOR} Ip already exists in LAN${N0_COLOR}"
 			;;
 		*)
 			log_err 1 "Unknown code from checkip"
@@ -341,8 +341,8 @@ _res=$?
 
 if [ ${_res} -ne 0 ]; then
 	${ECHO}
-	${ECHO} "${MAGENTA}Creating ${jname} failed: ${GREEN}cbsd jregister${NORMAL}"
-	${ECHO} "${MAGENTA}Please review bad config file: ${GREEN}/tmp/rc.conf_${jname}${NORMAL}"
+	${ECHO} "${N1_COLOR}Creating ${jname} failed: ${N2_COLOR}cbsd jregister${N0_COLOR}"
+	${ECHO} "${N1_COLOR}Please review bad config file: ${N2_COLOR}/tmp/rc.conf_${jname}${N0_COLOR}"
 	/bin/mv ${rcconf} /tmp
 	#cleanup
 	[ -f "${mount_fstab}" ] && /bin/rm -f ${mount_fstab}
@@ -352,13 +352,13 @@ fi
 
 
 echo
-${ECHO} "${MAGENTA}To edit VM properties use: ${GREEN}cbsd bconfig jname=${jname}${NORMAL}"
-${ECHO} "${MAGENTA}To start VM use: ${GREEN}cbsd bstart ${jname}${NORMAL}"
-${ECHO} "${MAGENTA}To stop VM use: ${GREEN}cbsd bstop ${jname}${NORMAL}"
-${ECHO} "${MAGENTA}To remove VM use: ${GREEN}cbsd bremove ${jname}${NORMAL}"
-${ECHO} "${MAGENTA}For attach VM console use: ${GREEN}cbsd blogin ${jname}${NORMAL}"
+${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd bconfig jname=${jname}${N0_COLOR}"
+${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd bstart ${jname}${N0_COLOR}"
+${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd bstop ${jname}${N0_COLOR}"
+${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd bremove ${jname}${N0_COLOR}"
+${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd blogin ${jname}${N0_COLOR}"
 echo
-${ECHO} "${MAGENTA}Creating ${jname} complete: ${GREEN}Enjoy!${NORMAL}"
+${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
 
 /bin/rm -f ${rcconf}
 
@@ -421,7 +421,7 @@ for i in ${system_dir}; do
 		if [ -d ${systemskeldir}/${i} ]; then
 			/bin/cp -a ${systemskeldir}/${i} ${jailsysdir}/${jname}/${i}
 		else
-			${ECHO} "${MAGENTA}bcreate: warning: no such dir: ${GREEN}${systemskeldir}/${i}${NORMAL}"
+			${ECHO} "${N1_COLOR}bcreate: warning: no such dir: ${N2_COLOR}${systemskeldir}/${i}${N0_COLOR}"
 			continue
 		fi
 	else
@@ -432,7 +432,7 @@ done
 
 # is cloud-init-based ?
 if [ ${is_cloud} -eq 1 ]; then
-	${ECHO} "${MAGENTA}auto-generate cloud-init settings: ${GREEN}${jailsysdir}/${jname}/cloud-init${NORMAL}"
+	${ECHO} "${N1_COLOR}auto-generate cloud-init settings: ${N2_COLOR}${jailsysdir}/${jname}/cloud-init${N0_COLOR}"
 	# auto adjust some missed settings
 
 	[ -z "${ci_jname}" ] && /usr/sbin/sysrc -qf ${jailsysdir}/${jname}/rc.conf_${jname} ci_jname="${jname}" > /dev/null 2>&1
diff --git a/jailctl/jclone b/jailctl/jclone
--- a/jailctl/jclone
+++ b/jailctl/jclone
@@ -25,16 +25,16 @@ readconf jclone.conf		# read users promote and clone_method settings
 [ -z "${clone_method}" ] && clone_method="auto"
 
 myjid=$( cbsdsqlro local SELECT jid FROM jails WHERE jname=\"${old}\" 2>/dev/null )
-[ -z "${myjid}" ] && err 1 "${MAGENTA}No such jail: ${GREEN}${old}${NORMAL}"
+[ -z "${myjid}" ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${old}${N0_COLOR}"
 
 [ -z "${cbsd_queue_name}" ] && cbsd_queue_name="/clonos/jailscontainers/"
 
 if [ ${checkstate} -eq 1 ]; then
-	[ $myjid -ne 0 ] && err 1 "${MAGENTA}Jail is online. Please stop them: ${GREEN}${old}${NORMAL}"
+	[ $myjid -ne 0 ] && err 1 "${N1_COLOR}Jail is online. Please stop them: ${N2_COLOR}${old}${N0_COLOR}"
 fi
 
 myjid=$( cbsdsqlro local SELECT jid FROM jails WHERE jname=\"${new}\" 2>/dev/null )
-[ -n "${myjid}" ] && err 1 "${MAGENTA}Jail already exist: ${GREEN}${new}${NORMAL}"
+[ -n "${myjid}" ] && err 1 "${N1_COLOR}Jail already exist: ${N2_COLOR}${new}${N0_COLOR}"
 
 jname="${old}"
 
@@ -48,14 +48,14 @@ fi
 case "${ip4_addr}" in
 	[Dd][Hh][Cc][Pp])
 		dhcpip=$( dhcpd )
-		[ $? -eq 2 ] && err 1 "${MAGENTA}No free IP address for DHCP in nodeippool${NORMAL}"
-		[ -z "${dhcpip}" ] && err 1 "${MAGENTA}Unable to dhcpd${NORMAL}"
+		[ $? -eq 2 ] && err 1 "${N1_COLOR}No free IP address for DHCP in nodeippool${N0_COLOR}"
+		[ -z "${dhcpip}" ] && err 1 "${N1_COLOR}Unable to dhcpd${N0_COLOR}"
 		ipwmask ${dhcpip}
-		[ -z "${IWM}" ] && err 1 "${MAGENTA}Unable IWM for dhcpd${NORMAL}"
+		[ -z "${IWM}" ] && err 1 "${N1_COLOR}Unable IWM for dhcpd${N0_COLOR}"
 		iptype ${IWM}
-		[ $? -eq 0 ] && err 1 "${MAGENTA}Not ip from dhcpd?: ${dhcpip} / ${IWM}"
+		[ $? -eq 0 ] && err 1 "${N1_COLOR}Not ip from dhcpd?: ${dhcpip} / ${IWM}"
 		ip4_addr="${dhcpip}"
-		${ECHO} "${MAGENTA}Selected IP: ${GREEN}${ip4_addr}${NORMAL}"
+		${ECHO} "${N1_COLOR}Selected IP: ${N2_COLOR}${ip4_addr}${N0_COLOR}"
 		if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
 			[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} id="${new}" cmd=update ip4_addr="${ip4_addr}" status=1
 		fi
@@ -72,7 +72,7 @@ ip4_addr_new="${ip4_addr}"
 host_hostname_new="${host_hostname}"
 
 . ${jrcconf}
-[ "${emulator}" = "bhyve" ] && err 1 "${MAGENTA}Jail in bhyve mode. Use ${GREEN}cbsd brename${MAGENTA} instead${NORMAL}"
+[ "${emulator}" = "bhyve" ] && err 1 "${N1_COLOR}Jail in bhyve mode. Use ${N2_COLOR}cbsd brename${N1_COLOR} instead${N0_COLOR}"
 
 DST="${jaildatadir}/${new}-${jaildatapref}"
 SRC="${jaildatadir}/${old}-${jaildatapref}"
@@ -95,7 +95,7 @@ case ${zfsfeat} in
 	;;
 esac
 
-[ ! -d "${SRC}" ] && err 1 "${MAGENTA}No jail data: ${GREEN}${SRC}${NORMAL}"
+[ ! -d "${SRC}" ] && err 1 "${N1_COLOR}No jail data: ${N2_COLOR}${SRC}${N0_COLOR}"
 
 if [ -d "${DST}" ]; then
 	/bin/rmdir ${DST} >/dev/null 2>&1
@@ -105,14 +105,14 @@ if [ -d "${DST}" ]; then
 		[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} id="${new}" cmd=jclone status=2 data_status=0
 	fi
 
-	[ -d "${DST}" ] && err 1 "${MAGENTA}Jail data already exist and it not empty: ${GREEN}${DST}${NORMAL}"
+	[ -d "${DST}" ] && err 1 "${N1_COLOR}Jail data already exist and it not empty: ${N2_COLOR}${DST}${N0_COLOR}"
 fi
 
 for i in ${JAILDIR} ${jailfstab} ${jailrcconf}; do
 	[ ! -d "${i}" ] && /bin/mkdir -p ${i}
 done
 
-printf "${MAGENTA}Cloning.${NORMAL}"
+printf "${N1_COLOR}Cloning.${N0_COLOR}"
 jmkrcconf jname=${old} > ${JAILRCCONF}
 
 ${SYSRC_CMD} -qf ${JAILRCCONF} jname="${new}" > /dev/null 2>&1
@@ -172,4 +172,4 @@ if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
 	[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} id="${new}" cmd=jclone status=2 data_status=0
 fi
 
-err 0 "${GREEN}ok${NORMAL}"
+err 0 "${N2_COLOR}ok${N0_COLOR}"
diff --git a/jailctl/jcreate b/jailctl/jcreate
--- a/jailctl/jcreate
+++ b/jailctl/jcreate
@@ -50,7 +50,7 @@ install_and_apply_helpers()
 
 	local module=$( cbsdsqlro ${_srcfile} SELECT helpername FROM system |/usr/bin/awk '{printf $1}' )
 
-	${ECHO} "${MAGENTA}Install and apply helpers ${_srcfile}: ${GREEN}${module}${NORMAL}"
+	${ECHO} "${N1_COLOR}Install and apply helpers ${_srcfile}: ${N2_COLOR}${module}${N0_COLOR}"
 
 	local helperdir="${jailsysdir}/${jname}/helpers"
 
@@ -80,7 +80,7 @@ readconf jail-freebsd-default.conf
 . ${distdir}/universe.subr
 . ${distdir}/freebsd_world.subr
 
-[ ! -f "${jconf}" ] && err 1 "${MAGENTA}no such jconf file${NORMAL}";
+[ ! -f "${jconf}" ] && err 1 "${N1_COLOR}no such jconf file${N0_COLOR}";
 
 jconf=$( /bin/realpath ${jconf} )
 
@@ -126,10 +126,10 @@ readconf jail-freebsd-default.conf
 
 if [ -n "${jprofile}" ]; then
 	if [ -r "${etcdir}/jail-freebsd-${jprofile}.conf" ]; then
-		${ECHO} "${MAGENTA}Use profile: ${GREEN}${etcdir}/jail-freebsd-${jprofile}.conf${NORMAL}"
+		${ECHO} "${N1_COLOR}Use profile: ${N2_COLOR}${etcdir}/jail-freebsd-${jprofile}.conf${N0_COLOR}"
 		/bin/cat ${etcdir}/jail-freebsd-${jprofile}.conf >> ${temprcconf}
 	elif [ -r "${etcdir}/defaults/jail-freebsd-${jprofile}.conf" ]; then
-		${ECHO} "${MAGENTA}Use profile: ${GREEN}${etcdir}/defaults/jail-freebsd-${jprofile}.conf${NORMAL}"
+		${ECHO} "${N1_COLOR}Use profile: ${N2_COLOR}${etcdir}/defaults/jail-freebsd-${jprofile}.conf${N0_COLOR}"
 		/bin/cat ${etcdir}/defaults/jail-freebsd-${jprofile}.conf >> ${temprcconf}
 	fi
 
@@ -145,7 +145,7 @@ fi
 
 . ${buildconf}
 
-[ -z "${jname}" ] && err 1 "${MAGENTA}No such jname variable${NORMAL}"
+[ -z "${jname}" ] && err 1 "${N1_COLOR}No such jname variable${N0_COLOR}"
 
 init_jail_path
 init_target_arch
@@ -155,7 +155,7 @@ init_kerneldir
 jstatus jname=${jname} > /dev/null 2>&1
 
 if [ $? -ne 0 ]; then
-	[ ${autorestart} -eq 0 ] && err 1 "${MAGENTA}Jail with ${jname} already exist. Use autorestart=1 for updating via jset${NORMAL}"
+	[ ${autorestart} -eq 0 ] && err 1 "${N1_COLOR}Jail with ${jname} already exist. Use autorestart=1 for updating via jset${N0_COLOR}"
 	jset jname=${jname} jconf=${jconf} autorestart=1
 
 	# CBSD QUEUE
@@ -175,7 +175,7 @@ esac
 
 get_base -v ${ver}
 
-${ECHO} "${MAGENTA}Please wait: ${GREEN}this will take a while...${NORMAL}"
+${ECHO} "${N1_COLOR}Please wait: ${N2_COLOR}this will take a while...${N0_COLOR}"
 
 [ -d "${data}" ] && removedata ${data}
 [ ! -d ${path} -a "${baserw}" -eq 0 ] && /bin/mkdir -p ${path}
@@ -184,7 +184,7 @@ ${ECHO} "${MAGENTA}Please wait: ${GREEN}this will take a while...${NORMAL}"
 
 if [ -d "${jailsysskeldir}" ]; then
 	# we have custom skeldir. copy
-	${ECHO} "${MAGENTA}Applying custom skel system dir template from: ${GREEN}${jailsysskeldir}${MAGENTA}"
+	${ECHO} "${N1_COLOR}Applying custom skel system dir template from: ${N2_COLOR}${jailsysskeldir}${N1_COLOR}"
 	/bin/cp -a ${jailsysskeldir} ${jailsysdir}/${jname}
 	# local fstab ?
 	[ -f "${jailsysskeldir}/fstab.local" ] && fstablocal="${jailsysskeldir}/fstab.local"
@@ -232,7 +232,7 @@ fi
 ## MD backend
 
 create_fs ${data}
-[ $? -ne 0 ] && err 1 "${MAGENTA}create_fs failed${NORMAL}"
+[ $? -ne 0 ] && err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
 [ ! -d "${data}" ] && err 1 "Can't create datadir ${data}"
 
 if [ -z "${zfs_snapsrc}" ]; then
@@ -245,7 +245,7 @@ mkfstab
 case "${ip4_addr}" in
 	[Dd][Hh][Cc][Pp])
 		ip4_addr=$( dhcpd )
-		[ $? -eq 2 ] && err 1 "${MAGENTA}No free IP address for DHCP in nodeippool${NORMAL}"
+		[ $? -eq 2 ] && err 1 "${N1_COLOR}No free IP address for DHCP in nodeippool${N0_COLOR}"
 		${SYSRC_CMD} -qf ${temprcconf} ip4_addr="${ip4_addr}" > /dev/null
 		# CBSD QUEUE
 		if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
@@ -283,21 +283,21 @@ if [ ${res} -eq 0 ]; then
 	fi
 
 	echo
-	${ECHO} "${MAGENTA}To edit VM properties use: ${GREEN}cbsd jconfig jname=${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}To start VM use: ${GREEN}cbsd jstart ${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}To stop VM use: ${GREEN}cbsd jstop ${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}To remove VM use: ${GREEN}cbsd jremove ${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}For attach VM console use: ${GREEN}cbsd jlogin ${jname}${NORMAL}"
+	${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd jconfig jname=${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd jstart ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd jstop ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd jremove ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd jlogin ${jname}${N0_COLOR}"
 	echo
-	${ECHO} "${MAGENTA}Creating ${jname} complete: ${GREEN}Enjoy!${NORMAL}"
+	${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
 
 	/bin/rm -f ${rcconf}
 
 	[ "${mdsize}" != "0" ] && unmountmd jroot=${data}
 else
 	${ECHO}
-	${ECHO} "${MAGENTA}Creating ${jname} failed: ${GREEN}cbsd jregister${NORMAL}"
-	${ECHO} "${MAGENTA}Please review bad config file: ${GREEN}/tmp/rc.conf_${jname}${NORMAL}"
+	${ECHO} "${N1_COLOR}Creating ${jname} failed: ${N2_COLOR}cbsd jregister${N0_COLOR}"
+	${ECHO} "${N1_COLOR}Please review bad config file: ${N2_COLOR}/tmp/rc.conf_${jname}${N0_COLOR}"
 	/bin/mv ${rcconf} /tmp
 	#cleanup
 	[ -f "${mount_fstab}" ] && /bin/rm -f ${mount_fstab}
@@ -315,7 +315,7 @@ if [ -n "${with_img_helpers}" ]; then
 
 	for i in ${with_img_helpers}; do
 		if [ ! -r "${i}" ]; then
-			${ECHO} "${MAGENTA}Helper doesn't available by path: ${GREEN}${i}${NORMAL}"
+			${ECHO} "${N1_COLOR}Helper doesn't available by path: ${N2_COLOR}${i}${N0_COLOR}"
 			continue
 		else
 			install_and_apply_helpers ${i}
diff --git a/jailctl/jexport b/jailctl/jexport
--- a/jailctl/jexport
+++ b/jailctl/jexport
@@ -32,13 +32,13 @@ jexport_me()
 	local _ret
 	local _filestats
 
-	${ECHO} "${MAGENTA}Exporting (with compress level:${GREEN}${compress}${MAGENTA}), please stand by: ${GREEN}${jname}${NORMAL}"
+	${ECHO} "${N1_COLOR}Exporting (with compress level:${N2_COLOR}${compress}${N1_COLOR}), please stand by: ${N2_COLOR}${jname}${N0_COLOR}"
 	local DEST="${dstdir}/${imgname}"
 	local JAILRCCONF="${jailsysdir}/${jname}/rc.conf_${jname}"
 
 	# check for already existance and offline
 	if [ ! -d "${data}" ]; then
-		${ECHO} "${MAGENTA}No jail data for ${jname}: ${GREEN}${data}${NORMAL}"
+		${ECHO} "${N1_COLOR}No jail data for ${jname}: ${N2_COLOR}${data}${N0_COLOR}"
 		return 1
 	fi
 
@@ -64,7 +64,7 @@ ___NCSTART_DATA=1 \
 				res=$( imgpart mode=pack jname=${jname} compress=${compress} part=header emulator=${emulator} out=${DEST} )
 				_ret=$?
 				/bin/rm -f ${JAILRCCONF}
-				[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_RCCONF*)
 				#currenlty we import/export operation for rc.conf via ascii format
@@ -75,47 +75,47 @@ ___NCSTART_DATA=1 \
 				_ret=$?
 				if [ ${_ret} -ne 0 ]; then
 					/bin/rm -f ${JAILRCCONF}
-					err 1 "${MAGENTA}Error in ${_part} replacewdir: ${res}${NORMAL}"
+					err 1 "${N1_COLOR}Error in ${_part} replacewdir: ${res}${N0_COLOR}"
 				fi
 				res=$( imgpart mode=pack jname=${jname} part=rcconf out=${DEST} )
 				_ret=$?
 				/bin/rm -f ${JAILRCCONF}
-				[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_PKGINFO*)
 				res=$( imgpart mode=pack jname=${jname} part=pkginfo out=${DEST} )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_DESCR*)
 				res=$( imgpart mode=pack jname=${jname} part=descr out=${DEST} )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_INFO*)
 				imgpart mode=pack jname=${jname} part=info out=${DEST}
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_FSTAB*)
 				TMPFSTAB="${ftmpdir}/fstab.$$"
 				[ ! -f "${mount_fstab}" ] && /usr/bin/touch ${mount_fstab}
 				/bin/cp ${mount_fstab} ${TMPFSTAB}
 				res=$( replacewdir file0="${mount_fstab}" old=${workdir} new="CBSDROOT" )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part} replacewdir: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part} replacewdir: ${res}${N0_COLOR}"
 				res=$( imgpart mode=pack jname=${jname} part=fstab out=${DEST} )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				/bin/mv ${TMPFSTAB} ${mount_fstab}
 				;;
 			___NCSTART_LOCALFSTAB*)
 				# localfstab is not mandatory file. Errcode is always 0
 				if [ -r ${mount_fstab}.local ]; then
 					res=$( replacewdir file0="${mount_fstab}.local" old=${workdir} new="CBSDROOT" )
-					[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part} replacewdir: ${res}${NORMAL}"
+					[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part} replacewdir: ${res}${N0_COLOR}"
 				fi
 				res=$( imgpart mode=pack jname=${jname} part=localfstab out=${DEST} || true )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_SYSDATA*)
 				res=$( imgpart mode=pack jname=${jname} part=sysdata out=${DEST} )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				;;
 			___NCSTART_DATA*)
 				#test for zfs mounted & mount if not
@@ -133,7 +133,7 @@ ___NCSTART_DATA=1 \
 				esac
 				jmkrcconf jname=${jname} > ${JAILRCCONF}
 				res=$( imgpart mode=pack jname=${jname} compress=${compress} part=data out=${DEST} filestats=${_filestats} 2>&1 )
-				[ $? -ne 0 ] && err 1 "${MAGENTA}Error in ${_part}: ${res}${NORMAL}"
+				[ $? -ne 0 ] && err 1 "${N1_COLOR}Error in ${_part}: ${res}${N0_COLOR}"
 				/bin/rm -f ${JAILRCCONF}
 				[ "${WASNOMOUNT}" = "1" ] && /sbin/zfs unmount "${ZPOOL}"
 				;;
@@ -166,11 +166,11 @@ ___NCSTART_DATA=1 \
 			img_flat_size=${convval}
 		fi
 
-		${ECHO} "${MAGENTA}environmets flat size: ${GREEN}${img_flat_size}${MAGENTA}, images size ${imgfile}: ${GREEN}${img_size}${NORMAL}"
+		${ECHO} "${N1_COLOR}environmets flat size: ${N2_COLOR}${img_flat_size}${N1_COLOR}, images size ${imgfile}: ${N2_COLOR}${img_size}${N0_COLOR}"
 
 		return 0
 	else
-		${ECHO} "${MAGENTA}Unknown error in jexport${NORMAL}"
+		${ECHO} "${N1_COLOR}Unknown error in jexport${N0_COLOR}"
 		return 1
 	fi
 }
@@ -208,7 +208,7 @@ if [ -n "${jname}" ]; then
 	fi
 else
 	select_jail_by_list -s "List of all jails" -e ${ls}
-	[ -z "${jname}" ] && err 1 "${MAGENTA}Give me jname${NORMAL}"
+	[ -z "${jname}" ] && err 1 "${N1_COLOR}Give me jname${N0_COLOR}"
 fi
 
 if [ -z "${imgname}" ]; then
@@ -219,10 +219,10 @@ fi
 
 . ${jrcconf}
 
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 if [ ${jid} -ne 0 -a "${emulator}" = "bhyve" ]; then
-	err 1 "${MAGENTA}VM is online${NORMAL}"
+	err 1 "${N1_COLOR}VM is online${N0_COLOR}"
 fi
 
 # CBSD QUEUE
diff --git a/jailctl/jrctl b/jailctl/jrctl
--- a/jailctl/jrctl
+++ b/jailctl/jrctl
@@ -30,7 +30,7 @@ EXTHELP="wf_jrctl.html"
 
 show_header()
 {
-	local _header="${WHITE}${BOLD}${myheader}${NORMAL}"
+	local _header="${H1_COLOR}${BOLD}${myheader}${N0_COLOR}"
 	[ ${header} -ne 0 ] && ${ECHO} "${_header}"
 }
 
@@ -108,14 +108,14 @@ show_jaildata_from_sql()
 		. ${distdir}/rctl.subr
 		. ${jrcconf}
 		populate_output_data
-		printf "${NORMAL}" # for column sort
+		printf "${N0_COLOR}" # for column sort
 		if [ "${jid}" != "0" ]; then
-			printf "${GREEN}"
+			printf "${N2_COLOR}"
 		else
-			printf "${CYAN}"
+			printf "${N4_COLOR}"
 		fi
 		printf "${_status}"
-		printf "${NORMAL}\n"
+		printf "${N0_COLOR}\n"
 	done
 }
 
@@ -178,10 +178,10 @@ set_limit()
 	esac
 
 	if [ ! -r "${_formfile}" ]; then
-		${ECHO} "${MAGENTA}No such ${_formfile}${NORMAL}"
+		${ECHO} "${N1_COLOR}No such ${_formfile}${N0_COLOR}"
 		forms module=${_mymodule} jname=${jname} inter=0
 		if [ ! -r "${_formfile}" ]; then
-			${ECHO} "${MAGENTA}No such ${_formfile}${NORMAL}"
+			${ECHO} "${N1_COLOR}No such ${_formfile}${N0_COLOR}"
 			return 1
 		fi
 	fi
@@ -195,7 +195,7 @@ set_limit()
 
 		eval _val="\$rctl_${i}"
 		if [ -n "${_val}" ]; then
-			${ECHO} "${MAGENTA}update rctl for: ${GREEN}${i}${NORMAL}"
+			${ECHO} "${N1_COLOR}update rctl for: ${N2_COLOR}${i}${N0_COLOR}"
 			cbsdsqlrw ${_formfile} "UPDATE forms SET new=\"${_val}\",cur=\"${_val}\" WHERE param=\"${i}\"" 2>/dev/null
 		fi
 
@@ -218,7 +218,7 @@ set_limit()
 		_val=
 		eval _val="\$rctl_${i}"
 		if [ -n "${_val}" ]; then
-			${ECHO} "${MAGENTA}update rctl-extra for: ${GREEN}${i}${NORMAL}"
+			${ECHO} "${N1_COLOR}update rctl-extra for: ${N2_COLOR}${i}${N0_COLOR}"
 			cbsdsqlrw ${_formfile} "UPDATE forms SET new=\"${_val}\",cur=\"${_val}\" WHERE param=\"${i}\"" 2>/dev/null
 		fi
 		_val=
@@ -248,23 +248,23 @@ set_limit()
 			fsquota)
 				. ${zfstool}
 				if [ ${zfsfeat} -ne 1 ]; then
-					${ECHO} "${MAGENTA}fsquota supported only on ZFS. Currently zfsfeat is: ${GREEN}${zfsfeat}${MAGENTA}. Skip set fsquota${NORMAL}"
+					${ECHO} "${N1_COLOR}fsquota supported only on ZFS. Currently zfsfeat is: ${N2_COLOR}${zfsfeat}${N1_COLOR}. Skip set fsquota${N0_COLOR}"
 					break
 				fi
 
 				zfsmnt ${data}
 				if [ $? -eq 0 ]; then
-					${ECHO} "${MAGENTA}${data} is not ZFS separated fileset. Skip set fsquota${NORMAL}"
+					${ECHO} "${N1_COLOR}${data} is not ZFS separated fileset. Skip set fsquota${N0_COLOR}"
 					break
 				fi
 
 				DATA=$( /sbin/zfs get -Ho value name ${data} )
 				if [ -z "${DATA}" ]; then
-					${ECHO} "${MAGENTA}Unable to get dataset name for: ${GREEN}${jaildatadir}${MAGENTA}. Skip set fsquota${NORMAL}"
+					${ECHO} "${N1_COLOR}Unable to get dataset name for: ${N2_COLOR}${jaildatadir}${N1_COLOR}. Skip set fsquota${N0_COLOR}"
 					break
 				fi
 
-				${ECHO} "${MAGENTA}Set new quota for ${jname}:${data}: ${GREEN}${_val}${NORMAL}"
+				${ECHO} "${N1_COLOR}Set new quota for ${jname}:${data}: ${N2_COLOR}${_val}${N0_COLOR}"
 				/sbin/zfs set quota=${_val} ${DATA}
 				;;
 			bw)
@@ -273,7 +273,7 @@ set_limit()
 	done
 
 	if [ -f "${LIMITS}"  ]; then
-		printf "${MAGENTA}${mode} resource limit: [ ${GREEN}"
+		printf "${N1_COLOR}${mode} resource limit: [ ${N2_COLOR}"
 		/bin/cat ${LIMITS} | while read _p; do
 			case ":${_p}" in
 				:#* | :)
@@ -284,7 +284,7 @@ set_limit()
 			_out=$( eval $_str )
 			[ $? -eq 0 ] && printf "${_p} "
 		done
-			printf "${MAGENTA}]${NORMAL}\n"
+			printf "${N1_COLOR}]${N0_COLOR}\n"
 	fi
 
 }
@@ -303,7 +303,7 @@ jail_rctl()
 			[ ${_ret} -ne 0 ] && err ${_ret} "set_error"
 			;;
 		"unset")
-			[ -z "${jname}" ] && err 1 "${MAGENTA}jname= must be set${NORMAL}"
+			[ -z "${jname}" ] && err 1 "${N1_COLOR}jname= must be set${N0_COLOR}"
 			/usr/bin/rctl -r jail:${jname}
 			return 0
 			;;
@@ -427,7 +427,7 @@ done
 #### MAIN
 if [ -n "${jname}" ]; then
 	. ${jrcconf}
-	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 fi
 
 case "${emulator}" in
diff --git a/jailctl/jset b/jailctl/jset
--- a/jailctl/jset
+++ b/jailctl/jset
@@ -7,7 +7,7 @@ EXTHELP="wf_jset.html"
 
 . ${subr}
 
-[ ! -f ${sharedir}/jail-arg ] && err 1 "${GREEN}no jail-arg file${NORMAL}";
+[ ! -f ${sharedir}/jail-arg ] && err 1 "${N2_COLOR}no jail-arg file${N0_COLOR}";
 . ${sharedir}/jail-arg
 
 MYOPTARG="autorestart jconf ${JARG} nice"
@@ -65,7 +65,7 @@ validate_ipaddr()
 		if [ $? -ne 0 ]; then
 			if [ -n "${V_INTERFACE}" -a -n "${V_IP}" ]; then
 				if ! is_nic_exist -n ${V_INTERFACE}; then
-					log_err 1 "${MAGENTA}jset for ${jname} error: interface not exist: ${GREEN}${V_INTERFACE}${NORMAL}"
+					log_err 1 "${N1_COLOR}jset for ${jname} error: interface not exist: ${N2_COLOR}${V_INTERFACE}${N0_COLOR}"
 				fi
 				_myip="${_myip} ${V_IP}"
 			else
@@ -115,7 +115,7 @@ validate_ipaddr()
 		done
 
 		if [ ${_ok} -eq 0 ]; then
-			${ECHO} "${LRED}jset warning: ${MAGENTA}IP address ${GREEN}${_j}${MAGENTA} already assigned to jail: ${GREEN}${_jname}${NORMAL}"
+			${ECHO} "${W1_COLOR}jset warning: ${N1_COLOR}IP address ${N2_COLOR}${_j}${N1_COLOR} already assigned to jail: ${N2_COLOR}${_jname}${N0_COLOR}"
 		fi
 	done # check for local jail end
 }
@@ -130,7 +130,7 @@ modify_ipaddr()
 	sqllist "${_A}" _interface _ip4_addr_old applytpl
 
 	if [ "${_interface}" = "0" ]; then
-		${ECHO} "${argpart}: ${MAGENTA}on-the-fly currently disabled because option interface is "0"${NORMAL}"
+		${ECHO} "${argpart}: ${N1_COLOR}on-the-fly currently disabled because option interface is "0"${N0_COLOR}"
 		cbsdlogger NOTICE ${CBSD_APP}: modify_ipaddr: on-the-fly currently disabled because option interface is 0
 		return 0
 	fi
@@ -155,7 +155,7 @@ modify_ipaddr()
 					;;
 			esac
 			IFS=" "
-			${ECHO} "${MAGENTA}Remove old IP: ${GREEN}/sbin/ifconfig ${_iface} ${_MODIF} ${IWM} -alias${NORMAL}"
+			${ECHO} "${N1_COLOR}Remove old IP: ${N2_COLOR}/sbin/ifconfig ${_iface} ${_MODIF} ${IWM} -alias${N0_COLOR}"
 			cbsdlogger NOTICE ${CBSD_APP}: modify_ipaddr: remove old IP: /sbin/ifconfig ${_iface} ${_MODIF} ${IWM} -alias
 			/sbin/ifconfig ${_iface} ${_MODIF} ${IWM} -alias >/dev/null 2>/dev/null
 			IFS=","
@@ -170,7 +170,7 @@ modify_ipaddr()
 			_dhcp=$( dhcpd )
 			if [ $? -eq 2 ]; then
 				cbsdlogger WARNING ${CBSD_APP}: modify_ipaddr: No free IP address for DHCP in nodeippool
-				err 1 "${MAGENTA}No free IP address for DHCP in nodeippool${NORMAL}"
+				err 1 "${N1_COLOR}No free IP address for DHCP in nodeippool${N0_COLOR}"
 			fi
 			_pureip="${_dhcp}"
 		fi
@@ -199,7 +199,7 @@ modify_ipaddr()
 			esac
 			[ "${mkhostsfile}" != "0" ] && mkjhosts ips="${IWM}" file="${data}/etc/hosts" hosts="${host_hostname}"
 			IFS=" "
-			${ECHO} "${MAGENTA}Setup new IP: ${GREEN}/sbin/ifconfig ${_iface} ${_MODIF} ${_pureip} alias${NORMAL}"
+			${ECHO} "${N1_COLOR}Setup new IP: ${N2_COLOR}/sbin/ifconfig ${_iface} ${_MODIF} ${_pureip} alias${N0_COLOR}"
 			cbsdlogger NOTICE ${CBSD_APP}: modify_ipaddr: setup new IP: /sbin/ifconfig ${_iface} ${_MODIF} ${_pureip} alias
 			/sbin/ifconfig ${_iface} ${_MODIF} ${_pureip} alias
 			IFS=","
@@ -217,7 +217,7 @@ modify_ipaddr()
 	/usr/sbin/jail -m ${_nIPs} jid=${jid}
 
 	cbsdsqlrw local UPDATE jails SET ${i}=\"${ip4_addr}\" WHERE jname=\"${jname}\"
-	${ECHO} "${argpart}: ${MAGENTA}${ip4_addr}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${ip4_addr}${N0_COLOR}"
 
 	if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
 		[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} id="${jname}" cmd=update ip4_addr="${ip4_addr}" status=1
@@ -229,7 +229,7 @@ modify_allow_mount()
 {
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_mount}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.mount=${allow_mount} jid=${jid}
-	${ECHO} "${argpart}: ${MAGENTA}${allow_mount}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_mount}${N0_COLOR}"
 }
 
 # jid must be set
@@ -237,7 +237,7 @@ modify_allow_raw_sockets()
 {
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_raw_sockets}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.raw_sockets=${allow_raw_sockets} jid=${jid}
-	${ECHO} "${argpart}: ${MAGENTA}${allow_raw_sockets}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_raw_sockets}${N0_COLOR}"
 }
 
 # jid must be set
@@ -245,7 +245,7 @@ modify_allow_read_msgbuf()
 {
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_read_msgbuf}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.read_msgbuf=${allow_read_msgbuf} jid=${jid}
-	${ECHO} "${argpart}: ${MAGENTA}${allow_read_msgbuf}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_read_msgbuf}${N0_COLOR}"
 }
 
 # jid must be set
@@ -253,7 +253,7 @@ modify_allow_vmm()
 {
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_vmm}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.vmm=${allow_vmm} jid=${jid}
-	${ECHO} "${argpart}: ${MAGENTA}${allow_vmm}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_vmm}${N0_COLOR}"
 }
 
 # jid must be set
@@ -264,7 +264,7 @@ modify_allow_nullfs()
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_nullfs}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.mount.nullfs=${allow_nullfs} jid=${jid}
 
-	${ECHO} "${argpart}: ${MAGENTA}${allow_nullfs}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_nullfs}${N0_COLOR}"
 	[ ${allow_nullfs} -eq 0 ] && return 0
 
 	# we need to force allow_mount too when allow_tmpfs sets to 1 and allow_mount is zero
@@ -272,7 +272,7 @@ modify_allow_nullfs()
 	if [ "${allow_mount}" = "0" ]; then
 		cbsdsqlrw local "UPDATE jails SET allow_mount=\"1\" WHERE jname=\"${jname}\""
 		/usr/sbin/jail -m allow.mount=1 jid=${jid}
-		${ECHO} "allow_mount: ${MAGENTA}1${NORMAL}"
+		${ECHO} "allow_mount: ${N1_COLOR}1${N0_COLOR}"
 	fi
 }
 
@@ -284,7 +284,7 @@ modify_allow_fusefs()
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_fusefs}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.mount.fusefs=${allow_fusefs} jid=${jid}
 
-	${ECHO} "${argpart}: ${MAGENTA}${allow_fusefs}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_fusefs}${N0_COLOR}"
 	[ ${allow_fusefs} -eq 0 ] && return 0
 
 	# we need to force allow_mount too when allow_tmpfs sets to 1 and allow_mount is zero
@@ -292,7 +292,7 @@ modify_allow_fusefs()
 	if [ "${allow_mount}" = "0" ]; then
 		cbsdsqlrw local "UPDATE jails SET allow_mount=\"1\" WHERE jname=\"${jname}\""
 		/usr/sbin/jail -m allow.mount=1 jid=${jid}
-		${ECHO} "allow_mount: ${MAGENTA}1${NORMAL}"
+		${ECHO} "allow_mount: ${N1_COLOR}1${N0_COLOR}"
 	fi
 }
 
@@ -304,7 +304,7 @@ modify_allow_procfs()
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_procfs}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.mount.procfs=${allow_procfs} jid=${jid}
 
-	${ECHO} "${argpart}: ${MAGENTA}${allow_procfs}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_procfs}${N0_COLOR}"
 	[ ${allow_procfs} -eq 0 ] && return 0
 
 	# we need to force allow_mount too when allow_tmpfs sets to 1 and allow_mount is zero
@@ -312,7 +312,7 @@ modify_allow_procfs()
 	if [ "${allow_mount}" = "0" ]; then
 		cbsdsqlrw local "UPDATE jails SET allow_mount=\"1\" WHERE jname=\"${jname}\""
 		/usr/sbin/jail -m allow.mount=1 jid=${jid}
-		${ECHO} "allow_mount: ${MAGENTA}1${NORMAL}"
+		${ECHO} "allow_mount: ${N1_COLOR}1${N0_COLOR}"
 	fi
 }
 
@@ -323,7 +323,7 @@ modify_allow_tmpfs()
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_tmpfs}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.mount.tmpfs=${allow_tmpfs} jid=${jid}
 
-	${ECHO} "${argpart}: ${MAGENTA}${allow_tmpfs}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_tmpfs}${N0_COLOR}"
 	[ ${allow_tmpfs} -eq 0 ] && return 0
 
 	# we need to force allow_mount too when allow_tmpfs sets to 1 and allow_mount is zero
@@ -331,7 +331,7 @@ modify_allow_tmpfs()
 	if [ "${allow_mount}" = "0" ]; then
 		cbsdsqlrw local "UPDATE jails SET allow_mount=\"1\" WHERE jname=\"${jname}\""
 		/usr/sbin/jail -m allow.mount=1 jid=${jid}
-		${ECHO} "allow_mount: ${MAGENTA}1${NORMAL}"
+		${ECHO} "allow_mount: ${N1_COLOR}1${N0_COLOR}"
 	fi
 }
 
@@ -342,7 +342,7 @@ modify_allow_fdescfs()
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${allow_fdescfs}\" WHERE jname=\"${jname}\""
 	/usr/sbin/jail -m allow.mount.fdescfs=${allow_fdescfs} jid=${jid}
 
-	${ECHO} "${argpart}: ${MAGENTA}${allow_fdescfs}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${allow_fdescfs}${N0_COLOR}"
 	[ ${allow_fdescfs} -eq 0 ] && return 0
 
 	# we need to force allow_mount too when allow_fdescfs sets to 1 and allow_mount is zero
@@ -350,7 +350,7 @@ modify_allow_fdescfs()
 	if [ "${allow_mount}" = "0" ]; then
 		cbsdsqlrw local "UPDATE jails SET allow_mount=\"1\" WHERE jname=\"${jname}\""
 		/usr/sbin/jail -m allow.mount=1 jid=${jid}
-		${ECHO} "allow_mount: ${MAGENTA}1${NORMAL}"
+		${ECHO} "allow_mount: ${N1_COLOR}1${N0_COLOR}"
 	fi
 }
 
@@ -361,7 +361,7 @@ modify_nice()
 	local _formfile="${jailsysdir}/${jname}/helpers/jrctl.sqlite"
 
 	if [ ! -r ${_formfile} ]; then
-		${ECHO} "${MAGENTA}No such rctl file: ${GREEN}${_formfile}${NORMAL}"
+		${ECHO} "${N1_COLOR}No such rctl file: ${N2_COLOR}${_formfile}${N0_COLOR}"
 		return 1
 	fi
 
@@ -373,7 +373,7 @@ modify_nice()
 modify_cpuset()
 {
 	cbsdsqlrw local UPDATE jails SET ${i}=\"${cpuset}\" WHERE jname=\"${jname}\"
-	${ECHO} "${argpart}: ${MAGENTA}${cpuset}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${cpuset}${N0_COLOR}"
 	cpuset -c -l ${cpuset} -j ${jid}
 }
 
@@ -393,12 +393,12 @@ modify_mount_src()
 
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${mount_src}\" WHERE jname=\"${jname}\""
 
-	${ECHO} "${argpart}: ${MAGENTA}${mount_src}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${mount_src}${N0_COLOR}"
 
 	. ${distdir}/universe.subr
 
 	init_srcdir
-	[ ! -d "${SRC_DIR}" ] && ${ECHO} "${MAGENTA}No such src dir: ${GREEN}${SRC_DIR}${NORMAL}"
+	[ ! -d "${SRC_DIR}" ] && ${ECHO} "${N1_COLOR}No such src dir: ${N2_COLOR}${SRC_DIR}${N0_COLOR}"
 
 	[ ${baserw} -eq 1 ] && path="${data}"
 	_dst="${path}/usr/src"
@@ -408,7 +408,7 @@ modify_mount_src()
 			is_mounted ${_dst} && umount -f ${_dst}
 			;;
 		1)
-			is_mounted ${_dst} && err 1 "${MAGENTA}Already mounted: ${GREEN}${_dst}${NORMAL}"
+			is_mounted ${_dst} && err 1 "${N1_COLOR}Already mounted: ${N2_COLOR}${_dst}${N0_COLOR}"
 			[ ! -d "${_dst}" ] && mkdir -p ${_dst}
 			${MOUNT_NULL_CMD} -oro ${SRC_DIR} ${_dst}
 			;;
@@ -432,7 +432,7 @@ modify_mount_ports()
 
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${mount_ports}\" WHERE jname=\"${jname}\""
 
-	${ECHO} "${argpart}: ${MAGENTA}${mount_ports}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${mount_ports}${N0_COLOR}"
 
 	[ ${baserw} -eq 1 ] && path="${data}"
 	_dst="${path}/usr/ports"
@@ -444,7 +444,7 @@ modify_mount_ports()
 		;;
 		1)
 			[ ! -d /usr/ports ] && return 0
-			is_mounted ${_dst} && err 1 "${MAGENTA}Already mounted: ${GREEN}${_dst}${NORMAL}"
+			is_mounted ${_dst} && err 1 "${N1_COLOR}Already mounted: ${N2_COLOR}${_dst}${N0_COLOR}"
 			[ ! -d "${_dst}" ] && mkdir -p ${_dst}
 			${MOUNT_NULL_CMD} -oro /usr/ports ${_dst}
 			[ ! -d /usr/ports/distfiles ] && mkdir -p /usr/ports/distfiles
@@ -470,7 +470,7 @@ modify_mount_kernel()
 
 	cbsdsqlrw local "UPDATE jails SET ${i}=\"${mount_kernel}\" WHERE jname=\"${jname}\""
 
-	${ECHO} "${argpart}: ${MAGENTA}${mount_kernel}${NORMAL}"
+	${ECHO} "${argpart}: ${N1_COLOR}${mount_kernel}${N0_COLOR}"
 
 	. ${distdir}/universe.subr
 	init_kerneldir
@@ -479,14 +479,14 @@ modify_mount_kernel()
 	_dst="${path}/boot/kernel"
 	_src="${KERNEL_DIR}/boot/kernel"
 
-	[ ! -d "${_src}" ] && err 1 "${MAGENTA}No such source kernel dir. Use buildkernel or repo for fetching kernel: ${GREEN}${_src}${NORMAL}"
+	[ ! -d "${_src}" ] && err 1 "${N1_COLOR}No such source kernel dir. Use buildkernel or repo for fetching kernel: ${N2_COLOR}${_src}${N0_COLOR}"
 
 	case "${mount_kernel}" in
 		0)
 			is_mounted ${_dst} && umount -f ${_dst}
 			;;
 		1)
-			is_mounted ${_dst} && err 1 "${MAGENTA}Already mounted: ${GREEN}${_dst}${NORMAL}"
+			is_mounted ${_dst} && err 1 "${N1_COLOR}Already mounted: ${N2_COLOR}${_dst}${N0_COLOR}"
 			[ ! -d "${_dst}" ] && /bin/mkdir -p ${_dst}
 			${MOUNT_NULL_CMD} -oro ${_src} ${_dst}
 			;;
@@ -547,7 +547,7 @@ update_jails()
 	if ! need_action; then
 		cbsdsqlrw local UPDATE jails SET ${i}=\"${VAL}\" WHERE jname=\"${jname}\"
 		cbsdlogger NOTICE ${CBSD_APP}: ${argpart}: ${VAL}
-		${ECHO} "${argpart}: ${MAGENTA}${VAL}${NORMAL}"
+		${ECHO} "${argpart}: ${N1_COLOR}${VAL}${N0_COLOR}"
 
 		# Update realtime info
 		if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
@@ -565,10 +565,10 @@ update_jails()
 # MAIN
 # here we get status from jstatus, not via jrcconf for non-overwriting params in args
 jid=$( jstatus jname=${jname} )
-[ $? -eq 0 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+[ $? -eq 0 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 if [ -n "${jconf}" ]; then
-	[ ! -r "${jconf}" ] && err 1 "${MAGENTA}No such jconf file: ${GREEN}${jconf}${NORMAL}"
+	[ ! -r "${jconf}" ] && err 1 "${N1_COLOR}No such jconf file: ${N2_COLOR}${jconf}${N0_COLOR}"
 	#jset jname=${jname} `/usr/bin/grep -v '#' ${jconf} | /usr/bin/grep .| /usr/bin/tr -d ";"`
 	my_arg=$( /usr/bin/grep -v '#' ${jconf} | /usr/bin/grep . | /usr/bin/tr -d ";" | /usr/bin/sed 's/"/\\"/g' | /usr/bin/xargs )
 	exec /bin/sh << EOF
@@ -667,7 +667,7 @@ for n in ${my_arg}; do
 					*)
 						if [ ${autorestart} -eq 0 ]; then
 							cbsdlogger NOTICE ${CBSD_APP}: on-the-fly currently unimplemented for ${argpart} for ${jname}
-							${ECHO} "${argpart}: ${MAGENTA}on-the-fly currently unimplemented${NORMAL}"
+							${ECHO} "${argpart}: ${N1_COLOR}on-the-fly currently unimplemented${N0_COLOR}"
 						else
 							update_jails
 						fi
diff --git a/jailctl/vcreate b/jailctl/vcreate
--- a/jailctl/vcreate
+++ b/jailctl/vcreate
@@ -26,7 +26,7 @@ readconf zfs.conf
 . ${cbsdinit}
 
 ### MAIN
-[ ! -f "$jconf" ] && err 1 "${MAGENTA}no such jconf file${NORMAL}";
+[ ! -f "$jconf" ] && err 1 "${N1_COLOR}no such jconf file${N0_COLOR}";
 over="${ver}"
 oarch="${arch}"
 jconf=$( realpath $jconf )
@@ -51,16 +51,16 @@ fi
 . ${buildconf}
 . ${temprcconf}
 
-[ -z "${jname}" ] && err 1 "${MAGENTA}No such jname variable${NORMAL}"
+[ -z "${jname}" ] && err 1 "${N1_COLOR}No such jname variable${N0_COLOR}"
 
 # profile
 readconf vm-${vm_os_type}-${vm_os_profile}.conf
-[ -z "${vm_profile}" ] && err 1 "${MAGENTA}No such profile: ${GREEN}vm-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+[ -z "${vm_profile}" ] && err 1 "${N1_COLOR}No such profile: ${N2_COLOR}vm-${vm_os_type}-${vm_os_profile}.conf${N0_COLOR}"
 # re-read jail params and apply personal after profile
 . ${temprcconf}
 
 jstatus jname=${jname} > /dev/null 2>&1
-[ $? -eq 0 ] || err 1 "${MAGENTA}Jail with $jname already exist${NORMAL}"
+[ $? -eq 0 ] || err 1 "${N1_COLOR}Jail with $jname already exist${N0_COLOR}"
 
 # ip validate
 if [ -n "${interface}" -a "${inteface}" != "0" ]; then
@@ -68,11 +68,11 @@ if [ -n "${interface}" -a "${inteface}" != "0" ]; then
 	checkip ip=${ips} check=1 > /dev/null 2>&1
 	case $? in
 		0)
-			err 1 "${MAGENTA}Ip not in pool range${NORMAL}"
+			err 1 "${N1_COLOR}Ip not in pool range${N0_COLOR}"
 			;;
 		1)	;;
 		2)
-			${ECHO} "${MAGENTA}Warning:${GREEN} Ip already exists in LAN${NORMAL}"
+			${ECHO} "${N1_COLOR}Warning:${N2_COLOR} Ip already exists in LAN${N0_COLOR}"
 			;;
 		*)
 			err 1 "Unknown code from checkip"
@@ -80,7 +80,7 @@ if [ -n "${interface}" -a "${inteface}" != "0" ]; then
 	esac
 fi
 
-${ECHO} "${MAGENTA}Please wait: ${GREEN}this will take a while...${NORMAL}"
+${ECHO} "${N1_COLOR}Please wait: ${N2_COLOR}this will take a while...${N0_COLOR}"
 
 [ -d "${data}" ] && removedata ${data}
 
@@ -106,7 +106,7 @@ if [ "${vm_os_type}" = "freebsd" -a "${from_jail}" = "1" ]; then
 			init_basedir
 			init_kerneldir
 			get_base -v ${ver}
-			${ECHO} "${MAGENTA}Stage1: ${GREEN}jail hier...${NORMAL}"
+			${ECHO} "${N1_COLOR}Stage1: ${N2_COLOR}jail hier...${N0_COLOR}"
 			populate_freebsd_world
 			customskel
 			;;
@@ -148,13 +148,13 @@ fi
 
 if [ ${_res} -eq 0 ]; then
 	echo
-	${ECHO} "${MAGENTA}To edit VM properties use: ${GREEN}cbsd vconfig jname=${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}To start VM use: ${GREEN}cbsd vstart ${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}To stop VM use: ${GREEN}cbsd vstop ${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}To remove VM use: ${GREEN}cbsd vremove ${jname}${NORMAL}"
-	${ECHO} "${MAGENTA}For attach VM console use: ${GREEN}cbsd vlogin ${jname}${NORMAL}"
+	${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd vconfig jname=${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd vstart ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd vstop ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd vremove ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd vlogin ${jname}${N0_COLOR}"
 	echo
-	${ECHO} "${MAGENTA}Creating ${jname} complete: ${GREEN}Enjoy!${NORMAL}"
+	${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
 	/bin/rm -f $rcconf
 
 	[ "${mdsize}" != "0" ] && unmountmd jroot=${data}
@@ -164,7 +164,7 @@ if [ ${_res} -eq 0 ]; then
 	defnic="nic1.vhd"
 
 	if [ "${from_jail}" ]; then
-		${ECHO} "${MAGENTA}Stage2: ${GREEN}jail2iso...${NORMAL}"
+		${ECHO} "${N1_COLOR}Stage2: ${N2_COLOR}jail2iso...${N0_COLOR}"
 		[ -z "${swapsize}" ] && swapsize="0"
 		jail2iso jname=${jname} nameserver=${jnameserver} ip4_addr=${ip4_addr} gw4=${gw4} dstname=${jname}.$$.img swapsize=${swapsize} freesize=${imgsize} dstdir=/tmp host_hostname="${host_hostname}" media=virtualbox quiet=1 prunelist=0 nobase=${nobase} vm_guestfs=${vm_guestfs}
 		jremove ${jname}
@@ -206,8 +206,8 @@ if [ ${_res} -eq 0 ]; then
 	exit 0
 else
 	${ECHO}
-	${ECHO} "${MAGENTA}Creating ${jname} failed: ${GREEN}cbsd jregister${NORMAL}"
-	${ECHO} "${MAGENTA}Please review bad config file: ${GREEN}/tmp/rc.conf_${jname}${NORMAL}"
+	${ECHO} "${N1_COLOR}Creating ${jname} failed: ${N2_COLOR}cbsd jregister${N0_COLOR}"
+	${ECHO} "${N1_COLOR}Please review bad config file: ${N2_COLOR}/tmp/rc.conf_${jname}${N0_COLOR}"
 	mv $rcconf /tmp
 	#cleanup
 	[ -f "${mount_fstab}" ] && /bin/rm -f ${mount_fstab}
diff --git a/jailctl/vstart b/jailctl/vstart
--- a/jailctl/vstart
+++ b/jailctl/vstart
@@ -46,7 +46,7 @@ if [ $# -gt 1 -a -z "${jname}" ]; then
 	done
 
 	wait_for_fpid -a start -t ${parallel}
-	err 0 "${MAGENTA}Multiple vstart: ${GREEN}done${NORMAL}"
+	err 0 "${N1_COLOR}Multiple vstart: ${N2_COLOR}done${N0_COLOR}"
 fi
 
 
@@ -55,11 +55,11 @@ init_virtualbox
 
 [ -z "$jname" ] && jname=$1
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
-[ ${status} -eq 2 ] && err 1 "${MAGENTA}Jail in slave mode. Please ${GREEN}cbsd jswmode mode=master${MAGENTA} first${NORMAL}"
-[ $jid -ne 0 ] && err 1 "${MAGENTA}Jail ${jname} already running, jid: ${GREEN}${jid}${NORMAL}"
-[ "${emulator}" != "virtualbox" ] && err 1 "${MAGENTA}Not virtualbox mode${NORMAL}"
-[ -z "${vm_ram}" -o -z "${vm_cpus}" -o -z "${vm_os_type}" ] && err 1 "${MAGENTA}Parameter is mandatory: ${GREEN}vm_ram, vm_cpus, vm_os_type${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+[ ${status} -eq 2 ] && err 1 "${N1_COLOR}Jail in slave mode. Please ${N2_COLOR}cbsd jswmode mode=master${N1_COLOR} first${N0_COLOR}"
+[ $jid -ne 0 ] && err 1 "${N1_COLOR}Jail ${jname} already running, jid: ${N2_COLOR}${jid}${N0_COLOR}"
+[ "${emulator}" != "virtualbox" ] && err 1 "${N1_COLOR}Not virtualbox mode${N0_COLOR}"
+[ -z "${vm_ram}" -o -z "${vm_cpus}" -o -z "${vm_os_type}" ] && err 1 "${N1_COLOR}Parameter is mandatory: ${N2_COLOR}vm_ram, vm_cpus, vm_os_type${N0_COLOR}"
 
 
 # hardcoded first disk path from SQL. Todo: mark bootable disk(s)
@@ -68,9 +68,9 @@ MDFILE=$( cbsdsqlro local SELECT dsk_path FROM ${emulator}dsk WHERE jname=\"${jn
 case "${vm_vnc_port}" in
 	0)
 		vm_port=$( get_next_tcp_port -s 5900 -e 6900 )
-		[ $? -ne 0 ] && err 1 "${MAGENTA}no free available port in 5900-6900 range${NORMAL}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}no free available port in 5900-6900 range${N0_COLOR}"
 		vnc_args="--vrde on --vrdeport ${vm_port} --vrdeproperty VNCPassword=cbsd"
-		${ECHO} "${MAGENTA}VRDP is enabled. VNC port: ${GREEN}${vm_port}. ${MAGENTA}VNC pass: ${GREEN}cbsd${NORMAL}${NORMAL}"
+		${ECHO} "${N1_COLOR}VRDP is enabled. VNC port: ${N2_COLOR}${vm_port}. ${N1_COLOR}VNC pass: ${N2_COLOR}cbsd${N0_COLOR}${N0_COLOR}"
 		;;
 	1)
 		vm_port=0
@@ -89,10 +89,10 @@ if [ "${interface}" != "auto" ]; then
 	_res=$( ${miscdir}/nics-list -s "lo" |while read _iface; do
 		[ "${interface}" = "${_iface}" ] && echo "${_iface}" ] && exit 0
 	done )
-	[ -z "${_res}" ] && err 1 "${MAGENTA}No such interface: ${GREEN}${interface}${NORMAL}"
+	[ -z "${_res}" ] && err 1 "${N1_COLOR}No such interface: ${N2_COLOR}${interface}${N0_COLOR}"
 else
 	auto_iface=$( /sbin/route -n get 0.0.0.0 |/usr/bin/awk '/interface/{print $2}' )
-	[ -z "${auto_iface}" ] && err 1 "${MAGENTA}Can't determine uplink interface${NORMAL}"
+	[ -z "${auto_iface}" ] && err 1 "${N1_COLOR}Can't determine uplink interface${N0_COLOR}"
 	interface="${auto_iface}"
 fi
 
@@ -108,14 +108,14 @@ else
 fi
 
 readconf vm-${vm_os_type}-${vm_os_profile}.conf
-[ -z "${vm_profile}" ] && err 1 "${MAGENTA}No such profile: ${GREEN}vm-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+[ -z "${vm_profile}" ] && err 1 "${N1_COLOR}No such profile: ${N2_COLOR}vm-${vm_os_type}-${vm_os_profile}.conf${N0_COLOR}"
 # re-read jail params and apply personal after profile
 . ${jrcconf}
 
 manage_boot_by_empty_hdd
 init_iso
 if [ $? -eq 1 -a "${vm_boot}" = "cd" ]; then
-	printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
+	printf "${N1_COLOR}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${N0_COLOR}"
 	for i in $( jot 5 ); do
 		printf "."
 		sleep 1
@@ -126,11 +126,11 @@ fi
 [ "${vm_iso_path}" != "0" ] && iso_img="${vm_iso_path}"
 
 if [ -r "${iso_img}" ]; then
-	${ECHO} "${MAGENTA}Attaching as DVD-DRIVE: ${GREEN}${iso_img}${NORMAL}"
+	${ECHO} "${N1_COLOR}Attaching as DVD-DRIVE: ${N2_COLOR}${iso_img}${N0_COLOR}"
 	${VBOX_MGMT_CMD} storageattach ${jname} --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium ${iso_img}
 fi
 
-${ECHO} "${MAGENTA}Boot from: ${GREEN}${vm_boot}${NORMAL}"
+${ECHO} "${N1_COLOR}Boot from: ${N2_COLOR}${vm_boot}${N0_COLOR}"
 
 case "${vm_boot}" in
 	"hdd")
diff --git a/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller b/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller
--- a/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller
+++ b/share/bsdconfig/cbsd/bhyvedsk-cfgcontroller
@@ -29,7 +29,7 @@ dialog_menu_main()
 		echo "export new_ctr_type=\"${type}\""
 		echo "export new_ctr_count=\"${count}\""
 		echo "export new_ctr_cache=\"${cache}\""
-	done ) || err 1 "${MAGENTA}Error while create controller map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create controller map${N0_COLOR}"
 
 	local menu_list="
 		'type'		'${new_ctr_type}'	'Select controller type'
@@ -103,8 +103,8 @@ set +e
 . ${BSDCFG_LIBE}/${APP_DIR}/include/messages-bhyve-dskcontroller.subr
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such VM: ${GREEN}${jname}${NORMAL}"
-[ "${emulator}" != "bhyve" ] && err 1 "${MAGENTA}Not in bhyve mode${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such VM: ${N2_COLOR}${jname}${N0_COLOR}"
+[ "${emulator}" != "bhyve" ] && err 1 "${N1_COLOR}Not in bhyve mode${N0_COLOR}"
 
 . ${distdir}/bhyve.subr
 . ${distdir}/share/bhyve/bhyve-controller.subr
diff --git a/share/bsdconfig/cbsd/bhyvedsk-cfgdsk b/share/bsdconfig/cbsd/bhyvedsk-cfgdsk
--- a/share/bsdconfig/cbsd/bhyvedsk-cfgdsk
+++ b/share/bsdconfig/cbsd/bhyvedsk-cfgdsk
@@ -33,7 +33,7 @@ dialog_menu_main()
 		echo "export dsk_slot=\"${dsk_slot}\""
 		echo "export dsk_type=\"${dsk_type}\""
 		echo "export bootable=\"${bootable}\""
-	done ) || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create disk map${N0_COLOR}"
 
 	# get ${dsk_size}
 	populate_dsk_size
@@ -154,8 +154,8 @@ set +e
 . ${BSDCFG_LIBE}/${APP_DIR}/include/messages-bhyvedsk.subr
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such VM: ${GREEN}${jname}${NORMAL}"
-[ "${emulator}" != "bhyve" ] && err 1 "${MAGENTA}Not in bhyve mode${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such VM: ${N2_COLOR}${jname}${N0_COLOR}"
+[ "${emulator}" != "bhyve" ] && err 1 "${N1_COLOR}Not in bhyve mode${N0_COLOR}"
 
 . ${distdir}/share/bhyve/bhyve-dsk.subr
 . ${distdir}/bhyve.subr
diff --git a/share/bsdconfig/cbsd/bhyvenic-cfgnic b/share/bsdconfig/cbsd/bhyvenic-cfgnic
--- a/share/bsdconfig/cbsd/bhyvenic-cfgnic
+++ b/share/bsdconfig/cbsd/bhyvenic-cfgnic
@@ -29,7 +29,7 @@ dialog_menu_main()
 		echo "export nic_hwaddr=\"${nic_hwaddr}\""
 		echo "export nic_address=\"${nic_address}\""
 		echo "export nic_mtu=\"${nic_mtu}\""
-	done ) || err 1 "${MAGENTA}Error while create NIC map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create NIC map${N0_COLOR}"
 
 	local menu_list="
 		'nic_driver'	'${nic_driver}'		'NIC driver'
@@ -105,8 +105,8 @@ set +e
 . $BSDCFG_LIBE/$APP_DIR/include/messages-bhyvenic.subr
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such VM: ${GREEN}${jname}${NORMAL}"
-[ "${emulator}" != "bhyve" ] && err 1 "${MAGENTA}Not in bhyve mode${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such VM: ${N2_COLOR}${jname}${N0_COLOR}"
+[ "${emulator}" != "bhyve" ] && err 1 "${N1_COLOR}Not in bhyve mode${N0_COLOR}"
 
 . $BSDCFG_LIBE/$APP_DIR/include/bhyvenic.subr
 . ${distdir}/bhyve.subr
diff --git a/share/bsdconfig/cbsd/jailnic-cfgnic b/share/bsdconfig/cbsd/jailnic-cfgnic
--- a/share/bsdconfig/cbsd/jailnic-cfgnic
+++ b/share/bsdconfig/cbsd/jailnic-cfgnic
@@ -29,7 +29,7 @@ dialog_menu_main()
 		echo "export nic_hwaddr${nic_last_id}=\"${nic_hwaddr}\""
 		echo "export nic_address${nic_last_id}=\"${nic_address}\""
 		nic_last_id=$(( nic_last_id + 1 ))
-	done ) || err 1 "${MAGENTA}Error while create nic map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create nic map${N0_COLOR}"
 
 	local menu_list="
 		'nic_name'	'${nic_name}'		'NIC name'
@@ -101,8 +101,8 @@ set +e
 . $BSDCFG_LIBE/$APP_DIR/include/messages-jailnic.subr
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such VM: ${GREEN}${jname}${NORMAL}"
-[ "${emulator}" != "jail" ] && err 1 "${MAGENTA}Not in jail mode${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such VM: ${N2_COLOR}${jname}${N0_COLOR}"
+[ "${emulator}" != "jail" ] && err 1 "${N1_COLOR}Not in jail mode${N0_COLOR}"
 
 . $BSDCFG_LIBE/$APP_DIR/include/jailnic.subr
 . ${distdir}/jail.subr
diff --git a/share/bsdconfig/cbsd/xendsk-cfgdsk b/share/bsdconfig/cbsd/xendsk-cfgdsk
--- a/share/bsdconfig/cbsd/xendsk-cfgdsk
+++ b/share/bsdconfig/cbsd/xendsk-cfgdsk
@@ -27,7 +27,7 @@ dialog_menu_main()
 		echo "export dsk_controller=\"${dsk_controller}\""
 		echo "export dsk_slot=\"${dsk_slot}\""
 		echo "export dsk_type=\"${dsk_type}\""
-	done ) || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create disk map${N0_COLOR}"
 
 	# get $dsk_size
 	populate_dsk_size
@@ -104,8 +104,8 @@ set +e
 f_include_lang $BSDCFG_LIBE/$APP_DIR/include/messages-xendsk.subr
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such VM: ${GREEN}${jname}${NORMAL}"
-[ "${emulator}" != "xen" ] && err 1 "${MAGENTA}Not in xen mode${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such VM: ${N2_COLOR}${jname}${N0_COLOR}"
+[ "${emulator}" != "xen" ] && err 1 "${N1_COLOR}Not in xen mode${N0_COLOR}"
 
 . $BSDCFG_LIBE/$APP_DIR/include/xendsk.subr
 . ${distdir}/xen.subr
diff --git a/sudoexec/jregister b/sudoexec/jregister
--- a/sudoexec/jregister
+++ b/sudoexec/jregister
@@ -12,7 +12,7 @@ rcfile= alternative path to ascii rc.conf file\n"
 
 . ${cbsdinit}
 
-[ -z "${jname}" -a -z "${rcfile}" ] && err 1 "${MAGENTA}Please specify: ${GREEN}jname= ${MAGENTA} or ${GREEN}rcfile=${NORMAL}"
+[ -z "${jname}" -a -z "${rcfile}" ] && err 1 "${N1_COLOR}Please specify: ${N2_COLOR}jname= ${N1_COLOR} or ${N2_COLOR}rcfile=${N0_COLOR}"
 
 . ${system}
 
@@ -58,10 +58,10 @@ jregister_multi_init()
 		shift $(($OPTIND - 1))
 	done
 
-	[ -z "${task_owner}" ] && err 1 "${MAGENTA}multiple_processing_spawn: empty -o multiple_task_owner${NORMAL}"
+	[ -z "${task_owner}" ] && err 1 "${N1_COLOR}multiple_processing_spawn: empty -o multiple_task_owner${N0_COLOR}"
 
 	. ${distdir}/multiple.subr
-	${ECHO} "${MAGENTA}Hint: Press ${GREEN}'Ctrl+t'${MAGENTA} to see last logfile line for active task${NORMAL}" 1>&2
+	${ECHO} "${N1_COLOR}Hint: Press ${N2_COLOR}'Ctrl+t'${N1_COLOR} to see last logfile line for active task${N0_COLOR}" 1>&2
 	task_id=
 	task_id_cur=
 	task_owner="${task_owner}"
@@ -105,7 +105,7 @@ if [ -n "${jail_list}" ]; then
 	task_owner="jregister_multiple_remove"
 	jregister_multi_init -c "${_args}" -o ${task_owner} -n "jregister"
 	
-	err 0 "${MAGENTA}Multiple jregister: ${GREEN}done${NORMAL}"
+	err 0 "${N1_COLOR}Multiple jregister: ${N2_COLOR}done${N0_COLOR}"
 fi
 
 # we prefer rcfile
@@ -116,7 +116,7 @@ else
 fi
 
 if [ ! -f  ${JAILRCCONF} ]; then
-	err 1 "${MAGENTA}no rcconf ${JAILRCCONF} file for jail: ${GREEN}${jname}${NORMAL}"
+	err 1 "${N1_COLOR}no rcconf ${JAILRCCONF} file for jail: ${N2_COLOR}${jname}${N0_COLOR}"
 fi
 
 . ${distdir}/env_register.subr
@@ -138,7 +138,7 @@ replacewdir file0=/tmp/rcconf.$$ old="CBSDROOT"
 [ -z "${dbfile}" ] && dbfile="${dbdir}/local.sqlite"
 
 if [ ! -f "${dbfile}" ]; then
-	err 1 "${MAGENTA}inventorydb not found. You must create them first via misc/updatesql: ${GREEN}${dbfile}${NORMAL}"
+	err 1 "${N1_COLOR}inventorydb not found. You must create them first via misc/updatesql: ${N2_COLOR}${dbfile}${N0_COLOR}"
 fi
 
 . ${sharedir}/jail-arg
diff --git a/sudoexec/jstop b/sudoexec/jstop
--- a/sudoexec/jstop
+++ b/sudoexec/jstop
@@ -15,7 +15,7 @@ EXTHELP="wf_jstop_jstart.html"
 . ${system}
 . ${mdtools}
 
-[ -z "${jname}" -a -z "$*" ] && err 1 "${MAGENTA}No jail specified${NORMAL}"
+[ -z "${jname}" -a -z "$*" ] && err 1 "${N1_COLOR}No jail specified${N0_COLOR}"
 
 [ -n "${inter}" ] && shift
 
@@ -62,34 +62,34 @@ if [ ${jail_num} -gt 1 ]; then
 
 	end_time=$( /bin/date +%s )
 	cbsdlogger NOTICE ${CBSD_APP}: executing for multiple done in $(( end_time - st_time ))s: ${JLIST}
-	err 0 "${MAGENTA}Multiple stop: ${GREEN}done${NORMAL}"
+	err 0 "${N1_COLOR}Multiple stop: ${N2_COLOR}done${N0_COLOR}"
 fi
 
 st_time=$( /bin/date +%s )
 [ -z "${jname}" ] && jname=$( echo ${JLIST} | /usr/bin/awk '{printf $1}' )
 [ -z "${jname}" ] && jname="$1"
-[ -z "${jname}" ] && err 1 "${MAGENTA}Give me jail name${NORMAL}"
+[ -z "${jname}" ] && err 1 "${N1_COLOR}Give me jail name${N0_COLOR}"
 
 . ${jrcconf}
 if [ $? -eq 1 ]; then
-	[ ${sqlreplica} -eq 0 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+	[ ${sqlreplica} -eq 0 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 	remotenode=$( jwhereis ${jname} )
-	[ -z "${remotenode}" ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+	[ -z "${remotenode}" ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 	for i in ${remotenode}; do
-		${ECHO} "${MAGENTA}Remote jstop: ${GREEN}${jname} ${MAGENTA}on${GREEN} ${i}${NORMAL}"
+		${ECHO} "${N1_COLOR}Remote jstop: ${N2_COLOR}${jname} ${N1_COLOR}on${N2_COLOR} ${i}${N0_COLOR}"
 		rexe node=${i} cbsd jstop jname=${jname}
 		if [ $? -eq 0 ]; then
 			# update inventory
-			${ECHO} "${MAGENTA}Updating inventory...${NORMAL}"
+			${ECHO} "${N1_COLOR}Updating inventory...${N0_COLOR}"
 			task mode=new autoflush=2 cbsd retrinv node=${i} tryoffline=1 data=db > /dev/null 2>&1
 		fi
 	done
 	exit 0
 fi
 
-[ ${jid} -eq 0 ] && err 1 "${MAGENTA}Not Running: ${GREEN}${jname}${NORMAL}"
-[ ${status} -eq 3 ] && err 1 "${MAGENTA}Jail in maintenance mode${NORMAL}"
-[ "${emulator}" = "bhyve" ] && err 1 "${MAGENTA}For bhyve jail use: ${GREEN}cbsd bstop ${jname} ${MAGENTA}instead${NORMAL}"
+[ ${jid} -eq 0 ] && err 1 "${N1_COLOR}Not Running: ${N2_COLOR}${jname}${N0_COLOR}"
+[ ${status} -eq 3 ] && err 1 "${N1_COLOR}Jail in maintenance mode${N0_COLOR}"
+[ "${emulator}" = "bhyve" ] && err 1 "${N1_COLOR}For bhyve jail use: ${N2_COLOR}cbsd bstop ${jname} ${N1_COLOR}instead${N0_COLOR}"
 [ -z "${cbsd_queue_name}" ] && cbsd_queue_name="/clonos/jailscontainers/"
 
 . ${distdir}/universe.subr
@@ -102,13 +102,13 @@ fi
 
 # VNC auto stop
 if [ -x "${moduledir}/vncterm.d/cbsdvnc" ]; then
-	${ECHO} "${MAGENTA}Stopping VNC daemon...${GREEN}"
+	${ECHO} "${N1_COLOR}Stopping VNC daemon...${N2_COLOR}"
 	vncterm jname=${jname} mode=stop ||true
 fi
 
 if [ "${vnet}" = "1" -a "${vimage_feature}" = "0" ]; then
-	${ECHO} "${MAGENTA}Jail ${GREEN}${jname}${MAGENTA} have vnet=1 flags but your kernel is not support VIMAGE${NORMAL}"
-	${ECHO} "${MAGENTA}Please recompile kernel with: ${GREEN}options VIMAGE${NORMAL}"
+	${ECHO} "${N1_COLOR}Jail ${N2_COLOR}${jname}${N1_COLOR} have vnet=1 flags but your kernel is not support VIMAGE${N0_COLOR}"
+	${ECHO} "${N1_COLOR}Please recompile kernel with: ${N2_COLOR}options VIMAGE${N0_COLOR}"
 	vnet=0
 fi
 
@@ -120,7 +120,7 @@ if [ ${vnet} -eq 1 ]; then
 
 	interfaces=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT name FROM jailnic | while read _int; do
 		printf "${_int} "
-	done ) || err 1 "${MAGENTA}jstart: error get interfaces name for vnet nic map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}jstart: error get interfaces name for vnet nic map${N0_COLOR}"
 
 	eth_seq=0
 	myepair_list=
@@ -147,7 +147,7 @@ if [ ${vnet} -eq 1 ]; then
 		fi
 		eth_seq=$(( eth_seq + 1 ))
 	done
-	[ -z "${myepair_list}" ] && ${ECHO} "${MAGENTA}Warning: Cant find epair_list for vnet-type jail:${GREEN}${jname}${NORMAL}"
+	[ -z "${myepair_list}" ] && ${ECHO} "${N1_COLOR}Warning: Cant find epair_list for vnet-type jail:${N2_COLOR}${jname}${N0_COLOR}"
 fi
 
 #determine that jail is FreeBSD. Useful for vnet operation in makejconf and
@@ -193,7 +193,7 @@ exec_master_prestop
 exec_prestop
 
 #rctl area
-${ECHO} "${MAGENTA}Stoping jail: ${GREEN}${jname}, parallel timeout=${parallel}${NORMAL}"
+${ECHO} "${N1_COLOR}Stoping jail: ${N2_COLOR}${jname}, parallel timeout=${parallel}${N0_COLOR}"
 jrctl jname=${jname} mode=unset >/dev/null 2>&1
 sleep 2
 
@@ -209,7 +209,7 @@ external_exec_master_script "master_poststop.d"
 exec_poststop
 
 if [ ${vnet} -eq 1 -a -n "${myepair_list}" ]; then
-	printf "${MAGENTA}Destroy epair: ${LYELLOW}"
+	printf "${N1_COLOR}Destroy epair: ${H3_COLOR}"
 
 	# how necessary to make 'ifconfig -vnet ethX' before
 	#no mem leak here and all correct?
@@ -217,7 +217,7 @@ if [ ${vnet} -eq 1 -a -n "${myepair_list}" ]; then
 		printf "${i} "
 		/sbin/ifconfig ${i} destroy
 	done
-	${ECHO} "${NORMAL}"
+	${ECHO} "${N0_COLOR}"
 fi
 
 # waiting for fixed kqueue in upstream
@@ -230,7 +230,7 @@ jaillock="${jailsysdir}/${jname}/locked"
 [ -f "${jaillock}" ] && /bin/rm -f ${jaillock}
 
 if [ "${ver}" != "empty" ]; then
-	${ECHO} "${MAGENTA}Updating: ${GREEN}pkg info${NORMAL}"
+	${ECHO} "${N1_COLOR}Updating: ${N2_COLOR}pkg info${N0_COLOR}"
 	pkg mode=info nomount=1 jname=${jname} > ${jailsysdir}/${jname}/pkg_info
 fi
 
diff --git a/sudoexec/junregister b/sudoexec/junregister
--- a/sudoexec/junregister
+++ b/sudoexec/junregister
@@ -32,10 +32,10 @@ junregister_multi_init()
 		shift $(($OPTIND - 1))
 	done
 
-	[ -z "${task_owner}" ] && err 1 "${MAGENTA}multiple_processing_spawn: empty -o multiple_task_owner${NORMAL}"
+	[ -z "${task_owner}" ] && err 1 "${N1_COLOR}multiple_processing_spawn: empty -o multiple_task_owner${N0_COLOR}"
 
 	. ${distdir}/multiple.subr
-	${ECHO} "${MAGENTA}Hint: Press ${GREEN}'Ctrl+t'${MAGENTA} to see last logfile line for active task${NORMAL}" 1>&2
+	${ECHO} "${N1_COLOR}Hint: Press ${N2_COLOR}'Ctrl+t'${N1_COLOR} to see last logfile line for active task${N0_COLOR}" 1>&2
 	task_id=
 	task_id_cur=
 	task_owner="${task_owner}"
@@ -76,7 +76,7 @@ if [ -n "${jail_list}" ]; then
 
 	task_owner="junregister_multiple_remove"
 	junregister_multi_init -c "${_args}" -o ${task_owner} -n "junregister"
-	err 0 "${MAGENTA}Multiple junregister: ${GREEN}done${NORMAL}"
+	err 0 "${N1_COLOR}Multiple junregister: ${N2_COLOR}done${N0_COLOR}"
 fi
 
 
@@ -86,20 +86,20 @@ if [ $? -eq 1 ]; then
 	# jail can be already unregistered
 	JAILRCCONF="${jailrcconfdir}/rc.conf_${jname}"
 	if [ ! -f "${JAILRCCONF}" ]; then
-		err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+		err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 	else
-		err 1 "${MAGENTA}Already unregistered: ${GREEN}${jname}${NORMAL}"
+		err 1 "${N1_COLOR}Already unregistered: ${N2_COLOR}${jname}${N0_COLOR}"
 	fi
 fi
 
 if [ ${jid} -ne 0 ]; then
-	err 1 "${MAGENTA}Jail is active. Please stop them first: ${GREEN}${jname}${NORMAL}"
+	err 1 "${N1_COLOR}Jail is active. Please stop them first: ${N2_COLOR}${jname}${N0_COLOR}"
 fi
 
 [ -z "${dbfile}" ] && dbfile="${dbdir}/local.sqlite"
 
 if [ ! -f "${dbfile}" ]; then
-	err 1 "${MAGENTA}inventorydb not found. You must create them first via misc/updatesql: ${GREEN}${dbfile}${NORMAL}"
+	err 1 "${N1_COLOR}inventorydb not found. You must create them first via misc/updatesql: ${N2_COLOR}${dbfile}${N0_COLOR}"
 fi
 
 if [ -z "${rcfile}" ]; then
@@ -113,19 +113,19 @@ res=$( replacewdir file0="${JAILRCCONF}" old=${workdir} new="CBSDROOT" )
 _ret=$?
 if [ ${_ret} -ne 0 ]; then
 	/bin/rm -f ${JAILRCCONF}
-	err 1 "${MAGENTA}Error replacewdir for ${JAILRCCONF}: ${res}${NORMAL}"
+	err 1 "${N1_COLOR}Error replacewdir for ${JAILRCCONF}: ${res}${N0_COLOR}"
 fi
 
 if [ -r ${mount_fstab} ]; then
 	res=$( replacewdir file0="${mount_fstab}" old=${workdir} new="CBSDROOT" )
 	_ret=$?
-	[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Error replacewdir for ${mount_fstab}: ${res}${NORMAL}"
+	[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error replacewdir for ${mount_fstab}: ${res}${N0_COLOR}"
 fi
 
 if [ -r {mount_fstab}.local ]; then
 	res=$( replacewdir file0="{mount_fstab}.local" old=${workdir} new="CBSDROOT" )
 	_ret=$?
-	[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Error replacewdir for ${mount_fstab}.local: ${res}${NORMAL}"
+	[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Error replacewdir for ${mount_fstab}.local: ${res}${N0_COLOR}"
 fi
 
 register_delete_full
diff --git a/sudoexec/xstart b/sudoexec/xstart
--- a/sudoexec/xstart
+++ b/sudoexec/xstart
@@ -21,7 +21,7 @@ readconf jail-freebsd-default.conf
 . ${distdir}/xen.subr
 . ${distdir}/vnet.subr 		# get_vm_uplink_interface
 
-[ -z "${jname}" -a -z "$*" ] && err 1 "${MAGENTA}No domain specified${NORMAL}"
+[ -z "${jname}" -a -z "$*" ] && err 1 "${N1_COLOR}No domain specified${N0_COLOR}"
 
 . ${distdir}/fetch.subr
 . ${distdir}/jcreate.subr       # for external_exec_master_script
@@ -78,7 +78,7 @@ start_xen()
 	# profile
 	readconf vm-${vm_os_type}-${vm_os_profile}.conf
 	if [ -z "${vm_profile}" ]; then
-		${ECHO} "${MAGENTA}No such profile: ${GREEN}vm-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+		${ECHO} "${N1_COLOR}No such profile: ${N2_COLOR}vm-${vm_os_type}-${vm_os_profile}.conf${N0_COLOR}"
 		sleep 2
 	fi
 	# re-read jail params and apply personal after profile
@@ -95,7 +95,7 @@ start_xen()
 	if [ "${vm_boot}" = "cd" ]; then
 		init_iso
 		if [ $? -eq 1 ]; then
-			printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
+			printf "${N1_COLOR}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${N0_COLOR}"
 				for i in $( /usr/bin/jot 5 ); do
 					printf "."
 					sleep 1
@@ -121,7 +121,7 @@ start_xen()
 	[ "${vm_os_profile}" = "0" ] && unset vm_os_profile
 
 #	if ! compile_dsk_args; then
-#		${ECHO} "${MAGENTA}No such disk for VMs: ${GREEN}${jname}${NORMAL}"
+#		${ECHO} "${N1_COLOR}No such disk for VMs: ${N2_COLOR}${jname}${N0_COLOR}"
 #		unset dsk_args
 #	fi
 
@@ -131,13 +131,13 @@ start_xen()
 
 	# init nic_args
 	#if ! compile_nic_args ; then
-	#	${ECHO} "${MAGENTA}No such nic for VMs: ${GREEN}${jname}${NORMAL}"
+	#	${ECHO} "${N1_COLOR}No such nic for VMs: ${N2_COLOR}${jname}${N0_COLOR}"
 	#	unset nic_args
 	#fi
 
 	# init console_args
 	#if ! compile_console_args; then
-	#	${ECHO} "${MAGENTA}No such console for VMs: ${GREEN}${jname}${NORMAL}"
+	#	${ECHO} "${N1_COLOR}No such console for VMs: ${N2_COLOR}${jname}${N0_COLOR}"
 	#	unset console_args
 	#fi
 
@@ -238,7 +238,7 @@ EOF
 	fi
 
 	if ! compile_dsk_args ${XENCFG}; then
-		${ECHO} "${MAGENTA}xstart: compile_dsk_args failed for vm: ${GREEN}${jname}${NORMAL}"
+		${ECHO} "${N1_COLOR}xstart: compile_dsk_args failed for vm: ${N2_COLOR}${jname}${N0_COLOR}"
 		unset dsk_args
 	fi
 
@@ -274,7 +274,7 @@ EOF
 
 	echo
 
-	${ECHO} "${MAGENTA}PID: ${GREEN}${vm_pid}${NORMAL}"
+	${ECHO} "${N1_COLOR}PID: ${N2_COLOR}${vm_pid}${N0_COLOR}"
 	cbsdsqlrw local "UPDATE jails SET jid=\"${vm_pid}\" WHERE jname=\"${jname}\""
 
 	# update state_time
@@ -325,7 +325,7 @@ if [ $# -gt 1 -a -z "${jname}" -o -n "${jail_list}" ]; then
 
 	wait_for_fpid -a start -t ${parallel}
 
-	err 0 "${MAGENTA}Multiple bstart: ${GREEN}done${NORMAL}"
+	err 0 "${N1_COLOR}Multiple bstart: ${N2_COLOR}done${N0_COLOR}"
 fi
 
 # MAIN
@@ -345,12 +345,12 @@ readconf xstart.conf
 readconf ${default_profile}
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such domain: ${GREEN}${jname}${NORMAL}"
-[ ${status} -eq 2 ] && err 1 "${MAGENTA}Domain in slave mode. Please ${GREEN}cbsd jswmode mode=master${MAGENTA} first${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such domain: ${N2_COLOR}${jname}${N0_COLOR}"
+[ ${status} -eq 2 ] && err 1 "${N1_COLOR}Domain in slave mode. Please ${N2_COLOR}cbsd jswmode mode=master${N1_COLOR} first${N0_COLOR}"
 
-[ ${jid} -ne 0 ] && err 1 "${MAGENTA}Jail ${jname} already running, jid: ${GREEN}${jid}${NORMAL}"
-[ "${emulator}" != "xen" ] && err 1 "${MAGENTA}Not xen mode${NORMAL}"
-[ -z "${vm_ram}" -o -z "${vm_cpus}" -o -z "${vm_os_type}" ] && err 1 "${MAGENTA}Parameter is mandatory: ${GREEN}vm_ram, vm_cpus, vm_os_type${NORMAL}"
+[ ${jid} -ne 0 ] && err 1 "${N1_COLOR}Jail ${jname} already running, jid: ${N2_COLOR}${jid}${N0_COLOR}"
+[ "${emulator}" != "xen" ] && err 1 "${N1_COLOR}Not xen mode${N0_COLOR}"
+[ -z "${vm_ram}" -o -z "${vm_cpus}" -o -z "${vm_os_type}" ] && err 1 "${N1_COLOR}Parameter is mandatory: ${N2_COLOR}vm_ram, vm_cpus, vm_os_type${N0_COLOR}"
 [ -z "${iso_auto_fetch}" ] && iso_auto_fetch=0
 [ -z "${debug}" ] && debug=0
 
@@ -360,10 +360,10 @@ main_sqlite_local="${jailsysdir}/${jname}/local.sqlite"
 MDFILE=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_path FROM xendsk WHERE jname=\"${jname}\" AND dsk_type=\"vhd\" LIMIT 1 2>/dev/null )
 
 if [ -z "${MDFILE}" ]; then
-	${ECHO} "${MAGENTA}Warning: no any storage device found for this VM${NORMAL}"
+	${ECHO} "${N1_COLOR}Warning: no any storage device found for this VM${N0_COLOR}"
 else
 	if [ ! -f "${data}/${MDFILE}" -a ! -h "${data}/${MDFILE}" ]; then
-		${ECHO} "${MAGENTA}No such ${data}/${MDFILE} but mdsize flags is not null.${NORMAL}"
+		${ECHO} "${N1_COLOR}No such ${data}/${MDFILE} but mdsize flags is not null.${N0_COLOR}"
 
 		# if zfsfeat=1, try scan for zvol
 		[ "${zfsfeat}" != "1" ] && break
@@ -377,7 +377,7 @@ else
 		for lunname in $( /usr/bin/seq 0 10 ); do
 			if [ -r /dev/zvol/${DATA}/bcbsd-${jname}-dsk${lunname}.vhd ]; then
 				/bin/ln -sf /dev/zvol/${DATA}/bcbsd-${jname}-dsk${lunname}.vhd ${data}/dsk${lunname}.vhd
-				${ECHO} "${MAGENTA}Found zvol and create symlink: ${data}/dsk${lunname}.vhd -> ${DATA}/bcbsd-${jname}-dsk${lunname}.vhd"
+				${ECHO} "${N1_COLOR}Found zvol and create symlink: ${data}/dsk${lunname}.vhd -> ${DATA}/bcbsd-${jname}-dsk${lunname}.vhd"
 			fi
 		done
 	fi
@@ -399,8 +399,8 @@ if [ ${status} -eq 3 ]; then
 	if [ "${comment}" = "Stopping_VM" ]; then
 		jswmode jname=${jname} mode=master comment='0'
 	else
-		${ECHO} "${MAGENTA}Xen in maintenance: ${GREEN}${comment}${NORMAL}"
-		err 1 "${MAGENTA}Please finish maintenance and switch mode via: ${GREEN}jswmode jname=${jname} mode=master comment='0'${NORMAL}"
+		${ECHO} "${N1_COLOR}Xen in maintenance: ${N2_COLOR}${comment}${N0_COLOR}"
+		err 1 "${N1_COLOR}Please finish maintenance and switch mode via: ${N2_COLOR}jswmode jname=${jname} mode=master comment='0'${N0_COLOR}"
 	fi
 fi
 
diff --git a/tools/attachzfs b/tools/attachzfs
--- a/tools/attachzfs
+++ b/tools/attachzfs
@@ -16,8 +16,8 @@ set +e
 . ${cbsdinit}
 
 [ ${zfsfeat} -eq 0 ] && exit
-[ -n "${fstab}" -a ! -f "${fstab}" ] && err 1 "${MAGENTA}attachzfs: ${fstab} does not exist${NORMAL}"
-[ -z "${zfs}" -a -z "${fstab}" ] && err 1 "${MAGENTA}attachzfs: ${GREEN}zfs=${MAGENTA} or ${GREEN}fstab= ${MAGENTA} is necessary${NORMAL}"
+[ -n "${fstab}" -a ! -f "${fstab}" ] && err 1 "${N1_COLOR}attachzfs: ${fstab} does not exist${N0_COLOR}"
+[ -z "${zfs}" -a -z "${fstab}" ] && err 1 "${N1_COLOR}attachzfs: ${N2_COLOR}zfs=${N1_COLOR} or ${N2_COLOR}fstab= ${N1_COLOR} is necessary${N0_COLOR}"
 
 zfs_check_and_attach()
 {
@@ -46,7 +46,7 @@ zfs_check_and_attach()
 /sbin/zfs set mountpoint=${_mp} ${1}
 EOF
 	else
-		${ECHO} "${MAGENTA}attachzfs error: FS already mounted, please unmount from hoster before attaching to jail: ${GREEN}${1}${NORMAL}"
+		${ECHO} "${N1_COLOR}attachzfs error: FS already mounted, please unmount from hoster before attaching to jail: ${N2_COLOR}${1}${N0_COLOR}"
 	fi
 
 	return 2
@@ -66,19 +66,19 @@ mount_via_fstab()
 		zfs_check_and_attach ${_device} ${_mountpt}
 		case $? in
 			0)
-				${ECHO} "${MAGENTA}attachzfs: ${GREEN}${_device}${MAGENTA} is not valid ZFS filesystem${NORMAL}"
+				${ECHO} "${N1_COLOR}attachzfs: ${N2_COLOR}${_device}${N1_COLOR} is not valid ZFS filesystem${N0_COLOR}"
 				;;
 			1)
-				${ECHO} "${MAGENTA}attachzfs: ${GREEN}${_device}${MAGENTA} already mounted. Please reset mount point via: ${GREEN}zfs set mountpoint=none ${_device}${NORMAL}"
+				${ECHO} "${N1_COLOR}attachzfs: ${N2_COLOR}${_device}${N1_COLOR} already mounted. Please reset mount point via: ${N2_COLOR}zfs set mountpoint=none ${_device}${N0_COLOR}"
 				;;
 			2)
-				${ECHO} "${MAGENTA}attachzfs: attached: ${GREEN}${_device}${NORMAL}"
+				${ECHO} "${N1_COLOR}attachzfs: attached: ${N2_COLOR}${_device}${N0_COLOR}"
 				;;
 			3)
-				${ECHO} "${MAGENTA}attachzfs: empty mount point for: ${GREEN}${_device}${NORMAL}"
+				${ECHO} "${N1_COLOR}attachzfs: empty mount point for: ${N2_COLOR}${_device}${N0_COLOR}"
 				;;
 			*)
-				${ECHO} "${MAGENTA}attachzfs: unknown error while test for zfsfs ${zfs}. Skip${NORMAL}"
+				${ECHO} "${N1_COLOR}attachzfs: unknown error while test for zfsfs ${zfs}. Skip${N0_COLOR}"
 				;;
 		esac
 	done
@@ -88,8 +88,8 @@ mount_via_fstab()
 }
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}attachzfs: no such jail: ${GREEN}${jname}${NORMAL}"
-[ ${status} -ne 1 ] && err 1 "${MAGENTA}attachzfs: jail is not running: ${GREEN}${jname}${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}attachzfs: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+[ ${status} -ne 1 ] && err 1 "${N1_COLOR}attachzfs: jail is not running: ${N2_COLOR}${jname}${N0_COLOR}"
 
 . ${zfstool}
 [ -n "${fstab}" ] && mount_via_fstab
diff --git a/tools/bhyvecfg-passhtu-tui b/tools/bhyvecfg-passhtu-tui
--- a/tools/bhyvecfg-passhtu-tui
+++ b/tools/bhyvecfg-passhtu-tui
@@ -29,7 +29,7 @@ dialog_menu_main()
 			mark=" "
 		fi
 		echo "'${id}'	'[${mark}] vhid=${vhid} advskew=${advskew}'	'iface=${interface};pass=${pass};state=${pass}'"
-	done ) || err 1 "${MAGENTA}Error while create vhid map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create vhid map${N0_COLOR}"
 
 	menu_list="${menu_list} '-'	'-'	''"
 
diff --git a/tools/createhd b/tools/createhd
--- a/tools/createhd
+++ b/tools/createhd
@@ -93,16 +93,16 @@ prefix=$( substr --pos=0 --len=1 --str=${dsk_path} )
 
 if [ ${named_disk} -eq 1 ]; then
 	prefix=$( substr --pos=0 --len=3 --str=${dsk_path} )
-	[ "${prefix}" != "dsk" ] && err 1 "${MAGENTA}Non-FS-based path must be named as: ${GREEN}dskX${NORMAL}"
+	[ "${prefix}" != "dsk" ] && err 1 "${N1_COLOR}Non-FS-based path must be named as: ${N2_COLOR}dskX${N0_COLOR}"
 fi
 
-[ ${named_disk} -eq 0 -a -r "${dsk_path}" ] && err 1 "${MAGENTA}File already exist in FS: ${GREEN}${dsk_path}${NORMAL}"
+[ ${named_disk} -eq 0 -a -r "${dsk_path}" ] && err 1 "${N1_COLOR}File already exist in FS: ${N2_COLOR}${dsk_path}${N0_COLOR}"
 
 if [ ${named_disk} -eq 1 -a -z "${jname}" ]; then
 
 	case "${zfsfeat}" in
 		0)
-			err 1 "${MAGENTA}For non-FS-based path (path not started from /), ${GREEN}jname=${MAGENTA} is mandatory${NORMAL}"
+			err 1 "${N1_COLOR}For non-FS-based path (path not started from /), ${N2_COLOR}jname=${N1_COLOR} is mandatory${N0_COLOR}"
 			;;
 		1)
 			jname="CBSDSYS"
@@ -116,8 +116,8 @@ fi
 
 if [ ${named_disk} -eq 1 -a "${jname}" != "CBSDSYS" ]; then
 	. ${jrcconf}
-	[ $? -eq 1 ] && err 1 "${MAGENTA}No such vm: ${GREEN}${jname}${NORMAL}"
-	[ "${emulator}" != "bhyve" ] && err 1 "${MAGENTA}Not in bhyve mode${NORMAL}"
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}No such vm: ${N2_COLOR}${jname}${N0_COLOR}"
+	[ "${emulator}" != "bhyve" ] && err 1 "${N1_COLOR}Not in bhyve mode${N0_COLOR}"
 	full_path="${data}/${dsk_path}.vhd"
 fi
 
@@ -129,13 +129,13 @@ case ${named_disk} in
 		cbsdsqlrw storage_media "INSERT INTO media ( name, path, type, jname, size ) VALUES ( \"${name}\", \"${dsk_path}\", \"${type}\", \"${jname}\", \"${size}\" )"
 		;;
 	1)
-		[ -r "${full_path}" -a -h "${full_path}" ] && err 1 "${MAGENTA}Disk file already exist: ${GREEN}${full_path}${NORMAL}"
+		[ -r "${full_path}" -a -h "${full_path}" ] && err 1 "${N1_COLOR}Disk file already exist: ${N2_COLOR}${full_path}${N0_COLOR}"
 
 		select_by_path ${full_path}
-		[ $? -eq 0 ] && err 1 "${MAGENTA}Path already registered: ${GREEN}${vm_res}${NORMAL}"
+		[ $? -eq 0 ] && err 1 "${N1_COLOR}Path already registered: ${N2_COLOR}${vm_res}${N0_COLOR}"
 
 		if ! bhyve_create_dsk -p ${full_path} -s ${size} -f 1; then
-			err 1 "${MAGENTA}bhyve_create_dsk from createhd failed for: ${GREEN}${full_path}${NORMAL}"
+			err 1 "${N1_COLOR}bhyve_create_dsk from createhd failed for: ${N2_COLOR}${full_path}${N0_COLOR}"
 		fi
 
 		;;
diff --git a/tools/expose b/tools/expose
--- a/tools/expose
+++ b/tools/expose
@@ -26,7 +26,7 @@ show_all_expose()
 		myjail=$( echo ${_file} | /usr/bin/sed -Ees:${jailsysdir}/::g -es:/expose.sqlite::g )
 		jstatus jname=${myjail} > /dev/null 2>&1
 		[ $? -eq 0 ] && continue
-		${ECHO} "${MAGENTA}Expose for ${GREEN}${myjail}${MAGENTA}:${NORMAL}"
+		${ECHO} "${N1_COLOR}Expose for ${N2_COLOR}${myjail}${N1_COLOR}:${N0_COLOR}"
 		fw_expose_list ${_file}
 	done
 }
@@ -57,15 +57,15 @@ get_first_fwnum()
 		break
 	done )
 
-	[ -z "${tmp}" ] && err 1 "${MAGENTA}Unable to determine first fwnum for expose${NORMAL}"
-	[ ${tmp} -eq ${fwexpose_end} ] && err 1 "${MAGENTA}No free ipfw num for expose in expose range: ${GREEN}${fwexpose_st} - ${fwexpose_end}${NORMAL}"
+	[ -z "${tmp}" ] && err 1 "${N1_COLOR}Unable to determine first fwnum for expose${N0_COLOR}"
+	[ ${tmp} -eq ${fwexpose_end} ] && err 1 "${N1_COLOR}No free ipfw num for expose in expose range: ${N2_COLOR}${fwexpose_st} - ${fwexpose_end}${N0_COLOR}"
 
 	fwnum="${tmp}"
 }
 
 pf_del()
 {
-	[ -z "${COMMENT}" ] && ${ECHO} "${MAGENTA}No comment in pf_del${NORMAL}" && return 1
+	[ -z "${COMMENT}" ] && ${ECHO} "${N1_COLOR}No comment in pf_del${N0_COLOR}" && return 1
 
 	if [ -f "${etcdir}/pfnat.conf" ]; then
 		if ${GREP_CMD} "${COMMENT}" ${etcdir}/pfnat.conf >/dev/null 2>&1; then
@@ -83,13 +83,13 @@ fw_expose_add()
 	res=$( /usr/bin/nc -w1 -z ${inaddr} ${in} 2>/dev/null )
 
 	if [ $? -eq 0 ]; then
-		${ECHO} "${MAGENTA}Port already in use on ${inaddr}: ${GREEN}${in}${NORMAL}"
+		${ECHO} "${N1_COLOR}Port already in use on ${inaddr}: ${N2_COLOR}${in}${N0_COLOR}"
 		return 0
 	fi
 
 	[ -f ${ftmpdir}/${jname}-expose_fwnum ] && fwnum=$( /bin/cat ${ftmpdir}/${jname}-expose_fwnum )
 
-	${ECHO} "${MAGENTA}CBSD Expose for ${jname}: ${GREEN}${in} -> ${out} (${proto})${NORMAL}"
+	${ECHO} "${N1_COLOR}CBSD Expose for ${jname}: ${N2_COLOR}${in} -> ${out} (${proto})${N0_COLOR}"
 
 	case "${nat_enable}" in
 		pf)
@@ -158,7 +158,7 @@ fw_expose_delete()
 	cbsdsqlrw ${exposefile} "DELETE FROM expose WHERE pin=$in AND pout=$out AND proto=\"${proto}\" AND inaddr=\"${inaddr}\" AND outaddr=\"${outaddr}\""
 
 	if [ ! -f ${ftmpdir}/${jname}-expose_fwnum ]; then
-		${ECHO} "${MAGENTA}No ${ftmpdir}/${jname}-expose_fwnum: skip for deletion expose rule${NORMAL}"
+		${ECHO} "${N1_COLOR}No ${ftmpdir}/${jname}-expose_fwnum: skip for deletion expose rule${N0_COLOR}"
 		return 0
 	else
 		fwnum=$( /bin/cat ${ftmpdir}/${jname}-expose_fwnum )
@@ -186,16 +186,16 @@ fi
 [ -z "${jname}" ] && err 1 "Give me jname"
 
 . ${jrcconf}
-[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+[ $? -eq 1 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 [ -z "${proto}" ] && proto="tcp"
 [ -z "${inaddr}" ] && inaddr="nodeip"  # "nodeip"  - reserverd word for $nodeip variable
 if [ "${nat_enable}" = "ipfw" ]; then
-	[ "$( /sbin/sysctl -qn net.inet.ip.fw.enable 2>/dev/null )" != "1" ] && err 1 "${MAGENTA}IPFW is not enabled${NORMAL}"
+	[ "$( /sbin/sysctl -qn net.inet.ip.fw.enable 2>/dev/null )" != "1" ] && err 1 "${N1_COLOR}IPFW is not enabled${N0_COLOR}"
 fi
 # init ipfw number
 get_first_fwnum
-[ -z "${fwnum}" ] && err 1 "${MAGENTA}Empty fwnum variable${NORMAL}"
+[ -z "${fwnum}" ] && err 1 "${N1_COLOR}Empty fwnum variable${N0_COLOR}"
 
 if [ -z "${outaddr}" ]; then
 	jip=$( get_first_ip )
@@ -203,7 +203,7 @@ else
 	jip="${outaddr}"
 fi
 
-[ -z "${jip}" ] && err 1 "${MAGENTA}Unable to determine jail ip${NORMAL}"
+[ -z "${jip}" ] && err 1 "${N1_COLOR}Unable to determine jail ip${N0_COLOR}"
 
 exposefile="${jailsysdir}/${jname}/expose.sqlite"
 
@@ -234,8 +234,8 @@ case "${mode}" in
 		;;
 esac
 
-[ -z "${in}" ] && err 1 "${MAGENTA}Empty ${GREEN}in${NORMAL}"
-[ -z "${out}" ] && err 1 "${MAGENTA}Empty ${GREEN}out${NORMAL}"
+[ -z "${in}" ] && err 1 "${N1_COLOR}Empty ${N2_COLOR}in${N0_COLOR}"
+[ -z "${out}" ] && err 1 "${N1_COLOR}Empty ${N2_COLOR}out${N0_COLOR}"
 
 COMMENT="// Setup by CBSD expose: ${proto}-${out}-${jname}"
 
@@ -249,6 +249,6 @@ case "${mode}" in
 		fw_expose_apply
 		;;
 	*)
-		err 1 "${MAGENTA}Unknown mode: ${GREEN}${mode}${NORMAL}"
+		err 1 "${N1_COLOR}Unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
 		;;
 esac
diff --git a/tools/media b/tools/media
--- a/tools/media
+++ b/tools/media
@@ -40,7 +40,7 @@ myheader=$( echo ${mydisplay} | /usr/bin/tr '[:lower:]' '[:upper:]' )
 
 show_header()
 {
-	local _header="${WHITE}${BOLD}${myheader}${NORMAL}"
+	local _header="${H1_COLOR}${BOLD}${myheader}${N0_COLOR}"
 	[ ${header} -eq 1 ] && ${ECHO} "${_header}"
 }
 
@@ -192,7 +192,7 @@ populate_output_data()
 				;;
 		esac
 		if [ -z "${_status}" ]; then
-			_status="${NORMAL}${_val}"
+			_status="${N0_COLOR}${_val}"
 		else
 			_status="${_status} ${_val}"
 		fi
@@ -209,9 +209,9 @@ show_data_from_sql()
 
 	cbsdsqlro storage_media ${_sql} | while read name path type jname size; do
 		populate_output_data
-		printf "${GREEN}"
+		printf "${N2_COLOR}"
 		printf "${_status}"
-		printf "${NORMAL}\n"
+		printf "${N0_COLOR}\n"
 	done
 
 	IFS=" "
@@ -297,7 +297,7 @@ check_protected()
 	protected=$( cbsdsqlro local SELECT protected FROM ${_table} WHERE jname=\"${jname}\" )
 
 	[ -z "${protected}" ] && protected="0"	# by default - is not protected
-	[ "${protected}" = "1" ] && err 1 "${MAGENTA}Environment is protected to delete: ${GREEN}${jname}${NORMAL}"
+	[ "${protected}" = "1" ] && err 1 "${N1_COLOR}Environment is protected to delete: ${N2_COLOR}${jname}${N0_COLOR}"
 }
 
 
@@ -305,9 +305,9 @@ storage_attach()
 {
 	local _data_dir_path _tmp_dir_path= _tmp_dsk_path= _res
 
-	[ -z "${name}" ] && err 1 "${MAGENTA}media: ${GREEN}name=${NORMAL}"
-	[ -z "${path}" ] && err 1 "${MAGENTA}media: ${GREEN}path=${NORMAL}"
-	[ -z "${jname}" ] && err 1 "${MAGENTA}Give me ${GREEN}jname=${NORMAL}"
+	[ -z "${name}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}name=${N0_COLOR}"
+	[ -z "${path}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}path=${N0_COLOR}"
+	[ -z "${jname}" ] && err 1 "${N1_COLOR}Give me ${N2_COLOR}jname=${N0_COLOR}"
 
 	local attached_to_name dsk_path dsk_name
 	local mydb virtio_type already_attached_to_me
@@ -326,11 +326,11 @@ storage_attach()
 
 	# todo: shared disk
 	if [ "${type}" = "hdd" ]; then
-		[ -n "${attached_to_jname}" ] && err 1 "${MAGENTA}disk ${name} with path ${path} already attached to: ${GREEN}${test_jname}${NORMAL}"
+		[ -n "${attached_to_jname}" ] && err 1 "${N1_COLOR}disk ${name} with path ${path} already attached to: ${N2_COLOR}${test_jname}${N0_COLOR}"
 		select_by_path "${by_path}"
-		[ $? -ne 0 ] && err 1 "${MAGENTA}Path not exist for jname by path ${by_path}: ${GREEN}${path}${NORMAL}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}Path not exist for jname by path ${by_path}: ${N2_COLOR}${path}${N0_COLOR}"
 		select_by_name "${by_name}"
-		[ $? -ne 0 ] && err 1 "${MAGENTA}Name not exist for jname by name ${by_name}: ${GREEN}${name}${NORMAL}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}Name not exist for jname by name ${by_name}: ${N2_COLOR}${name}${N0_COLOR}"
 	fi
 
 	# save variables before rcconf init
@@ -338,11 +338,11 @@ storage_attach()
 	dsk_name="${name}"
 
 	. ${jrcconf}
-	[ $? -eq 1 ] && err 1 "${MAGENTA}attachzfs: no such jail: ${GREEN}${jname}${NORMAL}"
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}attachzfs: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 	if [ -z "${type}" ]; then
 		type=$( imgtype path=${dsk_path} 2>&1 )
-		${ECHO} "${MAGENTA}media: auto-detected image type for ${dsk_path}: ${GREEN}${type}${NORMAL}"
+		${ECHO} "${N1_COLOR}media: auto-detected image type for ${dsk_path}: ${N2_COLOR}${type}${N0_COLOR}"
 	fi
 
 	case "${type}" in
@@ -361,7 +361,7 @@ storage_attach()
 			fi
 			_res=$( cbsdsqlro ${mydb} SELECT dsk_path FROM bhyvedsk WHERE jname=\"${jname}\" AND dsk_path=\"${_tmp_dsk_path}\" LIMIT 1 2>/dev/null )
 			if [ -n "${_res}" ]; then
-				${ECHO} "${MAGENTA}dsk_path already exist for ${jname}: ${GREEN}${_tmp_dsk_path}${NORMAL}"
+				${ECHO} "${N1_COLOR}dsk_path already exist for ${jname}: ${N2_COLOR}${_tmp_dsk_path}${N0_COLOR}"
 				return 1
 			fi
 			cbsdsqlrw ${mydb} "INSERT INTO ${emulator}dsk ( jname,dsk_controller,dsk_path,dsk_slot ) VALUES ( \"${jname}\",\"${virtio_type}\",\"${_tmp_dsk_path}\","0" )"
@@ -371,7 +371,7 @@ storage_attach()
 	# test for already attached
 	already_attached_to_me=$( cbsdsqlro storage_media SELECT jname FROM media WHERE path=\"${dsk_path}\" AND name=\"${dsk_name}\" AND jname=\"${jname}\" LIMIT 1 )
 
-	[ -n "${already_attached_to_me}" ] && err 1 "${MAGENTA}storage with name:${name} and path:${path} already attached for instance: ${GREEN}${jname}${NORMAL}"
+	[ -n "${already_attached_to_me}" ] && err 1 "${N1_COLOR}storage with name:${name} and path:${path} already attached for instance: ${N2_COLOR}${jname}${N0_COLOR}"
 
 	if [ -n "${attached_to_jname}" ]; then
 		#shared disk: INSERT
@@ -394,15 +394,15 @@ storage_attach()
 
 storage_detach()
 {
-	[ -z "${name}" ] && err 1 "${MAGENTA}media: ${GREEN}name=${NORMAL}"
-	[ -z "${path}" ] && err 1 "${MAGENTA}media: ${GREEN}path=${NORMAL}"
-	[ -z "${jname}" ] && err 1 "${MAGENTA}Give me ${GREEN}jname=${NORMAL}"
+	[ -z "${name}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}name=${N0_COLOR}"
+	[ -z "${path}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}path=${N0_COLOR}"
+	[ -z "${jname}" ] && err 1 "${N1_COLOR}Give me ${N2_COLOR}jname=${N0_COLOR}"
 
 	local dsk_path dsk_name
 	local mydb virtio_type already_attached_to_me
 
 	attached_to_me=$( cbsdsqlro storage_media SELECT jname FROM media WHERE path=\"${path}\" AND name=\"${name}\" AND jname=\"${jname}\" LIMIT 1 )
-	[ "${attached_to_me}" != "${jname}" ] && err 1 "${MAGENTA}disk ${name} with name:${name} and path:${path} is not attached to: ${GREEN}${jname}${NORMAL}"
+	[ "${attached_to_me}" != "${jname}" ] && err 1 "${N1_COLOR}disk ${name} with name:${name} and path:${path} is not attached to: ${N2_COLOR}${jname}${N0_COLOR}"
 
 	attached_to_jname=$( cbsdsqlro storage_media SELECT jname FROM media WHERE path=\"${path}\" AND name=\"${name}\" AND jname!=\"${jname}\" LIMIT 1 )
 
@@ -421,7 +421,7 @@ storage_detach()
 	dsk_name="${name}"
 
 	. ${jrcconf}
-	[ $? -eq 1 ] && err 1 "${MAGENTA}attachzfs: no such jail: ${GREEN}${jname}${NORMAL}"
+	[ $? -eq 1 ] && err 1 "${N1_COLOR}attachzfs: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 	case "${type}" in
 		iso|shared)
@@ -487,7 +487,7 @@ try_to_rm()
 	local path="${1}"
 	local _vm_list
 
-	[ -z "${path}" ] && err 1 "${MAGENTA}media: try_to_rm: empty path${NORMAL}"
+	[ -z "${path}" ] && err 1 "${N1_COLOR}media: try_to_rm: empty path${N0_COLOR}"
 
 	. ${zfstool}
 	if is_getzvol ${path}; then
@@ -496,12 +496,12 @@ try_to_rm()
 
 			_vm_list=$( which_vm_depens_on_zvol ${is_zvol} )
 
-			[ -n "${_vm_list}" ] && err 1 "${MAGENTA}Current vm depends from ${is_zvol}: ${GREEN}${_vm_list}${NORMAL}"
+			[ -n "${_vm_list}" ] && err 1 "${N1_COLOR}Current vm depends from ${is_zvol}: ${N2_COLOR}${_vm_list}${N0_COLOR}"
 
 			# zvol exist
 			/sbin/zfs destroy ${is_zvol}
 			_ret=$?
-			[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Unable to destroy zvol, please remove it by hand: ${GREEN}${is_zvol}${NORMAL}"
+			[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}Unable to destroy zvol, please remove it by hand: ${N2_COLOR}${is_zvol}${N0_COLOR}"
 		fi
 	fi
 	/bin/rm -f ${path}
@@ -523,36 +523,36 @@ fi
 case "${mode}" in
 	attach)
 		storage_attach
-		err 0 "${MAGENTA}Attached to: ${GREEN}${jname}${NORMAL}"
+		err 0 "${N1_COLOR}Attached to: ${N2_COLOR}${jname}${N0_COLOR}"
 		;;
 	detach)
 		storage_detach
-		err 0 "${MAGENTA}Detach to: ${GREEN}${jname}${NORMAL}"
+		err 0 "${N1_COLOR}Detach to: ${N2_COLOR}${jname}${N0_COLOR}"
 		;;
 	eject)
-		[ -z "${jname}" ] && err 1 "${MAGENTA}Please specify ${GREEN}jname=${NORMAL}"
+		[ -z "${jname}" ] && err 1 "${N1_COLOR}Please specify ${N2_COLOR}jname=${N0_COLOR}"
 		eject
-		err 0 "${MAGENTA}All CD/ISO ejected: ${GREEN}${jname}${NORMAL}"
+		err 0 "${N1_COLOR}All CD/ISO ejected: ${N2_COLOR}${jname}${N0_COLOR}"
 		;;
 	list)
 		show_local | /usr/bin/column -t
 		;;
 	get)
-		[ -z "${name}" -a -z "${path}" ] && err 1 "${MAGENTA}media: ${GREEN}name=${MAGENTA} or ${GREEN}path=${MAGENTA} value is reguired${NORMAL}"
-		[ -n "${name}" -a -n "${path}" ] && err 1 "${MAGENTA}media: Please specify ${GREEN}name=${MAGENTA} OR ${GREEN}path=${MAGENTA}, not both${NORMAL}"
+		[ -z "${name}" -a -z "${path}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}name=${N1_COLOR} or ${N2_COLOR}path=${N1_COLOR} value is reguired${N0_COLOR}"
+		[ -n "${name}" -a -n "${path}" ] && err 1 "${N1_COLOR}media: Please specify ${N2_COLOR}name=${N1_COLOR} OR ${N2_COLOR}path=${N1_COLOR}, not both${N0_COLOR}"
 		[ -n "${name}" ] && select_by_name
 		[ -n "${path}" ] && select_by_path
 		err 0 "${vm_res}"
 		;;
 	register)
-		[ -z "${name}" ] && err 1 "${MAGENTA}media: ${GREEN}name=${MAGENTA} is mandatory${NORMAL}"
-		[ -z "${path}" ] && err 1 "${MAGENTA}media: ${GREEN}path=${MAGENTA} is mandatory${NORMAL}"
-		select_by_path && err 1 "${MAGENTA}Path already exist for: ${GREEN}${vm_res}${NORMAL}"
-		select_by_name && err 1 "${MAGENTA}Name already exist for: ${GREEN}${vm_res}${NORMAL}"
+		[ -z "${name}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}name=${N1_COLOR} is mandatory${N0_COLOR}"
+		[ -z "${path}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}path=${N1_COLOR} is mandatory${N0_COLOR}"
+		select_by_path && err 1 "${N1_COLOR}Path already exist for: ${N2_COLOR}${vm_res}${N0_COLOR}"
+		select_by_name && err 1 "${N1_COLOR}Name already exist for: ${N2_COLOR}${vm_res}${N0_COLOR}"
 
 		if [ -z "${type}" ]; then
 			type=$( imgtype path=${path} 2>&1 )
-			${ECHO} "${MAGENTA}media: auto-detected image type for ${path}: ${GREEN}${type}${NORMAL}"
+			${ECHO} "${N1_COLOR}media: auto-detected image type for ${path}: ${N2_COLOR}${type}${N0_COLOR}"
 		fi
 
 		[ -z "${jname}" ] && jname="-"
@@ -564,7 +564,7 @@ case "${mode}" in
 			[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} cmd=refresh
 		fi
 
-		err 0 "${MAGENTA}Updated${NORMAL}"
+		err 0 "${N1_COLOR}Updated${N0_COLOR}"
 		;;
 	unregister)
 		[ -z "${type}" ] && type="hdd"
@@ -572,7 +572,7 @@ case "${mode}" in
 
 		check_protected
 
-		[ -z "${name}" -a -z "${path}" ] && err 1 "${MAGENTA}media: ${GREEN}name=${MAGENTA} or ${GREEN}path=${MAGENTA} value is reguired${NORMAL}"
+		[ -z "${name}" -a -z "${path}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}name=${N1_COLOR} or ${N2_COLOR}path=${N1_COLOR} value is reguired${N0_COLOR}"
 
 		if [ -n "${name}" -a -n "${path}" ]; then
 			unregister_or_remove -n "${name}" -p "${path}" -t "${type}" -j "${jname}"
@@ -587,7 +587,7 @@ case "${mode}" in
 			[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} cmd=refresh
 		fi
 
-		err 0 "${MAGENTA}Unregistered${NORMAL}"
+		err 0 "${N1_COLOR}Unregistered${N0_COLOR}"
 		;;
 	flushall)
 		# test for protected by select jname ???
@@ -598,15 +598,15 @@ case "${mode}" in
 			[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} cmd=refresh
 		fi
 
-		err 0 "${MAGENTA}Flushed${NORMAL}"
+		err 0 "${N1_COLOR}Flushed${N0_COLOR}"
 		;;
 	delete|remove)
-		[ -z "${type}" ] && err 1 "${GREEN}type= ${MAGENTA}is mandatory${NORMAL}"
+		[ -z "${type}" ] && err 1 "${N2_COLOR}type= ${N1_COLOR}is mandatory${N0_COLOR}"
 		[ -z "${jname}" ] && jname="-"
 
 		check_protected
 
-		[ -z "${name}" -a -z "${path}" ] && err 1 "${MAGENTA}media: ${GREEN}name=${MAGENTA} or ${GREEN}path=${MAGENTA} value is reguired${NORMAL}"
+		[ -z "${name}" -a -z "${path}" ] && err 1 "${N1_COLOR}media: ${N2_COLOR}name=${N1_COLOR} or ${N2_COLOR}path=${N1_COLOR} value is reguired${N0_COLOR}"
 
 		if [ -n "${name}" -a -n "${path}" ]; then
 
@@ -631,7 +631,7 @@ case "${mode}" in
 			fi
 		fi
 
-		[ -z "${path}" ] && err 1 "${MAGENTA}media delete: empty path variable${NORMAL}"
+		[ -z "${path}" ] && err 1 "${N1_COLOR}media delete: empty path variable${N0_COLOR}"
 
 		short_dsk_path=$( /usr/bin/basename ${path} )
 
@@ -653,11 +653,11 @@ case "${mode}" in
 			[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} cmd=refresh
 		fi
 
-		err 0 "${MAGENTA}Deleted${NORMAL}"
+		err 0 "${N1_COLOR}Deleted${N0_COLOR}"
 		;;
 	deleteall|removeall)
 		for i in $( cbsdsqlro storage_media SELECT path FROM media WHERE type != \"hdd\" ); do
-			${ECHO} "${MAGENTA}removing: ${GREEN}${i}${MAGENTA} ...${NORMAL}"
+			${ECHO} "${N1_COLOR}removing: ${N2_COLOR}${i}${N1_COLOR} ...${N0_COLOR}"
 			media mode=remove path="${i}" type="iso"
 		done
 		exit 0
@@ -668,7 +668,7 @@ case "${mode}" in
 		;;
 	dump)
 		# export media data to ascii file
-		[ ! -r ${dbdir}/storage_media.sqlite ] && err 1 "${MAGENTA}Not readable: ${GREEN}${dbdir}/storage_media.sqlite${NORMAL}"
+		[ ! -r ${dbdir}/storage_media.sqlite ] && err 1 "${N1_COLOR}Not readable: ${N2_COLOR}${dbdir}/storage_media.sqlite${N0_COLOR}"
 		if [ -n "${jname}" ]; then
 			_sql="SELECT name,path,type,size,jname FROM media WHERE jname=\"${jname}\""
 		else
@@ -687,7 +687,7 @@ case "${mode}" in
 		;;
 	*)
 
-		err 1 "${MAGENTA}Unknown mode: ${GREEN}${mode}${NORMAL}"
+		err 1 "${N1_COLOR}Unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
 		;;
 esac
 
diff --git a/tools/naton b/tools/naton
--- a/tools/naton
+++ b/tools/naton
@@ -17,12 +17,12 @@ ADDHELP="nat= name of framework. default in inventory config\n"
 check_nat_ip()
 {
 	natoff nat=all
-	/sbin/ping -c1 -S ${natip} ${natip} > /dev/null 2>&1 || err 1 "${MAGENTA}Cant assign nat address: ${GREEN}${natip}${MAGENTA}. Probably wrong ip. Nat cfg skipped${NORMAL}"
+	/sbin/ping -c1 -S ${natip} ${natip} > /dev/null 2>&1 || err 1 "${N1_COLOR}Cant assign nat address: ${N2_COLOR}${natip}${N1_COLOR}. Probably wrong ip. Nat cfg skipped${N0_COLOR}"
 }
 
 [ "${nat_enable}" = "0" ] && exit 0
 # forwarding for NAT mode
-${ECHO} "${MAGENTA}CBSD: Enable IP forwarding for NAT service${NORMAL}"
+${ECHO} "${N1_COLOR}CBSD: Enable IP forwarding for NAT service${N0_COLOR}"
 /sbin/sysctl net.inet6.ip6.forwarding=1 >/dev/null
 /sbin/sysctl net.inet.ip.forwarding=1 >/dev/null
 
@@ -44,7 +44,7 @@ case ${_ret} in
 		_extiface="${natip}"
 		natip=$( getip-by-nics nic=${_extiface} 2>/dev/null )
 		if [ $? -ne 0 ]; then
-			${ECHO} "${MAGENTA}Unable to determine first IP for nic: ${GREEN}${_extiface}${NORMAL}"
+			${ECHO} "${N1_COLOR}Unable to determine first IP for nic: ${N2_COLOR}${_extiface}${N0_COLOR}"
 			return 1
 		fi
 		ok="${nat_enable}" # used by make_nat
@@ -54,14 +54,14 @@ esac
 
 case "${nat_enable}" in
 	"pf")
-		[ ! -f "${etcdir}/pfnat.conf" ] && err 1 "${MAGENTA}No pfnat.conf. run ${GREEN}cbsd natcfg${MAGENTA} first${NORMAL}"
+		[ ! -f "${etcdir}/pfnat.conf" ] && err 1 "${N1_COLOR}No pfnat.conf. run ${N2_COLOR}cbsd natcfg${N1_COLOR} first${N0_COLOR}"
 		/sbin/kldstat -qm pf || /sbin/kldload pf
 		check_nat_ip
 		${PFCTL_CMD} -f ${etcdir}/pfnat.conf
 		${PFCTL_CMD} -e
 	;;
 	"ipfw")
-		[ ! -f "${etcdir}/ipfw.conf" ] && err 1 "${MAGENTA}No ipfw.conf. run ${GREEN}cbsd natcfg${MAGENTA} first${NORMAL}"
+		[ ! -f "${etcdir}/ipfw.conf" ] && err 1 "${N1_COLOR}No ipfw.conf. run ${N2_COLOR}cbsd natcfg${N1_COLOR} first${N0_COLOR}"
 		/sbin/kldstat -qm alias || /sbin/kldload libalias
 		/sbin/kldstat -qm ipfw_nat || /sbin/kldload ipfw_nat
 		check_nat_ip
diff --git a/tools/repo b/tools/repo
--- a/tools/repo
+++ b/tools/repo
@@ -59,7 +59,7 @@ checkrepo()
 	local _i
 
 	for _i in ${repo}; do
-		[ -z $1 ] && printf "${MAGENTA}Check for repository${NORMAL}: ${GREEN}${_i}${NORMAL} ..."
+		[ -z $1 ] && printf "${N1_COLOR}Check for repository${N0_COLOR}: ${N2_COLOR}${_i}${N0_COLOR} ..."
 		if fetchme -q 1 -u "${_i}/cbsd.index"; then
 			/bin/cat "${TF}"
 			exit 0
@@ -78,31 +78,31 @@ getsrc()
 	[ ! -f "${srcdir}/${DIR}/Makefile" -a $upgrade -ne 1 ] && err 1 "You already have ${ver}"
 
 	for MYREPO in ${repo}; do
-		${ECHO} "${MAGENTA}REPO${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
+		${ECHO} "${N1_COLOR}REPO${N0_COLOR}:${N2_COLOR}${MYREPO}${N0_COLOR}"
 		MIRROR="${MYREPO}/src_${ver}/mirror.html"
 		fetchme -q 1 -u "${MIRROR}"
 		if [ $? -eq 0 ]; then
 			MYREPO=$( /bin/cat ${TF} )
-			${ECHO} "${MAGENTA}Found new mirror for ${ver}${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
+			${ECHO} "${N1_COLOR}Found new mirror for ${ver}${N0_COLOR}:${N2_COLOR}${MYREPO}${N0_COLOR}"
 		fi
 		fetchme -o ${MYDIR}/src.txz -u ${MYREPO}/${DIR}/src.txz
-		[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz${NORMAL}" && icontinue
+		[ $? -eq 0 ] || ${ECHO} "${N1_COLOR}Not found: ${N2_COLOR}${MYREPO}/${DIR}/src.txz${N0_COLOR}" && icontinue
 		fetchme -o ${MYDIR}/src.txz.md5 -u ${MYREPO}/${DIR}/src.txz.md5
-		[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz.md5${NORMAL}" && continue
+		[ $? -eq 0 ] || ${ECHO} "${N1_COLOR}Not found: ${N2_COLOR}${MYREPO}/${DIR}/src.txz.md5${N0_COLOR}" && continue
 	done
 
 	[ -f "${MYDIR}/src.txz" -a -f "${MYDIR}/src.txz.md5" ] || err 1 "No sources found"
 
 	if checkmd5 ${MYDIR}; then
-		${ECHO} "${MAGENTA}MD5sum correct.${NORMAL}"
+		${ECHO} "${N1_COLOR}MD5sum correct.${N0_COLOR}"
 	else
-		err 1 "${MAGENTA}MD5sum incorrect.${NORMAL}"
+		err 1 "${N1_COLOR}MD5sum incorrect.${N0_COLOR}"
 	fi
 
 	ARCHIVE="${workdir}/tmp/src_${ver}.txz"
 	[ -f "${ARCHIVE}" ] && /bin/rm -f ${ARCHIVE}
 
-	${ECHO} "${MAGENTA}Extracting...${NORMAL}"
+	${ECHO} "${N1_COLOR}Extracting...${N0_COLOR}"
 	cd $workdir/tmp
 	set -e
 	/usr/bin/tar xfz ${MYDIR}/src.txz
@@ -110,7 +110,7 @@ getsrc()
 	/bin/rm -f ${MYDIR}/src.txz
 	/bin/mkdir -p ${srcdir}/src_${ver}
 	/bin/mv ${workdir}/tmp/src_${ver} ${srcdir}/
-	${ECHO} "${MAGENTA}Done...${NORMAL}"
+	${ECHO} "${N1_COLOR}Done...${N0_COLOR}"
 	DT=$( /bin/date "+%Y%m%d" )
 }
 
@@ -165,7 +165,7 @@ getbase()
 	else
 		case "${platform}" in
 			DragonFly)
-				err 1 "${MAGENTA}${platform} unsupported yet${NORMAL}"
+				err 1 "${N1_COLOR}${platform} unsupported yet${N0_COLOR}"
 				;;
 			FreeBSD)
 				case "${ver}" in
@@ -195,7 +195,7 @@ getbase()
 	fi
 
 	if [ -x "${BASE_DIR}/bin/sh" ]; then
-		[ ${upgrade} -eq 1 ] || err 1 "${MAGENTA}You already have ${ver}. Use mode=upgrade for upgrade${NORMAL}"
+		[ ${upgrade} -eq 1 ] || err 1 "${N1_COLOR}You already have ${ver}. Use mode=upgrade for upgrade${N0_COLOR}"
 		${CHFLAGS_CMD} -R noschg ${BASE_DIR}
 	fi
 
@@ -229,7 +229,7 @@ getbase()
 	t_size=0
 
 	if [ "${fbsdrepo}" = "1" ]; then
-		${ECHO} "${MAGENTA}Scanning for fastest mirror...${NORMAL}"
+		${ECHO} "${N1_COLOR}Scanning for fastest mirror...${N0_COLOR}"
 
 		_mirror_num=$( echo "${BSDBASE_DISTSITE}" | /usr/bin/wc -w | /usr/bin/awk {'printf $1'} )
 
@@ -249,29 +249,29 @@ getbase()
 			_mirror_cur=$(( _mirror_cur + 1 ))
 			cur_url_len=$( strlen ${i} )
 			free_len=$(( max_url_len - cur_url_len ))
-			printf " ${WHITE}* ${LGREEN}[ %-5s ] ${GREEN}${i}${NORMAL}:%-${free_len}s" ${_mirror_cur}/${_mirror_num}
+			printf " ${H1_COLOR}* ${H2_COLOR}[ %-5s ] ${N2_COLOR}${i}${N0_COLOR}:%-${free_len}s" ${_mirror_cur}/${_mirror_num}
 			t_size=$( /usr/bin/timeout -s HUP 3 ${bindir}/cfetch -s 1 -o /dev/null -u ${i} 2>/dev/null )
 			if [ -z "${t_size}" ]; then
-				${ECHO} "${LRED}failed${NORMAL}"
+				${ECHO} "${W1_COLOR}failed${N0_COLOR}"
 			else
-				${ECHO} "${LCYAN}${t_size}${NORMAL}"
+				${ECHO} "${H5_COLOR}${t_size}${N0_COLOR}"
 				if ! is_number ${t_size}; then
 					if [ ${t_size} -gt ${win_rate} ]; then
 						win_rate=${t_size}
 						win_mirror="${i}"
 					fi
 				else
-					${ECHO} "${LRED}failed, no size${NORMAL}"
+					${ECHO} "${W1_COLOR}failed, no size${N0_COLOR}"
 				fi
 			fi
 		done
-		[ -n "${win_mirror}" ] && ${ECHO} "${LYELLOW} Winner: ${GREEN}${win_mirror}${NORMAL}"
+		[ -n "${win_mirror}" ] && ${ECHO} "${H3_COLOR} Winner: ${N2_COLOR}${win_mirror}${N0_COLOR}"
 		iso_site="${win_mirror} ${BSDBASE_DISTSITE}"
 	fi
 
 	if [ "${fbsdrepo}" = "1" -a -z "${basename}" ]; then
 		## Official fbsd repo
-		${ECHO} "${MAGENTA}Looking for official ${platform} mirror:${NORMAL}"
+		${ECHO} "${N1_COLOR}Looking for official ${platform} mirror:${N0_COLOR}"
 		ARCHIVE="${MYDIR}/base.txz"
 		for MIRROR in ${iso_site}; do
 			fetchme -u ${MIRROR} -o ${ARCHIVE}
@@ -282,7 +282,7 @@ getbase()
 			fi
 		done
 		if [ -r ${ARCHIVE} ]; then
-			printf "\n${MAGENTA}Extracting base...${NORMAL}\n"
+			printf "\n${N1_COLOR}Extracting base...${N0_COLOR}\n"
 			[ ! -d "${BASE_DIR}" ] && mkdir -p ${BASE_DIR}
 			cd ${BASE_DIR}
 			set -e
@@ -305,14 +305,14 @@ getbase()
 						fi
 					done
 					if [ -r ${ARCHIVE} ]; then
-						printf "\n${MAGENTA}Extracting lib32...${NORMAL}\n"
+						printf "\n${N1_COLOR}Extracting lib32...${N0_COLOR}\n"
 						cd ${BASE_DIR}
 						set -e
 						/usr/bin/tar xfz ${ARCHIVE}
 						set +e
 						/bin/rm -f ${ARCHIVE}
 					else
-						printf "${GREEN} Lib32 not found${NORMAL}\n"
+						printf "${N2_COLOR} Lib32 not found${N0_COLOR}\n"
 					fi
 				fi
 			fi
@@ -327,10 +327,10 @@ getbase()
 				[ "${cbsd_queue_name}" != "none" ] && cbsd_queue_sys cbsd_queue_name=${cbsd_queue_name} cmd=repo id=base${ver}-${arch}-${stable} status=2
 			fi
 
-			${ECHO} "${MAGENTA}Done...${NORMAL}"
+			${ECHO} "${N1_COLOR}Done...${N0_COLOR}"
 			return 0
 		fi
-		printf "${GREEN} Not found${NORMAL}\n"
+		printf "${N2_COLOR} Not found${N0_COLOR}\n"
 		### Official fbsd repo end ###
 	fi
 
@@ -338,32 +338,32 @@ getbase()
 	_src_found=0
 
 	for MYREPO in ${repo}; do
-		${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
+		${ECHO} "${N1_COLOR}REPO: ${N2_COLOR}${MYREPO}${N0_COLOR}"
 		MIRROR="${MYREPO}/releases/${URL_HIER}/mirror.html";
 		fetchme -q1 -u ${MIRROR} -o ${TF}
 
 		if [ $? -eq 0 ]; then
 			MYREPO=$( /bin/cat ${TF} )
-			${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
+			${ECHO} "${N1_COLOR}Found new mirror for ${ver}: ${N2_COLOR}${MYREPO}${N0_COLOR}"
 		fi
 
 		if [ -z "${basename}" ]; then
-			${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${URL_HIER}/base.txz${NORMAL}"
+			${ECHO} "${N1_COLOR}Looking for: ${N2_COLOR}${MYREPO}/releases/${URL_HIER}/base.txz${N0_COLOR}"
 			fetchme -o ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${URL_HIER}/base.txz
 
 			if [ $? -ne 0 ]; then
-				${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${URL_HIER}/base.txz${NORMAL}"
+				${ECHO} "${N1_COLOR}Base not found: ${N2_COLOR}${MYREPO}/releases/${URL_HIER}/base.txz${N0_COLOR}"
 				continue
 			else
 				_src_found=1
 			fi
 			_srcmd5_found=1
 		else
-			${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${NORMAL}"
+			${ECHO} "${N1_COLOR}Looking for: ${N2_COLOR}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${N0_COLOR}"
 			fetchme -o ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${URL_HIER}/base_${basename}.txz
 
 			if [ $? -ne 0 ]; then
-				${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${NORMAL}"
+				${ECHO} "${N1_COLOR}Base not found: ${N2_COLOR}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${N0_COLOR}"
 				continue
 			else
 				_src_found=1
@@ -375,9 +375,9 @@ getbase()
 		[ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
 	done
 
-	[ ${_src_found} -ne 1 ] && err 1 "${MAGENTA}Not found data${NORMAL}"
+	[ ${_src_found} -ne 1 ] && err 1 "${N1_COLOR}Not found data${N0_COLOR}"
 
-	${ECHO} "${MAGENTA}Extracting...${NORMAL}"
+	${ECHO} "${N1_COLOR}Extracting...${N0_COLOR}"
 	[ ! -d "${BASE_DIR}" ] && mkdir -p ${BASE_DIR}
 	cd ${BASE_DIR}
 
@@ -403,7 +403,7 @@ getbase()
 		[ "${cbsd_queue_name}" != "none" ] && cbsd_queue_sys cbsd_queue_name=${cbsd_queue_name} cmd=repo id=base${ver}-${arch}-${stable} status=2
 	fi
 
-	${ECHO} "${MAGENTA}Done...${NORMAL}"
+	${ECHO} "${N1_COLOR}Done...${N0_COLOR}"
 
 	return 0
 }
@@ -418,7 +418,7 @@ getobj()
 	fi
 
 	for MYREPO in ${repo}; do
-		${ECHO} "${MAGENTA}REPO:${GREEN}${MYREPO}${NORMAL}"
+		${ECHO} "${N1_COLOR}REPO:${N2_COLOR}${MYREPO}${N0_COLOR}"
 		if [ -z "${basename}" ]; then
 			MIRROR="${MYREPO}/obj_${arch}_${ver}/mirror.html";
 		else
@@ -487,46 +487,46 @@ getkernel()
 	URL_HIER="${arch}/${target_arch}/${ver}"
 
 	if [ -d "${KERNEL_DIR}" ]; then
-		[ $upgrade -ne 1 ] && err 1 "${MAGENTA}You already have kernel ${name} for ${ver}${NORMAL}"
+		[ $upgrade -ne 1 ] && err 1 "${N1_COLOR}You already have kernel ${name} for ${ver}${N0_COLOR}"
 		removekernel ver=${ver} arch=${arch} name=${name}
 	fi
 
 	for MYREPO in ${repo}; do
-		${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
+		${ECHO} "${N1_COLOR}REPO: ${N2_COLOR}${MYREPO}${N0_COLOR}"
 		MIRROR="${MYREPO}/releases/${URL_HIER}/mirror.html"
 		fetchme -q1 -u ${MIRROR} -o ${TF}
 
 		if [ $? -eq 0 ]; then
 			MYREPO=$( /bin/cat ${TF} )
-			${ECHO} "${MAGENTA}Found new mirror for ${ver}: ${GREEN}${MYREPO}${NORMAL}"
+			${ECHO} "${N1_COLOR}Found new mirror for ${ver}: ${N2_COLOR}${MYREPO}${N0_COLOR}"
 		fi
 
-		${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${URL_HIER}/kernel${KERNNAME}.txz${NORMAL}"
+		${ECHO} "${N1_COLOR}Looking for: ${N2_COLOR}${MYREPO}/releases/${URL_HIER}/kernel${KERNNAME}.txz${N0_COLOR}"
 		fetchme -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz -u ${MYREPO}/releases/${URL_HIER}/kernel${KERNNAME}.txz
 		[ $? -eq 0 ] || continue
 		# fetchme -q1 -o ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/kernel_${name}_${arch}_${ver}.txz.md5
 		# [ $? -eq 0 ] || continue
 	done
 
-	[ ! -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz" ] && err 1 "${MAGENTA}No such sources:${GREEN}${MYDIR}/kernel_${name}_${arch}_${ver}.txz${NORMAL}"
+	[ ! -f "${MYDIR}/kernel_${name}_${arch}_${ver}.txz" ] && err 1 "${N1_COLOR}No such sources:${N2_COLOR}${MYDIR}/kernel_${name}_${arch}_${ver}.txz${N0_COLOR}"
 
 	# if checkmd5 ${MYDIR}; then
-	# ${ECHO} "${MAGENTA}MD5 sum: ${GREEN}correct${NORMAL}"
+	# ${ECHO} "${N1_COLOR}MD5 sum: ${N2_COLOR}correct${N0_COLOR}"
 	# else
-	# err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
+	# err 1 "${N1_COLOR}MD5 sum: ${N2_COLOR}incorrect${N0_COLOR}"
 	# exit 1
 	# fi
 
 	# /bin/rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz.md5
 
-	${ECHO} "${MAGENTA}Extracting...${NORMAL}"
+	${ECHO} "${N1_COLOR}Extracting...${N0_COLOR}"
 	[ ! -d "${KERNEL_DIR}" ] && mkdir -p ${KERNEL_DIR}
 	cd $KERNEL_DIR
 	set -e
 	tar xfz ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
 	set +e
 	rm -f ${MYDIR}/kernel_${name}_${arch}_${ver}.txz
-	${ECHO} "${MAGENTA}Done...${NORMAL}"
+	${ECHO} "${N1_COLOR}Done...${N0_COLOR}"
 }
 
 
@@ -544,24 +544,24 @@ getimg()
 		if [ $? -eq 0 -o $? -eq 3 ]; then
 			/bin/rm -f ${DST}
 		else
-			err 1 "${MAGENTA}You already have: ${GREEN}${DST}${NORMAL}"
+			err 1 "${N1_COLOR}You already have: ${N2_COLOR}${DST}${N0_COLOR}"
 		fi
 	fi
 
 	jstatus jname=${newjname} > /dev/null 2>&1
-	[ $? -ne 0 ] && err 1 "${MAGENTA}You already have ${GREEN}${newjname}${MAGENTA} jail. Remove it or use ${GREEN}newjname=${NORMAL}"
+	[ $? -ne 0 ] && err 1 "${N1_COLOR}You already have ${N2_COLOR}${newjname}${N1_COLOR} jail. Remove it or use ${N2_COLOR}newjname=${N0_COLOR}"
 
 	for MYREPO in ${repo}; do
-		${ECHO} "${MAGENTA}REPO:${GREEN} ${MYREPO}"
+		${ECHO} "${N1_COLOR}REPO:${N2_COLOR} ${MYREPO}"
 		MIRROR="${MYREPO}/img/${URL_HIER}/mirror.html"
 		fetchme -q1 -u ${MIRROR} -o ${TF}
 
 		if [ $? -eq 0 ]; then
 			MYREPO=$( /bin/cat ${TF} )
-			${ECHO} "${MAGENTA}Found new mirror for ${name} ${NORMAL}: ${MYREPO}"
+			${ECHO} "${N1_COLOR}Found new mirror for ${name} ${N0_COLOR}: ${MYREPO}"
 		fi
 
-		${ECHO} "${MAGENTA}Fetching ${name} jail: ${GREEN}${MYREPO}/${DIR}${MAGENTA}${NORMAL}"
+		${ECHO} "${N1_COLOR}Fetching ${name} jail: ${N2_COLOR}${MYREPO}/${DIR}${N1_COLOR}${N0_COLOR}"
 		fetchme -o ${DST} -u ${MYREPO}/img/${URL_HIER}/${name}.img
 
 		[ $? -eq 0 ] || continue
@@ -574,7 +574,7 @@ getbhyve()
 {
 	local URL_HIER DST
 
-	[ -z "${name}" ] && err 1 "${MAGENTA}Empty name=${NORMAL}"
+	[ -z "${name}" ] && err 1 "${N1_COLOR}Empty name=${N0_COLOR}"
 
 	[ -z "${newjname}" ] && newjname="${name}"
 
@@ -585,24 +585,24 @@ getbhyve()
 		if [ $? -eq 0 -o $? -eq 3 ]; then
 			/bin/rm -f ${DST}
 		else
-			err 1 "${MAGENTA}You already have: ${GREEN}${DST}${NORMAL}"
+			err 1 "${N1_COLOR}You already have: ${N2_COLOR}${DST}${N0_COLOR}"
 		fi
 	fi
 
 	jstatus jname=${newjname} > /dev/null 2>&1
-	[ $? -ne 0 ] && err 1 "${MAGENTA}You already have ${GREEN}${newjname}${MAGENTA} vm."
+	[ $? -ne 0 ] && err 1 "${N1_COLOR}You already have ${N2_COLOR}${newjname}${N1_COLOR} vm."
 
 	for MYREPO in ${repo}; do
-		${ECHO} "${MAGENTA}REPO:${GREEN} ${MYREPO}"
+		${ECHO} "${N1_COLOR}REPO:${N2_COLOR} ${MYREPO}"
 		MIRROR="${MYREPO}/bhyve/${name}/mirror.html"
 		fetchme -q1 -u ${MIRROR} -o ${TF}
 
 		if [ $? -eq 0 ]; then
 			MYREPO=$( /bin/cat ${TF} )
-			${ECHO} "${MAGENTA}Found new mirror for ${name} ${NORMAL}: ${MYREPO}"
+			${ECHO} "${N1_COLOR}Found new mirror for ${name} ${N0_COLOR}: ${MYREPO}"
 		fi
 
-		${ECHO} "${MAGENTA}Fetching ${name} jail: ${GREEN}${MYREPO}/${DIR}${MAGENTA}${NORMAL}"
+		${ECHO} "${N1_COLOR}Fetching ${name} jail: ${N2_COLOR}${MYREPO}/${DIR}${N1_COLOR}${N0_COLOR}"
 		fetchme -o ${DST} -u ${MYREPO}/bhyve/${name}.img
 
 		[ $? -eq 0 ] || continue
@@ -622,9 +622,9 @@ gethelpers()
 
 	if [ -z "${name}" ]; then
 		fetchme -q1 -u ${MIRROR}/helpersls -o ${ftmpdir}/helpers.$$.list
-		[ $? -ne 0 ] && err 1 "${MAGENTA}Error fetching for: ${GREEN}helper list${NORMAL}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}Error fetching for: ${N2_COLOR}helper list${N0_COLOR}"
 		for i in $( /bin/cat ${ftmpdir}/helpers.$$.list ); do
-			${ECHO} "${MAGENTA}Get helpers: ${GREEN}${i}${NORMAL}"
+			${ECHO} "${N1_COLOR}Get helpers: ${N2_COLOR}${i}${N0_COLOR}"
 			if [ "${mode}" = "upgrade" ]; then
 				repo action=get sources=helpers name=${i} mode=upgrade
 			else
@@ -644,7 +644,7 @@ gethelpers()
 		elif [ -d "${DST}/${name}" ]; then
 			rm -f ${tmpdir}/helpers/helpers_${name}.$$.tgz
 			rmdir ${tmpdir}/helpers
-			err 1 "${MAGENTA}Helpers already exist: ${GREEN}${name}${MAGENTA}. Use mode=upgrade for upgrading.${NORMAL}"
+			err 1 "${N1_COLOR}Helpers already exist: ${N2_COLOR}${name}${N1_COLOR}. Use mode=upgrade for upgrading.${N0_COLOR}"
 		fi
 		mkdir ${DST}/${name}
 		set -e
@@ -666,9 +666,9 @@ getmodules()
 
 	if [ -z "${name}" ]; then
 		fetchme -q1 -u ${MIRROR}/modulesls -o ${ftmpdir}/modules.$$.list
-		[ $? -ne 0 ] && err 1 "${MAGENTA}Error fetching for: ${GREEN}modules list${NORMAL}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}Error fetching for: ${N2_COLOR}modules list${N0_COLOR}"
 		for i in $( /bin/cat ${ftmpdir}/modules.$$.list ); do
-			${ECHO} "${MAGENTA}Get modules: ${GREEN}${i}${NORMAL}"
+			${ECHO} "${N1_COLOR}Get modules: ${N2_COLOR}${i}${N0_COLOR}"
 			if [ "${mode}" = "upgrade" ]; then
 				repo action=get sources=modules name=${i} mode=upgrade
 			else
@@ -688,7 +688,7 @@ getmodules()
 		elif [ -d "${DST}/${name}" ]; then
 			/bin/rm -f ${tmpdir}/modules/modules_${name}.$$.tgz
 			/bin/rmdir ${tmpdir}/modules
-			err 1 "${MAGENTA}modules already exist: ${GREEN}${name}${MAGENTA}. Use mode=upgrade for upgrading.${NORMAL}"
+			err 1 "${N1_COLOR}modules already exist: ${N2_COLOR}${name}${N1_COLOR}. Use mode=upgrade for upgrading.${N0_COLOR}"
 		fi
 		mkdir ${DST}/${name}
 		set -e
@@ -734,7 +734,7 @@ case "${action}" in
 	"list")
 		for i in ${repo}; do
 			if fetchme -q 1 -u "${i}/${sources}ls"; then
-				[ ${quiet} -ne 1 ] && ${ECHO} "${MAGENTA}Available sources on ${GREEN}$i:${NORMAL}"
+				[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Available sources on ${N2_COLOR}$i:${N0_COLOR}"
 				case "${sources}" in
 					"bhyve")
 						/bin/cat ${TF}
@@ -813,7 +813,7 @@ case "${action}" in
 				mkdir -p ${MYDIR}
 				getimg
 #				[ "${usehelpers}" = "1" ] && gethelpers ${name} ${name}
-				${ECHO} "${MAGENTA}Done... Importing...${NORMAL}"
+				${ECHO} "${N1_COLOR}Done... Importing...${N0_COLOR}"
 				if [ -n "${newjname}" ]; then
 					name="${newjname}"
 					jimport jname=${name} newjname="${name}"
@@ -821,7 +821,7 @@ case "${action}" in
 					jimport jname=${name}
 				fi
 				if [ -f "${importdir}/${name}.img" ]; then
-					${ECHO} "${MAGENTA}Import complete${NORMAL}"
+					${ECHO} "${N1_COLOR}Import complete${N0_COLOR}"
 					getyesno "Do you want to remove source image ${importdir}/${name}.img ?"
 					[ $? -eq 0 -o $? -eq 3 ] && /bin/rm -f ${importdir}/${name}.img
 				fi
@@ -840,7 +840,7 @@ case "${action}" in
 				;;
 			bhyve)
 				getbhyve
-				${ECHO} "${MAGENTA}Done... Importing...${NORMAL}"
+				${ECHO} "${N1_COLOR}Done... Importing...${N0_COLOR}"
 				if [ -n "${newjname}" ]; then
 					name="${newjname}"
 					bimport jname=${name} newjname="${name}"
@@ -848,13 +848,13 @@ case "${action}" in
 					bimport jname=${name}
 				fi
 				if [ -f "${importdir}/${name}.img" ]; then
-					${ECHO} "${MAGENTA}Import complete${NORMAL}"
+					${ECHO} "${N1_COLOR}Import complete${N0_COLOR}"
 					getyesno "Do you want to remove source image ${importdir}/${name}.img ?"
 					[ $? -eq 0 -o $? -eq 3 ] && /bin/rm -f ${importdir}/${name}.img
 				fi
 				;;
 			*)
-				err 1 "${MAGENTA}Unknown sources: ${GREEN}${sources}${NORMAL}"
+				err 1 "${N1_COLOR}Unknown sources: ${N2_COLOR}${sources}${N0_COLOR}"
 				;;
 		esac ## END of source case
 		;;
diff --git a/tools/task b/tools/task
--- a/tools/task
+++ b/tools/task
@@ -30,10 +30,10 @@ try_remote()
 	. ${nodes}
 
 	_ip=$( cbsdsqlro nodes SELECT ip FROM nodelist WHERE nodename=\"${node}\" 2>/dev/null )
-	[ -z "${_ip}" ] && err 1 "${MAGENTA}No such ip for node: ${GREEN}${node}${NORMAL}"
+	[ -z "${_ip}" ] && err 1 "${N1_COLOR}No such ip for node: ${N2_COLOR}${node}${N0_COLOR}"
 
 	if ! check_locktime ${ftmpdir}/shmux_${_ip}.lock > /dev/null 2>&1; then
-		err 1 "${MAGENTA}Node is offline: ${GREEN}${node}${NORMAL}"
+		err 1 "${N1_COLOR}Node is offline: ${N2_COLOR}${node}${N0_COLOR}"
 	fi
 
 	rexe node=${node} cbsd task autoflush=2 mode=new owner=${nodename} $@
@@ -68,12 +68,12 @@ shift ## mode=xxx
 
 case "${mode}" in
 	"new")
-		[ -z "$1" ] && err 1 "${MAGENTA}Command required${NORMAL}"
+		[ -z "$1" ] && err 1 "${N1_COLOR}Command required${N0_COLOR}"
 
 		# test for exclusive
 		if [ ${exclusive} -eq 1 ]; then
 			_excl_test=$( cbsdsqlro cbsdtaskd "SELECT id FROM taskd WHERE cmd=\"$@\" AND status != 2 AND owner=\"${owner}\" AND jname=\"${jname}\" ORDER BY id DESC LIMIT 1" )
-			[ -n "${_excl_test}" ] && err 1 "${MAGENTA}This job is exclusive, waiting to complete: ${GREEN}${_excl_test}${NORMAL}"
+			[ -n "${_excl_test}" ] && err 1 "${N1_COLOR}This job is exclusive, waiting to complete: ${N2_COLOR}${_excl_test}${N0_COLOR}"
 		fi
 
 		if [ -n "${logfile}" ]; then
@@ -82,9 +82,9 @@ case "${mode}" in
 			_err=$( cbsdsqlrw cbsdtaskd "INSERT INTO taskd ( cmd,status,notify,autoflush,owner,after,client_id,jname ) VALUES ( \"$@\", 0, \"$notify\", \"$autoflush\", \"$owner\", \"$after\", \"$client_id\", \"${jname}\" )" )
 		fi
 
-		[ $? -ne 0 ] && err 1 "${MAGENTA}Error: ${_err}${NORMAL}"
+		[ $? -ne 0 ] && err 1 "${N1_COLOR}Error: ${_err}${N0_COLOR}"
 		tid=$( cbsdsqlro cbsdtaskd "SELECT id FROM taskd WHERE cmd=\"$@\" AND status=0 ORDER BY id DESC LIMIT 1" )
-		[ -z "${tid}" ] && err 1 "${MAGENTA}Error: ${_err}${NORMAL}"
+		[ -z "${tid}" ] && err 1 "${N1_COLOR}Error: ${_err}${N0_COLOR}"
 		echo "${tid}"
 		;;
 	"cancel")
diff --git a/tools/valecfg-tui b/tools/valecfg-tui
--- a/tools/valecfg-tui
+++ b/tools/valecfg-tui
@@ -29,7 +29,7 @@ dialog_menu_main()
 			mark=" "
 		fi
 		echo "'${name}'	'[${mark}] vale=${name}'	'Switch named ${name}'"
-	done ) || err 1 "${MAGENTA}Error while create vale map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create vale map${N0_COLOR}"
 
 	[ -z "${menu_list}" ] && menu_list="''	'no data'	''"
 
diff --git a/tools/vhidcfg-tui b/tools/vhidcfg-tui
--- a/tools/vhidcfg-tui
+++ b/tools/vhidcfg-tui
@@ -29,7 +29,7 @@ dialog_menu_main()
 			mark=" "
 		fi
 		echo "'${id}'	'[${mark}] vhid=${carp_vhid} advskew=${carp_advskew}'	'interface=${interface};pass=${carp_pass};state=${carp_state}'"
-	done ) || err 1 "${MAGENTA}Error while create vhid map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create vhid map${N0_COLOR}"
 
 	[ -z "${menu_list}" ] && menu_list="''	'no data'	''"
 
diff --git a/tools/vm-cpu-topology-tui b/tools/vm-cpu-topology-tui
--- a/tools/vm-cpu-topology-tui
+++ b/tools/vm-cpu-topology-tui
@@ -29,7 +29,7 @@ dialog_menu_main()
 			mark=" "
 		fi
 		echo "'${name}'	'[${mark}] Sockets=${sockets},Cores=${cores},Threads=${threads}'	'description'"
-	done ) || err 1 "${MAGENTA}Error while create topology map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create topology map${N0_COLOR}"
 
 	[ -z "${menu_list}" ] && menu_list="''	'no data'	''"
 
diff --git a/tools/vm-packages-tui b/tools/vm-packages-tui
--- a/tools/vm-packages-tui
+++ b/tools/vm-packages-tui
@@ -29,7 +29,7 @@ dialog_menu_main()
 			mark=" "
 		fi
 		echo "'${name}'	'[${mark}] CPU=${pkg_vm_cpus} RAM=${pkg_vm_ram} DISK=${pkg_vm_disk}'	'description'"
-	done ) || err 1 "${MAGENTA}Error while create packages map${NORMAL}"
+	done ) || err 1 "${N1_COLOR}Error while create packages map${N0_COLOR}"
 
 	[ -z "${menu_list}" ] && menu_list="''	'no data'	''"
 
