bhyve: nic_persistent wip

diff --git a/jailctl/bcreate b/jailctl/bcreate
--- a/jailctl/bcreate
+++ b/jailctl/bcreate
@@ -380,16 +380,19 @@ fi
 
 echo
 if [ "${vm_zfs_guid}" != "0" ]; then
-	${ECHO} "${N1_COLOR}Global VM ZFS guid: ${N2_COLOR}${vm_zfs_guid}${N0_COLOR}"
+	[ -z "${NOINTER}" ] && ${ECHO} "${N1_COLOR}Global VM ZFS guid: ${N2_COLOR}${vm_zfs_guid}${N0_COLOR}"
 	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE settings SET vm_zfs_guid="${vm_zfs_guid}"
 fi
-${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd bconfig jname=${jname}${N0_COLOR}"
-${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd bstart ${jname}${N0_COLOR}"
-${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd bstop ${jname}${N0_COLOR}"
-${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd bremove ${jname}${N0_COLOR}"
-${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd blogin ${jname}${N0_COLOR}"
-echo
-${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
+
+if [ -z "${NOINTER}" ]; then
+	${ECHO} "${N1_COLOR}To edit VM properties use: ${N2_COLOR}cbsd bconfig jname=${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To start VM use: ${N2_COLOR}cbsd bstart ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To stop VM use: ${N2_COLOR}cbsd bstop ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}To remove VM use: ${N2_COLOR}cbsd bremove ${jname}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}For attach VM console use: ${N2_COLOR}cbsd blogin ${jname}${N0_COLOR}"
+	echo
+	${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
+fi
 
 /bin/rm -f ${rcconf}
 
@@ -432,13 +435,13 @@ if [ -n "${register_iso_as}" -a -n "${register_iso_name}" ]; then
 
 	if [ "${cd_rec_num}" = "0" ]; then
 		# register new ISO with assignment to this VM
-		media mode=register name="${register_iso_as}" path="${srcdir}/iso/${register_iso_name}" type=iso jname=${jname}
+		_res=$( media mode=register name="${register_iso_as}" path="${srcdir}/iso/${register_iso_name}" type=iso jname=${jname} 2>&1 )
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}bcreate: media register error: ${_res}${N0_COLOR}"
 	else
 		# we have free/unassignent CD. link to this VM
 		cbsdsqlrw storage_media "UPDATE media SET jname=\"${jname}\" WHERE jname=\"-\" AND type=\"iso\" AND name=\"${cd_name}\" AND path=\"${cd_path}\""
 	fi
-
-#	media mode=register name="${register_iso_as}" path="${srcdir}/iso/${register_iso_name}" type=iso jname=${jname}
 fi
 
 [ ! -d ${jailsysdir}/${jname} ] && /bin/mkdir -p ${jailsysdir}/${jname}
