up/destroy/exec/login: support for API via CBSDfile, WIP
highly experimental. WIP

diff --git a/jailctl/blogin b/jailctl/blogin
--- a/jailctl/blogin
+++ b/jailctl/blogin
@@ -1,15 +1,19 @@
 #!/usr/local/bin/cbsd
-#v11.2.1
+#v13.0.1
 globalconf="${distdir}/cbsd.conf";
 MYARG=""
 MYOPTARG="jname remote inter"
 MYDESC="Exec login into jail"
+ADDHELP="\
+  If you are in the CBSDfile directory, these environments will always have priority\n\
+"
 EXTHELP="wf_blogin"
 CBSDMODULE="bhyve"
 
 . ${subr}
 . ${strings}
 . ${tools}
+cbsd_api=0
 . ${cbsdinit}
 
 try_remote()
@@ -93,6 +97,65 @@ login_custom()
 	# restore CBSD PATH
 	export PATH="${CBSDPATH}"
 }
+
+# check for cloud function when CBSDfile exist
+if [ -z "${jname}" ]; then
+	Makefile="${CBSD_PWD}/CBSDfile"
+	if [ -r ${Makefile} ]; then
+		. ${Makefile}
+		if [ -n "${CLOUD_URL}" -a -n "${CLOUD_KEY}" ]; then
+			all_bhyve_list=$( ${EGREP_CMD} '^bhyve_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#bhyve_##g )
+			cbsd_api=1
+		else
+			cbsd_api=0
+			all_bhyve_list=$( ${EGREP_CMD} '^bhyve_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#bhyve_##g )
+			jname="${all_bhyve_list}"
+		fi
+	fi
+else
+	cbsd_api=0
+fi
+
+if [ ${cbsd_api} -eq 1 ]; then
+	CURL_CMD=$( which curl )
+	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
+	${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}"
+	_cid=$( ${MD5_CMD} -qs "${CLOUD_KEY}" )
+
+	for jname in ${all_bhyve_list}; do
+		[ -z "${jname}" ] && return 1
+		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${jname} 2>&1 )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
+			continue
+		fi
+		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh}" )
+		if [ "${_ssh_pref}" != "ssh" ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
+			continue
+		fi
+		_ssh_len=$( strlen "${_ssh}" )
+		_ssh_post=$( substr --pos=5 --len=${_ssh_len} --str="${_ssh}" )
+		#echo "${SSH_CMD} ${_ssh_post}"
+		# rewrite
+		if [ -n "${SUDO_USER}" ]; then
+			if [ -r /home/${SUDO_USER}/.ssh/id_ed25519 ]; then
+				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_ed25519"
+			elif [ -r /home/${SUDO_USER}/.ssh/id_rsa ]; then
+				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_rsa"
+			else
+				date
+			fi
+		fi
+		jexec_cmd="${SSH_CMD} -tt -oStrictHostKeyChecking=no -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_post}"
+		echo "[debug] exec: $jexec_cmd"
+		${jexec_cmd}
+	done
+	exit 0
+fi
 
 emulator="bhyve"	# for jname_is_multiple
 jname_is_multiple	# import jail_list if jname is mask
