lint jailctl

diff --git a/jailctl/bls b/jailctl/bls
--- a/jailctl/bls
+++ b/jailctl/bls
@@ -40,13 +40,13 @@ ${H3_COLOR}Examples${N0_COLOR}:
 "
 EXTHELP="wf_bls"
 
-. ${subrdir}/nc.subr
-. ${strings}
-. ${tools}
-. ${nodes}
+. "${subrdir}"/nc.subr
+. "${strings}"
+. "${tools}"
+. "${nodes}"
 
 readconf bls.conf
-. ${cbsdinit}
+. "${cbsdinit}"
 
 [ ! -d "${workdir}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no such workdir: ${N2_COLOR}${workdir}${N0_COLOR}"
 
@@ -96,7 +96,7 @@ fi
 mydisplay=$( echo ${display} | ${TR_CMD} ',' '  ' )
 
 # upper for header
-myheader=$( echo ${mydisplay} | ${TR_CMD} '[:lower:]' '[:upper:]' )
+myheader=$( echo "${mydisplay}" | ${TR_CMD} '[:lower:]' '[:upper:]' )
 
 JLS=
 
@@ -115,7 +115,7 @@ conv_status()
 			status="Slave"
 			;;
 		3)
-			_maintain_reason=$( cbsdsqlro local SELECT maintenance FROM jails WHERE jname=\"${jname}\" 2>/dev/null )
+			_maintain_reason=$( cbsdsqlro local SELECT maintenance FROM jails WHERE jname=\""${jname}"\" 2>/dev/null )
 			if [ -n "${_maintain_reason}" -a "${_maintain_reason}" != "0" ]; then
 				status="Maintenance:${_maintain_reason}"
 			else
@@ -131,7 +131,7 @@ conv_status()
 show_header()
 {
 	local _header="${H1_COLOR}${BOLD}${myheader}${N0_COLOR}"
-	[ ${header} -eq 1 ] && ${ECHO} ${_header}
+	[ "${header}" -eq 1 ] && ${ECHO} "${_header}"
 }
 
 # $1 - pid
@@ -139,7 +139,7 @@ get_rctl()
 {
 	local _val
 
-	get_rctl_values -m process -p ${1} -j ${jname}
+	get_rctl_values -m process -p "${1}" -j "${jname}"
 }
 
 # -j $jname
@@ -175,11 +175,11 @@ populate_output_data()
 			if [ "${racct}" = "1" ]; then
 				memoryuse=0
 				pcpu=0
-				_pid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\"${jname}\" 2>/dev/null )
+				_pid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\""${jname}"\" 2>/dev/null )
 				if [ "${_pid}" = "0" -o "${_pid}" = "1" ]; then
 					_val="0"
 				else
-					get_rctl ${_pid}
+					get_rctl "${_pid}"
 				fi
 			fi
 		else
@@ -188,10 +188,10 @@ populate_output_data()
 	else
 		# pop status variable from node_is_online()
 		_md5_node_name=$( ${MD5_CMD} -q -s ${sqlfile} )
-		eval _node_is_online=\$node_${_md5_node_name}_online
+		eval _node_is_online=\$node_"${_md5_node_name}"_online
 		if [ "${_node_is_online}" = "1" ]; then
 			# retr from sql
-			jid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\"${jname}\" 2>/dev/null )
+			jid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\""${jname}"\" 2>/dev/null )
 			case ${jid} in
 				0)
 					printf "${N4_COLOR}"
@@ -208,7 +208,7 @@ populate_output_data()
 	#populate values for in output string
 	for _i in ${mydisplay}; do
 		_val=
-		eval _val=\$$_i
+		eval _val=\$"$_i"
 		[ -z "${_val}" ] && _val="0"
 
 		# todo: remote sql fetch via retrinv
@@ -220,10 +220,10 @@ populate_output_data()
 
 		# search for custom column output helper first
 		if [ -x "${jailsysdir}/${jname}/facts.d/${_i}" ]; then
-			. ${subrdir}/jcreate.subr               # for export_jail_data_for_external_hook
-			geniplist ${ip4_addr}                   # for ipvX_first_public-like vars
+			. "${subrdir}"/jcreate.subr               # for export_jail_data_for_external_hook
+			geniplist "${ip4_addr}"                   # for ipvX_first_public-like vars
 			export_jail_data_for_external_hook
-			_val=$( ${jailsysdir}/${jname}/facts.d/${_i} | ${HEAD_CMD} -1 | ${AWK_CMD} '{printf $1}' )
+			_val=$( "${jailsysdir}"/"${jname}"/facts.d/"${_i}" | ${HEAD_CMD} -1 | ${AWK_CMD} '{printf $1}' )
 		else
 			case "${_i}" in
 				vm_ram)
@@ -260,7 +260,7 @@ populate_output_data()
 					fi
 					;;
 				vnc_port)
-					_tmpport=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vnc_port FROM settings LIMIT 1" )
+					_tmpport=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT vnc_port FROM settings LIMIT 1" )
 					if [ -n "${_tmpport}" ]; then
 						_val="${_tmpport}"
 					else
@@ -268,15 +268,15 @@ populate_output_data()
 					fi
 					;;
 				vnc)
-					_tmpport=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vnc_port FROM settings LIMIT 1" )
+					_tmpport=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT vnc_port FROM settings LIMIT 1" )
 					if [ -n "${_tmpport}" ]; then
 						# jailed?
-						_jailed=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT jailed FROM settings LIMIT 1" )
+						_jailed=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT jailed FROM settings LIMIT 1" )
 						[ -z "${_jailed}" ] && _jailed="0"
 						if [ "${_jailed}" != "0" ]; then
 							# this is jailed bhyve, try to obtain jail IPs
 							_jip=$( jget mode=quiet jname=${_jailed} ip4_addr )
-							iptype ${_jip} >/dev/null 2>&1
+							iptype "${_jip}" >/dev/null 2>&1
 							_ret=$?
 
 							case ${_ret} in
@@ -291,12 +291,12 @@ populate_output_data()
 							esac
 						else
 							# not jailed
-							if [ -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
+							if [ -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
 								# we need for special route of tcpbind presentation for foreign bhyve. replace 0.0.0.0 by nodeip
 								if [ "${sqlfile}" != "local" ]; then
 									_tmpbind=$( cbsdsqlro ${sqlfile} "SELECT nodeip FROM local LIMIT 1" 2>/dev/null )
 								else
-									_tmpbind=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT bhyve_vnc_tcp_bind FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
+									_tmpbind=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT bhyve_vnc_tcp_bind FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
 								fi
 							else
 								_tmpbind="Unk"
@@ -308,16 +308,16 @@ populate_output_data()
 					fi
 					;;
 				ip4_addr)
-					if [ -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
-						_val=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT ip4_addr FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
+					if [ -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
+						_val=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT ip4_addr FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
 					else
 						_val="Unk"
 					fi
 					[ "${_val}" = "(null)" ] && _val="DHCP"
 					;;
 				vm_zfs_guid)
-					if [ -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
-						_val=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vm_zfs_guid FROM settings LIMIT 1" 2>/dev/null )
+					if [ -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
+						_val=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT vm_zfs_guid FROM settings LIMIT 1" 2>/dev/null )
 					else
 						_val="0"
 					fi
@@ -357,26 +357,26 @@ show_jaildata_from_sql()
 		_status=
 
 		if [ "${sqlfile}" = "local" ]; then
-			. ${subrdir}/rcconf.subr
+			. "${subrdir}"/rcconf.subr
 		else
 			RHST="${sqlfile}"
-			. ${subrdir}/rrcconf.subr
+			. "${subrdir}"/rrcconf.subr
 		fi
 
 		# skip hidden env when show_hidden=0
 		[ -z "${hidden}" ] && hidden=0		# broken schema?
 		[ ${hidden} -eq 1 -a ${show_hidden} -eq 0 ] && continue
 
-		if [ ! -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
+		if [ ! -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
 			if [ "${mnt_start}" = "0" ]; then
 				# skip invalid vms
-				${ECHO} "${N1_COLOR}${jname}: can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}"  >> ${my_err_file}
+				${ECHO} "${N1_COLOR}${jname}: can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}"  >> "${my_err_file}"
 				continue
 			fi
 		fi
 
 		conv_status
-		populate_output_data -j ${jname} -s ${sqlfile}
+		populate_output_data -j "${jname}" -s ${sqlfile}
 	done
 }
 
@@ -400,16 +400,16 @@ show_local()
 	status="\-"
 	vnc="\-"
 
-	for J in $( ${LS_CMD} ${jailrcconfdir} ); do
+	for J in $( ${LS_CMD} "${jailrcconfdir}" ); do
 		[ "${J}" = "dir.id" ] && continue
 		jname=
-		[ ! -r ${jailrcconfdir}/${J} ] && continue
-		. ${jailrcconfdir}/${J}
+		[ ! -r "${jailrcconfdir}"/"${J}" ] && continue
+		. "${jailrcconfdir}"/"${J}"
 		# for bhyve vm only
 		[ "${emulator}" != "bhyve" ] && continue
 		[ -z "${jname}" ] && continue
-		populate_output_data -u 1 -j ${jname}
-		${ECHO} ${_status}
+		populate_output_data -u 1 -j "${jname}"
+		${ECHO} "${_status}"
 	done
 }
 
@@ -422,8 +422,8 @@ show_remote()
 	for _n in ${node}; do
 		nodename="${_n}"
 		# init and export into $node_${md5_node_name}_online node status
-		node_is_online -n ${nodename} -e 1
-		show_jaildata_from_sql ${_n}
+		node_is_online -n "${nodename}" -e 1
+		show_jaildata_from_sql "${_n}"
 	done
 }
 
@@ -443,7 +443,7 @@ show_jails()
 	fi
 }
 
-. ${subrdir}/jrctl.subr
+. "${subrdir}"/jrctl.subr
 
 #### MAIN
 [ -z "${header}" ] && header=1
@@ -452,10 +452,10 @@ sqldelimer=" "
 my_err_file="${ftmpdir}/ls.$$"
 show_jails | ${COLUMN_CMD} -t
 
-if [ -r ${my_err_file} ]; then
+if [ -r "${my_err_file}" ]; then
 	${ECHO} "${N1_COLOR}Error:${N0_COLOR}" 1>&2
-	${CAT_CMD} ${my_err_file} 1>&2
-	${RM_CMD} -f ${my_err_file}
+	${CAT_CMD} "${my_err_file}" 1>&2
+	${RM_CMD} -f "${my_err_file}"
 fi
 
 exit 0
diff --git a/jailctl/xls b/jailctl/xls
--- a/jailctl/xls
+++ b/jailctl/xls
@@ -22,13 +22,13 @@ ADDHELP="\
 "
 EXTHELP="wf_xls"
 
-. ${subrdir}/nc.subr
-. ${strings}
-. ${tools}
-. ${nodes}
+. "${subrdir}"/nc.subr
+. "${strings}"
+. "${tools}"
+. "${nodes}"
 
 readconf xls.conf
-. ${cbsdinit}
+. "${cbsdinit}"
 
 [ ! -d "${workdir}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no such workdir: ${N2_COLOR}${workdir}${N0_COLOR}"
 
@@ -78,7 +78,7 @@ fi
 mydisplay=$( echo ${display} | ${TR_CMD} ',' '  ' )
 
 # upper for header
-myheader=$( echo ${mydisplay} | ${TR_CMD} '[:lower:]' '[:upper:]' )
+myheader=$( echo "${mydisplay}" | ${TR_CMD} '[:lower:]' '[:upper:]' )
 
 JLS=
 
@@ -97,7 +97,7 @@ conv_status()
 			status="Slave"
 			;;
 		3)
-			_maintain_reason=$( cbsdsqlro local SELECT maintenance FROM jails WHERE jname=\"${jname}\" 2>/dev/null )
+			_maintain_reason=$( cbsdsqlro local SELECT maintenance FROM jails WHERE jname=\""${jname}"\" 2>/dev/null )
 			if [ -n "${_maintain_reason}" -a "${_maintain_reason}" != "0" ]; then
 				status="Maintenance:${_maintain_reason}"
 			else
@@ -113,7 +113,7 @@ conv_status()
 show_header()
 {
 	local _header="${H1_COLOR}${BOLD}${myheader}${N0_COLOR}"
-	[ ${header} -eq 1 ] && ${ECHO} ${_header}
+	[ "${header}" -eq 1 ] && ${ECHO} "${_header}"
 }
 
 # $1 - pid
@@ -121,7 +121,7 @@ get_rctl()
 {
 	local _val
 
-	get_rctl_values -m process -p ${1} -j ${jname}
+	get_rctl_values -m process -p "${1}" -j "${jname}"
 }
 
 # -j $jname
@@ -150,8 +150,8 @@ populate_output_data()
 	_pid="0"
 
 	if [ "${sqlfile}" = "local" ]; then
-		. ${subrdir}/xen.subr
-		_state=$( ${XL_CMD} list ${jname} > /dev/null 2>&1 )
+		. "${subrdir}"/xen.subr
+		_state=$( ${XL_CMD} list "${jname}" > /dev/null 2>&1 )
 		if [ $? -eq 0 ]; then
 			# xen is active
 			printf "${N2_COLOR}"
@@ -159,11 +159,11 @@ populate_output_data()
 			if [ "${racct}" = "1" ]; then
 				memoryuse=0
 				pcpu=0
-				_pid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\"${jname}\" )
+				_pid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\""${jname}"\" )
 				if [ "${_pid}" = "0" -o "${_pid}" = "1" ]; then
 					_val="0"
 				else
-					get_rctl ${_pid}
+					get_rctl "${_pid}"
 				fi
 			fi
 		else
@@ -174,10 +174,10 @@ populate_output_data()
 	else
 		# pop status variable from node_is_online()
 		_md5_node_name=$( ${MD5_CMD} -q -s ${sqlfile} )
-		eval _node_is_online=\$node_${_md5_node_name}_online
+		eval _node_is_online=\$node_"${_md5_node_name}"_online
 		if [ "${_node_is_online}" = "1" ]; then
 			# retr from sql
-			jid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\"${jname}\" )
+			jid=$( cbsdsqlro ${sqlfile} SELECT jid FROM jails WHERE jname=\""${jname}"\" )
 			case ${jid} in
 				0)
 					printf "${N4_COLOR}"
@@ -194,7 +194,7 @@ populate_output_data()
 	#populate values for in output string
 	for _i in ${mydisplay}; do
 		_val=
-		eval _val=\$$_i
+		eval _val=\$"$_i"
 		[ -z "${_val}" ] && _val="0"
 
 		# todo: remote sql fetch via retrinv
@@ -206,10 +206,10 @@ populate_output_data()
 
 		# search for custom column output helper first
 		if [ -x "${jailsysdir}/${jname}/facts.d/${_i}" ]; then
-			. ${subrdir}/jcreate.subr               # for export_jail_data_for_external_hook
-			geniplist ${ip4_addr}                   # for ipvX_first_public-like vars
+			. "${subrdir}"/jcreate.subr               # for export_jail_data_for_external_hook
+			geniplist "${ip4_addr}"                   # for ipvX_first_public-like vars
 			export_jail_data_for_external_hook
-			_val=$( ${jailsysdir}/${jname}/facts.d/${_i} | ${HEAD_CMD} -1 | ${AWK_CMD} '{printf $1}' )
+			_val=$( "${jailsysdir}"/"${jname}"/facts.d/"${_i}" | ${HEAD_CMD} -1 | ${AWK_CMD} '{printf $1}' )
 		else
 			case "${_i}" in
 				vm_ram)
@@ -246,7 +246,7 @@ populate_output_data()
 					fi
 					;;
 				vnc_port)
-					_tmpport=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vm_vnc_port FROM settings LIMIT 1" )
+					_tmpport=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT vm_vnc_port FROM settings LIMIT 1" )
 					if [ -n "${_tmpport}" ]; then
 						_val="${_tmpport}"
 					else
@@ -254,14 +254,14 @@ populate_output_data()
 					fi
 					;;
 				vnc)
-					_tmpport=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vm_vnc_port FROM settings LIMIT 1" )
+					_tmpport=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT vm_vnc_port FROM settings LIMIT 1" )
 					if [ -n "${_tmpport}" ]; then
-						if [ -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
+						if [ -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
 							# we need for special route of tcpbind presentation for foreign xen. replace 0.0.0.0 by nodeip
 							if [ "${sqlfile}" != "local" ]; then
 								_tmpbind=$( cbsdsqlro ${sqlfile} "SELECT nodeip FROM local LIMIT 1" 2>/dev/null )
 							else
-								_tmpbind=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT xen_vnc_tcp_bind FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
+								_tmpbind=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT xen_vnc_tcp_bind FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
 							fi
 						else
 							_tmpbind="Unk"
@@ -272,16 +272,16 @@ populate_output_data()
 					fi
 					;;
 				ip4_addr)
-					if [ -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
-						_val=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT ip4_addr FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
+					if [ -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
+						_val=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT ip4_addr FROM settings ORDER BY (created) DESC LIMIT 1" 2>/dev/null )
 					else
 						_val="Unk"
 					fi
 					[ "${_val}" = "(null)" ] && _val="DHCP"
 					;;
 				vm_zfs_guid)
-					if [ -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
-						_val=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vm_zfs_guid FROM settings LIMIT 1" 2>/dev/null )
+					if [ -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
+						_val=$( cbsdsqlro "${sqlfile_sysdir}"/"${jname}"/local.sqlite "SELECT vm_zfs_guid FROM settings LIMIT 1" 2>/dev/null )
 					else
 						_val="0"
 					fi
@@ -322,22 +322,22 @@ show_jaildata_from_sql()
 		_status=
 
 		if [ "${sqlfile}" = "local" ]; then
-			. ${subrdir}/rcconf.subr
+			. "${subrdir}"/rcconf.subr
 		else
 			RHST="${sqlfile}"
-			. ${subrdir}/rrcconf.subr
+			. "${subrdir}"/rrcconf.subr
 		fi
 
 		# skip hidden env when show_hidden=0
 		[ ${hidden} -eq 1 -a ${show_hidden} -eq 0 ] && continue
-		if [ ! -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
+		if [ ! -r "${sqlfile_sysdir}"/"${jname}"/local.sqlite ]; then
 			# skip invalid vms
-			${ECHO} "${N1_COLOR}Can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}" >> ${my_err_file}
+			${ECHO} "${N1_COLOR}Can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}" >> "${my_err_file}"
 			continue
 		fi
 
 		conv_status
-		populate_output_data -j ${jname} -s ${sqlfile}
+		populate_output_data -j "${jname}" -s ${sqlfile}
 	done
 }
 
@@ -362,16 +362,16 @@ show_local()
 	status="-"
 	vnc="-"
 
-	for J in $( ${LS_CMD} ${jailrcconfdir} ); do
+	for J in $( ${LS_CMD} "${jailrcconfdir}" ); do
 		[ "${J}" = "dir.id" ] && continue
 		jname=
-		[ ! -r ${jailrcconfdir}/${J} ] && continue
-		. ${jailrcconfdir}/${J}
+		[ ! -r "${jailrcconfdir}"/"${J}" ] && continue
+		. "${jailrcconfdir}"/"${J}"
 		# for XEN vm only
 		[ "${emulator}" != "xen" ] && continue
 		[ -z "${jname}" ] && continue
-		populate_output_data -u 1 -j ${jname}
-		${ECHO} ${_status}
+		populate_output_data -u 1 -j "${jname}"
+		${ECHO} "${_status}"
 	done
 }
 
@@ -385,8 +385,8 @@ show_remote()
 	for _n in ${node}; do
 		nodename="${_n}"
 		# init and export into $node_${md5_node_name}_online node status
-		node_is_online -n ${nodename} -e 1
-		show_jaildata_from_sql ${_n}
+		node_is_online -n "${nodename}" -e 1
+		show_jaildata_from_sql "${_n}"
 	done
 }
 
@@ -406,7 +406,7 @@ show_jails()
 	fi
 }
 
-. ${subrdir}/jrctl.subr
+. "${subrdir}"/jrctl.subr
 
 #### MAIN
 [ -z "${header}" ] && header=1
@@ -415,10 +415,10 @@ sqldelimer=" "
 my_err_file="${ftmpdir}/ls.$$"
 show_jails | ${COLUMN_CMD} -t
 
-if [ -r ${my_err_file} ]; then
+if [ -r "${my_err_file}" ]; then
 	${ECHO} "${N1_COLOR}Error:${N0_COLOR}" 1>&2
-	${CAT_CMD} ${my_err_file} 1>&2
-	${RM_CMD} -f ${my_err_file}
+	${CAT_CMD} "${my_err_file}" 1>&2
+	${RM_CMD} -f "${my_err_file}"
 fi
 
 exit 0
