bump version

diff --git a/jailctl/bls b/jailctl/bls
--- a/jailctl/bls
+++ b/jailctl/bls
@@ -27,6 +27,8 @@ EXTHELP="wf_bls"
 readconf bls.conf
 . ${cbsdinit}
 
+[ ! -d "${workdir}" ] && err 1 "${N1_COLOR}jls: no such workdir: ${N2_COLOR}${workdir}${N0_COLOR}"
+
 [ -n "${display}" ] && odisplay="${display}"	# store original display settings
 oalljails="${alljails}"				# store original settings, they have more weight vs auto
 oshownode="${shownode}"				# store original settings, they have more weight vs auto
@@ -97,7 +99,6 @@ conv_status()
 			;;
 	esac
 }
-
 
 show_header()
 {
@@ -175,7 +176,6 @@ populate_output_data()
 			printf "${DGRAY}"
 		fi
 	fi
-
 
 	#populate values for in output string
 	for _i in ${mydisplay}; do
@@ -301,7 +301,6 @@ populate_output_data()
 	printf "${N0_COLOR}\n"
 }
 
-
 # $1 - which file from. Eg: local
 show_jaildata_from_sql()
 {
@@ -330,11 +329,16 @@ show_jaildata_from_sql()
 			. ${rjrcconf}
 		fi
 
+		if [ ! -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
+			# skip invalid vms
+			${ECHO} "${N1_COLOR}Can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}" >> ${my_err_file}
+			continue
+		fi
+
 		conv_status
 		populate_output_data -j ${jname} -s ${sqlfile}
 	done
 }
-
 
 show_local()
 {
@@ -369,7 +373,6 @@ show_local()
 		${ECHO} ${_status}
 	done
 }
-
 
 show_remote()
 {
@@ -407,4 +410,13 @@ show_jails()
 [ -z "${header}" ] && header=1
 sqldelimer=" "
 
+my_err_file="${ftmpdir}/ls.$$"
 show_jails | /usr/bin/column -t
+
+if [ -r ${my_err_file} ]; then
+	${ECHO} "${N1_COLOR}Error:${N0_COLOR}" 1>&2
+	/bin/cat ${my_err_file} 1>&2
+	/bin/rm -f ${my_err_file}
+fi
+
+exit 0
diff --git a/jailctl/xls b/jailctl/xls
--- a/jailctl/xls
+++ b/jailctl/xls
@@ -270,6 +270,12 @@ show_jaildata_from_sql()
 			. ${rjrcconf}
 		fi
 
+		if [ ! -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
+			# skip invalid vms
+			${ECHO} "${N1_COLOR}Can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}" >> ${my_err_file}
+			continue
+		fi
+
 		conv_status
 		populate_output_data -j ${jname} -s ${sqlfile}
 	done
@@ -347,4 +353,13 @@ show_jails()
 [ -z "${header}" ] && header=1
 sqldelimer=" "
 
+my_err_file="${ftmpdir}/ls.$$"
 show_jails | /usr/bin/column -t
+
+if [ -r ${my_err_file} ]; then
+	${ECHO} "${N1_COLOR}Error:${N0_COLOR}" 1>&2
+	/bin/cat ${my_err_file} 1>&2
+	/bin/rm -f ${my_err_file}
+fi
+
+exit 0
diff --git a/sudoexec/junregister b/sudoexec/junregister
--- a/sudoexec/junregister
+++ b/sudoexec/junregister
@@ -108,15 +108,17 @@ else
 	JAILRCCONF="${rcfile}"
 fi
 
-if [ -r ${JAILRCCONF} ]; then
-	jmkrcconf jname=${jname} > ${JAILRCCONF}
-	res=$( replacewdir file0="${JAILRCCONF}" old=${workdir} new="CBSDROOT" )
-	_ret=$?
+CONF_DIR=$( /usr/bin/dirname ${JAILRCCONF} )
+[ ! -d "${CONF_DIR}" ] && /bin/mkdir -m 0755 -p ${CONF_DIR}
+[ ! -d "${CONF_DIR}" ] && err 1 "${N1_COLOR}no such dir: ${N2_COLOR}${CONF_DIR}${N0_COLOR}"
 
-	if [ ${_ret} -ne 0 ]; then
-		/bin/rm -f ${JAILRCCONF}
-		err 1 "${N1_COLOR}Error replacewdir for ${JAILRCCONF}: ${res}${N0_COLOR}"
-	fi
+jmkrcconf jname=${jname} > ${JAILRCCONF}
+res=$( replacewdir file0="${JAILRCCONF}" old=${workdir} new="CBSDROOT" )
+_ret=$?
+
+if [ ${_ret} -ne 0 ]; then
+	/bin/rm -f ${JAILRCCONF}
+	err 1 "${N1_COLOR}Error replacewdir for ${JAILRCCONF}: ${res}${N0_COLOR}"
 fi
 
 if [ -r ${mount_fstab} ]; then
diff --git a/tools/bhyve-dsk b/tools/bhyve-dsk
--- a/tools/bhyve-dsk
+++ b/tools/bhyve-dsk
@@ -9,11 +9,12 @@ ADDHELP="mode=attach,detach,remove,list,modify\n\
   - attach - create and attach new disk\n\
   - detach - detach disk from controller (without removing dsk)\n\
   - delete|remove - detach and remove disk\n\
-  - modify - modify disk properties (e.g: bootable=, dsk_sectorsize=)\n\
+  - modify - modify disk properties (e.g: bootable=, dsk_sectorsize=, dsk_size=, ..)\n\
   - get_next_free_dsk - out next available dsk name for jname\n\
  modify properties:\n\
   - bootable - set bootable flag (1 - true, - false)\n\
   - dsk_sectorsize - set sectorsize (e.g: 512, 4096, 512/4096)\n\
+  - dsk_size - increase disk size (e.g: 20g, +30g )\n\
   - dsk_zfs_guid - can be: 'auto'\n\
  mode=attach properties:\n\
   zvol_opts - pass ZFS volume options, e.g: zvol_opts=\"dedup=on sync=disabled\"\n\
@@ -32,7 +33,7 @@ dsk_mbps_limit=
 zvol_opts=
 . ${cbsdinit}
 
-available_properties="bootable dsk_sectorsize dsk_zfs_guid dsk_iops_limit dsk_mbps_limit"
+available_properties="bootable dsk_sectorsize dsk_zfs_guid dsk_iops_limit dsk_mbps_limit dsk_size"
 available_get_properties="dsk_path bootable dsk_sectorsize dsk_zfs_guid dsk_iops_limit dsk_mbps_limit"
 
 . ${distdir}/bhyve.subr
@@ -262,7 +263,7 @@ dsk_modify_bootable()
 			;;
 	esac
 
-	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET bootable=${_bootable} WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}\"
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET bootable=${_bootable} WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}.vhd\"
 	return 0
 }
 
@@ -297,10 +298,10 @@ dsk_modify_dsk_sectorsize()
 
 	[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && err 1 "${N1_COLOR}No such database: ${N2_COLOR}${jailsysdir}/${jname}/local.sqlite${N0_COLOR}"
 
-	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_sectorsize FROM bhyvedsk WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
+	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_sectorsize FROM bhyvedsk WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}.vhd\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
 	[ -z "${_old_val}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to get current dsk_sectorsize values for: dsk_controller=${N2_COLOR}${dsk_controller}${N1_COLOR} AND dsk_path=${N2_COLOR}${dsk_path}${N0_COLOR}"
 	[ "${_old_val}" = "${dsk_sectorsize}" ] && return 0
-	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_sectorsize=\"${dsk_sectorsize}\" WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}\"
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_sectorsize=\"${dsk_sectorsize}\" WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}.vhd\"
 
 	cbsdlogger NOTICE "${CBSD_APP}: modify sectorsize ${_old_val} -> ${dsk_sectorsize} (controller: ${dsk_controller}, dsk: ${dsk_path})"
 	${ECHO} "${N1_COLOR}dsk_sectorsize: ${N2_COLOR}changed${N0_COLOR}"
@@ -342,10 +343,10 @@ dsk_modify_dsk_zfs_guid()
 
 	[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && err 1 "${N1_COLOR}No such database: ${N2_COLOR}${jailsysdir}/${jname}/local.sqlite${N0_COLOR}"
 
-	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_zfs_guid FROM bhyvedsk WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
+	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_zfs_guid FROM bhyvedsk WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}.vhd\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
 	[ -z "${_old_val}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to get current dsk_zfs_guid values for: dsk_controller=${N2_COLOR}${dsk_controller}${N1_COLOR} AND dsk_path=${N2_COLOR}${dsk_path}${N0_COLOR}"
 
-	_dsk_fullpath="${jaildatadir}/${jname}-${jaildatapref}/${dsk_path}"
+	_dsk_fullpath="${jaildatadir}/${jname}-${jaildatapref}/${dsk_path}.vhd"
 
 	. ${zfstool}
 
@@ -354,9 +355,76 @@ dsk_modify_dsk_zfs_guid()
 	[ ${_ret} -ne 0 ] && err 0 "${N1_COLOR}skipp dsk_modify_dsk_zfs_guid error: unable to determine guid for: ${N2_COLOR}${_dsk_fullpath}${N0_COLOR}"
 	[ -z "${_res}" ] && err 0 "${N1_COLOR}skipp dsk_modify_dsk_zfs_guid error: unable to determine guid for: ${N2_COLOR}${_is_zvol}${N0_COLOR}"
 	[ "${_old_val}" = "${_res}" ] && return 0
-	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_zfs_guid=\"${_res}\" WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}\"
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_zfs_guid=\"${_res}\" WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}.vhd\"
 	cbsdlogger NOTICE "${CBSD_APP}: modify dsk_zfs_guid ${_old_val} -> ${dsk_sectorsize} (controller: ${dsk_controller}, dsk: ${dsk_path})"
 	${ECHO} "${N1_COLOR}dsk_zfs_guid: ${N2_COLOR}changed${N0_COLOR}"
+	return 0
+}
+
+dsk_modify_dsk_size()
+{
+	local _res _old_val _new_val tmp_zvol= _is_zvol
+	local _dsk_fullpath _zvol_pref= _ret
+
+	[ ${zfsfeat} -ne 1 ] && err 1 "${N1_COLOR}zfsfeat disabled${N0_COLOR}"
+
+	for i in jname dsk_controller dsk_path; do
+		_val=
+		eval _val="\$$i"
+		case "${i}" in
+			dsk_path)
+				[ -z "${_val}" ] && err 1 "${N1_COLOR}bhyve-dsk error: ${N2_COLOR}${i}= ${N1_COLOR}is mandatory${N0_COLOR}"
+				# trim .vhd if necessary
+				dsk_path=$( echo ${_val} | /usr/bin/sed 's:\.vhd::g' )
+				;;
+			dsk_controller)
+				[ -z "${_val}" ] && err 1 "${N1_COLOR}bhyve-dsk error: ${N2_COLOR}${i}= ${N1_COLOR}is mandatory${N0_COLOR}"
+				# check for valid controller
+				case "${_val}" in
+					virtio-blk|ahci-hd)
+						;;
+					*)
+						err 1 "${N1_COLOR}bhyve-dsk error: bhyve-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}virtio-blk, ahci-hd${N0_COLOR}"
+						;;
+				esac
+				;;
+		esac
+
+		[ -z "${_val}" ] && err 1 "${N1_COLOR}bhyve-dsk error: ${N2_COLOR}${i}= ${N1_COLOR}is mandatory${N0_COLOR}"
+	done
+
+	[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && err 1 "${N1_COLOR}No such database: ${N2_COLOR}${jailsysdir}/${jname}/local.sqlite${N0_COLOR}"
+	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_size FROM bhyvedsk WHERE dsk_controller=\"${dsk_controller}\" AND dsk_path=\"${dsk_path}.vhd\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
+	[ -z "${_old_val}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to get current dsk_size values for: dsk_controller=${N2_COLOR}${dsk_controller}${N1_COLOR} AND dsk_path=${N2_COLOR}${dsk_path}${N0_COLOR}"
+
+	if is_number "${dsk_size}"; then
+		if conv2bytes ${dsk_size}; then
+			_new_val="${convval}"
+		else
+			err 1 "${N1_COLOR}${CBSD_APP}: unable convert values to bytes: ${N2_COLOR}${dsk_size}${N0_COLOR}"
+		fi
+	else
+		# already in bytes?
+		_new_val="${dsk_size}"
+	fi
+
+	if [ ${_old_val} -gt ${_new_val} ]; then
+		${ECHO} "${N1_COLOR}${CBSD_APP}: disk reduction is not yet supported${N0_COLOR}"
+		err 1 "${N1_COLOR}new dsk_size must be larger than the old values ( >${N2_COLOR}${_old_val}${N1_COLOR} bytes )${N0_COLOR}"
+	fi
+
+	# check for available disksize/overcommiting ?
+	_dsk_fullpath="${jaildatadir}/${jname}-${jaildatapref}/${dsk_path}.vhd"
+
+	modify_dsk_size -f ${_dsk_fullpath} -s "${_new_val}"
+	_ret=$?
+	[ ${_ret} -ne 0 ] && return ${_ret}
+
+	# update
+	populate_dsk_size
+	# update values in table
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_size=\"${dsk_bsize}\" WHERE dsk_path=\"${dsk_path}\"
+	${ECHO} "${N1_COLOR}dsk_size: ${N2_COLOR}changed${N0_COLOR}"
 	return 0
 }
 
