bhyve live migration support, finalize: [3/3]
CBSD now support for bhyve live migration.

todo: more error handling, regression test, cpu/feature comparison

diff --git a/jailctl/bmigrate b/jailctl/bmigrate
--- a/jailctl/bmigrate
+++ b/jailctl/bmigrate
@@ -103,24 +103,92 @@ else
 fi
 
 ${ECHO} ${MAGENTA} "  ${GREEN}Preparing destination node...${NORMAL}"
-${ECHO} "${CYAN}[debug]remote cmd: /usr/sbin/bhyve -c 1 -m 1073741824 -H -A -s 0:0,hostbridge -s 2:0,virtio-blk,/usr/jails/jails-data/freebsd1-data/dsk1.vhd,sectorsize=512 -s 6,fbuf,tcp=127.0.0.1:5900,w=1024,h=768 -s 31,lpc -l com1,stdio -l bootrom,/usr/local/cbsd/upgrade/patch/efi.fd -R 192.168.84.96,24983 freebsd1${NORMAL}"
+${ECHO} "${CYAN}     [debug]remote cmd: /usr/sbin/bhyve -c 1 -m 1073741824 -H -A -s 0:0,hostbridge -s 2:0,virtio-blk,/usr/jails/jails-data/freebsd1-data/dsk1.vhd,sectorsize=512 -s 6,fbuf,tcp=127.0.0.1:5900,w=1024,h=768 -s 31,lpc -l com1,stdio -l bootrom,/usr/local/cbsd/upgrade/patch/efi.fd -R 192.168.84.96,24983 freebsd1${NORMAL}"
 
-printf "   ${LCYAN}* ${MAGENTA}Phase1: launch bhyve on remote node ... ${NORMAL}"
+printf "   ${LCYAN}* ${MAGENTA}Phase1: launch ${jname} domain on remote node ... ${NORMAL}"
 
-r_task_id=$( rexe node=${node} cbsd task mode=new owner=migration.$$ /usr/sbin/bhyve -c 1 -m 1073741824 -H -A -s 0:0,hostbridge -s 2:0,virtio-blk,/usr/jails/jails-data/freebsd1-data/dsk1.vhd,sectorsize=512 -s 5:0,virtio-rnd -s 6,fbuf,tcp=127.0.0.1:5900,w=1024,h=768,password=cbsd -s 30,xhci,tablet -s 31,lpc -l com1,stdio -l bootrom,/usr/local/cbsd/upgrade/patch/efi.fd -R 192.168.84.96,24983 freebsd1 | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+# remove old live migration config
+/bin/rm -f ${jailsysdir}/${jname}/live_migration.conf
 
+r_task_id=$( rexe node=${node} cbsd task mode=new owner=migration.$$ /usr/local/bin/cbsd bstart jname=${jname} lm=1 | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
 [ -z "${r_task_id}" ] && err 1 "${MAGENTA}cbsd task on ${node} failed${NORMAL}"
 
 printf "${LYELLOW}ok${NORMAL}"
 echo
-printf "   ${LCYAN}* ${MAGENTA}Phase2: waiting for bhyve instance ready by task id ${r_task_id} ${NORMAL}"
+printf "   ${LCYAN}* ${MAGENTA}Phase2: waiting for bhyve instance ready by task id ${GREEN}${r_task_id}${MAGENTA}...${NORMAL}"
 
 max_attempt=15
 cur_attempt=0
 
-for i in $( /usr/bin/seq 1 10 ); do
+for i in $( /usr/bin/seq 1 ${max_attempt} ); do
 	cur_attempt=$(( cur_attempt + 1 ))
-	#echo "rexe node=${node} /usr/local/bin/sqlite3 ~cbsd/var/db/cbsdtaskd.sqlite SELECT status FROM taskd WHERE id=\"${r_task_id}\""
+	if [ ! -r ${jailsysdir}/${jname}/live_migration.conf ]; then
+		sleep 1
+		continue
+	fi
+	r_job_status=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT status FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+	if [ "${r_job_status}" != "1" ]; then
+		printf "${MAGENTA}.${NORMAL}"
+		sleep 1
+	else
+		printf "${LYELLOW} ok${NORMAL}"
+		break
+	fi
+done
+
+echo
+[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
+
+# waiting for config
+max_attempt=5
+cur_attempt=0
+
+printf "   ${LCYAN}* ${MAGENTA}Phase3: waiting for migration configuration...${NORMAL}"
+
+for i in $( /usr/bin/seq 1 ${max_attempt} ); do
+	cur_attempt=$(( cur_attempt + 1 ))
+	r_job_status=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT status FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+	if [ "${r_job_status}" != "1" ]; then
+		printf "${MAGENTA}.${NORMAL}"
+		sleep 1
+	else
+		printf "${LYELLOW} ok${NORMAL}"
+		break
+	fi
+done
+
+echo
+[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
+
+live_migration_src_nodename=
+live_migration_dst_nodename=
+live_migration_dst_port=
+live_migration_src_nodename_ip=
+live_migration_dst_nodename_ip=
+
+. ${jailsysdir}/${jname}/live_migration.conf
+
+${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_src_nodename: ${GREEN}${live_migration_src_nodename}${NORMAL}"
+${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_dst_nodename: ${GREEN}${live_migration_dst_nodename}${NORMAL}"
+${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_dst_port: ${GREEN}${live_migration_dst_port}${NORMAL}"
+${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_src_nodename_ip: ${GREEN}${live_migration_src_nodename_ip}${NORMAL}"
+${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_dst_nodename_ip: ${GREEN}${live_migration_dst_nodename_ip}${NORMAL}"
+
+r_job_logfile=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT logfile FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+sleep 1
+${ECHO} "   ${LCYAN}* ${MAGENTA}Phase3: migration, please wait...${NORMAL}"
+${ECHO} "${CYAN}     [debug]remote cmd: bhyvectl --migrate=${live_migration_dst_nodename_ip},${live_migration_dst_port} --vm=${jname}${NORMAL}"
+
+/usr/sbin/bhyvectl --migrate=${live_migration_dst_nodename_ip},${live_migration_dst_port} --vm=${jname}
+
+# waiting for config
+max_attempt=5
+cur_attempt=0
+
+printf "   ${LCYAN}* ${MAGENTA}Phase4: Waiting for task finished: ${GREEN}${r_task_id}...${NORMAL}"
+
+for i in $( /usr/bin/seq 1 ${max_attempt} ); do
+	cur_attempt=$(( cur_attempt + 1 ))
 	r_job_status=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT status FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
 	if [ "${r_job_status}" != "2" ]; then
 		printf "${MAGENTA}.${NORMAL}"
@@ -129,22 +197,44 @@ for i in $( /usr/bin/seq 1 10 ); do
 		printf "${LYELLOW} ok${NORMAL}"
 		break
 	fi
-	[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
 done
 
-r_job_logfile=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT logfile FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
-${ECHO} "   ${LCYAN}* ${MAGENTA}Phase3: migration: bhyvectl --migrate=${remote_node_rip},24983 --vm=${jname}${NORMAL}"
-bhyvectl --migrate=${remote_node_rip},24983 --vm=${jname}
 echo
-sleep 3
-${ECHO} "      ${MAGENTA}Remote log for taskid ${LYELLOW}${r_task_id}${MAGENTA}:${NORMAL}"
-rexe node=${node} /bin/cat ${r_job_logfile}
-echo
-printf "   ${LCYAN}* ${MAGENTA}Phase3: migration to bhyve ${LYELLOW}${r_task_id} ${NORMAL}"
-echo
-${ECHO} "   ${LCYAN}* ${MAGENTA}Phase4: unregister ${jname} on ${my_nodename}${NORMAL}"
-#bunregister jname=${jname}
-${ECHO} "   ${LCYAN}* ${MAGENTA}Phase5: register ${jname} on ${remote_node_name}${NORMAL}"
-#rexe node=${node} cbsd bregister jname=${jname}
+[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
 
-#bunregister jname=${jname}
+${ECHO} "      ${MAGENTA}Remote log for taskid ${LYELLOW}${r_task_id}${MAGENTA}: ${GREEN}${r_job_logfile}${MAGENTA}:${NORMAL}"
+${ECHO} "${LCYAN}----------------------${WHITE}${BOLD}[log]${LCYAN}----------------------${NORMAL}"
+rexe node=${node} /bin/cat ${r_job_logfile}
+${ECHO} "${LCYAN}----------------------${WHITE}${BOLD}[log]${LCYAN}----------------------${NORMAL}"
+echo
+printf "   ${LCYAN}* ${MAGENTA}Phase5: waiting for the bhyve process to go away${NORMAL}"
+
+# waiting for config
+max_attempt=20
+cur_attempt=0
+
+for i in $( /usr/bin/seq 1 ${max_attempt} ); do
+	cur_attempt=$(( cur_attempt + 1 ))
+	if [ -e "/dev/vmm/${jname}" ]; then
+		printf "${MAGENTA}.${NORMAL}"
+		sleep 3
+	else
+		printf "${LYELLOW} ok${NORMAL}"
+		break
+	fi
+done
+
+echo
+. ${jrcconf} > /dev/null 2>&1
+[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Error: bhyve stile alive!${NORMAL}"
+${ECHO} "   ${LCYAN}* ${MAGENTA}Phase6: unregister ${jname} on ${my_nodename}${NORMAL}"
+bunregister jname=${jname}
+
+[ $? -ne 0 ] && err 1 "${MAGENTA}Unregister error${NORMAL}"
+# lets wait for file saved
+sleep 3
+
+${ECHO} "   ${LCYAN}* ${MAGENTA}Phase7: register ${jname} on ${remote_node_name}${NORMAL}"
+rexe node=${node} cbsd bregister jname=${jname}
+retrinv node=${remote_node_name} > /dev/null 2>&1
+rexe node=${node} cbsd retrinv node=${my_nodename} > /dev/null 2>&1
