bmigrate: better error handler
also create sudoexec tools/bhyve-exist script for external checking bhyve process
existance (without [jb]status and local base) - just check process list for bhyve.
this is used by live migration (for example), when the source node should make sure
that the destination node  has/got a working bhyve process

diff --git a/jailctl/bmigrate b/jailctl/bmigrate
--- a/jailctl/bmigrate
+++ b/jailctl/bmigrate
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v11.2.0
+#v12.0.0
 MYARG="jname node"
 MYOPTARG=""
 MYDESC="bhyve live migration"
@@ -29,6 +29,12 @@ d_cbsd_ver=$( rexe node=${node} /usr/local/bin/cbsd -c version 2>/dev/null | /us
 printf "${LYELLOW}ok${NORMAL}"
 echo
 s_cbsd_ver=$( version | /usr/bin/awk '/./{print $1}' )
+
+# Check for compiatible 
+# - todo: CPU features/modesl check
+# - todo: Memory/free amount check
+remote_process_status=$( rexe node=${node} /usr/local/bin/cbsd bhyve-exist jname=${jname} | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+[ -n "${remote_process_status}" ] && err 1 "${MAGENTA}bmigrate error: node ${GREEN}${jname}${MAGENTA} already has the running bhyve process with jname: ${GREEN}${jname}${NORMAL}"
 
 shared_dir="jails-data jails-rcconf jails-system"
 
@@ -109,26 +115,28 @@ printf "   ${LCYAN}* ${MAGENTA}Phase1: launch ${jname} domain on remote node ...
 # remove old live migration config
 /bin/rm -f ${jailsysdir}/${jname}/live_migration.conf
 
-r_task_id=$( rexe node=${node} cbsd task mode=new owner=migration.$$ /usr/local/bin/cbsd bstart jname=${jname} lm=1 | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
-[ -z "${r_task_id}" ] && err 1 "${MAGENTA}cbsd task on ${node} failed${NORMAL}"
+r_task_id=$( rexe node=${node} /usr/local/bin/cbsd task mode=new owner=migration.$$ /usr/local/bin/cbsd bstart jname=${jname} lm=1 | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+[ -z "${r_task_id}" ] && err 1 "${MAGENTA}cbsd task on ${node} failed: no task id${NORMAL}"
 
+sleep 1
 printf "${LYELLOW}ok${NORMAL}"
-echo
-printf "   ${LCYAN}* ${MAGENTA}Phase2: waiting for bhyve instance ready by task id ${GREEN}${r_task_id}${MAGENTA}...${NORMAL}"
 
-max_attempt=15
+### test 1: waiting for remote bhyve is running
+echo
+printf "   ${LCYAN}* ${MAGENTA}Phase2 (1/3): waiting for bhyve instance ready by task id ${GREEN}${r_task_id}${MAGENTA}...${NORMAL}"
+max_attempt=7		# ( sleep 2 x 7 = 14 seconds for run: this should be enough )
 cur_attempt=0
 
 for i in $( /usr/bin/seq 1 ${max_attempt} ); do
 	cur_attempt=$(( cur_attempt + 1 ))
 	if [ ! -r ${jailsysdir}/${jname}/live_migration.conf ]; then
-		sleep 1
+		sleep 2
 		continue
 	fi
 	r_job_status=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT status FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
 	if [ "${r_job_status}" != "1" ]; then
 		printf "${MAGENTA}.${NORMAL}"
-		sleep 1
+		sleep 2
 	else
 		printf "${LYELLOW} ok${NORMAL}"
 		break
@@ -138,26 +146,9 @@ done
 echo
 [ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
 
-# waiting for config
-max_attempt=5
-cur_attempt=0
-
-printf "   ${LCYAN}* ${MAGENTA}Phase3: waiting for migration configuration...${NORMAL}"
-
-for i in $( /usr/bin/seq 1 ${max_attempt} ); do
-	cur_attempt=$(( cur_attempt + 1 ))
-	r_job_status=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT status FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
-	if [ "${r_job_status}" != "1" ]; then
-		printf "${MAGENTA}.${NORMAL}"
-		sleep 1
-	else
-		printf "${LYELLOW} ok${NORMAL}"
-		break
-	fi
-done
-
+### test 2: check config
 echo
-[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
+printf "   ${LCYAN}* ${MAGENTA}Phase2 (2/3): check migration configuration, task id ${GREEN}${r_task_id}${MAGENTA}...${NORMAL}"
 
 live_migration_src_nodename=
 live_migration_dst_nodename=
@@ -167,20 +158,67 @@ live_migration_dst_nodename_ip=
 
 . ${jailsysdir}/${jname}/live_migration.conf
 
+# trap for cleanup
+trap "cbsd rexe node=${node} /usr/local/bin/cbsd task mode=new owner=migration.$$ /usr/local/bin/cbsd bstop jname=${jname} lm=1" HUP INT ABRT BUS TERM EXIT
+
+[ -z "${live_migration_src_nodename}" ] && err 1 "${MAGENTA}Empty ${live_migration_src_nodename}${NORMAL}"
+[ -z "${live_migration_dst_nodename}" ] && err 1 "${MAGENTA}Empty ${live_migration_dst_nodename}${NORMAL}"
+[ -z "${live_migration_dst_port}" ] && err 1 "${MAGENTA}Empty ${live_migration_dst_port}${NORMAL}"
+[ -z "${live_migration_src_nodename_ip}" ] && err 1 "${MAGENTA}Empty ${live_migration_src_nodename_ip}${NORMAL}"
+[ -z "${live_migration_dst_nodename_ip}" ] && err 1 "${MAGENTA}Empty ${live_migration_dst_nodename_ip}${NORMAL}"
+
+echo
 ${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_src_nodename: ${GREEN}${live_migration_src_nodename}${NORMAL}"
 ${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_dst_nodename: ${GREEN}${live_migration_dst_nodename}${NORMAL}"
 ${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_dst_port: ${GREEN}${live_migration_dst_port}${NORMAL}"
 ${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_src_nodename_ip: ${GREEN}${live_migration_src_nodename_ip}${NORMAL}"
 ${ECHO} "    ${LCYAN}- (cfg) ${MAGENTA}live_migration_dst_nodename_ip: ${GREEN}${live_migration_dst_nodename_ip}${NORMAL}"
 
+### test 3: waiting for bind/socket's open
+echo
+printf "   ${LCYAN}* ${MAGENTA}Phase2 (3/3): check for remote host bind/socket's open, task id ${GREEN}${r_task_id}${MAGENTA}...${NORMAL}"
+# waiting for remote bhyve is running
+max_attempt=3		# sleep 2 x 3 = 6 seconds for run: this should be enough
+cur_attempt=0
+
+. ${workdir}/virtual.subr	# for get_next_tcp_port
+
+for i in $( /usr/bin/seq 1 ${max_attempt} ); do
+	cur_attempt=$(( cur_attempt + 1 ))
+
+	# scan by next_tcp_port
+	_tmp=$( get_next_tcp_port -a ${live_migration_src_nodename_ip} -e ${live_migration_dst_port} -s ${live_migration_dst_port} )
+	if [ "${_tmp}" != "0" ]; then
+		printf "${MAGENTA}.${NORMAL}"
+		sleep 2
+	else
+		printf "${LYELLOW} ok${NORMAL}"
+		break
+	fi
+done
+
+echo
+[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
+
 r_job_logfile=$( cbsd rexe node=${node} misc/sqlcli var/db/cbsdtaskd.sqlite "SELECT logfile FROM taskd WHERE id=${r_task_id}" 2>/dev/null | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
 sleep 1
 ${ECHO} "   ${LCYAN}* ${MAGENTA}Phase3: migration, please wait...${NORMAL}"
 ${ECHO} "${CYAN}     [debug]remote cmd: bhyvectl --migrate=${live_migration_dst_nodename_ip},${live_migration_dst_port} --vm=${jname}${NORMAL}"
 
+# clean trap
+trap "date > /dev/null" HUP INT ABRT BUS TERM EXIT
+
 /usr/sbin/bhyvectl --migrate=${live_migration_dst_nodename_ip},${live_migration_dst_port} --vm=${jname}
 
-# waiting for config
+bhyve_migrate_ret=$?
+bhyve_remote_task_complete=0
+
+# Well, at this point, we no longer know in what state everything is 
+# and we need to monitor both systems to draw some conclusions.
+# First: let's wait for the completion of the remote task
+# Second: find bhyve process with ${jname} on both host
+
+# waiting for task finished
 max_attempt=5
 cur_attempt=0
 
@@ -199,12 +237,19 @@ for i in $( /usr/bin/seq 1 ${max_attempt} ); do
 done
 
 echo
-[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
+if [ ${cur_attempt} -gt ${max_attempt} ]; then
+	bhyve_remote_task_complete=1
+	${ECHO} "${LRED}bmigrate error: ${MAGENTA}Taskd timeout, max attempt exceeded: ${GREEN}${cur_attempt}${MAGENTA}. Please check on node ${GREEN}${node}${MAGENTA}: ${GREEN}cbsd taskls${NORMAL}"
+else
+	bhyve_remote_task_complete=1
+fi
 
 ${ECHO} "      ${MAGENTA}Remote log for taskid ${LYELLOW}${r_task_id}${MAGENTA}: ${GREEN}${r_job_logfile}${MAGENTA}:${NORMAL}"
 ${ECHO} "${LCYAN}----------------------${WHITE}${BOLD}[log]${LCYAN}----------------------${NORMAL}"
 rexe node=${node} /bin/cat ${r_job_logfile}
 ${ECHO} "${LCYAN}----------------------${WHITE}${BOLD}[log]${LCYAN}----------------------${NORMAL}"
+echo
+
 echo
 printf "   ${LCYAN}* ${MAGENTA}Phase5: waiting for the bhyve process to go away${NORMAL}"
 
@@ -224,16 +269,88 @@ for i in $( /usr/bin/seq 1 ${max_attempt} ); do
 done
 
 echo
+remote_process_status=$( rexe node=${node} /usr/local/bin/cbsd bhyve-exist jname=${jname} | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+local_process_status=$( bhyve-exist jname=${jname} | /usr/bin/tr -d \\r | /usr/bin/awk '/./{print $1}' )
+
+if [ -n "${remote_process_status}" ]; then
+	printf "     ${LCYAN}* ${MAGENTA}Phase5: remote bhyve process: ${LYELLOW}registered${NORMAL}"
+else
+	printf "     ${LCYAN}* ${MAGENTA}Phase5: remote bhyve process: ${LRED}not registered${NORMAL}"
+fi
+
+# Final status handler
+
+####### Remote side failed #####
+# Scenario 1: remote task log completed but no bhyve process: migration failed
+echo
+${ECHO} "${CYAN}     [debug]error handler: test 1${NORMAL}"
+if [ "${bhyve_remote_task_complete}" = "1" -a -z "${remote_process_status}" ]; then
+	err 1 "${MAGENTA}bmigrate: migration failed: task complete (id:${GREEN}${r_task_id}${MAGENTA}) but bhyve process is absent, check log${NORMAL}"
+fi
+
+${ECHO} "${CYAN}     [debug]error handler: test 2${NORMAL}"
+# Scenatio 2: remote task log still waiting but no bhyve process: migration failed
+if [ "${bhyve_remote_task_complete}" = "0" -a -z "${remote_process_status}" ]; then
+	${ECHO} "${MAGENTA}bmigrate: migration failed: task still in progress (id:${GREEN}${r_task_id}${MAGENTA}) but bhyve process is absent. Force to kill. Please check log${NORMAL}"
+	[ -z "${local_process_status}" ] && err 1 "${LRED}Warning: ${MAGENTA}No such bhyve process on current host, bhyve was crashed???${NORMAL}"
+	exit 1
+fi
+
+${ECHO} "${CYAN}     [debug]error handler: test 3${NORMAL}"
+# Scenario 3: remote node have bhyve process and local node have process, split brain, stop VM on remote node
+if [ -n "${remote_process_status}" -a -n "${local_process_status}" ]; then
+	${ECHO} "${MAGENTA}bmigrate: migration failed: Split brain: two bhyve process with ${GREEN}${jname}${MAGENTA} on both nodes. Force to kill on remote node. Please check log${NORMAL}"
+	exit 1
+fi
+
+${ECHO} "${CYAN}     [debug]error handler: test 4${NORMAL}"
+# Scenario 4: local node still have bhyve process with $jname and no bhyve process on remote
+if [ -z "${remote_process_status}" -a -n "${local_process_status}" ]; then
+	${ECHO} "${MAGENTA}bmigrate: migration failed: no bhyve process on remote node with ${GREEN}${jname}${MAGENTA} while local still has it. Please check log${NORMAL}"
+	exit 1
+fi
+
+# Now the last scenario remains - when everything went well
 . ${jrcconf} > /dev/null 2>&1
-[ ${cur_attempt} -gt ${max_attempt} ] && err 1 "${MAGENTA}Error: bhyve stile alive!${NORMAL}"
+
+# TODO: SQLite backup ?
 ${ECHO} "   ${LCYAN}* ${MAGENTA}Phase6: unregister ${jname} on ${my_nodename}${NORMAL}"
 bunregister jname=${jname}
 
-[ $? -ne 0 ] && err 1 "${MAGENTA}Unregister error${NORMAL}"
-# lets wait for file saved
-sleep 3
+if [ $? -ne 0 ]; then
+	${ECHO} "${LRED}Warning: ${MAGENTA}Unregister error: ${GREEN}${jname}${NORMAL}"
+	local_unregister=0
+else
+	local_unregister=1
+fi
+
+JAILRCCONF="${jailsysdir}/${jname}/rc.conf_${jname}"
+
+# lets wait for rc-conf file saved
+# waiting for config
+printf "   ${LCYAN}* ${MAGENTA}Phase7: waiting for rc.conf: ${NORMAL}"
+max_attempt=10
+cur_attempt=0
+
+for i in $( /usr/bin/seq 1 ${max_attempt} ); do
+	cur_attempt=$(( cur_attempt + 1 ))
+	if [ ! -r "${JAILRCCONF}" ]; then
+		printf "${MAGENTA}.${NORMAL}"
+		sleep 3
+	else
+		printf "${LYELLOW} ok${NORMAL}"
+		break
+	fi
+done
+
+echo
+if [ ${cur_attempt} -gt ${max_attempt} ]; then
+	${ECHO} "${MAGENTA}No rcconf saved. bregister on remode node is failed${NORMAL}"
+	# Restore backup from SQLite3? No RC Conf here?
+fi
 
 ${ECHO} "   ${LCYAN}* ${MAGENTA}Phase7: register ${jname} on ${remote_node_name}${NORMAL}"
-rexe node=${node} cbsd bregister jname=${jname}
+rexe node=${node} /usr/local/bin/cbsd bregister jname=${jname}
+${ECHO} "   ${LCYAN}* ${MAGENTA}Phase8: update inventory${NORMAL}"
 retrinv node=${remote_node_name} > /dev/null 2>&1
-rexe node=${node} cbsd retrinv node=${my_nodename} > /dev/null 2>&1
+rexe node=${node} /usr/local/bin/cbsd retrinv node=${my_nodename} > /dev/null 2>&1
