dhcpdv6: skip/lock file support

diff --git a/jailctl/bscp b/jailctl/bscp
--- a/jailctl/bscp
+++ b/jailctl/bscp
@@ -172,7 +172,24 @@ if [ ${cbsd_api} -eq 1 ]; then
 			scp_exec="${SCP_CMD} -oPort=${_ssh_port} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${1} ${_ssh_ip}:${rfile}"
 			echo "[debug] ${scp_exec}"
 		fi
-		${scp_exec}
+
+		_pass=0
+		_ret=0
+		_retry=0
+
+		while [ ${_pass} -ne 1 ]; do
+			${scp_exec}
+			_ret=$?
+			if [ ${_ret} -eq 0 ]; then
+				_pass=1
+				break
+			else
+				_retry=$(( _retry + 1 ))
+				[ ${_retry} -gt 3 ] && break
+				echo "[debug] error code: ${_ret}, retry ${_retry}/3: ${scp_exec}" 1>&2
+				sleep 1
+			fi
+		done
 	done
 	exit 0
 fi
