WIP: jscp/jexec/bscp/bexec,service,sysrc,pkg: support for CBSDfile/api

diff --git a/jailctl/bscp b/jailctl/bscp
--- a/jailctl/bscp
+++ b/jailctl/bscp
@@ -20,7 +20,7 @@ EXTHELP="wf_jailscp"
 . ${subr}
 . ${tools}
 . ${strings}
-
+cloud_api=0
 . ${cbsdinit}
 
 getjname()
@@ -51,6 +51,9 @@ try_remote()
 
 
 ### MAIN ###
+# change current dir
+cd ${CBSD_PWD}
+
 if [ -n "${verbose}" ]; then
 	shift
 else
@@ -93,6 +96,79 @@ fi
 [ -z "${jname}" -o -z "${dst}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: jail path via jail: path records not determine${N0_COLOR}"
 
 validate_jname "${jname}" || log_err 1 "${N1_COLOR}${CBSD_APP}: bad jname: ${jname}${N0_COLOR}"
+
+Makefile="${CBSD_PWD}/CBSDfile"
+if [ -r ${Makefile} ]; then
+	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
+	. ${Makefile}
+	all_bhyve_list=$( ${EGREP_CMD} '^bhyve_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#bhyve_##g )
+	if [ -n "${CLOUD_URL}" -a -n "${CLOUD_KEY}" ]; then
+		cbsd_api=1
+	else
+		cbsd_api=0
+	fi
+else
+	cbsd_api=0
+fi
+
+if [ ${cbsd_api} -eq 1 ]; then
+	CURL_CMD=$( which curl )
+	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
+	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
+	_cid=$( ${MD5_CMD} -qs "${CLOUD_KEY}" )
+
+	found=0
+	for i in ${all_bhyve_list}; do
+		if [ "${i}" = "${jname}" ]; then
+			found=1
+			break
+		fi
+	done
+	[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such bhyve: ${N2_COLOR}${jname}${N0_COLOR}"
+
+	for _jname in ${all_bhyve_list}; do
+		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${_jname} 2>&1 )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+			continue
+		fi
+		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh}" )
+		if [ "${_ssh_pref}" != "ssh" ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+			continue
+		fi
+		_ssh_len=$( strlen "${_ssh}" )
+		_ssh_post=$( substr --pos=5 --len=${_ssh_len} --str="${_ssh}" )
+		#echo "${SSH_CMD} ${_ssh_post}"
+		_ssh_ip=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $1}' )
+		_ssh_port=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $2}' | ${TR_CMD} -d '\-p' )
+		# rewrite
+		if [ -n "${SUDO_USER}" ]; then
+			if [ -r /home/${SUDO_USER}/.ssh/id_ed25519 ]; then
+				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_ed25519"
+			elif [ -r /home/${SUDO_USER}/.ssh/id_rsa ]; then
+				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_rsa"
+			else
+				date
+			fi
+		fi
+
+		if [ ${rarg} -eq 1 ]; then
+			DIR=$( ${DIRNAME_CMD} ${2} )
+			[ ! -d "${DIR}" ] && ${MKDIR_CMD} -p ${DIR}
+			scp_exec="${SCP_CMD} -oPort=${_ssh_port} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_ip}:${rfile} ${2}"
+			echo "[debug] ${scp_exec}"
+		else
+			scp_exec="${SCP_CMD} -oPort=${_ssh_port} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${1} ${_ssh_ip}:${rfile}"
+			echo "[debug] ${scp_exec}"
+		fi
+		${scp_exec}
+	done
+	exit 0
+fi
 
 . ${jrcconf}
 [ $? -eq 1 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such env: ${N2_COLOR}${jname}${N0_COLOR}"
diff --git a/tools/up b/tools/up
--- a/tools/up
+++ b/tools/up
@@ -61,6 +61,7 @@ bhyve_ssh_wait()
 		[ $? -eq 0 ] && break
 		_y=$(( _y + 1 ))
 		sleep 1
+		[ -z "${CBSDFILE_RECURSIVE}" ] && printf "." 1>&2
 		# todo: delete only ip
 		${ARP_CMD} -d -n ${ci_ip4_addr} > /dev/null 2>&1
 		if [ ${_y} -eq ${_attempt_max} ]; then
@@ -70,7 +71,9 @@ bhyve_ssh_wait()
 		fi
 	done
 
-	${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
+	# for ssh stabilization ;-(  retry ?
+	sleep 10
+	${ECHO} "${N1_COLOR}bhyve ssh available${N0_COLOR}"
 	# restore old settings
 	set ${_orig_options}
 
@@ -101,6 +104,7 @@ jail_ssh_wait()
 		[ ${_ret} -eq 0 ] && break
 		_y=$(( _y + 1 ))
 		sleep 1
+		[ -z "${CBSDFILE_RECURSIVE}" ] && printf "." 1>&2
 		# todo: delete only ip
 		${ARP_CMD} -d -n ${ci_ip4_addr} > /dev/null 2>&1
 		if [ ${_y} -eq ${_attempt_max} ]; then
@@ -110,7 +114,9 @@ jail_ssh_wait()
 		fi
 	done
 
-	${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
+	# for ssh stabilization
+	sleep 2
+	${ECHO} "${N1_COLOR}jail ssh available${N0_COLOR}"
 	# restore old settings
 	set ${_orig_options}
 
@@ -124,6 +130,7 @@ run_jail_cloud()
 	local CURL_CMD=$( which curl )
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
 	${ECHO} "${N1_COLOR}run image via: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}"
+	[ -z "${ssh_wait}" ] && ssh_wait=0
 
 	${CAT_CMD} > up-${jname}.json <<EOF
 {
@@ -133,6 +140,7 @@ run_jail_cloud()
   "cpus": "${vm_cpus}",
   "img": "${img}",
   "pkglist": "${pkglist}",
+  "tags": "${tags}",
   "pubkey": "${CLOUD_KEY}"
 }
 EOF
@@ -152,13 +160,11 @@ EOF
 		ret=0
 	fi
 	if [ ${ret} -eq 0 ]; then
-		${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
-
-		#bhyve_${jname}		# re-read variables
+		#jail_${jname}		# re-read variables
 
 		if fn_exists postcreate_${jname} 2>/dev/null; then
 			${ECHO} "${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
-			# cleanup bhyve when postcreate action failed
+			# cleanup jail when postcreate action failed
 			trap "set +o xtrace; ${ECHO} \"${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}: ${W1_COLOR}failed${N1_COLOR} : cleanup${N0_COLOR}\" 1>&2  ; jremove ${jname}" HUP INT ABRT BUS TERM EXIT
 			set -o errexit
 			set -o xtrace
@@ -324,6 +330,7 @@ run_bhyve_cloud()
 	local CURL_CMD=$( which curl )
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
 	${ECHO} "${N1_COLOR}run image via: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}"
+	[ -z "${ssh_wait}" ] && ssh_wait=0
 
 	${CAT_CMD} > up-${jname}.json <<EOF
 {
@@ -332,6 +339,7 @@ run_bhyve_cloud()
   "ram": "${vm_ram}",
   "cpus": "${vm_cpus}",
   "img": "${img}",
+  "tags": "${tags}",
   "pubkey": "${CLOUD_KEY}"
 }
 EOF
@@ -343,6 +351,41 @@ EOF
 	./deploy-${jname}.sh
 	# without debug
 	${RM_CMD} -f ./deploy-${jname}.sh ./up-${jname}.json
+
+	if [ ${ssh_wait} -eq 1 ]; then
+		bhyve_ssh_wait
+		ret=$?
+	else
+		ret=0
+	fi
+	if [ ${ret} -eq 0 ]; then
+		#bhyve_${jname}		# re-read variables
+
+		if fn_exists postcreate_${jname} 2>/dev/null; then
+			${ECHO} "${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+			# cleanup jail when postcreate action failed
+			trap "set +o xtrace; ${ECHO} \"${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}: ${W1_COLOR}failed${N1_COLOR} : cleanup${N0_COLOR}\" 1>&2  ; bremove ${jname}" HUP INT ABRT BUS TERM EXIT
+			set -o errexit
+			set -o xtrace
+			postcreate_${jname}
+			set +o xtrace
+			set +o errexit
+			trap "" HUP INT ABRT BUS TERM EXIT
+			${ECHO} "${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}: ${H3_COLOR}success${N0_COLOR}" 1>&2
+		else
+			${ECHO} "${N1_COLOR}  == postcreate function not specified: postcreate_${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+		fi
+
+		jname="${ojname}"
+		# per-env postup func
+		if fn_exists postup_${jname} 2>/dev/null; then
+			${ECHO} "${N1_COLOR}execute postup_${jname}${N0_COLOR}"
+			postup_${jname}
+			jname="${ojname}"		# for corrupted/changed jname in func
+		fi
+	else
+		[ ${ssh_wait} -eq 1 ] && err 1 "${N1_COLOR}ssh failed${N0_COLOR}"
+	fi
 	return 0
 }
 
@@ -446,8 +489,6 @@ run_bhyve()
 		ret=0
 	fi
 	if [ ${ret} -eq 0 ]; then
-		${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
-
 		#bhyve_${jname}		# re-read variables
 
 		if fn_exists postcreate_${jname} 2>/dev/null; then
