style

diff --git a/jailctl/bscp b/jailctl/bscp
--- a/jailctl/bscp
+++ b/jailctl/bscp
@@ -41,15 +41,15 @@ try_remote()
 
 	node=$( jwhereis ${jname} )
 
-	[ -z "${node}" ] && log_err 1 "Node not found for jail ${jname}"
+	[ -z "${node}" ] && log_err 1 "${CBSD_APP}: node not found for jail ${jname}"
 
 	cbsdlogger NOTICE ${CBSD_APP}: try to get remote jstatus for ${jname} on ${node}
 	status=$( rexe node=${node} cbsd jstatus ${jname} )
-	[ "${status}" = "0" ] && log_err 1 "jail ${jname} not running on ${node}"
+	[ "${status}" = "0" ] && log_err 1 "${CBSD_APP}: jail ${jname} not running on ${node}"
 	sqlfile="${node}"
 	. ${jrcconf}
 	[ "${baserw}" = "1" ] && path=${data}
-	[ -z "${path}" ] && log_err 1 "path not found"
+	[ -z "${path}" ] && log_err 1 "${CBSD_APP}: path not found"
 }
 
 
@@ -66,14 +66,14 @@ else
 	quiet=""
 fi
 
-[ $# -ne 2 ] && err 1 "${N1_COLOR}$0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ]${N0_COLOR}"
-jname=""
-rfile=""
+[ $# -ne 2 ] && err 1 "${N1_COLOR}${CBSD_APP}: $0 bhyve1:remotefile1 localfile1 [ localfile2 bhyve2@:remotefile2 ]${N0_COLOR}"
+jname=
+rfile=
 rarg=0
 
 if getjname $1; then
 	if getjname $2; then
-		log_err 1 "${N1_COLOR}Only one remote path${N0_COLOR}"
+		log_err 1 "${N1_COLOR}${CBSD_APP}: only one remote path${N0_COLOR}"
 	fi
 	rarg=1
 else
@@ -82,9 +82,9 @@ else
 	fi
 fi
 
-[ -z "${jname}" -o -z "${rfile}" ] && log_err 1 "${N1_COLOR}jail path via jail:path records not determine${N0_COLOR}"
+[ -z "${jname}" -o -z "${rfile}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: jail path via jail:path records not determine${N0_COLOR}"
 
-validate_jname "${jname}" || log_err 1 "${N1_COLOR}Bad jname: ${jname}${N0_COLOR}"
+validate_jname "${jname}" || log_err 1 "${N1_COLOR}${CBSD_ADD}: bad jname: ${jname}${N0_COLOR}"
 
 RSYNC=$( which rsync )
 
@@ -101,17 +101,18 @@ if [ $? -eq 1 ]; then
 		nodescp root=1 $1 ${node}:${path}${rfile}
 		err=$?
 	fi
-	exit $err
+	exit ${err}
 fi
 
-[ ${jid} -eq 0 ] && log_err 1 "${N1_COLOR}bhyve not active: ${jname}${N0_COLOR}"
+[ ${jid} -eq 0 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: bhyve not active: ${jname}${N0_COLOR}"
 
 if [ ${rarg} -eq 1 ]; then
 	readconf blogin.conf
 	readconf bscp.conf
-	echo "scp ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${ip4_addr}:${rfile} ${2}"
-	scp ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${ip4_addr}:${rfile} ${2}
-
+	echo "${SCP_CMD} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${ip4_addr}:${rfile} ${2}"
+	dstfile=$( ${BASENAME_CMD} ${2} )
+	${SCP_CMD} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${ci_user_add}@${ip4_addr}:${rfile} ${CBSD_PWD}/${dstfile}
+	ret=$?
 #	# from VM
 #	if [ -n "${RSYNC}" ]; then
 #		#we have rsync for that
@@ -136,18 +137,21 @@ else
 	if [ "${prefix}" = "/" ]; then
 		# full_path?
 		_source=$( ${REALPATH_CMD} "${1}" 2>/dev/null )
-		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}no such file: ${N2_COLOR}${1}${N0_COLOR}"
+		ret=$?
+		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such file: ${N2_COLOR}${1}${N0_COLOR}"
 	else
 		_source=$( ${REALPATH_CMD} "${CBSD_PWD}/${1}" 2>/dev/null )
-		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}no such file: ${N2_COLOR}${CBSD_PWD}/${1}${N0_COLOR}"
+		ret=$?
+		[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: no such file: ${N2_COLOR}${CBSD_PWD}/${1}${N0_COLOR}"
 	fi
 	dst=$( ${BASENAME_CMD} ${1} )
 	if [ -f ${_source} ]; then
-		echo "scp ${bscp_args} -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${ip4_addr}:${dst}"
-		scp ${bscp_args}  -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${ip4_addr}:${dst}
+		echo "${SCP_CMD} ${bscp_args} -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${ip4_addr}:${dst}"
+		${SCP_CMD} ${bscp_args}  -i ${workdir}/.ssh/id_rsa ${_source} ${ci_user_add}@${ip4_addr}:${dst}
+		ret=$?
 	elif [ -d "${_source}" ]; then
 		echo "DIR"
 	fi
 fi
+
+exit ${ret}
