bhyverun: set task to update process id
Use CBSD task to run the deferred task for updating bhyve PID after launching.
This is the work-around for Issue #399
in fact, we need a separated daemon as a bhyve monitor for monitoring
bhyve process or /dev/vmm/ entry via kqueue.

diff --git a/jailctl/bset b/jailctl/bset
--- a/jailctl/bset
+++ b/jailctl/bset
@@ -7,11 +7,12 @@ CBSDMODULE="bhyve"
 . ${sharedir}/bhyve.conf
 
 #concat for bhyve arg
-JARG="${MYCOL} nice"
+JARG="${MYCOL} nice vm_pid"
 
 MYOPTARG="$JARG"
 MYDESC="Modify parameter for bhyve"
-ADDHELP="mode=force for modification on the running jail\n"
+ADDHELP="mode=force for modification on the running jail\n\
+vm_pid - when 'auto', force to update pid from process list\n"
 
 . ${tools}
 . ${strings}
@@ -55,6 +56,27 @@ update_jails()
 				VAL=$(( ${VAL} * 1024 * 1024 ))
 			fi
 		;;
+		vm_pid)
+			VAL=
+			case "${vm_pid}" in
+				[Aa][Uu][Tt][Oo])
+					. ${distdir}/bhyve.subr
+					check_for_bhyve_process -j ${jname}
+					if [ $? -eq 0 ]; then
+						VAL=0
+					else
+						VAL="${vm_pid}"
+					fi
+					;;
+				*)
+					VAL="${vm_pid}"
+					;;
+			esac
+			[ -z "${VAL}" ] && err 1 "${N1_COLOR}bset vm_pid: unable to determine pid for: ${N2_COLOR}${jname}${N0_COLOR}"
+
+			if is_number ${VAL}; then
+				err 1 "${N1_COLOR}bset vm_pid: not number: ${N2_COLOR}${VAL}${N0_COLOR}"
+			fi
 	esac
 
 	[ -z "${i}" ] && return 0
@@ -69,9 +91,12 @@ update_jails()
 			cbsdsqlrw ${_formfile} UPDATE forms set cur=\"${VAL}\" WHERE param=\"nice\"
 			brenice jname=${jname}
 			;;
+		vm_pid)
+			# pid stored in jails settings as JID (should be moved to settings table)
+			cbsdsqlrw local "UPDATE jails SET jid=\"${VAL}\" WHERE jname=\"${jname}\""
+			;;
 		*)
 			cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE settings SET ${i}=\"${VAL}\"
-
 			# back compatible
 			cbsdsqlrw local UPDATE bhyve SET ${i}=\"${VAL}\" WHERE jname=\"${jname}\"
 			;;
