bhyve: add support for install FreeBSD guest from ISO, split for jail2iso methot into profile

diff --git a/jailctl/bstart b/jailctl/bstart
--- a/jailctl/bstart
+++ b/jailctl/bstart
@@ -33,9 +33,11 @@ init_iso()
 	local _mydir="${srcdir}/iso"
 	local _myfile="${_mydir}/${iso_img}"
 
+
 	[ ! -d "${_mydir}" -o ! -h "${_mydir}" ] && mkdir -p ${_mydir}
 
 	[ -z "${iso_img_dist}" ] && iso_img_dist="${iso_img}"
+
 
 	if [ ! -f "${_myfile}" -a ! -f "${_mydir}/${iso_img_dist}" -a "${fetch}" = "1" ]; then
 		[ -z "${iso_site}" ] && ${ECHO} "${MAGENTA}No such iso: ${GREEN}${_myfile}${MAGENTA} and ${GREEN}iso_site${MAGENTA} variable not found" && return 1
@@ -66,45 +68,87 @@ start_bhyve()
 
 	grubmem=$(( vm_ram / 1024 / 1024 ))
 
+	# profile
+	readconf bhyve-${vm_os_type}-${vm_os_profile}.conf
+	[ -z "${bhyve_profile}" ] && err 1 "${MAGENTA}No such profile: ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+	# re-read jail params and apply personal after profile
+	. ${jrcconf}
+
 	case "${vm_os_type}" in
 		"freebsd")
 			if [ "${from_jail}" = "1" ]; then
+				# from jail2iso mode
 				bhyveload_cmd="/usr/sbin/bhyveload -m ${vm_ram} -d ${data}/${MDFILE} ${jname}"
-				echo "$bhyveload_cmd"
+				echo "DEBUG: $bhyveload_cmd"
 				${tmuxcmd} new -s "cbsd-${jname}" "eval $bhyveload_cmd"
 #				installer_opt="-s 31:0,virtio-blk,${BOOTDISK}"
 			else
-				err 1 "WIP from ISO"
+				# default mode
+				_err=$( file -s ${data}/${MDFILE}| cut -d":" -f2|xargs)
+				if [ "${_err}" = "data" -o "${_err}" = "empty" -a "${vm_boot}" = "hdd" ]; then
+					if getyesno "${MAGENTA}Looks like ${GREEN}${data}/${MDFILE}${MAGENTA} is empty.${NORMAL}\n${BOLD}May be want to boot from CD?${NORMAL}"; then
+						vm_boot="cd";
+					fi
+				fi
+				[ "${vm_iso_path}" != "0" ] && iso_img="${vm_iso_path}"
+				if [ "${vm_boot}" = "cd" ]; then
+					init_iso
+					if [ $? -eq 1 ]; then
+						printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
+						for i in $( jot 5 ); do
+							printf "."
+							sleep 1
+						done
+						echo
+					fi
+				fi
+#				${ECHO} "${MAGENTA}Creating ${GREEN}device.map ${MAGENTA}in ${GREEN}${_devicemap}${NORMAL}"
+#				truncate -s0 ${_devicemap}
+#				echo "(hd0) ${data}/${MDFILE}" >> "${_devicemap}"
+#				echo "(cd0) ${iso_img}" >> "${_devicemap}"
+#				cat "${_devicemap}"
+#				[ -z "${grub_boot_cmd}" ] && err 1 "${MAGENTA}No such grub_boot_cmd variable. Check ${GREEN}vm_os_profile${MAGENTA} of config for ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf${MAGENTA} in ${etcdir}${NORMAL}"
+#				[ -z "${grub_iso_cmd}" -a "${vm_boot}" = "cd" ] && err 1 "${MAGENTA}No such grub_iso_cmd variable. Check ${GREEN}vm_os_profile${MANGETA} of config for ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf ${MAGENTA}in ${etcdir}${NORMAL}"
+
+				if [ "${vm_boot}" = "cd" ]; then
+					bhyveload_cmd="/usr/sbin/bhyveload -d ${iso_img} -m ${vm_ram} ${jname}"
+				else
+					bhyveload_cmd="/usr/sbin/bhyveload -m ${vm_ram} -d ${data}/${MDFILE} ${jname}"
+				fi
+
+				echo "DEBUG: $bhyveload_cmd"
+				${tmuxcmd} new -s "cbsd-${jname}" "eval $bhyveload_cmd"
+#				installer_opt="-s 31:0,virtio-blk,${BOOTDISK}"
+				echo "DEBUG: ${bhyveload_cmd}"
 			fi
 			;;
 		"linux")
 			_devicemap="${jailsysdir}/${jname}/device.map"
 			# profile
-			readconf bhyve-${vm_os_type}-${vm_os_profile}.conf
-			[ -z "${bhyve_profile}" ] && err 1 "${MAGENTA}No such profile: ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
-			# re-read jail params and apply personal after profile 
-			. ${jrcconf}
+#			readconf bhyve-${vm_os_type}-${vm_os_profile}.conf
+#			[ -z "${bhyve_profile}" ] && err 1 "${MAGENTA}No such profile: ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf${NORMAL}"
+#			# re-read jail params and apply personal after profile 
+#			. ${jrcconf}
 			_err=$( file -s ${data}/${MDFILE}| cut -d":" -f2|xargs)
 			
 			if [ "${_err}" = "data" -o "${_err}" = "empty" -a "${vm_boot}" = "hdd" ]; then
-				if getyesno "${MAGENTA}Looks like ${GREEN}${data}/${MDFILE}${MAGENTA} is empty.${NORMAL}\n${BOLD}May be you want to boot from CD?${NORMAL}"; then
-					vm_boot="cd";
+				if getyesno "${MAGENTA}Looks like ${GREEN}${data}/${MDFILE}${MAGENTA} is empty.${NORMAL}\n${BOLD}May be want to boot from CD?${NORMAL}"; then
+				    vm_boot="cd";
 				fi
 			fi
 
 			[ "${vm_iso_path}" != "0" ] && iso_img="${vm_iso_path}"
 			if [ "${vm_boot}" = "cd" ]; then
-				init_iso
-				if [ $? -eq 1 ]; then
-					printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
-					for i in $( jot 5 ); do
-						printf "."
-						sleep 1
-					done
-				echo
-				fi
+			    init_iso
+			    if [ $? -eq 1 ]; then
+				printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
+				for i in $( jot 5 ); do
+				    printf "."
+				    sleep 1
+				done
+			    echo
+			    fi
 			fi
-
 			${ECHO} "${MAGENTA}Creating ${GREEN}device.map ${MAGENTA}in ${GREEN}${_devicemap}${NORMAL}"
 			truncate -s0 ${_devicemap}
 			echo "(hd0) ${data}/${MDFILE}" >> "${_devicemap}"
@@ -112,7 +156,7 @@ start_bhyve()
 			cat "${_devicemap}"
 			[ -z "${grub_boot_cmd}" ] && err 1 "${MAGENTA}No such grub_boot_cmd variable. Check ${GREEN}vm_os_profile${MAGENTA} of config for ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf${MAGENTA} in ${etcdir}${NORMAL}"
 			[ -z "${grub_iso_cmd}" -a "${vm_boot}" = "cd" ] && err 1 "${MAGENTA}No such grub_iso_cmd variable. Check ${GREEN}vm_os_profile${MANGETA} of config for ${GREEN}bhyve-${vm_os_type}-${vm_os_profile}.conf ${MAGENTA}in ${etcdir}${NORMAL}"
-			echo ${grub_boot_cmd}
+			echo "DEBUG: ${grub_boot_cmd}"
 			;;
 		openbsd|dflybsd|netbsd)
 			_devicemap="${jailsysdir}/${jname}/device.map"
@@ -123,19 +167,19 @@ start_bhyve()
 			. ${jrcconf}
 			init_iso
 			if [ $? -eq 1 ]; then
-				printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
-				for i in $( jot 5 ); do
-					printf "."
-					sleep 1
-				done
-				echo
+			    printf "${MAGENTA}Continue without ${iso_img}. Hope this is ok, sleep for 5 seconds ${NORMAL}"
+			    for i in $( jot 5 ); do
+				printf "."
+				sleep 1
+			    done
+			    echo
 			fi
 			_err=$( file -s ${data}/${MDFILE}| cut -d":" -f2|xargs)
 
 			if [ "${_err}" = "data" -a "${vm_boot}" = "hdd" ]; then
-				if getyesno "${MAGENTA}Looks like ${GREEN}${data}/${MDFILE}${MAGENTA} is empty.${NORMAL}\n${BOLD}May be want to boot from CD?${NORMAL}"; then
-					vm_boot="cd";
-				fi
+			    if getyesno "${MAGENTA}Looks like ${GREEN}${data}/${MDFILE}${MAGENTA} is empty.${NORMAL}\n${BOLD}May be want to boot from CD?${NORMAL}"; then
+				vm_boot="cd";
+			    fi
 			fi
 
 			${ECHO} "${MAGENTA}Creating ${GREEN}device.map ${MAGENTA}in ${GREEN}${_devicemap}${NORMAL}"
@@ -149,40 +193,41 @@ start_bhyve()
 		*)
 			err 1 "${MAGENTA}Unknown vm profile: ${GREEN}${vm_os_type}${NORMAL}"
 	esac
-	if [ "${vm_os_type}" != "freebsd" ]; then
-		${ECHO} "${MAGENTA}Booting from: ${GREEN}${vm_boot}${NORMAL}"
-		# Bhyveload
-		case "${vm_boot}" in
-			"cd")
-				echo "B: $grub_iso_cmd"
-#				if [ "${inter}" = "0" ]; then
+
+			if [ "${vm_os_type}" != "freebsd" ]; then
+			    ${ECHO} "${MAGENTA}Booting from: ${GREEN}${vm_boot}${NORMAL}"
+			    # Bhyveload
+			    case "${vm_boot}" in
+				"cd")
+				    echo "DEBUG: $grub_iso_cmd"
+#				    if [ "${inter}" = "0" ]; then
 #					eval "/usr/sbin/daemon -p ${ftmpdir}/bhyveload.${jname}.$$ ${tmuxcmd} new -s \"cbsd-${jname}\" \"eval $grub_iso_cmd\""
-#				else
-					echo "$grub_iso_cmd"
+#				    else
+					echo "DEBUG: $grub_iso_cmd"
 					eval "$grub_iso_cmd"
-#				fi
+#				    fi
 				;;
-			"hdd")
-				echo "Boot from HDD"
-#				if [ "${inter}" = "0" ]; then
-#					echo "INTER"
-#					sleep 2
+				"hdd")
+				    echo "Boot from HDD"
+#				    if [ "${inter}" = "0" ]; then
+#				    echo "INTER"
+#				    sleep 2
 #					eval "/usr/sbin/daemon -p ${ftmpdir}/bhyveload.${jname}.$$ ${tmuxcmd} new -s \"cbsd-${jname}\" \"eval $grub_boot_cmd\""
-#				else
-					echo "${grub_boot_cmd}"
+#				    else
+					echo "DEBUG: ${grub_boot_cmd}"
 					eval "$grub_boot_cmd"
-#				fi
+#				    fi
 				;;
-			*)
-				echo "Booting from HDD"
-#				if [ "${inter}" = "0" ]; then
+				*)
+				    echo "Booting from HDD"
+#				    if [ "${inter}" = "0" ]; then
 #					eval "eval /usr/sbin/daemon -p ${ftmpdir}/bhyveload.${jname}.$$ ${tmuxcmd} new -s \"cbsd-${jname}\" \"eval $grub_boot_cmd\""
-#				else
+#				    else
 					eval "$grub_boot_cmd"
-#				fi
+#				    fi
 				;;
-		esac
-	fi
+			    esac
+			fi
 
 	# for vnet we can make another action
 	. ${vimageconf}
@@ -190,7 +235,7 @@ start_bhyve()
 	[ "${interface}" = "0" -o "${interface}" = "auto" ] && interface=$(getnics-by-ip ip=0.0.0.0)
 
 	if ! mybridge=`get_my_device bridge ${interface}`; then
-		err 1 "${MAGENTA}Error: Cant get_my_device for ${interface}: ${mybridge}${NORMAL}"
+	    err 1 "${MAGENTA}Error: Cant get_my_device for ${interface}: ${mybridge}${NORMAL}"
 	fi
 
 	mytap=$( get_my_tap ${mybridge} )
