fixes for cbsdsh perms; tmux support for remote jlogin; jlogin without args show jail list;

diff --git a/jailctl/bstop b/jailctl/bstop
--- a/jailctl/bstop
+++ b/jailctl/bstop
@@ -1,3 +1,61 @@
-#!/bin/sh
-#v9.2.2
-cbsd sudo /usr/local/cbsd/sudoexec/bstop $*
+#!/usr/local/bin/cbsd
+#v10.0.3
+globalconf="${workdir}/cbsd.conf";
+MYARG=""
+MYOPTARG="jname"
+MYDESC="Stop jail"
+CBSDMODULE="bhyve"
+EXTHELP="wf_jstop_jstart.html"
+
+[ -f ${globalconf} ] || err 1 "no such conf file";
+. ${globalconf}
+. ${subr}
+. ${inventory}
+. ${system}
+. ${mdtools}
+. ${strings}
+
+init $*
+
+# MAIN
+if [ $# -gt 1 ]; then
+# recursive stop
+    JLIST=$*
+    for jname in ${JLIST}; do
+	/usr/sbin/daemon -p ${ftmpdir}/jstop.${jname}.$$ /usr/local/bin/cbsd jstop jname=${jname}
+	#lets save .pid file
+	sleep 1
+	[ -f "${ftmpdir}/jstop.${jname}.$$" ] && cbsd cbsd_pwait --pid=`cat ${ftmpdir}/jstop.${jname}.$$` --timeout=${parallel}
+    done
+
+    wait_for_jstop
+
+    err 0 "${MAGENTA}Multiple stop: ${GREEN}done${NORMAL}"
+fi
+
+[ -z "${jname}" ] && jname=$1
+
+. ${jrcconf}
+[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+#[ ${jid} -eq 0 ] && err 1 "${MAGENTA}Not Running: ${GREEN}${jname}${NORMAL}"
+[ "${emulator}" != "bhyve" ] && err 1 "${MAGENTA}Not in bhyve mode${NORMAL}"
+
+/bin/ps axopid,ucomm,command|while read pid comm cmd; do
+    if [ "${comm}" = "bhyve" -o "${comm}" = "grub-bhyve" ]; then
+    _res=$( echo $cmd|grep " ${jname}$" 2>/dev/null)
+    [ -n "${_res}" ] && kill $pid
+    fi
+done
+
+bhyvectl --destroy --vm="${jname}"
+
+# cleanup for ifaces
+. ${vimageconf}
+
+mytap=`get_my_device tap ${jname}`
+
+if [ -n "${mytap}" ]; then
+    /sbin/ifconfig ${mytap} >/dev/null 2>&1 && /sbin/ifconfig ${mytap} destroy
+fi
+
+
diff --git a/jailctl/jcleanup b/jailctl/jcleanup
--- a/jailctl/jcleanup
+++ b/jailctl/jcleanup
@@ -1,2 +1,37 @@
 #!/bin/sh
-cbsd sudo /usr/local/cbsd/sudoexec/jcleanup $*
+#v10.0.3
+globalconf="${workdir}/cbsd.conf";
+CBSDMODULE="jail"
+MYARG="jname"
+MYOPTARG=""
+MYDESC="Force unmount and cleanup for offline jail"
+
+# Cleanup all items of broken jail
+[ -f ${globalconf} ] || err 1 "no such conf file";
+. ${globalconf}
+. ${subr}
+. ${system}
+. ${mdtools}
+. ${strings}
+
+init $*
+
+. ${jrcconf}
+[ $? -eq 1 ] && return 0 #only for registered jails
+
+# check for ip and remove them if exist
+#if [ -n "$interface" ]; then
+#    for _i in $multiips4; do
+#	IP=`echo ${_i} |cut -d "/" -f 1`
+#	    if [ `/sbin/ifconfig |grep -c ${IP}` -gt 0 ]; then
+#		IFACE=`cbsd getnics-by-ip ip=${IP}`
+#		echo "Remove ${IP} from ${IFACE}"
+#		/sbin/ifconfig ${IFACE} -alias ${IP}
+#	    fi
+#    done
+#fi
+
+[ "${mdsize}" != "0" ] && MDFILE=`eval find_md_by_mountpath ${data}`
+[ $baserw -eq 1 ] && path=$data
+umount_cdirs ${path} no_unmount_root
+[ "${mdsize}" != "0" -a -n "${MDFILE}" ] && cbsd unmountmd md=${MDFILE}
