j2prepare: check for remove version

diff --git a/jailctl/j2prepare b/jailctl/j2prepare
--- a/jailctl/j2prepare
+++ b/jailctl/j2prepare
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v12.0.6
+#v12.1.6
 CBSDMODULE="jail"
 MYARG="node jname mkdatadir"
 MYOPTARG="verbose sharedfs tryoffline"
@@ -21,8 +21,6 @@ emulator="jail" # for jname_is_multiple
 jail_list=
 jname_is_multiple
 
-
-my_name="j2prepare"
 . ${distdir}/time.subr
 st_time=$( ${DATE_CMD} +%s )
 
@@ -90,7 +88,6 @@ if [ -n "${jail_list}" ]; then
 	err 0 "${N1_COLOR}Multiple j2prepare: ${N2_COLOR}done${N0_COLOR}"
 fi
 
-
 ## MAIN
 [ -z "${jname}" ] && log_err 1 "${N1_COLOR}Give me jname${N0_COLOR}"
 
@@ -114,7 +111,7 @@ RJAILFSTAB="jails-fstab/${jailfstabpref}${jname}"
 
 # Update Redis
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
-        cbsdredis publish cbsd_events '{"cmd":"j2prepare", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":1}'
+	cbsdredis publish cbsd_events '{"cmd":"${CBSD_APP}", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":1}'
 fi
 
 not_sharedfs_action()
@@ -139,7 +136,7 @@ not_sharedfs_action()
 	nodescp tryoffline=${tryoffline} ${SECFILE} ${node}:etc > ${DEBLOG} 2>&1
 	dot "scp_secfile"
 	imgpart mode=pack jname=${jname} part=sysdata out=${tmpdir}/${jname}-sysdata.tgz > ${DEBLOG} 2>&1
-	trap "/bin/rm -f ${tmpdir}/${jname}-sysdata.tgz" 0 1 2 3 4
+	trap "${RM_CMD} -f ${tmpdir}/${jname}-sysdata.tgz" 0 1 2 3 4
 
 	cbsdlogger NOTICE ${CBSD_APP}: copy sysdata for ${jname} to ${node}
 	nodescp tryoffline=${tryoffline} ${tmpdir}/${jname}-sysdata.tgz ${node}:jails-system > ${DEBLOG} 2>&1
@@ -164,9 +161,19 @@ not_sharedfs_action()
 	rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd imgpart mode=extract jname=jails-system/${jname}-sysdata.tgz part=sysdata out=jails-system > ${DEBLOG} 2>&1
 	dot "rexe_img_extract_sysdata"
 
-	rexe tryoffline=${tryoffline} node=${node} rm -f jails-system/${jname}-sysdata.tgz jails-system/${jname}/locked > ${DEBLOG} 2>&1
+	rexe tryoffline=${tryoffline} node=${node} ${RM_CMD} -f jails-system/${jname}-sysdata.tgz jails-system/${jname}/locked > ${DEBLOG} 2>&1
 	dot "rexe_rm-f-sysdata"
 }
+
+printf "   ${H5_COLOR}* ${N1_COLOR}check for remote CBSD version: ${N0_COLOR}"
+# todo: we can get this version from the nodes database (from retrinv task)
+d_cbsd_ver=$( rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version 2>/dev/null | ${TR_CMD} -d \\r | ${AWK_CMD} '/./{print $1}' )
+[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: failed: rexe node=${node}${N0_COLOR}"
+printf "${H3_COLOR}${d_cbsd_ver}${N0_COLOR}"
+echo
+s_cbsd_ver=$( version | ${AWK_CMD} '/./{print $1}' )
+
+[ "${s_cbsd_ver}" != "${d_cbsd_ver}" ] && err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}CBSD version not equal: ${s_cbsd_ver} != ${d_cbsd_ver}${N0_COLOR}"
 
 if [ ${sharedfs} -eq 0 ]; then
 	cbsdlogger NOTICE ${CBSD_APP}: not shared fs with ${node}, perform not_sharedfs_action
@@ -177,7 +184,7 @@ jmkrcconf jname=${jname} > ${JAILRCCONF}
 cbsdlogger NOTICE ${CBSD_APP}: copy rcconf for ${jname} to ${node}
 nodescp tryoffline=${tryoffline} ${JAILRCCONF} ${node}:${RJAILRCCONF} > ${DEBLOG} 2>&1
 dot "scp rcconf"
-/bin/rm -f ${JAILRCCONF}
+${RM_CMD} -f ${JAILRCCONF}
 
 cbsdlogger NOTICE ${CBSD_APP}: jrsyncconf for ${jname} on ${node}
 rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd jrsyncconf jname=${jname} > ${DEBLOG} 2>&1
@@ -191,7 +198,7 @@ dot "rexe_4"
 if [ "${mod_cbsd_redis_enabled}" = "YES" -a -z "${MOD_CBSD_REDIS_DISABLED}" ]; then
 	end_time=$( ${DATE_CMD} +%s )
 	diff_time=$(( end_time - st_time ))
-        cbsdredis publish cbsd_events '{"cmd":"j2prepare", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":0, "dutation":'${diff_time}'}'
+	cbsdredis publish cbsd_events '{"cmd":"${CBSD_APP}", "node":"'${nodename}'", "dest":"'${node}'", "jail":"'${jname}'", "status":0, "duration":'${diff_time}'}'
 fi
 
 err 0 "${N2_COLOR}ok${N0_COLOR}"
