began to restore zfs-migrator: step 1/many

diff --git a/jailctl/j2prepare b/jailctl/j2prepare
--- a/jailctl/j2prepare
+++ b/jailctl/j2prepare
@@ -142,6 +142,12 @@ not_sharedfs_action()
 	imgpart mode=pack jname=${jname} part=sysdata out=${tmpdir}/${jname}-sysdata.tgz > ${DEBLOG} 2>&1
 	trap "${RM_CMD} -f ${tmpdir}/${jname}-sysdata.tgz" 0 1 2 3 4
 
+	if [ ! -r ${tmpdir}/${jname}-sysdata.tgz ]; then
+		err 1 "no such ${tmpdir}/${jname}-sysdata.tgz: cbsd imgpart mode=pack jname=${jname} part=sysdata out=${tmpdir}/${jname}-sysdata.tgz"
+	else
+		${DU_CMD} -sh ${tmpdir}/${jname}-sysdata.tgz
+	fi
+
 	cbsdlogger NOTICE ${CBSD_APP}: copy sysdata for ${jname} to ${node}
 	nodescp tryoffline=${tryoffline} ${tmpdir}/${jname}-sysdata.tgz ${node}:jails-system > ${DEBLOG} 2>&1
 	dot "scp_sysdata"
@@ -208,7 +214,8 @@ not_sharedfs_action()
 printf "   ${H5_COLOR}* ${N1_COLOR}check for remote CBSD version: ${N0_COLOR}"
 # todo: we can get this version from the nodes database (from retrinv task)
 d_cbsd_ver=$( rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version 2>/dev/null | ${TR_CMD} -d \\r | ${AWK_CMD} '/./{print $1}' )
-[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: failed: rexe node=${node}${N0_COLOR}"
+[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: failed: tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version${N0_COLOR}"
+[ -z "${d_cbsd_ver}" ] && err 1 "${N1_COLOR}${CBSD_APP}: failed: cbsd rexe tryoffline=${tryoffline} node=${node} /usr/local/bin/cbsd -c version${N0_COLOR}"
 printf "${H3_COLOR}${d_cbsd_ver}${N0_COLOR}"
 echo
 s_cbsd_ver=$( version | ${AWK_CMD} '/./{print $1}' )
