code style; nice 20 for buildworld and buildkernel via buildworld.conf

diff --git a/jailctl/jailscp b/jailctl/jailscp
--- a/jailctl/jailscp
+++ b/jailctl/jailscp
@@ -22,45 +22,44 @@ init $*
 
 getjname()
 {
-    local _t
+	local _t
 
-    _t=$(echo ${1} |grep ":")
+	_t=$(echo ${1} |grep ":")
 
-    [ $? -ne 0 ] && return 1
+	[ $? -ne 0 ] && return 1
 
-    jname=${1%%:*}
-    rfile=${1##*:}
-
+	jname=${1%%:*}
+	rfile=${1##*:}
 }
 
 try_remote()
 {
-    # this is only wrapper for compile correct arguments for cbsd nodescp
+	# this is only wrapper for compile correct arguments for cbsd nodescp
 
-    node=$( jwhereis $jname )
+	node=$( jwhereis $jname )
 
-    [ -z "${node}" ] && err 1 "Node not found for jail $jname"
+	[ -z "${node}" ] && err 1 "Node not found for jail $jname"
 
-    status=$( rexe node=$node cbsd jstatus $jname )
-    [ "${status}" = "0" ] && err 1 "Jail not running"
-    sqlfile="${node}"
-    . ${jrcconf}
-    [ "${baserw}" = "1" ] && path=${data}
-    [ -z "${path}" ] && err 1 "path not found"
+	status=$( rexe node=$node cbsd jstatus $jname )
+	[ "${status}" = "0" ] && err 1 "Jail not running"
+	sqlfile="${node}"
+	. ${jrcconf}
+	[ "${baserw}" = "1" ] && path=${data}
+	[ -z "${path}" ] && err 1 "path not found"
 }
 
 
 ### MAIN ###
 if [ -n "${verbose}" ]; then
-    shift
+	shift
 else
-    verbose=0
+	verbose=0
 fi
 
 if [ "${verbose}" = "0" ]; then
-    quiet="-q"
+	quiet="-q"
 else
-    quiet=""
+	quiet=""
 fi
 
 [ $# -ne 2 ] && err 1 "${MAGENTA}$0 jail1:remotefile1 localfile1 [ localfile2 jail2@:remotefile2 ]${NORMAL}"
@@ -69,14 +68,14 @@ rfile=""
 rarg=0
 
 if getjname $1; then
-    if getjname $2; then
-	err 1 "${MAGENTA}Only one remote path${NORMAL}"
-    fi
-    rarg=1
+	if getjname $2; then
+		err 1 "${MAGENTA}Only one remote path${NORMAL}"
+	fi
+	rarg=1
 else
-    if getjname $2; then
-	rarg=2
-    fi
+	if getjname $2; then
+		rarg=2
+	fi
 fi
 
 [ -z "${jname}" -o -z "${rfile}" ] && err 1 "${MAGENTA}jail path via jail:path records not determine${NORMAL}"
@@ -87,16 +86,16 @@ validate_jname ${jname}
 RSYNC=$(which rsync)
 . ${jrcconf}
 if [ $? -eq 1 ]; then
-    try_remote
+	try_remote
 
-    if [ $rarg -eq 1 ]; then
-	nodescp root=1 ${node}:${path}${rfile} ${2}
-	err=$?
-    else
-	nodescp root=1 $1 ${node}:${path}${rfile}
-	err=$?
-    fi
-    exit $err
+	if [ $rarg -eq 1 ]; then
+		nodescp root=1 ${node}:${path}${rfile} ${2}
+		err=$?
+	else
+		nodescp root=1 $1 ${node}:${path}${rfile}
+		err=$?
+	fi
+	exit $err
 fi
 
 [ $jid -eq 0 ] && err 1 "${MAGENTA}Jail not active${NORMAL}"
@@ -104,35 +103,34 @@ fi
 [ $baserw -eq 1 ] && path="${data}"
 
 if [ $rarg -eq 1 ]; then
-    DIR=$(dirname ${2})
-    [ ! -d "${DIR}" ] && mkdir -p ${DIR}
+	DIR=$(dirname ${2})
+	[ ! -d "${DIR}" ] && mkdir -p ${DIR}
 
-    if [ -n "${RSYNC}" ]; then
-	#we have rsync for that
-	[ ${verbose} -eq 1 ] && set -o xtrace
-	${RSYNC} -azlH ${path}${rfile} ${2}
-	[ ${verbose} -eq 1 ] && set +o xtrace
-    else
-	#no rsync, just scp
-	[ ${verbose} -eq 1 ] && set -o xtrace
-	cp -a ${path}${rfile} ${2}
-	[ ${verbose} -eq 1 ] && set +o xtrace
-    fi
+	if [ -n "${RSYNC}" ]; then
+		#we have rsync for that
+		[ ${verbose} -eq 1 ] && set -o xtrace
+		${RSYNC} -azzlH ${path}${rfile} ${2}
+		[ ${verbose} -eq 1 ] && set +o xtrace
+	else
+		#no rsync, just scp
+		[ ${verbose} -eq 1 ] && set -o xtrace
+		cp -a ${path}${rfile} ${2}
+		[ ${verbose} -eq 1 ] && set +o xtrace
+	fi
 else
-    DIR=$(dirname ${path}${rfile})
-    [ ${verbose} -eq 1 ] && set -o xtrace
-    [ ! -d "${DIR}" ] && mkdir -p "${DIR}"
-    [ ${verbose} -eq 1 ] && set +o xtrace
-    if [ -n "${RSYNC}" ]; then
-	#we have rsync for that
+	DIR=$(dirname ${path}${rfile})
 	[ ${verbose} -eq 1 ] && set -o xtrace
-	${RSYNC} -azlH ${1} ${path}${rfile}
+	[ ! -d "${DIR}" ] && mkdir -p "${DIR}"
 	[ ${verbose} -eq 1 ] && set +o xtrace
-    else
-	#no rsync, just scp
-	[ ${verbose} -eq 1 ] && set -o xtrace
-	cp -a ${1} ${path}${rfile}
-	[ ${verbose} -eq 1 ] && set +o xtrace
-    fi
+	if [ -n "${RSYNC}" ]; then
+		#we have rsync for that
+		[ ${verbose} -eq 1 ] && set -o xtrace
+		${RSYNC} -azzlH ${1} ${path}${rfile}
+		[ ${verbose} -eq 1 ] && set +o xtrace
+	else
+		#no rsync, just scp
+		[ ${verbose} -eq 1 ] && set -o xtrace
+		cp -a ${1} ${path}${rfile}
+		[ ${verbose} -eq 1 ] && set +o xtrace
+	fi
 fi
-
diff --git a/jailctl/jmkrcconf b/jailctl/jmkrcconf
--- a/jailctl/jmkrcconf
+++ b/jailctl/jmkrcconf
@@ -26,38 +26,37 @@ cat <<EOF
 EOF
 
 for i in ${JARG}; do
-    VAL=$(cbsdsql local SELECT ${i} FROM jails WHERE jname=\"${jname}\")
-    [ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
-    echo "${i}=\"${VAL}\";"
+	VAL=$( cbsdsql local SELECT ${i} FROM jails WHERE jname=\"${jname}\" )
+	[ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
+	echo "${i}=\"${VAL}\";"
 done
 
 
 if [ "${emulator}" = "bhyve" ]; then
-    . ${sharedir}/bhyve.conf
-    for i in ${MYCOL}; do
-	[ "${i}" = "jname" ] && continue
-	VAL=$(cbsdsql local SELECT ${i} FROM bhyve WHERE jname=\"${jname}\")
-	[ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
-	echo "${i}=\"${VAL}\";"
-    done
+	. ${sharedir}/bhyve.conf
+	for i in ${MYCOL}; do
+		[ "${i}" = "jname" ] && continue
+		VAL=$( cbsdsql local SELECT ${i} FROM bhyve WHERE jname=\"${jname}\" )
+		[ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
+		echo "${i}=\"${VAL}\";"
+	done
 
+	unset dsklist
+	sqldelimer=" "
 
-    unset dsklist
-    sqldelimer=" "
+	for last_disk in $( seq 1 16 ); do
+		unset dsk_controller${last_disk}
+	done
 
-    for last_disk in $( seq 1 16 ); do
-	unset dsk_controller${last_disk}
-    done
+	dsk_id=1
 
-    dsk_id=1
-
-    cbsdsql local SELECT dsk_controller,dsk_path,dsk_slot,dsk_type FROM bhyvedsk WHERE jname=\"${jname}\" | while read dsk_controller dsk_path dsk_slot dsk_type; do
-	echo "dsk_controller${dsk_id}=\"${dsk_controller}\";"
-	echo "dsk_path${dsk_id}=\"${dsk_path}\";"
-	echo "dsk_slot${dsk_id}=\"${dsk_slot}\";"
-	echo "dsk_type${dsk_id}=\"${dsk_type}\";"
-	dsk_id=$(( dsk_id + 1 ))
-    done || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
+	cbsdsql local SELECT dsk_controller,dsk_path,dsk_slot,dsk_type FROM bhyvedsk WHERE jname=\"${jname}\" | while read dsk_controller dsk_path dsk_slot dsk_type; do
+		echo "dsk_controller${dsk_id}=\"${dsk_controller}\";"
+		echo "dsk_path${dsk_id}=\"${dsk_path}\";"
+		echo "dsk_slot${dsk_id}=\"${dsk_slot}\";"
+		echo "dsk_type${dsk_id}=\"${dsk_type}\";"
+		dsk_id=$(( dsk_id + 1 ))
+	done || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
 fi
 
 #finally set jname
