taskd: stage 1/3; fixes for get_my_tap/freenic for vnet and tap; dummy dhcpd function; repo: newjname as argument for alternative name of stored jail

diff --git a/jailctl/jailscp b/jailctl/jailscp
--- a/jailctl/jailscp
+++ b/jailctl/jailscp
@@ -36,8 +36,18 @@ getjname()
 
 try_remote()
 {
-# this is only wrapper for compile correct arguments for cbsd nodescp
+    # this is only wrapper for compile correct arguments for cbsd nodescp
 
+    node=$( jwhereis $jname )
+
+    [ -z "${node}" ] && err 1 "Node not found for jail $jname"
+
+    status=$( rexe node=$node cbsd jstatus $jname )
+    [ "${status}" = "0" ] && err 1 "Jail not running"
+    sqlfile="${node}"
+    . ${jrcconf}
+    [ "${baserw}" = "1" ] && path=${data}
+    [ -z "${path}" ] && err 1 "path not found"
 }
 
 
@@ -76,9 +86,20 @@ validate_jname ${jname}
 [ $? -ne 1 ] && err 1 "${MAGENTA}Bad jname${NORMAL}"
 
 RSYNC=$(which rsync)
-
 . ${jrcconf}
-[ $? -eq 1 ] && try_remote
+if [ $? -eq 1 ]; then
+    try_remote
+
+    if [ $rarg -eq 1 ]; then
+	nodescp root=1 ${node}:${path}${rfile} ${2}
+	err=$?
+    else
+	nodescp root=1 $1 ${node}:${path}${rfile}
+	err=$?
+    fi
+    exit $err
+fi
+
 [ $jid -eq 0 ] && err 1 "${MAGENTA}Jail not active${NORMAL}"
 
 [ $baserw -eq 1 ] && path="${data}"
diff --git a/nodectl/node b/nodectl/node
--- a/nodectl/node
+++ b/nodectl/node
@@ -16,6 +16,7 @@ EXTHELP="wf_node.html"
 . ${subr}
 . ${tools}
 . ${color}
+. ${inventory}
 . ${nodes}
 
 init $*
@@ -49,11 +50,12 @@ nodeadd()
 
     if iptype $node; then
 	resolvhost ${node}
+	[ -z "${HST}" ] && err 1 "${MAGENTA}Can't resolv IP for ${node} hostname. Use IP address.${NORMAL}"
 	node=$HST
     fi
 
-    ${ECHO} "${MAGENTA}Connecting...${NORMAL}"
-    NODENAME=`cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename`
+    ${ECHO} "${MAGENTA}Connecting to ${node}...${NORMAL}"
+    NODENAME=$( cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename )
 
     case $? in
 	0)
@@ -89,7 +91,7 @@ nodeadd()
 		cbsdsql nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
 	    fi
 	    idle_update ${NODENAME}
-	    cbsd retrinv node=${NODENAME}
+	    cbsd retrinv node=${NODENAME} tryoffline=1
 	;;
 	1)
 	    cat ${DEBLOG}
@@ -132,21 +134,42 @@ nodedel()
     err 0 "${MAGENTA}Removed${NORMAL}"
 }
 
+conv_idle()
+{
+    local _res
+
+    if [ ${sqlreplica} -eq 1 ]; then
+	_res=$( check_locktime ${ftmpdir}/shmux_${_ip}.lock )
+	[ $? -eq 0 ] && _nodestatus="Connected" && _idle=${_res} && return 0
+    fi
+
+    _nodestatus="Disconnected"
+    idle_time=$( /bin/date -j -f "%Y-%m-%d %H:%M:%S" "${_idle}" "+%s" )
+    _res=$(( ( curtime - idle_time ) / 60 ))
+    _idle="${_res}"
+}
+
 
 nodelist()
 {
-
     if [ ${allinfo} -eq 0 ]; then
 	cbsdsql nodes SELECT nodename FROM nodelist
     else
-	sqldelimer=" "
-	[ ${header} -eq 1 ] && ${ECHO} "${BOLD}NODENAME IP PORT KEYFILE ROOTKEYFILE${NORMAL}"
-	cbsdsql nodes SELECT nodename,ip,port,keyfile,rootkeyfile FROM nodelist |while read _line; do
-	    printf "${NORMAL}${_line}\n"
+	[ ${header} -eq 1 ] && ${ECHO} "${BOLD}NODENAME IP PORT KEYFILE STATUS IDLE${NORMAL}"
+	local sqldelimer="|"
+	local IFS="|"
+	cbsdsql nodes SELECT nodename,ip,port,keyfile,idle FROM nodelist |while read _nodename _ip _port _keyfile _idle; do
+	    conv_idle
+	    printf "${NORMAL}${_nodename} ${_ip} ${_port} ${_keyfile} ${_nodestatus} ${_idle}\n"
 	done
     fi
-
+    unset sqldelimer
+    local IFS
 }
+
+
+# MAIN
+curtime=$( /bin/date +%s )
 
 [ -z "${allinfo}" ] && allinfo=1
 [ -z "${header}" ] && header=1
diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v10.0.4
+#v10.0.6
 globalconf="${workdir}/cbsd.conf";
 MYARG="jroot fstab"
 MYOPTARG="jname"
@@ -31,20 +31,20 @@ cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 	[ -z "${_device}" ] && continue
 	echo ${_device} |grep -sq ^/
 	[ $? -ne 0 ] && _device="${workdir}/${_device}"
-	if [ ! -f "${_device}" -o ! -d "${_device}" ]; then
-	    TMPLOG=`mktemp ${ftmpdir}/fstab.XXX`
-	    trap "rm -f ${TMPLOG}" 0 1 2 3 4 5
-	    echo "Source dir ${_device} doesn't exist" > ${TMPLOG}
-	fi
+#	if [ ! -f "${_device}" -o ! -d "${_device}" ]; then
+#	    TMPLOG=$( mktemp ${ftmpdir}/fstab.XXX )
+#	    trap "rm -f ${TMPLOG}" HUP INT ABRT BUS TERM EXIT
+#	    echo "Source dir ${_device} doesn't exist" > ${TMPLOG}
+#	fi
 	;;
     esac
 done
 
-if [ -f "${TMPLOG}" ]; then
-    ERRORLOG=`cat $TMPLOG`
-    rm -f ${TMPLOG}
-    err 1 "$ERRORLOG"
-fi
+#if [ -f "${TMPLOG}" ]; then
+#    ERRORLOG=$( cat $TMPLOG )
+#    rm -f ${TMPLOG}
+#    err 1 "$ERRORLOG"
+#fi
 
 cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
     [ "${_fs}" = "zfs" ] && continue
@@ -79,7 +79,7 @@ cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
     fi
 
     if [ ${mnt} -eq 0 ]; then
-	[ ! -d "${jroot}${_mountpt}" ] && mkdir -p ${jroot}${_mountpt}
+	[ ! -d "${jroot}${_mountpt}" ] && mkdir -p "${jroot}${_mountpt}"
 	[ ! -d "${jroot}${_mountpt}" ] && echo "Warning: Can't create ${jroot}${_mountpt} - permission problem ?"
 	/sbin/mount -t ${_fs} -o${_mode} ${_device} ${jroot}${_mountpt}
     fi
