add external_exec_local_script as hook for local scripts
WIP!
We can use additional hook in the appropriate directories for remote action on data:

remove.d for [jbx]remove
rename.d for [jbx]rename
clone.d for [jbx]clone

commands and so on.

This allows you to use any other native implementations to manipulate data.

Issue #373, suggested by: haynesjustin

diff --git a/jailctl/jclone b/jailctl/jclone
--- a/jailctl/jclone
+++ b/jailctl/jclone
@@ -86,6 +86,29 @@ JAILRCCONFORIG="${jailrcconfdir}/rc.conf_${old}"
 SYSDIROLD="${jailsysdir}/${old}"
 SYSDIRNEW="${jailsysdir}/${new}"
 
+. ${distdir}/jcreate.subr
+geniplist ${ip4_addr}           # for ipvX_first_public-like vars
+export_jail_data_for_external_hook
+external_exec_master_script "clone.d"
+
+external_exec_local_script "clone-local.d"
+_ret=$?
+
+skip_data_operation=0
+
+case "${_ret}" in
+	0)
+		# no local script, continue as usual
+		;;
+	1)
+		# local script exist and successful, skip data operation
+		skip_data_operation=0
+		;;
+	2)
+		err 1 "${N1_COLOR}clone-local.d hook failed, cancel clone${N0_COLOR}"
+		;;
+esac
+
 #rename zfs fs source
 case ${zfsfeat} in
 	1)
@@ -139,17 +162,20 @@ jname=${new}
 
 [ "${zfsfeat}" != "1" ] && clone_method="rsync"
 
-case ${clone_method} in
-	auto)
-		clonedata -s ${SRC} -d ${DST} -m zfs -n ${new} -p ${promote}
-		;;
-	*)
-		if [ "${verbose}" = "1" ]; then
-			clonedata -s ${SRC} -d ${DST} -m rsync
-		else
-			clonedata -s ${SRC} -d ${DST} -m rsync > /dev/null 2>&1
-		fi
-esac
+# jclone-local data exist/passed ?
+if [ ${skip_data_operation} -eq 0 ]; then
+	case ${clone_method} in
+		auto)
+			clonedata -s ${SRC} -d ${DST} -m zfs -n ${new} -p ${promote}
+			;;
+		*)
+			if [ "${verbose}" = "1" ]; then
+				clonedata -s ${SRC} -d ${DST} -m rsync
+			else
+				clonedata -s ${SRC} -d ${DST} -m rsync > /dev/null 2>&1
+			fi
+	esac
+fi
 
 dot "clone rsync"
 
