fix illegal option for TUI-based script; fake DHCP for jclone

diff --git a/jailctl/jclone b/jailctl/jclone
--- a/jailctl/jclone
+++ b/jailctl/jclone
@@ -4,6 +4,7 @@ MYARG="old new host_hostname"
 MYOPTARG="ip4_addr verbose"
 MYDESC="Jail cloning"
 CBSDMODULE="jail"
+ADDHELP="ip4_addr - can be DHCP\n"
 
 . ${subr}
 . ${tools}
@@ -20,6 +21,18 @@ myjid=$( cbsdsql local SELECT jid FROM jails WHERE jname=\"${new}\" 2>/dev/null 
 [ -n "${myjid}" ] && err 1 "${MAGENTA}Jail already exist: ${GREEN}${new}${NORMAL}"
 
 jname="${old}"
+
+if [ "${ip4_addr}" = "DHCP" ]; then
+	dhcpip=$( dhcpd )
+	[ -z "${dhcpip}" ] && err 1 "${MAGENTA}Unable to dhcpd${NORMAL}"
+	ipwmask ${dhcpip}
+	[ -z "${IWM}" ] && err 1 "${MAGENTA}Unable IWM for dhcpd${NORMAL}"
+	iptype ${IWM}
+	[ $? -eq 0 ] && err 1 "${MAGENTA}Not ip from dhcpd?: ${dhcpip} / ${IWM}"
+	ip4_addr="${dhcpip}"
+	${ECHO} "${MAGENTA}Selected IP: ${GREEN}${ip4_addr}${NORMAL}"
+fi
+
 ip4_addr_new="${ip4_addr}"
 host_hostname_new="${host_hostname}"
 
