9.2.2 wip: switch to cbsdsh

diff --git a/jailctl/jcreate b/jailctl/jcreate
--- a/jailctl/jcreate
+++ b/jailctl/jcreate
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v9.2.0
+#v9.2.2
 globalconf="${workdir}/cbsd.conf";
 MYARG="jconf"
 MYOPTARG="inter ver arch fstab"
@@ -43,7 +43,7 @@ EOF
 
 mkrcconf() {
     cp $temprcconf $rcconf
-    modconf ${rcconf} pkglist ""
+    ${miscdir}/sysrc -qf ${rcconf} pkglist="" >/dev/null
 }
 
 ### MAIN
@@ -61,8 +61,8 @@ trap "rm -f ${temprcconf}" HUP INT ABRT BUS TERM  EXIT
 . ${temprcconf}
 . ${buildconf}
 
-modconf ${temprcconf} ver ${ver}
-modconf ${temprcconf} arch ${arch}
+${miscdir}/sysrc -qf ${temprcconf} ver=${ver} > /dev/null
+${miscdir}/sysrc -qf ${temprcconf} arch=${arch} > /dev/null
 
 . ${temprcconf}
 
@@ -159,14 +159,25 @@ fi
 
 ### COPY FROM BASE
 if [ "${ver}" != "empty" ]; then
-    if ! populate_cdir ${src} ${data}; then
-	[ "${mdsize}" != "0" ] && cbsd unmountmd jroot=${data}
-	err 1 "Can't populate $data from $src"
+
+    if [ "$baserw" = "1" ]; then
+	if ! populate_cdir ${src} ${data}; then
+	    [ "${mdsize}" != "0" ] && cbsd unmountmd jroot=${data}
+	    err 1 "Can't populate $data from $src"
+	fi
+    else
+	cp -rP ${src}/etc ${data}/
+	cp -rP ${src}/root ${data}/
+	mtree -deU -f ${src}/etc/mtree/BSD.root.dist -p ${data} >/dev/null
+	mtree -deU -f ${src}/etc/mtree/BSD.usr.dist -p ${data}/usr >/dev/null
+        mtree -deU -f ${src}/etc/mtree/BSD.var.dist -p ${data}/var >/dev/null
+        mtree -deU -f ${src}/etc/mtree/BIND.chroot.dist -p ${data}/var/named >/dev/null
+        mtree -deU -f ${src}/etc/mtree/BSD.sendmail.dist -p ${data} >/dev/null
     fi
 
     touch "${data}/etc/fstab"
 
-    [ -d ${data}/var ] || mkdir ${data}/var
+    [ -d ${data}/usr/home ] || mkdir ${data}/usr/home
     [ -d ${data}/usr/local ] || mkdir ${data}/usr/local
     [ -d ${data}/usr/compat ] || mkdir ${data}/usr/compat
     [ -d ${data}/usr/ports ] || mkdir ${data}/usr/ports
@@ -192,7 +203,8 @@ if [ ${applytpl} -eq 1 ]; then
 
     [ ! -d "${data}/usr/local/etc" ] && mkdir -p "${data}/usr/local/etc"
 
-    generate_pkgconf -a ${arch} -v ${ver} > ${data}/usr/local/etc/pkg.conf
+#    generate_pkgconf -a ${arch} -v ${ver} > ${data}/usr/local/etc/pkg.conf
+    [ -f "/usr/local/etc/pkg.conf" ] && cp /usr/local/etc/pkg.conf ${data}/usr/local/etc/pkg.conf
 fi
 
 if [ "${pkglist}" != "NO" -a "${ver}" != "empty" -a -f "${pkglist}" ]; then
diff --git a/nodectl/node b/nodectl/node
--- a/nodectl/node
+++ b/nodectl/node
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v9.1.0
+#v9.2.2
 globalconf="${workdir}/cbsd.conf";
 MYARG="mode"
 MYOPTARG="node port rootkeyfile pw"
@@ -14,13 +14,15 @@ pw = password of cbsd user from remote node\n"
 . ${globalconf}
 . ${subr}
 . ${tools}
+. ${color}
+. ${nodes}
 init $*
 
 nodeadd()
 {
-    [ -n "${node}" ] || err 1 "Empty node"
+    [ -z "${node}" ] && err 1 "${MAGENTA}Empty node${NORMAL}"
     [ -z "${port}" ] && port=22222
-    [ -z "${pw}" ] && err 1 "Empty pw"
+    [ -z "${pw}" ] && err 1 "${MAGENTA}Empty pw${NORMAL}"
     [ -z "${rootkeyfile}" ] && rootkeyfile="/root/.ssh/id_rsa"
 
     if iptype $node; then
@@ -32,14 +34,14 @@ nodeadd()
 
     case $? in
 	0)
-	    [ -z "$NODENAME" ] && err 1 "No nodename found. Check remote cbsd settings"
-	    echo "$node has nodename ${NODENAME}"
+	    [ -z "$NODENAME" ] && err 1 "${MAGENTA}No nodename found. Check remote cbsd settings${NORMAL}"
+	    ${ECHO} "${MAGENTA}${node} has nodename: ${GREEN}${NODENAME}${NORMAL}"
 	;;
 	1)
-	    err 1 "Connection problem with $node"
+	    err 1 "${MAGENTA}Connection problem: ${GREEN}${node}${NORMAL}"
 	;;
 	2)
-	    err 1 "Bad password or system user"
+	    err 1 "${MAGENTA}Bad password or system user${NORMAL}"
 	;;
     esac
 
@@ -48,47 +50,59 @@ nodeadd()
 
     case $? in
 	0)
-	    echo "${node} Added successfull"
+	    ${ECHO} "${MAGENTA}Added successfull: ${GREEN}${node}${NORMAL}"
 	    LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
-	    modconf ${rsshdir}/${NODENAME}.node SSHKEY $LOCALKEY
-	    modconf ${rsshdir}/${NODENAME}.node IP $node
-	    modconf ${rsshdir}/${NODENAME}.node PORT $port
-	    A=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=select --nodename=${NODENAME} --param=ip`
+	    ${miscdir}/sysrc -qf ${rsshdir}/${NODENAME}.node SSHKEY=$LOCALKEY > /dev/null
+	    ${miscdir}/sysrc -qf ${rsshdir}/${NODENAME}.node IP=$node > /dev/null
+	    ${miscdir}/sysrc -qf ${rsshdir}/${NODENAME}.node PORT=$port > /dev/null
+	    A=`cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=get --nodename=${NODENAME} --param=ip`
 	    if [ -z "${A}" ]; then
 		cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=insert --nodename=${NODENAME} --ip=${node} --port=${port} --keyfile=${LOCALKEY} --rootkeyfile=$rootkeyfile --invfile=inv.${NODENAME}.sqlite
 	    else
-		echo "${node} Already exist in database, updating..."
+		${ECHO} "${MAGENTA}Already exist in database, updating: ${GREEN}${node}${NORMAL}"
 		cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=delete --nodename=${NODENAME}
 		cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=insert --nodename=${NODENAME} --ip=${node} --port=${port} --keyfile=${LOCALKEY} --rootkeyfile=$rootkeyfile --invfile=inv.${NODENAME}.sqlite
 	    fi
+	    idle_update ${NODENAME}
+	    cbsd retrinv node=${NODENAME}
 	;;
 	1)
 	    cat ${DEBLOG}
-	    err 1 "Error: Bad password"
+	    err 1 "${MAGENTA}Error: Bad password${NORMAL}"
 	;;
 	2)
 	    cat ${DEBLOG}
-	    err 1 "Error: No key found or wrong hostname. Make initenv on remote machine"
+	    err 1 "${MAGENTA}Error: No key found or wrong hostname. Make initenv on remote machine${NORMAL}"
 	;;
 	*)
 	    cat ${DEBLOG}
-	    err 1 "Error: Unkown error"
+	    err 1 "${MAGENTA}Error: Unkown error${NORMAL}"
 	;;
     esac
 }
 
 nodedel()
 {
-    [ -n "${node}" ] || err 1 "Empty node"
+    _descext="descr role domain notes location"
+
+    [ -n "${node}" ] || err 1 "${MAGENTA}Empty node${NORMAL}"
     NODECONF="${rsshdir}/${node}.node"
 
-    [ -f "${NODECONF}" ] || err 1 "No such node config"
+    [ ! -f "${NODECONF}" ] && err 1 "${MAGENTA}No such node config: ${GREEN}${NODECONF}${NORMAL}"
     . ${NODECONF}
 
     [ -f ${SSHKEY} ] && rm -f ${SSHKEY}
     rm -f ${NODECONF}
+    [ -f "${dbdir}/${node}.sqlite" ] && rm -f "${dbdir}/${node}.sqlite"
     cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=delete --nodename=${node}
-    echo "Removed"
+
+    #descriptions die too
+    find ${dbdir}/nodedescr -type f -depth 1 -maxdepth 1 -name ${node}.\*.descr -delete
+    for i in ${_descext}; do
+	[ -f "${dbdir}/nodedescr/${node}.${i}" ] && rm -f "${dbdir}/nodedescr/${node}.${i}"
+    done
+
+    ${ECHO} "${MAGENTA}Removed${NORMAL}"
 }
 
 
@@ -103,6 +117,6 @@ case "${mode}" in
 	cbsd nodesql --dbfile=${dbdir}/nodes.sqlite --action=list
     ;;
     *)
-	err 1 "Unknown mode"
+	err 1 "${MAGENTA}Unknown mode${NORMAL}"
     ;;
 esac
diff --git a/tools/pkgbrowser b/tools/pkgbrowser
--- a/tools/pkgbrowser
+++ b/tools/pkgbrowser
@@ -1,15 +1,19 @@
 #!/bin/sh
-#v9.1.0
+#v9.2.1
 globalconf="${workdir}/cbsd.conf";
 MYARG=""
-MYOPTARG="out"
+MYOPTARG="out repo conf"
 MYDESC="Generate choosen package list from repository"
-ADDHELP="out=path_to_file with result, instead of random\n"
+ADDHELP="out=path_to_file with result, instead of random\n\
+repo= use this repository\n\
+conf= use this pkg.conf\n"
 
 [ -f "${globalconf}" ] || err 1 "no such conf file";
 . ${globalconf}
 . ${subr}
 . ${tools}
+. ${color}
+
 init $*
 
 [ -z "${out}" ] && out="${ftmpdir}/pkgbrowser.$$"
@@ -18,20 +22,35 @@ tmp2="${ftmpdir}/pkgmytmp2.$$"
 
 DIALOG=${DIALOG=/usr/bin/dialog}
 
-truncate -s0 ${tmp1}
-trap "rm -f $tmp1 $tmp2" 0 1 2 3 4 5 9
+truncate -s0 ${tmp1} ${tmp2}
 
-printf "Building pkg list"
-LIST=`pkg rquery "%n-%v"`
+PKGCONF=""
+PKGOPT=""
 
-[ $? -ne 0 ] && err 1 "Repository not configured or network error"
+if [ -n "${repo}" ]; then
+    PKGCONF="${ftmpdir}/mypkg.conf.$$"
+    echo "PACKAGESITE: ${repo}" > ${PKGCONF}
+    trap "rm -f ${tmp1} ${tmp2} ${PKGCONF}" 0 1 2 3 4 5 9
+elif [ -n "${conf}" ]; then
+    [ -f "${conf}" ] && PKCONF="${conf}"
+fi
+
+[ -z "${PKGCONF}" -a -f "/usr/local/etc/pkg.conf" ] && PKGCONF="/usr/local/etc/pkg.conf"
+#[ -z "${PKGCONF}" ] && err 0 "${MAGENTA}No such valid configuration${NORMAL}"
+
+[ -z "${PKGCONF}" ] && PKGOPT="-C ${PKGCONF}"
+
+printf "${MAGENTA}Building pkg list${NORMAL}"
+LIST=`pkg ${PKGOPT} rquery "%n-%v"`
+
+[ $? -ne 0 ] && err 1 "${MAGENTA}Repository not configured or network error${NORMAL}"
 
 for i in ${LIST}; do
-    A=`pkg query "%ro" $i`
-    [ -z "${A}" ] &&  printf "." && echo $i >> ${tmp1}
+    A=`pkg ${PKGOPT} query "%ro" $i`
+    [ -z "${A}" ] &&  dot "pkg ${PKGOPT} query" && echo $i >> ${tmp1}
 done
 
-printf "done\r\nSorting...\r\n"
+printf "${GREEN}done${NORMAL}\r\n${MAGENTA}Sorting...${NORMAL}\r\n"
 
 cat > $tmp2 << EOF
 --colors --backtitle "\Z1Select packages" --separate-output --title "Select packages" --checklist "Use space for mark packages \n" 0 61 0
@@ -48,6 +67,6 @@ sort -u $tmp1 | \
 
 ${DIALOG} --file ${tmp2} 2>$out
 
-[ $? -ne 0 -o `wc -l ${out}|awk '{printf $1}'` = "0" ] && rm -f ${out} && err 1 "No pkg selected"
+[ $? -ne 0 -o `wc -l ${out}|awk '{printf $1}'` = "0" ] && rm -f ${out} && err 1 "${MAGENTA}No pkg selected${NORMAL}"
 
 echo $out
