wip: mnt_start hook for jail, MACROS for external cmd

diff --git a/jailctl/jcreate b/jailctl/jcreate
--- a/jailctl/jcreate
+++ b/jailctl/jcreate
@@ -212,7 +212,7 @@ get_base -v ${ver} ${_basename_args}
 
 ${ECHO} "${N1_COLOR}Please wait: ${N2_COLOR}this will take a while...${N0_COLOR}"
 
-[ -d "${data}" ] && removedata ${data}
+[ -d "${data}" ] && remove_data_dir ${data}
 [ ! -d ${path} -a "${baserw}" -eq 0 ] && ${MKDIR_CMD} -m 0755 -p ${path}
 [ ! -d ${jailsysdir}/${jname} ] && ${MKDIR_CMD} -p ${jailsysdir}/${jname}
 
@@ -223,13 +223,14 @@ if [ "${mnt_start}" != "0" ]; then
 	${ECHO} "${N1_COLOR}Execute mnt_start script: ${N2_COLOR}${mnt_start}${N0_COLOR}..."
 	# external mount, reset zfsfeat
 	zfsfeat=0
-	create_fs ${data}
-	[ $? -ne 0 ] && err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
+	[ ! -d "${data}" ] && ${MKDIR_CMD} ${data}
 	${mnt_start} -d ${data} -f ${jailfstabdir} -j ${jname} -r ${jailrcconfdir} -s ${jailsysdir}/${jname}
 	_ret=$?
 	if [ ${_ret} -ne 0 ]; then
 		err 1 "${W1_COLOR}error: ${N1_COLOR}mnt_start script failed: ${N2_COLOR}${mnt_start} ${jname}${N0_COLOR}"
 	fi
+	create_fs ${data}
+	[ $? -ne 0 ] && err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
 else
 	create_fs ${data}
 	[ $? -ne 0 ] && err 1 "${N1_COLOR}create_fs failed${N0_COLOR}"
@@ -365,7 +366,7 @@ else
 	${MV_CMD} ${rcconf} /tmp
 	#cleanup
 	[ -f "${mount_fstab}" ] && ${RM_CMD} -f ${mount_fstab}
-	removedata ${data}
+	remove_data_dir ${data}
 	exit 1
 fi
 
