pkg module: several improvements
 - added optional pkg.conf with which we can regulate some behavior:
   a) number or retry when pkg failed (default: 2)
   b) errcode behavior for pkg bootstrap (0, not fatal by def) and pkg action (1, fatal by default)

 - verbose/output control

if when creating the jail we were unable to install the necessary software,
this is considered an error creating the environment

It can be changed via ~cbsd/etc/pkg.conf. See sample: /usr/local/cbsd/modules/pkg.d/etc-sample/pkg.conf

Discussed in Issue #452

diff --git a/jailctl/jcreate b/jailctl/jcreate
--- a/jailctl/jcreate
+++ b/jailctl/jcreate
@@ -335,6 +335,16 @@ if [ ${res} -eq 0 ]; then
 	# pkg bootstrap && user accounting
 	if [ "${ver}" != "empty" ]; then
 		postcreate_module_action ${jname} ${jconf}
+		ret=$?
+		# if ret != 0, remove jail: something wrong
+		if [ ${ret} -ne 0 ]; then
+			${ECHO}
+			${ECHO} "${N1_COLOR}Creating ${jname} failed: ${N2_COLOR}postcreate_module_action${N0_COLOR}"
+			# cleanup
+			[ -f "${mount_fstab}" ] && ${RM_CMD} -f ${mount_fstab}
+			jremove jname=${jname}
+			exit ${ret}
+		fi
 	fi
 
 	echo
@@ -347,7 +357,6 @@ if [ ${res} -eq 0 ]; then
 	${ECHO} "${N1_COLOR}Creating ${jname} complete: ${N2_COLOR}Enjoy!${N0_COLOR}"
 
 	${RM_CMD} -f ${rcconf}
-
 	[ "${mdsize}" != "0" ] && unmountmd jroot=${data}
 else
 	${ECHO}
@@ -379,7 +388,6 @@ if [ -n "${with_img_helpers}" ]; then
 fi
 
 [ ! -r ${jailsysdir}/${jname}/local.sqlite ] && /usr/local/bin/cbsd ${miscdir}/updatesql ${jailsysdir}/${jname}/local.sqlite ${distdir}/share/local-jailnic.schema jailnic
-
 
 # rctl
 . ${distsharedir}/rctl.conf
