taskd: reset SQLITE_SEQUENCE when we do flushlog, add exclusive args ; bhyve: Improve UEFI boot, add bhyve-ppt script for manage ppt devices, add media script for manage virtual storage devices; add merge script to merge ascii-basedfile profiles;

diff --git a/jailctl/jimport b/jailctl/jimport
--- a/jailctl/jimport
+++ b/jailctl/jimport
@@ -176,8 +176,14 @@ if [ -n "${vm_zvol_list}" ]; then
 
 		dsk=${jaildatadir}/${jname}-${jaildatapref}/${i}.vhd
 
-		if ! bhyve_create_dsk ${dsk} ${vol_size} 1; then
-			err 1 "${MAGENTA}Unable bhyve_create_dsk for disk: ${i}${NORMAL}"
+		_res=
+		_msg=
+
+		_msg=$( bhyve_create_dsk ${dsk} ${vol_size} 1 )
+		_res=$?
+		if [ ${_res} -ne 0 ]; then
+			bremove ${jname}
+			err 1 "Error: Couldn't create the image file. ${_msg}"
 		fi
 
 		# ___NCSTART_ZVOL_dsk1=1
diff --git a/tools/jail2iso b/tools/jail2iso
--- a/tools/jail2iso
+++ b/tools/jail2iso
@@ -270,6 +270,7 @@ EOF
 create_img_for_dir()
 {
 	local base_size minfree1 minfree2
+	local _res _msg
 
 	[ -z "${freesize}" ] && freesize=0
 	[ -z "${imgfreesize}" ] && imgfreesize=0
@@ -312,8 +313,10 @@ create_img_for_dir()
 	all_size=$(( base_size + freesize + minfree1 + minfree2 + imgfreesize + swapsize ))
 	fs_size=$(( base_size + freesize + minfree1 + minfree2 ))
 
-	if ! bhyve_create_dsk ${2} ${all_size} 0; then
-		err 1 "Error: Couldn't create the image file. ${mdimage}"
+	_msg=$( bhyve_create_dsk ${2} ${all_size} 0 )
+	_res=$?
+	if [ ${_res} -ne 0 ]; then
+		err 1 "Error: Couldn't create the image file. ${_msg}"
 	fi
 }
 
