b-related commands

diff --git a/jailctl/jmkrcconf b/jailctl/jmkrcconf
--- a/jailctl/jmkrcconf
+++ b/jailctl/jmkrcconf
@@ -41,6 +41,24 @@ if [ "${emulator}" = "bhyve" ]; then
 	[ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
 	echo "${i}=\"${VAL}\";"
     done
+
+
+    unset dsklist
+    sqldelimer=" "
+
+    for last_disk in $( seq 1 16 ); do
+	unset dsk_controller${last_disk}
+    done
+
+    dsk_id=1
+
+    cbsdsql local SELECT dsk_controller,dsk_path,dsk_slot,dsk_type FROM bhyvedsk WHERE jname=\"${jname}\" | while read dsk_controller dsk_path dsk_slot dsk_type; do
+	echo "dsk_controller${dsk_id}=\"${dsk_controller}\";"
+	echo "dsk_path${dsk_id}=\"${dsk_path}\";"
+	echo "dsk_slot${dsk_id}=\"${dsk_slot}\";"
+	echo "dsk_type${dsk_id}=\"${dsk_type}\";"
+	dsk_id=$(( dsk_id + 1 ))
+    done || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
 fi
 
 #finally set jname
