Make CBSD more friendly for DragonFlyBSD. Nevertheless, while in DF have the old jail framework, CBSD unusable there; Fixes for nic opeation in brename/bclone; Add toggle service startup menu choosing in jconstruct-tui; Inventory now included through cbsd.conf in all scripts

diff --git a/jailctl/jmkrcconf b/jailctl/jmkrcconf
--- a/jailctl/jmkrcconf
+++ b/jailctl/jmkrcconf
@@ -12,7 +12,6 @@ MYOPTARG="$JARG mode"
 MYDESC="Create ascii rc.conf for jail"
 ADDHELP="mode=force for modification on the running jail\n"
 
-. ${inventory}
 . ${tools}
 . ${strings}
 init $*
@@ -41,9 +40,9 @@ if [ "${emulator}" = "bhyve" ]; then
 		echo "${i}=\"${VAL}\";"
 	done
 
-	unset dsklist
 	sqldelimer=" "
 
+	# DSK area
 	for last_disk in $( seq 1 16 ); do
 		unset dsk_controller${last_disk}
 	done
@@ -51,12 +50,31 @@ if [ "${emulator}" = "bhyve" ]; then
 	dsk_id=1
 
 	cbsdsql local SELECT dsk_controller,dsk_path,dsk_slot,dsk_type FROM bhyvedsk WHERE jname=\"${jname}\" | while read dsk_controller dsk_path dsk_slot dsk_type; do
+		[ -z "${dsk_type}" ] && continue
 		echo "dsk_controller${dsk_id}=\"${dsk_controller}\";"
 		echo "dsk_path${dsk_id}=\"${dsk_path}\";"
 		echo "dsk_slot${dsk_id}=\"${dsk_slot}\";"
 		echo "dsk_type${dsk_id}=\"${dsk_type}\";"
 		dsk_id=$(( dsk_id + 1 ))
 	done || err 1 "${MAGENTA}Error while create disk map${NORMAL}"
+
+	# NIC area
+	for last_nic in $( seq 1 16 ); do
+		unset nic_driver${last_disk}
+	done
+
+	nic_id=1
+
+	cbsdsql local SELECT nic_order,nic_driver,nic_slot,nic_type,nic_parent,nic_hwaddr FROM bhyvenic WHERE jname=\"${jname}\" | while read nic_order nic_driver nic_slot nic_type nic_parent nic_hwaddr; do
+		[ -z "${nic_hwaddr}" ] && continue
+		echo "nic_order${nic_id}=\"${nic_order}\";"
+		echo "nic_driver${nic_id}=\"${nic_driver}\";"
+		echo "nic_slot${nic_id}=\"${nic_slot}\";"
+		echo "nic_type${nic_id}=\"${nic_type}\";"
+		echo "nic_parent${nic_id}=\"${nic_parent}\";"
+		echo "nic_hwaddr${nic_id}=\"${nic_hwaddr}\";"
+		nic_id=$(( nic_id + 1 ))
+	done || err 1 "${MAGENTA}Error while create nic map${NORMAL}"
 fi
 
 #finally set jname
