convert to builtin; style

diff --git a/jailctl/jmkrcconf b/jailctl/jmkrcconf
--- a/jailctl/jmkrcconf
+++ b/jailctl/jmkrcconf
@@ -1,7 +1,7 @@
 #!/usr/bin/env cbsd
 #v10.0.4
 CBSDMODULE="jail"
-MYARG="jname"
+CIXARG="jname"
 
 . ${subrdir}/nc.subr
 
@@ -10,11 +10,30 @@ MYARG="jname"
 
 MYOPTARG="$JARG mode"
 MYDESC="Create ascii rc.conf for jail"
-ADDHELP="mode=force for modification on the running jail\n"
+ADDHELP="
+${H3_COLOR}Description${N0_COLOR}:
+
+Create ascii rc.conf for jail.
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}mode=${N0_COLOR} - set 'force' for modification on the running jail;
+
+${H3_COLOR}Examples${N0_COLOR}:
+
+ # cbsd jmkrcconf jname=myjail
+ # cbsd jmkrcconf jname=myjail mode=force
+
+${H3_COLOR}See also${N0_COLOR}:
+
+  cbsd jconfig --help
+  cbsd jset --help
+
+"
 
 . ${tools}
 . ${strings}
-. ${cbsdinit}
+cixinit
 
 . ${subrdir}/rcconf.subr
 [ $? -eq 1 ] && err 1 "${N1_COLOR}No such jail: ${N2_COLOR}${jname}${N0_COLOR}"
@@ -27,7 +46,7 @@ relative_path="1";
 EOF
 
 for i in ${JARG}; do
-	VAL=$( cbsdsqlro local "SELECT ${i} FROM jails WHERE jname='${jname}'" )
+	capture VAL cbsdsqlro local "SELECT ${i} FROM jails WHERE jname='${jname}'"
 	[ -z "${VAL}" ] && continue
 	[ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
 	echo "${i}=\"${VAL}\";"
@@ -38,7 +57,7 @@ if [ "${emulator}" = "bhyve" ]; then
 	. ${distsharedir}/bhyve.conf
 	for i in ${MYCOL}; do
 		[ "${i}" = "jname" ] && continue
-		VAL=$( cbsdsqlro local "SELECT ${i} FROM bhyve WHERE jname='${jname}'" )
+		capture VAL cbsdsqlro local "SELECT ${i} FROM bhyve WHERE jname='${jname}'"
 		[ "${VAL}" = "(null)" -o -z "${VAL}" ] && VAL=""
 		echo "${i}=\"${VAL}\";"
 	done
@@ -46,29 +65,31 @@ if [ "${emulator}" = "bhyve" ]; then
 	sqldelimer=" "
 
 	# DSK area
-	for last_disk in $( seq 1 16 ); do
+	capture _dsk_list ${SEQ_CMD} 1 16
+	for last_disk in ${_dsk_list}; do
 		unset dsk_controller${last_disk}
 	done
 
 	dsk_id=1
-
-	cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_controller,dsk_path,dsk_slot,dsk_type FROM bhyvedsk WHERE jname=\"${jname}\" | while read dsk_controller dsk_path dsk_slot dsk_type; do
+	capture _dsk_rows cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT dsk_controller,dsk_path,dsk_slot,dsk_type FROM bhyvedsk WHERE jname='${jname}'"
+	while read dsk_controller dsk_path dsk_slot dsk_type; do
 		[ -z "${dsk_type}" ] && continue
 		echo "dsk_controller${dsk_id}=\"${dsk_controller}\";"
 		echo "dsk_path${dsk_id}=\"${dsk_path}\";"
 		echo "dsk_slot${dsk_id}=\"${dsk_slot}\";"
 		echo "dsk_type${dsk_id}=\"${dsk_type}\";"
 		dsk_id=$(( dsk_id + 1 ))
-	done || err 1 "${N1_COLOR}Error while create disk map${N0_COLOR}"
+	done <<< "${_dsk_rows}" || err 1 "${N1_COLOR}Error while create disk map${N0_COLOR}"
 
 	# NIC area
-	for last_nic in $( seq 1 16 ); do
-		unset nic_driver${last_disk}
+	capture _nic_list ${SEQ_CMD} 1 16
+	for last_nic in ${_nic_list}; do
+		unset nic_driver${last_nic}
 	done
 
 	nic_id=1
-
-	cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT nic_order,nic_driver,nic_slot,nic_type,nic_parent,nic_hwaddr FROM bhyvenic WHERE jname=\"${jname}\" | while read nic_order nic_driver nic_slot nic_type nic_parent nic_hwaddr; do
+	capture _nic_rows cbsdsqlro ${jailsysdir}/${jname}/local.sqlite "SELECT nic_order,nic_driver,nic_slot,nic_type,nic_parent,nic_hwaddr FROM bhyvenic WHERE jname='${jname}'"
+	while read nic_order nic_driver nic_slot nic_type nic_parent nic_hwaddr; do
 		[ -z "${nic_hwaddr}" ] && continue
 		echo "nic_order${nic_id}=\"${nic_order}\";"
 		echo "nic_driver${nic_id}=\"${nic_driver}\";"
@@ -77,7 +98,7 @@ if [ "${emulator}" = "bhyve" ]; then
 		echo "nic_parent${nic_id}=\"${nic_parent}\";"
 		echo "nic_hwaddr${nic_id}=\"${nic_hwaddr}\";"
 		nic_id=$(( nic_id + 1 ))
-	done || err 1 "${N1_COLOR}Error while create nic map${N0_COLOR}"
+	done <<< "${_nic_rows}" || err 1 "${N1_COLOR}Error while create nic map${N0_COLOR}"
 fi
 
 #finally set jname
diff --git a/jailctl/jscp b/jailctl/jscp
--- a/jailctl/jscp
+++ b/jailctl/jscp
@@ -1,11 +1,23 @@
 #!/usr/bin/env cbsd
 #v13.0.2
 CBSDMODULE="jail"
-MYARG=""
-MYOPTARG="verbose"
+CIXARG=""
+CIXOPTARG="verbose"
 MYDESC="Get put file to remove nodes"
-ADDHELP="[verbose=1] jail1:remotefile1 localfile1 [ localfile2 jail2@:remotefile2 ]\n\
-verbose=1 for debug information\n"
+ADDHELP="${H3_COLOR}Description${N0_COLOR}:
+  Copy files to/from remote jail via network.
+
+${H3_COLOR}Options${N0_COLOR}:
+  verbose=1         ; enable debug output
+
+${H3_COLOR}Usage${N0_COLOR}:
+  cbsd jscp verbose=1 jail1:remotefile1 localfile1 [ localfile2 jail2@:remotefile2 ]
+
+${H3_COLOR}Examples${N0_COLOR}:
+  cbsd jscp jail1:/etc/hosts /tmp/hosts
+  cbsd jscp /tmp/file jail1:/tmp/file
+"
+
 EXTHELP="wf_jscp"
 
 # ToDo:
@@ -20,16 +32,15 @@ EXTHELP="wf_jscp"
 
 verbose=0
 cloud_api=0
-. ${cbsdinit}
+cixinit
 
 
 getjname()
 {
-	local _t
-
-	_t=$( echo ${1} | ${GREP_CMD} ":")
-
-	[ $? -ne 0 ] && return 1
+	case "${1}" in
+		*:*) ;;
+		*) return 1 ;;
+	esac
 
 	jname=${1%%:*}
 	rfile=${1##*:}
@@ -39,12 +50,12 @@ try_remote()
 {
 	# this is only wrapper for compile correct arguments for cbsd nodescp
 
-	node=$( jwhereis ${jname} )
+	capture node jwhereis ${jname}
 
 	[ -z "${node}" ] && log_err 1 "Node not found for jail ${jname}"
 
 	cbsdlogger NOTICE ${CIX_APP}: try to get remote jstatus for ${jname} on ${node}
-	status=$( rexe node=${node} cbsd jstatus ${jname} )
+	capture status rexe node=${node} cbsd jstatus ${jname}
 	[ "${status}" = "0" ] && log_err 1 "jail ${jname} not running on ${node}"
 	sqlfile="${node}"
 	. ${subrdir}/rcconf.subr
@@ -77,9 +88,12 @@ scp()
 
 	Makefile="${CIX_PWD}/CBSDfile"
 	if [ -r "${Makefile}" ]; then
-		[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
+		[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 		. ${Makefile}
-		all_jail_list=$( ${GREP_CMD} -E '^jail_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#jail_##g )
+		capture _grep_out ${GREP_CMD} -E '^jail_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile}
+		capture _xargs_out ${XARGS_CMD} <<< "${_grep_out}"
+		capture _tr_out ${TR_CMD} -d "()" <<< "${_xargs_out}"
+		capture all_jail_list ${SED_CMD} s#jail_##g <<< "${_tr_out}"
 
 		# limit by single jail
 		[ -n "${jname}" ] && all_jail_list="${jname}"
@@ -94,10 +108,10 @@ scp()
 	fi
 
 	if [ ${cbsd_api} -eq 1 ]; then
-		CURL_CMD=$( which curl )
+		capture CURL_CMD which curl
 		[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
-		[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
-		_cid=$( ${miscdir}/cbsd_md5 "${CLOUD_KEY}" )
+		[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
+		capture _cid ${miscdir}/cbsd_md5 "${CLOUD_KEY}"
 
 		found=0
 		for i in ${all_jail_list}; do
@@ -109,26 +123,27 @@ scp()
 		[ ${found} -eq 0 ] && err 1 "${N1_COLOR}${CIX_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 		for _jname in ${all_jail_list}; do
-			_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${_jname} 2>&1 )
+			capture _ssh ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${_jname} 2>&1
 			_ret=$?
 			if [ ${_ret} -ne 0 ]; then
-				${ECHO} "${N1_COLOR}${CIX_APP} error: curl error1: ${N2_COLOR}${_ssh}${N0_COLOR}"
-				${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+				echo "${N1_COLOR}${CIX_APP} error: curl error1: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
 				continue
 			fi
-			_ssh_string=$( echo "${_ssh}" | ${JQ_CMD} '.ssh_string' | ${TR_CMD} -d '"' )
-			_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh_string}" )
+			capture _jq_out ${JQ_CMD} '.ssh_string' <<< "${_ssh}"
+			capture _ssh_string ${TR_CMD} -d '"' <<< "${_jq_out}"
+			capture _ssh_pref substr --pos=0 --len=3 --str="${_ssh_string}"
 
 			if [ "${_ssh_pref}" != "ssh" ]; then
-				${ECHO} "${N1_COLOR}${CIX_APP} error: curl error2, no ssh_string:\n${N2_COLOR}${_ssh}${N0_COLOR}"
-				${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+				echo "${N1_COLOR}${CIX_APP} error: curl error2, no ssh_string:\n${N2_COLOR}${_ssh}${N0_COLOR}"
+				echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
 				continue
 			fi
-			_ssh_len=$( strlen "${_ssh_string}" )
-			_ssh_post=$( substr --pos=5 --len=${_ssh_len} --str="${_ssh_string}" )
-			#echo "${SSH_CMD} ${_ssh_post}"
-			_ssh_ip=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $1}' )
-			_ssh_port=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $2}' | ${TR_CMD} -d '\-p' )
+			capture _ssh_len strlen "${_ssh_string}"
+			capture _ssh_post substr --pos=5 --len=${_ssh_len} --str="${_ssh_string}"
+			capture _ssh_ip ${AWK_CMD} '{printf $1}' <<< "${_ssh_post}"
+			capture _awk_port ${AWK_CMD} '{printf $2}' <<< "${_ssh_post}"
+			capture _ssh_port ${TR_CMD} -d '\-p' <<< "${_awk_port}"
 			# rewrite
 			if [ -n "${SUDO_USER}" ]; then
 				if [ -r /home/${SUDO_USER}/.ssh/id_ed25519 ]; then
@@ -153,7 +168,7 @@ scp()
 			fi
 
 			if [ ${rarg} -eq 1 ]; then
-				DIR=$( ${DIRNAME_CMD} ${2} )
+				capture DIR ${DIRNAME_CMD} ${2}
 				[ ! -d "${DIR}" ] && ${MKDIR_CMD} -p ${DIR}
 				scp_exec="${SCP_CMD} -oPort=${_ssh_port} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_ip}:${rfile} ${2}"
 				echo "[debug1] ${scp_exec}"
@@ -183,7 +198,7 @@ scp()
 			${_cmd}
 			_ret=$?
 		fi
-		[ ${_ret} -ne 0 ] && ${ECHO} "${N1_COLOR}jscp cmd failed: ${N2_COLOR}${_cmd}${N0_COLOR}"
+		[ ${_ret} -ne 0 ] && echo "${N1_COLOR}jscp cmd failed: ${N2_COLOR}${_cmd}${N0_COLOR}"
 		return ${_ret}
 	fi
 
@@ -192,7 +207,7 @@ scp()
 	[ ${baserw} -eq 1 ] && path="${data}"
 
 	if [ ${rarg} -eq 1 ]; then
-		DIR=$( ${DIRNAME_CMD} ${2} )
+		capture DIR ${DIRNAME_CMD} ${2}
 		[ ! -d "${DIR}" ] && ${MKDIR_CMD} -p ${DIR}
 
 		if [ -n "${RSYNC_CMD}" ]; then
@@ -221,7 +236,7 @@ scp()
 			[ ${verbose} -eq 1 ] && set +o xtrace
 		fi
 	else
-		DIR=$( ${DIRNAME_CMD} ${path}${rfile} )
+		capture DIR ${DIRNAME_CMD} ${path}${rfile}
 		[ ${verbose} -eq 1 ] && set -o xtrace
 		[ ! -d "${DIR}" ] && ${MKDIR_CMD} -p "${DIR}"
 		[ ${verbose} -eq 1 ] && set +o xtrace
@@ -252,7 +267,7 @@ scp()
 		fi
 	fi
 
-	[ ${_ret} -ne 0 ] && ${ECHO} "${N1_COLOR}jscp cmd failed: ${N2_COLOR}${_cmd}${N0_COLOR}"
+	[ ${_ret} -ne 0 ] && echo "${N1_COLOR}jscp cmd failed: ${N2_COLOR}${_cmd}${N0_COLOR}"
 	return ${_ret}
 }
 
@@ -264,7 +279,7 @@ ARGS=
 
 # exclude jname= and mode= params from args str
 for i in $*; do
-	prefix8=$( substr --pos=0 --len=7 --str="${i}" )
+	capture prefix8 substr --pos=0 --len=7 --str="${i}"
 	[ "${prefix8}" = "verbose=" ] && continue
 	if [ -z "${ARGS}" ]; then
 		ARGS="${i}"
@@ -281,6 +296,6 @@ fi
 
 scp ${ARGS}
 ret=$?
-[ ${ret} -ne 0 ] && ${ECHO} "${N1_COLOR}jscp cmd failed: ${N2_COLOR}${_cmd}${N0_COLOR}"
+[ ${ret} -ne 0 ] && echo "${N1_COLOR}jscp cmd failed: ${N2_COLOR}${_cmd}${N0_COLOR}"
 
 exit ${ret}
diff --git a/modules/pkg.d/pkg b/modules/pkg.d/pkg
--- a/modules/pkg.d/pkg
+++ b/modules/pkg.d/pkg
@@ -1,5 +1,5 @@
 #!/usr/bin/env cbsd
-#v11.2.0
+#v11.2.1
 CBSDMODULE="jail"
 CIXARG="mode"
 CIXOPTARG="jname pkglist name repodir pkgconf chroot nomount cbsd_pkg_verbose cbsd_pkg_retry cbsd_pkg_interrupt_on_error cbsd_pkg_bootstrap_interrupt_on_error"
@@ -48,14 +48,13 @@ EXTHELP="modules/pkg.d"
 
 . ${subrdir}/nc.subr
 . ${tools}
-cloud_api=0
 cixinit
 
 # store values from args to overwrite config
 [ -n "${cbsd_pkg_retry}" ] && ocbsd_pkg_retry="${cbsd_pkg_retry}"
 [ -n "${cbsd_pkg_interrupt_on_error}" ] && ocbsd_pkg_interrupt_on_error="${cbsd_pkg_interrupt_on_error}"
 [ -n "${cbsd_pkg_bootstrap_interrupt_on_error}" ] && ocbsd_pkg_bootstrap_interrupt_on_error="${cbsd_pkg_bootstrap_interrupt_on_error}"
-[ -n "${cbsd_pkg_verbose}" ] && ocbsd_pkg_verbose="${cbsd_pkg_verbose=0}"
+[ -n "${cbsd_pkg_verbose}" ] && ocbsd_pkg_verbose="${cbsd_pkg_verbose}"
 
 . ${system}
 #defines
@@ -73,7 +72,7 @@ readconf pkg.conf
 [ -z "${PKG_SUFX}" ] && export PKG_SUFX=pkg
 
 # init defaults when pkg.conf is absent
-# see: ${CIX_DISTDIR}/modules/pkg.d/etc-sample/pkg.conf for detauls
+# see: ${CIX_DISTDIR}/modules/pkg.d/etc-sample/pkg.conf for details
 [ -z "${cbsd_pkg_retry}" ] && cbsd_pkg_retry=2
 [ -z "${cbsd_pkg_interrupt_on_error}" ] && cbsd_pkg_interrupt_on_error=1
 [ -z "${cbsd_pkg_bootstrap_interrupt_on_error}" ] && cbsd_pkg_bootstrap_interrupt_on_error=0
@@ -83,14 +82,9 @@ readconf pkg.conf
 [ -n "${ocbsd_pkg_retry}" ] && cbsd_pkg_retry="${ocbsd_pkg_retry}"
 [ -n "${ocbsd_pkg_interrupt_on_error}" ] && cbsd_pkg_interrupt_on_error="${ocbsd_pkg_interrupt_on_error}"
 [ -n "${ocbsd_pkg_bootstrap_interrupt_on_error}" ] && cbsd_pkg_bootstrap_interrupt_on_error="${ocbsd_pkg_bootstrap_interrupt_on_error}"
-[ -n "${ocbsd_pkg_verbose}" ] && cbsd_pkg_verbose="${ocbsd_pkg_verbose=0}"
+[ -n "${ocbsd_pkg_verbose}" ] && cbsd_pkg_verbose="${ocbsd_pkg_verbose}"
 
-if [ -n "${nomount}" ]; then
-	shift
-	nomount=${nomount}
-else
-	nomount=0
-fi
+nomount=${nomount:-0}
 
 PKGARGS=""
 TRAP=""
@@ -105,7 +99,7 @@ fi
 # check for cloud function when CBSDfile exist
 Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" -a "${CBSDFILE_RECURSIVE}" != "1" ]; then
-	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
+	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 	. ${Makefile}
 	all_jail_list=$( ${GREP_CMD} -E '^jail_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#jail_##g )
 
@@ -132,49 +126,38 @@ fi
 if [ ${cbsd_api} -eq 1 ]; then
 	[ -z "${CURL_CMD}" ] && capture CURL_CMD which curl
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
-	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
+	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
 	capture _cid ${miscdir}/cbsd_md5 "${CLOUD_KEY}"
 	for _jname in ${all_jail_list}; do
 		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${_jname} 2>&1 )
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl status error: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+			echo "${N1_COLOR}${CIX_APP} error: curl status error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
 			continue
 		fi
-		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh}" )
-		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
-			continue
-		fi
-		_ssh_len=$( strlen "${_ssh}" )
-		_ssh_post=$( substr --pos=5 --len=${_ssh_len} --str="${_ssh}" )
-		#echo "${SSH_CMD} ${_ssh_post}"
+		case "${_ssh}" in
+			ssh\ *)
+				_ssh_post=${_ssh#ssh }
+				;;
+			*)
+				echo "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+				continue
+				;;
+		esac
 		# rewrite
 		if [ -n "${SUDO_USER}" ]; then
 			if [ -r /home/${SUDO_USER}/.ssh/id_ed25519 ]; then
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_ed25519"
 			elif [ -r /home/${SUDO_USER}/.ssh/id_rsa ]; then
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_rsa"
-			else
-				date
 			fi
 		fi
 
-		_args=
-
-		# trim for jname= in "$*"
-		for i in ${CIX_OTHER_ARGS}; do
-			if [ -n "${_args}" ]; then
-				_args="${_args} ${i}"
-			else
-				_args="${i}"
-			fi
-		done
+		_args="${CIX_OTHER_ARGS}"
 
 		jexec_cmd="${SSH_CMD} -T -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_post}"
-		echo "[debug] ${jexec_cmd}"
 
 		case "${mode}" in
 			clean)
@@ -198,7 +181,7 @@ EOF
 					fi
 				;;
 			install)
-					${ECHO} "${N1_COLOR}pkg install, attempt: ${N2_COLOR}${_i}/${cbsd_pkg_retry}${N0_COLOR}"
+					echo "${N1_COLOR}pkg install, attempt: ${N2_COLOR}${_i}/${cbsd_pkg_retry}${N0_COLOR}"
 					${jexec_cmd} /bin/sh <<EOF
 ${ENV_CMD} SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes IGNORE_OSVERSION=yes pkg install -g -U -y ${_args}
 EOF
@@ -217,11 +200,6 @@ EOF
 				echo "CBSDfile/API unsupported yet: ${mode}"
 				;;
 		esac
-
-
-#	${jexec_cmd} <<CBSD_EOF
-#${cmd}
-#CBSD_EOF
 	done
 	exit 0
 fi
@@ -261,7 +239,7 @@ pkg_multi_init()
 	[ -z "${task_owner}" ] && err 1 "${N1_COLOR}multiple_processing_spawn: empty -o multiple_task_owner${N0_COLOR}"
 
 	. ${subrdir}/multiple.subr
-	${ECHO} "${N1_COLOR}Hint: Press ${N2_COLOR}'Ctrl+t'${N1_COLOR} to see last logfile line for active task${N0_COLOR}" 1>&2
+	echo "${N1_COLOR}Hint: Press ${N2_COLOR}'Ctrl+t'${N1_COLOR} to see last logfile line for active task${N0_COLOR}" 1>&2
 	task_id=
 	task_id_cur=
 	# spawn command for all jail
@@ -279,21 +257,12 @@ pkg_multi_init()
 
 # MAIN for multiple jails
 if [ -n "${jail_list}" ]; then
-	# multiple jailsastart always non interactive
+	# multiple jails always non interactive
 	if [ -n "${jail_list}" ]; then
 		JLIST="${jail_list}"
 	fi
 
-	_args=
-
-	# trim for jname= in "$*"
-	for i in ${CIX_OTHER_ARGS}; do
-		if [ -n "${_args}" ]; then
-			_args="${_args} ${i}"
-		else
-			_args="${i}"
-		fi
-	done
+	_args="${CIX_OTHER_ARGS}"
 
 	case "${mode}" in
 		clean)
@@ -377,20 +346,11 @@ if [ -n "${jname}" ]; then
 	fi
 
 	PKG_PRE="${CHROOT_EXEC}"
-	shift
 else
 	path=
 fi
 
-# trim special args
-_args=
-for i in ${CIX_OTHER_ARGS}; do
-	if [ -n "${_args}" ]; then
-		_args="${_args} ${i}"
-	else
-		_args="${i}"
-	fi
-done
+_args="${CIX_OTHER_ARGS}"
 
 if [ -n "${pkglist}" ]; then
 	[ ! -s "${pkglist}" ] && err 1 "${N1_COLOR}No such file or file is empty: ${N2_COLOR}${pkglist}${N0_COLOR}"
diff --git a/qemuctl/qget b/qemuctl/qget
--- a/qemuctl/qget
+++ b/qemuctl/qget
@@ -1,30 +1,8 @@
 #!/usr/bin/env cbsd
-#v12.1.5
+#v12.1.6
 CBSDMODULE="qemu"
-MYARG="jname"
-ADDHELP="
-${H3_COLOR}Description${N0_COLOR}:
-
-Retrieve QEMU VM parameters value. If no arguments are specified,
-all parameters will be displayed.
-
-${H3_COLOR}Options${N0_COLOR}:
-
- ${N2_COLOR}mode=${N0_COLOR}    - when set to 'quiet' - return value only.
- ${N2_COLOR}<params>${N0_COLOR}  - return value for <params>.
-
-${H3_COLOR}Examples${N0_COLOR}:
-
- # cbsd qget jname=vm1
- # cbsd qget jname=vm1 mode=quiet vm_cpus vm_ram vm_os_profile
-
-${H3_COLOR}See also${N0_COLOR}:
-
-  cbsd qset --help
-  cbsd qconfig --help
-  https://github.com/cbsd/cbsd/blob/develop/share/docs/general/tag_n_facts.md
-
-"
+CIXARG=""
+MYDESC="Get info related to qemu domain"
 
 jname=
 ojname=
@@ -38,8 +16,8 @@ ojname=
 MYCOL="${MYCOL} gid"		# gid located in global SQLite3
 ALL_ARGS="${MYCOL}"
 
-MYOPTARG="${MYCOL} mode"
-MYDESC="Get info related to qemu domain"
+CIXOPTARG="jname ${MYCOL} mode"
+
 ADDHELP="
 ${H3_COLOR}Description${N0_COLOR}:
 
@@ -63,8 +41,7 @@ ${H3_COLOR}See also${N0_COLOR}:
 
 "
 
-cloud_api=0
-. ${cbsdinit}
+cixinit
 
 if [ -n "${jname}" ]; then
 	# inherit jname env
@@ -74,7 +51,7 @@ fi
 # check for cloud function when CBSDfile exist
 Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" ]; then
-	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}" 1>&2
+	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}" 1>&2
 	. ${Makefile}
 	all_qemu_list=$( ${GREP_CMD} -E '^qemu_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#qemu_##g )
 
@@ -101,26 +78,28 @@ fi
 
 # only ip4_addr value supported
 if [ ${cbsd_api} -eq 1 ]; then
-	CURL_CMD=$( which curl )
+	capture CURL_CMD which curl
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
-	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
-	_cid=$( ${miscdir}/cbsd_md5 "${CLOUD_KEY}" )
+	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
+	capture _cid ${miscdir}/cbsd_md5 "${CLOUD_KEY}"
 	for _jname in ${all_qemu_list}; do
 		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${_jname} 2>&1 )
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl status error: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+			echo "${N1_COLOR}${CIX_APP} error: curl status error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
 			continue
 		fi
-		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh}" )
-		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
-			continue
-		fi
-		_ssh_len=$( strlen "${_ssh}" )
-		_ssh_post=$( substr --pos=5 --len=${_ssh_len} --str="${_ssh}" )
+		case "${_ssh}" in
+			ssh\ *)
+				_ssh_post=${_ssh#ssh }
+				;;
+			*)
+				echo "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${_jname}"
+				continue
+				;;
+		esac
 		_ip=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $1}' | ${TR_CMD} "@" " " | ${AWK_CMD} '{printf $2}' )
 		[ -z "${_ip}" ] && exit 1
 		echo "${_ip}"
@@ -131,14 +110,11 @@ fi
 [ -n "${ojname}" ] && jname="${ojname}"
 [ -z "${jname}" ] && err 1 "Give me jname"
 
-# push orig MYCOL
 OMYCOL="${MYCOL}"
 
 . ${subrdir}/rcconf.subr
 
 if [ $? -eq 1 ]; then
-	#
-	# try_remote, todo
 	sqlfile_sysdir="${tmpdir}/${1}"
 	err 1 "${N1_COLOR}No such qemu: ${N2_COLOR}${jname}${N0_COLOR}"
 else
@@ -151,16 +127,13 @@ else
 	QUIET=0
 fi
 
-ARGS=				# known args ( MYCOL)
-UNKNOWN_ARGS=			# unknown args ( external/custom ? )
+ARGS=
+UNKNOWN_ARGS=
 
-# exclude jname= and mode= params from args str
 for i in $*; do
-	prefix3=$( substr --pos=0 --len=3 --str=${i} )
-	prefix5=$( substr --pos=0 --len=5 --str=${i} )
-	prefix6=$( substr --pos=0 --len=6 --str=${i} )
-	[ "${prefix5}" = "mode=" ] && continue
-	[ "${prefix6}" = "jname=" ] && continue
+	case "${i%%=*}" in
+		mode|jname) continue ;;
+	esac
 
 	is_known_args=0
 
@@ -183,16 +156,15 @@ done
 for OID in ${ARGS}; do
 	case "${OID}" in
 		vnc)
-			_vnc_port=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vnc_port FROM settings LIMIT 1" )
-			_qemu_vnc_tcp_bind=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT qemu_vnc_tcp_bind FROM settings LIMIT 1" )
+			capture _vnc_port cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT vnc_port FROM settings LIMIT 1"
+			capture _qemu_vnc_tcp_bind cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT qemu_vnc_tcp_bind FROM settings LIMIT 1"
 			val="${_qemu_vnc_tcp_bind}:${_vnc_port}"
 			;;
 		gid)
-			# gid is global env ID, located in global/index database
-			val=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT gid FROM jails WHERE jname=\"${jname}\"" )
+			capture val cbsdsqlro ${dbdir}/local.sqlite "SELECT gid FROM jails WHERE jname=\"${jname}\""
 			;;
 		*)
-			val=$( cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT ${OID} FROM settings LIMIT 1" )
+			capture val cbsdsqlro ${sqlfile_sysdir}/${jname}/local.sqlite "SELECT ${OID} FROM settings LIMIT 1"
 			;;
 	esac
 
diff --git a/qemuctl/qlogin b/qemuctl/qlogin
--- a/qemuctl/qlogin
+++ b/qemuctl/qlogin
@@ -1,9 +1,8 @@
 #!/usr/bin/env cbsd
-#v13.0.1
-globalconf="${CIX_DISTDIR}/cbsd.conf";
-MYARG=""
-MYOPTARG="jname remote inter"
-MYDESC="Exec login into jail"
+#v13.0.2
+CIXARG=""
+CIXOPTARG="jname remote inter"
+MYDESC="Exec login into QEMU domain"
 ADDHELP="\
   If you are in the CBSDfile directory, these environments will always have priority\n\
 "
@@ -13,8 +12,7 @@ CBSDMODULE="qemu"
 . ${subrdir}/nc.subr
 . ${strings}
 . ${tools}
-cbsd_api=0
-. ${cbsdinit}
+cixinit
 
 try_remote()
 {
@@ -36,7 +34,7 @@ try_remote()
 
 	case "${login_cmd}" in
 		internal)
-			${ECHO} "${N1_COLOR}Exec qlogin internal on remote node: ${N2_COLOR}${RHST}${N0_COLOR}"
+			echo "${N1_COLOR}Exec qlogin internal on remote node: ${N2_COLOR}${RHST}${N0_COLOR}"
 			cbsdlogger NOTICE ${CIX_APP}: executing internal qlogin: rexe node=${RHST} /usr/local/bin/cbsd qlogin src_session=${nodename} jname=${jname} remote=1
 			rexe node=${RHST} /usr/local/bin/cbsd qlogin src_session=${nodename} jname=${jname} remote=1
 			;;
@@ -63,7 +61,7 @@ login_internal()
 	if [ "${vm_efi}" != "none" ]; then
 		if [ -f "${jailsysdir}/${jname}/vnc_port" ]; then
 			echo " *** VM booted in VNC mode. ***"
-			${ECHO} "${N1_COLOR}For attach VM console, use: ${N2_COLOR}vncviewer ${qemu_vnc_tcp_ipconnect}:${vm_port}${N0_COLOR}"
+			echo "${N1_COLOR}For attach VM console, use: ${N2_COLOR}vncviewer ${qemu_vnc_tcp_ipconnect}:${vm_port}${N0_COLOR}"
 			if ! getyesno "Do you want to attach into UEFI console anyway?"; then
 				exit 0
 			fi
@@ -91,7 +89,7 @@ login_custom()
 	# re-read custom
 	readconf qlogin.conf > /dev/null 2>&1
 
-	${ECHO} "${N1_COLOR}Custom login command: ${N2_COLOR}${login_cmd}${N0_COLOR}"
+	echo "${N1_COLOR}Custom login command: ${N2_COLOR}${login_cmd}${N0_COLOR}"
 	exec /bin/sh -c "${login_cmd}"
 	# restore CBSD PATH
 	export PATH="${CBSDPATH}"
@@ -136,7 +134,7 @@ jname_qlogin()
 # check for cloud function when CBSDfile exist
 Makefile="${CIX_PWD}/CBSDfile"
 if [ -r "${Makefile}" ]; then
-	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
+	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}found CBSDfile: ${N2_COLOR}${Makefile}${N0_COLOR}"
 	. ${Makefile}
 
 	all_qemu_list=$( ${GREP_CMD} -E '^qemu_[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*\(\)$' ${Makefile} | ${XARGS_CMD} | ${TR_CMD} -d "()" | ${SED_CMD} s#qemu_##g )
@@ -169,12 +167,12 @@ if [ -r "${Makefile}" ]; then
 			jname=
 			select_jail_by_list -s "List of online jails limited by CBSDfile scope [${all_qemu_list}]:" -l "${all_qemu_list}" -r 0 -e qls
 			if [ -n "${jname}" ]; then
-				${ECHO} "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+				echo "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
 				jname_qlogin
 			fi
 		else
 			jname="${all_qemu_list}"
-			${ECHO} "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+			echo "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
 			jname_qlogin
 		fi
 		exit 0
@@ -184,59 +182,54 @@ else
 fi
 
 if [ ${cbsd_api} -eq 1 ]; then
-	CURL_CMD=$( which curl )
+	capture CURL_CMD which curl
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
-	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
-	_cid=$( ${miscdir}/cbsd_md5 "${CLOUD_KEY}" )
+	[ -z "${CBSDFILE_RECURSIVE}" ] && echo "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
+	capture _cid ${miscdir}/cbsd_md5 "${CLOUD_KEY}"
 
 	for jname in ${all_qemu_list}; do
-		[ -z "${jname}" ] && return 1
+		[ -z "${jname}" ] && continue
 		_ssh=$( ${CURL_CMD} --no-progress-meter -H "cid:${_cid}" ${CLOUD_URL}/api/v1/status/${jname} 2>&1 )
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
+			echo "${N1_COLOR}${CIX_APP} error: curl error: ${N2_COLOR}${_ssh}${N0_COLOR}"
+			echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
 			continue
 		fi
 		_ssh_string=$( echo "${_ssh}" | ${JQ_CMD} '.ssh_string' | ${TR_CMD} -d '"' )
-		_ssh_pref=$( substr --pos=0 --len=3 --str="${_ssh_string}" )
-
-		if [ "${_ssh_pref}" != "ssh" ]; then
-			${ECHO} "${N1_COLOR}${CIX_APP} error: curl error2: ${N2_COLOR}${_ssh}${N0_COLOR}"
-			${ECHO} "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
-			continue
-		fi
-
-		_ssh_len=$( strlen "${_ssh_string}" )
-		_ssh_post=$( substr --pos=5 --len=${_ssh_len} --str="${_ssh_string}" )
-		#echo "${SSH_CMD} ${_ssh_post}"
+		case "${_ssh_string}" in
+			ssh\ *)
+				_ssh_post=${_ssh_string#ssh }
+				;;
+			*)
+				echo "${N1_COLOR}${CIX_APP} error: curl error2: ${N2_COLOR}${_ssh}${N0_COLOR}"
+				echo "${CURL_CMD} --no-progress-meter -H \"cid:XXXXX\" ${CLOUD_URL}/api/v1/status/${jname}"
+				continue
+				;;
+		esac
 		_ssh_ip=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $1}' )
 		_ssh_port=$( echo ${_ssh_post} | ${AWK_CMD} '{printf $2}' | ${TR_CMD} -d '\-p' )
 
-		# rewrite
 		if [ -n "${SUDO_USER}" ]; then
 			if [ -r /home/${SUDO_USER}/.ssh/id_ed25519 ]; then
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_ed25519"
 			elif [ -r /home/${SUDO_USER}/.ssh/id_rsa ]; then
 				_ssh_sudo_arg="-oIdentityFile=/home/${SUDO_USER}/.ssh/id_rsa"
-			else
-				date
 			fi
 		fi
 		jexec_cmd="${SSH_CMD} -tt -oStrictHostKeyChecking=no -oConnectTimeout=5 -oServerAliveInterval=10 ${_ssh_sudo_arg} ${_ssh_post}"
-		echo "[debug] exec: $jexec_cmd"
 		${jexec_cmd}
 	done
 	exit 0
 fi
 
-emulator="qemu"	# for jname_is_multiple
-jname_is_multiple	# import jail_list if jname is mask
+emulator="qemu"
+jname_is_multiple
 
 if [ -n "${jail_list}" ]; then
-	${ECHO} "${N1_COLOR}Found domains by mask: ${N2_COLOR}${jail_list}${N0_COLOR}"
+	echo "${N1_COLOR}Found domains by mask: ${N2_COLOR}${jail_list}${N0_COLOR}"
 	for jname in ${jail_list}; do
-		${ECHO} "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}"
+		echo "${N1_COLOR}exec qlogin to: ${N2_COLOR}${jname}${N0_COLOR}"
 		qlogin jname=${jname}
 	done
 	exit 0
diff --git a/qemuctl/qls b/qemuctl/qls
--- a/qemuctl/qls
+++ b/qemuctl/qls
@@ -7,7 +7,7 @@ MYDESC="List QEMU domain and status"
 ADDHELP="
 ${H3_COLOR}Description${N0_COLOR}:
 
-Print list of bhyve VMs including remote domains.
+Print list of QEMU VMs including remote domains.
 
 ${H3_COLOR}Options${N0_COLOR}:
 
@@ -25,7 +25,7 @@ ${H3_COLOR}Options${N0_COLOR}:
                  'nodename,jname,jid,vm_ram,vm_cpus,vm_os_type,ip4_addr,status,vnc';
                additional field:
                  'path'
-             Notes: 'vnc' data column is meta info from: 'bhyve_vnc_tcp_bind':'vnc_port'.
+             Notes: 'vnc' data column is meta info from: 'qemu_vnc_tcp_bind':'vnc_port'.
  ${N2_COLOR}header=${N0_COLOR}   - when set to 0 - don't print header.
  ${N2_COLOR}hidden=${N0_COLOR}   - show hidden env as well? 1 (default) - show, 0 - skip.
  ${N2_COLOR}node=${N0_COLOR}     - only for current node.
@@ -76,7 +76,7 @@ fi
 
 # restore manual settings
 [ -n "${oalljails}" ] && alljails="${oalljails}"
-[ -n "${oshownode}" ] && alljails="${oshownode}"
+[ -n "${oshownode}" ] && shownode="${oshownode}"
 [ -n "${ohidden}" ] && hidden="${ohidden}"
 
 # defaults
@@ -143,7 +143,7 @@ conv_status()
 show_header()
 {
 	local _header="${H1_COLOR}${BOLD}${myheader}${N0_COLOR}"
-	[ ${header} -eq 1 ] && ${ECHO} ${_header}
+	[ ${header} -eq 1 ] && echo ${_header}
 }
 
 # $1 - pid
@@ -239,13 +239,6 @@ populate_output_data()
 		eval _val=\$$_i
 		[ -z "${_val}" ] && _val="0"
 
-		# todo: remote sql fetch via retrinv
-		#if [ "${sqlfile}" != "local" ]; then
-		#	[ "${_i}" != "jname" ] && _val="x"
-		#	printf "${_val} "
-		#	continue
-		#fi
-
 		# search for custom column output helper first
 		if [ -x "${jailsysdir}/${jname}/facts.d/${_i}" ]; then
 			. ${subrdir}/jcreate.subr               # for export_jail_data_for_external_hook
@@ -256,7 +249,7 @@ populate_output_data()
 			case "${_i}" in
 				vm_ram)
 					# convert to MB
-					if ! is_number "${_val}"; then
+					if is_number "${_val}"; then
 						_val=$(( _val / 1024 / 1024 ))
 					else
 						_val="0"
@@ -265,7 +258,7 @@ populate_output_data()
 				vm_curmem)
 					# convert to MB
 					if [ "${_pid}" != "0" ]; then
-						if ! is_number "${memoryuse}"; then
+						if is_number "${memoryuse}"; then
 							_val=$(( memoryuse / 1024 / 1024 ))
 						else
 							_val=0
@@ -277,7 +270,7 @@ populate_output_data()
 					;;
 				pcpu)
 					if [ "${_pid}" != "0" ]; then
-						if ! is_number "${pcpu}"; then
+						if is_number "${pcpu}"; then
 							_val="${pcpu}"
 						else
 							_val=0
@@ -396,7 +389,7 @@ show_jaildata_from_sql()
 		[ ${hidden} -eq 1 -a ${show_hidden} -eq 0 ] && continue
 		if [ ! -r ${sqlfile_sysdir}/${jname}/local.sqlite ]; then
 			# skip invalid vms
-			${ECHO} "${N1_COLOR}Can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}" >> ${my_err_file}
+			echo "${N1_COLOR}Can't open database file for ${jname}: ${N2_COLOR}${sqlfile_sysdir}/${jname}/local.sqlite${N0_COLOR}" >> ${my_err_file}
 			continue
 		fi
 
@@ -434,7 +427,7 @@ show_local()
 		[ "${emulator}" != "qemu" ] && continue
 		[ -z "${jname}" ] && continue
 		populate_output_data -u 1 -j ${jname}
-		${ECHO} ${_status}
+		echo ${_status}
 	done
 }
 
@@ -479,7 +472,7 @@ my_err_file="${ftmpdir}/ls.$$"
 show_jails | ${COLUMN_CMD} -t
 
 if [ -r ${my_err_file} ]; then
-	${ECHO} "${N1_COLOR}Error:${N0_COLOR}" 1>&2
+	echo "${N1_COLOR}Error:${N0_COLOR}" 1>&2
 	${CAT_CMD} ${my_err_file} 1>&2
 	${RM_CMD} -f ${my_err_file}
 fi
diff --git a/sudoexec/bcreate b/sudoexec/bcreate
--- a/sudoexec/bcreate
+++ b/sudoexec/bcreate
@@ -247,7 +247,6 @@ really_create_vm()
 
 	# do not create disk
 	[ "${imgtype}" = "none" ] && return 0
-	#_res=$( substr --pos=0 --len=5 --str=${imgtype} )
 	capture _res substr --pos=0 --len=5 --str="${imgtype}"
 	if [ "${_res}" = "/dev/" ]; then
 		cbsdlogger NOTICE ${CIX_APP}: bcreate for ${jname}: imgtype = raw: ${imgtype}
@@ -284,14 +283,14 @@ really_create_vm()
 			1)
 				. ${subrdir}/zfs.subr
 				zfsmnt ${data}
-				[ $? -eq 2 ] && ${ZFS_CMD} mount "${ZPOOL}"
+				_ret=$?
+				[ ${_ret} -eq 2 ] && ${ZFS_CMD} mount "${ZPOOL}"
 				;;
 		esac
 
 		updateconf ${jconf_tmp} ver="${ver}"
 		${MV_CMD} /tmp/${jname}.$$.img ${data}/${defdsk}
 	else
-		#_msg=$( virtual_create_dsk -p ${data}/${defdsk} -s ${imgsize} -f 1 -t ${imgtype} 2>&1 )
 		capture _msg virtual_create_dsk -p ${data}/${defdsk} -s ${imgsize} -f 1 -t ${imgtype}
 		_res=$?
 		if [ ${_res} -ne 0 ]; then
@@ -303,63 +302,59 @@ really_create_vm()
 
 apply_flavor()
 {
-	unset oimgsize imgsize ovm_ram vm_ram ovm_cpus vm_cpus
-	capture flavors_available cbsdsqlro ${dbdir}/local.sqlite "SELECT name FROM vmpackages ORDER BY name"
-	flavor_exist=0
-	for i in ${flavors_available}; do
-		[ "${flavor}" = "${i}" ] && flavor_exist=1 && break
+	local _flavors_available= _flavor_exist= _i _res= _ovm_cpus= _ovm_ram= _oimgsize=
+
+	unset imgsize vm_ram vm_cpus
+	capture _flavors_available cbsdsqlro ${dbdir}/local.sqlite "SELECT name FROM vmpackages ORDER BY name"
+	_flavor_exist=0
+	for _i in ${_flavors_available}; do
+		[ "${flavor}" = "${_i}" ] && _flavor_exist=1 && break
 	done
 
-	[ ${flavor_exist} -eq 0 ] && log_err 1 "${N1_COLOR}${CIX_APP}: no such flavor [${flavor}], available flavors: ${N2_COLOR}${flavors_available}${N0_COLOR}"
+	[ ${_flavor_exist} -eq 0 ] && log_err 1 "${N1_COLOR}${CIX_APP}: no such flavor [${flavor}], available flavors: ${N2_COLOR}${_flavors_available}${N0_COLOR}"
 
 	capture _res cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name='${flavor}' LIMIT 1"
- 
+
 	[ -z "${_res}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get vm_cpus/vm_ram/imgsize for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
 	sqllistdelimer="|"
-	sqllist "${_res}" ovm_cpus ovm_ram oimgsize
+	sqllist "${_res}" _ovm_cpus _ovm_ram _oimgsize
 	unset sqllistdelimer
 	${ECHO} "${N1_COLOR}${CIX_APP}: flavor ${flavor} -> vm_cpus/vm_ram/imgsize: ${N2_COLOR}[${_res}]${N0_COLOR}"
 
-	[ -z "${ovm_ram}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get 'vm_ram' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
-	[ -z "${oimgsize}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get 'imgsize' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
-	[ -z "${ovm_cpus}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get 'vm_cpus' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+	[ -z "${_ovm_ram}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get 'vm_ram' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+	[ -z "${_oimgsize}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get 'imgsize' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+	[ -z "${_ovm_cpus}" ] && log_err 1 "${N1_COLOR}${CIX_APP}: unable to get 'vm_cpus' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
 
-	vm_ram="${ovm_ram}"
-	imgsize="${oimgsize}"
-	vm_cpus="${ovm_cpus}"
-
-	unset flavor oflavor flavor_exist flavors_available _res
+	vm_ram="${_ovm_ram}"
+	imgsize="${_oimgsize}"
+	vm_cpus="${_ovm_cpus}"
 }
 
 imgsize_validate()
 {
-	# imgsize validate
+	local _imgsize_min_bytes= _imgsize_min_human_mb= _imgsize_bytes= _imgsize_human_mb=
+
 	if [ -n "${imgsize_min}" -a -n "${imgsize}" ]; then
 		if is_number "${imgsize_min}"; then
-			imgsize_min_bytes="${imgsize_min}"
+			_imgsize_min_bytes="${imgsize_min}"
 		else
-			capture imgsize_min_bytes ${miscdir}/conv2human "${imgsize_min}"
+			capture _imgsize_min_bytes ${miscdir}/conv2human "${imgsize_min}"
 		fi
 
-		[ -z "${imgsize_min_bytes}" -o "${imgsize_min_bytes}" = "0" ] && err 1 "${N1_COLOR}${CIX_APP}: unable to convert imgsize to bytes: ${N2_COLOR}${imgsize_min}${N0_COLOR}"
+		[ -z "${_imgsize_min_bytes}" -o "${_imgsize_min_bytes}" = "0" ] && err 1 "${N1_COLOR}${CIX_APP}: unable to convert imgsize to bytes: ${N2_COLOR}${imgsize_min}${N0_COLOR}"
 
-		imgsize_min_human_mb=$(( imgsize_min_bytes / 1024 / 1024 ))
+		_imgsize_min_human_mb=$(( _imgsize_min_bytes / 1024 / 1024 ))
 
 		if is_number "${imgsize}"; then
-			imgsize_bytes="${imgsize}"
+			_imgsize_bytes="${imgsize}"
 		else
-			capture imgsize_bytes ${miscdir}/conv2human "${imgsize}"
+			capture _imgsize_bytes ${miscdir}/conv2human "${imgsize}"
 		fi
 
-		imgsize_human_mb=$(( imgsize_bytes / 1024 / 1024 ))
+		_imgsize_human_mb=$(( _imgsize_bytes / 1024 / 1024 ))
 
-		if [ ${imgsize_bytes} -lt ${imgsize_min_bytes} ]; then
-			# not fatal?
-	#		if [ "${zfsfeat}" = "1" ]; then
-	#			${ZFS_CMD} destroy ${DATA}/${jname}
-	#		fi
-	#		err 1 "${N1_COLOR}imgsize too small: ${N2_COLOR}${imgsize_bytes} ( ${imgsize_human_mb}mb ) < ${imgsize_min_bytes} ( ${imgsize_min_human_mb}mb )${N0_COLOR}"
-			${ECHO} "${W1_COLOR}imgsize too small: ${N2_COLOR}${imgsize_bytes} ( ${imgsize_human_mb}mb ) < ${imgsize_min_bytes} ( ${imgsize_min_human_mb}mb )${N0_COLOR}"
+		if [ ${_imgsize_bytes} -lt ${_imgsize_min_bytes} ]; then
+			${ECHO} "${W1_COLOR}imgsize too small: ${N2_COLOR}${_imgsize_bytes} ( ${_imgsize_human_mb}mb ) < ${_imgsize_min_bytes} ( ${_imgsize_min_human_mb}mb )${N0_COLOR}"
 		fi
 	fi
 }
@@ -367,28 +362,30 @@ imgsize_validate()
 # vm_ram validate
 vm_ram_validate()
 {
+	local _vm_ram_min_bytes= _vm_ram_min_human_mb= _vm_ram_bytes= _vm_ram_human_mb=
+
 	if [ -n "${vm_ram_min}" -a -n "${vm_ram}" ]; then
 		if is_number "${vm_ram_min}"; then
-			vm_ram_min_bytes="${vm_ram_min}"
+			_vm_ram_min_bytes="${vm_ram_min}"
 		else
-			capture vm_ram_min_bytes ${miscdir}/conv2human "${vm_ram_min}"
+			capture _vm_ram_min_bytes ${miscdir}/conv2human "${vm_ram_min}"
 		fi
 
-		vm_ram_min_human_mb=$(( vm_ram_min_bytes / 1024 / 1024 ))
+		_vm_ram_min_human_mb=$(( _vm_ram_min_bytes / 1024 / 1024 ))
 
 		if is_number "${vm_ram}"; then
-			vm_ram_bytes="${vm_ram}"
+			_vm_ram_bytes="${vm_ram}"
 		else
-			capture vm_ram_bytes ${miscdir}/conv2human "${vm_ram}"
+			capture _vm_ram_bytes ${miscdir}/conv2human "${vm_ram}"
 		fi
 
-		vm_ram_human_mb=$(( vm_ram_bytes / 1024 / 1024 ))
+		_vm_ram_human_mb=$(( _vm_ram_bytes / 1024 / 1024 ))
 
-		if [ ${vm_ram_bytes} -lt ${vm_ram_min_bytes} ]; then
+		if [ ${_vm_ram_bytes} -lt ${_vm_ram_min_bytes} ]; then
 			if [ "${zfsfeat}" = "1" ]; then
 				${ZFS_CMD} destroy ${DATA}/${jname}
 			fi
-			err 1 "${N1_COLOR}vm_ram too small: ${N2_COLOR}${vm_ram_bytes} ( ${vm_ram_human_mb}mb ) < ${vm_ram_min_bytes} ( ${vm_ram_min_human_mb}mb )${N0_COLOR}"
+			err 1 "${N1_COLOR}vm_ram too small: ${N2_COLOR}${_vm_ram_bytes} ( ${_vm_ram_human_mb}mb ) < ${_vm_ram_min_bytes} ( ${_vm_ram_min_human_mb}mb )${N0_COLOR}"
 		fi
 	fi
 }
@@ -411,14 +408,13 @@ copy_vars()
 
 set_rctl()
 {
-	# RCTL
+	local _val= _i=
 	. ${distsharedir}/rctl.conf
-	for i in ${RCTL} ${RCTL_EXTRA}; do
-	        _val=
-		eval _val="\$rctl_${i}"
+	for _i in ${RCTL} ${RCTL_EXTRA}; do
+		_val=
+		eval _val="\$rctl_${_i}"
 		[ -z "${_val}" ] && continue
-		#echo "INIT RCTL: jrctl jname=${jname} mode=set ${i}=${_val}"
-		${miscdir}/daemonize ${jailctldir}/jrctl jname=${jname} mode=set ${i}=${_val} > /dev/null 2>&1
+		${miscdir}/daemonize ${jailctldir}/jrctl jname=${jname} mode=set ${_i}=${_val} > /dev/null 2>&1
 	done
 }
 
@@ -597,7 +593,6 @@ if [ "${zfsfeat}" = "1" -a "${mnt_start}" = "0" ]; then
 	[ -z "${data}" ] && data="${jaildatadir}/${jname}-${jaildatapref}"
 	olddata="${data}"
 	data="${workdir}/vm/${jname}"
-	#updateconf ${temprcconf} data="${data}"
 	SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} data=\"${data}\""
 	${LN_CMD} -sf ${data} ${olddata}
 	${LN_CMD} -sf ${data} ${jailsysdir}/${jname}
@@ -744,7 +739,6 @@ if [ -n "${lpc_temp_sql}" ]; then
 	# dump and import lpc table
 	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CIX_APP}: import lpc data from: ${N2_COLOR}${lpc_temp_sql} ${N1_COLOR}via${N2_COLOR} ${_tmp_table_file}${N1_COLOR} dump${N0_COLOR}"
 	# skip CREATE TABLE lpc: lpc already exist
-	#${SQLITE_CMD} "${lpc_temp_sql}" .dump | ${SQLITE_CMD} "${jailsysdir}/${jname}/local.sqlite"
 	cbsdsqlrw "${jailsysdir}/${jname}/local.sqlite" "DELETE FROM lpc"
 	${SQLITE3_CMD} "${lpc_temp_sql}" ".mode insert lpc" "SELECT * FROM lpc;" | ${SQLITE3_CMD} "${jailsysdir}/${jname}/local.sqlite"
 	${RM_CMD} -f ${lpc_temp_sql} ${lpc_temp_sql}-shm ${lpc_temp_sql}-wal
@@ -779,15 +773,11 @@ SYSRC_TEMPRCCONF=
 echo 1>&2
 if [ "${vm_zfs_guid}" != "0" ]; then
 	[ -z "${NOINTER}" ] && ${ECHO} "${N1_COLOR}Global VM ZFS guid: ${N2_COLOR}${vm_zfs_guid}${N0_COLOR}" 1>&2
-	#cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE settings SET vm_zfs_guid='${vm_zfs_guid}'"
 	SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE settings SET vm_zfs_guid='${vm_zfs_guid}'"
 fi
 if [ "${uuid}" = "0" ]; then
 	capture uuid ${UUIDGEN_CMD}
-	#[ -z "${NOINTER}" ] && ${ECHO} "${N1_COLOR}Global VM UUID: ${N2_COLOR}${uuid}${N0_COLOR}"
-	#cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE settings SET uuid='${uuid}'"
 	SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE settings SET uuid='${uuid}'"
-	#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} uuid="${uuid}"
 	SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} uuid=\"${uuid}\""
 fi
 
@@ -850,73 +840,39 @@ case "${imgtype}" in
 			#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "INSERT INTO bhyvedsk ( jname,dsk_controller,dsk_path,dsk_slot,dsk_size,dsk_sectorsize,dsk_zfs_guid ) VALUES ( '${jname}','${virtio_type}','${defdsk}','0','${dsk_bsize}','${sectorsize}', '${dsk_zfs_guid}' )"
 			SQLITE_LOCAL="${SQLITE_LOCAL}; INSERT INTO bhyvedsk ( jname,dsk_controller,dsk_path,dsk_slot,dsk_size,dsk_sectorsize,dsk_zfs_guid ) VALUES ( '${jname}','${virtio_type}','${defdsk}','0','${dsk_bsize}','${sectorsize}', '${dsk_zfs_guid}' )"
 		else
-			#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "INSERT INTO bhyvedsk ( jname,dsk_path,dsk_slot,dsk_size,dsk_sectorsize,dsk_zfs_guid ) VALUES ( '${jname}','${defdsk}','0','${dsk_bsize}','${sectorsize}','${dsk_zfs_guid}' )"
 			SQLITE_LOCAL="${SQLITE_LOCAL}; INSERT INTO bhyvedsk ( jname,dsk_path,dsk_slot,dsk_size,dsk_sectorsize,dsk_zfs_guid ) VALUES ( '${jname}','${defdsk}','0','${dsk_bsize}','${sectorsize}','${dsk_zfs_guid}' )"
 		fi
 
 		# mark the first disk bootable
-		#cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET bootable='true' WHERE dsk_path='${defdsk}'"
 		SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE bhyvedsk SET bootable='true' WHERE dsk_path='${defdsk}'"
 		;;
 esac
 
 if [ -n "${nic_driver}" ]; then
-	#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "INSERT INTO bhyvenic ( jname,nic_driver,nic_parent ) VALUES ( '${jname}', '${nic_driver}', '${interface}' )"
 	SQLITE_LOCAL="${SQLITE_LOCAL}; INSERT INTO bhyvenic ( jname,nic_driver,nic_parent ) VALUES ( '${jname}', '${nic_driver}', '${interface}' )"
 else
-	#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "INSERT INTO bhyvenic ( jname,nic_parent ) VALUES ( '${jname}', '${interface}' )"
 	SQLITE_LOCAL="${SQLITE_LOCAL}; INSERT INTO bhyvenic ( jname,nic_parent ) VALUES ( '${jname}', '${interface}' )"
 fi
 
 if [ -n "${nic_flags}" ]; then
-	#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_flags='${nic_flags}' WHERE nic_parent='${interface}'"
 	SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE bhyvenic SET nic_flags='${nic_flags}' WHERE nic_parent='${interface}'"
-	#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} nic_flags="${nic_flags}"
 	SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} nic_flags=\"${nic_flags}\""
 fi
 
 if [ -n "${interface2}" -a "${interface2}" != "0" ]; then
-	#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "INSERT INTO bhyvenic ( jname,nic_parent ) VALUES ( '${jname}', '${interface2}' )"
 	SQLITE_LOCAL="${SQLITE_LOCAL}; INSERT INTO bhyvenic ( jname,nic_parent ) VALUES ( '${jname}', '${interface2}' )"
 	if [ -n "${ci_interface_mtu2}" ]; then
-		#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_mtu='${ci_interface_mtu2}' WHERE nic_parent='${interface2}'"
 		SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE bhyvenic SET nic_mtu='${ci_interface_mtu2}' WHERE nic_parent='${interface2}'"
 	fi
-	#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} interface2="${interface2}"
 	SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} interface2=\"${interface2}\""
 	if [ -n "${nic2_flags}" ]; then
-		#${miscdir}/sqlcli ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_flags='${nic2_flags}' WHERE nic_parent='${interface2}'"
 		SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE bhyvenic SET nic_flags='${nic2_flags}' WHERE nic_parent='${interface2}'"
-		#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} nic_flags="${nic2_flags}"
 		SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} nic_flags=\"${nic2_flags}\""
 	fi
 fi
 
 : "${nic_ratelimit:=0}"
 
-#if [ "${bhyve_have_net_ratelimit}" = "1" ]; then
-#	if [ "${nic_ratelimit}" != "0" ]; then
-#		cbsdlogger NOTICE ${CIX_APP}: bcreate for ${jname}: nic_ratelimit for nic id 1: ${nic_ratelimit}
-#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_ratelimit='${nic_ratelimit}' WHERE id='1'"
-#		updateconf ${jailsysdir}/${jname}/rc.conf_${jname} nic_ratelimit="${nic_ratelimit}"
-#	fi
-#fi
-
-#[ -z "${dsk_iops_limit}" ] && dsk_iops_limit="0"
-#[ -z "${dsk_mbps_limit}" ] && dsk_mbps_limit="0"
-
-#if [ "${bhyve_have_dsk_ratelimit}" = "1" ]; then
-#	if [ "${dsk_iops_limit}" != "0" ]; then
-#		cbsdlogger NOTICE ${CIX_APP}: bcreate for ${jname}: dsk_iops_limit for dsk ${defdsk}: ${dsk_iops_limit}
-#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET dsk_iops_limit='${dsk_iops_limit}' WHERE dsk_path='${defdsk}'"
-#		updateconf ${jailsysdir}/${jname}/rc.conf_${jname} dsk_iops_limit="${dsk_iops_limit}"
-#	fi
-#	if [ "${dsk_mbps_limit}" != "0" ]; then
-#		cbsdlogger NOTICE ${CIX_APP}: bcreate for ${jname}: dsk_mbps_limit for dsk ${defdsk}: ${dsk_mbps_limit}
-#		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvedsk SET dsk_mbps_limit='${dsk_mbps_limit}' WHERE dsk_path='${defdsk}'"
-#		updateconf ${jailsysdir}/${jname}/rc.conf_${jname} dsk_mbps_limit="${dsk_mbps_limit}"
-#	fi
-#fi
 
 # update state_time
 SQLITE_LOCAL="${SQLITE_LOCAL}; UPDATE settings SET state_time=(strftime('%s','now')); UPDATE settings SET created=(strftime('%s','now'))"
@@ -1013,14 +969,12 @@ if [ ${is_cloud} -eq 1 ]; then
 		ci_interface="${interface}"
 		updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_interface="${ci_interface}"
 	fi
-#	[ -z "${ci_jname}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_jname="${jname}"
-#	[ -z "${ci_fqdn}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_fqdn="${host_hostname}"
 
 	[ -z "${ci_jname}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_jname=\"${jname}\""
 	[ -z "${ci_fqdn}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_fqdn=\"${host_hostname}\""
 
 	if [ -z "${ci_ip4_addr}" ]; then
-		${ECHO} "${W1_COLOR}warning: ${N1_COLOR}cloud-init based profile but ci_ip4_addr not set. Force to: ${N2_COLOR}DHCP${N0_COLOR}" 2>&1
+		${ECHO} "${W1_COLOR}warning: ${N1_COLOR}cloud-init based profile but ci_ip4_addr not set. Force to: ${N2_COLOR}DHCP${N0_COLOR}" 1>&2
 		ci_ip4_addr="DHCP"
 	fi
 	if [ -z "${ci_gw4}" ]; then
@@ -1029,7 +983,7 @@ if [ ${is_cloud} -eq 1 ]; then
 				true
 				;;
 			*)
-				${ECHO} "${W1_COLOR}warning: ${N1_COLOR}cloud-init based profile but ci_gw4 not set. VM without gateway?${N0_COLOR}" 2>&1
+				${ECHO} "${W1_COLOR}warning: ${N1_COLOR}cloud-init based profile but ci_gw4 not set. VM without gateway?${N0_COLOR}" 1>&2
 				;;
 		esac
 	fi
@@ -1056,7 +1010,7 @@ if [ ${is_cloud} -eq 1 ]; then
 				_mod=1
 				;;
 			[Dd][Hh][Cc][Pp][vV]6)
-				capture dhcpdv6
+				capture _pureip dhcpdv6
 				if [ $? -eq 2 ]; then
 					cbsdlogger NOTICE ${CIX_APP}: no free IP address for DHCPv6 in nodeip6pool
 					err 1 "${N1_COLOR}${CIX_APP}: no free IP address for DHCPv6 in nodeip6pool${N0_COLOR}"
@@ -1160,13 +1114,10 @@ if [ ${is_cloud} -eq 1 ]; then
 		ip4_addr="${_ip4_addr}"
 		ci_ip4_addr="${normalize_ci_ip4_addr}"
 
-		#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ip4_addr="${ip4_addr}" ci_ip4_addr="${normalize_ci_ip4_addr}"
 		SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ip4_addr=\"${ip4_addr}\" ci_ip4_addr=\"${normalize_ci_ip4_addr}\""
 		bset jname="${jname}" ip4_addr="${_ip4_addr}" ci_ip4_addr="${normalize_ci_ip4_addr}" quiet=1
-		# > /dev/null 2>&1
 	fi
 
-	#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_gw42="${ci_gw42}"
 	[ -n "${ci_gw42}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_gw42=\"${ci_gw42}\""
 
 	if [ -n "${ci_ip4_addr2}" ]; then
@@ -1190,10 +1141,8 @@ if [ ${is_cloud} -eq 1 ]; then
 
 		ip4_addr="${ip4_addr},${_ip4_addr}"
 
-		#updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ip4_addr="${ip4_addr}" ci_ip4_addr2="${ci_ip4_addr2}"
 		SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ip4_addr=\"${ip4_addr}\" ci_ip4_addr2=\"${ci_ip4_addr2}\""
 		bset jname="${jname}" ip4_addr="${ip4_addr}" quiet=1
-		# > /dev/null 2>&1
 		normalize_ip4_addr="${normalize_ip4_addr},${ci_ip4_addr2}"
 	fi
 
@@ -1202,19 +1151,6 @@ if [ ${is_cloud} -eq 1 ]; then
 	[ "${ci_interface2}" = "0" ] && unset ci_interface2
 	[ "${ci_ip4_addr2}" = "0" ] && unset ci_ip4_addr2
 	[ "${ci_gw4}" = "0" ] && unset ci_gw4
-
-	# loop + one shot sysrc
-#	[ -z "${ci_nameserver_address}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_nameserver_address="${default_ci_nameserver_address}"
-#	[ -z "${ci_nameserver_search}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_nameserver_search="${default_ci_nameserver_search}"
-#	[ -z "${ci_interface_name}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_interface_name="${default_ci_interface_name}"
-#	[ -z "${ci_user_pw_user}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_user_pw_user="${ci_user_pw_user}"
-#	[ -z "${ci_user_pw_root}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_user_pw_root="${ci_user_pw_root}"
-#	[ -z "${ci_user_pw_root}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_user_pw_root="${ci_user_pw_root}"
-#	[ -z "${ci_user_pubkey}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_user_pubkey="${ci_user_pubkey}"
-#	[ -z "${ci_user_pubkey2}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_user_pubkey2="${ci_user_pubkey2}"
-#	[ -z "${ci_interface2}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_interface2="${ci_interface2}"
-#	[ -z "${ci_ip4_addr2}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_ip4_addr2="${ci_ip4_addr2}"
-#	[ -z "${ci_gw4}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_gw4=\"${ci_gw4}\""
 
 	[ -z "${ci_nameserver_address}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_nameserver_address=\"${default_ci_nameserver_address}\""
 	[ -z "${ci_nameserver_search}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_nameserver_search=\"${default_ci_nameserver_search}\""
@@ -1237,7 +1173,6 @@ if [ ${is_cloud} -eq 1 ]; then
 		cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite "UPDATE bhyvenic SET nic_hwaddr='${nic_hwaddr0}' WHERE id='1'"
 	fi
 
-#	[ -z "${ci_nic_hwaddr0}" ] && updateconf ${jailsysdir}/${jname}/rc.conf_${jname} ci_nic_hwaddr0="${nic_hwaddr0}"
 	[ -z "${ci_nic_hwaddr0}" ] && SYSRC_TEMPRCCONF="${SYSRC_TEMPRCCONF} ci_nic_hwaddr0=\"${nic_hwaddr0}\""
 
 	case "${vm_os_type}" in
diff --git a/system/baseupdate b/system/baseupdate
--- a/system/baseupdate
+++ b/system/baseupdate
@@ -66,13 +66,13 @@ readconf ${platform}-baseupdate.conf
 
 generate_freebsd_config()
 {
-	local _res=
+	local _res= _i=
 
 	# validate mandatory variables
-	for i in keyprint servername components; do
+	for _i in keyprint servername components; do
 		_res=
-		eval _res="\$$i"
-		[ -z "${_res}" ] && err 1 "${N1_COLOR}baseupdate generate_freebsd_config error: empty variable ${N2_COLOR}${i}${N1_COLOR}. please use ${platform}-baseupdate.conf to setup${N0_COLOR}"
+		eval _res="\$${_i}"
+		[ -z "${_res}" ] && err 1 "${N1_COLOR}baseupdate generate_freebsd_config error: empty variable ${N2_COLOR}${_i}${N1_COLOR}. please use ${platform}-baseupdate.conf to setup${N0_COLOR}"
 	done
 
 	${CAT_CMD} << EOF > "${1}"
@@ -91,7 +91,7 @@ EOF
 
 update_base()
 {
-	local _i= _res= _cmd=
+	local _i= _res= _cmd= _col=
 
 	sqlfile="local"
 	local _mod_count=0
@@ -102,18 +102,21 @@ update_base()
 	# add this as modifiers to narrow down the conditions for an exact result.
 	# for example when ver= specidied, we got: "WHERE ver=X"
 
-	for i in ver arch target_arch; do
+	for _i in ver arch target_arch; do
 		_res=
-		eval _res="\$$i"
+		eval _res="\$${_i}"
 		[ -z "${_res}" ] && continue
+		# map target_arch to targetarch (DB column name)
+		case ${_i} in
+			target_arch) _col=targetarch ;;
+			*) _col=${_i} ;;
+		esac
 		case ${_mod_count} in
 			0)
-				# first modificator
-			_sql="${_sql} WHERE ${i}='${_res}'"
-			;;
-		*)
-			# append modificator, concat with AND
-			_sql="${_sql} AND ${i}='${_res}'"
+				_sql="${_sql} WHERE ${_col}='${_res}'"
+				;;
+			*)
+				_sql="${_sql} AND ${_col}='${_res}'"
 				;;
 		esac
 		_mod_count=$(( _mod_count + 1 ))
@@ -125,35 +128,35 @@ update_base()
 	capture _rows cbsdsqlro ${sqlfile} "${_sql}"
 
 	while read _platform _name _arch _targetarch _ver; do
-		base="${_name}_${_arch}_${_targetarch}_${_ver}"
-		basepath=${workdir}/basejail/${base}
-		if [ ! -r ${basepath}/bin/sh ]; then
-			${ECHO} "${N1_COLOR}No such /bin/sh in: ${N2_COLOR}${basepath}${N1_COLOR}. Bad dir/hier? Skipped${N0_COLOR}"
+		_base="${_name}_${_arch}_${_targetarch}_${_ver}"
+		_basepath=${workdir}/basejail/${_base}
+		if [ ! -r ${_basepath}/bin/sh ]; then
+			${ECHO} "${N1_COLOR}No such /bin/sh in: ${N2_COLOR}${_basepath}${N1_COLOR}. Bad dir/hier? Skipped${N0_COLOR}"
 			continue
 		fi
-		printf "${N1_COLOR}Updating ${basepath}: ${N0_COLOR}"
+		printf "${N1_COLOR}Updating ${_basepath}: ${N0_COLOR}"
 
 		# set fake env
-		set_bsdenv_by_path -p ${basepath} -v ${_ver}
+		set_bsdenv_by_path -p ${_basepath} -v ${_ver}
 		${UNAME_CMD} -v
 		case "${platform}" in
 			HardenedBSD)
 				capture _cmd which hbsd-update
 				[ ! -x "${_cmd}" ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}no such executables in PATH: ${N2_COLOR}hbsd-update${N0_COLOR}"
-				${ECHO} "${N1_COLOR}${_cmd} -n -r \"${N2_COLOR}${basepath}${N1_COLOR}\"${N0_COLOR}"
-				echo "${_cmd} -n -r \"${basepath}\""
-				${_cmd} -n -r "${basepath}"
+				${ECHO} "${N1_COLOR}${_cmd} -n -r \"${N2_COLOR}${_basepath}${N1_COLOR}\"${N0_COLOR}"
+				${ECHO} "${_cmd} -n -r \"${_basepath}\""
+				${_cmd} -n -r "${_basepath}"
 				;;
 			FreeBSD)
 				capture _cmd which freebsd-update
 				[ ! -x "${_cmd}" ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}no such executables in PATH: ${N2_COLOR}freebsd-update${N0_COLOR}"
-				capture tmpconf ${MKTEMP_CMD}
-				trap "${RM_CMD} -f ${tmpconf}" HUP INT ABRT BUS TERM EXIT
-				generate_freebsd_config "${tmpconf}"
-				FBSD_UPDATE="${_cmd} -f ${tmpconf} -b ${basepath} --not-running-from-cron --currently-running ${_ver}-RELEASE"
-				${ECHO} "${N1_COLOR}${FBSD_UPDATE}${N0_COLOR}"
-				echo "${ENV_CMD} PAGER=${CAT_CMD} ${FBSD_UPDATE} fetch install"
-				${ENV_CMD} PAGER=${CAT_CMD} ${FBSD_UPDATE} fetch install
+				capture _tmpconf ${MKTEMP_CMD}
+				trap "${RM_CMD} -f ${_tmpconf}" HUP INT ABRT BUS TERM EXIT
+				generate_freebsd_config "${_tmpconf}"
+				_FBSD_UPDATE="${_cmd} -f ${_tmpconf} -b ${_basepath} --not-running-from-cron --currently-running ${_ver}-RELEASE"
+				${ECHO} "${N1_COLOR}${_FBSD_UPDATE}${N0_COLOR}"
+				${ECHO} "${ENV_CMD} PAGER=${CAT_CMD} ${_FBSD_UPDATE} fetch install"
+				${ENV_CMD} PAGER=${CAT_CMD} ${_FBSD_UPDATE} fetch install
 				;;
 		esac
 
