WIP: volumes support: add sysdir_volume jail params

diff --git a/jailctl/jset b/jailctl/jset
--- a/jailctl/jset
+++ b/jailctl/jset
@@ -923,6 +923,74 @@ modify_mount_linprocfs()
 	esac
 }
 
+# sysdir_volume
+modify_sysdir_volume()
+{
+	local _ver= _dst= _oldval= _src=
+	local _volsysdir= _sysdir=
+
+	#push new variable in tmp stack
+	_oldval="${sysdir_volume}"
+
+	. ${system}
+	. ${subrdir}/rcconf.subr
+
+	#restore new variable
+	sysdir_volume="${_oldval}"
+
+
+	_volsysdir="${workdir}/VOLUMES/${jname}-system"
+	_sysdir="${jailsysdir}/${jname}"
+
+	case "${sysdir_volume}" in
+		0)
+			# move from VOLUMES to default location
+			if [ ! -r "${_volsysdir}/local.sqlite" ]; then
+				${ECHO} "${W1_COLOR}${CIX_APP} error${N1_COLOR}: switch to default location: no source dir: ${N2_COLOR}${_volsysdir}${N0_COLOR}" 1>&2
+				return 1
+			fi
+			[ -h "${_sysdir}" ] && ${RM_CMD} "${_sysdir}"
+			[ ! -d "${_sysdir}" ] && ${MKDIR_CMD} -p "${_sysdir}"
+			${ECHO} "${N1_COLOR}${CIX_APP}: switch to default location: ${N2_COLOR}${_volsysdir} -> ${_sysdir}${N0_COLOR}" 1>&2
+			${RSYNC_CMD} -avz ${_volsysdir}/ ${_sysdir}/
+			# re-check
+			if [ ! -r ${_sysdir}/local.sqlite ]; then
+				${ECHO} "${W1_COLOR}${CIX_APP} error${N1_COLOR}: switch to default location: no local.sqlite: ${N2_COLOR}${_sysdir}/local.sqlite${N0_COLOR}" 1>&2
+				return 1
+			fi
+
+			${RM_CMD} -rf "${_volsysdir}"
+			;;
+		1)
+			# move from default location to VOLUMES
+			if [ ! -r "${_sysdir}/local.sqlite" ]; then
+				${ECHO} "${W1_COLOR}${CIX_APP} error${N1_COLOR}: switch to VOLUME location: no source dir: ${N2_COLOR}${_sysdir}${N0_COLOR}" 1>&2
+				return 1
+			fi
+			[ ! -d "${_volsysdir}" ] && ${MKDIR_CMD} -p ${_volsysdir}
+			${ECHO} "${N1_COLOR}${CIX_APP}: switch to VOLUME location: ${N2_COLOR}${_sysdir} -> ${_volsysdir}${N0_COLOR}" 1>&2
+			${RSYNC_CMD} -avz ${_sysdir}/ ${_volsysdir}/
+
+			# re-check
+			if [ ! -r ${_volsysdir}/local.sqlite ]; then
+				${ECHO} "${W1_COLOR}${CIX_APP} error${N1_COLOR}: switch to VOLUME location: no local.sqlite: ${N2_COLOR}${_volsysdir}/local.sqlite${N0_COLOR}" 1>&2
+				return 1
+			fi
+
+			${RM_CMD} -rf ${_sysdir}
+			${LN_CMD} -sf ${_volsysdir} ${_sysdir}
+			;;
+		*)
+			${ECHO} "${W1_COLOR}${CIX_APP} error${N1_COLOR}: sysdir_volume valid value: 0,1: ${N2_COLOR}${sysdir_volume}${N0_COLOR}" 1>&2
+			return 1
+			;;
+	esac
+
+	cbsdsqlrw local "UPDATE jails SET ${i}='${sysdir_volume}' WHERE jname='${jname}'"
+	${ECHO} "${argpart}: ${N1_COLOR}${sysdir_volume}${N0_COLOR}"
+}
+
+
 need_action()
 {
 	eval VAL="\$$i"
@@ -989,6 +1057,9 @@ update_jails()
 			;;
 		jnameserver)
 			modify_jnameserver
+			;;
+		sysdir_volume)
+			modify_sysdir_volume
 			;;
 	esac
 
@@ -1112,11 +1183,11 @@ for n in ${my_arg}; do
 						cbsdlogger NOTICE ${CIX_APP}: modify_ipaddr for ${jname}
 						modify_ipaddr
 						;;
-					"cpuset")
+					cpuset)
 						cbsdlogger NOTICE ${CIX_APP}: modify_cpuset for ${jname}
 						modify_cpuset
 						;;
-					"nice")
+					nice)
 						cbsdlogger NOTICE ${CIX_APP}: modify_nice for ${jname}
 						modify_nice
 						;;
@@ -1210,6 +1281,10 @@ for n in ${my_arg}; do
 					host_hostname)
 						cbsdlogger NOTICE ${CIX_APP}: modify_host_hostname
 						modify_host_hostname
+						;;
+					sysdir_volume)
+						cbsdlogger NOTICE ${CIX_APP}: modify_sysdir_volume
+						modify_sysdir_volume
 						;;
 					*)
 						if [ ${autorestart} -eq 0 ]; then
