code cleanup & style. move cbsd dir to cbsdsh. Rewrite Makefile: stage 1/2

diff --git a/jailctl/jsnapshot b/jailctl/jsnapshot
--- a/jailctl/jsnapshot
+++ b/jailctl/jsnapshot
@@ -21,227 +21,224 @@ init $*
 
 show_header()
 {
-    local _header="${BOLD}${myheader}${NORMAL}"
-    [ ${header} -ne 0 ] && $ECHO ${_header}
+	local _header="${BOLD}${myheader}${NORMAL}"
+	[ ${header} -ne 0 ] && $ECHO ${_header}
 }
 
 
 check_jname()
 {
-    [ -z "${jname}" ] && err 1 "${MAGENTA}Please set ${GREEN}jname=${NORMAL}"
-    . ${jrcconf}
-    [ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+	[ -z "${jname}" ] && err 1 "${MAGENTA}Please set ${GREEN}jname=${NORMAL}"
+	. ${jrcconf}
+	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
 }
 
 zfs_snapshot_list()
 {
-    local _mod _fs _p1 _jname _createtime _status _snaptime _snapname _used
-    [ -n "${jname}" ] && _mod="${ZPOOL}/${jname}"
+	local _mod _fs _p1 _jname _createtime _status _snaptime _snapname _used
+	[ -n "${jname}" ] && _mod="${ZPOOL}/${jname}"
 
-    show_header
+	show_header
 
-    for _fs in $(/sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null); do
-	_status=""
-	_jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null)
-	[ -z "${_jname}" ] && continue
-	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
-	_snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" 2>/dev/null)
-	[ -z "${_snapname}" ] && continue
-	#populate values for in output string
-	for _i in ${mydisplay}; do
-	    case "${_i}" in
-		"snapname")
-		    _status="${_status}${_snapname} "
-		    ;;
-		"jname")
-		    _status="${_status}${_jname} "
-		    ;;
-		"creation")
-		    _createtime=$(zfs get -H -o value creation "${_fs}" 2>/dev/null)
-		    _snaptime=$( date -j -f "%a %b %d %T %Y" "${_createtime}" "+%Y-%m-%d__%H:%M" )
-		    _status="${_status}${_snaptime} "
-		    ;;
-		"used")
-		    _used=$(zfs get -H -o value used "${_fs}" 2>/dev/null)
-		    _status="${_status}${_used} "
-		    ;;
-
-	    esac
+	for _fs in $( /sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null ); do
+		_status=""
+		_jname=$( /sbin/zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null )
+		[ -z "${_jname}" ] && continue
+		[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
+		_snapname=$( /sbin/zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" 2>/dev/null )
+		[ -z "${_snapname}" ] && continue
+		#populate values for in output string
+		for _i in ${mydisplay}; do
+			case "${_i}" in
+				"snapname")
+					_status="${_status}${_snapname} "
+					;;
+				"jname")
+					_status="${_status}${_jname} "
+					;;
+				"creation")
+					_createtime=$( /sbin/zfs get -H -o value creation "${_fs}" 2>/dev/null )
+					_snaptime=$( date -j -f "%a %b %d %T %Y" "${_createtime}" "+%Y-%m-%d__%H:%M" )
+					_status="${_status}${_snaptime} "
+					;;
+				"used")
+					_used=$( /sbin/zfs get -H -o value used "${_fs}" 2>/dev/null )
+					_status="${_status}${_used} "
+					;;
+			esac
+		done
+		${ECHO} "${NORMAL}${_status}"
 	done
-	${ECHO} "${NORMAL}${_status}"
-    done
 }
 
 zfs_snapshot_destroyall()
 {
-    local _fs _jname _mod _snapname
+	local _fs _jname _mod _snapname
 
-    [ -n "${jname}" ] && _mod="${ZPOOL}/${jname}"
+	[ -n "${jname}" ] && _mod="${ZPOOL}/${jname}"
 
-    for _fs in $(/sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null); do
-	_jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null)
-	[ -z "${_jname}" ] && continue
-	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
-	_snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" 2>/dev/null)
-	[ -z "${_snapname}" ] && continue
-	zfs_snapshot_destroy ${_fs} && ${ECHO} "${MAGENTA}zfs snapshot for ${jname} destoyed: ${GREEN}${_snapname}${NORMAL}"
-    done
+	for _fs in $( /sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null ); do
+		_jname=$( /sbin/zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null )
+		[ -z "${_jname}" ] && continue
+		[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
+		_snapname=$( /sbin/zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" 2>/dev/null )
+		[ -z "${_snapname}" ] && continue
+		zfs_snapshot_destroy ${_fs} && ${ECHO} "${MAGENTA}zfs snapshot for ${jname} destoyed: ${GREEN}${_snapname}${NORMAL}"
+	done
 }
 
 
 zfs_snapshot_destroy_by_snapname()
 {
-    local _fs _jname _mod _snapname _chkloop=0
+	local _fs _jname _mod _snapname _chkloop=0
 
-    [ -z "${snapname}" ] && err 1 "${MAGENTA}Please set ${GREEN}snapname=${MAGENTA} or use ${GREEN}mode=destroyall ${MAGENTA}to destroy all snapshots for this jail${NORMAL}"
-    [ -n "${jname}" ] && _mod="${ZPOOL}/${jname}@${snapname}"
+	[ -z "${snapname}" ] && err 1 "${MAGENTA}Please set ${GREEN}snapname=${MAGENTA} or use ${GREEN}mode=destroyall ${MAGENTA}to destroy all snapshots for this jail${NORMAL}"
+	[ -n "${jname}" ] && _mod="${ZPOOL}/${jname}@${snapname}"
 
-    for _fs in $(/sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null); do
-	_chkloop=$(( _chkloop + 1 ))
-	# normally we never got _chkloop greater than 1
-	[ ${_chkloop} -gt 10 ] && err 1 "${MAGENTA}Error for parsing snapname in zfs_snapshot_destroy_by_snapname${NORMAL}"
-	_jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null)
-	[ -z "${_jname}" ] && continue
-	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
-	_snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" 2>/dev/null)
-	[ -z "${_snapname}" -o "${_snapname}" != "${snapname}" ] && continue
-	zfs_snapshot_destroy ${_fs} && ${ECHO} "${MAGENTA}zfs snapshot for ${jname} destoyed: ${GREEN}${_snapname}${NORMAL}"
-	# if cycle is not end than something wrong with parsing of snapname
-    done
+	for _fs in $( /sbin/zfs list -H -r -t snapshot -o name ${_mod} 2>/dev/null ); do
+		_chkloop=$(( _chkloop + 1 ))
+		# normally we never got _chkloop greater than 1
+		[ ${_chkloop} -gt 10 ] && err 1 "${MAGENTA}Error for parsing snapname in zfs_snapshot_destroy_by_snapname${NORMAL}"
+		_jname=$( /sbin/zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null )
+		[ -z "${_jname}" ] && continue
+		[ -n "${jname}" -a "${jname}" != "${_jname}" ] && continue
+		_snapname=$( /sbin/zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" 2>/dev/null )
+		[ -z "${_snapname}" -o "${_snapname}" != "${snapname}" ] && continue
+		zfs_snapshot_destroy ${_fs} && ${ECHO} "${MAGENTA}zfs snapshot for ${jname} destoyed: ${GREEN}${_snapname}${NORMAL}"
+		# if cycle is not end than something wrong with parsing of snapname
+	done
 }
 
 rsync_snapshot_list()
 {
-    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
 }
 
 ufs_snapshot_list()
 {
-    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
-    fs_type="ufs"
+	err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+	fs_type="ufs"
 
-    for snap in `snapinfo $fs_dir 2>/dev/null`; do
-	if [ ! -f $snap ]; then
-	    continue
-	fi
+	for snap in $( snapinfo $fs_dir 2>/dev/null ); do
+		[ ! -f $snap ] && continue
 
-	#   determine sizes
-	fs_size=`df -k $fs_dir | tail -n1 | awk '{ print $2; }'`
-	used_size=`df -k $fs_dir | tail -n1 | awk '{ print $3; }'`
-	snap_size=`du -k $snap | awk '{ print $1; }'`
+		#   determine sizes
+		fs_size=$( df -k $fs_dir | tail -n1 | awk '{ print $2; }' )
+		used_size=$( df -k $fs_dir | tail -n1 | awk '{ print $3; }' )
+		snap_size=$( du -k $snap | awk '{ print $1; }' )
 
-	#   determine snapshot creation time
-	if [ ".$verbose" = .yes ]; then
-	    snap_time=`stat -f "%B" $snap`
-	    snap_time=`date -r "$snap_time" "+%Y-%m-%dT%H:%M"`
-	fi
+		#   determine snapshot creation time
+		if [ ".$verbose" = .yes ]; then
+			snap_time=$( stat -f "%B" $snap )
+			snap_time=$( date -r "$snap_time" "+%Y-%m-%dT%H:%M" )
+		fi
 
-	#   calculate percentages
-	snap_percent=`echo . | awk '{ printf("%.1f%%", (snap / fs) * 100); }' snap="$snap_size" fs="$fs_size"`
-	used_percent=`echo . | awk '{ printf("%.1f%%", (used / fs) * 100); }' used="$used_size" fs="$fs_size"`
+		#   calculate percentages
+		snap_percent=` echo . | awk '{ printf("%.1f%%", (snap / fs) * 100); }' snap="$snap_size" fs="$fs_size" `
+		used_percent=` echo . | awk '{ printf("%.1f%%", (used / fs) * 100); }' used="$used_size" fs="$fs_size" `
 
-	#   canonicalize for output
-	fs_size=`canonksize $fs_size`
-	snap_size=`canonksize $snap_size`
-	used_size=`canonksize $used_size`
-	snap_file=`echo "$snap" | sed -e 's;.*/\([^/]*\)$;\1;'`
+		#   canonicalize for output
+		fs_size=$( canonksize $fs_size )
+		snap_size=$( canonksize $snap_size )
+		used_size=$( canonksize $used_size )
+		snap_file=`echo "$snap" | sed -e 's;.*/\([^/]*\)$;\1;'`
 
-	#   output snapshot information
-	if [ ".$verbose" = .yes ]; then
-	    printf "%-15s %4s %8s %7s %8s %7s  %-15s %s\n" "$fs_dir" "$fs_type" "$used_size" "$used_percent" "$snap_size" "$snap_percent" "$snap_file" "$snap_time"
-	else
-	    printf "%-15s %8s %7s %8s %7s  %-15s\n" "$fs_dir" "$used_size" "$used_percent" "$snap_size" "$snap_percent" "$snap_file"
-	fi
-    done
+		#   output snapshot information
+		if [ ".$verbose" = .yes ]; then
+			printf "%-15s %4s %8s %7s %8s %7s  %-15s %s\n" "$fs_dir" "$fs_type" "$used_size" "$used_percent" "$snap_size" "$snap_percent" "$snap_file" "$snap_time"
+		else
+			printf "%-15s %8s %7s %8s %7s  %-15s\n" "$fs_dir" "$used_size" "$used_percent" "$snap_size" "$snap_percent" "$snap_file"
+		fi
+	done
 }
 
 zfs_snapshot_create()
 {
-    local _tst _createtime
+	local _tst _createtime
 
-    [ -z "${snapname}" ] && err 1 "${MAGENTA}Empty ${GREEN}snapname=${NORMAL}"
+	[ -z "${snapname}" ] && err 1 "${MAGENTA}Empty ${GREEN}snapname=${NORMAL}"
 
-    _createtime=$(date "+%Y%m%d%H%M%S")
-    [ "${snapname}" = "gettimeofday" ] && snapname=${_createtime}
+	_createtime=$(date "+%Y%m%d%H%M%S")
+	[ "${snapname}" = "gettimeofday" ] && snapname=${_createtime}
 
-    _tst=$(zfs snapshot ${ZPOOL}/${jname}@${snapname} 2>&1)
-    [ $? -ne 0 ] && err 1 "${MAGENTA}zfs snapshot error: ${NORMAL}${_tst}"
-    zfs set cbsdsnap:jname=${jname} ${ZPOOL}/${jname}@${snapname}
-    zfs set cbsdsnap:snapname=${snapname} ${ZPOOL}/${jname}@${snapname}
+	_tst=$( /sbin/zfs snapshot ${ZPOOL}/${jname}@${snapname} 2>&1)
+	[ $? -ne 0 ] && err 1 "${MAGENTA}zfs snapshot error: ${NORMAL}${_tst}"
+	/sbin/zfs set cbsdsnap:jname=${jname} ${ZPOOL}/${jname}@${snapname}
+	/sbin/zfs set cbsdsnap:snapname=${snapname} ${ZPOOL}/${jname}@${snapname}
 }
 
 ufs_snapshot_create()
 {
-    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
 }
 
 rsync_snapshot_create()
 {
-    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
 }
 
 zfs_snapshot_destroy()
 {
-    [ -z "${1}" ] && return 1
-    zfs destroy ${1}
+	[ -z "${1}" ] && return 1
+	/sbin/zfs destroy ${1}
 }
 
 ufs_snapshot_destroy()
 {
-    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
 }
 
 ufs_snapshot_destroyall()
 {
-    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
 }
 
 ufs_snapshot_destroy_by_snapname()
 {
-    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
 }
 
 rsync_snapshot_destroy()
 {
-    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
 }
 
 
 zfs_snapshot_rollback()
 {
-    local _createtime _fs _snapname _jname
-    [ -z "${snapname}" ] && err 1 "${MAGENTA}empty ${GREEN}snapname=${NORMAL}"
-    _fs="${ZPOOL}/${jname}@${snapname}"
+	local _createtime _fs _snapname _jname
+	[ -z "${snapname}" ] && err 1 "${MAGENTA}empty ${GREEN}snapname=${NORMAL}"
+	_fs="${ZPOOL}/${jname}@${snapname}"
 
-    _jname=$(zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null)
-    [ -z "${_jname}" ] && err 1 "${MAGENTA}no such snapshot ${snapname} for ${jname}${NORMAL}"
-    [ -n "${jname}" -a "${jname}" != "${_jname}" ] && err "${MAGENTA}Found snapshot ${GREEN}${snapname}${MANGETA} but its owner is ${GREEN}${_jname}${NORMAL}"
-    _snapname=$(zfs get -H -o value -s local cbsdsnap:snapname "${_fs}")
-    [ -z "${_snapname}" ] && err 1 "${MAGENTA}Snapshot found but he is not created by ${GREEN}cbsd${NORMAL} - skipp${NORMAL}"
-     _createtime=$(zfs get -H -o value creation "${_fs}")
-    zfs rollback -r ${_fs} && ${ECHO} "${MAGENTA}Restored state to ${GREEN}${snapname}${MAGENTA} snapshot created in ${GREEN}${_createtime}${NORMAL}"
+	_jname=$( /sbin/zfs get -H -o value -s local cbsdsnap:jname "${_fs}" 2>/dev/null)
+	[ -z "${_jname}" ] && err 1 "${MAGENTA}no such snapshot ${snapname} for ${jname}${NORMAL}"
+	[ -n "${jname}" -a "${jname}" != "${_jname}" ] && err "${MAGENTA}Found snapshot ${GREEN}${snapname}${MANGETA} but its owner is ${GREEN}${_jname}${NORMAL}"
+	_snapname=$( /sbin/zfs get -H -o value -s local cbsdsnap:snapname "${_fs}" )
+	[ -z "${_snapname}" ] && err 1 "${MAGENTA}Snapshot found but he is not created by ${GREEN}cbsd${NORMAL} - skipp${NORMAL}"
+	 _createtime=$( /sbin/zfs get -H -o value creation "${_fs}" )
+	/sbin/zfs rollback -r ${_fs} && ${ECHO} "${MAGENTA}Restored state to ${GREEN}${snapname}${MAGENTA} snapshot created in ${GREEN}${_createtime}${NORMAL}"
 }
 
 ufs_snapshot_rollback()
 {
-    err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: ufs not implemented${NORMAL}"
 }
 
 rsync_snapshot_rollback()
 {
-    err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
+	err 1 "${MAGENTA}jsnapshot: rsync not implemented${NORMAL}"
 }
 
 #MAIN
 if [ -z "${snapfs}" ]; then
-    if [ "$zfsfeat" = "1" ]; then
-	snapfs="zfs"
-	. $zfstool
-	ZPOOL=$( /sbin/zfs get -Ho value name ${jaildatadir} 2>/dev/null)
-	[ -z "${ZPOOL}" ] && err 1 "${MAGENTA}Can't find ZFS pool on ${GREEN}${jaildatadir}${NORMAL}"
-    else
-	snapfs="ufs"
-    fi
+	if [ "$zfsfeat" = "1" ]; then
+		snapfs="zfs"
+		. $zfstool
+		ZPOOL=$( /sbin/zfs get -Ho value name ${jaildatadir} 2>/dev/null)
+		[ -z "${ZPOOL}" ] && err 1 "${MAGENTA}Can't find ZFS pool on ${GREEN}${jaildatadir}${NORMAL}"
+	else
+		snapfs="ufs"
+	fi
 fi
 
 [ -z "${display}" ] && display="jname,snapname,creation,used"
@@ -255,23 +252,23 @@ myheader=$(echo ${mydisplay} |tr '[:lower:]' '[:upper:]')
 [ -z "${header}" ] && header=1
 
 case "${mode}" in
-    "list")
-	${snapfs}_snapshot_list |/usr/bin/column -t
-	;;
-    "create")
-	check_jname
-	${snapfs}_snapshot_create
-	;;
-    "destroy")
-	check_jname
-	${snapfs}_snapshot_destroy_by_snapname
-	;;
-    "destroyall")
-	check_jname
-	${snapfs}_snapshot_destroyall
-	;;
-    "rollback")
-	check_jname
-	${snapfs}_snapshot_rollback
-	;;
+	"list")
+		${snapfs}_snapshot_list |/usr/bin/column -t
+		;;
+	"create")
+		check_jname
+		${snapfs}_snapshot_create
+		;;
+	"destroy")
+		check_jname
+		${snapfs}_snapshot_destroy_by_snapname
+		;;
+	"destroyall")
+		check_jname
+		${snapfs}_snapshot_destroyall
+		;;
+	"rollback")
+		check_jname
+		${snapfs}_snapshot_rollback
+		;;
 esac
diff --git a/nodectl/node b/nodectl/node
--- a/nodectl/node
+++ b/nodectl/node
@@ -23,148 +23,148 @@ init $*
 
 getpw()
 {
-    local oldmodes=`stty -g`
-    pw=""
+	local oldmodes=$( stty -g )
+	pw=""
 
-    trap "stty ${oldmodes}" HUP INT ABRT BUS TERM EXIT
+	trap "stty ${oldmodes}" HUP INT ABRT BUS TERM EXIT
 
-    printf "${BOLD}Enter password of cbsd user on ${GREEN}${node}${NORMAL}${BOLD}:${NORMAL} "
-    while [ -z "${pw}" ]; do
-	stty -echo
-	set -e
-	read pw
-	set +e
-    done
+	printf "${BOLD}Enter password of cbsd user on ${GREEN}${node}${NORMAL}${BOLD}:${NORMAL} "
+	while [ -z "${pw}" ]; do
+		stty -echo
+		set -e
+		read pw
+		set +e
+	done
 
-    stty $oldmodes
-    echo
+	stty $oldmodes
+	echo
 }
 
 
 nodeadd()
 {
-    [ -z "${node}" ] && err 1 "${MAGENTA}Empty node${NORMAL}"
-    [ -z "${port}" ] && port=22222
-    [ -z "${pw}" ] && getpw
-    [ -z "${rootkeyfile}" ] && rootkeyfile="/root/.ssh/id_rsa"
+	[ -z "${node}" ] && err 1 "${MAGENTA}Empty node${NORMAL}"
+	[ -z "${port}" ] && port=22222
+	[ -z "${pw}" ] && getpw
+	[ -z "${rootkeyfile}" ] && rootkeyfile="/root/.ssh/id_rsa"
 
-    if iptype $node; then
-	resolvhost ${node}
-	[ -z "${HST}" ] && err 1 "${MAGENTA}Can't resolv IP for ${node} hostname. Use IP address.${NORMAL}"
-	node=$HST
-    fi
+	if iptype $node; then
+		resolvhost ${node}
+		[ -z "${HST}" ] && err 1 "${MAGENTA}Can't resolv IP for ${node} hostname. Use IP address.${NORMAL}"
+		node=$HST
+	fi
 
-    ${ECHO} "${MAGENTA}Connecting to ${node}...${NORMAL}"
-    NODENAME=$( cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename )
+	${ECHO} "${MAGENTA}Connecting to ${node}...${NORMAL}"
+	NODENAME=$( cbsd cbsdssh $node $port $cbsduser $pw cbsd getinfo -q nodename )
 
-    case $? in
-	0)
-	    [ -z "$NODENAME" ] && err 1 "${MAGENTA}No nodename found. Check remote cbsd settings${NORMAL}"
-	    ${ECHO} "${MAGENTA}${node} has nodename: ${GREEN}${NODENAME}${NORMAL}"
-	;;
-	1)
-	    err 1 "${MAGENTA}Connection problem: ${GREEN}${node}${NORMAL}"
-	;;
-	2)
-	    err 1 "${MAGENTA}Bad password or system user${NORMAL}"
-	;;
-    esac
+	case $? in
+		0)
+			[ -z "$NODENAME" ] && err 1 "${MAGENTA}No nodename found. Check remote cbsd settings${NORMAL}"
+			${ECHO} "${MAGENTA}${node} has nodename: ${GREEN}${NODENAME}${NORMAL}"
+			;;
+		1)
+			err 1 "${MAGENTA}Connection problem: ${GREEN}${node}${NORMAL}"
+			;;
+		2)
+			err 1 "${MAGENTA}Bad password or system user${NORMAL}"
+			;;
+	esac
 
-    MD5NAME=`md5 -qs ${NODENAME}`
-    cbsd nodeaddkey md5name=${MD5NAME} ip=${node} port=${port} pw=${pw} > $DEBLOG 2>&1
+	MD5NAME=`md5 -qs ${NODENAME}`
+	cbsd nodeaddkey md5name=${MD5NAME} ip=${node} port=${port} pw=${pw} > $DEBLOG 2>&1
 
-    case $? in
-	0)
-	    ${ECHO} "${MAGENTA}Added successfull: ${GREEN}${node}${NORMAL}"
-	    LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
-	    sysrc -qf ${rsshdir}/${NODENAME}.node SSHKEY=$LOCALKEY > /dev/null
-	    sysrc -qf ${rsshdir}/${NODENAME}.node IP=$node > /dev/null
-	    sysrc -qf ${rsshdir}/${NODENAME}.node PORT=$port > /dev/null
-	    chown ${cbsduser} ${rsshdir}/${NODENAME}.node
-	    IP=`cbsdsql nodes select ip from nodelist where nodename=\"${NODENAME}\"`
+	case $? in
+		0)
+			${ECHO} "${MAGENTA}Added successfull: ${GREEN}${node}${NORMAL}"
+			LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
+			sysrc -qf ${rsshdir}/${NODENAME}.node SSHKEY=$LOCALKEY > /dev/null
+			sysrc -qf ${rsshdir}/${NODENAME}.node IP=$node > /dev/null
+			sysrc -qf ${rsshdir}/${NODENAME}.node PORT=$port > /dev/null
+			chown ${cbsduser} ${rsshdir}/${NODENAME}.node
+			IP=`cbsdsql nodes select ip from nodelist where nodename=\"${NODENAME}\"`
 
-	    if [ -z "${IP}" ]; then
-		cbsdsql nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
-	    else
-		${ECHO} "${MAGENTA}Already exist in database, updating: ${GREEN}${node}${NORMAL}"
-		cbsdsql nodes DELETE FROM nodelist WHERE nodename=\"${NODENAME}\"
-		cbsdsql nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
-	    fi
-	    idle_update ${NODENAME}
-	    cbsd retrinv node=${NODENAME} tryoffline=1
-	;;
-	1)
-	    cat ${DEBLOG}
-	    err 1 "${MAGENTA}Error: Bad password${NORMAL}"
-	;;
-	2)
-	    [ -f "${DEBLOG}" ] && cat ${DEBLOG}
-	    err 1 "${MAGENTA}Error: No key found or wrong hostname. Make initenv on remote machine${NORMAL}"
-	;;
-	*)
-	    cat ${DEBLOG}
-	    err 1 "${MAGENTA}Error: Unkown error${NORMAL}"
-	;;
-    esac
+			if [ -z "${IP}" ]; then
+				cbsdsql nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
+			else
+				${ECHO} "${MAGENTA}Already exist in database, updating: ${GREEN}${node}${NORMAL}"
+				cbsdsql nodes DELETE FROM nodelist WHERE nodename=\"${NODENAME}\"
+				cbsdsql nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
+			fi
+			idle_update ${NODENAME}
+			cbsd retrinv node=${NODENAME} tryoffline=1
+			;;
+		1)
+			cat ${DEBLOG}
+			err 1 "${MAGENTA}Error: Bad password${NORMAL}"
+			;;
+		2)
+			[ -f "${DEBLOG}" ] && cat ${DEBLOG}
+			err 1 "${MAGENTA}Error: No key found or wrong hostname. Make initenv on remote machine${NORMAL}"
+			;;
+		*)
+			cat ${DEBLOG}
+			err 1 "${MAGENTA}Error: Unkown error${NORMAL}"
+			;;
+	esac
 }
 
 nodedel()
 {
-    local _descext="descr role domain notes location" _res
+	local _descext="descr role domain notes location" _res
 
-    [ -n "${node}" ] || err 1 "${MAGENTA}Empty node${NORMAL}"
-    NODECONF="${rsshdir}/${node}.node"
+	[ -n "${node}" ] || err 1 "${MAGENTA}Empty node${NORMAL}"
+	NODECONF="${rsshdir}/${node}.node"
 
-    if [ -f "${NODECONF}" ]; then
-	. ${NODECONF}
-	[ -f ${SSHKEY} ] && rm -f ${SSHKEY}
-	rm -f ${NODECONF}
-    else
-	${ECHO} "${MAGENTA}No such node config: ${GREEN}${NODECONF}${NORMAL}"
-    fi
+	if [ -f "${NODECONF}" ]; then
+		. ${NODECONF}
+		[ -f ${SSHKEY} ] && rm -f ${SSHKEY}
+		rm -f ${NODECONF}
+	else
+		${ECHO} "${MAGENTA}No such node config: ${GREEN}${NODECONF}${NORMAL}"
+	fi
 
-    [ -f "${dbdir}/${node}.sqlite" ] && rm -f "${dbdir}/${node}.sqlite"
-    _res=$( cbsdsql nodes DELETE FROM nodelist WHERE nodename=\"${node}\" )
+	[ -f "${dbdir}/${node}.sqlite" ] && rm -f "${dbdir}/${node}.sqlite"
+	_res=$( cbsdsql nodes DELETE FROM nodelist WHERE nodename=\"${node}\" )
 
-    #descriptions die too
-    find ${dbdir}/nodedescr -type f -depth 1 -maxdepth 1 -name ${node}.\*.descr -delete
-    for i in ${_descext}; do
-	[ -f "${dbdir}/nodedescr/${node}.${i}" ] && rm -f "${dbdir}/nodedescr/${node}.${i}"
-    done
-    err 0 "${MAGENTA}Removed${NORMAL}"
+	#descriptions die too
+	find ${dbdir}/nodedescr -type f -depth 1 -maxdepth 1 -name ${node}.\*.descr -delete
+	for i in ${_descext}; do
+		[ -f "${dbdir}/nodedescr/${node}.${i}" ] && rm -f "${dbdir}/nodedescr/${node}.${i}"
+	done
+	err 0 "${MAGENTA}Removed${NORMAL}"
 }
 
 conv_idle()
 {
-    local _res
+	local _res
 
-    if [ ${sqlreplica} -eq 1 ]; then
-	_res=$( check_locktime ${ftmpdir}/shmux_${_ip}.lock )
-	[ $? -eq 0 ] && _nodestatus="Connected" && _idle=${_res} && return 0
-    fi
+	if [ ${sqlreplica} -eq 1 ]; then
+		_res=$( check_locktime ${ftmpdir}/shmux_${_ip}.lock )
+		[ $? -eq 0 ] && _nodestatus="Connected" && _idle=${_res} && return 0
+	fi
 
-    _nodestatus="Disconnected"
-    idle_time=$( /bin/date -j -f "%Y-%m-%d %H:%M:%S" "${_idle}" "+%s" )
-    _res=$(( ( curtime - idle_time ) / 60 ))
-    _idle="${_res}"
+	_nodestatus="Disconnected"
+	idle_time=$( /bin/date -j -f "%Y-%m-%d %H:%M:%S" "${_idle}" "+%s" )
+	_res=$(( ( curtime - idle_time ) / 60 ))
+	_idle="${_res}"
 }
 
 
 nodelist()
 {
-    if [ ${allinfo} -eq 0 ]; then
-	cbsdsql nodes SELECT nodename FROM nodelist
-    else
-	[ ${header} -eq 1 ] && ${ECHO} "${BOLD}NODENAME IP PORT KEYFILE STATUS IDLE${NORMAL}"
-	local sqldelimer="|"
-	local IFS="|"
-	cbsdsql nodes SELECT nodename,ip,port,keyfile,idle FROM nodelist |while read _nodename _ip _port _keyfile _idle; do
-	    conv_idle
-	    printf "${NORMAL}${_nodename} ${_ip} ${_port} ${_keyfile} ${_nodestatus} ${_idle}\n"
-	done
-    fi
-    unset sqldelimer
-    local IFS
+	if [ ${allinfo} -eq 0 ]; then
+		cbsdsql nodes SELECT nodename FROM nodelist
+	else
+		[ ${header} -eq 1 ] && ${ECHO} "${BOLD}NODENAME IP PORT KEYFILE STATUS IDLE${NORMAL}"
+		local sqldelimer="|"
+		local IFS="|"
+		cbsdsql nodes SELECT nodename,ip,port,keyfile,idle FROM nodelist |while read _nodename _ip _port _keyfile _idle; do
+			conv_idle
+			printf "${NORMAL}${_nodename} ${_ip} ${_port} ${_keyfile} ${_nodestatus} ${_idle}\n"
+		done
+	fi
+	unset sqldelimer
+	local IFS
 }
 
 
@@ -175,16 +175,16 @@ curtime=$( /bin/date +%s )
 [ -z "${header}" ] && header=1
 
 case "${mode}" in
-    "add")
-	nodeadd
-    ;;
-    "remove")
-	nodedel
-    ;;
-    "list")
-	nodelist |/usr/bin/column -t
-    ;;
-    *)
-	err 1 "${MAGENTA}Unknown mode${NORMAL}"
-    ;;
+	"add")
+		nodeadd
+		;;
+	"remove")
+		nodedel
+		;;
+	"list")
+		nodelist |/usr/bin/column -t
+		;;
+	*)
+		err 1 "${MAGENTA}Unknown mode${NORMAL}"
+		;;
 esac
