make replacewdir also for jregister/junregister
not only for jimport/jexport:
different systems with a common file system can use different CBSD workdir,
thus we need to change and replace CBSD workdir every time upon j[u]register

diff --git a/jailctl/junregister b/jailctl/junregister
--- a/jailctl/junregister
+++ b/jailctl/junregister
@@ -56,5 +56,24 @@ for jname in ${JLIST}; do
 	fi
 
 	jmkrcconf jname=${jname} > ${JAILRCCONF}
+	res=$( replacewdir file0="${JAILRCCONF}" old=${workdir} new="CBSDROOT" )
+	_ret=$?
+	if [ ${_ret} -ne 0 ]; then
+		/bin/rm -f ${JAILRCCONF}
+		err 1 "${MAGENTA}Error replacewdir for ${JAILRCCONF}: ${res}${NORMAL}"
+	fi
+
+	if [ -r ${mount_fstab} ]; then
+		res=$( replacewdir file0="${mount_fstab}" old=${workdir} new="CBSDROOT" )
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Error replacewdir for ${mount_fstab}: ${res}${NORMAL}"
+	fi
+
+	if [ -r {mount_fstab}.local ]; then
+		res=$( replacewdir file0="{mount_fstab}.local" old=${workdir} new="CBSDROOT" )
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Error replacewdir for ${mount_fstab}.local: ${res}${NORMAL}"
+	fi
+
 	register_delete_full
 done
