convert to cixinit

diff --git a/modules/pkg.d/pkg b/modules/pkg.d/pkg
--- a/modules/pkg.d/pkg
+++ b/modules/pkg.d/pkg
@@ -1,9 +1,8 @@
 #!/usr/local/bin/cbsd
-# fetch http://pkgmir.pkg.freebsd.org/freebsd:11:x86:64/latest/packagesite.txz
 #v11.2.0
 CBSDMODULE="jail"
-MYARG="mode"
-MYOPTARG="jname pkglist name repodir pkgconf chroot nomount cbsd_pkg_verbose cbsd_pkg_retry cbsd_pkg_interrupt_on_error cbsd_pkg_bootstrap_interrupt_on_error"
+CIXARG="mode"
+CIXOPTARG="jname pkglist name repodir pkgconf chroot nomount cbsd_pkg_verbose cbsd_pkg_retry cbsd_pkg_interrupt_on_error cbsd_pkg_bootstrap_interrupt_on_error"
 MYDESC="Manage jail packages via pkg(7)"
 ADDHELP="
 ${H3_COLOR}Description${N0_COLOR}:
@@ -48,8 +47,9 @@ ${H3_COLOR}Examples${N0_COLOR}:
 EXTHELP="modules/pkg.d"
 
 . ${subrdir}/nc.subr
+. ${tools}
 cloud_api=0
-. ${cbsdinit}
+cixinit
 
 # store values from args to overwrite config
 [ -n "${cbsd_pkg_retry}" ] && ocbsd_pkg_retry="${cbsd_pkg_retry}"
@@ -130,7 +130,7 @@ else
 fi
 
 if [ ${cbsd_api} -eq 1 ]; then
-	CURL_CMD=$( which curl )
+	[ -z "${CURL_CMD}" ] && CURL_CMD=$( which curl )
 	[ -z "${CURL_CMD}" ] && err 1 "${N1_COLOR}cloud up requires curl, please install: ${N2_COLOR}pkg install -y curl${N0_COLOR}"
 	[ -z "${CBSDFILE_RECURSIVE}" ] && ${ECHO} "${N1_COLOR}main cloud api: ${N2_COLOR}${CLOUD_URL}${N0_COLOR}" 1>&2
 	_cid=$( ${miscdir}/cbsd_md5 "${CLOUD_KEY}" )
@@ -165,21 +165,7 @@ if [ ${cbsd_api} -eq 1 ]; then
 		_args=
 
 		# trim for jname= in "$*"
-		for i in $*; do
-			prefix=
-			prefix6=$( substr --pos=0 --len=6 --str="${i}" )
-			prefix5=$( substr --pos=0 --len=5 --str="${i}" )
-			prefix15=$( substr --pos=0 --len=15 --str="${i}" )
-			prefix17=$( substr --pos=0 --len=17 --str="${i}" )
-			prefix28=$( substr --pos=0 --len=28 --str="${i}" )
-			prefix38=$( substr --pos=0 --len=38 --str="${i}" )
-
-			[ "${prefix15}" = "cbsd_pkg_retry=" ] && continue
-			[ "${prefix17}" = "cbsd_pkg_verbose=" ] && continue
-			[ "${prefix28}" = "cbsd_pkg_interrupt_on_error=" ] && continue
-			[ "${prefix38}" = "cbsd_pkg_bootstrap_interrupt_on_error=" ] && continue
-			[ "${prefix6}" = "jname=" ] && continue
-			[ "${prefix5}" = "mode=" ] && continue
+		for i in ${CIX_OTHER_ARGS}; do
 			if [ -n "${_args}" ]; then
 				_args="${_args} ${i}"
 			else
@@ -195,19 +181,19 @@ if [ ${cbsd_api} -eq 1 ]; then
 					${jexec_cmd} pkg-static clean -ya
 					;;
 			bootstrap|update)
-					printf "${N1_COLOR}pkg: [${N2_COLOR}bootstrap...${N1_COLOR}${N0_COLOR}"
+					printf "${N1_COLOR}pkg: [${N2_COLOR}bootstrap...${N1_COLOR}${N0_COLOR}" 1>&2
 					${jexec_cmd} /bin/sh <<EOF
 ${ENV_CMD} ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes pkg bootstrap -f
 ${ENV_CMD} IGNORE_OSVERSION=yes SIGNATURE_TYPE=none ${TIMEOUT_CMD} 60 pkg update -f
 EOF
 					_ret=$?
 					if [ ${_ret} -eq 0 ]; then
-						printf "${N2_COLOR}ok${N1_COLOR}]${N0_COLOR}"
-						echo
+						printf "${N2_COLOR}ok${N1_COLOR}]${N0_COLOR}" 1>&2
+						echo 1>&2
 						break
 					else
-						printf "${N1_COLOR}bootstrap failed${N1_COLOR}]${N0_COLOR}"
-						echo
+						printf "${N1_COLOR}bootstrap failed${N1_COLOR}]${N0_COLOR}" 1>&2
+						echo 1>&2
 						echo "${_ret}"
 					fi
 				;;
@@ -218,12 +204,12 @@ ${ENV_CMD} SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes IGNORE_OSVERSION=yes pkg in
 EOF
 					_ret=$?
 					if [ ${_ret} -eq 0 ]; then
-						printf "${N2_COLOR}ok${N1_COLOR}]${N0_COLOR}"
-						echo
+						printf "${N2_COLOR}ok${N1_COLOR}]${N0_COLOR}" 1>&2
+						echo 1>&2
 						break
 					else
-						printf "${N1_COLOR}bootstrap failed${N1_COLOR}]${N0_COLOR}"
-						echo
+						printf "${N1_COLOR}bootstrap failed${N1_COLOR}]${N0_COLOR}" 1>&2
+						echo 1>&2
 						echo "${_ret}"
 					fi
 				;;
@@ -301,21 +287,7 @@ if [ -n "${jail_list}" ]; then
 	_args=
 
 	# trim for jname= in "$*"
-	for i in $*; do
-		prefix=
-		prefix6=$( substr --pos=0 --len=6 --str="${i}" )
-		prefix5=$( substr --pos=0 --len=5 --str="${i}" )
-		prefix15=$( substr --pos=0 --len=15 --str="${i}" )
-		prefix17=$( substr --pos=0 --len=17 --str="${i}" )
-		prefix28=$( substr --pos=0 --len=28 --str="${i}" )
-		prefix38=$( substr --pos=0 --len=38 --str="${i}" )
-
-		[ "${prefix15}" = "cbsd_pkg_retry=" ] && continue
-		[ "${prefix17}" = "cbsd_pkg_verbose=" ] && continue
-		[ "${prefix28}" = "cbsd_pkg_interrupt_on_error=" ] && continue
-		[ "${prefix38}" = "cbsd_pkg_bootstrap_interrupt_on_error=" ] && continue
-		[ "${prefix6}" = "jname=" ] && continue
-		[ "${prefix5}" = "mode=" ] && continue
+	for i in ${CIX_OTHER_ARGS}; do
 		if [ -n "${_args}" ]; then
 			_args="${_args} ${i}"
 		else
@@ -410,20 +382,7 @@ fi
 
 # trim special args
 _args=
-for i in $*; do
-	prefix=
-	prefix6=$( substr --pos=0 --len=6 --str="${i}" )
-	prefix5=$( substr --pos=0 --len=5 --str="${i}" )
-	prefix15=$( substr --pos=0 --len=15 --str="${i}" )
-	prefix17=$( substr --pos=0 --len=17 --str="${i}" )
-	prefix28=$( substr --pos=0 --len=28 --str="${i}" )
-	prefix38=$( substr --pos=0 --len=38 --str="${i}" )
-	[ "${prefix15}" = "cbsd_pkg_retry=" ] && continue
-	[ "${prefix17}" = "cbsd_pkg_verbose=" ] && continue
-	[ "${prefix28}" = "cbsd_pkg_interrupt_on_error=" ] && continue
-	[ "${prefix38}" = "cbsd_pkg_bootstrap_interrupt_on_error=" ] && continue
-	[ "${prefix6}" = "jname=" ] && continue
-	[ "${prefix5}" = "mode=" ] && continue
+for i in ${CIX_OTHER_ARGS}; do
 	if [ -n "${_args}" ]; then
 		_args="${_args} ${i}"
 	else
