Prepare for FreeBSD 10.2-RELEASE: fix kmem patch, some of vm-profiles

diff --git a/system/buildkernel b/system/buildkernel
--- a/system/buildkernel
+++ b/system/buildkernel
@@ -50,6 +50,14 @@ else
 fi
 
 init_basedir
+
+if [ ! -d "${BASE_DIR}" -o ! -f "${BASE_DIR}/bin/sh" ]; then
+	${ECHO} "${MAGENTA}FreeBSD base on ${GREEN}${BASE_DIR}${MAGENTA} is missing${NORMAL}"
+	${ECHO} "${MAGENTA}Use ${GREEN}cbsd world${MAGENTA} to compile from the source${NORMAL}"
+	${ECHO} "${GREEN}cbsd repo action=get sources=base${MAGENTA} to obtain it from repository.${NORMAL}"
+	exit 1
+fi
+
 init_make_flags
 
 LOCKFILE=${ftmpdir}/$( /sbin/md5 -qs ${MAKEOBJDIRPREFIX} ).lock
