etcupdate: wip, #474

diff --git a/system/etcupdate b/system/etcupdate
--- a/system/etcupdate
+++ b/system/etcupdate
@@ -14,8 +14,10 @@
 #      etcupdate_excludes="-I '/root/*' -I '/etc/hosts'" ?
 MYARG="mode"
 MYOPTARG="from to jname ver default_obtain_etcupdate_method"
-MYDESC="Upgrade jail base data when baserw=1"
+MYDESC="etcupdate helper, manage updates to system files not updated by installworld"
 CBSDMODULE="jail"
+ADDHELP="mode - extract,build,update\n\
+default_obtain_etcupdate_method= overwrite obtain method, valid: build,index\n"
 
 . ${subr}
 . ${strings}
@@ -48,8 +50,7 @@ case "${mode}" in
 		init_target_arch
 		init_srcdir
 
-		etcupdate_dir_root=$( ${REALPATH_CMD} ${SRC_DIR}/../ )
-		etcupdate_dir="${etcupdate_dir_root}/etcupdate"
+		etcupdate_dir="${srcdir}/src_${ver}/etcupdate"
 
 		case "${default_obtain_etcupdate_method}" in
 			build)
@@ -82,7 +83,7 @@ case "${mode}" in
 
 				[ -d ${etcupdate_dir}/current ] && ${RM_CMD} -rf ${etcupdate_dir}/current
 				${ECHO} "${N1_COLOR}${CBSD_APP}: extract to: ${N2_COLOR}${etcupdate_dir}/current${N1_COLOR} (by: ${N2_COLOR}${index_file} <- ${BASE_DIR}${N1_COLOR})${N0_COLOR}"
-				copy-binlib filelist=${index_file} dstdir=${etcupdate_dir}/current basedir=${BASE_DIR}
+				copy-binlib filelist=${index_file} dstdir=${etcupdate_dir}/current basedir=${BASE_DIR} 2>/dev/null
 				;;
 			*)
 				err 1 "${N1_COLOR}${CBSD_APP}: unknown default_obtain_etcupdate_method: ${N2_COLOR}${default_obtain_etcupdate_method}${N0_COLOR}"
@@ -97,8 +98,7 @@ case "${mode}" in
 		init_target_arch
 		init_srcdir
 
-		etcupdate_dir_root=$( ${REALPATH_CMD} ${SRC_DIR}/../ )
-		etcupdate_dir="${etcupdate_dir_root}"
+		etcupdate_dir="${srcdir}/src_${ver}/etcupdate"
 
 		case "${default_obtain_etcupdate_method}" in
 			build)
@@ -112,29 +112,40 @@ case "${mode}" in
 				fi
 				;;
 			index)
-				${ECHO} "${N1_COLOR}${CBSD_APP}: build to: ${N2_COLOR}${etcupdate_dir}${N1_COLOR} (by: ${N2_COLOR}${index_file} <- ${BASE_DIR}${N1_COLOR})${N0_COLOR}"
+				[ ! -d ${etcupdate_dir}/current ] && etcupdate mode=extract ver=${ver}
+				[ ! -d ${etcupdate_dir}/current ] && err 1 "${N1_COLOR}${CBSD_APP} no dir: ${N1_COLOR}${etcupdate_dir}/current${N1_COLOR}. please run: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
+
+				${ECHO} "${N1_COLOR}${CBSD_APP}: build to: ${N2_COLOR}${etcupdate_dir}/etcupdate.tgz${N1_COLOR} (from: ${N2_COLOR}${etcupdate_dir}/current${N1_COLOR})${N0_COLOR}"
+				[ -r ${etcupdate_dir}/etcupdate.tgz ] && ${RM_CMD} -f ${etcupdate_dir}/etcupdate.tgz
+				cd ${etcupdate_dir}/current
+				${TAR_CMD} cfz ${etcupdate_dir}/etcupdate.tgz .
+				[ ! -r ${etcupdate_dir}/etcupdate.tgz ] && err 1 "${N1_COLOR}${CBSD_APP} failed to build: ${N1_COLOR}${etcupdate_dir}/etcupdate.tgz${N0_COLOR}"
 				;;
 		esac
 		;;
 	update)
+		[ -z "${jname}" ] && log_err 1 "${N1_COLOR}Please set jset: ${N2_COLOR}jname${N0_COLOR}"
 		. ${jrcconf}
-		[ $? -eq 1 ] && log_err 1 "${N1_COLOR}${CBSD_APP}no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+		[ $? -eq 1 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 
 		[ -z "${from}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}from=${N0_COLOR}"
 		[ -z "${to}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}to=${N0_COLOR}"
+
 		ver="${from}"
 		init_target_arch
 		init_srcdir
-		etcupdate_from_dir_root=$( ${REALPATH_CMD} ${SRC_DIR}/../ )
-		etcupdate_from_dir="${etcupdate_from_dir_root}/etcupdate"
-		[ ! -d ${etcupdate_from_dir}/current ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}${etcupdate_from_dir}/current${N0_COLOR}"
+
+		etcupdate_from_dir="${srcdir}/src_${ver}/etcupdate"
+		if [ ! -d ${etcupdate_from_dir}/current ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP} error: no such ${N2_COLOR}${etcupdate_from_dir}/current${N0_COLOR}"
+			err 1 "${N1_COLOR}please run for init: ${N2_COLOR}cbsd etcupdate mode=extract ver=${ver}${N0_COLOR}"
+		fi
 		${ECHO} "${N1_COLOR}${CBSD_APP} source hier: ${N2_COLOR}${etcupdate_from_dir}/current${N0_COLOR}"
 
 		ver="${to}"
 		init_target_arch
 		init_srcdir
-		etcupdate_to_dir_root=$( ${REALPATH_CMD} ${SRC_DIR}/../ )
-		etcupdate_to_dir="${etcupdate_to_dir_root}"
+		etcupdate_to_dir="${srcdir}/src_${ver}"
 
 		if [ ! -r ${etcupdate_to_dir}/etcupdate.tgz ]; then
 			err 1 "${N1_COLOR}${CBSD_APP} failed: no ${N2_COLOR}${etcupdate_to_dir}/etcupdate.tgz${N0_COLOR}"
@@ -147,7 +158,8 @@ case "${mode}" in
 		[ ! -d ${etcupdate_jail_root} ] && ${MKDIR_CMD} -p ${etcupdate_jail_root}
 		# we need RW place for log? redefine log path and use nullfs in RO?
 		${CP_CMD} -a ${etcupdate_from_dir}/current ${etcupdate_jail_root}
-		${ETCUPDATE_CMD} -d ${etcupdate_jail_root} -t ${etcupdate_to_dir}/etcupdate.tgz -D ${path}
+		echo "${ETCUPDATE_CMD} -d ${etcupdate_jail_root} -t ${etcupdate_to_dir}/etcupdate.tgz -D ${path} ${extra_etcupdate_flags}"
+		${ETCUPDATE_CMD} -d ${etcupdate_jail_root} -t ${etcupdate_to_dir}/etcupdate.tgz -D ${path} ${extra_etcupdate_flags}
 		;;
 	*)
 		err 1 "${N1_COLOR}${CBSD_APP} error: unknown mode: ${N2_COLOR}${mode}${N0_COLOR}"
