update pkg-base

diff --git a/system/install-pkg-world b/system/install-pkg-world
--- a/system/install-pkg-world
+++ b/system/install-pkg-world
@@ -132,35 +132,35 @@ export ASSUME_ALWAYS_YES=yes
 export ABI
 eval base_in_pkg_repo_url="${base_in_pkg_repo_url}"
 
-${FETCH_CMD} -o /tmp/distribution_${arch}_${target_arch}_${ver}.tgz  ${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz
-ret=$?
-if [ ${ret} -ne 0 ]; then
-	err 1 "${N1_COLOR}fetch distribution archive failed: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
-fi
+# CIX only
+#${FETCH_CMD} -o /tmp/distribution_${arch}_${target_arch}_${ver}.tgz  ${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz
+#ret=$?
+#if [ ${ret} -ne 0 ]; then
+#	err 1 "${N1_COLOR}fetch distribution archive failed: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+#fi
 
-if [ ! -r /tmp/distribution_${arch}_${target_arch}_${ver}.tgz ]; then
-	err 1 "${N1_COLOR}fetch distribution archive failed: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
-fi
+#if [ ! -r /tmp/distribution_${arch}_${target_arch}_${ver}.tgz ]; then
+#	err 1 "${N1_COLOR}fetch distribution archive failed: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+#fi
 
+#cd /tmp
+#${TAR_CMD} xfz distribution_${arch}_${target_arch}_${ver}.tgz
+#ret=$?
+#if [ ${ret} -ne 0 ]; then
+#	${RM_CMD} -f distribution_${arch}_${target_arch}_${ver}.tgz
+#	err 1 "${N1_COLOR}unable to extract archive into /tmp: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+#fi
 
-cd /tmp
-${TAR_CMD} xfz distribution_${arch}_${target_arch}_${ver}.tgz
-ret=$?
-if [ ${ret} -ne 0 ]; then
-	${RM_CMD} -f distribution_${arch}_${target_arch}_${ver}.tgz
-	err 1 "${N1_COLOR}unable to extract archive into /tmp: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
-fi
+#${RM_CMD} -f distribution_${arch}_${target_arch}_${ver}.tgz
 
-${RM_CMD} -f distribution_${arch}_${target_arch}_${ver}.tgz
-
-if [ ! -r /tmp/distribution_${arch}_${target_arch}_${ver}/COPYRIGHT ]; then
-	[ -d /tmp/distribution_${arch}_${target_arch}_${ver} ] && ${RM_CMD} -rf /tmp/distribution_${arch}_${target_arch}_${ver}
-	err 1 "${N1_COLOR}fetch/extract distribution archive failed: no such /COPYRIGHT file in ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
-fi
+#if [ ! -r /tmp/distribution_${arch}_${target_arch}_${ver}/COPYRIGHT ]; then
+#	[ -d /tmp/distribution_${arch}_${target_arch}_${ver} ] && ${RM_CMD} -rf /tmp/distribution_${arch}_${target_arch}_${ver}
+#	err 1 "${N1_COLOR}fetch/extract distribution archive failed: no such /COPYRIGHT file in ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+#fi
 
 # to log?
-${RSYNC_CMD} -avz /tmp/distribution_${arch}_${target_arch}_${ver}/ ${BASE_DIR}/ > /dev/null 2>&1
-[ -d /tmp/distribution_${arch}_${target_arch}_${ver} ] && ${RM_CMD} -rf /tmp/distribution_${arch}_${target_arch}_${ver}
+#${RSYNC_CMD} -avz /tmp/distribution_${arch}_${target_arch}_${ver}/ ${BASE_DIR}/ > /dev/null 2>&1
+#[ -d /tmp/distribution_${arch}_${target_arch}_${ver} ] && ${RM_CMD} -rf /tmp/distribution_${arch}_${target_arch}_${ver}
 
 # Setup pkg
 ${MKDIR_CMD} -p ${BASE_DIR}/usr/share/keys/
@@ -169,14 +169,24 @@ ${RSYNC_CMD} -avz /usr/share/keys/ ${BASE_DIR}/usr/share/keys/
 # we need to use system/global path
 [ ! -d ${BASE_DIR}/etc/pkg ] && ${MKDIR_CMD} -p ${BASE_DIR}/etc/pkg
 ${ECHO} "${N1_COLOR}Generate pkg.conf for base-in-packages v${ver}: ${N2_COLOR}${BASE_DIR}/etc/pkg/base-in-pkg.conf${N0_COLOR}"
+#${CAT_CMD} > ${BASE_DIR}/etc/pkg/base-in-pkg.conf <<EOF
+## created by CBSD install-pkg-world
+#cbsd-base-in-pkg: {
+#	conservative_upgrade: no,
+#	priority: 10
+#	url: "${base_in_pkg_repo_url}",
+#	mirror_type: "none",
+#	enabled: yes
+#}
+#EOF
+
 ${CAT_CMD} > ${BASE_DIR}/etc/pkg/base-in-pkg.conf <<EOF
-# created by CBSD install-pkg-world
 cbsd-base-in-pkg: {
-	conservative_upgrade: no,
-	priority: 10
-	url: "${base_in_pkg_repo_url}",
-	mirror_type: "none",
-	enabled: yes
+  url: "${base_in_pkg_repo_url}",
+  mirror_type: "srv",
+  signature_type: "fingerprints",
+  fingerprints: "/usr/share/keys/pkg",
+  enabled: yes
 }
 EOF
 
@@ -222,7 +232,7 @@ if [ -x "${PKG_CMD}" ]; then
 	env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes ${PKG_CMD} -r ${BASE_DIR} install pkg
 	[ -x ${BASE_DIR}/usr/local/sbin/pkg ] && ${CP_CMD} -a ${BASE_DIR}/usr/local/sbin/pkg ${BASE_DIR}/usr/sbin/
 	[ -x ${BASE_DIR}/usr/local/sbin/pkg-static ] && ${CP_CMD} -a ${BASE_DIR}/usr/local/sbin/pkg-static ${BASE_DIR}/usr/sbin/
-	env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes ${PKG_CMD} -r ${BASE_DIR} remove -f pkg
+	#env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes ${PKG_CMD} -r ${BASE_DIR} remove -f pkg
 else
 	echo "No such pkg executable for bootstrap: [${PKG_CMD}]"
 fi
@@ -268,6 +278,8 @@ baseelf=$( ${miscdir}/elf_tables --ver ${BASE_DIR}/bin/sh 2>/dev/null )
 
 [ -z "${baseelf}" ] && baseelf="0"
 [ -z "${destdir}" ] && register_base arch=${arch} ver=${ver} target_arch="${target_arch}" source="install-pkg-world" auto_baseupdate=0 ${_basename_args}
+
+preparebase dst=${BASE_DIR} emulator=${emulator} qemu="${qemu}" init_freebsd_pkg=0
 
 ${RM_CMD} -f ${BASE_DIR_LOCKFILE}
 
