install-pkg-world: wip

diff --git a/system/install-pkg-world b/system/install-pkg-world
--- a/system/install-pkg-world
+++ b/system/install-pkg-world
@@ -103,20 +103,21 @@ set -o errexit
 cbsdlogger NOTICE ${CBSD_APP}: install-pkg-world started: ${MAKE_CMD} -C ${SRC_DIR} installworld DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
 
 ${MKDIR_CMD} -p ${BASE_DIR}/usr/share/keys/
-/usr/local/bin/rsync -avz /usr/share/keys/ ${BASE_DIR}/usr/share/keys/
+${RSYNC_CMD} -avz /usr/share/keys/ ${BASE_DIR}/usr/share/keys/
 
 readconf ${platform}-base_in_pkg.conf
 readconf ${platform}-base_in_pkg-${ver}.conf
 
 # we need to use system/global path
 [ ! -d ${BASE_DIR}/etc/pkg ] && ${MKDIR_CMD} -p ${BASE_DIR}/etc/pkg
+${ECHO} "${N1_COLOR}Generate pkg.conf for base-in-packages v${ver}: ${N2_COLOR}${BASE_DIR}/etc/pkg/base-in-pkg.conf${N0_COLOR}"
 ${CAT_CMD} > ${BASE_DIR}/etc/pkg/base-in-pkg.conf <<EOF
-base-in-pkg: {
+cbsd-base-in-pkg: {
 	conservative_upgrade: no,
 	priority: 10
 	url: "${base_in_pkg_repo_url}",
 	mirror_type: "none",
-	enaled: yes
+	enabled: yes
 }
 EOF
 
@@ -127,11 +128,30 @@ nameserver 8.8.8.8              # CBSD makeresolv function
 nameserver 8.8.4.4              # CBSD makeresolv function
 EOF
 
-env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -r ${BASE_DIR} update
-env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -r ${BASE_DIR} install -y FreeBSD-runtime
-env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -r ${BASE_DIR} install -y ${base_in_pkg_list_active}
+#env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -C /usr/jails/basejail/base_amd64_amd64_14.0/etc/pkg/base-in-pkg.conf -R /usr/jails/basejail/base_amd64_amd64_14.0/etc/pkg  update -f -r LOL
 
-${RM_CMD} -f ${BASE_DIR}/usr/local/etc/pkg/repos/pkg.convectix.com.conf
+echo "env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} update -f -r cbsd-base-in-pkg"
+env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg ${PKG_CMD} -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} update -f -r cbsd-base-in-pkg
+ret=$?
+if [ ${ret} -ne 0 ]; then
+	err ${ret} "pkg failed: ${ret}"
+fi
+
+echo "env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} -r ${BASE_DIR} install -y -r cbsd-base-in-pkg FreeBSD-runtime"
+env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} -r ${BASE_DIR} install -y -r cbsd-base-in-pkg FreeBSD-runtime
+ret=$?
+if [ ${ret} -ne 0 ]; then
+	err ${ret} "pkg failed: ${ret}"
+fi
+
+echo "env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} install -y -r cbsd-base-in-pkg ${base_in_pkg_list_active}"
+env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} install -y -r cbsd-base-in-pkg ${base_in_pkg_list_active}
+ret=$?
+if [ ${ret} -ne 0 ]; then
+	err ${ret} "pkg failed: ${ret}"
+fi
+
+## ABI!!
 ${CP_CMD} -a /usr/sbin/pkg ${BASE_DIR}/usr/sbin/
 
 # not in PKG ?
@@ -146,20 +166,24 @@ for i in /etc/mail /boot; do
 	[ ! -d ${BASE_DIR}${i} ] && ${MKDIR_CMD} -p ${BASE_DIR}${i}
 done
 
-if [ "${platform}" = "DragonFly" ]; then
-	cbsdlogger NOTICE ${CBSD_APP}: distribution started: ${MAKE_CMD} -C ${SRC_DIR}/etc distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
-	${MAKE_CMD} -C ${SRC_DIR}/etc distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
-	cbsdlogger NOTICE ${CBSD_APP}: distribution ended: ${MAKE_CMD} -C ${SRC_DIR}/etc distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
-else
-	cbsdlogger NOTICE ${CBSD_APP}: distribution started: ${MAKE_CMD} -C ${SRC_DIR} distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
-	${MAKE_CMD} -C ${SRC_DIR} distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
-	cbsdlogger NOTICE ${CBSD_APP}: distribution ended: ${MAKE_CMD} -C ${SRC_DIR} distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
-fi
+#if [ "${platform}" = "DragonFly" ]; then
+#	cbsdlogger NOTICE ${CBSD_APP}: distribution started: ${MAKE_CMD} -C ${SRC_DIR}/etc distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
+#	${MAKE_CMD} -C ${SRC_DIR}/etc distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
+#	cbsdlogger NOTICE ${CBSD_APP}: distribution ended: ${MAKE_CMD} -C ${SRC_DIR}/etc distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
+#else
+#	cbsdlogger NOTICE ${CBSD_APP}: distribution started: ${MAKE_CMD} -C ${SRC_DIR} distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
+#	${MAKE_CMD} -C ${SRC_DIR} distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
+#	cbsdlogger NOTICE ${CBSD_APP}: distribution ended: ${MAKE_CMD} -C ${SRC_DIR} distribution DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
+#fi
 
 set +o errexit
 
 [ $? -ne 0 ] && err 1 "${N1_COLOR}Installworld error${N0_COLOR}"
 [ -n "${oqemu}" ] && qemu="${oqemu}"
+# The most recent versions of packages are already installed
+#Bootstrapping pkg from https://pkg.convectix.com/FreeBSD:14:amd64/latest, please wait...
+#pkg: Error fetching https://pkg.convectix.com/FreeBSD:14:amd64/latest/Latest/pkg.txz: Not Found
+#A pre-built version of pkg could not be found for your system.
 preparebase dst=${BASE_DIR} emulator=${emulator} qemu="${qemu}"
 
 [ ! -f ${BASE_DIR}/bin/sh ] && err 1 "${N1_COLOR}No such /bin/sh in ${BASE_DIR}. Try to rebuild world${N0_COLOR}"
