install-pkg-world: wip

diff --git a/system/install-pkg-world b/system/install-pkg-world
--- a/system/install-pkg-world
+++ b/system/install-pkg-world
@@ -69,6 +69,8 @@ fi
 
 #[ -x "${BASE_DIR}/bin/sh" ] &&  err 1 "${N1_COLOR}${CBSD_APP}: not empty, base already exist: ${N2_COLOR}${BASE_DIR}${N0_COLOR}"
 
+[ -z "${BASE_DIR}" ] && err 1 "${N1_COLOR}Empty BASE_DIR${N0_COLOR}"
+
 [ ! -d "${BASE_DIR}" ] && ${MKDIR_CMD} -p ${BASE_DIR}
 makelock ${BASE_DIR_LOCKFILE} "cleanup_bases"
 
@@ -102,11 +104,49 @@ fi
 set -o errexit
 cbsdlogger NOTICE ${CBSD_APP}: install-pkg-world started: ${MAKE_CMD} -C ${SRC_DIR} installworld DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
 
-${MKDIR_CMD} -p ${BASE_DIR}/usr/share/keys/
-${RSYNC_CMD} -avz /usr/share/keys/ ${BASE_DIR}/usr/share/keys/
-
 readconf ${platform}-base_in_pkg.conf
 readconf ${platform}-base_in_pkg-${ver}.conf
+
+# We need distribution first due to valid CRC sum for config via PKG
+${ECHO} "${N1_COLOR}Fetching distribution archive...${N0_COLOR}"
+
+major_ver=${ver%%.*}
+
+ABI="${platform}:${major_ver}:${arch}"
+eval base_in_pkg_repo_url="${base_in_pkg_repo_url}"
+
+${FETCH_CMD} -o /tmp/distribution_${arch}_${target_arch}_${ver}.tgz  ${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz
+ret=$?
+if [ ${ret} -ne 0 ]; then
+	err 1 "${N1_COLOR}fetch distribution archive failed: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+fi
+
+if [ ! -r /tmp/distribution_${arch}_${target_arch}_${ver}.tgz ]; then
+	err 1 "${N1_COLOR}fetch distribution archive failed: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+fi
+
+cd /tmp
+${TAR_CMD} xfz distribution_${arch}_${target_arch}_${ver}.tgz
+ret=$?
+if [ ${ret} -ne 0 ]; then
+	${RM_CMD} -f distribution_${arch}_${target_arch}_${ver}.tgz
+	err 1 "${N1_COLOR}unable to extract archive into /tmp: ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+fi
+
+${RM_CMD} -f distribution_${arch}_${target_arch}_${ver}.tgz
+
+if [ ! -r /tmp/distribution_${arch}_${target_arch}_${ver}/COPYRIGHT ]; then
+	[ -d /tmp/distribution_${arch}_${target_arch}_${ver} ] && ${RM_CMD} -rf /tmp/distribution_${arch}_${target_arch}_${ver}
+	err 1 "${N1_COLOR}fetch/extract distribution archive failed: no such /COPYRIGHT file in ${N2_COLOR}${base_in_pkg_repo_url}/distribution_${arch}_${target_arch}_${ver}.tgz${N0_COLOR}"
+fi
+
+# to log?
+${RSYNC_CMD} -avz /tmp/distribution_${arch}_${target_arch}_${ver}/ ${BASE_DIR}/ > /dev/null 2>&1
+[ -d /tmp/distribution_${arch}_${target_arch}_${ver} ] && ${RM_CMD} -rf /tmp/distribution_${arch}_${target_arch}_${ver}
+
+# Setup pkg
+${MKDIR_CMD} -p ${BASE_DIR}/usr/share/keys/
+${RSYNC_CMD} -avz /usr/share/keys/ ${BASE_DIR}/usr/share/keys/
 
 # we need to use system/global path
 [ ! -d ${BASE_DIR}/etc/pkg ] && ${MKDIR_CMD} -p ${BASE_DIR}/etc/pkg
@@ -127,8 +167,6 @@ ${CAT_CMD} > ${BASE_DIR}/etc/resolv.conf <<EOF
 nameserver 8.8.8.8              # CBSD makeresolv function
 nameserver 8.8.4.4              # CBSD makeresolv function
 EOF
-
-#env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -C /usr/jails/basejail/base_amd64_amd64_14.0/etc/pkg/base-in-pkg.conf -R /usr/jails/basejail/base_amd64_amd64_14.0/etc/pkg  update -f -r LOL
 
 echo "env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} update -f -r cbsd-base-in-pkg"
 env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg ${PKG_CMD} -R ${BASE_DIR}/etc/pkg -r ${BASE_DIR} update -f -r cbsd-base-in-pkg
@@ -151,11 +189,25 @@ if [ ${ret} -ne 0 ]; then
 	err ${ret} "pkg failed: ${ret}"
 fi
 
-## ABI!!
-${CP_CMD} -a /usr/sbin/pkg ${BASE_DIR}/usr/sbin/
+# Remove .pkgsave file
+${FIND_CMD} ${BASE_DIR}/ -type f -name *.pkgsave -delete
+
+# Remove base-in-packages repo
+${RM_CMD} -f ${BASE_DIR}/etc/pkg/base-in-pkg.conf
+
+## ABI?
+[ -z "${PKG_CMD}" ] && PKG_CMD="/usr/sbin/pkg"
+if [ -x "${PKG_CMD}" ]; then
+	env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes ${PKG_CMD} -r ${BASE_DIR} install pkg
+	[ -x ${BASE_DIR}/usr/local/sbin/pkg ] && ${CP_CMD} -a ${BASE_DIR}/usr/local/sbin/pkg ${BASE_DIR}/usr/sbin/
+	[ -x ${BASE_DIR}/usr/local/sbin/pkg-static ] && ${CP_CMD} -a ${BASE_DIR}/usr/local/sbin/pkg-static ${BASE_DIR}/usr/sbin/
+	env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes ${PKG_CMD} -r ${BASE_DIR} remove -f pkg
+else
+	echo "No such pkg executable for bootstrap: [${PKG_CMD}]"
+fi
 
 # not in PKG ?
-${CP_CMD} -a /sbin/rcorder ${BASE_DIR}/sbin/
+#${CP_CMD} -a /sbin/rcorder ${BASE_DIR}/sbin/
 
 #${MAKE_CMD} -C ${SRC_DIR} installworld DESTDIR=${BASE_DIR} TARGET=${build_arch} TARGET_ARCH=${build_target_arch}
 
@@ -180,11 +232,12 @@ set +o errexit
 
 [ $? -ne 0 ] && err 1 "${N1_COLOR}Installworld error${N0_COLOR}"
 [ -n "${oqemu}" ] && qemu="${oqemu}"
-# The most recent versions of packages are already installed
-#Bootstrapping pkg from https://pkg.convectix.com/FreeBSD:14:amd64/latest, please wait...
-#pkg: Error fetching https://pkg.convectix.com/FreeBSD:14:amd64/latest/Latest/pkg.txz: Not Found
-#A pre-built version of pkg could not be found for your system.
-preparebase dst=${BASE_DIR} emulator=${emulator} qemu="${qemu}"
+preparebase dst=${BASE_DIR} emulator=${emulator} qemu="${qemu}" init_freebsd_pkg=0
+
+# Purge/Prune PKG cache
+[ -d ${BASE_DIR}/var/cache/pkg ] && ${FIND_CMD} ${BASE_DIR}/var/cache/pkg/ -depth 1 -maxdepth 1 -delete
+#echo "env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -r ${BASE_DIR} clean all"
+#env SIGNATURE_TYPE=none ASSUME_ALWAYS_YES=yes /usr/sbin/pkg -r ${BASE_DIR} clean all
 
 [ ! -f ${BASE_DIR}/bin/sh ] && err 1 "${N1_COLOR}No such /bin/sh in ${BASE_DIR}. Try to rebuild world${N0_COLOR}"
 
