WIP: getting rid of /usr/local/cbsd hardcode

diff --git a/system/module b/system/module
--- a/system/module
+++ b/system/module
@@ -12,7 +12,7 @@ rewrite any CBSD command (for example: 'jstart', 'bdestroy') on your own favorit
 and more convenient for you. The 'cbsd module' script allows you to manage ready-made 
 3rd-party modules through Git.
 
- All modules stored in the /usr/local/cbsd/modules/ directory, but require manual 
+ All modules stored in the ${CIX_DISTDIR}/modules/ directory, but require manual 
 activation through ~cbsd/etc/modules.conf file.
 
  To work the script, you need an executable 'git; file in the PATH.
@@ -54,11 +54,11 @@ install_module()
 	local _metadata_tmp="/tmp/cbsd_module.$$"
 
 	# fetch metadata via unprivilege user
-	${TIMEOUT_CMD} -s KILL 6 ${SUDO_CMD} -u nobody /usr/local/cbsd/bin/cfetch -u ${_gh_raw_content_prefix}-${data}/${version}/metadata.conf -o ${_metadata_tmp}
+	${TIMEOUT_CMD} -s KILL 6 ${SUDO_CMD} -u nobody ${CIX_DISTDIR}/bin/cfetch -u ${_gh_raw_content_prefix}-${data}/${version}/metadata.conf -o ${_metadata_tmp}
 	_ret=$?
 
 	if [ ${_ret} -ne 0 ]; then
-		${ECHO} "${N1_COLOR}${CIX_APP}: unable to fetch metadata via: /usr/local/cbsd/bin/cfetch -u ${N2_COLOR}${_gh_raw_content_prefix}-${data}/${version}/metadata.conf${N0_COLOR}" 1>&2
+		${ECHO} "${N1_COLOR}${CIX_APP}: unable to fetch metadata via: ${CIX_DISTDIR}/bin/cfetch -u ${N2_COLOR}${_gh_raw_content_prefix}-${data}/${version}/metadata.conf${N0_COLOR}" 1>&2
 		[ -r ${_metadata_tmp} ] && ${RM_CMD} ${_metadata_tmp}
 		return 1
 	fi
@@ -76,8 +76,8 @@ install_module()
 
 	# we do not accept content in places other than CBSD, test it
 	_prefix23=$( substr --pos=0 --len=23 --str="${MODULE_DIR}" )
-	if [ "${_prefix23}" != "/usr/local/cbsd/modules" ]; then
-		${ECHO} "${N1_COLOR}${CIX_APP}: MODULE_DIR != /usr/local/cbsd/modules in manifest: ${N2_COLOR}${MODULE_DIR}${N0_COLOR}" 1>&2
+	if [ "${_prefix23}" != "${CIX_DISTDIR}/modules" ]; then
+		${ECHO} "${N1_COLOR}${CIX_APP}: MODULE_DIR != ${CIX_DISTDIR}/modules in manifest: ${N2_COLOR}${MODULE_DIR}${N0_COLOR}" 1>&2
 		return 1
 	fi
 
