style

diff --git a/system/preparebase b/system/preparebase
--- a/system/preparebase
+++ b/system/preparebase
@@ -17,7 +17,7 @@ ${H3_COLOR}Options${N0_COLOR}:
  ${N2_COLOR}init_freebsd_pkg     - init/bootstrap pkg(8) tools, 1 - yes (default;
 ${H3_COLOR}Examples${N0_COLOR}:
 
- # cbsd preparebase dst=/usr/jails/basejail/base_amd64_amd64_14.0
+ # cbsd preparebase dst=/usr/jails/basejail/base_amd64_amd64_15.1
 
 "
 
@@ -369,14 +369,15 @@ EOF
 				${UMOUNT_CMD} ${dst}/dev
 				;;
 			*)
-				${miscdir}/mountpoint ${dst}/dev || ${MOUNT_CMD} -t devfs devfs ${dst}/dev
-#env ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes timeout 30 ${_pkg_bin} bootstrap -y -f || true
-				timeout 30 ${CHROOT_CMD} ${dst} /bin/sh <<EOF
+				if [ "${qemu}" != "1" ]; then
+					${miscdir}/mountpoint ${dst}/dev || ${MOUNT_CMD} -t devfs devfs ${dst}/dev
+					timeout 30 ${CHROOT_CMD} ${dst} /bin/sh <<________________________________________EOF
 export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 export ASSUME_ALWAYS_YES=yes SIGNATURE_TYPE=none IGNORE_OSVERSION=yes
 [ -x "${_pkg_bin}" ] && ${_pkg_bin} update -f || true
-EOF
-				${UMOUNT_CMD} ${dst}/dev
+________________________________________EOF
+					${UMOUNT_CMD} ${dst}/dev
+				fi
 				;;
 		esac
 
@@ -394,20 +395,22 @@ EOF
 	fi
 fi
 
+
 if [ "${qemu}" = "1" ]; then
 	# for qemu user mode
 	[ -z "${emulator}" ] && exit 0
 	[ "${emulator}" = "jail" -o "${emulator}" = "bhyve" ] && exit 0
-
-	${ECHO} " * Copying emulator to /bin" 1>&2
 	. ${subrdir}/emulator.subr
+
 	init_usermode_emul
+
+	${ECHO} " * Apply emulator for ${dst}/bin: ${emultest}" 1>&2
 
 	[ ! -d "${dst}/bin" ] && ${MKDIR_CMD} -m 0755 -p ${dst}/bin
 	[ ! -r ${emultest} ] && err 1 "${N1_COLOR}${CIX_APP}: no such emulator: ${N2_COLOR}${emultest}${N0_COLOR}"
 	capture emulfile ${BASENAME_CMD} ${emultest}
 	[ ! -r ${dst}/bin/${emulfile} ] && ${CP_CMD} -a ${emultest} ${dst}/bin/
-	[ ! -r ${dst}/bin/${emulfile} ] && err 1 "${N1_COLOR}${CIX_APP}: unable to copy: ${N2_COLOR}cp ${emultest} ${dst}/bin/${N0_COLOR}"
+	[ ! -r ${dst}/bin/${emulfile} ] && err 1 "${N1_COLOR}${CIX_APP}: unable to copy: ${N2_COLOR}${CP_CMD} -a ${emultest} ${dst}/bin/${N0_COLOR}"
 fi
 
 exit 0
