qemu: use /bin location instead of /usr/local/bin

diff --git a/system/preparebase b/system/preparebase
--- a/system/preparebase
+++ b/system/preparebase
@@ -28,16 +28,13 @@ ADDHELP="emulator - copy qemu usermode files for chrooting, eg: emulator=qemu-ar
 [ -z "${emulator}" ] && exit 0
 [ "${emulator}" = "jail" -o "${emulator}" = "bhyve" ] && exit 0
 
-echo " * Copying emulator to /bin"
+echo " * Copying emulator to /bin" 1>&2
 . ${distdir}/emulator.subr
 init_usermode_emul
 [ ! -d "${dst}/bin" ] && ${MKDIR_CMD} -m 0755 -p ${dst}/bin
-${CP_CMD} -a ${emultest} ${dst}/bin/
-[ ! -d ${dst}/usr/local/bin ] && ${MKDIR_CMD} -p -m 0755 ${dst}/usr/local/bin
-
-if [ -n "${path}" -a -d "${path}" ]; then
-	[ ! -d ${path}/usr/local/bin ] && ${MKDIR_CMD} -p -m 0755 ${path}/usr/local/bin
-	cd ${path}/usr/local/bin && ${LN_CMD} -sf /bin/${emulator} ${emulator}
-fi
+[ ! -r ${emultest} ] && err 1 "${N1_COLOR}${CBSD_APP}: no such emulator: ${N2_COLOR}${emultest}${N0_COLOR}"
+emulfile=$( ${BASENAME_CMD} ${emultest} )
+[ ! -r ${dst}/bin/${emulfile} ] && ${CP_CMD} -a ${emultest} ${dst}/bin/
+[ ! -r ${dst}/bin/${emulfile} ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to copy: ${N2_COLOR}cp ${emultest} ${dst}/bin/${N0_COLOR}"
 
 exit 0
