switch srcup for FreeBSD to git

diff --git a/system/srcup b/system/srcup
--- a/system/srcup
+++ b/system/srcup
@@ -102,6 +102,7 @@ svn_checkout()
 		nice -n 19 ${IDPRIO_CMD} 29 ${SCM} cleanup
 	fi
 	${ECHO} "${N1_COLOR}Processing svn update...${N0_COLOR}"
+	[ -z "${rev}" ] && rev="head"
 	cbsdlogger NOTICE ${CBSD_APP}: processing svn update: ${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}
 	echo "${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}"
 	nice -n 19 ${IDPRIO_CMD} 29 ${SCM} checkout -r ${rev} ${SCM_URL} ${_srcdir}
@@ -110,8 +111,8 @@ svn_checkout()
 
 git_checkout()
 {
-	local _depth
-	local _ret=0
+	local _depth _remotes _origin
+	local _ret=0 _p2 _branch
 
 	[ "${depth}" != "0" ] && _depth="${depth}"
 
@@ -132,15 +133,27 @@ git_checkout()
 		set -o xtrace
 		cd ${dst}
 		nice -n 19 ${IDPRIO_CMD} 29 ${SCM} reset --hard				# reset to source default
+
+		_remotes="remotes/"
+		_origin="origin/"
+
+		# remove 'remotes/' + 'origin/'
+		_p2=${SCM_GIT_BRANCH##*${_remotes}}
+		_branch=${_p2##*${_origin}}
+
+		[ -z "${_branch}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: empty branch var SCM_GIT_BRANCH${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CBSD_APP} swith to branch: ${N2_COLOR}${_branch}${N0_COLOR}"
+
+		nice -n 19 ${IDPRIO_CMD} 29 ${SCM} pull ${git_pull_flags}
+		_ret=$?
+
 		if [ -n "${rev}" ]; then
 			nice -n 19 ${IDPRIO_CMD} 29 ${SCM} checkout ${rev}
 			_ret=$?
 		else
-			nice -n 19 ${IDPRIO_CMD} 29 ${SCM} checkout ${SCM_GIT_BRANCH}
+			nice -n 19 ${IDPRIO_CMD} 29 ${SCM} checkout ${_branch}
 			_ret=$?
 		fi
-		nice -n 19 ${IDPRIO_CMD} 29 ${SCM} pull ${git_pull_flags}
-		_ret=$?
 		set +o xtrace
 		# restore CBSD PATH
 		export PATH="${CBSDPATH}"
@@ -269,10 +282,10 @@ case "${checkout_method}" in
 	git*)
 		st_time=$( ${DATE_CMD} +%s )
 
-		[ ! -r ${sharedir}/${platform}-git_branches.conf ] && err 1 "${N1_COLOR}No ${sharedir}/${platform}-git_branches.conf for git branch map${N0_COLOR}"
-		. ${sharedir}/${platform}-git_branches.conf
-		[ -z "${SCM_GIT_BRANCH}" ] && SCM_GIT_BRANCH=$( init_git_branch )
-		[ -z "${SCM_GIT_BRANCH}" ] && err 1 "${N1_COLOR}no SCM_GIT_BRANCH var${N0_COLOR}"
+#		[ ! -r ${sharedir}/${platform}-git_branches.conf ] && err 1 "${N1_COLOR}No ${sharedir}/${platform}-git_branches.conf for git branch map${N0_COLOR}"
+#		. ${sharedir}/${platform}-git_branches.conf
+#		[ -z "${SCM_GIT_BRANCH}" ] && SCM_GIT_BRANCH=$( init_git_branch )
+#		[ -z "${SCM_GIT_BRANCH}" ] && err 1 "${N1_COLOR}no SCM_GIT_BRANCH var${N0_COLOR}"
 		init_git
 		# conditional registration:
 		init_scm_and_version
