Multiple NIC support for bhyve: work in progress...

diff --git a/nodectl/node b/nodectl/node
--- a/nodectl/node
+++ b/nodectl/node
@@ -44,6 +44,8 @@ getpw()
 
 nodeadd()
 {
+	local _res
+
 	[ -z "${node}" ] && err 1 "${MAGENTA}Empty node${NORMAL}"
 	[ -z "${port}" ] && port=22222
 	[ -z "${pw}" ] && getpw
@@ -76,7 +78,9 @@ nodeadd()
 	MD5NAME=$( /sbin/md5 -qs ${NODENAME} )
 	nodeaddkey md5name=${MD5NAME} ip=${node} port=${port} pw=${pw} > $DEBLOG 2>&1
 
-	case $? in
+	_res=$?
+
+	case ${_res} in
 		0)
 			${ECHO} "${MAGENTA}Added successfull: ${GREEN}${node}${NORMAL}"
 			LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
@@ -95,18 +99,19 @@ nodeadd()
 			fi
 			idle_update ${NODENAME}
 			retrinv node=${NODENAME} tryoffline=1
+			return ${_res}
 			;;
 		1)
 			cat ${DEBLOG}
-			err 1 "${MAGENTA}Error: Bad password${NORMAL}"
+			err ${_res} "${MAGENTA}Error: Bad password${NORMAL}"
 			;;
 		2)
 			[ -f "${DEBLOG}" ] && cat ${DEBLOG}
-			err 1 "${MAGENTA}Error: No key found or wrong hostname. Make initenv on remote machine${NORMAL}"
+			err ${_res} "${MAGENTA}Error: No key found or wrong hostname. Make initenv on remote machine${NORMAL}"
 			;;
 		*)
 			cat ${DEBLOG}
-			err 1 "${MAGENTA}Error: Unkown error${NORMAL}"
+			err ${_res} "${MAGENTA}Error: Unkown error${NORMAL}"
 			;;
 	esac
 }
