bhyve: add dsk_zfs_guid field

diff --git a/tools/bhyve-dsk b/tools/bhyve-dsk
--- a/tools/bhyve-dsk
+++ b/tools/bhyve-dsk
@@ -1,7 +1,7 @@
 #!/usr/local/bin/cbsd
 #v12.0.6
 MYARG="mode"
-MYOPTARG="jname controller dsk dsk_size bootable dsk_sectorsize"
+MYOPTARG="jname controller dsk dsk_size bootable dsk_sectorsize display header"
 MYDESC="Manage bhyve ahci/virtio disk"
 CBSDMODULE="bhyve"
 EXTHELP="wf_bhyve"
@@ -9,9 +9,15 @@ ADDHELP="mode=attach,detach,remove,list,modify\n\
   - attach - create and attach new disk\n\
   - detach - detach disk from controller (without removing dsk)\n\
   - delete - detach and remove disk\n\
-  - modify - modify disk properties (e.g: bootable=)\n\
+  - modify - modify disk properties (e.g: bootable=, dsk_sectorsize=)\n\
  modify properties:\n\
-  - bootable - set bootable flag (1 - true, - false)\n"
+  - bootable - set bootable flag (1 - true, - false)\n\
+  - dsk_sectorsize - set sectorsize (e.g: 512, 4096, 512/4096)\n\
+  - dsk_zfs_guid - can be: 'auto'\n\
+ mode=list properties:\n\
+  header=0 don't print header\n\
+  display= list by comma for column. Default: jname,dsk_controller,dsk_path,dsk_size,dsk_sectorsize,bootable\n\
+    also available: dsk_zfs_guid\n"
 
 . ${subr}
 . ${system}
@@ -19,7 +25,7 @@ ADDHELP="mode=attach,detach,remove,list,modify\n\
 bootable=
 . ${cbsdinit}
 
-available_properties="bootable"
+available_properties="bootable dsk_sectorsize dsk_zfs_guid"
 
 . ${distdir}/bhyve.subr
 . ${distdir}/virtual.subr
@@ -136,6 +142,61 @@ dsk_modify_bootable()
 	return 0
 }
 
+dsk_modify_dsk_sectorsize()
+{
+	local _res _old_val
+
+	for i in jname controller dsk; do
+		_val=
+		eval _val="\$$i"
+		[ -z "${_val}" ] && err 1 "${N1_COLOR}dsk_modify_dsk_sectorsize error: ${N2_COLOR}${i}= ${N1_COLOR}is mandatory${N0_COLOR}"
+	done
+
+	[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && err 1 "${N1_COLOR}No such database: ${N2_COLOR}${jailsysdir}/${jname}/local.sqlite${N0_COLOR}"
+
+	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_sectorsize FROM bhyvedsk WHERE dsk_controller=\"${controller}\" AND dsk_path=\"${dsk}\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
+	[ -z "${_old_val}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to get current dsk_sectorsize values for: dsk_controller=${N2_COLOR}${controller}${N1_COLOR} AND dsk_path=${N2_COLOR}${dsk}${N0_COLOR}"
+	[ "${_old_val}" = "${dsk_sectorsize}" ] && return 0
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_sectorsize=\"${dsk_sectorsize}\" WHERE dsk_controller=\"${controller}\" AND dsk_path=\"${dsk}\"
+
+	cbsdlogger NOTICE "${CBSD_APP}: modify sectorsize ${_old_val} -> ${dsk_sectorsize} (controller: ${controller}, dsk: ${dsk})"
+	${ECHO} "${N1_COLOR}dsk_sectorsize: ${N2_COLOR}changed${N0_COLOR}"
+	return 0
+}
+
+dsk_modify_dsk_zfs_guid()
+{
+	local _res _old_val tmp_zvol= _is_zvol
+	local _dsk_fullpath _zvol_pref= _ret
+
+	[ ${zfsfeat} -ne 1 ] && err 1 "${N1_COLOR}zfsfeat disabled${N0_COLOR}"
+	[ "${dsk_zfs_guid}" != "auto" ] && err 1 "${N1_COLOR}dsk_zfs_guid valid values: 'auto'${N0_COLOR}"
+
+	for i in jname controller dsk; do
+		_val=
+		eval _val="\$$i"
+		[ -z "${_val}" ] && err 1 "${N1_COLOR}dsk_modify_dsk_zfs_guid error: ${N2_COLOR}${i}= ${N1_COLOR}is mandatory${N0_COLOR}"
+	done
+
+	[ ! -r ${jailsysdir}/${jname}/local.sqlite ] && err 1 "${N1_COLOR}No such database: ${N2_COLOR}${jailsysdir}/${jname}/local.sqlite${N0_COLOR}"
+
+	_old_val=$( cbsdsqlro ${jailsysdir}/${jname}/local.sqlite SELECT dsk_zfs_guid FROM bhyvedsk WHERE dsk_controller=\"${controller}\" AND dsk_path=\"${dsk}\" LIMIT 1 | /usr/bin/awk '{printf $1}' )
+	[ -z "${_old_val}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to get current dsk_zfs_guid values for: dsk_controller=${N2_COLOR}${controller}${N1_COLOR} AND dsk_path=${N2_COLOR}${dsk}${N0_COLOR}"
+
+	_dsk_fullpath="${jaildatadir}/${jname}-${jaildatapref}/${dsk}"
+
+	. ${zfstool}
+
+	_res=$( get_dsk_zfs_guid -p ${_dsk_fullpath} )
+	_ret=$?
+	[ ${_ret} -ne 0 ] && err 0 "${N1_COLOR}skipp dsk_modify_dsk_zfs_guid error: unable to determine guid for: ${N2_COLOR}${_dsk_fullpath}${N0_COLOR}"
+	[ -z "${_res}" ] && err 0 "${N1_COLOR}skipp dsk_modify_dsk_zfs_guid error: unable to determine guid for: ${N2_COLOR}${_is_zvol}${N0_COLOR}"
+	[ "${_old_val}" = "${_res}" ] && return 0
+	cbsdsqlrw ${jailsysdir}/${jname}/local.sqlite UPDATE bhyvedsk SET dsk_zfs_guid=\"${_res}\" WHERE dsk_controller=\"${controller}\" AND dsk_path=\"${dsk}\"
+	cbsdlogger NOTICE "${CBSD_APP}: modify dsk_zfs_guid ${_old_val} -> ${dsk_sectorsize} (controller: ${controller}, dsk: ${dsk})"
+	${ECHO} "${N1_COLOR}dsk_zfs_guid: ${N2_COLOR}changed${N0_COLOR}"
+	return 0
+}
 
 dsk_modify()
 {
@@ -154,8 +215,6 @@ dsk_modify()
 	[ ${_prop_num} -eq 0 ] && ${ECHO} "${N1_COLOR}available properties: ${N2_COLOR}${available_properties}${N0_COLOR}"
 }
 
-
-
 case "${mode}" in
 	attach)
 		dsk_attach
@@ -167,7 +226,9 @@ case "${mode}" in
 		dsk_detach
 		;;
 	list)
-		bhyve-dsk-list
+		[ -z "${display}" ] && display="jname,dsk_controller,dsk_path,dsk_size,dsk_sectorsize,bootable"
+		[ -z "${header}" ] && header="1"
+		bhyve-dsk-list header="${header}" display="${display}"
 		;;
 	modify)
 		dsk_modify
