Welcome to ArchBSD bhyve profile; normalize_path func for relative paths in jconf

diff --git a/tools/cpr b/tools/cpr
--- a/tools/cpr
+++ b/tools/cpr
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v10.0.4
+#v10.0.7
 globalconf="${workdir}/cbsd.conf"
 CBSDMODULE="cpr"
 MYARG="cdir pkglist dstdir"
@@ -37,46 +37,46 @@ init $*
 
 umount_temp_dirs()
 {
-    # when error before cdir, we do not have any mounts by scripts
-    [ -z "${cdir}" -o ! -d "${cdir}" ] && return 0
+	# when error before cdir, we do not have any mounts by scripts
+	[ -z "${cdir}" -o ! -d "${cdir}" ] && return 0
 
-    umount_cdirs ${cdir}
+	umount_cdirs ${cdir}
 
-    #destroy md disk when he used
-    if [ "${CCACHEFS}" = "mdfs" -a -n "${MDDEV}" ]; then
-	${ECHO} "${MAGENTA}Destroy md drive: ${GREEN}${MDDEV}${NORMAL}"
-	mdconfig -d -u ${MDDEV}
-    fi
+	#destroy md disk when he used
+	if [ "${CCACHEFS}" = "mdfs" -a -n "${MDDEV}" ]; then
+		${ECHO} "${MAGENTA}Destroy md drive: ${GREEN}${MDDEV}${NORMAL}"
+		mdconfig -d -u ${MDDEV}
+	fi
 }
 
 mount_temp_dirs()
 {
-    local _tmpfstab="${ftmpdir}/mount_temp_dirs.$$"
-    set +e
-    kldstat -qm linprocfs || kldload linprocfs
-    set -e
+	local _tmpfstab="${ftmpdir}/mount_temp_dirs.$$"
+	set +e
+	kldstat -qm linprocfs || kldload linprocfs
+	set -e
 
-    TRAP="${TRAP} rm -f ${_tmpfstab};"
-    trap "${TRAP};" HUP INT ABRT BUS TERM EXIT
+	TRAP="${TRAP} rm -f ${_tmpfstab};"
+	trap "${TRAP};" HUP INT ABRT BUS TERM EXIT
 
-    cat > ${_tmpfstab} << EOF
+	cat > ${_tmpfstab} << EOF
 devfs /dev devfs rw 0 0
 procfs /proc procfs rw 0 0
 linprocfs /usr/compat/linux/proc linprocfs rw 0 0
 EOF
 
-    [ -d "${SRC_DIR}" ] && echo "${SRC_DIR} /usr/src nullfs ro 0 0" >> ${_tmpfstab}
+	[ -d "${SRC_DIR}" ] && echo "${SRC_DIR} /usr/src nullfs ro 0 0" >> ${_tmpfstab}
 
-    if [ -z "${repoversion}" -o "${repoversion}" = "default" ]; then
-	PORTSCFG_SRC="/var/db/ports"
-	MYPKGDIR="${PKGDIRROOT}/default"
-    else
-	PORTSCFG_SRC="${dbdir}/ports-${repoversion}"
-	MYPKGDIR="${PKGDIRROOT}/${repoversion}"
-    fi
+	if [ -z "${repoversion}" -o "${repoversion}" = "default" ]; then
+		PORTSCFG_SRC="/var/db/ports"
+		MYPKGDIR="${PKGDIRROOT}/default"
+	else
+		PORTSCFG_SRC="${dbdir}/ports-${repoversion}"
+		MYPKGDIR="${PKGDIRROOT}/${repoversion}"
+	fi
 
-    [ ! -d "${PORTSCFG_SRC}" ] && mkdir -p ${PORTSCFG_SRC}
-    [ ! -d "${MYPKGDIR}" ] && mkdir -p ${MYPKGDIR}
+	[ ! -d "${PORTSCFG_SRC}" ] && mkdir -p ${PORTSCFG_SRC}
+	[ ! -d "${MYPKGDIR}" ] && mkdir -p ${MYPKGDIR}
 
     cat >> ${_tmpfstab} << EOF
 ${PORTSCFG_SRC} /var/db/ports nullfs rw 0 0
@@ -95,39 +95,34 @@ EOF
 	fi
     fi
 
-    [ -d "${KERNEL_DIR}" ] && echo "${KERNEL_DIR} /boot/kernel nullfs ro 0 0" >> ${_tmpfstab}
+	[ -d "${KERNEL_DIR}" ] && echo "${KERNEL_DIR} /boot/kernel nullfs ro 0 0" >> ${_tmpfstab}
 
-    cbsd mountfstab jroot=$cdir fstab=${_tmpfstab} jname="${jname}"
-    rm -f ${_tmpfstab}
+	cbsd mountfstab jroot=$cdir fstab=${_tmpfstab} jname="${jname}"
+	rm -f ${_tmpfstab}
 }
 
 
 prepare_chroot()
 {
-    ${ECHO} "${MAGENTA}Building packages... ${NORMAL}"
+	${ECHO} "${MAGENTA}Building packages... ${NORMAL}"
 
-NEEDEDPORTS="\
-/usr/ports/ports-mgmt/portmaster \
-/usr/ports/ports-mgmt/dialog4ports
-"
+	[ "$ccache" = "1" ] && NEEDEDPORTS="${NEEDEDPORTS} /usr/ports/devel/ccache"
+	[ "$distcc" = "1" ] && NEEDEDPORTS="/usr/ports/devel/distcc ${NEEDEDPORTS}"
+	export NEEDEDPORTS
 
-    [ "$ccache" = "1" ] && NEEDEDPORTS="${NEEDEDPORTS} /usr/ports/devel/ccache"
-    [ "$distcc" = "1" ] && NEEDEDPORTS="/usr/ports/devel/distcc ${NEEDEDPORTS}"
-    export NEEDEDPORTS
+	[ -n "${usegcc}" ] && export usegcc
+	[ -f "${makeconf}" ] && cp ${makeconf} ${cdir}/etc/make.conf
 
-    [ -n "${usegcc}" ] && export usegcc
-    [ -f "${makeconf}" ] && cp ${makeconf} ${cdir}/etc/make.conf
+	# remove default pkg.conf
+	rm -f ${cdir}/etc/pkg/*.conf
 
-    # remove default pkg.conf
-    rm -f ${cdir}/etc/pkg/*.conf
+	# make sure we have work dir in /tmp for parallel builds
+	[ $( grep ^WRKDIRPREFIX= ${cdir}/etc/make.conf|wc -l )  = 0 ] && echo WRKDIRPREFIX=/tmp >> ${cdir}/etc/make.conf
+	cp /etc/resolv.conf ${cdir}/etc
 
-    # make sure we have work dir in /tmp for parallel builds
-    [ `grep ^WRKDIRPREFIX= ${cdir}/etc/make.conf|wc -l` = 0 ] && echo WRKDIRPREFIX=/tmp >> ${cdir}/etc/make.conf
-    cp /etc/resolv.conf ${cdir}/etc
+	touch ${cdir}/etc/src.conf
 
-    touch ${cdir}/etc/src.conf
-
-    chroot $cdir /bin/sh << EOF
+	chroot $cdir /bin/sh << EOF
 service ldconfig start
 #env ASSUME_ALWAYS_YES=yes pkg > /dev/null 2>&1
 mv /etc/make.conf /tmp
@@ -139,29 +134,28 @@ pkg2ng
 find /tmp/usr/ports -type d -name work -exec rm -rf {} \; > /dev/null 2>&1
 
 if [ -n "\${usegcc}" ]; then
-    make -C \$usegcc install
-#    sysrc -f /etc/make.conf USE_GCC=YES
-    cp /etc/make.conf /tmp/mk.conf
-    grep -v USE_GCC /tmp/mk.conf > /etc/make.conf
-    echo USE_GCC=yes >> /etc/make.conf
+	make -C \$usegcc install
+	cp /etc/make.conf /tmp/mk.conf
+	grep -v USE_GCC /tmp/mk.conf > /etc/make.conf
+	echo USE_GCC=yes >> /etc/make.conf
 fi
 
 for i in \${NEEDEDPORTS}; do
-    if [ -f /tmp/buildcontinue ]; then
-	cd /tmp/packages
-	PORTNAME=\`make -C \$i -V PKGNAME\`
-        pkg info -e \$PORTNAME >/dev/null 2>&1 || {
-    	    [ -f \${PORTNAME}.txz ] && env ASSUME_ALWAYS_YES=yes pkg add ./\${PORTNAME}.txz && echo -e "\033[40;35m\${PORTNAME} found and added from cache. \033[0m"
-	}
-	pkg info -e \$PORTNAME || {
-	    make -C \$i clean
-	    make -C \$i
-	    make -C \$i install
-	    }
-    else
-	echo "Installing \$i "
-	make -C \$i install clean
-    fi
+	if [ -f /tmp/buildcontinue ]; then
+		cd /tmp/packages
+		PORTNAME=\`make -C \$i -V PKGNAME\`
+		pkg info -e \$PORTNAME >/dev/null 2>&1 || {
+			[ -f \${PORTNAME}.txz ] && env ASSUME_ALWAYS_YES=yes pkg add ./\${PORTNAME}.txz && echo -e "\033[40;35m\${PORTNAME} found and added from cache. \033[0m"
+		}
+		pkg info -e \$PORTNAME || {
+			make -C \$i clean
+			make -C \$i
+			make -C \$i install
+		}
+	else
+		echo "Installing \$i "
+		make -C \$i install clean
+	fi
 done
 EOF
 }
@@ -169,20 +163,20 @@ EOF
 
 copy_ccachedir_to_chroot()
 {
-    ${ECHO} "${MAGENTA}Moving cache from storage: ${GREEN}${ccache_realdir}${MAGENTA}...${NORMAL}"
-    set +o errexit
-    [ ! -d "${cdir}/root/.ccache" ] && mkdir -p ${cdir}/root/.ccache
-    cp -a ${ccache_realdir}/* ${cdir}/root/.ccache/
-    set -o errexit
+	${ECHO} "${MAGENTA}Moving cache from storage: ${GREEN}${ccache_realdir}${MAGENTA}...${NORMAL}"
+	set +o errexit
+	[ ! -d "${cdir}/root/.ccache" ] && mkdir -p ${cdir}/root/.ccache
+	cp -a ${ccache_realdir}/* ${cdir}/root/.ccache/
+	set -o errexit
 }
 
 copy_ccachedir_from_chroot()
 {
-    set +o errexit
-    [ -d "${ccache_realdir}" ] && rm -rf $ccache_realdir
-    ${ECHO} "${MAGENTA}Moving cache to storage${NORMAL}"
-    mv ${cdir}/root/.ccache ${ccache_realdir}
-    set -o errexit
+	set +o errexit
+	[ -d "${ccache_realdir}" ] && rm -rf $ccache_realdir
+	${ECHO} "${MAGENTA}Moving cache to storage${NORMAL}"
+	mv ${cdir}/root/.ccache ${ccache_realdir}
+	set -o errexit
 }
 
 
@@ -199,21 +193,21 @@ init_kerneldir
 unset SRCCONF
 
 if [ -d "${dstdir}" ]; then
-    [ "${append}" = "1" ] && break
-    A=`ls -C1 ${dstdir}/`
-    [ -n "${A}" ] && err 1 "Warning: ${dstdir}/ is not empty. Please clean before cpr initialization: ${A}"
+	[ "${append}" = "1" ] && break
+	A=$( ls -C1 ${dstdir}/ )
+	[ -n "${A}" ] && err 1 "Warning: ${dstdir}/ is not empty. Please clean before cpr initialization: ${A}"
 else
-    mkdir -p "${dstdir}"
+	mkdir -p "${dstdir}"
 fi
 
-if [ `uname -m` = "i386" -a "${arch}" = "amd64" ]; then
-    err 1 "Cannot install amd64 base on i386 hosts"
+if [ $( uname -m ) = "i386" -a "${arch}" = "amd64" ]; then
+	err 1 "Cannot install amd64 base on i386 hosts"
 fi
 
 if [ "$new" = "0" ]; then
-    new=0
+	new=0
 else
-    new=1
+	new=1
 fi
 
 [ -z "${makeconf}" ] && makeconf="${sharedir}/cpr_make.conf"
@@ -221,11 +215,11 @@ fi
 [ ! -f "${pkglist}" -a "${pkglist}" != "pkg_cutleaves" ] && err 1 "No pkglist file"
 
 if [ "${pkglist}" = "pkg_cutleaves" ]; then
-    _tmppkglist="${ftmpdir}/tmppkglist.txt.$$"
-    cbsd pkg_cutleaves out=${_tmppkglist}
-    pkglist=${_tmppkglist}
+	_tmppkglist="${ftmpdir}/tmppkglist.txt.$$"
+	cbsd pkg_cutleaves out=${_tmppkglist}
+	pkglist=${_tmppkglist}
 else
-    _tmppkglist=""
+	_tmppkglist=""
 fi
 
 [ -d "${cdir}" ] && umount_cdirs ${cdir} || true
@@ -238,18 +232,18 @@ fi
 export cdir=${cdir}
 
 if [ "${pause}" = "1" ]; then
-    export pause=1
+	export pause=1
 else
-    export pause=0
+	export pause=0
 fi
 
 [ ! -d "${PORTSCFG_SRC}" ] && mkdir -p $PORTSCFG_SRC
 
 #defaults
 if [ "${ccache}" = "1" ]; then
-    ccache=1
+	ccache=1
 else
-    ccache=0
+	ccache=0
 fi
 
 if [ "${distcc}" = "1" ]; then
@@ -270,21 +264,21 @@ if [ $ccache -eq 1 -o $distcc -eq 1 ]; then
     prepare_make_conf ${makeconf} ${cdir}/etc/make.conf
 fi
 
-DT_START=`date +%s`
+DT_START=$( date +%s )
 send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch} ${repoversion} started" -b "${DT_START}"
 cp ${sharedir}/cpr_packages.sh ${cdir}/tmp/cpr_packages.sh
 
 grep -v "^#" ${pkglist} > ${cdir}/tmp/ports_list.txt
 
 if [ $ccache -eq 1 ]; then
-    ccache_prefix="cbsd cpr $ver $arch ${target_arch} $basename"
-    ccache_dir="/var/cache/ccache"
+	ccache_prefix="cbsd cpr $ver $arch ${target_arch} $basename"
+	ccache_dir="/var/cache/ccache"
 
-    if ! init_ccache_dir; then
-	ccache=0
-    else
-	copy_ccachedir_to_chroot
-    fi
+	if ! init_ccache_dir; then
+		ccache=0
+	else
+		copy_ccachedir_to_chroot
+	fi
 fi
 
 set -o errexit
@@ -293,40 +287,40 @@ chroot $cdir sh /tmp/cpr_packages.sh
 TRAP="${TRAP} umount_cdirs ${cdir}; rm -f ${LOCKFILE} ${_tmppkglist};"
 trap "${TRAP}" HUP INT ABRT BUS TERM  EXIT
 
-DT_END=`date +%s`
+DT_END=$( date +%s )
 DT_DIFF=$((DT_END - DT_START))
 
 [ $ccache -eq 1 ] && copy_ccachedir_from_chroot
 # test for port_log from portmater and send broken build log to email
 set +o errexit
- A=`ls ${cdir}/tmp/port_log* 2>/dev/null`
+A=$( ls ${cdir}/tmp/port_log* 2>/dev/null )
 
- if [ -n "${A}" ]; then
-    if [ -n "${CBSDRCPT}" ]; then
-	send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} failed. See message below and next message for datail" -f ${cdir}/tmp/build.log
-        sleep 5 # delay for correct message order ;)
-	send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} broken build log" -f ${A} 
- fi
-    cat ${A}
-    err 1 "Build packages.sh error"   
- fi
+if [ -n "${A}" ]; then
+	if [ -n "${CBSDRCPT}" ]; then
+		send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} failed. See message below and next message for datail" -f ${cdir}/tmp/build.log
+		sleep 5 # delay for correct message order ;)
+		send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} broken build log" -f ${A} 
+	fi
+	cat ${A}
+	err 1 "Build packages.sh error"   
+fi
 set -o errexit
 
 if [ "${dstdir}" = "repo" ]; then
-    find ${cdir}/packages/All -type f -name \*.txz -exec mv -f {} ${MYPKGDIR}/ \;
-    ROOTPKGDIR="${MYPKGDIR}"
+	find ${cdir}/packages/All -type f -name \*.txz -exec mv -f {} ${MYPKGDIR}/ \;
+	ROOTPKGDIR="${MYPKGDIR}"
 else
-    find ${cdir}/packages/All -type f -name \*.txz -exec cp -n {} ${MYPKGDIR}/ \;
-    ROOTPKGDIR="${dstdir}"
-    mkdir -p ${ROOTPKGDIR}
-    mv ${cdir}/packages/* ${ROOTPKGDIR}/
+	find ${cdir}/packages/All -type f -name \*.txz -exec cp -n {} ${MYPKGDIR}/ \;
+	ROOTPKGDIR="${dstdir}"
+	mkdir -p ${ROOTPKGDIR}
+	mv ${cdir}/packages/* ${ROOTPKGDIR}/
 fi
 
 
-    # create pkg in symlinked /Latest location (see pkg-repository(5))
-    cd ${ROOTPKGDIR}
-    ln -s ./All ./Latest
-    cd ${ROOTPKGDIR}/All
-    find ./ -type f -name pkg-[0-9]* -exec ln -s {} ./pkg.txz \;
+# create pkg in symlinked /Latest location (see pkg-repository(5))
+cd ${ROOTPKGDIR}
+ln -s ./All ./Latest
+cd ${ROOTPKGDIR}/All
+find ./ -type f -name pkg-[0-9]* -exec ln -s {} ./pkg.txz \;
 
-    send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch} ${repoversion} complete" -b "${DT_END}"
+send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch} ${repoversion} complete" -b "${DT_END}"
