remove deprecated patch; remove periodic task; traffic ipfw counter now server by cbsdd; bhyve: we use the different tmux session name for bhyveload/bhyve and blogin preferred bhyve session

diff --git a/tools/cpr b/tools/cpr
--- a/tools/cpr
+++ b/tools/cpr
@@ -2,15 +2,14 @@
 #v10.0.7
 globalconf="${workdir}/cbsd.conf"
 CBSDMODULE="cpr"
-MYARG="cdir pkglist dstdir"
-MYOPTARG="ver arch basename stable new repoversion ccache pause makeconf append usegcc"
+MYARG=""
+MYOPTARG="ver arch basename stable new repoversion ccache pause makeconf append usegcc attach"
 MYDESC="Create pkg repository"
 ADDHELP="ver=head for current.\n\
 stable=1 for RELENG_X\n\
 dstdir= path to output packages or 'repo' for update repoversion\n\
-cdir= temporary chroot directory\n\
 pkglist= path to ascii file with port list for install or 'pkg_cutleaves' for dup master set\n\
-new= 1 - new repo (remove cdir (default)) or 0 - continue\n\
+new= 1 - new repo (remove path (default)) or 0 - continue\n\
 repoversion= name of repo version (ports cfg version), default for system set\n\
 ccache=1 or 0 - enable ccache (default is 0, disabled)\n\
 distcc=0 or 1 - enable distcc (default is 0, disabled)\n\
@@ -18,7 +17,7 @@ makeconf= path to alternative cpr_make.conf to /etc/make.conf in chroot\n\
 pause=1 - make pause (for example for chroot in env) before create pkg\n\
 append=1 - do not check for dstdir in not empty\n\
 usegcc=path to gcc port\n"
-set -e
+#set -e
 
 TRAP=""
 
@@ -27,6 +26,7 @@ TRAP=""
 . ${subr}
 . ${inventory}
 . ${system}
+. ${strings}
 . ${distccacheconf}
 . ${mailconf}
 . ${tools}
@@ -35,12 +35,116 @@ readconf buildworld.conf
 init $*
 . ${buildconf}
 
+show_tmux_session()
+{
+	tmuxcmd=$( which tmux 2>/dev/null )
+	
+	[ -z "${tmuxcmd}" ] && err 1 "${MAGENTA}No such tmux${NORMAL}"
+
+	${ECHO} "${MAGENTA}Active cpr session:${NORMAL}"
+	${tmuxcmd} list-sessions 2>/dev/null| grep "\-cpr: " |cut -d : -f 1
+	exit 0
+}
+
+post_action()
+{
+	if [ $pause -eq 1 ]; then
+		${ECHO} "${MAGENTA}Pause before create pkg.${NORMAL}"
+		${ECHO} "${MAGENTA}You can enter in jail via: ${GREEN}cbsd jlogin ${jname}${NORMAL}"
+		${ECHO} "${MAGENTA}Press any key to continue.${NORMAL}"
+		read pause
+	fi
+
+	${ECHO} "${MAGENTA}Creating packages... ${NORMAL}"
+
+	chroot ${path} /bin/sh << EOF
+export PACKAGES=/packages
+
+for i in \$( pkg info -oa | cut -d : -f1 ); do
+	pkg create -n -g -f txz -o \${PACKAGES}/All/ \$i
+done
+
+cd \${PACKAGES}
+rm -f digests.txz packagesite.txz repo.txz
+pkg repo \${PACKAGES}/
+EOF
+
+#TRAP="${TRAP} umount_paths ${path}; rm -f ${LOCKFILE} ${_tmppkglist};"
+TRAP="${TRAP} rm -f ${LOCKFILE} ${_tmppkglist};"
+trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
+
+DT_END=$( date +%s )
+DT_DIFF=$((DT_END - DT_START))
+
+[ $ccache -eq 1 ] && copy_ccachedir_from_chroot
+# test for port_log from portmater and send broken build log to email
+#set +o errexit
+#A=$( ls ${path}/tmp/port_log* 2>/dev/null )
+
+#if [ -n "${A}" ]; then
+#       if [ -n "${CBSDRCPT}" ]; then
+#               send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} failed. See message below and next message for datail" -f ${path}/tmp/build.log
+#               sleep 5 # delay for correct message order ;)
+#               send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} broken build log" -f ${A}
+#       fi
+#       cat ${A}
+#       err 1 "Build packages.sh error"
+#fi
+
+	cbsd jstop ${jname}
+	if [ "${dstdir}" = "repo" ]; then
+		find ${path}/packages/All -type f -name \*.txz -exec mv -f {} ${MYPKGDIR}/ \;
+		ROOTPKGDIR="${MYPKGDIR}"
+	else
+		find ${path}/packages/All -type f -name \*.txz -exec cp -n {} ${MYPKGDIR}/ \;
+		ROOTPKGDIR="${dstdir}"
+		mkdir -p ${ROOTPKGDIR}
+		mv ${path}/packages/* ${ROOTPKGDIR}/
+	fi
+
+	# create pkg in symlinked /Latest location (see pkg-repository(5))
+	cd ${ROOTPKGDIR}
+	ln -s ./All ./Latest
+	cd ${ROOTPKGDIR}/All
+	find ./ -type f -name pkg-[0-9]* -exec ln -s {} ./pkg.txz \;
+
+	send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch} ${repoversion} complete" -b "${DT_END}"
+}
+
+
+# $1 - src-session name
+init_tmux()
+{
+	local src_session
+
+	src_session="${1}"
+
+	if [ "${tmux_cpr}" != "1" -o -z "${src_session}" ]; then
+		tmux_cpr=0
+		return 0
+        fi
+
+	tmuxcmd=$( which tmux 2>/dev/null )
+
+	session_name="${src_session}"
+
+	if [ -n "${tmuxcmd}" ]; then
+		# tmux here and we preferred them
+		return 0
+	fi
+
+	# no tmux here
+	tmux_cpr=0
+	return 0
+
+}
+
 umount_temp_dirs()
 {
-	# when error before cdir, we do not have any mounts by scripts
-	[ -z "${cdir}" -o ! -d "${cdir}" ] && return 0
+	# when error before path, we do not have any mounts by scripts
+	[ -z "${path}" -o ! -d "${path}" ] && return 0
 
-	umount_cdirs ${cdir}
+	umount_paths ${path}
 
 	#destroy md disk when he used
 	if [ "${CCACHEFS}" = "mdfs" -a -n "${MDDEV}" ]; then
@@ -52,20 +156,9 @@ umount_temp_dirs()
 mount_temp_dirs()
 {
 	local _tmpfstab="${ftmpdir}/mount_temp_dirs.$$"
-	set +e
-	kldstat -qm linprocfs || kldload linprocfs
-	set -e
 
 	TRAP="${TRAP} rm -f ${_tmpfstab};"
 	trap "${TRAP};" HUP INT ABRT BUS TERM EXIT
-
-	cat > ${_tmpfstab} << EOF
-devfs /dev devfs rw 0 0
-procfs /proc procfs rw 0 0
-linprocfs /usr/compat/linux/proc linprocfs rw 0 0
-EOF
-
-	[ -d "${SRC_DIR}" ] && echo "${SRC_DIR} /usr/src nullfs ro 0 0" >> ${_tmpfstab}
 
 	if [ -z "${repoversion}" -o "${repoversion}" = "default" ]; then
 		PORTSCFG_SRC="/var/db/ports"
@@ -83,21 +176,7 @@ ${PORTSCFG_SRC} /var/db/ports nullfs rw 0 0
 ${MYPKGDIR} /tmp/packages nullfs rw 0 0
 EOF
 
-    if [ "$MOUNT_PORTS" = "1" -a "$MOUNT_DISTFILES" = "1" ]; then
-	cat >> ${_tmpfstab} << EOF
-/usr/ports /usr/ports nullfs rw 0 0
-EOF
-    else
-	if [ "${MOUNT_PORTS}" = "0" -a "${MOUNT_DISTFILES}" = "1" ]; then
-	cat >> ${_tmpfstab} << EOF
-/usr/ports/distfiles nullfs /usr/ports/distfiles rw 0 0
-EOF
-	fi
-    fi
-
-	[ -d "${KERNEL_DIR}" ] && echo "${KERNEL_DIR} /boot/kernel nullfs ro 0 0" >> ${_tmpfstab}
-
-	cbsd mountfstab jroot=$cdir fstab=${_tmpfstab} jname="${jname}"
+	cbsd mountfstab jroot=$path fstab=${_tmpfstab} jname="${jname}"
 	rm -f ${_tmpfstab}
 }
 
@@ -111,22 +190,22 @@ prepare_chroot()
 	export NEEDEDPORTS
 
 	[ -n "${usegcc}" ] && export usegcc
-	[ -f "${makeconf}" ] && cp ${makeconf} ${cdir}/etc/make.conf
+	[ -f "${makeconf}" ] && cp ${makeconf} ${path}/etc/make.conf
 
 	# remove default pkg.conf
-	rm -f ${cdir}/etc/pkg/*.conf
+	rm -f ${path}/etc/pkg/*.conf
 
 	# make sure we have work dir in /tmp for parallel builds
-	[ $( grep ^WRKDIRPREFIX= ${cdir}/etc/make.conf|wc -l )  = 0 ] && echo WRKDIRPREFIX=/tmp >> ${cdir}/etc/make.conf
-	cp /etc/resolv.conf ${cdir}/etc
+	[ $( grep ^WRKDIRPREFIX= ${path}/etc/make.conf|wc -l )  = 0 ] && echo WRKDIRPREFIX=/tmp >> ${path}/etc/make.conf
+	cp /etc/resolv.conf ${path}/etc
 
-	touch ${cdir}/etc/src.conf
+	touch ${path}/etc/src.conf
 
-	chroot $cdir /bin/sh << EOF
+	chroot $path /bin/sh << EOF
 service ldconfig start
 #env ASSUME_ALWAYS_YES=yes pkg > /dev/null 2>&1
 mv /etc/make.conf /tmp
-make -C /usr/ports/ports-mgmt/pkg clean install
+pkg info -e pkg || make -C /usr/ports/ports-mgmt/pkg clean install
 mv /tmp/make.conf /etc
 pkg2ng
 # remove default pkg.conf
@@ -141,9 +220,9 @@ if [ -n "\${usegcc}" ]; then
 fi
 
 for i in \${NEEDEDPORTS}; do
+		PORTNAME=\$( make -C \$i -V PORTNAME )
 	if [ -f /tmp/buildcontinue ]; then
 		cd /tmp/packages
-		PORTNAME=\`make -C \$i -V PKGNAME\`
 		pkg info -e \$PORTNAME >/dev/null 2>&1 || {
 			[ -f \${PORTNAME}.txz ] && env ASSUME_ALWAYS_YES=yes pkg add ./\${PORTNAME}.txz && echo -e "\033[40;35m\${PORTNAME} found and added from cache. \033[0m"
 		}
@@ -153,37 +232,32 @@ for i in \${NEEDEDPORTS}; do
 			make -C \$i install
 		}
 	else
-		echo "Installing \$i "
+		pkg info -e \$PORTNAME && continue
+		echo "Installing \$PORTNAME from \$i "
 		make -C \$i install clean
 	fi
 done
 EOF
 }
 
-
 copy_ccachedir_to_chroot()
 {
 	${ECHO} "${MAGENTA}Moving cache from storage: ${GREEN}${ccache_realdir}${MAGENTA}...${NORMAL}"
-	set +o errexit
-	[ ! -d "${cdir}/root/.ccache" ] && mkdir -p ${cdir}/root/.ccache
-	cp -a ${ccache_realdir}/* ${cdir}/root/.ccache/
-	set -o errexit
+	[ ! -d "${path}/root/.ccache" ] && mkdir -p ${path}/root/.ccache
+	cp -a ${ccache_realdir}/* ${path}/root/.ccache/
 }
 
 copy_ccachedir_from_chroot()
 {
-	set +o errexit
 	[ -d "${ccache_realdir}" ] && rm -rf $ccache_realdir
 	${ECHO} "${MAGENTA}Moving cache to storage${NORMAL}"
-	mv ${cdir}/root/.ccache ${ccache_realdir}
-	set -o errexit
+	mv ${path}/root/.ccache ${ccache_realdir}
 }
 
-
+[ -z "${pkglist}" -o -z "${dstdir}" ] && show_tmux_session
 
 ### MAIN
 readconf cpr.conf
-
 init_target_arch
 init_srcdir
 init_supported_arch
@@ -192,22 +266,23 @@ init_kerneldir
 
 unset SRCCONF
 
+if [ "$new" = "0" ]; then
+	new=0
+else
+	new=1
+fi
+
 if [ -d "${dstdir}" ]; then
-	[ "${append}" = "1" ] && break
-	A=$( ls -C1 ${dstdir}/ )
-	[ -n "${A}" ] && err 1 "Warning: ${dstdir}/ is not empty. Please clean before cpr initialization: ${A}"
+	if [ "${new}" = "1" -o "${append}" = "0" ]; then
+		A=$( ls -1 ${dstdir}/ |wc -l |awk '{ printf $1 }' )
+		[ "${A}" != "0" ] && ${ECHO} "${MAGENTA}Warning: ${GREEN}${dstdir}/${MAGENTA} is not empty. Please clean before cpr initialization:${NORMAL}" && err 1 $( ls -1 ${dstdir} )
+	fi
 else
 	mkdir -p "${dstdir}"
 fi
 
 if [ $( uname -m ) = "i386" -a "${arch}" = "amd64" ]; then
 	err 1 "Cannot install amd64 base on i386 hosts"
-fi
-
-if [ "$new" = "0" ]; then
-	new=0
-else
-	new=1
 fi
 
 [ -z "${makeconf}" ] && makeconf="${sharedir}/cpr_make.conf"
@@ -222,14 +297,29 @@ else
 	_tmppkglist=""
 fi
 
-[ -d "${cdir}" ] && umount_cdirs ${cdir} || true
-[ -d "${cdir}" -a $new -eq 1 ] && chflags -R noschg ${cdir} && rm -rf ${cdir}
-[ ! -d "${cdir}" -a $new -eq 0 ] && new=1
-[ ! -d "${cdir}" ] && mkdir ${cdir}
-[ $new -eq 1 ] && baserw=1 && populate_cdir ${BASE_DIR} ${cdir} ||true
-[ $new -eq 0 ] && touch ${cdir}/tmp/buildcontinue
+jname="cpr1"
+. ${jrcconf}
 
-export cdir=${cdir}
+if [ $? -eq 1 ]; then
+	${ECHO} "${MAGENTA}No such jail. Create from template: ${GREEN}${jname}${NORMAL}"
+	cbsd jcreate jconf=/usr/local/cbsd/tmp/cpr-amd64-amd64-11-tpl.jconf
+	cbsd jstart ${jname}
+fi
+
+. ${jrcconf}
+[ "$baserw" = "1" ] && path=$data
+
+if [ $jid -eq 0 ]; then
+	${ECHO} "${MAGENTA}Jail is not running. Starting... ${GREEN}${jname}${NORMAL}"
+	cbsd jstart ${jname}
+fi
+
+#[ -d "${path}" ] && umount_paths ${path} || true
+#[ -d "${path}" -a $new -eq 1 ] && chflags -R noschg ${path} && rm -rf ${path}
+#[ ! -d "${path}" -a $new -eq 0 ] && new=1
+#[ ! -d "${path}" ] && mkdir ${path}
+#[ $new -eq 1 ] && baserw=1 && populate_path ${BASE_DIR} ${path} ||true
+#[ $new -eq 0 ] && touch ${path}/tmp/buildcontinue
 
 if [ "${pause}" = "1" ]; then
 	export pause=1
@@ -247,28 +337,28 @@ else
 fi
 
 if [ "${distcc}" = "1" ]; then
-    distcc=1
+	distcc=1
 else
-    distcc=0
+	distcc=0
 fi
 
-TRAP="${TRAP} umount_cdirs ${cdir}; rm -f ${LOCKFILE} ${_tmppkglist};"
-trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
+#TRAP="${TRAP} umount_paths ${path}; rm -f ${LOCKFILE} ${_tmppkglist};"
+#trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 mount_temp_dirs
 
-[ "${MOUNT_PORTS}" = "0" -a $new -eq 1 ] && chroot ${cdir} portsnap fetch extract
+#[ "${MOUNT_PORTS}" = "0" -a $new -eq 1 ] && chroot ${path} portsnap fetch extract
 
 prepare_chroot
 
 if [ $ccache -eq 1 -o $distcc -eq 1 ]; then
-    prepare_make_conf ${makeconf} ${cdir}/etc/make.conf
+	prepare_make_conf ${makeconf} ${path}/etc/make.conf
 fi
 
 DT_START=$( date +%s )
 send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch} ${repoversion} started" -b "${DT_START}"
-cp ${sharedir}/cpr_packages.sh ${cdir}/tmp/cpr_packages.sh
+cp ${sharedir}/cpr_packages.sh ${path}/tmp/cpr_packages.sh
 
-grep -v "^#" ${pkglist} > ${cdir}/tmp/ports_list.txt
+grep -v "^#" ${pkglist} > ${path}/tmp/ports_list.txt
 
 if [ $ccache -eq 1 ]; then
 	ccache_prefix="cbsd cpr $ver $arch ${target_arch} $basename"
@@ -281,46 +371,22 @@ if [ $ccache -eq 1 ]; then
 	fi
 fi
 
-set -o errexit
-chroot $cdir sh /tmp/cpr_packages.sh
+jexec="cbsd jexec jname=${jname} sh /tmp/cpr_packages.sh"
 
-TRAP="${TRAP} umount_cdirs ${cdir}; rm -f ${LOCKFILE} ${_tmppkglist};"
-trap "${TRAP}" HUP INT ABRT BUS TERM  EXIT
+init_tmux "${jname}-cpr"
 
-DT_END=$( date +%s )
-DT_DIFF=$((DT_END - DT_START))
-
-[ $ccache -eq 1 ] && copy_ccachedir_from_chroot
-# test for port_log from portmater and send broken build log to email
-set +o errexit
-A=$( ls ${cdir}/tmp/port_log* 2>/dev/null )
-
-if [ -n "${A}" ]; then
-	if [ -n "${CBSDRCPT}" ]; then
-		send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} failed. See message below and next message for datail" -f ${cdir}/tmp/build.log
-		sleep 5 # delay for correct message order ;)
-		send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch}-${target_arch} ${repoversion} broken build log" -f ${A} 
+if [ $tmux_cpr -eq 1 ]; then
+	${tmuxcmd} list-sessions | /usr/bin/grep -qwF "${session_name}:"
+	if [ $? -eq 1 ]; then
+		echo "${tmuxcmd} new -s ${session_name}"
+		${tmuxcmd} new -s "${session_name}" "eval ${jexec}"
+	else
+		${tmuxcmd} attach-session -t "${session_name}"
 	fi
-	cat ${A}
-	err 1 "Build packages.sh error"   
-fi
-set -o errexit
-
-if [ "${dstdir}" = "repo" ]; then
-	find ${cdir}/packages/All -type f -name \*.txz -exec mv -f {} ${MYPKGDIR}/ \;
-	ROOTPKGDIR="${MYPKGDIR}"
 else
-	find ${cdir}/packages/All -type f -name \*.txz -exec cp -n {} ${MYPKGDIR}/ \;
-	ROOTPKGDIR="${dstdir}"
-	mkdir -p ${ROOTPKGDIR}
-	mv ${cdir}/packages/* ${ROOTPKGDIR}/
+	eval "${jexec}"
 fi
 
-
-# create pkg in symlinked /Latest location (see pkg-repository(5))
-cd ${ROOTPKGDIR}
-ln -s ./All ./Latest
-cd ${ROOTPKGDIR}/All
-find ./ -type f -name pkg-[0-9]* -exec ln -s {} ./pkg.txz \;
-
-send_notification -s "[CBSD ${nodename}] cpr ${ver} ${arch} ${repoversion} complete" -b "${DT_END}"
+if [ $tmux_cpr -ne 1 ]; then
+	post_action
+fi
