prepare for CBSD 10.1.2-RELEASE

diff --git a/tools/cpr b/tools/cpr
--- a/tools/cpr
+++ b/tools/cpr
@@ -72,7 +72,7 @@ pkg repo \${PACKAGES}/
 EOF
 
 #TRAP="${TRAP} umount_paths ${path}; rm -f ${LOCKFILE} ${_tmppkglist};"
-TRAP="${TRAP} rm -f ${LOCKFILE} ${_tmppkglist};"
+TRAP="${TRAP} /bin/rm -f ${LOCKFILE} ${_tmppkglist};"
 trap "${TRAP}" HUP INT ABRT BUS TERM EXIT
 
 DT_END=$( date +%s )
@@ -301,11 +301,13 @@ else
 fi
 
 jname="cpr1"
-. ${jrcconf}
+cbsd jstatus jname=${jname}
 
-if [ $? -eq 1 ]; then
+if [ $? -eq 0 ]; then
 	${ECHO} "${MAGENTA}No such jail. Create from template: ${GREEN}${jname}${NORMAL}"
-	cbsd jcreate jconf=/usr/local/cbsd/tmp/cpr-amd64-amd64-11-tpl.jconf
+	tpl="/usr/local/cbsd/tmp/cpr-amd64-amd64-${ver}-tpl.jconf"
+	[ ! -f "${tpl}" ] && err 1 "No such profile: ${tpl}"
+	cbsd jcreate jconf=${tpl} || err 1 "Error jail creation via tpl ${tpl}"
 	cbsd jstart ${jname}
 fi
 
diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -1,5 +1,5 @@
-#!/bin/sh
-#v10.0.6
+#!/usr/local/bin/cbsd
+#v10.1.2
 globalconf="${workdir}/cbsd.conf";
 MYARG="jroot fstab"
 MYOPTARG="jname"
@@ -14,75 +14,122 @@ set +e
 . ${system}
 init $*
 
-[ -f "${fstab}" ] || err 1 "${fstab} does not exist"
-[ -d "${jroot}" ] || err 1 "${jroot} does not exist"
+[ ! -f "${fstab}" ] && err 1 "${fstab} does not exist"
+[ ! -d "${jroot}" ] && err 1 "${jroot} does not exist"
+
+# local fstab exist ?
+have_local=0
+
+init_localmpt_fstab()
+{
+	[ ! -f "${fstab}.local" ] && return 0
+
+	have_local=1
+
+	local i=0
+
+	eval $( /bin/cat ${fstab}.local | while read _device _mountpt _fs _mode _a _b; do
+		case ":${_device}" in
+			:#* | :)
+			continue
+			;;
+		*)
+			echo "local_mpt${i}=\"${_mountpt}\""
+			i=$(( i + 1 ))
+			;;
+		esac
+	done )
+}
+
+# return 0 if no such mount point in fstab.local exist
+# return 1 if exist
+# $1 - test mpt
+# example:
+# if ! check_for_localmpt_fstab /tmp; then
+#		echo "EXIST"
+# fi
+check_for_localmpt_fstab()
+{
+	local _res=0
+
+	[ -z "${1}" ] && return 0
+
+	for i in $( /usr/bin/seq 0 128 ); do
+		eval local_mpt="\$local_mpt${i}"
+		[ -z "${local_mpt}" ] && break
+		[ "${local_mpt}" = "${1}" ] && _res=1 && break
+	done
+
+	return ${_res}
+}
+
+## MAIN
+init_localmpt_fstab
 
 # first pass: test for fstab is valid
-cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
-    [ "${_fs}" = "zfs" ] && continue
-    case ":${_device}" in
-	:#* | :)
-	continue
-	;;
-    *)
+/bin/cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 	[ "${_fs}" = "zfs" ] && continue
-	if [ "${_fs}" = "geli" ]; then
-		is_mounted ${gelidir} && continue
-		err 1 "Error: ${gelidir} is not initializated. Please use: 'cbsd geli mode=initmaster' first"
-	fi
-	[ -z "${_device}" ] && continue
-	echo ${_device} |grep -sq ^/
-	[ $? -ne 0 ] && _device="${workdir}/${_device}"
-#	if [ ! -f "${_device}" -o ! -d "${_device}" ]; then
-#	    TMPLOG=$( /usr/bin/mktemp ${ftmpdir}/fstab.XXX )
-#	    trap "rm -f ${TMPLOG}" HUP INT ABRT BUS TERM EXIT
-#	    echo "Source dir ${_device} doesn't exist" > ${TMPLOG}
-#	fi
-	;;
-    esac
+	case ":${_device}" in
+		:#* | :)
+		continue
+		;;
+	*)
+		[ "${_fs}" = "zfs" ] && continue
+		if [ "${_fs}" = "geli" ]; then
+			is_mounted ${gelidir} && continue
+			err 1 "Error: ${gelidir} is not initializated. Please use: 'cbsd geli mode=initmaster' first"
+		fi
+		[ -z "${_device}" ] && continue
+		# append workdir if it not full path
+		prefix=$( substr --pos=0 --len=1 --str=${_device} )
+		[ "${prefix}" != "/" ] && _device="${workdir}/${_device}"
+		;;
+	esac
 done
 
-#if [ -f "${TMPLOG}" ]; then
-#    ERRORLOG=$( cat $TMPLOG )
-#    rm -f ${TMPLOG}
-#    err 1 "$ERRORLOG"
-#fi
 
-cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
-    [ "${_fs}" = "zfs" ] && continue
-    case ":${_device}" in
-	:#* | :)
-	continue
-	;;
-    esac
 
-    mnt=0
+/bin/cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
+	[ "${_fs}" = "zfs" ] && continue
+	case ":${_device}" in
+		:#* | :)
+		continue
+		;;
+	esac
 
-    if [ "${_fs}" = "geli" ]; then
-    # prepare src part
-	echo "${_device}"|grep -sq ^/
-	if [ $? -ne 0 ]; then
-	    if [ -z "${jname}" ]; then
-		_device="${workdir}/${_device}"
-	    else
-		_device="${jailsysdir}/${jname}/${_device}"
-	    fi
+	# SKIP mount when mount point also exist in fstab.local. fstab.local is preferred
+	if [ ${have_local} -eq 1 ]; then
+		if ! check_for_localmpt_fstab ${_mountpt}; then
+			continue
+		fi
 	fi
-	cbsd attachgeli file="${_device}" dst="${jroot}${_mountpt}" mode="${_mode}"
-	continue
-    fi
 
-    echo ${_device} |grep -sq ^/
-    [ $? -ne 0 ] && _device="${workdir}/${_device}"
+	mnt=0
+	prefix=$( substr --pos=0 --len=1 --str=${_device} )
 
-    if is_mounted "${jroot}${_mountpt}"; then
-	echo "${jroot}${_mountpt} already mounted"
-	mnt=1
-    fi
+	if [ "${_fs}" = "geli" ]; then
+		# prepare src part
+		if [ "${prefix}" != "/" ]; then
+			if [ -z "${jname}" ]; then
+				_device="${workdir}/${_device}"
+			else
+				_device="${jailsysdir}/${jname}/${_device}"
+			fi
+		fi
+		attachgeli file="${_device}" dst="${jroot}${_mountpt}" mode="${_mode}"
+		continue
+	fi
 
-    if [ ${mnt} -eq 0 ]; then
-	[ ! -d "${jroot}${_mountpt}" ] && mkdir -p "${jroot}${_mountpt}"
-	[ ! -d "${jroot}${_mountpt}" ] && echo "Warning: Can't create ${jroot}${_mountpt} - permission problem ?"
-	/sbin/mount -t ${_fs} -o${_mode} ${_device} ${jroot}${_mountpt}
-    fi
+	[ "${prefix}" != "/" ] && _device="${workdir}/${_device}"
+
+	if is_mounted "${jroot}${_mountpt}"; then
+		echo "${jroot}${_mountpt} already mounted"
+		mnt=1
+	fi
+
+	if [ ${mnt} -eq 0 ]; then
+		[ ! -d "${jroot}${_mountpt}" ] && mkdir -p "${jroot}${_mountpt}"
+		[ ! -d "${jroot}${_mountpt}" ] && echo "Warning: Can't create ${jroot}${_mountpt} - permission problem ?"
+		/sbin/mount -t ${_fs} -o${_mode} ${_device} ${jroot}${_mountpt}
+	fi
 done
