check for cores/sockets values

diff --git a/tools/cpu-topology b/tools/cpu-topology
--- a/tools/cpu-topology
+++ b/tools/cpu-topology
@@ -21,7 +21,7 @@ cpu_topology_in_ascii_art()
 
 	[ -z "${jail_list}" -a -z "${bhyve_list}" ] && jail_list="no any environments"
 
-	for i in $( /usr/bin/seq 1 ${sockets_num} ); do
+	for i in $( ${SEQ_CMD} 1 ${sockets_num} ); do
 
 		socket_id=$(( i - 1 ))
 
@@ -44,8 +44,11 @@ cpu_topology_in_ascii_art()
 	done
 }
 
+NDOMAINS=$( ${SYSCTL_CMD} -qn vm.ndomains 2>/dev/null )
+[ -z "${NDOMAINS}" ] && NDOMAINS="0"				# x86 only?
+
 ${SYSCTL_CMD} -qn kern.sched.topology_spec > ${tmpdir}/top.$$
-trap "/bin/rm -f ${tmpdir}/top.$$" HUP INT ABRT BUS TERM EXIT
+trap "${RM_CMD} -f ${tmpdir}/top.$$" HUP INT ABRT BUS TERM EXIT
 
 sockets_num=
 cores_num=
@@ -63,10 +66,28 @@ eval $( ${miscdir}/dump_cpu_topology ${tmpdir}/top.$$ 2>/dev/null )
 #cores_by_socket1="14 12 10 8 "
 #threads_by_socket1="15 13 11 9 "
 
+[ -z "${cores_max}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: unknown cores_max${N0_COLOR}"
+[ -z "${sockets_num}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: unknown sockets_num${N0_COLOR}"
+[ "${sockets_num}" = "0" ] && err 1 "${N1_COLOR}${CBSD_APP} error: sockets_num=0${N0_COLOR}"
+
+if is_number ${sockets_num}; then
+	err 1 "${N1_COLOR}${CBSD_APP} error: sockets_num is not number: ${N2_COLOR}[${sockets_num}]${N0_COLOR}"
+fi
+if is_number ${cores_max}; then
+	err 1 "${N1_COLOR}${CBSD_APP} error: cores_max is not number: ${N2_COLOR}[${cores_max}]${N0_COLOR}"
+fi
+
 ${ECHO} "${N1_COLOR}Model: ${N2_COLOR}${cpumodel}${N0_COLOR}"
 ${ECHO} "${N1_COLOR}Sockets num: ${N2_COLOR}${sockets_num}${N0_COLOR}"
 ${ECHO} "${N1_COLOR}Cores num: ${N2_COLOR}${cores_num}${N0_COLOR}"
 ${ECHO} "${N1_COLOR}Threads num: ${N2_COLOR}${threads_num}${N0_COLOR}"
+
+if [ ${sockets_num} -gt 1 -a ${NDOMAINS} -lt 2 ]; then
+	NUMA_INFO=" ${W1_COLOR}(but sockets > 1, NUMA not enabled in BIOS?)${N0_COLOR} "
+fi
+${ECHO} "${N1_COLOR}NUMA domains: ${N2_COLOR}${NDOMAINS}${NUMA_INFO}${N0_COLOR}"
+
+
 ${ECHO} "--"
 ${ECHO} "${N1_COLOR}Core max: ${N2_COLOR}${cores_max}${N0_COLOR}"
 
