bhyve_create_dsk + xen_create_dsk = virtual_create_dsk()
consolidate two equal funcion into generic

diff --git a/tools/createhd b/tools/createhd
--- a/tools/createhd
+++ b/tools/createhd
@@ -134,8 +134,8 @@ case ${named_disk} in
 		select_by_path ${full_path}
 		[ $? -eq 0 ] && err 1 "${N1_COLOR}Path already registered: ${N2_COLOR}${vm_res}${N0_COLOR}"
 
-		if ! bhyve_create_dsk -p ${full_path} -s ${size} -f 1; then
-			err 1 "${N1_COLOR}bhyve_create_dsk from createhd failed for: ${N2_COLOR}${full_path}${N0_COLOR}"
+		if ! virtual_create_dsk -p ${full_path} -s ${size} -f 1; then
+			err 1 "${N1_COLOR}virtual_create_dsk from createhd failed for: ${N2_COLOR}${full_path}${N0_COLOR}"
 		fi
 
 		;;
