use buildah oci layer id to find zfs volume that matches image, diff-digest not always found right layer

diff --git a/tools/images b/tools/images
--- a/tools/images
+++ b/tools/images
@@ -183,13 +183,13 @@ images_register()
 					err 1 "${N1_COLOR}${CIX_APP}: buildah image not found: ${N2_COLOR}${path}${N0_COLOR}"
 				fi
 
-				_image_sha256=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah inspect "${_imgname}" | ${JQ_CMD} -r '.OCIv1.rootfs.diff_ids[-1]' )
+				_image_top_layer=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah inspect --type=image "${_imgname}" | ${JQ_CMD} -r '.FromImageID // .ImageID // .ID' )
 				_ret=$?
-				if [ ${_ret} -ne 0 -o -z "${_image_sha256}" ]; then
-					${ECHO} "${N1_COLOR}${CIX_APP}: unable to create find tom layer in image ${_imgname}${N0_COLOR}"
+				if [ ${_ret} -ne 0 -o -z "${_image_top_layer}" ]; then
+					${ECHO} "${N1_COLOR}${CIX_APP}: unable to create find top layer in image ${_imgname}${N0_COLOR}"
 					exit 1
 				fi
-                echo "image sha256: ${_image_sha256}"
+                echo "image top layer: ${_image_top_layer}"
 
 				case "${_buildah_platform}" in
 					freebsd)
@@ -205,7 +205,13 @@ images_register()
 
 				##ZFS
 				if [ ${zfsfeat} -eq 1 ]; then
-                    _image_volume_id=$(jq -r '.[]|select(."diff-digest" == "'"${_image_sha256}"'")|(.parent // .id)' ${workdir}/basejail/buildah/zfs-layers/layers.json | tail -n1)
+                    _image_volume_id=$(${JQ_CMD} -r '.[] | select(.id=="'${_image_top_layer}'") | .layer' ${workdir}/basejail/buildah/zfs-images/images.json)
+					_ret=$?
+					if [ ${_ret} -ne 0 -o -z "${_image_volume_id}" ]; then
+						${ECHO} "${N1_COLOR}${CIX_APP}: unable to find volume id for image top layer ${_image_top_layer}${N0_COLOR}"
+						exit 1
+					fi
+
                     _zvol=$(${ZFS_CMD} get -Ho value name ${workdir}/basejail/buildah)
                     _ret=$?
                     if [ -z "${_zvol}" -o ${_ret} -ne 0 ]; then
