wip

diff --git a/tools/imghelper b/tools/imghelper
--- a/tools/imghelper
+++ b/tools/imghelper
@@ -1,7 +1,7 @@
 #!/usr/local/bin/cbsd
 #v10.1.0
-MYARG="formfile"
-MYOPTARG=""
+MYARG=""
+MYOPTARG="formfile bootstrap jname"
 MYDESC="Ncurses-based jail image boostrap helper"
 EXTHELP="wf_imghelper.html"
 
@@ -9,22 +9,29 @@ EXTHELP="wf_imghelper.html"
 . ${inventory}
 . ${settingstui}
 . ${tools}
+. ${strings}
+. ${system}
 . ${dialog}
 
+
 if [ "${1}" != "--help" -a "${1}" != "--args" ]; then
-	formfile="${1}"
-	[ ! -f "${1}" ] && err 1 "${MAGENTA}No such form file: ${GREEN}${formfile}${NORMAL}"
-	shift
-	param=$( cbsdsql ${formfile} SELECT param FROM forms ORDER by idx |xargs )
-	MYOPTARG="${MYOPTARG} ${param}"
+	# assume that this is the path to form wheny start with a slash
+	echo "${1}" |/usr/bin/grep -q ^/
+	if [ $? -eq 0 ]; then
+		formfile="${1}"
+		[ ! -f "${1}" ] && err 1 "${MAGENTA}No such form file: ${GREEN}${formfile}${NORMAL}"
+		shift
+		param=$( cbsdsql ${formfile} SELECT param FROM forms ORDER by idx |/usr/bin/xargs )
+		MYOPTARG="${MYOPTARG} ${param}"
+	fi
 fi
 
 init $*
 
-# if allfilled; then
+# if all_filled; then
 #    echo "ALL FILLED"
 # fi
-allfilled()
+all_filled()
 {
 	local i _T
 
@@ -32,6 +39,7 @@ allfilled()
 		eval _T=\${${i}}
 		[ -z "${_T}" ] && return 1
 	done
+
 	return 0
 }
 
@@ -73,9 +81,7 @@ dialog_menu_main()
 	local title=" Image parameters for ${jname} "
 	local _mydesc
 
-	local menu_list="
-		'EXIT'  'EXIT'  'Exit jconstruct-tui'
-	" # END-QUOTE
+	local menu_list=
 
 	for _items in ${FORMS}; do
 		eval VAL=\$${_items}
@@ -138,21 +144,89 @@ get_helper_value()
 	f_dialog_input _input "${_mydesc}" "${VAL}" \
 		"${_message}" || return $?
 
-	[ -n "${_input}" ] && eval ${mtag}_defaults="${_input}"
+	[ -n "${_input}" ] && eval ${mtag}="${_input}"
+
 }
 
-load_forms
-
 #### [ MAIN AREA ] ####
-while [ 1 ]; do
+# we work in two modes:
+# when we got bootstrap file ( which shall contain install_img )
+# or only formfile ( can be set in boostrap )
+#
+# When no bootstrap - load and execute form then exist
+# when bootstrap exist - after form execute install_img func
+#
+with_bootstrap=0
+
+if [ -n "${bootstrap}" ]; then
+
+	[ ! -f "${bootstrap}" ] && err 1 "${MAGENTA}No such bootstrap file: ${GREEN}${bootstrap}${NORMAL}"
+
+	[ -z "${jname}" ] && err 1 "${MAGENTA}jname= is necessary for bootstrap${NORMAL}"
+
+	. ${jrcconf}
+	[ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
+	[ ${jid} -ne 0 ] && err 1 "${MAGENTA}Error: jail is active${NORMAL}"
+
+	. ${bootstrap}
+	. ${workdir}/universe.subr
+
+	[ -z "${formfile}" ] && err 1 "No such formfile"
+	[ ! -f "${formfile}" ] && err 1 "Formfile doesn't exist: ${formfile}"
+
+#	init_target_arch
+#	init_basedir
+
+	[ $baserw -eq 1 ] && path=$data
+	[ ! -d "${path}" ] && mkdir -p ${path}
+
+#	if ! is_mounted "${path}"; then
+#		mountbase
+#	fi
+
+#	mountfstab
+
+	with_bootstrap=1
+else
+	[ -z "${formfile}" ] && err 1 "No such formfile"
+	[ ! -f "${formfile}" ] && err 1 "Formfile doesn't exist: ${formfile}"
+fi
+
+param=$( cbsdsql ${formfile} SELECT param FROM forms ORDER by idx |/usr/bin/xargs )
+load_forms
+x=1
+
+while [ ${x} -eq 1 ]; do
 	dialog_menu_main
 	ret=$?
 	case $ret in
 		${DIALOG_OK})
-			get_helper_value
+			case "${mtag}" in
+				"COMMIT")
+					if all_filled; then
+						x=0
+						continue
+					else
+						f_dialog_msgbox "All field is mandatory"
+					fi
+					continue
+					;;
+				*)
+					get_helper_value
+					;;
+			esac
 			;;
 		*)
 			f_die
 			;;
 	esac
 done
+
+# no bootrstap? this is the end my beautiful friend
+[ ${with_bootstrap} -eq 0 ] && f_die
+
+# Here is boostrap-only area
+jstart jname=${jname}
+install_img
+jstop jname=${jname}
+img_message
