* jexport: add dstdir alternative directory for saving images; * jexport: support for wss notification for ClonOS * added tools/imgremove: script for safe removal CBSD images:      - we check that the file is an image of CBSD before deleting.      This script is mainly used by the ClonOS because it does not      have the right to delete files. * imghelper.c micro optimization: we search for the header only in   the first 1MB. If header signature is not detected - error 1.   This speeds up the validation of large files that are not CBSD images

diff --git a/tools/imgpart b/tools/imgpart
--- a/tools/imgpart
+++ b/tools/imgpart
@@ -1,5 +1,5 @@
 #!/usr/local/bin/cbsd
-#v10.1.0
+#v16.1.17
 MYARG="jname part mode"
 MYOPTARG="out hdrver compress emulator"
 MYDESC="Pack or extract chunk from from image"
@@ -31,11 +31,13 @@ extractchunk()
 		0)
 			[ -z "${out}" ] && out="/dev/stdout"
 			imghelper --start ${FROM} --end ${TO} --infile ${SRC} --outfile ${out}
+			[ $? -ne 0 ] && err 1 "${MAGENTA}imghelper error${NORMAL}"
 			echo >> ${out}
 			;;
 		1)
 			[ -z "${out}" ] && out=$( /bin/pwd )
 			imghelper --start ${FROM} --end ${TO} --infile ${SRC} | /usr/bin/tar xpf - -C "${out}" --numeric-owner
+			[ $? -ne 0 ] && err 1 "${MAGENTA}imghelper error${NORMAL}"
 			;;
 	esac
 
