fixes for forgotten replacewdir for rcconf

diff --git a/tools/imgpart b/tools/imgpart
--- a/tools/imgpart
+++ b/tools/imgpart
@@ -145,12 +145,20 @@ packme()
 			;;
 		rcconf)
 			# use jailrcconfdir for back compatible with CBSD < 10.1.0
+			_tmpout=$( /usr/bin/mktemp )
 			echo "___NCSTART_RCCONF=1" >> ${out}
 			if [ -f "${jailsysdir}/${jname}/rc.conf_${jname}" ]; then
-				/bin/cat $jailsysdir/$jname/rc.conf_${jname} >> ${out}
+				/bin/cat $jailsysdir/$jname/rc.conf_${jname} >> ${_tmpout}
 			else
-				[ -f "${jailrcconfdir}/rc.conf_${jname}" ] && /bin/cat ${jailrcconfdir}/rc.conf_${jname} >> ${out}
+				[ -f "${jailrcconfdir}/rc.conf_${jname}" ] && /bin/cat ${jailrcconfdir}/rc.conf_${jname} >> ${_tmpout}
 			fi
+			res=$( replacewdir file0="${_tmpout}" old=${workdir} new="CBSDROOT" )
+			if [ $? -ne 0 ]; then
+				/bin/rm -f ${_tmpout}
+				err 1 "${MAGENTA}Error in ${part} imgpart/replacewdir: ${res}${NORMAL}"
+			fi
+			/bin/cat ${_tmpout} >> ${out}
+			/bin/rm -f ${_tmpout}
 			echo >> ${out}
 			;;
 		pkginfo)
