style

diff --git a/tools/jail2iso b/tools/jail2iso
--- a/tools/jail2iso
+++ b/tools/jail2iso
@@ -1,27 +1,36 @@
 #!/usr/local/bin/cbsd
 #v12.0.12
-MYARG="jname dstdir media"
-MYOPTARG="dstname name label product publisher prunelist freesize host_hostname ip4_addr gw4 timezone nameserver nic inter quiet efi nobase swapsize fromfile vm_guestfs applytpl"
+MYARG="dstdir jname media"
+MYOPTARG="applytpl dstname efi freesize fromfile gw4 host_hostname inter ip4_addr label name nameserver nic nobase product prunelist publisher quiet swapsize timezone ver vm_guestfs"
 MYDESC="Convert jail into cd9660 ISO or memstick image"
-ADDHELP="\
- dstdir       = destination dir for storing jname.iso\n\
- dstname      = for alternative image name\n\
- name         = for alternative kernel name (GENERIC is default)\n\
- label        = label for media\n\
- media        = iso,memstick,livecd or bhyve\n\
- prunelist    = path to prunelist, default is \${sharedir}/jail2iso-prunelist. 0 for disable.\n\
- freesize     = reserved (expand to) X size of image free space (100m, 1g)\n\
- host_hostname= set hostname in rc.conf image (freebsd only)\n\
- ip4_addr     = set ip4 addr or 'DHCP' in rc.conf image (freebsd only\n\
- gw4          = gateway for IPv4\n\
- timezone     = set timezone in image (freebsd only)\n\
- nameserver   = set nameserver in image (freebsd only)\n\
- nic          = specify network nic for ip4_addr\n\
- efi          = - set 0 to disable efi by default (if efiboot.img exist its preffered boot method)\n\
- swapsize     = - Allocate/configure SWAP partition to X size\n\
- fromfile     = - Read arguments from file\n\
- vm_guestfs   = ufs or zfs. Default is: ufs\n\
- applytpl     = manage rc.conf for image, e.g set ip,hostname,nameserver. default - 1, apply\n\
+ADDHELP="
+
+${H3_COLOR}Description${N0_COLOR}:
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}applytpl=${N0_COLOR}     = manage rc.conf for image, e.g set ip,hostname,nameserver. default - 1, apply
+ ${N2_COLOR}dstdir=${N0_COLOR}       = destination dir for storing jname.iso
+ ${N2_COLOR}dstname=${N0_COLOR}      = for alternative image name
+ ${N2_COLOR}efi=${N0_COLOR}          = - set 0 to disable efi by default (if efiboot.img exist its preffered boot method)
+ ${N2_COLOR}freesize=${N0_COLOR}     = reserved (expand to) X size of image free space (100m, 1g)
+ ${N2_COLOR}fromfile=${N0_COLOR}     = - Read arguments from file
+ ${N2_COLOR}gw4=${N0_COLOR}          = gateway for IPv4
+ ${N2_COLOR}host_hostname=${N0_COLOR}  set hostname in rc.conf image (freebsd only)
+ ${N2_COLOR}ip4_addr=${N0_COLOR}     = set ip4 addr or 'DHCP' in rc.conf image (freebsd only
+ ${N2_COLOR}jname=${N0_COLOR}        = source data jail name
+ ${N2_COLOR}label=${N0_COLOR}        = label for media
+ ${N2_COLOR}media=${N0_COLOR}        = iso,memstick,livecd or bhyve
+ ${N2_COLOR}name=${N0_COLOR}         = for alternative kernel name (GENERIC is default)
+ ${N2_COLOR}nameserver=${N0_COLOR}   = set nameserver in image (freebsd only)
+ ${N2_COLOR}nic=${N0_COLOR}          = specify network nic for ip4_addr
+ ${N2_COLOR}prunelist=${N0_COLOR}    = path to prunelist, default is \${sharedir}/jail2iso-prunelist. 0 for disable.
+ ${N2_COLOR}swapsize=${N0_COLOR}     = - Allocate/configure SWAP partition to X size
+ ${N2_COLOR}timezone=${N0_COLOR}     = set timezone in image (freebsd only)
+ ${N2_COLOR}vm_guestfs=${N0_COLOR}   = ufs or zfs. Default is: ufs
+
+${H3_COLOR}Examples${N0_COLOR}:
+
 "
 EXTHELP="wf_jail2iso"
 
@@ -34,8 +43,11 @@ readconf jail2iso.conf
 EFI_PART_SIZE="260m"			# default FreeBSD efi partition
 
 applytpl=1
-
+ver=
+over=
 . ${cbsdinit}
+
+[ -n "${ver}" ] && over="${ver}"
 
 oapplytpl="${applytpl}"
 
@@ -53,6 +65,10 @@ oapplytpl="${applytpl}"
 
 . ${jrcconf}
 [ $? -eq 1 ] && err 1 "${N1_COLOR}no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+
+# restore orig ver after rcconf
+[ -n "${over}" ] && ver="${over}"
+
 [ ${jid} -ne 0 ] && err 1 "${N1_COLOR}jail is active. please stop them first: ${N2_COLOR}${jname}${N0_COLOR}"
 
 [ -r "${fromfile}" ] && . ${fromfile}
@@ -228,10 +244,12 @@ makemfsroot()
 
 	_filelist="${distsharedir}/${platform}-filemin_${_ver}.txt.xz"
 
+	[ ! -r ${_filelist} ] && err 1 "${N1_COLOR}${CBSD_APP}: no such index file: ${N2_COLOR}${_filelist}${N0_COLOR}"
+
 	${ECHO} "${N1_COLOR}mfsroot index: ${N2_COLOR}${_filelist}${N0_COLOR}"
 
 	copy-binlib filelist=${_filelist} dstdir=${_tmpdir} basedir=${BASE_DIR} chaselibs=1 mtree=1
-	echo
+
 	preparebase dst=${_tmpdir}
 
 	local _size=0
@@ -268,6 +286,8 @@ makemfsroot()
 	[ -d "${DST_DIR}/usr/bin" ] && ${RM_CMD} -rf ${DST_DIR}/usr/bin
 	${UMOUNT_CMD} -f ${DST_DIR} && ${RMDIR_CMD} ${DST_DIR}
 	${MDCONFIG_CMD} -d -u ${DEV}
+
+	${ECHO} "${N1_COLOR}${CBSD_APP} mfsroot done, temp md: ${N2_COLOR}${DEV}${N0_COLOR}" 1>&2
 }
 
 
@@ -458,7 +478,7 @@ check_for_external_mount()
 # Create full FS/data hier in ${TMP_DIR} directory
 make_ufs()
 {
-	${ECHO} "${N1_COLOR}kernel required: ${ver}${N0_COLOR}"
+	${ECHO} "${N1_COLOR}kernel required ver: ${ver}${N0_COLOR}" 1>&2
 	# move to kernel init?
 	get_kernel
 
@@ -496,12 +516,17 @@ make_ufs()
 	${MKDIR_CMD} -p ${TMP_DIR}
 	#echo "[debug] cd ${path} && nice -n 19 ${IDPRIO_CMD} 29 ${PAX_CMD} -p eme -rw . ${TMP_DIR}"
 
+	echo "make_ufs: media: ${media}"
+
 	# not for iso too ?
-	if [ "${media}" != "memstick" ]; then
-		echo "[debug]cd ${path} && nice -n 19 ${IDPRIO_CMD} 29 ${PAX_CMD} -p eme -rw . ${TMP_DIR}"
+	# new comment: why skip here ;-)
+#	if [ "${media}" != "memstick" ]; then
+#		echo
+		echo "[debug]cd ${path} && nice -n 19 ${IDPRIO_CMD} 29 ${PAX_CMD} -p eme -rw . ${TMP_DIR}" 1>&2
 		cd ${path} && nice -n 19 ${IDPRIO_CMD} 29 ${PAX_CMD} -p eme -rw . ${TMP_DIR}
 		sync
-	fi
+#		echo
+#	fi
 
 	[ "${media}" != "bhyve" ] && ${RM_CMD} -rf ${TMP_DIR}/rescue
 	[ "${prunelist}" != "0" ] && prunelist ${TMP_DIR}
@@ -510,7 +535,15 @@ make_ufs()
 	# BAD FOR packages
 	#[ "${media}" != "bhyve" ] && ${FIND_CMD} ${TMP_DIR} -type f -name \*.a -delete
 
-	${CP_CMD} -a ${KERNEL_DIR}/boot/kernel ${TMP_DIR}/boot
+	[ ! -d ${TMP_DIR}/boot/kernel ] && ${MKDIR_CMD} -p ${TMP_DIR}/boot/kernel
+
+	${CP_CMD} -a ${KERNEL_DIR}/boot/kernel/* ${TMP_DIR}/boot/kernel/
+
+	if [ ! -r "${TMP_DIR}/boot/kernel/kernel" ]; then
+		echo "no such ${TMP_DIR}/boot/kernel/kernel"
+		echo "check: ${CP_CMD} -a ${KERNEL_DIR}/boot/kernel/* ${TMP_DIR}/boot/kernel/"
+		read p
+	fi
 
 	if [ "${media}" != "bhyve" ]; then
 		${RM_CMD} -f ${TMP_DIR}/boot/kernel/*.symbols
@@ -685,6 +718,7 @@ EOF
 }
 
 # MAIN
+
 jcleanup jname=${jname}
 clear_tmp_dir
 [ ${baserw} -eq 1 ] && path=${data}
