initial bhyve support; move jailskeldir into jail.conf; rename pwait to cbsd_pwait; remove exec.clean by default; buildin is_number func in cbsd sh; and other small optimizations. bump version to 10.0.4

diff --git a/tools/jail2iso b/tools/jail2iso
--- a/tools/jail2iso
+++ b/tools/jail2iso
@@ -2,15 +2,22 @@
 #v10.0.4
 globalconf="${workdir}/cbsd.conf"
 MYARG="jname dstdir media"
-MYOPTARG="name label product publisher prunelist freesize"
+MYOPTARG="dstname name label product publisher prunelist freesize host_hostname ip4_addr gw4 timezone nameserver nic inter quiet"
 MYDESC="Convert jail into cd9660 ISO or memstick image"
 ADDHELP="dstdir= destination dir for storing jname.iso\n\
-name - for alternative kernel name (GENERIC is default)\n\
-label - label for media\n\
-media - iso,memstick or bhyve\n\
-prunelist= path to prunelist, default is ${sharedir}/jail2iso-prunelist\n\
-freesize= reserved (expand) for X image size (100m, 1g) of free space (primarily for bhyve img)\n"
-EXTHELP="html/wf_jail2iso_en.html"
+dstname= for alternative image name\n\
+name= for alternative kernel name (GENERIC is default)\n\
+label= label for media\n\
+media= iso,memstick or bhyve\n\
+prunelist= path to prunelist, default is \${sharedir}/jail2iso-prunelist. 0 for disable.\n\
+freesize= reserved (expand to) X size of image free space (100m, 1g)\n\
+host_hostname= set hostname in rc.conf image (freebsd only)\n\
+ip4_addr= set ip4 addr or 'DHCP' in rc.conf image (freebsd only\n\
+gw4= gateway for IPv4\n\
+timezone= set timezone in image (freebsd only)\n\
+nameserver= set nameserver in image (freebsd only)\n\
+nic= specify network nic for ip4_addr\n"
+EXTHELP="wf_jail2iso.html"
 
 [ -f "${globalconf}" ] || err 1 "no such conf file"
 . ${globalconf}
@@ -29,6 +36,7 @@ init $*
 . ${jrcconf}
 [ $? -eq 1 ] && err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
 
+[ -z "${quiet}" ] && quiet=0
 [ "${media}" = "bhyve" -a -z "${freesize}" ] && err 1 "${MAGENTA}For media=bhyve please set freesize= value. For example: ${GREEN}freesize=1g${NORMAL}"
 
 init_target_arch
@@ -201,6 +209,52 @@ prunelist()
     done
 }
 
+# $1 - rootdir
+epilogue_img()
+{
+    local _rootfs="${1}"
+    [ -z "${_rootfs}" -a ! -d "${_rootfs}" ] && return 0
+    [ -z "${nic}" ] && nic="vtnet0"
+
+    sysrc -qf ${_rootfs}/etc/rc.conf fsck_y_enable="YES" >/dev/null
+
+    if [ -n "${host_hostname}" ]; then
+	sysrc -qf ${_rootfs}/etc/rc.conf hostname="${host_hostname}" >/dev/null
+#	chroot ${_rootfs} /bin/sh << EOF
+#hostname ${host_hostname}
+#make -C /etc/mail
+#EOF
+    fi
+
+    if [ -n "${ip4_addr}" ]; then
+	case "${ip4_addr}" in
+		[Dd][Hh][Cc][Pp])
+			sysrc -qf ${_rootfs}/etc/rc.conf ifconfig_${nic}="DHCP" >/dev/null
+			;;
+		*)
+			sysrc -qf ${_rootfs}/etc/rc.conf ipv4_addrs_${nic}="${ip4_addr}" >/dev/null
+		#	[ -n "${host_hostname}" ] && echo "${ip4_addr} ${host_hostname" >> ${_rootfs}/etc/hosts
+	esac
+    fi
+
+    if [ -n "${gw4}" ]; then
+	sysrc -qf ${_rootfs}/etc/rc.conf defaultrouter="${gw4}" >/dev/null
+    fi
+
+    if [ -n "${nameserver}" ]; then
+	IFS=","
+	for i in ${nameserver}; do
+		echo "nameserver ${i}" >> ${_rootfs}/etc/resolv.conf
+	done
+	unset IFS
+    fi
+
+    if [ -n "${timezone}" ]; then
+	[ -f "/usr/share/zoneinfo/${timezone}" ] && cp /usr/share/zoneinfo/${timezone} ${_rootfs}/etc/localtime
+    fi
+}
+
+
 
 makemfsroot()
 {
@@ -215,7 +269,7 @@ makemfsroot()
     make_libmap
     copy_binlib
     prepare_dir
-    prunelist ${DST_DIR}
+    [ "${prunelist}" != "0" ] && prunelist ${DST_DIR}
     cd /
     # make flags for preparedir script
     [ -d "${DST_DIR}/usr/bin" ] && rm -rf ${DST_DIR}/usr/bin
@@ -225,11 +279,38 @@ makemfsroot()
 }
 
 
+show_bhyve_message()
+{
+    $ECHO "${MAGENTA}Completed. Image ready for bhyve, example:${NORMAL}"
+    cat << EOF
+ % kldload vmm
+ % kldload if_tap
+ % sysctl -w net.link.tap.up_on_open=1
+ % ifconfig tap0 create
+ % ifconfig bridge0 create
+EOF
+    ${ECHO} " % ifconfig bridge0 addm ${mynic} addm tap0    ${GREEN}<< -- where ${mynic} is uplink${NORMAL}"
+    cat << EOF
+ % ifconfig bridge0 up
+ % sh /usr/share/examples/bhyve/vmrun.sh -d ${dstdir}/${dstname} ${jname}
+EOF
+}
+
+
 # MAIN
 clear_tmp_dir
 [ $baserw -eq 1 ] && path=$data
 
-[ -z "${prunelist}" ] && prunelist="${sharedir}/jail2iso-prunelist"
+[ "${prunelist}" != "0" ] && prunelist="${sharedir}/jail2iso-prunelist"
+
+[ ! -d "${BASE_DIR}" ] && err 1 "${MAGENTA}No base data on: ${GREEN}${BASE_DIR}${NORMAL}"
+
+# move to kernel init?
+if [ ! -d "${KERNEL_DIR}" ]; then
+    getyesno "No kernel ${KERNEL_DIR}. Try to fetch from remote repository?"
+    [ $? -eq 1 -o $? -eq 3 ] && err 1 "${MAGENTA}No base data on: ${GREEN}${KERNEL_DIR}${NORMAL}"
+    cbsd repo action=get sources=kernel arch=${arch} ver=${ver} target_arch=${target_arch}
+fi
 
 [ ! -d "${KERNEL_DIR}" ] && err 1 "No such ${KERNEL_DIR}"
 [ "$media" = "iso" -o "$media" = "memstick" -o "${media}" = "bhyve" ] || err 1 "${MAGENTA}Unknown media type. Must be: ${GREEN}iso${MAGENTA},${GREEN} memstick ${MAGENTA}or${GREEN} bhyve${NORMAL}"
@@ -247,7 +328,7 @@ cp -a ${path} ${TMP_DIR}
 
 [ "${media}" != "bhyve" ] && rm -rf ${TMP_DIR}/rescue
 
-prunelist ${TMP_DIR}
+[ "${prunelist}" != "0" ] && prunelist ${TMP_DIR}
 
 # remove archive
 find ${TMP_DIR} -type f -name \*.a -delete
@@ -276,6 +357,10 @@ EOF
 else
 cat >> ${TMP_DIR}/boot/loader.conf <<EOF
 console="userboot"
+#virtio_load="YES"
+#virtio_pci_load="YES"
+#virtio_blk_load="YES"
+#if_vtnet_load="YES"
 EOF
 fi
 
@@ -287,7 +372,8 @@ case "${media}" in
     ROOTFS="/dev/ufs/${LABEL} /mnt ufs ro,noatime 1 1"
     ;;
 "bhyve")
-    ROOTFS="/dev/vtbd0 / ufs rw 1 1"
+#    ROOTFS="/dev/vtbd0 / ufs rw 1 1"
+    ROOTFS="/dev/ufs/${LABEL} / ufs rw 1 1"
     ;;
 esac
 
@@ -329,49 +415,42 @@ console "/usr/libexec/getty std.9600"   vt100   on secure
 EOF
 fi
 
+# post action inside image
+epilogue_img ${TMP_DIR}
+
+
 case "${media}" in
-"iso")
-    /usr/local/cbsd/release/mkisoimages.sh ${LABEL} ${dstdir}/${jname}-${ver}_${arch}.iso ${TMP_DIR}
-    ;;
-"memstick")
-    makefs -B little -o label=${LABEL} ${dstdir}/${jname}-${ver}_${arch}.img ${TMP_DIR}
-
-    [ $? -ne 0 ] && err 1 "makefs failed"
-
-    unit=`mdconfig -a -t vnode -f ${dstdir}/${jname}-${ver}_${arch}.img`
-    [ $? -ne 0 ] && err 1 "mdconfig failed"
-    gpart create -s BSD ${unit}
-    gpart bootcode -b ${TMP_DIR}/boot/boot ${unit}
-    gpart add -t freebsd-ufs ${unit}
-    mdconfig -d -u ${unit}
-    ;;
-"bhyve")
-    makefs -o label="${LABEL}" ${dstdir}/${jname}-${ver}_${arch}.img ${TMP_DIR}
-    if [ $? -eq 0 -a -n "${freesize}" ]; then
-	${ECHO} "${MAGENTA}Expand image size up to: ${GREEN}${freesize}${NORMAL}"
-	truncate -s +${freesize} ${dstdir}/${jname}-${ver}_${arch}.img
-	md=$(mdconfig -a -t vnode -f ${dstdir}/${jname}-${ver}_${arch}.img)
-	growfs -y /dev/${md}
-	if [ $? -eq 0 ]; then
-	    mynic=$( cbsd getnics-by-ip ip=0.0.0.0 2>/dev/null )
-	    [ -z "${mynic}" ] && mynic="em0"
-	    $ECHO "${MAGENTA}Completed. Image ready for bhyve, example:${NORMAL}"
-	    cat << EOF
- % kldload vmm
- % kldload if_tap
- % sysctl -w net.link.tap.up_on_open=1
- % ifconfig tap0 create
- % ifconfig bridge0 create
-EOF
-	    ${ECHO} " % ifconfig bridge0 addm ${mynic} addm tap0    ${GREEN}<< -- where ${mynic} is uplink${NORMAL}"
-	cat << EOF
- % ifconfig bridge0 up
- % sh /usr/share/examples/bhyve/vmrun.sh -d ${dstdir}/${jname}-${ver}_${arch}.img ${jname}
-EOF
-	fi
-	mdconfig -d -u ${md}
-    fi
-    ;;
+	"iso")
+	    [ -z "${dstname}" ] && dstname="${jname}-${ver}_${arch}.iso"
+	    /usr/local/cbsd/release/mkisoimages.sh ${LABEL} ${dstdir}/${dstname} ${TMP_DIR}
+	    ;;
+	"memstick")
+	    [ -z "${dstname}" ] && dstname="${jname}-${ver}_${arch}.img"
+	    makefs -B little -o version=2 -o label=${LABEL} ${dstdir}/${dstname} ${TMP_DIR}
+	    [ $? -ne 0 ] && err 1 "makefs failed"
+	    unit=`mdconfig -a -t vnode -f ${dstdir}/${dstname}`
+	    [ $? -ne 0 ] && err 1 "mdconfig failed"
+	    gpart create -s BSD ${unit}
+	    gpart bootcode -b ${TMP_DIR}/boot/boot ${unit}
+	    gpart add -t freebsd-ufs ${unit}
+	    mdconfig -d -u ${unit}
+	    ;;
+	"bhyve")
+	    [ -z "${dstname}" ] && dstname="${jname}-${ver}_${arch}.img"
+	    makefs -o version=2 -o label="${LABEL}" ${dstdir}/${dstname} ${TMP_DIR}
+	    if [ $? -eq 0 -a -n "${freesize}" ]; then
+		${ECHO} "${MAGENTA}Expand image size up to: ${GREEN}${freesize}${NORMAL}"
+		truncate -s +${freesize} ${dstdir}/${dstname}
+		md=$(mdconfig -a -t vnode -f ${dstdir}/${dstname})
+		growfs -y /dev/${md}
+		if [ $? -eq 0 ]; then
+		    mynic=$( cbsd getnics-by-ip ip=0.0.0.0 2>/dev/null )
+		    [ -z "${mynic}" ] && mynic="em0"
+		    [ ${quiet} -eq 0 ] && show_bhyve_message
+		fi
+		mdconfig -d -u ${md}
+	    fi
+	    ;;
 esac
 
 [ "${ver}" != "empty" ] && cbsd unmountfstab jroot=${path} fstab=${mount_fstab} > /dev/null 2>&1
diff --git a/tools/jconstruct b/tools/jconstruct
--- a/tools/jconstruct
+++ b/tools/jconstruct
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v9.2.2
+#v10.0.5
 MYDESC="console dialog for jail creation"
 globalconf="${workdir}/cbsd.conf";
 MYARG=""
@@ -17,15 +17,21 @@ init $*
 get_jname()
 {
     freejname
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="${freejname}"
+    _default="${freejname}"
     _input=""
     while [ x${_input} = x ]; do
-	$ECHO "${BOLD}${GET_JNAME_MSG} e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	$ECHO "${BOLD}${GET_JNAME_MSG} e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
 	if validate_jname ${_input}; then
+	    _input=""
+	fi
+
+	/usr/local/bin/cbsd jstatus jname=${_input}
+	if [ $? -ne 0 ]; then
+	    ${ECHO} "${MAGENTA}ERROR: Jail ${GREEN}${_input}${MAGENTA} already exist. Try again${NORMAL}"
 	    _input=""
 	fi
     done
@@ -35,14 +41,14 @@ get_jname()
 # $fqdn
 get_jail_fqdn()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="${jname}.my.domain"
+    _default="${jname}.my.domain"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_FQDN_MSG} e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_FQDN_MSG} e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
     export fqdn=${_input}
 }
@@ -64,20 +70,14 @@ get_jail_ips()
 # $oninterface
 get_jail_oninterface()
 {
-    local DEFAULT _input
+    local _default _input
 
-    if [ -z "${interface}" -o "${interface}" = "auto" ]; then
-	if [ -n "${ip4_addr}" ]; then
-	    DEFAULT=`cbsd getnics-by-ip ip=${ip4_addr}`
-	else
-	    DEFAULT=`cbsd getnics-by-ip ip=0.0.0.0`
-	fi
-    fi
+    _default="${interface}"
 
     while [ x${_input} = x ]; do
-	$ECHO "${BOLD}${GET_ONINTERFACE_MSG} e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	$ECHO "${BOLD}${GET_ONINTERFACE_MSG} e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export interface=${_input}
@@ -86,14 +86,14 @@ get_jail_oninterface()
 # $base
 get_jail_base()
 {
-    local _input DEFAULT
+    local _input _default
 
-    DEFAULT="${ver}"
+    _default="${ver}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_BASE_MSG} e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_BASE_MSG} e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export ver=${_input}
@@ -102,14 +102,14 @@ get_jail_base()
 # $base
 get_jail_arch()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="${arch}"
+    _default="${arch}"
 
     while [ x${_input} = x ]; do
 	${ECHO} "${BOLD}${GET_ARCH_MSG} e.g: ${GREEN}${arch}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export arch=${_input}
@@ -119,14 +119,14 @@ get_jail_arch()
 # $baserw
 get_jail_baserw()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="0"
+    _default="${baserw}"
 
     while [ x${_input} = x ]; do
-	$ECHO "${BOLD}${GET_BASERW_MSG} ( 0 - nullfs base mount in RO, 1 - no nullfs, RW ) e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	$ECHO "${BOLD}${GET_BASERW_MSG} ( 0 - nullfs base mount in RO, 1 - no nullfs, RW ) e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export baserw=${_input}
@@ -135,14 +135,14 @@ get_jail_baserw()
 # $mount_src
 get_jail_mount_src()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="0"
+    _default="${mount_src}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_SRCMOUNT_MSG} (0 - no, 1 - yes): e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_SRCMOUNT_MSG} (0 - no, 1 - yes): e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export mount_src=${_input}
@@ -151,14 +151,14 @@ get_jail_mount_src()
 # $mount_obj
 get_jail_mount_obj()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="0"
+    _default="${mount_obj}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_OBJMOUNT_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_OBJMOUNT_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export mount_obj=${_input}
@@ -167,14 +167,14 @@ get_jail_mount_obj()
 # $mount_ports
 get_jail_mount_ports()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="1"
+    _default="${mount_ports}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_PORTSMOUNT_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_PORTSMOUNT_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export mount_ports=${_input}
@@ -184,14 +184,14 @@ get_jail_mount_ports()
 # $applytpl
 get_jail_applytpl()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="1"
+    _default="${applytpl}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_APPLYTPL_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_APPLYTPL_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export applytpl=${_input}
@@ -200,34 +200,31 @@ get_jail_applytpl()
 # $applytpl
 get_jail_floatresolv()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="1"
+    _default="${floatresolv}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_FLOATRESOLV_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${DEFAULT}${NORMAL}"
+	${ECHO} "${BOLD}${GET_FLOATRESOLV_MSG} ( 0 - no, 1 - yes) e.g: ${GREEN}${_default}${NORMAL}"
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export floatresolv=${_input}
 }
 
 
-
-
-
 # $astart
 get_jail_astart()
 {
-    local DEFAULT _input
+    local _default _input
 
-    DEFAULT="1"
+    _default="${astart}"
 
     while [ x${_input} = x ]; do
-	${ECHO} "${BOLD}${GET_ASTART_MSG} ( 0 - no, 1 -yes) e.g: ${GREEN}${DEFAULT}${NORMAL} "
+	${ECHO} "${BOLD}${GET_ASTART_MSG} ( 0 - no, 1 -yes) e.g: ${GREEN}${_default}${NORMAL} "
 	read _input
-	[ -z "${_input}" ] && _input="${DEFAULT}"
+	[ -z "${_input}" ] && _input="${_default}"
     done
 
     export astart=${_input}
@@ -303,6 +300,7 @@ done
 
 #defaults
 . ${buildconf}
+readconf jail.conf
 
 get_jname &&  \
 get_jail_fqdn && \
