boot1.efifat deprecated in current

diff --git a/tools/jail2iso b/tools/jail2iso
--- a/tools/jail2iso
+++ b/tools/jail2iso
@@ -706,7 +706,27 @@ case "${media}" in
 					_swap_args=
 			fi
 				if [ ${efi} -eq 1 ]; then
-					${MKIMG_CMD} -s gpt -b ${TMP_DIR}/boot/pmbr -p efi:=${TMP_DIR}/boot/boot1.efifat -p freebsd-boot:=${TMP_DIR}/boot/gptboot ${_swap_args} -p freebsd-ufs:=${dstdir}/${dstname}.part -o ${dstdir}/${dstname}
+					# efifat was deprecated in 12.2-RELEASE
+					if [ -r ${TMP_DIR}/boot/boot1.efifat ]; then
+						${MKIMG_CMD} -s gpt -b ${TMP_DIR}/boot/pmbr -p efi:=${TMP_DIR}/boot/boot1.efifat -p freebsd-boot:=${TMP_DIR}/boot/gptboot ${_swap_args} -p freebsd-ufs:=${dstdir}/${dstname}.part -o ${dstdir}/${dstname}
+					elif [ -r ${TMP_DIR}/boot/boot1.efi ]; then
+
+	truncate -s64M /tmp/efi.efi
+	unit=$( ${MDCONFIG_CMD} -a -t vnode -f /tmp/efi.efi 2>&1 )
+	[ $? -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: mdconfig ${W1_COLOR}failed${N2_COLOR} ${unit}${N0_COLOR}"
+	echo "stamp loader.efi: /tmp/efi.efi"
+	tmp_mp=$( ${MKTEMP_CMD} -d )
+	newfs_msdos -F 32 -c 1 /dev/${unit}
+	mount -t msdosfs /dev/${unit} ${tmp_mp}
+	mkdir -p ${tmp_mp}/EFI/BOOT
+	cp /boot/loader.efi ${tmp_mp}/EFI/BOOT/BOOTX64.efi
+	umount ${tmp_mp}
+	rmdir ${tmp_mp}
+	mdconfig -d -u ${unit}
+						${MKIMG_CMD} -s gpt -b ${TMP_DIR}/boot/pmbr -p efi:=/tmp/efi.efi -p freebsd-boot:=${TMP_DIR}/boot/gptboot ${_swap_args} -p freebsd-ufs:=${dstdir}/${dstname}.part -o ${dstdir}/${dstname}
+					else
+						err 1 "${N1_COLOR}${CBSD_APP}: no such boot1.efi or loader.efi${N0_COLOR}"
+					fi
 				else
 					${MKIMG_CMD} -s gpt -b ${TMP_DIR}/boot/pmbr -p freebsd-boot:=${TMP_DIR}/boot/gptboot ${_swap_args} -p freebsd-ufs:=${dstdir}/${dstname}.part -o ${dstdir}/${dstname}
 				fi
