move prepare_jail from pkg module to tools.subr: useful not only for pkg; Rewrite imghelper to work with SQLite-based registry of helper settings

diff --git a/tools/jail2iso b/tools/jail2iso
--- a/tools/jail2iso
+++ b/tools/jail2iso
@@ -367,7 +367,11 @@ bhyve_zfs_install()
 	done )
 
 	[ $? -ne 0 ] && err 1 "${MAGENTA}Can't find free pool name: ${GREEN}${mypool}${NORMAL}"
+
+	echo "zfsinstall devs=${unit} srcdata=${data} mnt=${mnttmp} pool=${mypool} swap=\"${swapsize}\" quiet=1"
+	read p
 	zfsinstall devs=${unit} srcdata=${data} mnt=${mnttmp} pool=${mypool} swap="${swapsize}" quiet=1
+	[ $? -ne 0 ] && err 1 "${MAGENTA}Error for zfsinstall${NORMAL}"
 
 	# hack for remove all dirty zpool 
 	/bin/cat > ${mnttmp}/etc/rc.local <<EOF
@@ -386,10 +390,10 @@ fi
 /bin/rm -f /etc/rc.local
 EOF
 	epilogue_img ${mnttmp}
-	/sbin/umount ${mnttmp}/var
-	/sbin/umount ${mnttmp}/tmp
-	/sbin/umount ${mnttmp}
-	/bin/rmdir ${mnttmp}
+	/sbin/umount ${mnttmp}/var > /dev/null 2>&1
+	/sbin/umount ${mnttmp}/tmp > /dev/null 2>&1
+	/sbin/umount ${mnttmp} > /dev/null 2>&1
+	/bin/rmdir ${mnttmp} > /dev/null 2>&1
 	/sbin/zpool export -f ${mypool}
 }
 
