bhyve: cloud-init wip

diff --git a/tools/media b/tools/media
--- a/tools/media
+++ b/tools/media
@@ -471,18 +471,42 @@ eject()
 	cbsdsql storage_media "UPDATE media SET jname='-' WHERE jname=\"${jname}\" AND type=\"iso\""
 }
 
+which_vm_depens_on_zvol()
+{
+	local _vm_list _vol="${1}"
+
+	[ -z "${_vol}" ] && return 0
+
+	_vm_list=$( /sbin/zfs list -H -r -t snapshot -o name ${_vol} | /usr/bin/cut -d '@' -f 2 | /usr/bin/cut -d '-' -f 2 | /usr/bin/xargs )
+
+	[ -z "${_vm_list}" ] && return 0
+	printf "${_vm_list}"
+	return 1
+}
+
+
 # try to remove ISO file
 try_to_rm()
 {
 	local path="${1}"
+	local _vm_list
 
 	[ -z "${path}" ] && err 1 "${MAGENTA}media: try_to_rm: empty path${NORMAL}"
 
 	. ${zfstool}
 	if is_getzvol ${path}; then
-		/sbin/zfs destroy ${is_zvol}
-		_ret=$?
-		[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Unable to destroy zvol, please remove it by hand: ${GREEN}${is_zvol}${NORMAL}"
+		/sbin/zfs list ${is_zvol} > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+
+			_vm_list=$( which_vm_depens_on_zvol ${is_zvol} )
+
+			[ -n "${_vm_list}" ] && err 1 "${MAGENTA}Current vm depends from ${is_zvol}: ${GREEN}${_vm_list}${NORMAL}"
+
+			# zvol exist
+			/sbin/zfs destroy ${is_zvol}
+			_ret=$?
+			[ ${_ret} -ne 0 ] && err 1 "${MAGENTA}Unable to destroy zvol, please remove it by hand: ${GREEN}${is_zvol}${NORMAL}"
+		fi
 	fi
 	/bin/rm -f ${path}
 	return 0
@@ -585,7 +609,8 @@ case "${mode}" in
 
 		if [ -n "${name}" -a -n "${path}" ]; then
 
-			try_to_rm ${path}
+			# need before actual delete from SQL due to zvol deps check
+			[ "${type}" = "iso" ] && try_to_rm ${path}
 
 			if [ "${jname}" = "-" ]; then
 				cbsdsql storage_media "DELETE FROM media WHERE name=\"${name}\" AND path=\"${path}\" AND type=\"${type}\""
@@ -599,6 +624,8 @@ case "${mode}" in
 				path="${vm_res}"
 				cbsdsql storage_media "DELETE FROM media WHERE name=\"${name}\" AND jname=\"${jname}\""
 			elif [ -n "${path}" ]; then
+				# need before actual delete from SQL due to zvol deps check
+				[ "${type}" = "iso" ] && try_to_rm ${path}
 				cbsdsql storage_media "DELETE FROM media WHERE path=\"${path}\" AND jname=\"${jname}\""
 			fi
 		fi
@@ -629,16 +656,10 @@ case "${mode}" in
 		;;
 	deleteall|removeall)
 		for i in $( cbsdsql storage_media SELECT path FROM media WHERE type != \"hdd\" ); do
-			cbsdsql storage_media "DELETE FROM media WHERE path=\"${i}\""
-			[ -r "${i}" ] && /bin/rm -f ${i}
+			${ECHO} "${MAGENTA}removing: ${GREEN}${i}${MAGENTA} ...${NORMAL}"
+			media mode=remove path="${i}" type="iso"
 		done
-
-		# CBSD QUEUE
-		if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
-			[ "${cbsd_queue_name}" != "none" ] && cbsd_queue cbsd_queue_name=${cbsd_queue_name} cmd=refresh
-		fi
-
-		err 0 "${MAGENTA}Deleted${NORMAL}"
+		exit 0
 		;;
 	update)
 		[ -n "${type}" ] && update_type
