zfs jail feature: wip

diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v9.2.0
+#v10.0.0
 globalconf="${workdir}/cbsd.conf";
 MYARG="jroot fstab"
 MYOPTARG=""
@@ -16,47 +16,48 @@ SYSMNT=`/sbin/mount |grep " on " |awk '{printf $3" "}'`
 [ -d "${jroot}" ] || err 1 "${jroot} does not exist"
 
 cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
-case ":${_device}" in
-:#* | :)
-continue
-;;
-*)
-[ -z "${_device}" ] && continue
-echo ${_device} |grep -sq ^/
-[ $? -eq 0 -a ! -d "${_device}" ] && {
-TMPLOG=`mktemp ${ftmpdir}/fstab.XXX`
-trap "rm -f ${TMPLOG}" 0 1 2 3 4 5
-echo "Source dir ${_device} doesn't exist" > ${TMPLOG}
-}
-;;
-esac
+    [ "${_fs}" = "zfs" ] && continue
+    case ":${_device}" in
+	:#* | :)
+	continue
+	;;
+    *)
+	[ -z "${_device}" ] && continue
+	echo ${_device} |grep -sq ^/
+	if [ $? -eq 0 -a ! -d "${_device}" ]; then
+	    TMPLOG=`mktemp ${ftmpdir}/fstab.XXX`
+	    trap "rm -f ${TMPLOG}" 0 1 2 3 4 5
+	    echo "Source dir ${_device} doesn't exist" > ${TMPLOG}
+	fi
+	;;
+    esac
 done
 
-[ -f "${TMPLOG}" ] && {
-	ERRORLOG=`cat $TMPLOG`
-	rm -f ${TMPLOG}
-	err 1 "$ERRORLOG"
-}
-
+if [ -f "${TMPLOG}" ]; then
+    ERRORLOG=`cat $TMPLOG`
+    rm -f ${TMPLOG}
+    err 1 "$ERRORLOG"
+fi
 
 cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
-case ":${_device}" in
-:#* | :)
-continue
-;;
-esac
+    [ "${_fs}" = "zfs" ] && continue
+    case ":${_device}" in
+	:#* | :)
+	continue
+	;;
+    esac
 
-mnt=0
-for _MNT in ${SYSMNT}; do
-    if [ "${_MNT}" = "${jroot}${_mountpt}" ]; then
-    echo "${jroot}${_mountpt} already mounted"
-    mnt=1
+    mnt=0
+    for _MNT in ${SYSMNT}; do
+	if [ "${_MNT}" = "${jroot}${_mountpt}" ]; then
+	    echo "${jroot}${_mountpt} already mounted"
+	    mnt=1
+	fi
+    done
+
+    if [ ${mnt} -eq 0 ]; then
+	[ ! -d "${jroot}${_mountpt}" ] && mkdir -p ${jroot}${_mountpt}
+	[ ! -d "${jroot}${_mountpt}" ] && echo "Warning: Can't create ${jroot}${_mountpt} - permission problem ?"
+	/sbin/mount -t ${_fs} -o${_mode} ${_device} ${jroot}${_mountpt}
     fi
-done
-
-if [ ${mnt} -eq 0 ]; then
-    [ ! -d "${jroot}${_mountpt}" ] && mkdir -p ${jroot}${_mountpt}
-    [ ! -d "${jroot}${_mountpt}" ] && echo "Warning: Can't create ${jroot}${_mountpt} - permission problem ?"
-    /sbin/mount -t ${_fs} -o${_mode} ${_device} ${jroot}${_mountpt}
-fi
 done
