geli: WIP. exec_consolelog in jconfig added

diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -1,8 +1,8 @@
 #!/bin/sh
-#v10.0.3
+#v10.0.4
 globalconf="${workdir}/cbsd.conf";
 MYARG="jroot fstab"
-MYOPTARG=""
+MYOPTARG="jname"
 MYDESC="Mount jail by fstab file"
 ADDHELP="jroot - root of jail, fstab - fstab file\n"
 
@@ -23,6 +23,11 @@ cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 	continue
 	;;
     *)
+	[ "${_fs}" = "zfs" ] && continue
+	if [ "${_fs}" = "geli" ]; then
+	     is_mounted ${gelidir} && continue
+	     err 1 "Error: ${gelidir} is not initializated. Please use: 'cbsd geli mode=initmaster' first"
+	fi
 	[ -z "${_device}" ] && continue
 	echo ${_device} |grep -sq ^/
 	[ $? -ne 0 ] && _device="${workdir}/${_device}"
@@ -50,6 +55,20 @@ cat ${fstab} | while read _device _mountpt _fs _mode _a _b; do
     esac
 
     mnt=0
+
+    if [ "${_fs}" = "geli" ]; then
+    # prepare src part
+	echo "${_device}"|grep -sq ^/
+	if [ $? -ne 0 ]; then
+	    if [ -z "${jname}" ]; then
+		_device="${workdir}/${_device}"
+	    else
+		_device="${jailsysdir}/${jname}/${_device}"
+	    fi
+	fi
+	cbsd attachgeli file="${_device}" dst="${jroot}${_mountpt}" mode="${_mode}"
+	continue
+    fi
 
     echo ${_device} |grep -sq ^/
     [ $? -ne 0 ] && _device="${workdir}/${_device}"
