mountfstab: support for multiple jname or jname by mask, Issue #729
also valid call:
  cbsd mountfstab jail1 jail2 jail3
  cbsd mountfstab jname=jai*

diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -35,6 +35,9 @@ ${H3_COLOR}Examples${N0_COLOR}:
 2)
 # cbsd mountfstab fstab=/tmp/fstab jroot=/usr/jails/jails/myjail1
 
+# cbsd mountfstab jname='*'
+# cbsd mountfstab jail1 jail2
+
 ${H3_COLOR}See also${N0_COLOR}:
 
  cbsd unmountfstab --help
@@ -53,16 +56,14 @@ jroot=
 . ${cbsdinit}
 . ${system}
 
-if [ -z "${fstab}" -a -z "${jroot}" ]; then
-	# mount by jname ?
-	[ -z "${jname}" -a -z "${1}" ] && err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}mandatory params: ${N2_COLOR}fstab= jroot= ${N1_COLOR}or ${N2_COLOR}jname=${N0_COLOR}"
-	[ -z "${jname}" ] && jname="${1}"
-
-	# TODO: multiple jailname support? by mask (jname='*') and/or: 'cbsd mountfstab jail1 jail2 jail3 ..' ?
-
+mountfstab_by_jname()
+{
 	. ${subrdir}/rcconf.subr
 
-	[ $? -eq 1 ] && err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+	if [ $? -eq 1 ]; then
+		${ECHO} "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
+		return 1
+	fi
 
 	if [ ${baserw} -eq 0 ]; then
 		_jroot="${path}"
@@ -82,7 +83,23 @@ if [ -z "${fstab}" -a -z "${jroot}" ]; then
 		ret=$?
 		[ ${ret} -ne 0 ] && err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}mountfstab jroot=\"${_jroot}\" fstab=\"${mount_fstab}.local\"${N0_COLOR}"
 	fi
+}
 
+if [ -z "${fstab}" -a -z "${jroot}" ]; then
+	# mount by jname
+	[ -z "${jname}" -a -z "${1}" ] && err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}mandatory params: ${N2_COLOR}fstab= jroot= ${N1_COLOR}or ${N2_COLOR}jname=${N0_COLOR}"
+	[ -z "${jname}" ] && jname="${*}"
+
+	emulator="jail"         # for jname_is_multiple
+	jname_is_multiple
+
+	[ -z "${jail_list}" ] && jail_list="${jname}"
+
+	if [ -n "${jail_list}" ]; then
+		for jname in ${jail_list}; do
+			mountfstab_by_jname
+		done
+	fi
 	exit ${ret}
 fi
 
