WIP: volumes support

diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -253,6 +253,20 @@ ${CAT_CMD} ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 			;;
 	esac
 
+	# don't allow "..", "()", "|" in path
+	echo "${_device}" | ${GREP_CMD} -qE '(\.\.)|(\|)|(\()|(\))'
+	if [ $? -eq 0 ]; then
+		${ECHO} "${W1_COLOR}${CIX_APP} warning: .. not allowed: ${N2_COLOR}${_device}${N0_COLOR}"
+		continue
+	fi
+
+	# don't allow "..", "()", "|" in path
+	echo "${_mountpt}" | ${GREP_CMD} -qE '(\.\.)|(\|)|(\()|(\))'
+	if [ $? -eq 0 ]; then
+		${ECHO} "${W1_COLOR}${CIX_APP} warning: .. not allowed: ${N2_COLOR}${_mountpt}${N0_COLOR}"
+		continue
+	fi
+
 	# SKIP mount when mount point also exist in fstab.local. fstab.local is preferred
 	if [ ${have_local} -eq 1 ]; then
 		if ! check_for_localmpt_fstab ${_mountpt}; then
@@ -284,27 +298,27 @@ ${CAT_CMD} ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 	fi
 
 	_spec_device=${_device%%/*}
-	echo "SPEC: ${_device} -> ${_spec_device}"
 	# Detect/recognize entries like: 'WORKDIR_VOLUMES/home    /home   nullfs  rw 0 0'
 	# and map to ~cbsd/VOLUMES dataset's
 	if [ "${_spec_device}" = "WORKDIR_VOLUMES" ]; then
+		[ "${_fs}" != "nullfs" ] && log_err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}only nullfs supported for WORKDIR_VOLUMES: ${N2_COLOR}${_fs}${N0_COLOR}"
 		_rvolpath="${_device#*/}"
 		_volpath="/${_rvolpath}"
-		${ECHO} "${N1_COLOR}${CIX_APP}: WORKDIR_VOLUMES: ${N2_COLOR}${cbsd_workdir}/${jname}/data -> ${_volpath}${N0_COLOR}" 1>&2
-		_device="${workdir}/VOLUMES"
-		continue
-	fi
-
-	if [ "${_fs}" = "nullfs" ]; then
-		if [ "${prefix}" != "/" ]; then
-			_device="${workdir}/${_device}"
-		else
-			if ! [ -d "${_device}" ]; then
-				if [ ! -c "${_device}" -o ! -b "${_device}" ]; then
-					# notes: Unix socket not supported by nullfs, only regular files
-					if [ ! -f "${_device}" ]; then
-						${ECHO} "${W1_COLOR}${CIX_APP} warning: ${N1_COLOR}mountfstab: no such source (directory or file) for jail ${jname}: ${N2_COLOR}${_device}${N0_COLOR}"
-						continue
+		_device="${workdir}/VOLUMES/${jname}-data/${_rvolpath}"
+		${ECHO} "${N1_COLOR}${CIX_APP}: WORKDIR_VOLUMES: ${N2_COLOR}${_device} -> ${_volpath}${N0_COLOR}" 1>&2
+		[ ! -d "${_device}" ] && log_err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}no such volume directory: ${N2_COLOR}${_device}${N0_COLOR}"
+	else
+		if [ "${_fs}" = "nullfs" ]; then
+			if [ "${prefix}" != "/" ]; then
+				_device="${workdir}/${_device}"
+			else
+				if ! [ -d "${_device}" ]; then
+					if [ ! -c "${_device}" -o ! -b "${_device}" ]; then
+						# notes: Unix socket not supported by nullfs, only regular files
+						if [ ! -f "${_device}" ]; then
+							${ECHO} "${W1_COLOR}${CIX_APP} warning: ${N1_COLOR}mountfstab: no such source (directory or file) for jail ${jname}: ${N2_COLOR}${_device}${N0_COLOR}"
+							continue
+						fi
 					fi
 				fi
 			fi
