WIP: volumes support

diff --git a/tools/mountfstab b/tools/mountfstab
--- a/tools/mountfstab
+++ b/tools/mountfstab
@@ -58,8 +58,9 @@ jroot=
 
 mountfstab_by_jname()
 {
-	. ${subrdir}/rcconf.subr
+	local _jroot= _ret=
 
+	. ${subrdir}/rcconf.subr
 	if [ $? -eq 1 ]; then
 		${ECHO} "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}no such jail: ${N2_COLOR}${jname}${N0_COLOR}"
 		return 1
@@ -71,17 +72,17 @@ mountfstab_by_jname()
 		_jroot="${data}"
 	fi
 
-	ret=0
+	_ret=0
 
 	if [ -r ${mount_fstab} ]; then
 		mountfstab jroot="${_jroot}" fstab="${mount_fstab}"
-		ret=$?
-		[ ${ret} -ne 0 ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}mountfstab jroot=\"${_jroot}\" fstab=\"${mount_fstab}\"${N0_COLOR}"
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}mountfstab jroot=\"${_jroot}\" fstab=\"${mount_fstab}\"${N0_COLOR}"
 	fi
 	if [ -r ${mount_fstab}.local ]; then
 		mountfstab jroot="${_jroot}" fstab="${mount_fstab}.local"
-		ret=$?
-		[ ${ret} -ne 0 ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}mountfstab jroot=\"${_jroot}\" fstab=\"${mount_fstab}.local\"${N0_COLOR}"
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${W1_COLOR}${CIX_APP} error: ${N1_COLOR}mountfstab jroot=\"${_jroot}\" fstab=\"${mount_fstab}.local\"${N0_COLOR}"
 	fi
 }
 
@@ -98,9 +99,10 @@ if [ -z "${fstab}" -a -z "${jroot}" ]; then
 	if [ -n "${jail_list}" ]; then
 		for jname in ${jail_list}; do
 			mountfstab_by_jname
+			_ret=$?
 		done
 	fi
-	exit ${ret}
+	exit ${_ret}
 fi
 
 [ ! -f "${fstab}" ] && err 1 "${fstab} does not exist"
@@ -278,6 +280,18 @@ ${CAT_CMD} ${fstab} | while read _device _mountpt _fs _mode _a _b; do
 		${_device} -p ${jroot}${_mountpt} -o ${_mode} ${jname}
 		ret=$?
 		[ ${ret} -ne 0 ] && ${ECHO} "${W1_COLOR}${CIX_APP} warning: ${N1_COLOR}unable to create mountpoint via external ${_device}: ${N2_COLOR}${jroot}${_mountpt}${N0_COLOR}"
+		continue
+	fi
+
+	_spec_device=${_device%%/*}
+	echo "SPEC: ${_device} -> ${_spec_device}"
+	# Detect/recognize entries like: 'WORKDIR_VOLUMES/home    /home   nullfs  rw 0 0'
+	# and map to ~cbsd/VOLUMES dataset's
+	if [ "${_spec_device}" = "WORKDIR_VOLUMES" ]; then
+		_rvolpath="${_device#*/}"
+		_volpath="/${_rvolpath}"
+		${ECHO} "${N1_COLOR}${CIX_APP}: WORKDIR_VOLUMES: ${N2_COLOR}${cbsd_workdir}/${jname}/data -> ${_volpath}${N0_COLOR}" 1>&2
+		_device="${workdir}/VOLUMES"
 		continue
 	fi
 
