cbsd natcfg: a little more customization for NAT Rules
a) split RDR/NAT rules per file: ~cbsd/etc/pfnat.conf + ~cbsd/etc/pfrdr.conf:
   this allows to include CBSD rules in general/system /etc/pf.conf config
b) cbsd_nat_skip_natip_network + cbsd_nat_networks settings via cbsd-pf.conf to customization of
   default NAT rules: we can add arbitrary networks instead of RFC1918

These changes make it possible to configure the rules more flexible, for example: Issue #634

diff --git a/tools/naton b/tools/naton
--- a/tools/naton
+++ b/tools/naton
@@ -3,7 +3,31 @@
 MYARG=""
 MYOPTARG="nat"
 MYDESC="Enable NAT service for RFC1918 Networks"
-ADDHELP="nat= name of framework. default in inventory config\n"
+ADDHELP="
+${H3_COLOR}Description${N0_COLOR}:
+
+Enable/apply NAT framework configured via 'cbsd natcfg'
+
+pf firewall notes:
+
+ Also you can re-configure 'cbsd naton' function via ~cbsd/etc/cbsd-pf.conf and switch from
+ internal CBSD 'enable' method to custom.
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}nat${N0_COLOR}    - alternative NAT framework name.
+
+${H3_COLOR}Examples${N0_COLOR}:
+
+ # cbsd naton
+
+${H3_COLOR}See also${N0_COLOR}:
+
+ cbsd natcfg --help
+ cbsd natoff --help
+ cbsd expose --help
+
+"
 
 . ${subrdir}/nc.subr
 
@@ -55,11 +79,23 @@ esac
 
 case "${nat_enable}" in
 	"pf")
-		[ ! -f "${etcdir}/pfnat.conf" ] && err 1 "${N1_COLOR}No pfnat.conf. run ${N2_COLOR}cbsd natcfg${N1_COLOR} first${N0_COLOR}"
-		${KLDSTAT_CMD} -qm pf || ${KLDLOAD_CMD} pf
-		check_nat_ip
-		${PFCTL_CMD} -f ${etcdir}/pfnat.conf
-		${PFCTL_CMD} -e
+		# copy default pf.conf
+		if [ ! -r ${workdir}/etc/pf.conf ]; then
+			cbsdlogger NOTICE ${CBSD_APP}: first CBSD pf run: use ${workdir}/etc/defaults/pf.conf.tpl as template for: ${workdir}/etc/pf.conf
+			${ECHO} "${N1_COLOR}${CBSD_APP}: first CBSD pf run: use ${workdir}/etc/defaults/pf.conf.tpl as template for: ${N2_COLOR}${workdir}/etc/pf.conf${N0_COLOR}"
+			${SED_CMD} -e "s:%%CBSD_WORKDIR%%:${workdir}:g" ${workdir}/etc/defaults/pf.conf.tpl > ${workdir}/etc/pf.conf
+		fi
+
+		[ ! -r ${workdir}/etc/pfnat.conf ] && ${TOUCH_CMD} ${workdir}/etc/pfnat.conf
+		[ ! -r ${workdir}/etc/pfrdr.conf ] && ${TOUCH_CMD} ${workdir}/etc/pfrdr.conf
+
+		readconf cbsd-pf.conf
+		if fn_exists cbsd_external_naton 2>/dev/null; then
+			cbsd_external_naton
+			ret=$?
+		else
+			err 1 "${W1_COLOR}${CBSD_APP} error: ${N1_COLOR}no such cbsd_external_naton() function, please check: ${N2_COLOR}cbsd-pf.conf${N0_COLOR}"
+		fi
 	;;
 	"ipfw")
 		[ ! -f "${etcdir}/ipfw.conf" ] && err 1 "${N1_COLOR}No ipfw.conf. run ${N2_COLOR}cbsd natcfg${N1_COLOR} first${N0_COLOR}"
@@ -76,4 +112,4 @@ case "${nat_enable}" in
 	;;
 esac
 
-exit 0
+exit ${ret}
