improved operation with Free/HBSD bases
get_base: added strict versioning via -v $ver
baseupdate: fix upgrade when hoster version != basejail version, e.g:
  hoster: FreeBSD 13-CURRENT and jails/basejail - 12.0-RELEASE
baseupdate todo: add support to update only specified bases, not all;
cbsd sources and cbsd bases: support for "source" column: store information
  what sources were the data obtained from (srcup,repo,world)

diff --git a/tools/repo b/tools/repo
--- a/tools/repo
+++ b/tools/repo
@@ -122,7 +122,11 @@ register_fetched_base()
 	baseelf=
 	baseelf=$( ${miscdir}/elf_tables --ver ${BASE_DIR}/bin/sh 2>/dev/null )
 
+	local source="${1}"
+	[ -z "${source}" ] && source="unknown"
+
 	[ -z "${baseelf}" ] && baseelf="0"
+	[ -z "${TARGET_ARCH}" ] && TARGET_ARCH="${arch}"
 
 	strpos --str="${ver}" --search="."
 
@@ -133,8 +137,7 @@ register_fetched_base()
 		stable=0
 	fi
 
-	#${ECHO} "${MAGENTA}Register base as: ${GREEN}p=$platform,a=$arch,t=$TARGET_ARCH,v=$ver,s=$stable${NORMAL}"
-	register_base arch=${arch} ver=${ver} target_arch=${TARGET_ARCH} stable=${stable} platform="${platform}"
+	register_base arch=${arch} ver=${ver} target_arch=${TARGET_ARCH} stable=${stable} platform="${platform}" source="${source}"
 }
 
 
@@ -272,8 +275,8 @@ getbase()
 		## Official fbsd repo
 		${ECHO} "${MAGENTA}Looking for official ${platform} mirror:${NORMAL}"
 		ARCHIVE="${MYDIR}/base.txz"
-		for i in ${iso_site}; do
-			fetchme -u ${i} -o ${ARCHIVE}
+		for MIRROR in ${iso_site}; do
+			fetchme -u ${MIRROR} -o ${ARCHIVE}
 			if [ $? -eq 0 ]; then
 				break
 			else
@@ -316,7 +319,7 @@ getbase()
 				fi
 			fi
 			preparebase dst=${BASE_DIR}
-			register_fetched_base
+			register_fetched_base ${MIRROR}
 			# CBSD QUEUE
 			if [ -x "${moduledir}/cbsd_queue.d/cbsd_queue" ]; then
 				baseelf=
@@ -356,72 +359,41 @@ getbase()
 			else
 				_src_found=1
 			fi
-
-#	    fetchme -q1 -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5
-
-#	    if [ $? -ne 0 ]; then
-#		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
-#		continue
-#	    else
-		_srcmd5_found=1
-#	    fi
-	    else
-		${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${NORMAL}"
-		fetchme -o ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${URL_HIER}/base_${basename}.txz
-
-		if [ $? -ne 0 ]; then
-			${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${NORMAL}"
-			continue
+			_srcmd5_found=1
 		else
-			_src_found=1
-		fi
+			${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${NORMAL}"
+			fetchme -o ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz -u ${MYREPO}/releases/${URL_HIER}/base_${basename}.txz
 
-#	    fetchme -q1 -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5
+			if [ $? -ne 0 ]; then
+				${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/releases/${URL_HIER}/base_${basename}.txz${NORMAL}"
+				continue
+			else
+				_src_found=1
+			fi
 
-#	    if [ $? -ne 0 ]; then
-#		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
-#		continue
-#	    else
-		_srcmd5_found=1
-#	    fi
+			_srcmd5_found=1
 		fi
 
 		[ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
 	done
 
-#    if checkmd5 ${MYDIR}; then
-#	${ECHO} "${MAGENTA}MD5 sum:${GREEN} correct${NORMAL}"
-#    else
-#	err 1 "${MAGENTA}MD5 sum: ${GREEN}incorrect${NORMAL}"
-#    fi
-
-#    if [ -z "${basename}" ]; then
-#	rm -f  ${MYDIR}/base_${arch}_${ver}.txz.md5
-#    else
-#	rm -f ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5
-#    fi
-
 	[ ${_src_found} -ne 1 ] && err 1 "${MAGENTA}Not found data${NORMAL}"
 
 	${ECHO} "${MAGENTA}Extracting...${NORMAL}"
 	[ ! -d "${BASE_DIR}" ] && mkdir -p ${BASE_DIR}
-	#/base_${arch}_${ver}
-	cd $BASE_DIR
-	#/base_${arch}_${ver}
+	cd ${BASE_DIR}
 
 	if [ -z "${basename}" ]; then
 		set -e
 		tar xfz ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz
 		set +e
-#		rm -f ${MYDIR}/base_${arch}_${target_arch}_${ver}.txz.md5
 	else
 		set -e
 		tar xfz ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz
 		set +e
-#		rm -f ${MYDIR}/base_${basename}_${arch}_${target_arch}_${ver}.txz.md5
 	fi
 
-	register_fetched_base
+	register_fetched_base ${MIRROR}
 	cleanup_bases
 
 	# CBSD QUEUE
