fixes: for 9.1 cbsdsh, conflict jail with some hostname, locking for buildworld tree on different arch, fetch for one small chunks. pkg.conf update to >=1.1.4

diff --git a/tools/repo b/tools/repo
--- a/tools/repo
+++ b/tools/repo
@@ -1,5 +1,5 @@
 #!/bin/sh
-#v9.2.2
+#v10.0.0
 globalconf="${workdir}/cbsd.conf";
 MYARG="action"
 # action=list,get,put
@@ -87,9 +87,9 @@ getsrc()
 	    ${ECHO} "${MAGENTA}Found new mirror for ${ver}${NORMAL}:${GREEN}${MYREPO}${NORMAL}"
 	fi
 	cbsd cfetch -o ${MYDIR}/src.txz -u ${MYREPO}/${DIR}/src.txz
-	[ $? -eq 0 ] || continue
+	[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz${NORMAL}" && icontinue
 	cbsd cfetch -o ${MYDIR}/src.txz.md5 -u ${MYREPO}/${DIR}/src.txz.md5 >/dev/null 2>&1
-	[ $? -eq 0 ] || continue
+	[ $? -eq 0 ] || ${ECHO} "${MAGENTA}Not found: ${GREEN}${MYREPO}/${DIR}/src.txz.md5${NORMAL}" && continue
     done
 
     [ -f "${MYDIR}/src.txz" -a -f "${MYDIR}/src.txz.md5" ] || err 1 "No sources found"
@@ -115,6 +115,7 @@ getsrc()
 
 getbase()
 {
+    local _srcmd5_found _src_found
 
     if [ -z "${basename}" ]; then
 	BDIR="${basejailpref}_${arch}_${ver}"
@@ -161,6 +162,9 @@ getbase()
     ### Official fbsd repo end ###
     fi
 
+    _srcmd5_found=0
+    _src_found=0
+
     for MYREPO in $REPO; do
 	${ECHO} "${MAGENTA}REPO: ${GREEN}${MYREPO}${NORMAL}"
 	if [ -z "${basename}" ]; then
@@ -179,23 +183,45 @@ getbase()
 	if [ -z "${basename}" ]; then
 	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz${NORMAL}"
 	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz
-	    [ $? -eq 0 ] || continue
+
+	    if [ $? -ne 0 ]; then
+		${ECHO} "${MAGENTA}DBase not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz${NORMAL}"
+		continue
+	    else
+		_src_found=1
+	    fi
+
 	    cbsd cfetch -o ${MYDIR}/base_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5 >/dev/null 2>&1
-	    [ $? -eq 0 ] || continue
+
+	    if [ $? -ne 0 ]; then
+		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
+		continue
+	    else
+		_srcmd5_found=1
+	    fi
 	else
 	    ${ECHO} "${MAGENTA}Looking for: ${GREEN}${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz${NORMAL}"
 	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz
-	    [ $? -eq 0 ] || continue
-	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
-	    [ $? -eq 0 ] || continue
-	fi
-    done
 
-    if [ -z "${basename}" ]; then
-	[ -f "${MYDIR}/base_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/base_${arch}_${ver}.txz" ] || err 1 "${MAGENTA}No such sources: ${GREEN}${MYDIR}/base_${arch}_${ver}.txz.md5 and/or ${MYDIR}/base_${arch}_${ver}.txz${NORMAL}"
-    else
-	[ -f "${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5" -a -f "${MYDIR}/base_${basename}_${arch}_${ver}.txz" ] || err 1 "$MAGENTA}No such sources: ${GREEN}${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5${NORMAL}"
-    fi
+	    if [ $? -ne 0 ]; then
+		${ECHO} "${MAGENTA}Base not found: ${GREEN}${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz${NORMAL}"
+		continue
+	    else
+		_src_found=1
+	    fi
+
+	    cbsd cfetch -o ${MYDIR}/base_${basename}_${arch}_${ver}.txz.md5 -u ${MYREPO}/${DIR}/base_${basename}_${arch}_${ver}.txz.md5 >/dev/null 2>&1
+
+	    if [ $? -ne 0 ]; then
+		${ECHO} "${MAGENTA}MD5 base not found: ${GREEN}${MYREPO}/${DIR}/base_${arch}_${ver}.txz.md5${NORMAL}"
+		continue
+	    else
+		_srcmd5_found=1
+	    fi
+	fi
+
+    [ ${_srcmd5_found} -eq 1 -a ${_src_found} -eq 1 ] && break
+    done
 
     if checkmd5 ${MYDIR}; then
 	${ECHO} "${MAGENTA}MD5 sum:${GREEN} correct${NORMAL}"
