autostart via taskd; autostart support for bhyve VMs

diff --git a/tools/task b/tools/task
--- a/tools/task
+++ b/tools/task
@@ -60,27 +60,27 @@ shift ## mode=xxx
 
 
 case "${mode}" in
-    "new")
-	[ -z "$1" ] && err 1 "${MAGENTA}Command required${NORMAL}"
-	if [ -n "${logfile}" ]; then
-	    _err=$( cbsdsql cbsdtaskd "INSERT INTO taskd ( cmd,status,logfile,logtype,notify,autoflush,owner,after ) VALUES ( \"$@\", 0, \"$logfile\", 0, \"$notify\", \"$autoflush\", \"$owner\", \"$after\" )" )
-	else
-	    _err=$( cbsdsql cbsdtaskd "INSERT INTO taskd ( cmd,status,notify,autoflush,owner,after ) VALUES ( \"$@\", 0, \"$notify\", \"$autoflush\", \"$owner\", \"$after\" )" )
-	fi
+	"new")
+		[ -z "$1" ] && err 1 "${MAGENTA}Command required${NORMAL}"
+		if [ -n "${logfile}" ]; then
+			_err=$( cbsdsql cbsdtaskd "INSERT INTO taskd ( cmd,status,logfile,logtype,notify,autoflush,owner,after ) VALUES ( \"$@\", 0, \"$logfile\", 0, \"$notify\", \"$autoflush\", \"$owner\", \"$after\" )" )
+		else
+			_err=$( cbsdsql cbsdtaskd "INSERT INTO taskd ( cmd,status,notify,autoflush,owner,after ) VALUES ( \"$@\", 0, \"$notify\", \"$autoflush\", \"$owner\", \"$after\" )" )
+		fi
 
-	[ $? -ne 0 ] && err 1 "${MAGENTA}Error: ${_err}${NORMAL}"
-	tid=$( cbsdsql cbsdtaskd "SELECT id FROM taskd WHERE cmd=\"$@\" AND status=0 ORDER BY id DESC LIMIT 1" )
-	[ -z "${tid}" ] && err 1 "${MAGENTA}Error: ${_err}${NORMAL}"
-	${ECHO} "${MAGENTA}Queued: ${GREEN}${tid}${NORMAL}"
-	;;
-    "cancel")
-    ;;
-    "cancelall")
-    ;;
-    "flushall")
-	for i in $( cbsdsql cbsdtaskd SELECT logfile FROM taskd WHERE status='2' ); do
-	    [ -f "${i}" ] && rm -f "${i}"
-	done
-	cbsdsql cbsdtaskd DELETE FROM taskd WHERE status='2'
-	;;
+		[ $? -ne 0 ] && err 1 "${MAGENTA}Error: ${_err}${NORMAL}"
+		tid=$( cbsdsql cbsdtaskd "SELECT id FROM taskd WHERE cmd=\"$@\" AND status=0 ORDER BY id DESC LIMIT 1" )
+		[ -z "${tid}" ] && err 1 "${MAGENTA}Error: ${_err}${NORMAL}"
+		${ECHO} "${MAGENTA}Queued: ${GREEN}${tid}${NORMAL}"
+		;;
+	"cancel")
+		;;
+	"cancelall")
+		;;
+	"flushall")
+		for i in $( cbsdsql cbsdtaskd SELECT logfile FROM taskd WHERE status='2' ); do
+			[ -f "${i}" ] && rm -f "${i}"
+		done
+		cbsdsql cbsdtaskd DELETE FROM taskd WHERE status='2'
+		;;
 esac
