WIP: jscp,service,sysrc,pkg: support for CBSDfile/api

diff --git a/tools/up b/tools/up
--- a/tools/up
+++ b/tools/up
@@ -26,6 +26,9 @@ CLOUD_KEY=
 [ -z "${multiple}" ] && multiple=0
 [ -z "${cur_env}" ] && cur_env=1
 
+# skip notice for subcommand with CBSDfile/API
+export CBSDFILE_RECURSIVE=1
+
 # init CBSDfile data
 if [ -n "${cwd}" ]; then
 	[ ! -r ${cwd}/CBSDfile ] && err 1 "${N1_COLOR}${CBSD_APP}: no such CBSDfile: ${N2_COLOR}${cwd}/CBSDfile${N0_COLOR}"
@@ -74,6 +77,47 @@ bhyve_ssh_wait()
 	return 0
 }
 
+jail_ssh_wait()
+{
+	local _orig_options _ret
+	_orig_options=$( set +o )
+
+	# disable errexit/xtrace settings for a while..
+	set +o xtrace
+	set +o errexit
+
+	local _attempt_max=60 _i _x _y
+	readconf cbsdfile.conf
+	if [ -n "${jail_ssh_wait_timeout}" ]; then
+		_attempt_max="${jail_ssh_wait_timeout}"
+	fi
+
+	${ECHO} "${N1_COLOR}waiting jail ssh (${_attempt_max}s): ${N2_COLOR}${jname}${N0_COLOR}"
+	# wait for VM boot
+	_y=2		# test for timeout exceed
+	for _i in $( ${SEQ_CMD} 1 ${_attempt_max} ); do
+		_x=$( timeout 10 cbsd jexec jname=${jname} date > /dev/null 2>&1 )
+		_ret=$?
+		[ ${_ret} -eq 0 ] && break
+		_y=$(( _y + 1 ))
+		sleep 1
+		# todo: delete only ip
+		${ARP_CMD} -d -n ${ci_ip4_addr} > /dev/null 2>&1
+		if [ ${_y} -eq ${_attempt_max} ]; then
+			# restore old settings
+			set ${_orig_options}
+			return 1
+		fi
+	done
+
+	${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
+	# restore old settings
+	set ${_orig_options}
+
+	return 0
+}
+
+
 # testing/wip
 run_jail_cloud()
 {
@@ -88,6 +132,7 @@ run_jail_cloud()
   "ram": "${vm_ram}",
   "cpus": "${vm_cpus}",
   "img": "${img}",
+  "pkglist": "${pkglist}",
   "pubkey": "${CLOUD_KEY}"
 }
 EOF
@@ -99,6 +144,43 @@ EOF
 	./deploy-${jname}.sh
 	# without debug
 	${RM_CMD} -f ./deploy-${jname}.sh ./up-${jname}.json
+
+	if [ ${ssh_wait} -eq 1 ]; then
+		jail_ssh_wait
+		ret=$?
+	else
+		ret=0
+	fi
+	if [ ${ret} -eq 0 ]; then
+		${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
+
+		#bhyve_${jname}		# re-read variables
+
+		if fn_exists postcreate_${jname} 2>/dev/null; then
+			${ECHO} "${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+			# cleanup bhyve when postcreate action failed
+			trap "set +o xtrace; ${ECHO} \"${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}: ${W1_COLOR}failed${N1_COLOR} : cleanup${N0_COLOR}\" 1>&2  ; jremove ${jname}" HUP INT ABRT BUS TERM EXIT
+			set -o errexit
+			set -o xtrace
+			postcreate_${jname}
+			set +o xtrace
+			set +o errexit
+			trap "" HUP INT ABRT BUS TERM EXIT
+			${ECHO} "${N1_COLOR}  == execute postcreate function for: ${N2_COLOR}${jname}: ${H3_COLOR}success${N0_COLOR}" 1>&2
+		else
+			${ECHO} "${N1_COLOR}  == postcreate function not specified: postcreate_${N2_COLOR}${jname}${N0_COLOR}" 1>&2
+		fi
+
+		jname="${ojname}"
+		# per-env postup func
+		if fn_exists postup_${jname} 2>/dev/null; then
+			${ECHO} "${N1_COLOR}execute postup_${jname}${N0_COLOR}"
+			postup_${jname}
+			jname="${ojname}"		# for corrupted/changed jname in func
+		fi
+	else
+		[ ${ssh_wait} -eq 1 ] && err 1 "${N1_COLOR}ssh failed${N0_COLOR}"
+	fi
 	return 0
 }
 
