up: turn off xtrace/errexit for ssh_wait in postaction

diff --git a/tools/up b/tools/up
--- a/tools/up
+++ b/tools/up
@@ -39,6 +39,13 @@ imgtype=
 
 bhyve_ssh_wait()
 {
+	local _orig_options
+	_orig_options=$( set +o )
+
+	# disable errexit/xtrace settings for a while..
+	set +o xtrace
+	set +o errexit
+
 	local _attempt_max=60 _i _x _y
 
 	${ECHO} "${N1_COLOR}waiting VM ssh (${_attempt_max}): ${N2_COLOR}${jname}...${N0_COLOR}"
@@ -51,8 +58,16 @@ bhyve_ssh_wait()
 		sleep 1
 		# todo: delete only ip
 		${ARP_CMD} -d -n ${ci_ip4_addr} > /dev/null 2>&1
-		[ ${_y} -eq ${_attempt_max} ] && return 1
+		if [ ${_y} -eq ${_attempt_max} ]; then
+			# restore old settings
+			set ${_orig_options}
+			return 1
+		fi
 	done
+
+	${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
+	# restore old settings
+	set ${_orig_options}
 
 	return 0
 }
@@ -136,8 +151,12 @@ run_bhyve()
 	# restore old workdir
 	cbsd_workdir="${ocbsd_workdir}"
 
-	bhyve_ssh_wait
-	ret=$?
+	if [ ${ssh_wait} -eq 1 ]; then
+		bhyve_ssh_wait
+		ret=$?
+	else
+		ret=0
+	fi
 	if [ ${ret} -eq 0 ]; then
 		${ECHO} "${N1_COLOR}ssh available${N0_COLOR}"
 		bhyve_${jname}		# re-read variables
@@ -156,10 +175,10 @@ run_bhyve()
 		else
 			${ECHO} "${N1_COLOR}  == postcreate function not specified: postcreate_${N2_COLOR}${jname}${N0_COLOR}" 1>&2
 		fi
-
 	else
-		${ECHO} "${N1_COLOR}ssh failed${N0_COLOR}"
+		[ ${ssh_wait} -eq 1 ] && err 1 "${N1_COLOR}ssh failed${N0_COLOR}"
 	fi
+	return 0
 }
 
 # MAIN
