xen: sync code with bhyve

diff --git a/tools/xen-dsk b/tools/xen-dsk
--- a/tools/xen-dsk
+++ b/tools/xen-dsk
@@ -1,7 +1,7 @@
 #!/usr/local/bin/cbsd
 #v12.0.14
 MYARG="mode"
-MYOPTARG="jname dsk_controller dsk_path dsk_size bootable display header"
+MYOPTARG="jname dsk_controller dsk_path dsk_size bootable display header zvol_opts"
 MYDESC="Manage XEN disks"
 CBSDMODULE="xen"
 EXTHELP="wf_xen"
@@ -14,6 +14,8 @@ ADDHELP="mode=attach,detach,remove,list,modify\n\
  modify properties:\n\
   - bootable - set bootable flag (1 - true, - false)\n\
   - dsk_zfs_guid - can be: 'auto'\n\
+ mode=attach properties:\n\
+  zvol_opts - pass ZFS volume options, e.g: zvol_opts=\"dedup=on sync=disabled\"\n\
  mode=list properties:\n\
   header=0 don't print header\n\
   display= list by comma for column. Default: jname,dsk_controller,dsk_path,dsk_size,bootable,dsk_iops_limit,dsk_mbps_limit\n\
@@ -26,6 +28,7 @@ ADDHELP="mode=attach,detach,remove,list,modify\n\
 bootable=
 dsk_iops_limit=
 dsk_mbps_limit=
+zvol_opts=
 . ${cbsdinit}
 
 available_properties="bootable dsk_zfs_guid"
@@ -37,7 +40,7 @@ available_get_properties="dsk_path bootable dsk_sectorsize dsk_zfs_guid"
 
 dsk_attach()
 {
-	local _val _ret
+	local _val _ret _zvol_opts _zvol_args
 
 	if [ -z "${dsk_sectorsize}" ]; then
 		readconf xen-default-default.conf
@@ -67,7 +70,7 @@ dsk_attach()
 					xvd|sd|hd)
 						;;
 					*)
-						err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}xen-dsk: unknown dsk_controller ${_val}, valid: ${N1_COLOR}xvd, sd, hd${N0_COLOR}"
+						err 1 "${N1_COLOR}xen-dsk error: xen-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}xvd, sd, hd${N0_COLOR}"
 						;;
 				esac
 				;;
@@ -76,8 +79,25 @@ dsk_attach()
 		[ -z "${_val}" ] && err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}${i}= ${N1_COLOR}is mandatory${N0_COLOR}"
 	done
 
-	add_dsk -c "${dsk_controller}" -d "${dsk_path}" -s "${dsk_size}" -z "${dsk_sectorsize}"
-	_ret=$?
+	if [ -n "${zvol_opts}" ]; then
+		for i in ${zvol_opts}; do
+			if [ -z "${_zvol_opts}" ]; then
+				_zvol_opts="-o ${i}"
+			else
+				_zvol_opts="${_zvol_opts} -o ${i}"
+			fi
+		done
+	else
+		_zvol_opts=
+	fi
+
+	if [ -n "${_zvol_opts}" ]; then
+		add_dsk -c "${dsk_controller}" -d "${dsk_path}" -s "${dsk_size}" -z "${dsk_sectorsize}" -o "${_zvol_opts}"
+		_ret=$?
+	else
+		add_dsk -c "${dsk_controller}" -d "${dsk_path}" -s "${dsk_size}" -z "${dsk_sectorsize}"
+		_ret=$?
+	fi
 	if [ ${_ret} -eq 0 ]; then
 		${ECHO} "${N2_COLOR}${dsk_path}${N1_COLOR} attached${N0_COLOR}"
 	else
@@ -107,7 +127,7 @@ dsk_detach()
 					xvd|sd|hd)
 						;;
 					*)
-						err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}xen-dsk: unknown dsk_controller ${_val}, valid: ${N1_COLOR}xvd, sd, hd${N0_COLOR}"
+						err 1 "${N1_COLOR}xen-dsk error: xen-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}xvd, sd, hd${N0_COLOR}"
 						;;
 				esac
 				;;
@@ -149,7 +169,7 @@ dsk_delete()
 					xvd|sd|hd)
 						;;
 					*)
-						err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}xen-dsk: unknown dsk_controller ${_val}, valid: ${N1_COLOR}xvd, sd, hd${N0_COLOR}"
+						err 1 "${N1_COLOR}xen-dsk error: xen-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}xvd, sd, hd${N0_COLOR}"
 						;;
 				esac
 				;;
@@ -190,7 +210,7 @@ dsk_modify_bootable()
 					xvd|sd|hd)
 						;;
 					*)
-						err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}xen-dsk: unknown dsk_controller ${_val}, valid: ${N1_COLOR}xvd, sd, hd${N0_COLOR}"
+						err 1 "${N1_COLOR}xen-dsk error: xen-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}xvd, sd, hd${N0_COLOR}"
 						;;
 				esac
 				;;
@@ -265,7 +285,7 @@ dsk_modify_dsk_sectorsize()
 					xvd|sd|hd)
 						;;
 					*)
-						err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}xen-dsk: unknown dsk_controller ${_val}, valid: ${N1_COLOR}xvd, sd, hd${N0_COLOR}"
+						err 1 "${N1_COLOR}xen-dsk error: xen-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}xvd, sd, hd${N0_COLOR}"
 						;;
 				esac
 				;;
@@ -309,7 +329,7 @@ dsk_modify_dsk_zfs_guid()
 					xvd|sd|hd)
 						;;
 					*)
-						err 1 "${N1_COLOR}xen-dsk error: ${N2_COLOR}xen-dsk: unknown dsk_controller ${_val}, valid: ${N1_COLOR}xvd, sd, hd${N0_COLOR}"
+						err 1 "${N1_COLOR}xen-dsk error: xen-dsk: unknown dsk_controller ${_val}, valid: ${N2_COLOR}xvd, sd, hd${N0_COLOR}"
 						;;
 				esac
 				;;
