began to restore zfs-migrator: step 2/many

diff --git a/tools/zfs-migrator b/tools/zfs-migrator
--- a/tools/zfs-migrator
+++ b/tools/zfs-migrator
@@ -669,6 +669,9 @@ if [ ${full} -eq 1 ]; then
 			j2prepare node=${node} jname=${jname} mkdatadir=1 tryoffline=1
 			ret=$?
 			[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: error: ${N2_COLOR}cbsd j2prepare node=${node} jname=${jname} mkdatadir=1 tryoffline=1${N0_COLOR}"
+			j2slave node=${node} jname=${jname} tryoffline=1
+			ret=$?
+			[ ${ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: error, no cbsdrsyncd service enabled on remote host?: ${N2_COLOR}j2slave node=${node} jname=${jname} tryoffline=1${N0_COLOR}"
 			;;
 	esac
 
